--------------------------------------------------------
--  DDL for Table AGING_INVT_SHIP_VAL
--------------------------------------------------------

  CREATE TABLE "AGING_INVT_SHIP_VAL" 
   (	"PRODUCT_CODE" VARCHAR2(16), 
	"SOLD_COST_BEFORE_SEP_2002" NUMBER, 
	"SOLD_PRICE_BEFORE_SEP_2002" NUMBER, 
	"SOLD_COST_RCVD_IN_2003" NUMBER, 
	"SOLD_PRICE_RCVD_IN_2003" NUMBER, 
	"SOLD_COST_RCVD_IN_2004" NUMBER, 
	"SOLD_PRICE_RCVD_IN_2004" NUMBER, 
	"SOLD_COST_RCVD_IN_2005" NUMBER, 
	"SOLD_PRICE_RCVD_IN_2005" NUMBER, 
	"SOLD_COST_RCVD_IN_2006" NUMBER, 
	"SOLD_PRICE_RCVD_IN_2006" NUMBER, 
	"SOLD_COST_RCVD_IN_2007" NUMBER, 
	"SOLD_PRICE_RCVD_IN_2007" NUMBER, 
	"SOLD_COST_RCVD_IN_2008" NUMBER, 
	"SOLD_PRICE_RCVD_IN_2008" NUMBER
   ) ;
