--------------------------------------------------------
--  DDL for Table DEMO_CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "DEMO_CUSTOMERS" 
   (	"CUSTOMER_ID" NUMBER, 
	"CUST_FIRST_NAME" VARCHAR2(20), 
	"CUST_LAST_NAME" VARCHAR2(20), 
	"CUST_STREET_ADDRESS1" VARCHAR2(60), 
	"CUST_STREET_ADDRESS2" VARCHAR2(60), 
	"CUST_CITY" VARCHAR2(30), 
	"CUST_STATE" VARCHAR2(2), 
	"CUST_POSTAL_CODE" VARCHAR2(10), 
	"PHONE_NUMBER1" VARCHAR2(25), 
	"PHONE_NUMBER2" VARCHAR2(25), 
	"CREDIT_LIMIT" NUMBER(9,2), 
	"CUST_EMAIL" VARCHAR2(30)
   ) ;
