--------------------------------------------------------
--  DDL for Table SALES_CALL_DTL
--------------------------------------------------------

  CREATE TABLE "SALES_CALL_DTL" 
   (	"SALES_CALL_DTL_NBR" NUMBER(9,0), 
	"SALES_LEAD_NBR" NUMBER(9,0), 
	"CALL_DT" DATE, 
	"INDIV_NBR_CALL" NUMBER(9,0), 
	"NA_CATEGORY_NBR" NUMBER(9,0), 
	"IC_CATEGORY_NBR" NUMBER(9,0), 
	"ITEM_CD_MASK" VARCHAR2(50), 
	"CAUSE_OF_ACTIVITY" VARCHAR2(50), 
	"CUST_NM" VARCHAR2(60), 
	"ORG_NBR_CUST" NUMBER(9,0), 
	"ADDR_NBR" NUMBER(9,0), 
	"INDIV_NBR_CALLED" NUMBER(9,0), 
	"INDUSTRY_TYPE" VARCHAR2(50), 
	"PRIMARY_PRODUCT_MANF" VARCHAR2(50), 
	"USING_PRINCIPAL_FLG" VARCHAR2(1), 
	"COMPETITION" VARCHAR2(512), 
	"ANNUAL_DMD_AMT" NUMBER(10,2), 
	"ANNUAL_DMD_QTY" NUMBER(8,0), 
	"PROD_START_DT" DATE, 
	"EXPECTED_DURATION_MNTHS" NUMBER(3,0)
   ) ;
