--------------------------------------------------------
--  DDL for Table VND_RTRN_DTL
--------------------------------------------------------

  CREATE TABLE "VND_RTRN_DTL" 
   (	"VND_RTRN_HDR_NBR" NUMBER(9,0), 
	"VND_RTRN_DTL_NBR" NUMBER(9,0), 
	"VND_RTRN_LINE_NBR" NUMBER(3,0), 
	"LOT_NBR_RTRN" NUMBER(9,0), 
	"LOT_UM" VARCHAR2(3), 
	"QTY_RTRN" NUMBER(13,5), 
	"QTY_DISPOSITION" NUMBER(13,5), 
	"QTY_CREDIT" NUMBER(13,5), 
	"UNIT_COST_CREDIT" NUMBER(17,6), 
	"UNIT_COST_DENOM_CREDIT" NUMBER(17,6), 
	"DISP_CD" VARCHAR2(8), 
	"SHIP_VIA_CD" VARCHAR2(8), 
	"WAYBILL_CD" VARCHAR2(20), 
	"CHARGE_CD" VARCHAR2(10), 
	"CHARGE_AMT" NUMBER(10,2), 
	"ADJ_CD" VARCHAR2(8), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"CHARGE_AMT_DENOM" NUMBER(10,2), 
	"RTRN_REASON_CD" VARCHAR2(8)
   ) ;
