--------------------------------------------------------
--  DDL for Table WH_FACILITY_TRANS_SHIP
--------------------------------------------------------

  CREATE TABLE "WH_FACILITY_TRANS_SHIP" 
   (	"WH_FACILITY_TRANS_SHIP_NBR" NUMBER(9,0), 
	"WH_PICK_BATCH_TRANS_NBR" NUMBER(9,0), 
	"FACILITY_SRC" VARCHAR2(16), 
	"FACILITY_DEST" VARCHAR2(16), 
	"SHIP_VIA_CD" VARCHAR2(8), 
	"SHIP_DT" DATE, 
	"EST_ARRIVAL_DT" DATE, 
	"BIN_NBR_TRANSIT" NUMBER(9,0), 
	"WAYBILL_CD" VARCHAR2(20), 
	"SHIP_STAT_ID" VARCHAR2(1), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE
   ) ;

   COMMENT ON COLUMN "WH_FACILITY_TRANS_SHIP"."SHIP_STAT_ID" IS 'O-Open S-Shipped, R-Received, P-Processed';
