--------------------------------------------------------
--  DDL for Table AGING_INVT_VAL
--------------------------------------------------------

  CREATE TABLE "INTERFAST"."AGING_INVT_VAL" 
   (	"PRODUCT_CODE" VARCHAR2(16 BYTE), 
	"HOME_VAL" NUMBER, 
	"RCVD_BEFORE_30_SEP_2002" NUMBER, 
	"RCVD_IN_2003" NUMBER, 
	"RCVD_IN_2004" NUMBER, 
	"RCVD_IN_2005" NUMBER, 
	"RCVD_IN_2006" NUMBER, 
	"RCVD_IN_2007" NUMBER, 
	"RCVD_IN_2008" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
