--------------------------------------------------------
--  DDL for Table APS_ALLOC_DELETE_LOG
--------------------------------------------------------

  CREATE TABLE "INTERFAST"."APS_ALLOC_DELETE_LOG" 
   (	"DELETE_DT" DATE, 
	"APS_ALLOC_ONHAND_NBR" NUMBER(9,0), 
	"DMD_KEY" NUMBER(9,0), 
	"LOT_NBR" NUMBER(9,0), 
	"ALLOC_QTY" NUMBER(13,5), 
	"APS_SPLY_SUB_POOL_NBR" NUMBER(9,0), 
	"SUBST_ID" VARCHAR2(1 BYTE), 
	"FACILITY_RQST" VARCHAR2(16 BYTE), 
	"FACILITY_ACT" VARCHAR2(16 BYTE), 
	"ITEM_NBR_RQST" NUMBER(9,0), 
	"UNIT_PRICE_SELL_UM" NUMBER(17,6), 
	"UNIT_PRICE_DENOM_SELL_UM" NUMBER(17,6), 
	"UNIT_PRICE_STK_UM" NUMBER(17,6), 
	"UNIT_PRICE_DENOM_STK_UM" NUMBER(17,6), 
	"ALLOC_TYPE_ID" VARCHAR2(1 BYTE), 
	"WH_FACILITY_TRANS_ONHAND_NBR" NUMBER(9,0), 
	"AVAIL_DT" DATE, 
	"AVAIL_DT_TYPE_ID" VARCHAR2(1 BYTE), 
	"DMD_TYPE" VARCHAR2(2 BYTE), 
	"LOG_COMM" VARCHAR2(1000 BYTE), 
	"NOTIFY_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 31457280 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
