REM INSERTING into AERODEMO.APS_SRC_RULE_REPLEN
SET DEFINE OFF;
Insert into AERODEMO.APS_SRC_RULE_REPLEN (APS_SRC_RULE_SET_NBR,APS_SRC_RULE_NBR) values (183,455);
Insert into AERODEMO.APS_SRC_RULE_REPLEN (APS_SRC_RULE_SET_NBR,APS_SRC_RULE_NBR) values (176,414);
