--------------------------------------------------------
--  DDL for Table APS_SPLY_FACILITY_ITEM
--------------------------------------------------------

  CREATE TABLE "INTERFAST"."APS_SPLY_FACILITY_ITEM" 
   (	"APS_SPLY_SUB_POOL_NBR" NUMBER(9,0), 
	"FACILITY" VARCHAR2(16 BYTE), 
	"ITEM_NBR" NUMBER(9,0), 
	"UNALLOC_CUST_ORD_DT" DATE, 
	"ALLOC_LATE_CUST_ORD_DT" DATE, 
	"UNALLOC_FCST_DT" DATE, 
	"ALLOC_LATE_FCST_DT" DATE, 
	"UNALLOC_REPLEN_DT" DATE, 
	"RESCHED_REPLEN_IN_DAYS" NUMBER(3,0), 
	"RESCHED_REPLEN_OUT_DAYS" NUMBER(3,0), 
	"ONHAND_QTY" NUMBER(11,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
