REM INSERTING into AERODEMO.FAKE_INDIV_NM
SET DEFINE OFF;
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Xin Guan');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Rika Ruiz');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('YUANYUAN GU');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Linda Pellerin');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('DANIELE BLANCHARD');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Mike Blinn');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('LEE CHIDESTER');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Julie Casha');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Nathalie Leduc');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('MARVIN FENSTER');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('ISABELLE PHANEUF');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('CHRISTIEN FORGET');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('FRANK ONG');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('ss');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('DOMINIQUE NORMAND');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('MIKE STONEMAN');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Maya Lisonova');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('GEORGE');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Mie Horiuchi');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Beverley Doran');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Manon');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('M.DELASABLONNIERE');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Serge Belisle');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Lee');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Yi Han Chen');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('aram k');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Cheryl L. Peoples');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('GRANT BELL');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Sabrina Brusco');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('JEAN BRUNDAGE');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Sandra Morton');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('LI YANG');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Angie Bozzer');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('TERESA BORRELLI');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Kelly');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('ROBERT WEIR');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('LAURA CADENA');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('MIKE S');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Mike');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('DEREK WHITE');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Mike Griego');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('SONYA');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('BRAD BUELL');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('neil');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Bob Zacharias');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('AKIKO EVANS');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Misato Yoshikawa');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Bill Allison');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('MARK');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('DONALD COLLIN');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Eric Bergoin');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Bob Brown');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Steve Paghal');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('DANIEL RAYMOND');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Debora Costantion');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('BRENDA SHULER');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('DAVID AMBTMAN');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Y.S.Hong Y.S.Hong');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('STEVE');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('KRIS PERSAUD X221');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values (null);
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Natalie Hamilton');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Juhi Somal');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('ELAINE');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('JEFF SCHNUCKER');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('HJ Kim HJ Kim');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Lysette Taylor');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('PATRICK ROMANO');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('CHRIS');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('June Ewald');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Jason');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Gregg Rosenblatt');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('MARC SAVIGNAC');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Zoran Mitrovski');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Byran Shantz');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Gail Torres');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('RONALD THIELEMANN');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Kelly Reger');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Nathan Matsui');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Amélie Trevisan');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('JOE COLETTI');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Valen Yang');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('CHARLEEN HANLAN');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('SUSAN HOU');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('MICHAEL');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('PATRICK LANKHORST');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('TERRY BORRELLI');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('TAKU HIRANO');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Deb Nelson');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Addiel Norris');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('IGOR INDOLFI');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Shannon');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Wendy Bowering');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('LESIA BULCHAK');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Anna Zdzieba');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Teresa (Terry) Borrelli');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('JENNIFER  SMITH');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Eric Hackler');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('SUSAN RENTERIA');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('ANDY LIU');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('PAULA  ALMEIDA');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Jim Kuramoto');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('STEPHANIE AGUIAR');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('ARTURO VIGANO');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('ISABELLE PHANEUF/ ANDREE-ANNE');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Sebina Deir');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('SABINO MICHELE IERONIMO');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Renata Ljubic');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('MAYUMI HAMMETT');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Bryan Shantz');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('DAVID MONTE');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Ludwig Siket');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Chris Searcy');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('carol');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('CAROLE CHARTRAND');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('JOSE CASTENADA');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Popocatl');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('VALERIE LEBLANC');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Jennifer Smith');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('CONNIE GRAND');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Mark Dellamattia');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('DAVE HORCH');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Debora Costantino');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('LARRY BRATTON');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('Scott Moffat');
Insert into AERODEMO.FAKE_INDIV_NM (INDIV_NM) values ('DEBORA CONSTANTINO');
