REM INSERTING into AERODEMO.FCST_GRP
SET DEFINE OFF;
Insert into AERODEMO.FCST_GRP (FCST_GRP,FCST_GRP_DESCR,UT_USER_NBR,LAST_MOD_DT,OO_PRTY,WO_PRTY,SS_PRTY,FC_PRTY) values ('CLCORE','CLEVELAND CORE',1,to_date('22-DEC-06','DD-MON-RR'),20,1,30,60);
Insert into AERODEMO.FCST_GRP (FCST_GRP,FCST_GRP_DESCR,UT_USER_NBR,LAST_MOD_DT,OO_PRTY,WO_PRTY,SS_PRTY,FC_PRTY) values ('MTJITS','MONTREAL JITS',1,to_date('22-DEC-06','DD-MON-RR'),7,1,12,59);
Insert into AERODEMO.FCST_GRP (FCST_GRP,FCST_GRP_DESCR,UT_USER_NBR,LAST_MOD_DT,OO_PRTY,WO_PRTY,SS_PRTY,FC_PRTY) values ('VCJITS','VANCOUVER JITS',1,to_date('22-DEC-06','DD-MON-RR'),4,1,13,60);
Insert into AERODEMO.FCST_GRP (FCST_GRP,FCST_GRP_DESCR,UT_USER_NBR,LAST_MOD_DT,OO_PRTY,WO_PRTY,SS_PRTY,FC_PRTY) values ('USJITS','USA JITS',1,to_date('22-DEC-06','DD-MON-RR'),3,1,8,56);
Insert into AERODEMO.FCST_GRP (FCST_GRP,FCST_GRP_DESCR,UT_USER_NBR,LAST_MOD_DT,OO_PRTY,WO_PRTY,SS_PRTY,FC_PRTY) values ('MTCORE','MONTREAL CORE',1,to_date('22-DEC-06','DD-MON-RR'),20,1,52,63);
Insert into AERODEMO.FCST_GRP (FCST_GRP,FCST_GRP_DESCR,UT_USER_NBR,LAST_MOD_DT,OO_PRTY,WO_PRTY,SS_PRTY,FC_PRTY) values ('VCCORE','VANCOUVER CORE',1,to_date('22-DEC-06','DD-MON-RR'),20,1,51,62);
Insert into AERODEMO.FCST_GRP (FCST_GRP,FCST_GRP_DESCR,UT_USER_NBR,LAST_MOD_DT,OO_PRTY,WO_PRTY,SS_PRTY,FC_PRTY) values ('TOCORE','TORONTO CORE',1,to_date('22-DEC-06','DD-MON-RR'),20,1,30,61);
Insert into AERODEMO.FCST_GRP (FCST_GRP,FCST_GRP_DESCR,UT_USER_NBR,LAST_MOD_DT,OO_PRTY,WO_PRTY,SS_PRTY,FC_PRTY) values ('OTCORE','OTTAWA CORE',1,to_date('22-DEC-06','DD-MON-RR'),20,1,53,64);
Insert into AERODEMO.FCST_GRP (FCST_GRP,FCST_GRP_DESCR,UT_USER_NBR,LAST_MOD_DT,OO_PRTY,WO_PRTY,SS_PRTY,FC_PRTY) values ('USCORE','USA CORE',1,to_date('22-DEC-06','DD-MON-RR'),20,1,54,65);
Insert into AERODEMO.FCST_GRP (FCST_GRP,FCST_GRP_DESCR,UT_USER_NBR,LAST_MOD_DT,OO_PRTY,WO_PRTY,SS_PRTY,FC_PRTY) values ('TMP','TEMPORARY',18,to_date('19-MAR-05','DD-MON-RR'),97,96,98,99);
Insert into AERODEMO.FCST_GRP (FCST_GRP,FCST_GRP_DESCR,UT_USER_NBR,LAST_MOD_DT,OO_PRTY,WO_PRTY,SS_PRTY,FC_PRTY) values ('OTJITS','OTTAWA JITS',1,to_date('22-DEC-06','DD-MON-RR'),5,1,11,58);
Insert into AERODEMO.FCST_GRP (FCST_GRP,FCST_GRP_DESCR,UT_USER_NBR,LAST_MOD_DT,OO_PRTY,WO_PRTY,SS_PRTY,FC_PRTY) values ('TOJITS','TORONTO JITS',1,to_date('22-DEC-06','DD-MON-RR'),6,1,10,57);
Insert into AERODEMO.FCST_GRP (FCST_GRP,FCST_GRP_DESCR,UT_USER_NBR,LAST_MOD_DT,OO_PRTY,WO_PRTY,SS_PRTY,FC_PRTY) values ('WPJITS','Winnipeg JITS',13,to_date('26-MAY-08','DD-MON-RR'),2,1,9,56);
Insert into AERODEMO.FCST_GRP (FCST_GRP,FCST_GRP_DESCR,UT_USER_NBR,LAST_MOD_DT,OO_PRTY,WO_PRTY,SS_PRTY,FC_PRTY) values ('BRAD','For BRAD only-DO NOT USE ELSEWHERE',1,to_date('22-DEC-06','DD-MON-RR'),20,1,55,66);
Insert into AERODEMO.FCST_GRP (FCST_GRP,FCST_GRP_DESCR,UT_USER_NBR,LAST_MOD_DT,OO_PRTY,WO_PRTY,SS_PRTY,FC_PRTY) values ('FLCORE','FLORIDA CUSTOMERS',1,to_date('22-DEC-06','DD-MON-RR'),20,1,55,66);
Insert into AERODEMO.FCST_GRP (FCST_GRP,FCST_GRP_DESCR,UT_USER_NBR,LAST_MOD_DT,OO_PRTY,WO_PRTY,SS_PRTY,FC_PRTY) values ('MICORE','MIAMI CUSTOMERS',1,to_date('22-DEC-06','DD-MON-RR'),20,1,55,66);
