--------------------------------------------------------
--  File created - Sunday-January-26-2020   
--------------------------------------------------------
@/common/home/jjs/papsdemo/AGING_INVT_SHIP_VAL.sql
@/common/home/jjs/papsdemo/AGING_INVT_VAL.sql
@/common/home/jjs/papsdemo/APP_CTL.sql
@/common/home/jjs/papsdemo/APS_ALLOC_DELETE_LOG.sql
@/common/home/jjs/papsdemo/APS_ALLOC_ONHAND_FC.sql
@/common/home/jjs/papsdemo/APS_ALLOC_ONHAND_OO.sql
@/common/home/jjs/papsdemo/APS_ALLOC_ONHAND_SS.sql
@/common/home/jjs/papsdemo/APS_ALLOC_ONHAND_WO.sql
@/common/home/jjs/papsdemo/APS_ALLOC_REPLEN_FC.sql
@/common/home/jjs/papsdemo/APS_ALLOC_REPLEN_OO.sql
@/common/home/jjs/papsdemo/APS_ALLOC_REPLEN_SS.sql
@/common/home/jjs/papsdemo/APS_ALLOC_REPLEN_WO.sql
@/common/home/jjs/papsdemo/APS_ALLOC_WO_FC.sql
@/common/home/jjs/papsdemo/APS_ALLOC_WO_OO.sql
@/common/home/jjs/papsdemo/APS_ALLOC_WO_SS.sql
@/common/home/jjs/papsdemo/APS_ALLOC_WO_WO.sql
@/common/home/jjs/papsdemo/APS_CTL.sql
@/common/home/jjs/papsdemo/APS_DMD_RULE_SET_ITEM.sql
@/common/home/jjs/papsdemo/APS_ITEM_GLOBAL_SUBST.sql
@/common/home/jjs/papsdemo/APS_ITEM_LOG.sql
@/common/home/jjs/papsdemo/APS_PLAN_GRP.sql
@/common/home/jjs/papsdemo/APS_RESULT_DTL_DEL.sql
@/common/home/jjs/papsdemo/APS_RESULT_DTL_DMD.sql
@/common/home/jjs/papsdemo/APS_RESULT_DTL_SPLY.sql
@/common/home/jjs/papsdemo/APS_RQST_QUEUE.sql
@/common/home/jjs/papsdemo/APS_SCENARIO.sql
@/common/home/jjs/papsdemo/APS_SPLY_FACILITY_ITEM.sql
@/common/home/jjs/papsdemo/APS_SPLY_POOL.sql
@/common/home/jjs/papsdemo/APS_SPLY_SUB_POOL.sql
