--------------------------------------------------------
--  File created - Sunday-January-26-2020   
--------------------------------------------------------
@/common/home/jjs/papsdemo/AIL_BACK_DATA_TABLE.sql
@/common/home/jjs/papsdemo/ALLOC_STATS_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APP_CTL_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APP_CTL2_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_ALLOC_DELETE_LOG_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_ALLOC_NBR_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_ALLOC_ONHAND_FC_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_ALLOC_ONHAND_OO_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_ALLOC_ONHAND_SS_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_ALLOC_ONHAND_WO_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_ALLOC_REPLEN_FC_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_ALLOC_REPLEN_OO_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_ALLOC_REPLEN_SS_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_ALLOC_REPLEN_WO_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_ALLOC_WO_FC_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_ALLOC_WO_OO_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_ALLOC_WO_SS_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_ALLOC_WO_WO_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_CTL_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_DISPATCH_QUEUE_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_IDEAL_GLOBAL_REPLEN_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_ITEM_GLOBAL_SUBST_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_ITEM_LOG_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_ITEM_REPLEN_POLICY_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_PLAN_GRP_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_RESULT_DTL_DMD_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_RESULT_DTL_SPLY_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_RQST_QUEUE_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_SPLY_POOL_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_SPLY_SUB_POOL_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_SRC_RULE_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_SRC_RULE_PRIMARY_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_SRC_RULE_REPLEN_DATA_TABLE.sql
@/common/home/jjs/papsdemo/APS_SRC_RULE_SET_DATA_TABLE.sql
@/common/home/jjs/papsdemo/AR_INV_DTL_DATA_TABLE.sql
@/common/home/jjs/papsdemo/AR_INV_HDR_DATA_TABLE.sql
@/common/home/jjs/papsdemo/AR_RMA_DTL_DATA_TABLE.sql
@/common/home/jjs/papsdemo/AR_RMA_RCPT_DATA_TABLE.sql
@/common/home/jjs/papsdemo/CAL_CALENDAR_DATA_TABLE.sql
@/common/home/jjs/papsdemo/CAL_DT_DATA_TABLE.sql
@/common/home/jjs/papsdemo/CAL_HOLIDAY_DATA_TABLE.sql
@/common/home/jjs/papsdemo/CURRENCY_DATA_TABLE.sql
@/common/home/jjs/papsdemo/CURSOR_EXPLAIN_PLAN_DATA_TABLE.sql
@/common/home/jjs/papsdemo/CURSOR_INFO_DATA_TABLE.sql
@/common/home/jjs/papsdemo/CURSOR_INFO_RUN_DATA_TABLE.sql
@/common/home/jjs/papsdemo/CURSOR_SQL_TEXT_DATA_TABLE.sql
@/common/home/jjs/papsdemo/CURSOR_STAT_DATA_TABLE.sql
@/common/home/jjs/papsdemo/DEBUG_TABLE_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FAKE_DATE_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FAKE_EMAILS_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FAKE_INDIV_NM_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FAKE_NAMES_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FAKE_ORG_NM_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FAKE_PHN_NBRS_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FCST_GRP_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FCST_REPORT_DTL_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_ADJ_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_AGGR_MAST_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_AGGR_MAST_ATTR_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_AGGR_MAST_DTL_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_ATTR_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_ATTR_VAL_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_BUILD_RATE_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_BUILD_RATE_GRP_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_CTL_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_DTL_TMP_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_FCST_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_FCST_AGGR_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_FCST_BAK_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_FCST_BUCKET_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_FCST_MDL_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_FCST_MDL_GRP_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_FCST_MDL_GRP_HDR_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_FCST_MDL_OLD_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_FCST_PRD_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_FCST_PRD_OLD_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_FCST_XX_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_HDR_TMP_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_HIST_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_HIST_DIST_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_ITEM_ATTR_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_ITEM_DFLT_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_ITEM_FCST_MDL_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_ITEM_MAST_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_ITEM_MAST_DTL_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_ITEM_UNFORECASTABLE_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FC_QUEUE_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FIM_ATTR_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FIM_ATTRS_DATA_TABLE.sql
@/common/home/jjs/papsdemo/FIM_MSG_DATA_TABLE.sql
@/common/home/jjs/papsdemo/IC_ATTR_DATA_TABLE.sql
@/common/home/jjs/papsdemo/IC_ATTR_VAL_DATA_TABLE.sql
@/common/home/jjs/papsdemo/IC_ATTR_VAL_BAK_DATA_TABLE.sql
@/common/home/jjs/papsdemo/IC_BIN_DATA_TABLE.sql
@/common/home/jjs/papsdemo/IC_BOM_DATA_TABLE.sql
@/common/home/jjs/papsdemo/IC_BOM_CERT_DATA_TABLE.sql
@/common/home/jjs/papsdemo/IC_CATEGORY_DATA_TABLE.sql
@/common/home/jjs/papsdemo/IC_CATEGORY_OLD_DATA_TABLE.sql
@/common/home/jjs/papsdemo/IC_CERT_CD_DATA_TABLE.sql
@/common/home/jjs/papsdemo/IC_ITEM_ATTR_DATA_TABLE.sql
@/common/home/jjs/papsdemo/IC_ITEM_ATTR_BAK_DATA_TABLE.sql
@/common/home/jjs/papsdemo/IC_ITEM_COST_DATA_TABLE.sql
@/common/home/jjs/papsdemo/IC_ITEM_CUST_SUBST_DATA_TABLE.sql
@/common/home/jjs/papsdemo/IC_ITEM_LOC_DATA_TABLE.sql
@/common/home/jjs/papsdemo/IC_ITEM_LOC_BOX_DATA_TABLE.sql
