REM INSERTING into AERODEMO.IC_ITEM_COST
SET DEFINE OFF;
Insert into AERODEMO.IC_ITEM_COST (ITEM_NBR,COST_TYPE_CD,UNIT_COST,COST_CALC_DT,UT_USER_NBR,LAST_MOD_DT) values (53519,'DICTATED_COST',0.72,to_date('20-MAY-17','DD-MON-RR'),13,to_date('09-JUN-17','DD-MON-RR'));
Insert into AERODEMO.IC_ITEM_COST (ITEM_NBR,COST_TYPE_CD,UNIT_COST,COST_CALC_DT,UT_USER_NBR,LAST_MOD_DT) values (53518,'DICTATED_COST',0.69,to_date('20-MAY-17','DD-MON-RR'),13,to_date('09-JUN-17','DD-MON-RR'));
Insert into AERODEMO.IC_ITEM_COST (ITEM_NBR,COST_TYPE_CD,UNIT_COST,COST_CALC_DT,UT_USER_NBR,LAST_MOD_DT) values (33793,'DICTATED_COST',0.69,to_date('20-MAY-17','DD-MON-RR'),18,to_date('20-MAY-17','DD-MON-RR'));
Insert into AERODEMO.IC_ITEM_COST (ITEM_NBR,COST_TYPE_CD,UNIT_COST,COST_CALC_DT,UT_USER_NBR,LAST_MOD_DT) values (33794,'DICTATED_COST',0.72,to_date('20-MAY-17','DD-MON-RR'),18,to_date('20-MAY-17','DD-MON-RR'));
Insert into AERODEMO.IC_ITEM_COST (ITEM_NBR,COST_TYPE_CD,UNIT_COST,COST_CALC_DT,UT_USER_NBR,LAST_MOD_DT) values (91886,'DICTATED_COST',2.8925,to_date('27-NOV-16','DD-MON-RR'),13,to_date('27-NOV-16','DD-MON-RR'));
