REM INSERTING into INTERFAST.IC_UM_CNVT_ITEM
SET DEFINE OFF;
Insert into INTERFAST.IC_UM_CNVT_ITEM (ITEM_NBR,UM_ID_FROM,UM_ID_TO,UM_CNVT_FACT_ITEM,UT_USER_NBR,LAST_MOD_DT) values (31313,'EA','PD',754,85,to_date('10-JUN-03','DD-MON-RR'));
Insert into INTERFAST.IC_UM_CNVT_ITEM (ITEM_NBR,UM_ID_FROM,UM_ID_TO,UM_CNVT_FACT_ITEM,UT_USER_NBR,LAST_MOD_DT) values (59922,'EA','FT',1,4,to_date('01-OCT-03','DD-MON-RR'));
Insert into INTERFAST.IC_UM_CNVT_ITEM (ITEM_NBR,UM_ID_FROM,UM_ID_TO,UM_CNVT_FACT_ITEM,UT_USER_NBR,LAST_MOD_DT) values (70716,'FT','EA',1,4,to_date('04-DEC-03','DD-MON-RR'));
Insert into INTERFAST.IC_UM_CNVT_ITEM (ITEM_NBR,UM_ID_FROM,UM_ID_TO,UM_CNVT_FACT_ITEM,UT_USER_NBR,LAST_MOD_DT) values (70715,'FT','EA',1,4,to_date('08-JAN-04','DD-MON-RR'));
Insert into INTERFAST.IC_UM_CNVT_ITEM (ITEM_NBR,UM_ID_FROM,UM_ID_TO,UM_CNVT_FACT_ITEM,UT_USER_NBR,LAST_MOD_DT) values (229119,'EA','FT',32,4,to_date('17-AUG-04','DD-MON-RR'));
Insert into INTERFAST.IC_UM_CNVT_ITEM (ITEM_NBR,UM_ID_FROM,UM_ID_TO,UM_CNVT_FACT_ITEM,UT_USER_NBR,LAST_MOD_DT) values (229119,'FT','FT',0.375,4,to_date('17-AUG-04','DD-MON-RR'));
Insert into INTERFAST.IC_UM_CNVT_ITEM (ITEM_NBR,UM_ID_FROM,UM_ID_TO,UM_CNVT_FACT_ITEM,UT_USER_NBR,LAST_MOD_DT) values (195087,'EA','PD',703,1,to_date('05-JUL-04','DD-MON-RR'));
Insert into INTERFAST.IC_UM_CNVT_ITEM (ITEM_NBR,UM_ID_FROM,UM_ID_TO,UM_CNVT_FACT_ITEM,UT_USER_NBR,LAST_MOD_DT) values (70714,'FT','EA',1,4,to_date('08-JUN-05','DD-MON-RR'));
Insert into INTERFAST.IC_UM_CNVT_ITEM (ITEM_NBR,UM_ID_FROM,UM_ID_TO,UM_CNVT_FACT_ITEM,UT_USER_NBR,LAST_MOD_DT) values (127480,'EA','IN',6,4,to_date('03-AUG-05','DD-MON-RR'));
