REM INSERTING into INTERFAST.IC_UM_HDR
SET DEFINE OFF;
Insert into INTERFAST.IC_UM_HDR (UM_FAMILY,UM_FAMILY_DESCR,UT_USER_NBR,LAST_MOD_DT) values ('COUNT','Counts',1,to_date('02-JUL-01','DD-MON-RR'));
Insert into INTERFAST.IC_UM_HDR (UM_FAMILY,UM_FAMILY_DESCR,UT_USER_NBR,LAST_MOD_DT) values ('LENGTH','Length measurement',1,to_date('11-SEP-01','DD-MON-RR'));
Insert into INTERFAST.IC_UM_HDR (UM_FAMILY,UM_FAMILY_DESCR,UT_USER_NBR,LAST_MOD_DT) values ('WEIGHT','Weights',1,to_date('26-SEP-01','DD-MON-RR'));
