package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Allocs generated by hbm2java
 */
@Entity
@Table(name="ALLOCS"
)
public class Allocs  implements java.io.Serializable {


     private AllocsId id;

    public Allocs() {
    }

    public Allocs(AllocsId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="type", column=@Column(name="TYPE", length=5) ), 
        @AttributeOverride(name="itemNbrRqst", column=@Column(name="ITEM_NBR_RQST", precision=9, scale=0) ), 
        @AttributeOverride(name="demandPk", column=@Column(name="DEMAND_PK", precision=9, scale=0) ), 
        @AttributeOverride(name="supplyPk", column=@Column(name="SUPPLY_PK", precision=9, scale=0) ), 
        @AttributeOverride(name="apsSplySubPoolNbr", column=@Column(name="APS_SPLY_SUB_POOL_NBR", precision=22, scale=0) ), 
        @AttributeOverride(name="facilityRqst", column=@Column(name="FACILITY_RQST", length=16) ), 
        @AttributeOverride(name="facilityAct", column=@Column(name="FACILITY_ACT", length=16) ), 
        @AttributeOverride(name="substId", column=@Column(name="SUBST_ID", length=1) ), 
        @AttributeOverride(name="allocQty", column=@Column(name="ALLOC_QTY", precision=13, scale=5) ), 
        @AttributeOverride(name="whFacilityTransNbr", column=@Column(name="WH_FACILITY_TRANS_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="availDtTypeId", column=@Column(name="AVAIL_DT_TYPE_ID", length=1) ) } )
    public AllocsId getId() {
        return this.id;
    }
    
    public void setId(AllocsId id) {
        this.id = id;
    }




}


