package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AllocStats generated by hbm2java
 */
@Entity
@Table(name="ALLOC_STATS"
)
public class AllocStats  implements java.io.Serializable {


     private AllocStatsId id;

    public AllocStats() {
    }

    public AllocStats(AllocStatsId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="nbrOoOld", column=@Column(name="NBR_OO_OLD", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrOoNew", column=@Column(name="NBR_OO_NEW", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrWoOld", column=@Column(name="NBR_WO_OLD", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrWoNew", column=@Column(name="NBR_WO_NEW", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrSsOld", column=@Column(name="NBR_SS_OLD", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrSsNew", column=@Column(name="NBR_SS_NEW", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrFcOld", column=@Column(name="NBR_FC_OLD", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrFcNew", column=@Column(name="NBR_FC_NEW", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrOoAllocFullOld", column=@Column(name="NBR_OO_ALLOC_FULL_OLD", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrOoAllocFullNew", column=@Column(name="NBR_OO_ALLOC_FULL_NEW", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrWoAllocFullOld", column=@Column(name="NBR_WO_ALLOC_FULL_OLD", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrWoAllocFullNew", column=@Column(name="NBR_WO_ALLOC_FULL_NEW", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrSsAllocFullOld", column=@Column(name="NBR_SS_ALLOC_FULL_OLD", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrSsAllocFullNew", column=@Column(name="NBR_SS_ALLOC_FULL_NEW", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrFcAllocFullOld", column=@Column(name="NBR_FC_ALLOC_FULL_OLD", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrFcAllocFullNew", column=@Column(name="NBR_FC_ALLOC_FULL_NEW", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrOoUnallocOld", column=@Column(name="NBR_OO_UNALLOC_OLD", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrOoUnallocNew", column=@Column(name="NBR_OO_UNALLOC_NEW", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrWoUnallocOld", column=@Column(name="NBR_WO_UNALLOC_OLD", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrWoUnallocNew", column=@Column(name="NBR_WO_UNALLOC_NEW", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrSsUnallocOld", column=@Column(name="NBR_SS_UNALLOC_OLD", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrSsUnallocNew", column=@Column(name="NBR_SS_UNALLOC_NEW", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrFcUnallocOld", column=@Column(name="NBR_FC_UNALLOC_OLD", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrFcUnallocNew", column=@Column(name="NBR_FC_UNALLOC_NEW", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrOoAllocFullOntimeOld", column=@Column(name="NBR_OO_ALLOC_FULL_ONTIME_OLD", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrOoAllocFullOntimeNew", column=@Column(name="NBR_OO_ALLOC_FULL_ONTIME_NEW", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrWoAllocFullOntimeOld", column=@Column(name="NBR_WO_ALLOC_FULL_ONTIME_OLD", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrWoAllocFullOntimeNew", column=@Column(name="NBR_WO_ALLOC_FULL_ONTIME_NEW", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrSsAllocFullOntimeOld", column=@Column(name="NBR_SS_ALLOC_FULL_ONTIME_OLD", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrSsAllocFullOntimeNew", column=@Column(name="NBR_SS_ALLOC_FULL_ONTIME_NEW", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrFcAllocFullOntimeOld", column=@Column(name="NBR_FC_ALLOC_FULL_ONTIME_OLD", precision=9, scale=0) ), 
        @AttributeOverride(name="nbrFcAllocFullOntimeNew", column=@Column(name="NBR_FC_ALLOC_FULL_ONTIME_NEW", precision=9, scale=0) ) } )
    public AllocStatsId getId() {
        return this.id;
    }
    
    public void setId(AllocStatsId id) {
        this.id = id;
    }




}


