package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ApsAllocReplenFc generated by hbm2java
 */
@Entity
@Table(name="APS_ALLOC_REPLEN_FC"
)
public class ApsAllocReplenFc  implements java.io.Serializable, AllocReplen {


     private int apsAllocReplenFcNbr;
     private WhFacilityTransReplen whFacilityTransReplen;
     private IcItemMast icItemMast;
     private int fcFcstNbr;
     private int poLineDtlNbr;
     private BigDecimal allocQty;
     private String substId;
     private String facilityRqst;
     private String facilityAct;
     private String allocTypeId;
	private int apsSplySubPoolNbr;

    public ApsAllocReplenFc() {
    }

   
     @Id 

    
    @Column(name="APS_ALLOC_REPLEN_FC_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getApsAllocReplenFcNbr() {
        return this.apsAllocReplenFcNbr;
    }
    
    public void setApsAllocReplenFcNbr(int apsAllocReplenFcNbr) {
        this.apsAllocReplenFcNbr = apsAllocReplenFcNbr;
    }

/* (non-Javadoc)
 * @see com.pacificdataservices.diamond.models.AllocReplen#getWhFacilityTransReplen()
 */
@Override
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WH_FACILITY_TRANS_REPLEN_NBR")
    public WhFacilityTransReplen getWhFacilityTransReplen() {
        return this.whFacilityTransReplen;
    }
    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocReplen#setWhFacilityTransReplen(com.pacificdataservices.diamond.models.WhFacilityTransReplen)
	 */
    @Override
	public void setWhFacilityTransReplen(WhFacilityTransReplen whFacilityTransReplen) {
        this.whFacilityTransReplen = whFacilityTransReplen;
    }

/* (non-Javadoc)
 * @see com.pacificdataservices.diamond.models.AllocReplen#getIcItemMast()
 */
@Override
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR_RQST", nullable=false)
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocReplen#setIcItemMast(com.pacificdataservices.diamond.models.IcItemMast)
	 */
    @Override
	public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }

    
    @Column(name="FC_FCST_NBR", nullable=false, precision=9, scale=0)
    public int getFcFcstNbr() {
        return this.fcFcstNbr;
    }
    
    public void setFcFcstNbr(int fcFcstNbr) {
        this.fcFcstNbr = fcFcstNbr;
    }

    
    @Column(name="PO_LINE_DTL_NBR", nullable=false, precision=9, scale=0)
    public int getPoLineDtlNbr() {
        return this.poLineDtlNbr;
    }
    
    public void setPoLineDtlNbr(int poLineDtlNbr) {
        this.poLineDtlNbr = poLineDtlNbr;
    }

    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocReplen#getAllocQty()
	 */
    @Override
	@Column(name="ALLOC_QTY", nullable=false, precision=13, scale=5)
    public BigDecimal getAllocQty() {
        return this.allocQty;
    }
    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocReplen#setAllocQty(java.math.BigDecimal)
	 */
    @Override
	public void setAllocQty(BigDecimal allocQty) {
        this.allocQty = allocQty;
    }

    
    @Column(name="SUBST_ID", length=1)
    public String getSubstId() {
        return this.substId;
    }
    
    public void setSubstId(String substId) {
        this.substId = substId;
    }

    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocReplen#getFacilityRqst()
	 */
    @Override
	@Column(name="FACILITY_RQST", nullable=false, length=16)
    public String getFacilityRqst() {
        return this.facilityRqst;
    }
    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocReplen#setFacilityRqst(java.lang.String)
	 */
    @Override
	public void setFacilityRqst(String facilityRqst) {
        this.facilityRqst = facilityRqst;
    }

    
    @Column(name="FACILITY_ACT", nullable=false, length=16)
    public String getFacilityAct() {
        return this.facilityAct;
    }
    
    public void setFacilityAct(String facilityAct) {
        this.facilityAct = facilityAct;
    }

    
    @Column(name="ALLOC_TYPE_ID", nullable=false, length=1)
    public String getAllocTypeId() {
        return this.allocTypeId;
    }
    
    public void setAllocTypeId(String allocTypeId) {
        this.allocTypeId = allocTypeId;
    }

    @Column(name="APS_SPLY_SUB_POOL_NBR", nullable=false, precision=9, scale=0)
    public int getApsSplySubPoolNbr() {
    	return this.apsSplySubPoolNbr;
    }
    
	@Override
	public void setApsSplySubPoolNbr(Integer apsSplySubPoolNbr) {
		this.apsSplySubPoolNbr = apsSplySubPoolNbr;
	}


}


