package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApsAllocOnhandFc generated by hbm2java
 */
@Entity
@Table(name="APS_ALLOC_ONHAND_FC"
)
public class ApsAllocOnhandFc  implements java.io.Serializable, AllocOnhand {


     private int apsAllocOnhandFcNbr;
     private WhFacilityTransOnhand whFacilityTransOnhand;
     private IcItemMast icItemMast;
     private int fcFcstNbr;
     private int lotNbr;
     private BigDecimal allocQty;
     private int apsSplySubPoolNbr;
     private String substId;
     private String facilityRqst;
     private String facilityAct;
     private String allocTypeId;
     private Date availDt;
     private String availDtTypeId;

    public ApsAllocOnhandFc() {
    }

   
     @Id 

    
    @Column(name="APS_ALLOC_ONHAND_FC_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getApsAllocOnhandFcNbr() {
        return this.apsAllocOnhandFcNbr;
    }
    
    public void setApsAllocOnhandFcNbr(int apsAllocOnhandFcNbr) {
        this.apsAllocOnhandFcNbr = apsAllocOnhandFcNbr;
    }

/* (non-Javadoc)
 * @see com.pacificdataservices.diamond.models.AllocOnhand#getWhFacilityTransOnhand()
 */
@Override
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WH_FACILITY_TRANS_ONHAND_NBR")
    public WhFacilityTransOnhand getWhFacilityTransOnhand() {
        return this.whFacilityTransOnhand;
    }
    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocOnhand#setWhFacilityTransOnhand(com.pacificdataservices.diamond.models.WhFacilityTransOnhand)
	 */
    @Override
	public void setWhFacilityTransOnhand(WhFacilityTransOnhand whFacilityTransOnhand) {
        this.whFacilityTransOnhand = whFacilityTransOnhand;
    }

/* (non-Javadoc)
 * @see com.pacificdataservices.diamond.models.AllocOnhand#getIcItemMast()
 */
@Override
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR_RQST", nullable=false)
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocOnhand#setIcItemMast(com.pacificdataservices.diamond.models.IcItemMast)
	 */
    @Override
	public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }

    
    @Column(name="FC_FCST_NBR", nullable=false, precision=9, scale=0)
    public int getFcFcstNbr() {
        return this.fcFcstNbr;
    }
    
    public void setFcFcstNbr(int fcFcstNbr) {
        this.fcFcstNbr = fcFcstNbr;
    }

    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocOnhand#getLotNbr()
	 */
    @Override
	@Column(name="LOT_NBR", nullable=false, precision=9, scale=0)
    public int getLotNbr() {
        return this.lotNbr;
    }
    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocOnhand#setLotNbr(int)
	 */
    @Override
	public void setLotNbr(int lotNbr) {
        this.lotNbr = lotNbr;
    }

    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocOnhand#getAllocQty()
	 */
    @Override
	@Column(name="ALLOC_QTY", nullable=false, precision=13, scale=5)
    public BigDecimal getAllocQty() {
        return this.allocQty;
    }
    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocOnhand#setAllocQty(java.math.BigDecimal)
	 */
    @Override
	public void setAllocQty(BigDecimal allocQty) {
        this.allocQty = allocQty;
    }

    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocOnhand#getApsSplySubPoolNbr()
	 */
    @Override
	@Column(name="APS_SPLY_SUB_POOL_NBR", nullable=false, precision=9, scale=0)
    public int getApsSplySubPoolNbr() {
        return this.apsSplySubPoolNbr;
    }
    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocOnhand#setApsSplySubPoolNbr(int)
	 */
    @Override
	public void setApsSplySubPoolNbr(int apsSplySubPoolNbr) {
        this.apsSplySubPoolNbr = apsSplySubPoolNbr;
    }

    
    @Column(name="SUBST_ID", length=1)
    public String getSubstId() {
        return this.substId;
    }
    
    public void setSubstId(String substId) {
        this.substId = substId;
    }

    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocOnhand#getFacilityRqst()
	 */
    @Override
	@Column(name="FACILITY_RQST", nullable=false, length=16)
    public String getFacilityRqst() {
        return this.facilityRqst;
    }
    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocOnhand#setFacilityRqst(java.lang.String)
	 */
    @Override
	public void setFacilityRqst(String facilityRqst) {
        this.facilityRqst = facilityRqst;
    }

    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocOnhand#getFacilityAct()
	 */
    @Override
	@Column(name="FACILITY_ACT", nullable=false, length=16)
    public String getFacilityAct() {
        return this.facilityAct;
    }
    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocOnhand#setFacilityAct(java.lang.String)
	 */
    @Override
	public void setFacilityAct(String facilityAct) {
        this.facilityAct = facilityAct;
    }

    
    @Column(name="ALLOC_TYPE_ID", nullable=false, length=1)
    public String getAllocTypeId() {
        return this.allocTypeId;
    }
    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocOnhand#setAllocTypeId(java.lang.String)
	 */
    @Override
	public void setAllocTypeId(String allocTypeId) {
        this.allocTypeId = allocTypeId;
    }

    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocOnhand#getAvailDt()
	 */
    @Override
	@Temporal(TemporalType.DATE)
    @Column(name="AVAIL_DT", nullable=false, length=7)
    public Date getAvailDt() {
        return this.availDt;
    }
    
    /* (non-Javadoc)
	 * @see com.pacificdataservices.diamond.models.AllocOnhand#setAvailDt(java.util.Date)
	 */
    @Override
	public void setAvailDt(Date availDt) {
        this.availDt = availDt;
    }

    
    @Column(name="AVAIL_DT_TYPE_ID", nullable=false, length=1)
    public String getAvailDtTypeId() {
        return this.availDtTypeId;
    }
    
    public void setAvailDtTypeId(String availDtTypeId) {
        this.availDtTypeId = availDtTypeId;
    }




}


