package com.pacificdataservices.diamond.models;
// Generated Mar 21, 2019 5:50:00 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ApsAllocDeleteLog generated by hbm2java
 */
@Entity
@Table(name="APS_ALLOC_DELETE_LOG"
)
public class ApsAllocDeleteLog  implements java.io.Serializable {


     private ApsAllocDeleteLogId id;

    public ApsAllocDeleteLog() {
    }

    public ApsAllocDeleteLog(ApsAllocDeleteLogId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="deleteDt", column=@Column(name="DELETE_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="apsAllocOnhandNbr", column=@Column(name="APS_ALLOC_ONHAND_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="dmdKey", column=@Column(name="DMD_KEY", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="lotNbr", column=@Column(name="LOT_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="allocQty", column=@Column(name="ALLOC_QTY", nullable=false, precision=13, scale=5) ), 
        @AttributeOverride(name="apsSplySubPoolNbr", column=@Column(name="APS_SPLY_SUB_POOL_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="substId", column=@Column(name="SUBST_ID", length=1) ), 
        @AttributeOverride(name="facilityRqst", column=@Column(name="FACILITY_RQST", nullable=false, length=16) ), 
        @AttributeOverride(name="facilityAct", column=@Column(name="FACILITY_ACT", nullable=false, length=16) ), 
        @AttributeOverride(name="itemNbrRqst", column=@Column(name="ITEM_NBR_RQST", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="unitPriceSellUm", column=@Column(name="UNIT_PRICE_SELL_UM", precision=17, scale=6) ), 
        @AttributeOverride(name="unitPriceDenomSellUm", column=@Column(name="UNIT_PRICE_DENOM_SELL_UM", precision=17, scale=6) ), 
        @AttributeOverride(name="unitPriceStkUm", column=@Column(name="UNIT_PRICE_STK_UM", precision=17, scale=6) ), 
        @AttributeOverride(name="unitPriceDenomStkUm", column=@Column(name="UNIT_PRICE_DENOM_STK_UM", precision=17, scale=6) ), 
        @AttributeOverride(name="allocTypeId", column=@Column(name="ALLOC_TYPE_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="whFacilityTransOnhandNbr", column=@Column(name="WH_FACILITY_TRANS_ONHAND_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="availDt", column=@Column(name="AVAIL_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="availDtTypeId", column=@Column(name="AVAIL_DT_TYPE_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="dmdType", column=@Column(name="DMD_TYPE", nullable=false, length=2) ), 
        @AttributeOverride(name="logComm", column=@Column(name="LOG_COMM", length=1000) ), 
        @AttributeOverride(name="notifyDt", column=@Column(name="NOTIFY_DT", length=7) ) } )
    public ApsAllocDeleteLogId getId() {
        return this.id;
    }
    
    public void setId(ApsAllocDeleteLogId id) {
        this.id = id;
    }




}


