package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApsAvailOnhand generated by hbm2java
 */
@Entity
@Table(name="APS_AVAIL_ONHAND"
)
public class ApsAvailOnhand  implements java.io.Serializable {


     private String splyIdentifier;
     private String facility;
     private int apsSplySubPoolNbr;
     private Integer orgNbrMfr;
     private int orgNbrVnd;
     private int lotNbr;
     private String lotUm;
     private int itemNbr;
     private Date availDt;
     private BigDecimal grossAvailQty;
     private String revLvl;
     private int pkSupply;
     private BigDecimal lotCost;
     private String cntryCdOrigin;
     private Date mfrDate;
     private Date expireDt;
     private Date rcptDt;
     private String availDtId;

    public ApsAvailOnhand() {
    }

	
    public ApsAvailOnhand(String splyIdentifier, String facility, int apsSplySubPoolNbr, int orgNbrVnd, int lotNbr, String lotUm, int itemNbr, int pkSupply, BigDecimal lotCost) {
        this.splyIdentifier = splyIdentifier;
        this.facility = facility;
        this.apsSplySubPoolNbr = apsSplySubPoolNbr;
        this.orgNbrVnd = orgNbrVnd;
        this.lotNbr = lotNbr;
        this.lotUm = lotUm;
        this.itemNbr = itemNbr;
        this.pkSupply = pkSupply;
        this.lotCost = lotCost;
    }
    public ApsAvailOnhand(String splyIdentifier, String facility, int apsSplySubPoolNbr, Integer orgNbrMfr, int orgNbrVnd, int lotNbr, String lotUm, int itemNbr, Date availDt, BigDecimal grossAvailQty, String revLvl, int pkSupply, BigDecimal lotCost, String cntryCdOrigin, Date mfrDate, Date expireDt, Date rcptDt, String availDtId) {
       this.splyIdentifier = splyIdentifier;
       this.facility = facility;
       this.apsSplySubPoolNbr = apsSplySubPoolNbr;
       this.orgNbrMfr = orgNbrMfr;
       this.orgNbrVnd = orgNbrVnd;
       this.lotNbr = lotNbr;
       this.lotUm = lotUm;
       this.itemNbr = itemNbr;
       this.availDt = availDt;
       this.grossAvailQty = grossAvailQty;
       this.revLvl = revLvl;
       this.pkSupply = pkSupply;
       this.lotCost = lotCost;
       this.cntryCdOrigin = cntryCdOrigin;
       this.mfrDate = mfrDate;
       this.expireDt = expireDt;
       this.rcptDt = rcptDt;
       this.availDtId = availDtId;
    }
   
     @Id 

    
    @Column(name="SPLY_IDENTIFIER", nullable=false, length=108)
    public String getSplyIdentifier() {
        return this.splyIdentifier;
    }
    
    public void setSplyIdentifier(String splyIdentifier) {
        this.splyIdentifier = splyIdentifier;
    }

    
    @Column(name="FACILITY", nullable=false, length=16)
    public String getFacility() {
        return this.facility;
    }
    
    public void setFacility(String facility) {
        this.facility = facility;
    }

    
    @Column(name="APS_SPLY_SUB_POOL_NBR", nullable=false, precision=9, scale=0)
    public int getApsSplySubPoolNbr() {
        return this.apsSplySubPoolNbr;
    }
    
    public void setApsSplySubPoolNbr(int apsSplySubPoolNbr) {
        this.apsSplySubPoolNbr = apsSplySubPoolNbr;
    }

    
    @Column(name="ORG_NBR_MFR", precision=9, scale=0)
    public Integer getOrgNbrMfr() {
        return this.orgNbrMfr;
    }
    
    public void setOrgNbrMfr(Integer orgNbrMfr) {
        this.orgNbrMfr = orgNbrMfr;
    }

    
    @Column(name="ORG_NBR_VND", nullable=false, precision=9, scale=0)
    public int getOrgNbrVnd() {
        return this.orgNbrVnd;
    }
    
    public void setOrgNbrVnd(int orgNbrVnd) {
        this.orgNbrVnd = orgNbrVnd;
    }

    
    @Column(name="LOT_NBR", nullable=false, precision=9, scale=0)
    public int getLotNbr() {
        return this.lotNbr;
    }
    
    public void setLotNbr(int lotNbr) {
        this.lotNbr = lotNbr;
    }

    
    @Column(name="LOT_UM", nullable=false, length=3)
    public String getLotUm() {
        return this.lotUm;
    }
    
    public void setLotUm(String lotUm) {
        this.lotUm = lotUm;
    }

    
    @Column(name="ITEM_NBR", nullable=false, precision=9, scale=0)
    public int getItemNbr() {
        return this.itemNbr;
    }
    
    public void setItemNbr(int itemNbr) {
        this.itemNbr = itemNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="AVAIL_DT", length=7)
    public Date getAvailDt() {
        return this.availDt;
    }
    
    public void setAvailDt(Date availDt) {
        this.availDt = availDt;
    }

    
    @Column(name="GROSS_AVAIL_QTY", precision=22, scale=0)
    public BigDecimal getGrossAvailQty() {
        return this.grossAvailQty;
    }
    
    public void setGrossAvailQty(BigDecimal grossAvailQty) {
        this.grossAvailQty = grossAvailQty;
    }

    
    @Column(name="REV_LVL", length=5)
    public String getRevLvl() {
        return this.revLvl;
    }
    
    public void setRevLvl(String revLvl) {
        this.revLvl = revLvl;
    }

    
    @Column(name="PK_SUPPLY", nullable=false, precision=9, scale=0)
    public int getPkSupply() {
        return this.pkSupply;
    }
    
    public void setPkSupply(int pkSupply) {
        this.pkSupply = pkSupply;
    }

    
    @Column(name="LOT_COST", nullable=false, precision=13, scale=6)
    public BigDecimal getLotCost() {
        return this.lotCost;
    }
    
    public void setLotCost(BigDecimal lotCost) {
        this.lotCost = lotCost;
    }

    
    @Column(name="CNTRY_CD_ORIGIN", length=3)
    public String getCntryCdOrigin() {
        return this.cntryCdOrigin;
    }
    
    public void setCntryCdOrigin(String cntryCdOrigin) {
        this.cntryCdOrigin = cntryCdOrigin;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MFR_DATE", length=7)
    public Date getMfrDate() {
        return this.mfrDate;
    }
    
    public void setMfrDate(Date mfrDate) {
        this.mfrDate = mfrDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXPIRE_DT", length=7)
    public Date getExpireDt() {
        return this.expireDt;
    }
    
    public void setExpireDt(Date expireDt) {
        this.expireDt = expireDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RCPT_DT", length=7)
    public Date getRcptDt() {
        return this.rcptDt;
    }
    
    public void setRcptDt(Date rcptDt) {
        this.rcptDt = rcptDt;
    }

    
    @Column(name="AVAIL_DT_ID", length=1)
    public String getAvailDtId() {
        return this.availDtId;
    }
    
    public void setAvailDtId(String availDtId) {
        this.availDtId = availDtId;
    }




}


