package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ApsAllocReplenOo generated by hbm2java
 */
@Entity
@Table(name="APS_ALLOC_REPLEN_OO"
)
public class ApsAllocReplenOo  implements java.io.Serializable, AllocReplen {


     private int apsAllocReplenOoNbr;
     private WhFacilityTransReplen whFacilityTransReplen;
     private IcItemMast icItemMast;
     private int oeOrdDtlNbr;
     private int poLineDtlNbr;
     private BigDecimal allocQty;
     private String substId;
     private String facilityRqst;
     private String facilityAct;
     private BigDecimal unitPriceSellUm;
     private BigDecimal unitPriceDenomSellUm;
     private BigDecimal unitPriceStkUm;
     private BigDecimal unitPriceDenomStkUm;
     private String allocTypeId;
	private int apsSplySubPoolNbr;

    public ApsAllocReplenOo() {
    }

	
     @Id 

    
    @Column(name="APS_ALLOC_REPLEN_OO_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getApsAllocReplenOoNbr() {
        return this.apsAllocReplenOoNbr;
    }
    
    public void setApsAllocReplenOoNbr(int apsAllocReplenOoNbr) {
        this.apsAllocReplenOoNbr = apsAllocReplenOoNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WH_FACILITY_TRANS_REPLEN_NBR")
    public WhFacilityTransReplen getWhFacilityTransReplen() {
        return this.whFacilityTransReplen;
    }
    
    public void setWhFacilityTransReplen(WhFacilityTransReplen whFacilityTransReplen) {
        this.whFacilityTransReplen = whFacilityTransReplen;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR_RQST", nullable=false)
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }

    
    @Column(name="OE_ORD_DTL_NBR", nullable=false, precision=9, scale=0)
    public int getOeOrdDtlNbr() {
        return this.oeOrdDtlNbr;
    }
    
    public void setOeOrdDtlNbr(int oeOrdDtlNbr) {
        this.oeOrdDtlNbr = oeOrdDtlNbr;
    }

    
    @Column(name="PO_LINE_DTL_NBR", nullable=false, precision=9, scale=0)
    public int getPoLineDtlNbr() {
        return this.poLineDtlNbr;
    }
    
    public void setPoLineDtlNbr(int poLineDtlNbr) {
        this.poLineDtlNbr = poLineDtlNbr;
    }

    
    @Column(name="ALLOC_QTY", nullable=false, precision=13, scale=5)
    public BigDecimal getAllocQty() {
        return this.allocQty;
    }
    
    public void setAllocQty(BigDecimal allocQty) {
        this.allocQty = allocQty;
    }

    
    @Column(name="SUBST_ID", length=1)
    public String getSubstId() {
        return this.substId;
    }
    
    public void setSubstId(String substId) {
        this.substId = substId;
    }

    
    @Column(name="FACILITY_RQST", nullable=false, length=16)
    public String getFacilityRqst() {
        return this.facilityRqst;
    }
    
    public void setFacilityRqst(String facilityRqst) {
        this.facilityRqst = facilityRqst;
    }

    
    @Column(name="FACILITY_ACT", nullable=false, length=16)
    public String getFacilityAct() {
        return this.facilityAct;
    }
    
    public void setFacilityAct(String facilityAct) {
        this.facilityAct = facilityAct;
    }

    
    @Column(name="UNIT_PRICE_SELL_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceSellUm() {
        return this.unitPriceSellUm;
    }
    
    public void setUnitPriceSellUm(BigDecimal unitPriceSellUm) {
        this.unitPriceSellUm = unitPriceSellUm;
    }

    
    @Column(name="UNIT_PRICE_DENOM_SELL_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceDenomSellUm() {
        return this.unitPriceDenomSellUm;
    }
    
    public void setUnitPriceDenomSellUm(BigDecimal unitPriceDenomSellUm) {
        this.unitPriceDenomSellUm = unitPriceDenomSellUm;
    }

    
    @Column(name="UNIT_PRICE_STK_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceStkUm() {
        return this.unitPriceStkUm;
    }
    
    public void setUnitPriceStkUm(BigDecimal unitPriceStkUm) {
        this.unitPriceStkUm = unitPriceStkUm;
    }

    
    @Column(name="UNIT_PRICE_DENOM_STK_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceDenomStkUm() {
        return this.unitPriceDenomStkUm;
    }
    
    public void setUnitPriceDenomStkUm(BigDecimal unitPriceDenomStkUm) {
        this.unitPriceDenomStkUm = unitPriceDenomStkUm;
    }

    
    @Column(name="ALLOC_TYPE_ID", nullable=false, length=1)
    public String getAllocTypeId() {
        return this.allocTypeId;
    }
    
    public void setAllocTypeId(String allocTypeId) {
        this.allocTypeId = allocTypeId;
    }


    @Column(name="APS_SPLY_SUB_POOL_NBR", nullable=false, precision=9, scale=0)
    public int getApsSplySubPoolNbr() {
    	return this.apsSplySubPoolNbr;
    }
    
	@Override
	public void setApsSplySubPoolNbr(Integer apsSplySubPoolNbr) {
		this.apsSplySubPoolNbr = apsSplySubPoolNbr;
	}

}


