package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ApsAllocOnhandOoNoprice generated by hbm2java
 */
@Entity
@Table(name="APS_ALLOC_ONHAND_OO_NOPRICE"
)
public class ApsAllocOnhandOoNoprice  implements java.io.Serializable {


     private ApsAllocOnhandOoNopriceId id;

    public ApsAllocOnhandOoNoprice() {
    }

    public ApsAllocOnhandOoNoprice(ApsAllocOnhandOoNopriceId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="itemNbrRqst", column=@Column(name="ITEM_NBR_RQST", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="oeOrdDtlNbr", column=@Column(name="OE_ORD_DTL_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="lotNbr", column=@Column(name="LOT_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="apsSplySubPoolNbr", column=@Column(name="APS_SPLY_SUB_POOL_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="facilityRqst", column=@Column(name="FACILITY_RQST", nullable=false, length=16) ), 
        @AttributeOverride(name="facilityAct", column=@Column(name="FACILITY_ACT", nullable=false, length=16) ), 
        @AttributeOverride(name="substId", column=@Column(name="SUBST_ID", length=1) ), 
        @AttributeOverride(name="allocQty", column=@Column(name="ALLOC_QTY", nullable=false, precision=13, scale=5) ), 
        @AttributeOverride(name="allocTypeId", column=@Column(name="ALLOC_TYPE_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="whFacilityTransOnhandNbr", column=@Column(name="WH_FACILITY_TRANS_ONHAND_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="availDt", column=@Column(name="AVAIL_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="availDtTypeId", column=@Column(name="AVAIL_DT_TYPE_ID", nullable=false, length=1) ) } )
    public ApsAllocOnhandOoNopriceId getId() {
        return this.id;
    }
    
    public void setId(ApsAllocOnhandOoNopriceId id) {
        this.id = id;
    }




}


