package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ApsAllocWoOo generated by hbm2java
 */
@Entity
@Table(name="APS_ALLOC_WO_OO"
)
public class ApsAllocWoOo  implements java.io.Serializable, AllocWo {


     private int apsAllocWoOoNbr;
     private WoHdr woHdr;
     private int oeOrdDtlNbr;
     private OeOrdDtl oeOrdDtl;
     private IcItemMast icItemMast;
     private BigDecimal allocQty;
     private String facilityRqst;
     private String facilityAct;
     private String allocTypeId;
     private Integer whFacilityTransWoNbr;
	private int woHdrNbr;
	private Integer apsSplySubPoolNbr;

    public ApsAllocWoOo() {
    }

	
     @Id 

    
    @Column(name="APS_ALLOC_WO_OO_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getApsAllocWoOoNbr() {
        return this.apsAllocWoOoNbr;
    }
    
    public void setApsAllocWoOoNbr(int apsAllocWoOoNbr) {
        this.apsAllocWoOoNbr = apsAllocWoOoNbr;
    }

    @Column(name="OE_ORD_DTL_NBR")
    public int getOeOrdDtlNbr() {
    	return oeOrdDtlNbr;
    }
    
    public void setOeOrdDtlNbr(int oeOrdDtlNbr) {
    	this.oeOrdDtlNbr =oeOrdDtlNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OE_ORD_DTL_NBR", nullable=false, insertable=false,updatable=false)
    public OeOrdDtl getOeOrdDtl() {
        return this.oeOrdDtl;
    }
    
    public void setOeOrdDtl(OeOrdDtl oeOrdDtl) {
        this.oeOrdDtl = oeOrdDtl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR_RQST", nullable=false)
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }

    
    @Column(name="ALLOC_QTY", nullable=false, precision=13, scale=5)
    public BigDecimal getAllocQty() {
        return this.allocQty;
    }
    
    public void setAllocQty(BigDecimal allocQty) {
        this.allocQty = allocQty;
    }

    
    @Column(name="FACILITY_RQST", nullable=false, length=16)
    public String getFacilityRqst() {
        return this.facilityRqst;
    }
    
    public void setFacilityRqst(String facilityRqst) {
        this.facilityRqst = facilityRqst;
    }

    
    @Column(name="FACILITY_ACT", nullable=false, length=16)
    public String getFacilityAct() {
        return this.facilityAct;
    }
    
    public void setFacilityAct(String facilityAct) {
        this.facilityAct = facilityAct;
    }

    
    @Column(name="ALLOC_TYPE_ID", nullable=false, length=1)
    public String getAllocTypeId() {
        return this.allocTypeId;
    }
    
    public void setAllocTypeId(String allocTypeId) {
        this.allocTypeId = allocTypeId;
    }

    
    @Column(name="WH_FACILITY_TRANS_WO_NBR", precision=9, scale=0)
    public Integer getWhFacilityTransWoNbr() {
        return this.whFacilityTransWoNbr;
    }
    
    public void setWhFacilityTransWoNbr(Integer whFacilityTransWoNbr) {
        this.whFacilityTransWoNbr = whFacilityTransWoNbr;
    }


    @Column(name="WO_HDR_NBR", precision=9, scale=0)
    public int getWoHdrNbr() {
    	return woHdrNbr;
    }
	@Override
	public void setWoHdrNbr(int woHdrNbr) {
    	this.woHdrNbr  = woHdrNbr;
		
	}

	@Override
	public void setApsSplySubPoolNbr(Integer apsSplySubPoolNbr) {
		this.apsSplySubPoolNbr = apsSplySubPoolNbr;
	}


	@Override
    @Column(name="APS_SPLY_SUB_POOL_NBR", precision=9, scale=0)
	public int getApsSplySubPoolNbr() {
		return apsSplySubPoolNbr;
	}




}


