package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApsDmdFc generated by hbm2java
 */
@Entity
@Table(name="APS_DMD_FC"
)
public class ApsDmdFc  implements java.io.Serializable {


     private String dmdCd;
     private String dmdTypeCd;
     private int itemNbrDmd;
     private Date rqstDt;
     private int apsSrcRuleSetNbr;
     private int orgNbrCust;
     private String orgCdCust;
     private BigDecimal openQty;
    // private BigDecimal openQtyAdj;
     private short custAllocPrty;
     private String revLvl;
     private Integer orgNbrMfrRqst;
     private int fcItemMastNbr;
     private String fcstGrp;
     private int fcFcstNbr;
    // private String hardAllocFcWithinLeadTm;

    public ApsDmdFc() {
    }

     @Id 
	@Column(name="FC_FCST_NBR", nullable=false)
	public int getFcFcstNbr() {
		return fcFcstNbr;
	}
     
    public void  setFcFcstNbr(int fcFcstNbr) {
    	this.fcFcstNbr = fcFcstNbr;
    }
 
    
    @Column(name="DMD_CD", nullable=false, length=53)
    public String getDmdCd() {
        return this.dmdCd;
    }
    
    public void setDmdCd(String dmdCd) {
        this.dmdCd = dmdCd;
    }

    
    @Column(name="DMD_TYPE_CD", length=2)
    public String getDmdTypeCd() {
        return this.dmdTypeCd;
    }
    
    public void setDmdTypeCd(String dmdTypeCd) {
        this.dmdTypeCd = dmdTypeCd;
    }

    
    @Column(name="ITEM_NBR_DMD", nullable=false, precision=9, scale=0)
    public int getItemNbrDmd() {
        return this.itemNbrDmd;
    }
    
    public void setItemNbrDmd(int itemNbrDmd) {
        this.itemNbrDmd = itemNbrDmd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RQST_DT", nullable=false, length=7)
    public Date getRqstDt() {
        return this.rqstDt;
    }
    
    public void setRqstDt(Date rqstDt) {
        this.rqstDt = rqstDt;
    }

    
    @Column(name="APS_SRC_RULE_SET_NBR", nullable=false, precision=9, scale=0)
    public int getApsSrcRuleSetNbr() {
        return this.apsSrcRuleSetNbr;
    }
    
    public void setApsSrcRuleSetNbr(int apsSrcRuleSetNbr) {
        this.apsSrcRuleSetNbr = apsSrcRuleSetNbr;
    }

    
    @Column(name="ORG_NBR_CUST", nullable=false, precision=9, scale=0)
    public int getOrgNbrCust() {
        return this.orgNbrCust;
    }
    
    public void setOrgNbrCust(int orgNbrCust) {
        this.orgNbrCust = orgNbrCust;
    }

    
    @Column(name="ORG_CD_CUST", nullable=false, length=15)
    public String getOrgCdCust() {
        return this.orgCdCust;
    }
    
    public void setOrgCdCust(String orgCdCust) {
        this.orgCdCust = orgCdCust;
    }

    
    @Column(name="OPEN_QTY", precision=22, scale=0)
    public BigDecimal getOpenQty() {
        return this.openQty;
    }
    
    public void setOpenQty(BigDecimal openQty) {
        this.openQty = openQty;
    }

    
//    @Column(name="OPEN_QTY_ADJ", precision=17, scale=5)
//    public BigDecimal getOpenQtyAdj() {
//        return this.openQtyAdj;
//    }
//    
//    public void setOpenQtyAdj(BigDecimal openQtyAdj) {
//        this.openQtyAdj = openQtyAdj;
//    }

    
    @Column(name="CUST_ALLOC_PRTY", nullable=false, precision=3, scale=0)
    public short getCustAllocPrty() {
        return this.custAllocPrty;
    }
    
    public void setCustAllocPrty(short custAllocPrty) {
        this.custAllocPrty = custAllocPrty;
    }

    
    @Column(name="REV_LVL", length=5)
    public String getRevLvl() {
        return this.revLvl;
    }
    
    public void setRevLvl(String revLvl) {
        this.revLvl = revLvl;
    }

    
    @Column(name="ORG_NBR_MFR_RQST", precision=9, scale=0)
    public Integer getOrgNbrMfrRqst() {
        return this.orgNbrMfrRqst;
    }
    
    public void setOrgNbrMfrRqst(Integer orgNbrMfrRqst) {
        this.orgNbrMfrRqst = orgNbrMfrRqst;
    }

    
    @Column(name="FC_ITEM_MAST_NBR", nullable=false, precision=9, scale=0)
    public int getFcItemMastNbr() {
        return this.fcItemMastNbr;
    }
    
    public void setFcItemMastNbr(int fcItemMastNbr) {
        this.fcItemMastNbr = fcItemMastNbr;
    }

    
    @Column(name="FCST_GRP", nullable=false, length=8)
    public String getFcstGrp() {
        return this.fcstGrp;
    }
    
    public void setFcstGrp(String fcstGrp) {
        this.fcstGrp = fcstGrp;
    }

    
//    @Column(name="HARD_ALLOC_FC_WITHIN_LEAD_TM", nullable=false, length=1)
//    public String getHardAllocFcWithinLeadTm() {
//        return this.hardAllocFcWithinLeadTm;
//    }
//    
//    public void setHardAllocFcWithinLeadTm(String hardAllocFcWithinLeadTm) {
//        this.hardAllocFcWithinLeadTm = hardAllocFcWithinLeadTm;
//    }




}


