package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApsDispatchQueue generated by hbm2java
 */
@Entity
@Table(name="APS_DISPATCH_QUEUE"
)
public class ApsDispatchQueue  implements java.io.Serializable {


     private int itemNbr;
     private Date dispatchTime;
     private Integer planGrpNbr;

    public ApsDispatchQueue() {
    }

	
    public ApsDispatchQueue(int itemNbr) {
        this.itemNbr = itemNbr;
    }
    public ApsDispatchQueue(int itemNbr, Date dispatchTime, Integer planGrpNbr) {
       this.itemNbr = itemNbr;
       this.dispatchTime = dispatchTime;
       this.planGrpNbr = planGrpNbr;
    }
   
     @Id 

    
    @Column(name="ITEM_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getItemNbr() {
        return this.itemNbr;
    }
    
    public void setItemNbr(int itemNbr) {
        this.itemNbr = itemNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DISPATCH_TIME", length=7)
    public Date getDispatchTime() {
        return this.dispatchTime;
    }
    
    public void setDispatchTime(Date dispatchTime) {
        this.dispatchTime = dispatchTime;
    }

    
    @Column(name="PLAN_GRP_NBR", precision=9, scale=0)
    public Integer getPlanGrpNbr() {
        return this.planGrpNbr;
    }
    
    public void setPlanGrpNbr(Integer planGrpNbr) {
        this.planGrpNbr = planGrpNbr;
    }




}


