package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApsDmdRuleSetItem generated by hbm2java
 */
@Entity
@Table(name="APS_DMD_RULE_SET_ITEM"
)
public class ApsDmdRuleSetItem  implements java.io.Serializable {


     private int apsDmdRuleSetItemNbr;
     private ApsSrcRuleSet apsSrcRuleSet;
     private IcItemMast icItemMast;
     private Date unallocCustOrdDt;
     private Date allocLateCustOrdDt;
     private Date unallocFcstDt;
     private Date allocLateFcstDt;
     private Date unallocSafetyStkDt;
     private Date allocLateSafetyStkDt;
     private Date unallocWorkOrdDt;
     private Date allocLateWorkOrdDt;
     private String apsRuleWarnFlg;
     private BigDecimal custOrdQtyTot;
     private BigDecimal custAllocQtyTot;
     private BigDecimal onhandQty;

    public ApsDmdRuleSetItem() {
    }

	
    public ApsDmdRuleSetItem(int apsDmdRuleSetItemNbr, ApsSrcRuleSet apsSrcRuleSet, IcItemMast icItemMast) {
        this.apsDmdRuleSetItemNbr = apsDmdRuleSetItemNbr;
        this.apsSrcRuleSet = apsSrcRuleSet;
        this.icItemMast = icItemMast;
    }
    public ApsDmdRuleSetItem(int apsDmdRuleSetItemNbr, ApsSrcRuleSet apsSrcRuleSet, IcItemMast icItemMast, Date unallocCustOrdDt, Date allocLateCustOrdDt, Date unallocFcstDt, Date allocLateFcstDt, Date unallocSafetyStkDt, Date allocLateSafetyStkDt, Date unallocWorkOrdDt, Date allocLateWorkOrdDt, String apsRuleWarnFlg, BigDecimal custOrdQtyTot, BigDecimal custAllocQtyTot, BigDecimal onhandQty) {
       this.apsDmdRuleSetItemNbr = apsDmdRuleSetItemNbr;
       this.apsSrcRuleSet = apsSrcRuleSet;
       this.icItemMast = icItemMast;
       this.unallocCustOrdDt = unallocCustOrdDt;
       this.allocLateCustOrdDt = allocLateCustOrdDt;
       this.unallocFcstDt = unallocFcstDt;
       this.allocLateFcstDt = allocLateFcstDt;
       this.unallocSafetyStkDt = unallocSafetyStkDt;
       this.allocLateSafetyStkDt = allocLateSafetyStkDt;
       this.unallocWorkOrdDt = unallocWorkOrdDt;
       this.allocLateWorkOrdDt = allocLateWorkOrdDt;
       this.apsRuleWarnFlg = apsRuleWarnFlg;
       this.custOrdQtyTot = custOrdQtyTot;
       this.custAllocQtyTot = custAllocQtyTot;
       this.onhandQty = onhandQty;
    }
   
     @Id 

    
    @Column(name="APS_DMD_RULE_SET_ITEM_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getApsDmdRuleSetItemNbr() {
        return this.apsDmdRuleSetItemNbr;
    }
    
    public void setApsDmdRuleSetItemNbr(int apsDmdRuleSetItemNbr) {
        this.apsDmdRuleSetItemNbr = apsDmdRuleSetItemNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APS_SRC_RULE_SET_NBR", nullable=false)
    public ApsSrcRuleSet getApsSrcRuleSet() {
        return this.apsSrcRuleSet;
    }
    
    public void setApsSrcRuleSet(ApsSrcRuleSet apsSrcRuleSet) {
        this.apsSrcRuleSet = apsSrcRuleSet;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR", nullable=false)
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UNALLOC_CUST_ORD_DT", length=7)
    public Date getUnallocCustOrdDt() {
        return this.unallocCustOrdDt;
    }
    
    public void setUnallocCustOrdDt(Date unallocCustOrdDt) {
        this.unallocCustOrdDt = unallocCustOrdDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ALLOC_LATE_CUST_ORD_DT", length=7)
    public Date getAllocLateCustOrdDt() {
        return this.allocLateCustOrdDt;
    }
    
    public void setAllocLateCustOrdDt(Date allocLateCustOrdDt) {
        this.allocLateCustOrdDt = allocLateCustOrdDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UNALLOC_FCST_DT", length=7)
    public Date getUnallocFcstDt() {
        return this.unallocFcstDt;
    }
    
    public void setUnallocFcstDt(Date unallocFcstDt) {
        this.unallocFcstDt = unallocFcstDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ALLOC_LATE_FCST_DT", length=7)
    public Date getAllocLateFcstDt() {
        return this.allocLateFcstDt;
    }
    
    public void setAllocLateFcstDt(Date allocLateFcstDt) {
        this.allocLateFcstDt = allocLateFcstDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UNALLOC_SAFETY_STK_DT", length=7)
    public Date getUnallocSafetyStkDt() {
        return this.unallocSafetyStkDt;
    }
    
    public void setUnallocSafetyStkDt(Date unallocSafetyStkDt) {
        this.unallocSafetyStkDt = unallocSafetyStkDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ALLOC_LATE_SAFETY_STK_DT", length=7)
    public Date getAllocLateSafetyStkDt() {
        return this.allocLateSafetyStkDt;
    }
    
    public void setAllocLateSafetyStkDt(Date allocLateSafetyStkDt) {
        this.allocLateSafetyStkDt = allocLateSafetyStkDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UNALLOC_WORK_ORD_DT", length=7)
    public Date getUnallocWorkOrdDt() {
        return this.unallocWorkOrdDt;
    }
    
    public void setUnallocWorkOrdDt(Date unallocWorkOrdDt) {
        this.unallocWorkOrdDt = unallocWorkOrdDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ALLOC_LATE_WORK_ORD_DT", length=7)
    public Date getAllocLateWorkOrdDt() {
        return this.allocLateWorkOrdDt;
    }
    
    public void setAllocLateWorkOrdDt(Date allocLateWorkOrdDt) {
        this.allocLateWorkOrdDt = allocLateWorkOrdDt;
    }

    
    @Column(name="APS_RULE_WARN_FLG", length=1)
    public String getApsRuleWarnFlg() {
        return this.apsRuleWarnFlg;
    }
    
    public void setApsRuleWarnFlg(String apsRuleWarnFlg) {
        this.apsRuleWarnFlg = apsRuleWarnFlg;
    }

    
    @Column(name="CUST_ORD_QTY_TOT", precision=9)
    public BigDecimal getCustOrdQtyTot() {
        return this.custOrdQtyTot;
    }
    
    public void setCustOrdQtyTot(BigDecimal custOrdQtyTot) {
        this.custOrdQtyTot = custOrdQtyTot;
    }

    
    @Column(name="CUST_ALLOC_QTY_TOT", precision=9)
    public BigDecimal getCustAllocQtyTot() {
        return this.custAllocQtyTot;
    }
    
    public void setCustAllocQtyTot(BigDecimal custAllocQtyTot) {
        this.custAllocQtyTot = custAllocQtyTot;
    }

    
    @Column(name="ONHAND_QTY", precision=11, scale=5)
    public BigDecimal getOnhandQty() {
        return this.onhandQty;
    }
    
    public void setOnhandQty(BigDecimal onhandQty) {
        this.onhandQty = onhandQty;
    }




}


