package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApsResultDtlSply generated by hbm2java
 */
@Entity
@Table(name="APS_RESULT_DTL_SPLY"
)
public class ApsResultDtlSply  implements java.io.Serializable {


     private ApsResultDtlSplyId id;
     private Integer lotNbrSply;
     private String facilitySply;
     private Integer apsSplySubPoolNbrSply;
     private Integer poLineDtlNbr;
     private Integer woHdrNbr;
     private BigDecimal splyQty;
     private BigDecimal splyQtyAlloc;
     private Date availDt;
     private Integer orgNbrMfrSply;
     private Integer orgNbrVndSply;
     private Date apsAvailDt;
     private Integer whFacilityTransOnhandNbr;
     private Integer whFacilityTransReplenNbr;
     private Integer whFacilityTransWoNbr;
     private String srcRuleFlg;
     private String splyCertToDemandFlg;
     private String explicitMfrFlg;
     private String apprvMfrFlg;
     private String attributeCertFlg;
     private String revLvlFlg;
     private String lotDtFlg;
     private String cntryOfOriginFlg;
     private String custSubstFlg;
     private String globalSubstFlg;
     private String equivFlg;
     private String availDtTypeId;

    public ApsResultDtlSply() {
    }

	
    public ApsResultDtlSply(ApsResultDtlSplyId id, String availDtTypeId) {
        this.id = id;
        this.availDtTypeId = availDtTypeId;
    }
    public ApsResultDtlSply(ApsResultDtlSplyId id, Integer lotNbrSply, String facilitySply, Integer apsSplySubPoolNbrSply, Integer poLineDtlNbr, Integer woHdrNbr, BigDecimal splyQty, BigDecimal splyQtyAlloc, Date availDt, Integer orgNbrMfrSply, Integer orgNbrVndSply, Date apsAvailDt, Integer whFacilityTransOnhandNbr, Integer whFacilityTransReplenNbr, Integer whFacilityTransWoNbr, String srcRuleFlg, String splyCertToDemandFlg, String explicitMfrFlg, String apprvMfrFlg, String attributeCertFlg, String revLvlFlg, String lotDtFlg, String cntryOfOriginFlg, String custSubstFlg, String globalSubstFlg, String equivFlg, String availDtTypeId) {
       this.id = id;
       this.lotNbrSply = lotNbrSply;
       this.facilitySply = facilitySply;
       this.apsSplySubPoolNbrSply = apsSplySubPoolNbrSply;
       this.poLineDtlNbr = poLineDtlNbr;
       this.woHdrNbr = woHdrNbr;
       this.splyQty = splyQty;
       this.splyQtyAlloc = splyQtyAlloc;
       this.availDt = availDt;
       this.orgNbrMfrSply = orgNbrMfrSply;
       this.orgNbrVndSply = orgNbrVndSply;
       this.apsAvailDt = apsAvailDt;
       this.whFacilityTransOnhandNbr = whFacilityTransOnhandNbr;
       this.whFacilityTransReplenNbr = whFacilityTransReplenNbr;
       this.whFacilityTransWoNbr = whFacilityTransWoNbr;
       this.srcRuleFlg = srcRuleFlg;
       this.splyCertToDemandFlg = splyCertToDemandFlg;
       this.explicitMfrFlg = explicitMfrFlg;
       this.apprvMfrFlg = apprvMfrFlg;
       this.attributeCertFlg = attributeCertFlg;
       this.revLvlFlg = revLvlFlg;
       this.lotDtFlg = lotDtFlg;
       this.cntryOfOriginFlg = cntryOfOriginFlg;
       this.custSubstFlg = custSubstFlg;
       this.globalSubstFlg = globalSubstFlg;
       this.equivFlg = equivFlg;
       this.availDtTypeId = availDtTypeId;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="apsResultDtlDmdNbr", column=@Column(name="APS_RESULT_DTL_DMD_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="splyIdentifier", column=@Column(name="SPLY_IDENTIFIER", nullable=false, length=20) ) } )
    public ApsResultDtlSplyId getId() {
        return this.id;
    }
    
    public void setId(ApsResultDtlSplyId id) {
        this.id = id;
    }

    
    @Column(name="LOT_NBR_SPLY", precision=9, scale=0)
    public Integer getLotNbrSply() {
        return this.lotNbrSply;
    }
    
    public void setLotNbrSply(Integer lotNbrSply) {
        this.lotNbrSply = lotNbrSply;
    }

    
    @Column(name="FACILITY_SPLY", length=16)
    public String getFacilitySply() {
        return this.facilitySply;
    }
    
    public void setFacilitySply(String facilitySply) {
        this.facilitySply = facilitySply;
    }

    
    @Column(name="APS_SPLY_SUB_POOL_NBR_SPLY", precision=9, scale=0)
    public Integer getApsSplySubPoolNbrSply() {
        return this.apsSplySubPoolNbrSply;
    }
    
    public void setApsSplySubPoolNbrSply(Integer apsSplySubPoolNbrSply) {
        this.apsSplySubPoolNbrSply = apsSplySubPoolNbrSply;
    }

    
    @Column(name="PO_LINE_DTL_NBR", precision=9, scale=0)
    public Integer getPoLineDtlNbr() {
        return this.poLineDtlNbr;
    }
    
    public void setPoLineDtlNbr(Integer poLineDtlNbr) {
        this.poLineDtlNbr = poLineDtlNbr;
    }

    
    @Column(name="WO_HDR_NBR", precision=9, scale=0)
    public Integer getWoHdrNbr() {
        return this.woHdrNbr;
    }
    
    public void setWoHdrNbr(Integer woHdrNbr) {
        this.woHdrNbr = woHdrNbr;
    }

    
    @Column(name="SPLY_QTY", precision=13, scale=5)
    public BigDecimal getSplyQty() {
        return this.splyQty;
    }
    
    public void setSplyQty(BigDecimal splyQty) {
        this.splyQty = splyQty;
    }

    
    @Column(name="SPLY_QTY_ALLOC", precision=13, scale=5)
    public BigDecimal getSplyQtyAlloc() {
        return this.splyQtyAlloc;
    }
    
    public void setSplyQtyAlloc(BigDecimal splyQtyAlloc) {
        this.splyQtyAlloc = splyQtyAlloc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="AVAIL_DT", length=7)
    public Date getAvailDt() {
        return this.availDt;
    }
    
    public void setAvailDt(Date availDt) {
        this.availDt = availDt;
    }

    
    @Column(name="ORG_NBR_MFR_SPLY", precision=9, scale=0)
    public Integer getOrgNbrMfrSply() {
        return this.orgNbrMfrSply;
    }
    
    public void setOrgNbrMfrSply(Integer orgNbrMfrSply) {
        this.orgNbrMfrSply = orgNbrMfrSply;
    }

    
    @Column(name="ORG_NBR_VND_SPLY", precision=9, scale=0)
    public Integer getOrgNbrVndSply() {
        return this.orgNbrVndSply;
    }
    
    public void setOrgNbrVndSply(Integer orgNbrVndSply) {
        this.orgNbrVndSply = orgNbrVndSply;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="APS_AVAIL_DT", length=7)
    public Date getApsAvailDt() {
        return this.apsAvailDt;
    }
    
    public void setApsAvailDt(Date apsAvailDt) {
        this.apsAvailDt = apsAvailDt;
    }

    
    @Column(name="WH_FACILITY_TRANS_ONHAND_NBR", precision=9, scale=0)
    public Integer getWhFacilityTransOnhandNbr() {
        return this.whFacilityTransOnhandNbr;
    }
    
    public void setWhFacilityTransOnhandNbr(Integer whFacilityTransOnhandNbr) {
        this.whFacilityTransOnhandNbr = whFacilityTransOnhandNbr;
    }

    
    @Column(name="WH_FACILITY_TRANS_REPLEN_NBR", precision=9, scale=0)
    public Integer getWhFacilityTransReplenNbr() {
        return this.whFacilityTransReplenNbr;
    }
    
    public void setWhFacilityTransReplenNbr(Integer whFacilityTransReplenNbr) {
        this.whFacilityTransReplenNbr = whFacilityTransReplenNbr;
    }

    
    @Column(name="WH_FACILITY_TRANS_WO_NBR", precision=9, scale=0)
    public Integer getWhFacilityTransWoNbr() {
        return this.whFacilityTransWoNbr;
    }
    
    public void setWhFacilityTransWoNbr(Integer whFacilityTransWoNbr) {
        this.whFacilityTransWoNbr = whFacilityTransWoNbr;
    }

    
    @Column(name="SRC_RULE_FLG", length=1)
    public String getSrcRuleFlg() {
        return this.srcRuleFlg;
    }
    
    public void setSrcRuleFlg(String srcRuleFlg) {
        this.srcRuleFlg = srcRuleFlg;
    }

    
    @Column(name="SPLY_CERT_TO_DEMAND_FLG", length=1)
    public String getSplyCertToDemandFlg() {
        return this.splyCertToDemandFlg;
    }
    
    public void setSplyCertToDemandFlg(String splyCertToDemandFlg) {
        this.splyCertToDemandFlg = splyCertToDemandFlg;
    }

    
    @Column(name="EXPLICIT_MFR_FLG", length=1)
    public String getExplicitMfrFlg() {
        return this.explicitMfrFlg;
    }
    
    public void setExplicitMfrFlg(String explicitMfrFlg) {
        this.explicitMfrFlg = explicitMfrFlg;
    }

    
    @Column(name="APPRV_MFR_FLG", length=1)
    public String getApprvMfrFlg() {
        return this.apprvMfrFlg;
    }
    
    public void setApprvMfrFlg(String apprvMfrFlg) {
        this.apprvMfrFlg = apprvMfrFlg;
    }

    
    @Column(name="ATTRIBUTE_CERT_FLG", length=1)
    public String getAttributeCertFlg() {
        return this.attributeCertFlg;
    }
    
    public void setAttributeCertFlg(String attributeCertFlg) {
        this.attributeCertFlg = attributeCertFlg;
    }

    
    @Column(name="REV_LVL_FLG", length=1)
    public String getRevLvlFlg() {
        return this.revLvlFlg;
    }
    
    public void setRevLvlFlg(String revLvlFlg) {
        this.revLvlFlg = revLvlFlg;
    }

    
    @Column(name="LOT_DT_FLG", length=1)
    public String getLotDtFlg() {
        return this.lotDtFlg;
    }
    
    public void setLotDtFlg(String lotDtFlg) {
        this.lotDtFlg = lotDtFlg;
    }

    
    @Column(name="CNTRY_OF_ORIGIN_FLG", length=1)
    public String getCntryOfOriginFlg() {
        return this.cntryOfOriginFlg;
    }
    
    public void setCntryOfOriginFlg(String cntryOfOriginFlg) {
        this.cntryOfOriginFlg = cntryOfOriginFlg;
    }

    
    @Column(name="CUST_SUBST_FLG", length=1)
    public String getCustSubstFlg() {
        return this.custSubstFlg;
    }
    
    public void setCustSubstFlg(String custSubstFlg) {
        this.custSubstFlg = custSubstFlg;
    }

    
    @Column(name="GLOBAL_SUBST_FLG", length=1)
    public String getGlobalSubstFlg() {
        return this.globalSubstFlg;
    }
    
    public void setGlobalSubstFlg(String globalSubstFlg) {
        this.globalSubstFlg = globalSubstFlg;
    }

    
    @Column(name="EQUIV_FLG", length=1)
    public String getEquivFlg() {
        return this.equivFlg;
    }
    
    public void setEquivFlg(String equivFlg) {
        this.equivFlg = equivFlg;
    }

    
    @Column(name="AVAIL_DT_TYPE_ID", nullable=false, length=1)
    public String getAvailDtTypeId() {
        return this.availDtTypeId;
    }
    
    public void setAvailDtTypeId(String availDtTypeId) {
        this.availDtTypeId = availDtTypeId;
    }




}


