package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ApsResultDtlSplyVw generated by hbm2java
 */
@Entity
@Table(name="APS_RESULT_DTL_SPLY_VW"
)
public class ApsResultDtlSplyVw  implements java.io.Serializable {


     private ApsResultDtlSplyVwId id;

    public ApsResultDtlSplyVw() {
    }

    public ApsResultDtlSplyVw(ApsResultDtlSplyVwId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="apsResultDtlDmdNbr", column=@Column(name="APS_RESULT_DTL_DMD_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="splyIdentifier", column=@Column(name="SPLY_IDENTIFIER", nullable=false, length=20) ), 
        @AttributeOverride(name="lotNbrSply", column=@Column(name="LOT_NBR_SPLY", precision=9, scale=0) ), 
        @AttributeOverride(name="facilitySply", column=@Column(name="FACILITY_SPLY", length=16) ), 
        @AttributeOverride(name="apsSplySubPoolNbrSply", column=@Column(name="APS_SPLY_SUB_POOL_NBR_SPLY", precision=9, scale=0) ), 
        @AttributeOverride(name="apsSplyPoolCdSply", column=@Column(name="APS_SPLY_POOL_CD_SPLY", nullable=false, length=20) ), 
        @AttributeOverride(name="apsSplySubPoolCdSply", column=@Column(name="APS_SPLY_SUB_POOL_CD_SPLY", nullable=false, length=20) ), 
        @AttributeOverride(name="poLineDtlNbr", column=@Column(name="PO_LINE_DTL_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="woHdrNbr", column=@Column(name="WO_HDR_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="splyQty", column=@Column(name="SPLY_QTY", precision=13, scale=5) ), 
        @AttributeOverride(name="splyQtyAlloc", column=@Column(name="SPLY_QTY_ALLOC", precision=13, scale=5) ), 
        @AttributeOverride(name="availDt", column=@Column(name="AVAIL_DT", length=7) ), 
        @AttributeOverride(name="orgNbrMfrSply", column=@Column(name="ORG_NBR_MFR_SPLY", precision=9, scale=0) ), 
        @AttributeOverride(name="orgNmMfrSply", column=@Column(name="ORG_NM_MFR_SPLY", length=60) ), 
        @AttributeOverride(name="orgNbrVndSply", column=@Column(name="ORG_NBR_VND_SPLY", precision=9, scale=0) ), 
        @AttributeOverride(name="orgNmVndSply", column=@Column(name="ORG_NM_VND_SPLY", length=60) ), 
        @AttributeOverride(name="apsAvailDt", column=@Column(name="APS_AVAIL_DT", length=7) ), 
        @AttributeOverride(name="whFacilityTransOnhandNbr", column=@Column(name="WH_FACILITY_TRANS_ONHAND_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="whFacilityTransReplenNbr", column=@Column(name="WH_FACILITY_TRANS_REPLEN_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="whFacilityTransWoNbr", column=@Column(name="WH_FACILITY_TRANS_WO_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="srcRuleFlg", column=@Column(name="SRC_RULE_FLG", length=1) ), 
        @AttributeOverride(name="splyCertToDemandFlg", column=@Column(name="SPLY_CERT_TO_DEMAND_FLG", length=1) ), 
        @AttributeOverride(name="explicitMfrFlg", column=@Column(name="EXPLICIT_MFR_FLG", length=1) ), 
        @AttributeOverride(name="apprvMfrFlg", column=@Column(name="APPRV_MFR_FLG", length=1) ), 
        @AttributeOverride(name="attributeCertFlg", column=@Column(name="ATTRIBUTE_CERT_FLG", length=1) ), 
        @AttributeOverride(name="revLvlFlg", column=@Column(name="REV_LVL_FLG", length=1) ), 
        @AttributeOverride(name="lotDtFlg", column=@Column(name="LOT_DT_FLG", length=1) ), 
        @AttributeOverride(name="cntryOfOriginFlg", column=@Column(name="CNTRY_OF_ORIGIN_FLG", length=1) ), 
        @AttributeOverride(name="equivFlg", column=@Column(name="EQUIV_FLG", length=1) ), 
        @AttributeOverride(name="custSubstFlg", column=@Column(name="CUST_SUBST_FLG", length=1) ), 
        @AttributeOverride(name="globalSubstFlg", column=@Column(name="GLOBAL_SUBST_FLG", length=1) ), 
        @AttributeOverride(name="availDtTypeId", column=@Column(name="AVAIL_DT_TYPE_ID", nullable=false, length=1) ) } )
    public ApsResultDtlSplyVwId getId() {
        return this.id;
    }
    
    public void setId(ApsResultDtlSplyVwId id) {
        this.id = id;
    }




}


