package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ApsRqstGrp generated by hbm2java
 */
@Entity
@Table(name="APS_RQST_GRP"
)
public class ApsRqstGrp  implements java.io.Serializable {


     private ApsRqstGrpId id;

    public ApsRqstGrp() {
    }

    public ApsRqstGrp(ApsRqstGrpId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="dmdOoFlg", column=@Column(name="DMD_OO_FLG", length=1) ), 
        @AttributeOverride(name="dmdFcFlg", column=@Column(name="DMD_FC_FLG", length=1) ), 
        @AttributeOverride(name="dmdWoFlg", column=@Column(name="DMD_WO_FLG", length=1) ), 
        @AttributeOverride(name="splyOhFlg", column=@Column(name="SPLY_OH_FLG", length=1) ), 
        @AttributeOverride(name="splyPoFlg", column=@Column(name="SPLY_PO_FLG", length=1) ), 
        @AttributeOverride(name="splyWoFlg", column=@Column(name="SPLY_WO_FLG", length=1) ) } )
    public ApsRqstGrpId getId() {
        return this.id;
    }
    
    public void setId(ApsRqstGrpId id) {
        this.id = id;
    }




}


