package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ApsRqstQueueId generated by hbm2java
 */
@Embeddable
public class ApsRqstQueueId  implements java.io.Serializable {


     private int itemNbr;
     private String dmdOoFlg;
     private String dmdFcFlg;
     private String dmdWoFlg;
     private String splyOhFlg;
     private String splyPoFlg;
     private String splyWoFlg;
     private Date rqstTm;
     private String apsException;
     private boolean itemPrty;
     private Date dispatchTm;
     private String rqstSrc;

    public ApsRqstQueueId() {
    }

	
    public ApsRqstQueueId(int itemNbr, Date rqstTm, boolean itemPrty, String rqstSrc) {
        this.itemNbr = itemNbr;
        this.rqstTm = rqstTm;
        this.itemPrty = itemPrty;
        this.rqstSrc = rqstSrc;
    }
    public ApsRqstQueueId(int itemNbr, String dmdOoFlg, String dmdFcFlg, String dmdWoFlg, String splyOhFlg, String splyPoFlg, String splyWoFlg, Date rqstTm, String apsException, boolean itemPrty, Date dispatchTm, String rqstSrc) {
       this.itemNbr = itemNbr;
       this.dmdOoFlg = dmdOoFlg;
       this.dmdFcFlg = dmdFcFlg;
       this.dmdWoFlg = dmdWoFlg;
       this.splyOhFlg = splyOhFlg;
       this.splyPoFlg = splyPoFlg;
       this.splyWoFlg = splyWoFlg;
       this.rqstTm = rqstTm;
       this.apsException = apsException;
       this.itemPrty = itemPrty;
       this.dispatchTm = dispatchTm;
       this.rqstSrc = rqstSrc;
    }
   


    @Column(name="ITEM_NBR", nullable=false, precision=9, scale=0)
    public int getItemNbr() {
        return this.itemNbr;
    }
    
    public void setItemNbr(int itemNbr) {
        this.itemNbr = itemNbr;
    }


    @Column(name="DMD_OO_FLG", length=1)
    public String getDmdOoFlg() {
        return this.dmdOoFlg;
    }
    
    public void setDmdOoFlg(String dmdOoFlg) {
        this.dmdOoFlg = dmdOoFlg;
    }


    @Column(name="DMD_FC_FLG", length=1)
    public String getDmdFcFlg() {
        return this.dmdFcFlg;
    }
    
    public void setDmdFcFlg(String dmdFcFlg) {
        this.dmdFcFlg = dmdFcFlg;
    }


    @Column(name="DMD_WO_FLG", length=1)
    public String getDmdWoFlg() {
        return this.dmdWoFlg;
    }
    
    public void setDmdWoFlg(String dmdWoFlg) {
        this.dmdWoFlg = dmdWoFlg;
    }


    @Column(name="SPLY_OH_FLG", length=1)
    public String getSplyOhFlg() {
        return this.splyOhFlg;
    }
    
    public void setSplyOhFlg(String splyOhFlg) {
        this.splyOhFlg = splyOhFlg;
    }


    @Column(name="SPLY_PO_FLG", length=1)
    public String getSplyPoFlg() {
        return this.splyPoFlg;
    }
    
    public void setSplyPoFlg(String splyPoFlg) {
        this.splyPoFlg = splyPoFlg;
    }


    @Column(name="SPLY_WO_FLG", length=1)
    public String getSplyWoFlg() {
        return this.splyWoFlg;
    }
    
    public void setSplyWoFlg(String splyWoFlg) {
        this.splyWoFlg = splyWoFlg;
    }


    @Column(name="RQST_TM", nullable=false, length=7)
    public Date getRqstTm() {
        return this.rqstTm;
    }
    
    public void setRqstTm(Date rqstTm) {
        this.rqstTm = rqstTm;
    }


    @Column(name="APS_EXCEPTION", length=2048)
    public String getApsException() {
        return this.apsException;
    }
    
    public void setApsException(String apsException) {
        this.apsException = apsException;
    }


    @Column(name="ITEM_PRTY", nullable=false, precision=1, scale=0)
    public boolean isItemPrty() {
        return this.itemPrty;
    }
    
    public void setItemPrty(boolean itemPrty) {
        this.itemPrty = itemPrty;
    }


    @Column(name="DISPATCH_TM", length=7)
    public Date getDispatchTm() {
        return this.dispatchTm;
    }
    
    public void setDispatchTm(Date dispatchTm) {
        this.dispatchTm = dispatchTm;
    }


    @Column(name="RQST_SRC", nullable=false, length=61)
    public String getRqstSrc() {
        return this.rqstSrc;
    }
    
    public void setRqstSrc(String rqstSrc) {
        this.rqstSrc = rqstSrc;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ApsRqstQueueId) ) return false;
		 ApsRqstQueueId castOther = ( ApsRqstQueueId ) other; 
         
		 return (this.getItemNbr()==castOther.getItemNbr())
 && ( (this.getDmdOoFlg()==castOther.getDmdOoFlg()) || ( this.getDmdOoFlg()!=null && castOther.getDmdOoFlg()!=null && this.getDmdOoFlg().equals(castOther.getDmdOoFlg()) ) )
 && ( (this.getDmdFcFlg()==castOther.getDmdFcFlg()) || ( this.getDmdFcFlg()!=null && castOther.getDmdFcFlg()!=null && this.getDmdFcFlg().equals(castOther.getDmdFcFlg()) ) )
 && ( (this.getDmdWoFlg()==castOther.getDmdWoFlg()) || ( this.getDmdWoFlg()!=null && castOther.getDmdWoFlg()!=null && this.getDmdWoFlg().equals(castOther.getDmdWoFlg()) ) )
 && ( (this.getSplyOhFlg()==castOther.getSplyOhFlg()) || ( this.getSplyOhFlg()!=null && castOther.getSplyOhFlg()!=null && this.getSplyOhFlg().equals(castOther.getSplyOhFlg()) ) )
 && ( (this.getSplyPoFlg()==castOther.getSplyPoFlg()) || ( this.getSplyPoFlg()!=null && castOther.getSplyPoFlg()!=null && this.getSplyPoFlg().equals(castOther.getSplyPoFlg()) ) )
 && ( (this.getSplyWoFlg()==castOther.getSplyWoFlg()) || ( this.getSplyWoFlg()!=null && castOther.getSplyWoFlg()!=null && this.getSplyWoFlg().equals(castOther.getSplyWoFlg()) ) )
 && ( (this.getRqstTm()==castOther.getRqstTm()) || ( this.getRqstTm()!=null && castOther.getRqstTm()!=null && this.getRqstTm().equals(castOther.getRqstTm()) ) )
 && ( (this.getApsException()==castOther.getApsException()) || ( this.getApsException()!=null && castOther.getApsException()!=null && this.getApsException().equals(castOther.getApsException()) ) )
 && (this.isItemPrty()==castOther.isItemPrty())
 && ( (this.getDispatchTm()==castOther.getDispatchTm()) || ( this.getDispatchTm()!=null && castOther.getDispatchTm()!=null && this.getDispatchTm().equals(castOther.getDispatchTm()) ) )
 && ( (this.getRqstSrc()==castOther.getRqstSrc()) || ( this.getRqstSrc()!=null && castOther.getRqstSrc()!=null && this.getRqstSrc().equals(castOther.getRqstSrc()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getItemNbr();
         result = 37 * result + ( getDmdOoFlg() == null ? 0 : this.getDmdOoFlg().hashCode() );
         result = 37 * result + ( getDmdFcFlg() == null ? 0 : this.getDmdFcFlg().hashCode() );
         result = 37 * result + ( getDmdWoFlg() == null ? 0 : this.getDmdWoFlg().hashCode() );
         result = 37 * result + ( getSplyOhFlg() == null ? 0 : this.getSplyOhFlg().hashCode() );
         result = 37 * result + ( getSplyPoFlg() == null ? 0 : this.getSplyPoFlg().hashCode() );
         result = 37 * result + ( getSplyWoFlg() == null ? 0 : this.getSplyWoFlg().hashCode() );
         result = 37 * result + ( getRqstTm() == null ? 0 : this.getRqstTm().hashCode() );
         result = 37 * result + ( getApsException() == null ? 0 : this.getApsException().hashCode() );
         result = 37 * result + (this.isItemPrty()?1:0);
         result = 37 * result + ( getDispatchTm() == null ? 0 : this.getDispatchTm().hashCode() );
         result = 37 * result + ( getRqstSrc() == null ? 0 : this.getRqstSrc().hashCode() );
         return result;
   }   


}


