package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ApsRqstQueue generated by hbm2java
 */
@Entity
@Table(name="APS_RQST_QUEUE"
)
public class ApsRqstQueue  implements java.io.Serializable {


     private ApsRqstQueueId id;
     private IcItemMast icItemMast;

    public ApsRqstQueue() {
    }

    public ApsRqstQueue(ApsRqstQueueId id, IcItemMast icItemMast) {
       this.id = id;
       this.icItemMast = icItemMast;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="dmdOoFlg", column=@Column(name="DMD_OO_FLG", length=1) ), 
        @AttributeOverride(name="dmdFcFlg", column=@Column(name="DMD_FC_FLG", length=1) ), 
        @AttributeOverride(name="dmdWoFlg", column=@Column(name="DMD_WO_FLG", length=1) ), 
        @AttributeOverride(name="splyOhFlg", column=@Column(name="SPLY_OH_FLG", length=1) ), 
        @AttributeOverride(name="splyPoFlg", column=@Column(name="SPLY_PO_FLG", length=1) ), 
        @AttributeOverride(name="splyWoFlg", column=@Column(name="SPLY_WO_FLG", length=1) ), 
        @AttributeOverride(name="rqstTm", column=@Column(name="RQST_TM", nullable=false, length=7) ), 
        @AttributeOverride(name="apsException", column=@Column(name="APS_EXCEPTION", length=2048) ), 
        @AttributeOverride(name="itemPrty", column=@Column(name="ITEM_PRTY", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="dispatchTm", column=@Column(name="DISPATCH_TM", length=7) ), 
        @AttributeOverride(name="rqstSrc", column=@Column(name="RQST_SRC", nullable=false, length=61) ) } )
    public ApsRqstQueueId getId() {
        return this.id;
    }
    
    public void setId(ApsRqstQueueId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR", nullable=false, insertable=false, updatable=false)
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }




}


