package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 5:38:54 AM by Hibernate Tools 5.4.1.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApsSrcRule generated by hbm2java
 */
@Entity
@Table(name="APS_SRC_RULE"
)
public class ApsSrcRule  implements java.io.Serializable {


     private int apsSrcRuleNbr = -1;
     private int apsSplySubPoolNbr;   // TODO DUAL
     private transient ApsSplySubPool apsSplySubPool;
     private transient ApsSrcRuleSet apsSrcRuleSet;
     // TODO DUAL
     private int apsSrcRuleSetNbr;

     private transient UtFacility utFacility;
     private String facility;
     private String splyTypeId;
     private short srcPrty;
     private transient int utUserNbr;
     private transient Date lastModDt;

    public ApsSrcRule() {
    }

     @Id 

    
    @Column(name="APS_SRC_RULE_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getApsSrcRuleNbr() {
        return this.apsSrcRuleNbr;
    }
    
    public void setApsSrcRuleNbr(int apsSrcRuleNbr) {
        this.apsSrcRuleNbr = apsSrcRuleNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APS_SPLY_SUB_POOL_NBR", nullable=false, insertable=false, updatable=false)  // TODO DUAL
    public ApsSplySubPool getApsSplySubPool() {
        return this.apsSplySubPool;
    }
    
    public void setApsSplySubPool(ApsSplySubPool apsSplySubPool) {
        this.apsSplySubPool = apsSplySubPool;
    }

    // TODO DUAL
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APS_SRC_RULE_SET_NBR", nullable=false, insertable=false, updatable=false)
    public ApsSrcRuleSet getApsSrcRuleSet() {
        return this.apsSrcRuleSet;
    }
    
    public void setApsSrcRuleSet(ApsSrcRuleSet apsSrcRuleSet) {
        this.apsSrcRuleSet = apsSrcRuleSet;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FACILITY", nullable=false, insertable=false, updatable=false)
    public UtFacility getUtFacility() {
        return this.utFacility;
    }
    
    public void setUtFacility(UtFacility utFacility) {
        this.utFacility = utFacility;
    }

    
    @Column(name="SPLY_TYPE_ID", nullable=false, length=1)
    public String getSplyTypeId() {
        return this.splyTypeId;
    }
    
    public void setSplyTypeId(String splyTypeId) {
        this.splyTypeId = splyTypeId;
    }

    
    @Column(name="SRC_PRTY", nullable=false, precision=3, scale=0)
    public short getSrcPrty() {
        return this.srcPrty;
    }
    
    public void setSrcPrty(short srcPrty) {
        this.srcPrty = srcPrty;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }

    @Column(name="APS_SRC_RULE_SET_NBR", nullable=false)
	public int getApsSrcRuleSetNbr() {
		return apsSrcRuleSetNbr;
	}


	public void setApsSrcRuleSetNbr(int apsSrcRuleSetNbr) {
		this.apsSrcRuleSetNbr = apsSrcRuleSetNbr;
	}

    @Column(name="APS_SPLY_SUB_POOL_NBR", nullable=false)
	public int getApsSplySubPoolNbr() {
		return apsSplySubPoolNbr;
	}


	public void setApsSplySubPoolNbr(int apsSplySubPoolNbr) {
		this.apsSplySubPoolNbr = apsSplySubPoolNbr;
	}

    @Column(name="FACILITY", nullable=false)
	public String getFacility() {
		return facility;
	}


	public void setFacility(String facility) {
		this.facility = facility;
	}

	@Override
	public String toString() {
		return 
					"ApsSrcRule [apsSrcRuleNbr=" + apsSrcRuleNbr + ", "
						+ "apsSrcRuleSetNbr=" + apsSrcRuleSetNbr + ", "
				+ "apsSplySubPoolNbr=" + apsSplySubPoolNbr
								+ "splyTypeId=" + splyTypeId + 
								", srcPrty=" + srcPrty + "]";
	}






}


