package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApsSummaryDat generated by hbm2java
 */
@Entity
@Table(name="APS_SUMMARY_DAT"
)
public class ApsSummaryDat  implements java.io.Serializable {


     private int apsSummaryDatNbr;
     private ApsSplyPool apsSplyPool;
     private UtFacility utFacility;
     private IcItemMast icItemMast;
     private String stkUm;
     private Date bucketStartDt;
     private BigDecimal totPoQty;
     private BigDecimal totOoQty;
     private BigDecimal totWoSplyQty;
     private BigDecimal totWoDmdQty;
     private BigDecimal totFcstQty;
     private BigDecimal totSsQty;
     private BigDecimal totUnallocQty;
     private BigDecimal totReschedQty;
     private BigDecimal totProjPosQty;
     private BigDecimal totShortfallQty;

    public ApsSummaryDat() {
    }

	
    public ApsSummaryDat(int apsSummaryDatNbr, ApsSplyPool apsSplyPool, UtFacility utFacility, IcItemMast icItemMast, Date bucketStartDt) {
        this.apsSummaryDatNbr = apsSummaryDatNbr;
        this.apsSplyPool = apsSplyPool;
        this.utFacility = utFacility;
        this.icItemMast = icItemMast;
        this.bucketStartDt = bucketStartDt;
    }
    public ApsSummaryDat(int apsSummaryDatNbr, ApsSplyPool apsSplyPool, UtFacility utFacility, IcItemMast icItemMast, String stkUm, Date bucketStartDt, BigDecimal totPoQty, BigDecimal totOoQty, BigDecimal totWoSplyQty, BigDecimal totWoDmdQty, BigDecimal totFcstQty, BigDecimal totSsQty, BigDecimal totUnallocQty, BigDecimal totReschedQty, BigDecimal totProjPosQty, BigDecimal totShortfallQty) {
       this.apsSummaryDatNbr = apsSummaryDatNbr;
       this.apsSplyPool = apsSplyPool;
       this.utFacility = utFacility;
       this.icItemMast = icItemMast;
       this.stkUm = stkUm;
       this.bucketStartDt = bucketStartDt;
       this.totPoQty = totPoQty;
       this.totOoQty = totOoQty;
       this.totWoSplyQty = totWoSplyQty;
       this.totWoDmdQty = totWoDmdQty;
       this.totFcstQty = totFcstQty;
       this.totSsQty = totSsQty;
       this.totUnallocQty = totUnallocQty;
       this.totReschedQty = totReschedQty;
       this.totProjPosQty = totProjPosQty;
       this.totShortfallQty = totShortfallQty;
    }
   
     @Id 

    
    @Column(name="APS_SUMMARY_DAT_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getApsSummaryDatNbr() {
        return this.apsSummaryDatNbr;
    }
    
    public void setApsSummaryDatNbr(int apsSummaryDatNbr) {
        this.apsSummaryDatNbr = apsSummaryDatNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APS_SPLY_POOL_CD", nullable=false)
    public ApsSplyPool getApsSplyPool() {
        return this.apsSplyPool;
    }
    
    public void setApsSplyPool(ApsSplyPool apsSplyPool) {
        this.apsSplyPool = apsSplyPool;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FACILITY", nullable=false)
    public UtFacility getUtFacility() {
        return this.utFacility;
    }
    
    public void setUtFacility(UtFacility utFacility) {
        this.utFacility = utFacility;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR", nullable=false)
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }

    
    @Column(name="STK_UM", length=3)
    public String getStkUm() {
        return this.stkUm;
    }
    
    public void setStkUm(String stkUm) {
        this.stkUm = stkUm;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="BUCKET_START_DT", nullable=false, length=7)
    public Date getBucketStartDt() {
        return this.bucketStartDt;
    }
    
    public void setBucketStartDt(Date bucketStartDt) {
        this.bucketStartDt = bucketStartDt;
    }

    
    @Column(name="TOT_PO_QTY", precision=13, scale=5)
    public BigDecimal getTotPoQty() {
        return this.totPoQty;
    }
    
    public void setTotPoQty(BigDecimal totPoQty) {
        this.totPoQty = totPoQty;
    }

    
    @Column(name="TOT_OO_QTY", precision=13, scale=5)
    public BigDecimal getTotOoQty() {
        return this.totOoQty;
    }
    
    public void setTotOoQty(BigDecimal totOoQty) {
        this.totOoQty = totOoQty;
    }

    
    @Column(name="TOT_WO_SPLY_QTY", precision=13, scale=5)
    public BigDecimal getTotWoSplyQty() {
        return this.totWoSplyQty;
    }
    
    public void setTotWoSplyQty(BigDecimal totWoSplyQty) {
        this.totWoSplyQty = totWoSplyQty;
    }

    
    @Column(name="TOT_WO_DMD_QTY", precision=13, scale=5)
    public BigDecimal getTotWoDmdQty() {
        return this.totWoDmdQty;
    }
    
    public void setTotWoDmdQty(BigDecimal totWoDmdQty) {
        this.totWoDmdQty = totWoDmdQty;
    }

    
    @Column(name="TOT_FCST_QTY", precision=13, scale=5)
    public BigDecimal getTotFcstQty() {
        return this.totFcstQty;
    }
    
    public void setTotFcstQty(BigDecimal totFcstQty) {
        this.totFcstQty = totFcstQty;
    }

    
    @Column(name="TOT_SS_QTY", precision=13, scale=5)
    public BigDecimal getTotSsQty() {
        return this.totSsQty;
    }
    
    public void setTotSsQty(BigDecimal totSsQty) {
        this.totSsQty = totSsQty;
    }

    
    @Column(name="TOT_UNALLOC_QTY", precision=13, scale=5)
    public BigDecimal getTotUnallocQty() {
        return this.totUnallocQty;
    }
    
    public void setTotUnallocQty(BigDecimal totUnallocQty) {
        this.totUnallocQty = totUnallocQty;
    }

    
    @Column(name="TOT_RESCHED_QTY", precision=13, scale=5)
    public BigDecimal getTotReschedQty() {
        return this.totReschedQty;
    }
    
    public void setTotReschedQty(BigDecimal totReschedQty) {
        this.totReschedQty = totReschedQty;
    }

    
    @Column(name="TOT_PROJ_POS_QTY", precision=13, scale=5)
    public BigDecimal getTotProjPosQty() {
        return this.totProjPosQty;
    }
    
    public void setTotProjPosQty(BigDecimal totProjPosQty) {
        this.totProjPosQty = totProjPosQty;
    }

    
    @Column(name="TOT_SHORTFALL_QTY", precision=13, scale=5)
    public BigDecimal getTotShortfallQty() {
        return this.totShortfallQty;
    }
    
    public void setTotShortfallQty(BigDecimal totShortfallQty) {
        this.totShortfallQty = totShortfallQty;
    }




}


