package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ApsSrcRuleSetVw generated by hbm2java
 */
@Entity
@Table(name="APS_SRC_RULE_SET_VW"
)
public class ApsSrcRuleSetVw  implements java.io.Serializable {


     private ApsSrcRuleSetVwId id;

    public ApsSrcRuleSetVw() {
    }

    public ApsSrcRuleSetVw(ApsSrcRuleSetVwId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="apsSrcRuleSetNbr", column=@Column(name="APS_SRC_RULE_SET_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="apsSplySubPoolNbr", column=@Column(name="APS_SPLY_SUB_POOL_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="facility", column=@Column(name="FACILITY", nullable=false, length=16) ), 
        @AttributeOverride(name="splyTypeId", column=@Column(name="SPLY_TYPE_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="srcPrty", column=@Column(name="SRC_PRTY", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="utUserNbr", column=@Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="lastModDt", column=@Column(name="LAST_MOD_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="apsSrcRuleNbr", column=@Column(name="APS_SRC_RULE_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="apsSrcRuleSetCd", column=@Column(name="APS_SRC_RULE_SET_CD", nullable=false, length=20) ), 
        @AttributeOverride(name="apsSrcRuleSetDescr", column=@Column(name="APS_SRC_RULE_SET_DESCR", length=60) ), 
        @AttributeOverride(name="apsSplyPoolCd", column=@Column(name="APS_SPLY_POOL_CD", nullable=false, length=20) ), 
        @AttributeOverride(name="apsSplySubPoolCd", column=@Column(name="APS_SPLY_SUB_POOL_CD", nullable=false, length=20) ), 
        @AttributeOverride(name="splyPoolTypeId", column=@Column(name="SPLY_POOL_TYPE_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="splyPoolTypeDescr", column=@Column(name="SPLY_POOL_TYPE_DESCR", length=12) ), 
        @AttributeOverride(name="apsSplySubPoolDescr", column=@Column(name="APS_SPLY_SUB_POOL_DESCR", length=60) ), 
        @AttributeOverride(name="orgNbrVnd", column=@Column(name="ORG_NBR_VND", precision=9, scale=0) ), 
        @AttributeOverride(name="orgCd", column=@Column(name="ORG_CD", length=15) ) } )
    public ApsSrcRuleSetVwId getId() {
        return this.id;
    }
    
    public void setId(ApsSrcRuleSetVwId id) {
        this.id = id;
    }




}


