package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ArInvDtl generated by hbm2java
 */
@Entity
@Table(name="AR_INV_DTL"
)
public class ArInvDtl  implements java.io.Serializable {


     private int arInvDtlNbr;
     private ApsSplySubPool apsSplySubPool;
     private ArInvHdr arInvHdr;
     private PoMfrMast poMfrMast;
     private PoVndMast poVndMast;
     private UtFacility utFacility;
     private IcLotMast icLotMast;
     private IcUm icUm;
     private NaOrgAddr naOrgAddr;
     private OeOrdDtl oeOrdDtl;
     private IcItemMast icItemMast;
     private short lineNbr;
     private String ordCd;
     private short lineNbrOrd;
     private String custPoCd;
     private String custLineCd;
     private String itemCd;
     private String itemDescr;
     private String shipToAddrCd;
     private BigDecimal qtyOpen;
     private BigDecimal qtyShip;
     private String orgNmVnd;
     private String orgNmMfr;
     private String mfrLotCd;
     private String revLvl;
     private BigDecimal unitCostStkUm;
     private BigDecimal unitCostDenomStkUm;
     private BigDecimal unitCostSellUm;
     private BigDecimal unitCostDenomSellUm;
     private BigDecimal unitPriceStkUm;
     private BigDecimal unitPriceDenomStkUm;
     private BigDecimal unitPriceSellUm;
     private BigDecimal unitPriceDenomSellUm;
     private String tieCd;
     private String contractCd;
     private String custBinCd;
     private String orgCdMfr;
     private String orgCdVnd;
     private BigDecimal qtyOpenStkUm;
     private BigDecimal qtyShipStkUm;
     private String binCd;
     private Integer icCategoryNbr;
     private String icCategoryNm;
     private String icCategoryDescr;
     private String custBinCdNew;
     private Set<ArRmaDtl> arRmaDtls = new HashSet<ArRmaDtl>(0);

    public ArInvDtl() {
    }

	
    public ArInvDtl(int arInvDtlNbr, ApsSplySubPool apsSplySubPool, ArInvHdr arInvHdr, PoVndMast poVndMast, UtFacility utFacility, IcLotMast icLotMast, IcUm icUm, NaOrgAddr naOrgAddr, OeOrdDtl oeOrdDtl, IcItemMast icItemMast, short lineNbr, String ordCd, short lineNbrOrd, String itemCd, String itemDescr, String shipToAddrCd, BigDecimal qtyOpen, BigDecimal qtyShip, String orgNmVnd, String orgCdVnd, BigDecimal qtyOpenStkUm, BigDecimal qtyShipStkUm) {
        this.arInvDtlNbr = arInvDtlNbr;
        this.apsSplySubPool = apsSplySubPool;
        this.arInvHdr = arInvHdr;
        this.poVndMast = poVndMast;
        this.utFacility = utFacility;
        this.icLotMast = icLotMast;
        this.icUm = icUm;
        this.naOrgAddr = naOrgAddr;
        this.oeOrdDtl = oeOrdDtl;
        this.icItemMast = icItemMast;
        this.lineNbr = lineNbr;
        this.ordCd = ordCd;
        this.lineNbrOrd = lineNbrOrd;
        this.itemCd = itemCd;
        this.itemDescr = itemDescr;
        this.shipToAddrCd = shipToAddrCd;
        this.qtyOpen = qtyOpen;
        this.qtyShip = qtyShip;
        this.orgNmVnd = orgNmVnd;
        this.orgCdVnd = orgCdVnd;
        this.qtyOpenStkUm = qtyOpenStkUm;
        this.qtyShipStkUm = qtyShipStkUm;
    }
    public ArInvDtl(int arInvDtlNbr, ApsSplySubPool apsSplySubPool, ArInvHdr arInvHdr, PoMfrMast poMfrMast, PoVndMast poVndMast, UtFacility utFacility, IcLotMast icLotMast, IcUm icUm, NaOrgAddr naOrgAddr, OeOrdDtl oeOrdDtl, IcItemMast icItemMast, short lineNbr, String ordCd, short lineNbrOrd, String custPoCd, String custLineCd, String itemCd, String itemDescr, String shipToAddrCd, BigDecimal qtyOpen, BigDecimal qtyShip, String orgNmVnd, String orgNmMfr, String mfrLotCd, String revLvl, BigDecimal unitCostStkUm, BigDecimal unitCostDenomStkUm, BigDecimal unitCostSellUm, BigDecimal unitCostDenomSellUm, BigDecimal unitPriceStkUm, BigDecimal unitPriceDenomStkUm, BigDecimal unitPriceSellUm, BigDecimal unitPriceDenomSellUm, String tieCd, String contractCd, String custBinCd, String orgCdMfr, String orgCdVnd, BigDecimal qtyOpenStkUm, BigDecimal qtyShipStkUm, String binCd, Integer icCategoryNbr, String icCategoryNm, String icCategoryDescr, String custBinCdNew, Set<ArRmaDtl> arRmaDtls) {
       this.arInvDtlNbr = arInvDtlNbr;
       this.apsSplySubPool = apsSplySubPool;
       this.arInvHdr = arInvHdr;
       this.poMfrMast = poMfrMast;
       this.poVndMast = poVndMast;
       this.utFacility = utFacility;
       this.icLotMast = icLotMast;
       this.icUm = icUm;
       this.naOrgAddr = naOrgAddr;
       this.oeOrdDtl = oeOrdDtl;
       this.icItemMast = icItemMast;
       this.lineNbr = lineNbr;
       this.ordCd = ordCd;
       this.lineNbrOrd = lineNbrOrd;
       this.custPoCd = custPoCd;
       this.custLineCd = custLineCd;
       this.itemCd = itemCd;
       this.itemDescr = itemDescr;
       this.shipToAddrCd = shipToAddrCd;
       this.qtyOpen = qtyOpen;
       this.qtyShip = qtyShip;
       this.orgNmVnd = orgNmVnd;
       this.orgNmMfr = orgNmMfr;
       this.mfrLotCd = mfrLotCd;
       this.revLvl = revLvl;
       this.unitCostStkUm = unitCostStkUm;
       this.unitCostDenomStkUm = unitCostDenomStkUm;
       this.unitCostSellUm = unitCostSellUm;
       this.unitCostDenomSellUm = unitCostDenomSellUm;
       this.unitPriceStkUm = unitPriceStkUm;
       this.unitPriceDenomStkUm = unitPriceDenomStkUm;
       this.unitPriceSellUm = unitPriceSellUm;
       this.unitPriceDenomSellUm = unitPriceDenomSellUm;
       this.tieCd = tieCd;
       this.contractCd = contractCd;
       this.custBinCd = custBinCd;
       this.orgCdMfr = orgCdMfr;
       this.orgCdVnd = orgCdVnd;
       this.qtyOpenStkUm = qtyOpenStkUm;
       this.qtyShipStkUm = qtyShipStkUm;
       this.binCd = binCd;
       this.icCategoryNbr = icCategoryNbr;
       this.icCategoryNm = icCategoryNm;
       this.icCategoryDescr = icCategoryDescr;
       this.custBinCdNew = custBinCdNew;
       this.arRmaDtls = arRmaDtls;
    }
   
     @Id 

    
    @Column(name="AR_INV_DTL_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getArInvDtlNbr() {
        return this.arInvDtlNbr;
    }
    
    public void setArInvDtlNbr(int arInvDtlNbr) {
        this.arInvDtlNbr = arInvDtlNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APS_SPLY_SUB_POOL_NBR", nullable=false)
    public ApsSplySubPool getApsSplySubPool() {
        return this.apsSplySubPool;
    }
    
    public void setApsSplySubPool(ApsSplySubPool apsSplySubPool) {
        this.apsSplySubPool = apsSplySubPool;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="INV_CD", nullable=false)
    public ArInvHdr getArInvHdr() {
        return this.arInvHdr;
    }
    
    public void setArInvHdr(ArInvHdr arInvHdr) {
        this.arInvHdr = arInvHdr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORG_NBR_MFR")
    public PoMfrMast getPoMfrMast() {
        return this.poMfrMast;
    }
    
    public void setPoMfrMast(PoMfrMast poMfrMast) {
        this.poMfrMast = poMfrMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORG_NBR_VND", nullable=false)
    public PoVndMast getPoVndMast() {
        return this.poVndMast;
    }
    
    public void setPoVndMast(PoVndMast poVndMast) {
        this.poVndMast = poVndMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FACILITY", nullable=false)
    public UtFacility getUtFacility() {
        return this.utFacility;
    }
    
    public void setUtFacility(UtFacility utFacility) {
        this.utFacility = utFacility;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LOT_NBR", nullable=false)
    public IcLotMast getIcLotMast() {
        return this.icLotMast;
    }
    
    public void setIcLotMast(IcLotMast icLotMast) {
        this.icLotMast = icLotMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SELL_UM", nullable=false)
    public IcUm getIcUm() {
        return this.icUm;
    }
    
    public void setIcUm(IcUm icUm) {
        this.icUm = icUm;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SHIP_TO_ADDR_NBR", nullable=false)
    public NaOrgAddr getNaOrgAddr() {
        return this.naOrgAddr;
    }
    
    public void setNaOrgAddr(NaOrgAddr naOrgAddr) {
        this.naOrgAddr = naOrgAddr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OE_ORD_DTL_NBR", nullable=false)
    public OeOrdDtl getOeOrdDtl() {
        return this.oeOrdDtl;
    }
    
    public void setOeOrdDtl(OeOrdDtl oeOrdDtl) {
        this.oeOrdDtl = oeOrdDtl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR", nullable=false)
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }

    
    @Column(name="LINE_NBR", nullable=false, precision=3, scale=0)
    public short getLineNbr() {
        return this.lineNbr;
    }
    
    public void setLineNbr(short lineNbr) {
        this.lineNbr = lineNbr;
    }

    
    @Column(name="ORD_CD", nullable=false, length=20)
    public String getOrdCd() {
        return this.ordCd;
    }
    
    public void setOrdCd(String ordCd) {
        this.ordCd = ordCd;
    }

    
    @Column(name="LINE_NBR_ORD", nullable=false, precision=4, scale=0)
    public short getLineNbrOrd() {
        return this.lineNbrOrd;
    }
    
    public void setLineNbrOrd(short lineNbrOrd) {
        this.lineNbrOrd = lineNbrOrd;
    }

    
    @Column(name="CUST_PO_CD", length=30)
    public String getCustPoCd() {
        return this.custPoCd;
    }
    
    public void setCustPoCd(String custPoCd) {
        this.custPoCd = custPoCd;
    }

    
    @Column(name="CUST_LINE_CD", length=5)
    public String getCustLineCd() {
        return this.custLineCd;
    }
    
    public void setCustLineCd(String custLineCd) {
        this.custLineCd = custLineCd;
    }

    
    @Column(name="ITEM_CD", nullable=false, length=50)
    public String getItemCd() {
        return this.itemCd;
    }
    
    public void setItemCd(String itemCd) {
        this.itemCd = itemCd;
    }

    
    @Column(name="ITEM_DESCR", nullable=false, length=50)
    public String getItemDescr() {
        return this.itemDescr;
    }
    
    public void setItemDescr(String itemDescr) {
        this.itemDescr = itemDescr;
    }

    
    @Column(name="SHIP_TO_ADDR_CD", nullable=false, length=16)
    public String getShipToAddrCd() {
        return this.shipToAddrCd;
    }
    
    public void setShipToAddrCd(String shipToAddrCd) {
        this.shipToAddrCd = shipToAddrCd;
    }

    
    @Column(name="QTY_OPEN", nullable=false, precision=13, scale=5)
    public BigDecimal getQtyOpen() {
        return this.qtyOpen;
    }
    
    public void setQtyOpen(BigDecimal qtyOpen) {
        this.qtyOpen = qtyOpen;
    }

    
    @Column(name="QTY_SHIP", nullable=false, precision=13, scale=5)
    public BigDecimal getQtyShip() {
        return this.qtyShip;
    }
    
    public void setQtyShip(BigDecimal qtyShip) {
        this.qtyShip = qtyShip;
    }

    
    @Column(name="ORG_NM_VND", nullable=false, length=60)
    public String getOrgNmVnd() {
        return this.orgNmVnd;
    }
    
    public void setOrgNmVnd(String orgNmVnd) {
        this.orgNmVnd = orgNmVnd;
    }

    
    @Column(name="ORG_NM_MFR", length=60)
    public String getOrgNmMfr() {
        return this.orgNmMfr;
    }
    
    public void setOrgNmMfr(String orgNmMfr) {
        this.orgNmMfr = orgNmMfr;
    }

    
    @Column(name="MFR_LOT_CD", length=20)
    public String getMfrLotCd() {
        return this.mfrLotCd;
    }
    
    public void setMfrLotCd(String mfrLotCd) {
        this.mfrLotCd = mfrLotCd;
    }

    
    @Column(name="REV_LVL", length=5)
    public String getRevLvl() {
        return this.revLvl;
    }
    
    public void setRevLvl(String revLvl) {
        this.revLvl = revLvl;
    }

    
    @Column(name="UNIT_COST_STK_UM", precision=17, scale=6)
    public BigDecimal getUnitCostStkUm() {
        return this.unitCostStkUm;
    }
    
    public void setUnitCostStkUm(BigDecimal unitCostStkUm) {
        this.unitCostStkUm = unitCostStkUm;
    }

    
    @Column(name="UNIT_COST_DENOM_STK_UM", precision=17, scale=6)
    public BigDecimal getUnitCostDenomStkUm() {
        return this.unitCostDenomStkUm;
    }
    
    public void setUnitCostDenomStkUm(BigDecimal unitCostDenomStkUm) {
        this.unitCostDenomStkUm = unitCostDenomStkUm;
    }

    
    @Column(name="UNIT_COST_SELL_UM", precision=17, scale=6)
    public BigDecimal getUnitCostSellUm() {
        return this.unitCostSellUm;
    }
    
    public void setUnitCostSellUm(BigDecimal unitCostSellUm) {
        this.unitCostSellUm = unitCostSellUm;
    }

    
    @Column(name="UNIT_COST_DENOM_SELL_UM", precision=17, scale=6)
    public BigDecimal getUnitCostDenomSellUm() {
        return this.unitCostDenomSellUm;
    }
    
    public void setUnitCostDenomSellUm(BigDecimal unitCostDenomSellUm) {
        this.unitCostDenomSellUm = unitCostDenomSellUm;
    }

    
    @Column(name="UNIT_PRICE_STK_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceStkUm() {
        return this.unitPriceStkUm;
    }
    
    public void setUnitPriceStkUm(BigDecimal unitPriceStkUm) {
        this.unitPriceStkUm = unitPriceStkUm;
    }

    
    @Column(name="UNIT_PRICE_DENOM_STK_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceDenomStkUm() {
        return this.unitPriceDenomStkUm;
    }
    
    public void setUnitPriceDenomStkUm(BigDecimal unitPriceDenomStkUm) {
        this.unitPriceDenomStkUm = unitPriceDenomStkUm;
    }

    
    @Column(name="UNIT_PRICE_SELL_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceSellUm() {
        return this.unitPriceSellUm;
    }
    
    public void setUnitPriceSellUm(BigDecimal unitPriceSellUm) {
        this.unitPriceSellUm = unitPriceSellUm;
    }

    
    @Column(name="UNIT_PRICE_DENOM_SELL_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceDenomSellUm() {
        return this.unitPriceDenomSellUm;
    }
    
    public void setUnitPriceDenomSellUm(BigDecimal unitPriceDenomSellUm) {
        this.unitPriceDenomSellUm = unitPriceDenomSellUm;
    }

    
    @Column(name="TIE_CD", length=1)
    public String getTieCd() {
        return this.tieCd;
    }
    
    public void setTieCd(String tieCd) {
        this.tieCd = tieCd;
    }

    
    @Column(name="CONTRACT_CD", length=8)
    public String getContractCd() {
        return this.contractCd;
    }
    
    public void setContractCd(String contractCd) {
        this.contractCd = contractCd;
    }

    
    @Column(name="CUST_BIN_CD", length=40)
    public String getCustBinCd() {
        return this.custBinCd;
    }
    
    public void setCustBinCd(String custBinCd) {
        this.custBinCd = custBinCd;
    }

    
    @Column(name="ORG_CD_MFR", length=15)
    public String getOrgCdMfr() {
        return this.orgCdMfr;
    }
    
    public void setOrgCdMfr(String orgCdMfr) {
        this.orgCdMfr = orgCdMfr;
    }

    
    @Column(name="ORG_CD_VND", nullable=false, length=15)
    public String getOrgCdVnd() {
        return this.orgCdVnd;
    }
    
    public void setOrgCdVnd(String orgCdVnd) {
        this.orgCdVnd = orgCdVnd;
    }

    
    @Column(name="QTY_OPEN_STK_UM", nullable=false, precision=13, scale=5)
    public BigDecimal getQtyOpenStkUm() {
        return this.qtyOpenStkUm;
    }
    
    public void setQtyOpenStkUm(BigDecimal qtyOpenStkUm) {
        this.qtyOpenStkUm = qtyOpenStkUm;
    }

    
    @Column(name="QTY_SHIP_STK_UM", nullable=false, precision=13, scale=5)
    public BigDecimal getQtyShipStkUm() {
        return this.qtyShipStkUm;
    }
    
    public void setQtyShipStkUm(BigDecimal qtyShipStkUm) {
        this.qtyShipStkUm = qtyShipStkUm;
    }

    
    @Column(name="BIN_CD", length=16)
    public String getBinCd() {
        return this.binCd;
    }
    
    public void setBinCd(String binCd) {
        this.binCd = binCd;
    }

    
    @Column(name="IC_CATEGORY_NBR", precision=9, scale=0)
    public Integer getIcCategoryNbr() {
        return this.icCategoryNbr;
    }
    
    public void setIcCategoryNbr(Integer icCategoryNbr) {
        this.icCategoryNbr = icCategoryNbr;
    }

    
    @Column(name="IC_CATEGORY_NM", length=16)
    public String getIcCategoryNm() {
        return this.icCategoryNm;
    }
    
    public void setIcCategoryNm(String icCategoryNm) {
        this.icCategoryNm = icCategoryNm;
    }

    
    @Column(name="IC_CATEGORY_DESCR", length=60)
    public String getIcCategoryDescr() {
        return this.icCategoryDescr;
    }
    
    public void setIcCategoryDescr(String icCategoryDescr) {
        this.icCategoryDescr = icCategoryDescr;
    }

    
    @Column(name="CUST_BIN_CD_NEW", length=40)
    public String getCustBinCdNew() {
        return this.custBinCdNew;
    }
    
    public void setCustBinCdNew(String custBinCdNew) {
        this.custBinCdNew = custBinCdNew;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="arInvDtl")
    public Set<ArRmaDtl> getArRmaDtls() {
        return this.arRmaDtls;
    }
    
    public void setArRmaDtls(Set<ArRmaDtl> arRmaDtls) {
        this.arRmaDtls = arRmaDtls;
    }




}


