package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArInvHdr generated by hbm2java
 */
@Entity
@Table(name="AR_INV_HDR"
)
public class ArInvHdr  implements java.io.Serializable {


     private String invCd;
     private NaIndiv naIndiv;
     private NaOrgAddr naOrgAddrByShipToAddrNbr;
     private NaOrgAddr naOrgAddrByBillToAddrNbr;
     private OeCustMast oeCustMast;
     private OeOrdHdr oeOrdHdr;
     private Currency currency;
     private Date invDt;
     private String invStatId;
     private String orgNmCust;
     private String ordCd;
     private String custPoCd;
     private Date shipDt;
     private String billToAddrCd;
     private String billToAddrDescr;
     private String billToAddr1;
     private String billToAddr2;
     private String billToAddr3;
     private String billToCity;
     private String billToStateCd;
     private String billToPostalCd;
     private String billToCntryCd;
     private String shipToAddrCd;
     private String shipToAddrDescr;
     private String shipToAddr1;
     private String shipToAddr2;
     private String shipToAddr3;
     private String shipToCity;
     private String shipToStateCd;
     private String shipToPostalCd;
     private String shipToCntryCd;
     private String shipViaCd;
     private String termCd;
     private BigDecimal grossInvValue;
     private BigDecimal wght;
     private Integer ctnCnt;
     private BigDecimal frgtCharge;
     private BigDecimal netInvValue;
     private String waybillCd;
     private String trdFlg;
     private Integer arInvBatchNbr;
     private String fobCd;
     private String orgCdCust;
     private String salesTerrCd;
     private Integer arSummaryInvNbr;
     private Integer glTaxGrpNbr;
     private String printFlg;
     private Date invPrintDtOrig;
     private Date invPrintDtLast;
     private Integer utUserNbrPrint;
     private String ordTypeCd;
     private String summaryInvRef;
     private Integer whShipPrtyNbr;
     private String paymentMethodCd;
     private Set<ArInvDtl> arInvDtls = new HashSet<ArInvDtl>(0);

    public ArInvHdr() {
    }

	
    public ArInvHdr(String invCd, NaOrgAddr naOrgAddrByShipToAddrNbr, NaOrgAddr naOrgAddrByBillToAddrNbr, OeCustMast oeCustMast, OeOrdHdr oeOrdHdr, Currency currency, Date invDt, String invStatId, String orgNmCust, String ordCd, Date shipDt, String billToAddrCd, String shipToAddrCd, String shipViaCd, String termCd, BigDecimal grossInvValue, String trdFlg, String orgCdCust, String salesTerrCd, String printFlg, String ordTypeCd) {
        this.invCd = invCd;
        this.naOrgAddrByShipToAddrNbr = naOrgAddrByShipToAddrNbr;
        this.naOrgAddrByBillToAddrNbr = naOrgAddrByBillToAddrNbr;
        this.oeCustMast = oeCustMast;
        this.oeOrdHdr = oeOrdHdr;
        this.currency = currency;
        this.invDt = invDt;
        this.invStatId = invStatId;
        this.orgNmCust = orgNmCust;
        this.ordCd = ordCd;
        this.shipDt = shipDt;
        this.billToAddrCd = billToAddrCd;
        this.shipToAddrCd = shipToAddrCd;
        this.shipViaCd = shipViaCd;
        this.termCd = termCd;
        this.grossInvValue = grossInvValue;
        this.trdFlg = trdFlg;
        this.orgCdCust = orgCdCust;
        this.salesTerrCd = salesTerrCd;
        this.printFlg = printFlg;
        this.ordTypeCd = ordTypeCd;
    }
    public ArInvHdr(String invCd, NaIndiv naIndiv, NaOrgAddr naOrgAddrByShipToAddrNbr, NaOrgAddr naOrgAddrByBillToAddrNbr, OeCustMast oeCustMast, OeOrdHdr oeOrdHdr, Currency currency, Date invDt, String invStatId, String orgNmCust, String ordCd, String custPoCd, Date shipDt, String billToAddrCd, String billToAddrDescr, String billToAddr1, String billToAddr2, String billToAddr3, String billToCity, String billToStateCd, String billToPostalCd, String billToCntryCd, String shipToAddrCd, String shipToAddrDescr, String shipToAddr1, String shipToAddr2, String shipToAddr3, String shipToCity, String shipToStateCd, String shipToPostalCd, String shipToCntryCd, String shipViaCd, String termCd, BigDecimal grossInvValue, BigDecimal wght, Integer ctnCnt, BigDecimal frgtCharge, BigDecimal netInvValue, String waybillCd, String trdFlg, Integer arInvBatchNbr, String fobCd, String orgCdCust, String salesTerrCd, Integer arSummaryInvNbr, Integer glTaxGrpNbr, String printFlg, Date invPrintDtOrig, Date invPrintDtLast, Integer utUserNbrPrint, String ordTypeCd, String summaryInvRef, Integer whShipPrtyNbr, String paymentMethodCd, Set<ArInvDtl> arInvDtls) {
       this.invCd = invCd;
       this.naIndiv = naIndiv;
       this.naOrgAddrByShipToAddrNbr = naOrgAddrByShipToAddrNbr;
       this.naOrgAddrByBillToAddrNbr = naOrgAddrByBillToAddrNbr;
       this.oeCustMast = oeCustMast;
       this.oeOrdHdr = oeOrdHdr;
       this.currency = currency;
       this.invDt = invDt;
       this.invStatId = invStatId;
       this.orgNmCust = orgNmCust;
       this.ordCd = ordCd;
       this.custPoCd = custPoCd;
       this.shipDt = shipDt;
       this.billToAddrCd = billToAddrCd;
       this.billToAddrDescr = billToAddrDescr;
       this.billToAddr1 = billToAddr1;
       this.billToAddr2 = billToAddr2;
       this.billToAddr3 = billToAddr3;
       this.billToCity = billToCity;
       this.billToStateCd = billToStateCd;
       this.billToPostalCd = billToPostalCd;
       this.billToCntryCd = billToCntryCd;
       this.shipToAddrCd = shipToAddrCd;
       this.shipToAddrDescr = shipToAddrDescr;
       this.shipToAddr1 = shipToAddr1;
       this.shipToAddr2 = shipToAddr2;
       this.shipToAddr3 = shipToAddr3;
       this.shipToCity = shipToCity;
       this.shipToStateCd = shipToStateCd;
       this.shipToPostalCd = shipToPostalCd;
       this.shipToCntryCd = shipToCntryCd;
       this.shipViaCd = shipViaCd;
       this.termCd = termCd;
       this.grossInvValue = grossInvValue;
       this.wght = wght;
       this.ctnCnt = ctnCnt;
       this.frgtCharge = frgtCharge;
       this.netInvValue = netInvValue;
       this.waybillCd = waybillCd;
       this.trdFlg = trdFlg;
       this.arInvBatchNbr = arInvBatchNbr;
       this.fobCd = fobCd;
       this.orgCdCust = orgCdCust;
       this.salesTerrCd = salesTerrCd;
       this.arSummaryInvNbr = arSummaryInvNbr;
       this.glTaxGrpNbr = glTaxGrpNbr;
       this.printFlg = printFlg;
       this.invPrintDtOrig = invPrintDtOrig;
       this.invPrintDtLast = invPrintDtLast;
       this.utUserNbrPrint = utUserNbrPrint;
       this.ordTypeCd = ordTypeCd;
       this.summaryInvRef = summaryInvRef;
       this.whShipPrtyNbr = whShipPrtyNbr;
       this.paymentMethodCd = paymentMethodCd;
       this.arInvDtls = arInvDtls;
    }
   
     @Id 

    
    @Column(name="INV_CD", unique=true, nullable=false, length=20)
    public String getInvCd() {
        return this.invCd;
    }
    
    public void setInvCd(String invCd) {
        this.invCd = invCd;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SELL_INDIV_NBR")
    public NaIndiv getNaIndiv() {
        return this.naIndiv;
    }
    
    public void setNaIndiv(NaIndiv naIndiv) {
        this.naIndiv = naIndiv;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SHIP_TO_ADDR_NBR", nullable=false)
    public NaOrgAddr getNaOrgAddrByShipToAddrNbr() {
        return this.naOrgAddrByShipToAddrNbr;
    }
    
    public void setNaOrgAddrByShipToAddrNbr(NaOrgAddr naOrgAddrByShipToAddrNbr) {
        this.naOrgAddrByShipToAddrNbr = naOrgAddrByShipToAddrNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BILL_TO_ADDR_NBR", nullable=false)
    public NaOrgAddr getNaOrgAddrByBillToAddrNbr() {
        return this.naOrgAddrByBillToAddrNbr;
    }
    
    public void setNaOrgAddrByBillToAddrNbr(NaOrgAddr naOrgAddrByBillToAddrNbr) {
        this.naOrgAddrByBillToAddrNbr = naOrgAddrByBillToAddrNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORG_NBR_CUST", nullable=false)
    public OeCustMast getOeCustMast() {
        return this.oeCustMast;
    }
    
    public void setOeCustMast(OeCustMast oeCustMast) {
        this.oeCustMast = oeCustMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OE_ORD_HDR_NBR", nullable=false)
    public OeOrdHdr getOeOrdHdr() {
        return this.oeOrdHdr;
    }
    
    public void setOeOrdHdr(OeOrdHdr oeOrdHdr) {
        this.oeOrdHdr = oeOrdHdr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CURR_CD", nullable=false)
    public Currency getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(Currency currency) {
        this.currency = currency;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="INV_DT", nullable=false, length=7)
    public Date getInvDt() {
        return this.invDt;
    }
    
    public void setInvDt(Date invDt) {
        this.invDt = invDt;
    }

    
    @Column(name="INV_STAT_ID", nullable=false, length=1)
    public String getInvStatId() {
        return this.invStatId;
    }
    
    public void setInvStatId(String invStatId) {
        this.invStatId = invStatId;
    }

    
    @Column(name="ORG_NM_CUST", nullable=false, length=60)
    public String getOrgNmCust() {
        return this.orgNmCust;
    }
    
    public void setOrgNmCust(String orgNmCust) {
        this.orgNmCust = orgNmCust;
    }

    
    @Column(name="ORD_CD", nullable=false, length=20)
    public String getOrdCd() {
        return this.ordCd;
    }
    
    public void setOrdCd(String ordCd) {
        this.ordCd = ordCd;
    }

    
    @Column(name="CUST_PO_CD", length=30)
    public String getCustPoCd() {
        return this.custPoCd;
    }
    
    public void setCustPoCd(String custPoCd) {
        this.custPoCd = custPoCd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SHIP_DT", nullable=false, length=7)
    public Date getShipDt() {
        return this.shipDt;
    }
    
    public void setShipDt(Date shipDt) {
        this.shipDt = shipDt;
    }

    
    @Column(name="BILL_TO_ADDR_CD", nullable=false, length=8)
    public String getBillToAddrCd() {
        return this.billToAddrCd;
    }
    
    public void setBillToAddrCd(String billToAddrCd) {
        this.billToAddrCd = billToAddrCd;
    }

    
    @Column(name="BILL_TO_ADDR_DESCR", length=60)
    public String getBillToAddrDescr() {
        return this.billToAddrDescr;
    }
    
    public void setBillToAddrDescr(String billToAddrDescr) {
        this.billToAddrDescr = billToAddrDescr;
    }

    
    @Column(name="BILL_TO_ADDR_1", length=30)
    public String getBillToAddr1() {
        return this.billToAddr1;
    }
    
    public void setBillToAddr1(String billToAddr1) {
        this.billToAddr1 = billToAddr1;
    }

    
    @Column(name="BILL_TO_ADDR_2", length=30)
    public String getBillToAddr2() {
        return this.billToAddr2;
    }
    
    public void setBillToAddr2(String billToAddr2) {
        this.billToAddr2 = billToAddr2;
    }

    
    @Column(name="BILL_TO_ADDR_3", length=30)
    public String getBillToAddr3() {
        return this.billToAddr3;
    }
    
    public void setBillToAddr3(String billToAddr3) {
        this.billToAddr3 = billToAddr3;
    }

    
    @Column(name="BILL_TO_CITY", length=25)
    public String getBillToCity() {
        return this.billToCity;
    }
    
    public void setBillToCity(String billToCity) {
        this.billToCity = billToCity;
    }

    
    @Column(name="BILL_TO_STATE_CD", length=5)
    public String getBillToStateCd() {
        return this.billToStateCd;
    }
    
    public void setBillToStateCd(String billToStateCd) {
        this.billToStateCd = billToStateCd;
    }

    
    @Column(name="BILL_TO_POSTAL_CD", length=10)
    public String getBillToPostalCd() {
        return this.billToPostalCd;
    }
    
    public void setBillToPostalCd(String billToPostalCd) {
        this.billToPostalCd = billToPostalCd;
    }

    
    @Column(name="BILL_TO_CNTRY_CD", length=3)
    public String getBillToCntryCd() {
        return this.billToCntryCd;
    }
    
    public void setBillToCntryCd(String billToCntryCd) {
        this.billToCntryCd = billToCntryCd;
    }

    
    @Column(name="SHIP_TO_ADDR_CD", nullable=false, length=8)
    public String getShipToAddrCd() {
        return this.shipToAddrCd;
    }
    
    public void setShipToAddrCd(String shipToAddrCd) {
        this.shipToAddrCd = shipToAddrCd;
    }

    
    @Column(name="SHIP_TO_ADDR_DESCR", length=60)
    public String getShipToAddrDescr() {
        return this.shipToAddrDescr;
    }
    
    public void setShipToAddrDescr(String shipToAddrDescr) {
        this.shipToAddrDescr = shipToAddrDescr;
    }

    
    @Column(name="SHIP_TO_ADDR_1", length=30)
    public String getShipToAddr1() {
        return this.shipToAddr1;
    }
    
    public void setShipToAddr1(String shipToAddr1) {
        this.shipToAddr1 = shipToAddr1;
    }

    
    @Column(name="SHIP_TO_ADDR_2", length=30)
    public String getShipToAddr2() {
        return this.shipToAddr2;
    }
    
    public void setShipToAddr2(String shipToAddr2) {
        this.shipToAddr2 = shipToAddr2;
    }

    
    @Column(name="SHIP_TO_ADDR_3", length=30)
    public String getShipToAddr3() {
        return this.shipToAddr3;
    }
    
    public void setShipToAddr3(String shipToAddr3) {
        this.shipToAddr3 = shipToAddr3;
    }

    
    @Column(name="SHIP_TO_CITY", length=25)
    public String getShipToCity() {
        return this.shipToCity;
    }
    
    public void setShipToCity(String shipToCity) {
        this.shipToCity = shipToCity;
    }

    
    @Column(name="SHIP_TO_STATE_CD", length=5)
    public String getShipToStateCd() {
        return this.shipToStateCd;
    }
    
    public void setShipToStateCd(String shipToStateCd) {
        this.shipToStateCd = shipToStateCd;
    }

    
    @Column(name="SHIP_TO_POSTAL_CD", length=10)
    public String getShipToPostalCd() {
        return this.shipToPostalCd;
    }
    
    public void setShipToPostalCd(String shipToPostalCd) {
        this.shipToPostalCd = shipToPostalCd;
    }

    
    @Column(name="SHIP_TO_CNTRY_CD", length=3)
    public String getShipToCntryCd() {
        return this.shipToCntryCd;
    }
    
    public void setShipToCntryCd(String shipToCntryCd) {
        this.shipToCntryCd = shipToCntryCd;
    }

    
    @Column(name="SHIP_VIA_CD", nullable=false, length=8)
    public String getShipViaCd() {
        return this.shipViaCd;
    }
    
    public void setShipViaCd(String shipViaCd) {
        this.shipViaCd = shipViaCd;
    }

    
    @Column(name="TERM_CD", nullable=false, length=10)
    public String getTermCd() {
        return this.termCd;
    }
    
    public void setTermCd(String termCd) {
        this.termCd = termCd;
    }

    
    @Column(name="GROSS_INV_VALUE", nullable=false, precision=17, scale=5)
    public BigDecimal getGrossInvValue() {
        return this.grossInvValue;
    }
    
    public void setGrossInvValue(BigDecimal grossInvValue) {
        this.grossInvValue = grossInvValue;
    }

    
    @Column(name="WGHT", precision=10, scale=3)
    public BigDecimal getWght() {
        return this.wght;
    }
    
    public void setWght(BigDecimal wght) {
        this.wght = wght;
    }

    
    @Column(name="CTN_CNT", precision=7, scale=0)
    public Integer getCtnCnt() {
        return this.ctnCnt;
    }
    
    public void setCtnCnt(Integer ctnCnt) {
        this.ctnCnt = ctnCnt;
    }

    
    @Column(name="FRGT_CHARGE", precision=11)
    public BigDecimal getFrgtCharge() {
        return this.frgtCharge;
    }
    
    public void setFrgtCharge(BigDecimal frgtCharge) {
        this.frgtCharge = frgtCharge;
    }

    
    @Column(name="NET_INV_VALUE", precision=17, scale=5)
    public BigDecimal getNetInvValue() {
        return this.netInvValue;
    }
    
    public void setNetInvValue(BigDecimal netInvValue) {
        this.netInvValue = netInvValue;
    }

    
    @Column(name="WAYBILL_CD", length=20)
    public String getWaybillCd() {
        return this.waybillCd;
    }
    
    public void setWaybillCd(String waybillCd) {
        this.waybillCd = waybillCd;
    }

    
    @Column(name="TRD_FLG", nullable=false, length=1)
    public String getTrdFlg() {
        return this.trdFlg;
    }
    
    public void setTrdFlg(String trdFlg) {
        this.trdFlg = trdFlg;
    }

    
    @Column(name="AR_INV_BATCH_NBR", precision=9, scale=0)
    public Integer getArInvBatchNbr() {
        return this.arInvBatchNbr;
    }
    
    public void setArInvBatchNbr(Integer arInvBatchNbr) {
        this.arInvBatchNbr = arInvBatchNbr;
    }

    
    @Column(name="FOB_CD", length=8)
    public String getFobCd() {
        return this.fobCd;
    }
    
    public void setFobCd(String fobCd) {
        this.fobCd = fobCd;
    }

    
    @Column(name="ORG_CD_CUST", nullable=false, length=15)
    public String getOrgCdCust() {
        return this.orgCdCust;
    }
    
    public void setOrgCdCust(String orgCdCust) {
        this.orgCdCust = orgCdCust;
    }

    
    @Column(name="SALES_TERR_CD", nullable=false, length=8)
    public String getSalesTerrCd() {
        return this.salesTerrCd;
    }
    
    public void setSalesTerrCd(String salesTerrCd) {
        this.salesTerrCd = salesTerrCd;
    }

    
    @Column(name="AR_SUMMARY_INV_NBR", precision=9, scale=0)
    public Integer getArSummaryInvNbr() {
        return this.arSummaryInvNbr;
    }
    
    public void setArSummaryInvNbr(Integer arSummaryInvNbr) {
        this.arSummaryInvNbr = arSummaryInvNbr;
    }

    
    @Column(name="GL_TAX_GRP_NBR", precision=9, scale=0)
    public Integer getGlTaxGrpNbr() {
        return this.glTaxGrpNbr;
    }
    
    public void setGlTaxGrpNbr(Integer glTaxGrpNbr) {
        this.glTaxGrpNbr = glTaxGrpNbr;
    }

    
    @Column(name="PRINT_FLG", nullable=false, length=1)
    public String getPrintFlg() {
        return this.printFlg;
    }
    
    public void setPrintFlg(String printFlg) {
        this.printFlg = printFlg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="INV_PRINT_DT_ORIG", length=7)
    public Date getInvPrintDtOrig() {
        return this.invPrintDtOrig;
    }
    
    public void setInvPrintDtOrig(Date invPrintDtOrig) {
        this.invPrintDtOrig = invPrintDtOrig;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="INV_PRINT_DT_LAST", length=7)
    public Date getInvPrintDtLast() {
        return this.invPrintDtLast;
    }
    
    public void setInvPrintDtLast(Date invPrintDtLast) {
        this.invPrintDtLast = invPrintDtLast;
    }

    
    @Column(name="UT_USER_NBR_PRINT", precision=9, scale=0)
    public Integer getUtUserNbrPrint() {
        return this.utUserNbrPrint;
    }
    
    public void setUtUserNbrPrint(Integer utUserNbrPrint) {
        this.utUserNbrPrint = utUserNbrPrint;
    }

    
    @Column(name="ORD_TYPE_CD", nullable=false, length=8)
    public String getOrdTypeCd() {
        return this.ordTypeCd;
    }
    
    public void setOrdTypeCd(String ordTypeCd) {
        this.ordTypeCd = ordTypeCd;
    }

    
    @Column(name="SUMMARY_INV_REF", length=30)
    public String getSummaryInvRef() {
        return this.summaryInvRef;
    }
    
    public void setSummaryInvRef(String summaryInvRef) {
        this.summaryInvRef = summaryInvRef;
    }

    
    @Column(name="WH_SHIP_PRTY_NBR", precision=5, scale=0)
    public Integer getWhShipPrtyNbr() {
        return this.whShipPrtyNbr;
    }
    
    public void setWhShipPrtyNbr(Integer whShipPrtyNbr) {
        this.whShipPrtyNbr = whShipPrtyNbr;
    }

    
    @Column(name="PAYMENT_METHOD_CD", length=3)
    public String getPaymentMethodCd() {
        return this.paymentMethodCd;
    }
    
    public void setPaymentMethodCd(String paymentMethodCd) {
        this.paymentMethodCd = paymentMethodCd;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="arInvHdr")
    public Set<ArInvDtl> getArInvDtls() {
        return this.arInvDtls;
    }
    
    public void setArInvDtls(Set<ArInvDtl> arInvDtls) {
        this.arInvDtls = arInvDtls;
    }




}


