package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArRmaRcpt generated by hbm2java
 */
@Entity
@Table(name="AR_RMA_RCPT"
)
public class ArRmaRcpt  implements java.io.Serializable {


     private int arRmaRcptNbr;
     private ApsSplySubPool apsSplySubPool;
     private ArRmaDtl arRmaDtl;
     private IcLotMast icLotMast;
     private IcUm icUm;
     private OeCustMast oeCustMast;
     private IcBin icBin;
     private IcItemMast icItemMast;
     private Date rcptDt;
     private BigDecimal qtyReceived;
     private BigDecimal qtyReceivedStkUm;
     private BigDecimal qtyAccepted;
     private BigDecimal qtyAcceptedStkUm;
     private String rmaComments;
     private String rcptStatId;
     private String facilityRecv;
     private int utUserNbrRecv;
     private Integer utUserNbrInspect;
     private Date processDt;
     private int utUserNbr;
     private Date lastModDt;
     private BigDecimal lotCostLanded;
     private Integer icTransGlNbr;

    public ArRmaRcpt() {
    }

	
    public ArRmaRcpt(int arRmaRcptNbr, IcUm icUm, IcItemMast icItemMast, Date rcptDt, BigDecimal qtyReceived, BigDecimal qtyReceivedStkUm, String rcptStatId, int utUserNbrRecv, int utUserNbr, Date lastModDt) {
        this.arRmaRcptNbr = arRmaRcptNbr;
        this.icUm = icUm;
        this.icItemMast = icItemMast;
        this.rcptDt = rcptDt;
        this.qtyReceived = qtyReceived;
        this.qtyReceivedStkUm = qtyReceivedStkUm;
        this.rcptStatId = rcptStatId;
        this.utUserNbrRecv = utUserNbrRecv;
        this.utUserNbr = utUserNbr;
        this.lastModDt = lastModDt;
    }
    public ArRmaRcpt(int arRmaRcptNbr, ApsSplySubPool apsSplySubPool, ArRmaDtl arRmaDtl, IcLotMast icLotMast, IcUm icUm, OeCustMast oeCustMast, IcBin icBin, IcItemMast icItemMast, Date rcptDt, BigDecimal qtyReceived, BigDecimal qtyReceivedStkUm, BigDecimal qtyAccepted, BigDecimal qtyAcceptedStkUm, String rmaComments, String rcptStatId, String facilityRecv, int utUserNbrRecv, Integer utUserNbrInspect, Date processDt, int utUserNbr, Date lastModDt, BigDecimal lotCostLanded, Integer icTransGlNbr) {
       this.arRmaRcptNbr = arRmaRcptNbr;
       this.apsSplySubPool = apsSplySubPool;
       this.arRmaDtl = arRmaDtl;
       this.icLotMast = icLotMast;
       this.icUm = icUm;
       this.oeCustMast = oeCustMast;
       this.icBin = icBin;
       this.icItemMast = icItemMast;
       this.rcptDt = rcptDt;
       this.qtyReceived = qtyReceived;
       this.qtyReceivedStkUm = qtyReceivedStkUm;
       this.qtyAccepted = qtyAccepted;
       this.qtyAcceptedStkUm = qtyAcceptedStkUm;
       this.rmaComments = rmaComments;
       this.rcptStatId = rcptStatId;
       this.facilityRecv = facilityRecv;
       this.utUserNbrRecv = utUserNbrRecv;
       this.utUserNbrInspect = utUserNbrInspect;
       this.processDt = processDt;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
       this.lotCostLanded = lotCostLanded;
       this.icTransGlNbr = icTransGlNbr;
    }
   
     @Id 

    
    @Column(name="AR_RMA_RCPT_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getArRmaRcptNbr() {
        return this.arRmaRcptNbr;
    }
    
    public void setArRmaRcptNbr(int arRmaRcptNbr) {
        this.arRmaRcptNbr = arRmaRcptNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APS_SPLY_SUB_POOL_NBR_RECV")
    public ApsSplySubPool getApsSplySubPool() {
        return this.apsSplySubPool;
    }
    
    public void setApsSplySubPool(ApsSplySubPool apsSplySubPool) {
        this.apsSplySubPool = apsSplySubPool;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AR_RMA_DTL_NBR")
    public ArRmaDtl getArRmaDtl() {
        return this.arRmaDtl;
    }
    
    public void setArRmaDtl(ArRmaDtl arRmaDtl) {
        this.arRmaDtl = arRmaDtl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LOT_NBR_RECV")
    public IcLotMast getIcLotMast() {
        return this.icLotMast;
    }
    
    public void setIcLotMast(IcLotMast icLotMast) {
        this.icLotMast = icLotMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RMA_UM", nullable=false)
    public IcUm getIcUm() {
        return this.icUm;
    }
    
    public void setIcUm(IcUm icUm) {
        this.icUm = icUm;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORG_NBR_CUST")
    public OeCustMast getOeCustMast() {
        return this.oeCustMast;
    }
    
    public void setOeCustMast(OeCustMast oeCustMast) {
        this.oeCustMast = oeCustMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIN_NBR_STAGE")
    public IcBin getIcBin() {
        return this.icBin;
    }
    
    public void setIcBin(IcBin icBin) {
        this.icBin = icBin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR", nullable=false)
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RCPT_DT", nullable=false, length=7)
    public Date getRcptDt() {
        return this.rcptDt;
    }
    
    public void setRcptDt(Date rcptDt) {
        this.rcptDt = rcptDt;
    }

    
    @Column(name="QTY_RECEIVED", nullable=false, precision=13, scale=5)
    public BigDecimal getQtyReceived() {
        return this.qtyReceived;
    }
    
    public void setQtyReceived(BigDecimal qtyReceived) {
        this.qtyReceived = qtyReceived;
    }

    
    @Column(name="QTY_RECEIVED_STK_UM", nullable=false, precision=13, scale=5)
    public BigDecimal getQtyReceivedStkUm() {
        return this.qtyReceivedStkUm;
    }
    
    public void setQtyReceivedStkUm(BigDecimal qtyReceivedStkUm) {
        this.qtyReceivedStkUm = qtyReceivedStkUm;
    }

    
    @Column(name="QTY_ACCEPTED", precision=13, scale=5)
    public BigDecimal getQtyAccepted() {
        return this.qtyAccepted;
    }
    
    public void setQtyAccepted(BigDecimal qtyAccepted) {
        this.qtyAccepted = qtyAccepted;
    }

    
    @Column(name="QTY_ACCEPTED_STK_UM", precision=13, scale=5)
    public BigDecimal getQtyAcceptedStkUm() {
        return this.qtyAcceptedStkUm;
    }
    
    public void setQtyAcceptedStkUm(BigDecimal qtyAcceptedStkUm) {
        this.qtyAcceptedStkUm = qtyAcceptedStkUm;
    }

    
    @Column(name="RMA_COMMENTS")
    public String getRmaComments() {
        return this.rmaComments;
    }
    
    public void setRmaComments(String rmaComments) {
        this.rmaComments = rmaComments;
    }

    
    @Column(name="RCPT_STAT_ID", nullable=false, length=1)
    public String getRcptStatId() {
        return this.rcptStatId;
    }
    
    public void setRcptStatId(String rcptStatId) {
        this.rcptStatId = rcptStatId;
    }

    
    @Column(name="FACILITY_RECV", length=16)
    public String getFacilityRecv() {
        return this.facilityRecv;
    }
    
    public void setFacilityRecv(String facilityRecv) {
        this.facilityRecv = facilityRecv;
    }

    
    @Column(name="UT_USER_NBR_RECV", nullable=false, precision=9, scale=0)
    public int getUtUserNbrRecv() {
        return this.utUserNbrRecv;
    }
    
    public void setUtUserNbrRecv(int utUserNbrRecv) {
        this.utUserNbrRecv = utUserNbrRecv;
    }

    
    @Column(name="UT_USER_NBR_INSPECT", precision=9, scale=0)
    public Integer getUtUserNbrInspect() {
        return this.utUserNbrInspect;
    }
    
    public void setUtUserNbrInspect(Integer utUserNbrInspect) {
        this.utUserNbrInspect = utUserNbrInspect;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PROCESS_DT", length=7)
    public Date getProcessDt() {
        return this.processDt;
    }
    
    public void setProcessDt(Date processDt) {
        this.processDt = processDt;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }

    
    @Column(name="LOT_COST_LANDED", precision=13, scale=6)
    public BigDecimal getLotCostLanded() {
        return this.lotCostLanded;
    }
    
    public void setLotCostLanded(BigDecimal lotCostLanded) {
        this.lotCostLanded = lotCostLanded;
    }

    
    @Column(name="IC_TRANS_GL_NBR", precision=9, scale=0)
    public Integer getIcTransGlNbr() {
        return this.icTransGlNbr;
    }
    
    public void setIcTransGlNbr(Integer icTransGlNbr) {
        this.icTransGlNbr = icTransGlNbr;
    }




}


