package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArRmaDtl generated by hbm2java
 */
@Entity
@Table(name="AR_RMA_DTL"
)
public class ArRmaDtl  implements java.io.Serializable {


     private int arRmaDtlNbr;
     private ArInvDtl arInvDtl;
     private IcUm icUm;
     private IcItemMast icItemMast;
     private String rmaCd;
     private short arRmaLineNbr;
     private String rmaReasonCd;
     private String itemCd;
     private String itemDescr;
     private BigDecimal qtyRtrnAuth;
     private BigDecimal qtyRtrnAuthStkUm;
     private BigDecimal qtyReceived;
     private BigDecimal qtyReceivedStkUm;
     private BigDecimal qtyAccepted;
     private BigDecimal qtyAcceptedStkUm;
     private BigDecimal qtyCredited;
     private BigDecimal qtyCreditedStkUm;
     private BigDecimal unitPriceStkUm;
     private BigDecimal unitPriceDenomStkUm;
     private BigDecimal unitPriceSellUm;
     private BigDecimal unitPriceDenomSellUm;
     private BigDecimal creditPriceDenom;
     private BigDecimal creditPrice;
     private int utUserNbr;
     private Date lastModDt;
     private BigDecimal unitCostStkUm;
     private BigDecimal unitCostDenomStkUm;
     private BigDecimal unitCostSellUm;
     private BigDecimal unitCostDenomSellUm;
     private Set<ArRmaRcpt> arRmaRcpts = new HashSet<ArRmaRcpt>(0);

    public ArRmaDtl() {
    }

	
    public ArRmaDtl(int arRmaDtlNbr, ArInvDtl arInvDtl, IcItemMast icItemMast, String rmaCd, short arRmaLineNbr, String itemCd, String itemDescr, int utUserNbr, Date lastModDt) {
        this.arRmaDtlNbr = arRmaDtlNbr;
        this.arInvDtl = arInvDtl;
        this.icItemMast = icItemMast;
        this.rmaCd = rmaCd;
        this.arRmaLineNbr = arRmaLineNbr;
        this.itemCd = itemCd;
        this.itemDescr = itemDescr;
        this.utUserNbr = utUserNbr;
        this.lastModDt = lastModDt;
    }
    public ArRmaDtl(int arRmaDtlNbr, ArInvDtl arInvDtl, IcUm icUm, IcItemMast icItemMast, String rmaCd, short arRmaLineNbr, String rmaReasonCd, String itemCd, String itemDescr, BigDecimal qtyRtrnAuth, BigDecimal qtyRtrnAuthStkUm, BigDecimal qtyReceived, BigDecimal qtyReceivedStkUm, BigDecimal qtyAccepted, BigDecimal qtyAcceptedStkUm, BigDecimal qtyCredited, BigDecimal qtyCreditedStkUm, BigDecimal unitPriceStkUm, BigDecimal unitPriceDenomStkUm, BigDecimal unitPriceSellUm, BigDecimal unitPriceDenomSellUm, BigDecimal creditPriceDenom, BigDecimal creditPrice, int utUserNbr, Date lastModDt, BigDecimal unitCostStkUm, BigDecimal unitCostDenomStkUm, BigDecimal unitCostSellUm, BigDecimal unitCostDenomSellUm, Set<ArRmaRcpt> arRmaRcpts) {
       this.arRmaDtlNbr = arRmaDtlNbr;
       this.arInvDtl = arInvDtl;
       this.icUm = icUm;
       this.icItemMast = icItemMast;
       this.rmaCd = rmaCd;
       this.arRmaLineNbr = arRmaLineNbr;
       this.rmaReasonCd = rmaReasonCd;
       this.itemCd = itemCd;
       this.itemDescr = itemDescr;
       this.qtyRtrnAuth = qtyRtrnAuth;
       this.qtyRtrnAuthStkUm = qtyRtrnAuthStkUm;
       this.qtyReceived = qtyReceived;
       this.qtyReceivedStkUm = qtyReceivedStkUm;
       this.qtyAccepted = qtyAccepted;
       this.qtyAcceptedStkUm = qtyAcceptedStkUm;
       this.qtyCredited = qtyCredited;
       this.qtyCreditedStkUm = qtyCreditedStkUm;
       this.unitPriceStkUm = unitPriceStkUm;
       this.unitPriceDenomStkUm = unitPriceDenomStkUm;
       this.unitPriceSellUm = unitPriceSellUm;
       this.unitPriceDenomSellUm = unitPriceDenomSellUm;
       this.creditPriceDenom = creditPriceDenom;
       this.creditPrice = creditPrice;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
       this.unitCostStkUm = unitCostStkUm;
       this.unitCostDenomStkUm = unitCostDenomStkUm;
       this.unitCostSellUm = unitCostSellUm;
       this.unitCostDenomSellUm = unitCostDenomSellUm;
       this.arRmaRcpts = arRmaRcpts;
    }
   
     @Id 

    
    @Column(name="AR_RMA_DTL_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getArRmaDtlNbr() {
        return this.arRmaDtlNbr;
    }
    
    public void setArRmaDtlNbr(int arRmaDtlNbr) {
        this.arRmaDtlNbr = arRmaDtlNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AR_INV_DTL_NBR", nullable=false)
    public ArInvDtl getArInvDtl() {
        return this.arInvDtl;
    }
    
    public void setArInvDtl(ArInvDtl arInvDtl) {
        this.arInvDtl = arInvDtl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SELL_UM")
    public IcUm getIcUm() {
        return this.icUm;
    }
    
    public void setIcUm(IcUm icUm) {
        this.icUm = icUm;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR", nullable=false)
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }

    
    @Column(name="RMA_CD", nullable=false, length=20)
    public String getRmaCd() {
        return this.rmaCd;
    }
    
    public void setRmaCd(String rmaCd) {
        this.rmaCd = rmaCd;
    }

    
    @Column(name="AR_RMA_LINE_NBR", nullable=false, precision=3, scale=0)
    public short getArRmaLineNbr() {
        return this.arRmaLineNbr;
    }
    
    public void setArRmaLineNbr(short arRmaLineNbr) {
        this.arRmaLineNbr = arRmaLineNbr;
    }

    
    @Column(name="RMA_REASON_CD", length=8)
    public String getRmaReasonCd() {
        return this.rmaReasonCd;
    }
    
    public void setRmaReasonCd(String rmaReasonCd) {
        this.rmaReasonCd = rmaReasonCd;
    }

    
    @Column(name="ITEM_CD", nullable=false, length=50)
    public String getItemCd() {
        return this.itemCd;
    }
    
    public void setItemCd(String itemCd) {
        this.itemCd = itemCd;
    }

    
    @Column(name="ITEM_DESCR", nullable=false, length=50)
    public String getItemDescr() {
        return this.itemDescr;
    }
    
    public void setItemDescr(String itemDescr) {
        this.itemDescr = itemDescr;
    }

    
    @Column(name="QTY_RTRN_AUTH", precision=13, scale=5)
    public BigDecimal getQtyRtrnAuth() {
        return this.qtyRtrnAuth;
    }
    
    public void setQtyRtrnAuth(BigDecimal qtyRtrnAuth) {
        this.qtyRtrnAuth = qtyRtrnAuth;
    }

    
    @Column(name="QTY_RTRN_AUTH_STK_UM", precision=13, scale=5)
    public BigDecimal getQtyRtrnAuthStkUm() {
        return this.qtyRtrnAuthStkUm;
    }
    
    public void setQtyRtrnAuthStkUm(BigDecimal qtyRtrnAuthStkUm) {
        this.qtyRtrnAuthStkUm = qtyRtrnAuthStkUm;
    }

    
    @Column(name="QTY_RECEIVED", precision=13, scale=5)
    public BigDecimal getQtyReceived() {
        return this.qtyReceived;
    }
    
    public void setQtyReceived(BigDecimal qtyReceived) {
        this.qtyReceived = qtyReceived;
    }

    
    @Column(name="QTY_RECEIVED_STK_UM", precision=13, scale=5)
    public BigDecimal getQtyReceivedStkUm() {
        return this.qtyReceivedStkUm;
    }
    
    public void setQtyReceivedStkUm(BigDecimal qtyReceivedStkUm) {
        this.qtyReceivedStkUm = qtyReceivedStkUm;
    }

    
    @Column(name="QTY_ACCEPTED", precision=13, scale=5)
    public BigDecimal getQtyAccepted() {
        return this.qtyAccepted;
    }
    
    public void setQtyAccepted(BigDecimal qtyAccepted) {
        this.qtyAccepted = qtyAccepted;
    }

    
    @Column(name="QTY_ACCEPTED_STK_UM", precision=13, scale=5)
    public BigDecimal getQtyAcceptedStkUm() {
        return this.qtyAcceptedStkUm;
    }
    
    public void setQtyAcceptedStkUm(BigDecimal qtyAcceptedStkUm) {
        this.qtyAcceptedStkUm = qtyAcceptedStkUm;
    }

    
    @Column(name="QTY_CREDITED", precision=13, scale=5)
    public BigDecimal getQtyCredited() {
        return this.qtyCredited;
    }
    
    public void setQtyCredited(BigDecimal qtyCredited) {
        this.qtyCredited = qtyCredited;
    }

    
    @Column(name="QTY_CREDITED_STK_UM", precision=13, scale=5)
    public BigDecimal getQtyCreditedStkUm() {
        return this.qtyCreditedStkUm;
    }
    
    public void setQtyCreditedStkUm(BigDecimal qtyCreditedStkUm) {
        this.qtyCreditedStkUm = qtyCreditedStkUm;
    }

    
    @Column(name="UNIT_PRICE_STK_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceStkUm() {
        return this.unitPriceStkUm;
    }
    
    public void setUnitPriceStkUm(BigDecimal unitPriceStkUm) {
        this.unitPriceStkUm = unitPriceStkUm;
    }

    
    @Column(name="UNIT_PRICE_DENOM_STK_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceDenomStkUm() {
        return this.unitPriceDenomStkUm;
    }
    
    public void setUnitPriceDenomStkUm(BigDecimal unitPriceDenomStkUm) {
        this.unitPriceDenomStkUm = unitPriceDenomStkUm;
    }

    
    @Column(name="UNIT_PRICE_SELL_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceSellUm() {
        return this.unitPriceSellUm;
    }
    
    public void setUnitPriceSellUm(BigDecimal unitPriceSellUm) {
        this.unitPriceSellUm = unitPriceSellUm;
    }

    
    @Column(name="UNIT_PRICE_DENOM_SELL_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceDenomSellUm() {
        return this.unitPriceDenomSellUm;
    }
    
    public void setUnitPriceDenomSellUm(BigDecimal unitPriceDenomSellUm) {
        this.unitPriceDenomSellUm = unitPriceDenomSellUm;
    }

    
    @Column(name="CREDIT_PRICE_DENOM", precision=17, scale=6)
    public BigDecimal getCreditPriceDenom() {
        return this.creditPriceDenom;
    }
    
    public void setCreditPriceDenom(BigDecimal creditPriceDenom) {
        this.creditPriceDenom = creditPriceDenom;
    }

    
    @Column(name="CREDIT_PRICE", precision=17, scale=6)
    public BigDecimal getCreditPrice() {
        return this.creditPrice;
    }
    
    public void setCreditPrice(BigDecimal creditPrice) {
        this.creditPrice = creditPrice;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }

    
    @Column(name="UNIT_COST_STK_UM", precision=17, scale=6)
    public BigDecimal getUnitCostStkUm() {
        return this.unitCostStkUm;
    }
    
    public void setUnitCostStkUm(BigDecimal unitCostStkUm) {
        this.unitCostStkUm = unitCostStkUm;
    }

    
    @Column(name="UNIT_COST_DENOM_STK_UM", precision=17, scale=6)
    public BigDecimal getUnitCostDenomStkUm() {
        return this.unitCostDenomStkUm;
    }
    
    public void setUnitCostDenomStkUm(BigDecimal unitCostDenomStkUm) {
        this.unitCostDenomStkUm = unitCostDenomStkUm;
    }

    
    @Column(name="UNIT_COST_SELL_UM", precision=17, scale=6)
    public BigDecimal getUnitCostSellUm() {
        return this.unitCostSellUm;
    }
    
    public void setUnitCostSellUm(BigDecimal unitCostSellUm) {
        this.unitCostSellUm = unitCostSellUm;
    }

    
    @Column(name="UNIT_COST_DENOM_SELL_UM", precision=17, scale=6)
    public BigDecimal getUnitCostDenomSellUm() {
        return this.unitCostDenomSellUm;
    }
    
    public void setUnitCostDenomSellUm(BigDecimal unitCostDenomSellUm) {
        this.unitCostDenomSellUm = unitCostDenomSellUm;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="arRmaDtl")
    public Set<ArRmaRcpt> getArRmaRcpts() {
        return this.arRmaRcpts;
    }
    
    public void setArRmaRcpts(Set<ArRmaRcpt> arRmaRcpts) {
        this.arRmaRcpts = arRmaRcpts;
    }




}


