package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CalDt generated by hbm2java
 */
@Entity
@Table(name="CAL_DT"
)
public class CalDt  implements java.io.Serializable {


     private CalDtId id;
     private CalCalendar calCalendar;
     private short cycle;
     private byte intvl;
     private BigDecimal intvlPct;
     private String workDayFlg;
     private Date prdStartDt;
     private Boolean calQtr;
     private Short workDayNbr;

    public CalDt() {
    }

	
    public CalDt(CalDtId id, CalCalendar calCalendar, short cycle, byte intvl, BigDecimal intvlPct, String workDayFlg) {
        this.id = id;
        this.calCalendar = calCalendar;
        this.cycle = cycle;
        this.intvl = intvl;
        this.intvlPct = intvlPct;
        this.workDayFlg = workDayFlg;
    }
    public CalDt(CalDtId id, CalCalendar calCalendar, short cycle, byte intvl, BigDecimal intvlPct, String workDayFlg, Date prdStartDt, Boolean calQtr, Short workDayNbr) {
       this.id = id;
       this.calCalendar = calCalendar;
       this.cycle = cycle;
       this.intvl = intvl;
       this.intvlPct = intvlPct;
       this.workDayFlg = workDayFlg;
       this.prdStartDt = prdStartDt;
       this.calQtr = calQtr;
       this.workDayNbr = workDayNbr;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="calendar", column=@Column(name="CALENDAR", nullable=false, length=6) ), 
        @AttributeOverride(name="calDt", column=@Column(name="CAL_DT", nullable=false, length=7) ) } )
    public CalDtId getId() {
        return this.id;
    }
    
    public void setId(CalDtId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CALENDAR", nullable=false, insertable=false, updatable=false)
    public CalCalendar getCalCalendar() {
        return this.calCalendar;
    }
    
    public void setCalCalendar(CalCalendar calCalendar) {
        this.calCalendar = calCalendar;
    }

    
    @Column(name="CYCLE", nullable=false, precision=4, scale=0)
    public short getCycle() {
        return this.cycle;
    }
    
    public void setCycle(short cycle) {
        this.cycle = cycle;
    }

    
    @Column(name="INTVL", nullable=false, precision=2, scale=0)
    public byte getIntvl() {
        return this.intvl;
    }
    
    public void setIntvl(byte intvl) {
        this.intvl = intvl;
    }

    
    @Column(name="INTVL_PCT", nullable=false, precision=6, scale=3)
    public BigDecimal getIntvlPct() {
        return this.intvlPct;
    }
    
    public void setIntvlPct(BigDecimal intvlPct) {
        this.intvlPct = intvlPct;
    }

    
    @Column(name="WORK_DAY_FLG", nullable=false, length=1)
    public String getWorkDayFlg() {
        return this.workDayFlg;
    }
    
    public void setWorkDayFlg(String workDayFlg) {
        this.workDayFlg = workDayFlg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PRD_START_DT", length=7)
    public Date getPrdStartDt() {
        return this.prdStartDt;
    }
    
    public void setPrdStartDt(Date prdStartDt) {
        this.prdStartDt = prdStartDt;
    }

    
    @Column(name="CAL_QTR", precision=1, scale=0)
    public Boolean getCalQtr() {
        return this.calQtr;
    }
    
    public void setCalQtr(Boolean calQtr) {
        this.calQtr = calQtr;
    }

    
    @Column(name="WORK_DAY_NBR", precision=3, scale=0)
    public Short getWorkDayNbr() {
        return this.workDayNbr;
    }
    
    public void setWorkDayNbr(Short workDayNbr) {
        this.workDayNbr = workDayNbr;
    }




}


