package com.pacificdataservices.diamond.models;
// Generated Mar 21, 2019 5:50:00 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FakeOrgNm generated by hbm2java
 */
@Entity
@Table(name="FAKE_ORG_NM"
)
public class FakeOrgNm  implements java.io.Serializable {


     private FakeOrgNmId id;

    public FakeOrgNm() {
    }

    public FakeOrgNm(FakeOrgNmId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orgNm", column=@Column(name="ORG_NM", length=60) ), 
        @AttributeOverride(name="fakeOrgNm", column=@Column(name="FAKE_ORG_NM", length=60) ) } )
    public FakeOrgNmId getId() {
        return this.id;
    }
    
    public void setId(FakeOrgNmId id) {
        this.id = id;
    }




}


