package com.pacificdataservices.diamond.models;
// Generated Mar 21, 2019 5:50:00 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FakeDate generated by hbm2java
 */
@Entity
@Table(name="FAKE_DATE"
)
public class FakeDate  implements java.io.Serializable {


     private Date maxModDt;

    public FakeDate() {
    }

    public FakeDate(Date maxModDt) {
       this.maxModDt = maxModDt;
    }
   
     @Id 

    @Temporal(TemporalType.DATE)
    @Column(name="MAX_MOD_DT", length=7)
    public Date getMaxModDt() {
        return this.maxModDt;
    }
    
    public void setMaxModDt(Date maxModDt) {
        this.maxModDt = maxModDt;
    }




}


