package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FcAdj generated by hbm2java
 */
@Entity
@Table(name="FC_ADJ"
)
public class FcAdj  implements java.io.Serializable {


     private int fcAdjNbr;
     private FcItemMast fcItemMast;
     private short cycle;
     private byte intvl;
     private Byte prd;
     private String adjId;
     private BigDecimal adjAmt;
     private String adjComm;
     private int indivNbrAdj;
     private Date adjTm;

    public FcAdj() {
    }

	
    public FcAdj(int fcAdjNbr, FcItemMast fcItemMast, short cycle, byte intvl, String adjId, BigDecimal adjAmt, int indivNbrAdj, Date adjTm) {
        this.fcAdjNbr = fcAdjNbr;
        this.fcItemMast = fcItemMast;
        this.cycle = cycle;
        this.intvl = intvl;
        this.adjId = adjId;
        this.adjAmt = adjAmt;
        this.indivNbrAdj = indivNbrAdj;
        this.adjTm = adjTm;
    }
    public FcAdj(int fcAdjNbr, FcItemMast fcItemMast, short cycle, byte intvl, Byte prd, String adjId, BigDecimal adjAmt, String adjComm, int indivNbrAdj, Date adjTm) {
       this.fcAdjNbr = fcAdjNbr;
       this.fcItemMast = fcItemMast;
       this.cycle = cycle;
       this.intvl = intvl;
       this.prd = prd;
       this.adjId = adjId;
       this.adjAmt = adjAmt;
       this.adjComm = adjComm;
       this.indivNbrAdj = indivNbrAdj;
       this.adjTm = adjTm;
    }
   
     @Id 

    
    @Column(name="FC_ADJ_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getFcAdjNbr() {
        return this.fcAdjNbr;
    }
    
    public void setFcAdjNbr(int fcAdjNbr) {
        this.fcAdjNbr = fcAdjNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FC_ITEM_MAST_NBR", nullable=false)
    public FcItemMast getFcItemMast() {
        return this.fcItemMast;
    }
    
    public void setFcItemMast(FcItemMast fcItemMast) {
        this.fcItemMast = fcItemMast;
    }

    
    @Column(name="CYCLE", nullable=false, precision=4, scale=0)
    public short getCycle() {
        return this.cycle;
    }
    
    public void setCycle(short cycle) {
        this.cycle = cycle;
    }

    
    @Column(name="INTVL", nullable=false, precision=2, scale=0)
    public byte getIntvl() {
        return this.intvl;
    }
    
    public void setIntvl(byte intvl) {
        this.intvl = intvl;
    }

    
    @Column(name="PRD", precision=2, scale=0)
    public Byte getPrd() {
        return this.prd;
    }
    
    public void setPrd(Byte prd) {
        this.prd = prd;
    }

    
    @Column(name="ADJ_ID", nullable=false, length=2)
    public String getAdjId() {
        return this.adjId;
    }
    
    public void setAdjId(String adjId) {
        this.adjId = adjId;
    }

    
    @Column(name="ADJ_AMT", nullable=false, precision=10)
    public BigDecimal getAdjAmt() {
        return this.adjAmt;
    }
    
    public void setAdjAmt(BigDecimal adjAmt) {
        this.adjAmt = adjAmt;
    }

    
    @Column(name="ADJ_COMM", length=80)
    public String getAdjComm() {
        return this.adjComm;
    }
    
    public void setAdjComm(String adjComm) {
        this.adjComm = adjComm;
    }

    
    @Column(name="INDIV_NBR_ADJ", nullable=false, precision=9, scale=0)
    public int getIndivNbrAdj() {
        return this.indivNbrAdj;
    }
    
    public void setIndivNbrAdj(int indivNbrAdj) {
        this.indivNbrAdj = indivNbrAdj;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ADJ_TM", nullable=false, length=7)
    public Date getAdjTm() {
        return this.adjTm;
    }
    
    public void setAdjTm(Date adjTm) {
        this.adjTm = adjTm;
    }




}


