package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FcAggrHistCycleActVw generated by hbm2java
 */
@Entity
@Table(name="FC_AGGR_HIST_CYCLE_ACT_VW"
)
public class FcAggrHistCycleActVw  implements java.io.Serializable {


     private FcAggrHistCycleActVwId id;

    public FcAggrHistCycleActVw() {
    }

    public FcAggrHistCycleActVw(FcAggrHistCycleActVwId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fcAggrMastNbr", column=@Column(name="FC_AGGR_MAST_NBR") ), 
        @AttributeOverride(name="fcstGrp", column=@Column(name="FCST_GRP") ), 
        @AttributeOverride(name="fcstTypeId", column=@Column(name="FCST_TYPE_ID") ), 
        @AttributeOverride(name="fcstAggrTypeId", column=@Column(name="FCST_AGGR_TYPE_ID") ), 
        @AttributeOverride(name="cycle", column=@Column(name="CYCLE") ), 
        @AttributeOverride(name="jan", column=@Column(name="JAN") ), 
        @AttributeOverride(name="feb", column=@Column(name="FEB") ), 
        @AttributeOverride(name="mar", column=@Column(name="MAR") ), 
        @AttributeOverride(name="apr", column=@Column(name="APR") ), 
        @AttributeOverride(name="may", column=@Column(name="MAY") ), 
        @AttributeOverride(name="jun", column=@Column(name="JUN") ), 
        @AttributeOverride(name="jul", column=@Column(name="JUL") ), 
        @AttributeOverride(name="aug", column=@Column(name="AUG") ), 
        @AttributeOverride(name="sep", column=@Column(name="SEP") ), 
        @AttributeOverride(name="oct", column=@Column(name="OCT") ), 
        @AttributeOverride(name="nov", column=@Column(name="NOV") ), 
        @AttributeOverride(name="dec", column=@Column(name="DEC") ), 
        @AttributeOverride(name="tot", column=@Column(name="TOT") ) } )
    public FcAggrHistCycleActVwId getId() {
        return this.id;
    }
    
    public void setId(FcAggrHistCycleActVwId id) {
        this.id = id;
    }




}


