package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FcAggrMastAttr generated by hbm2java
 */
@Entity
@Table(name="FC_AGGR_MAST_ATTR"
)
public class FcAggrMastAttr  implements java.io.Serializable {


     private FcAggrMastAttrId id;
     private FcAggrMast fcAggrMast;
     private IcAttr icAttr;
     private String attrVal;

    public FcAggrMastAttr() {
    }

    public FcAggrMastAttr(FcAggrMastAttrId id, FcAggrMast fcAggrMast, IcAttr icAttr, String attrVal) {
       this.id = id;
       this.fcAggrMast = fcAggrMast;
       this.icAttr = icAttr;
       this.attrVal = attrVal;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fcAggrMastNbr", column=@Column(name="FC_AGGR_MAST_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="icAttrNbr", column=@Column(name="IC_ATTR_NBR", nullable=false, precision=9, scale=0) ) } )
    public FcAggrMastAttrId getId() {
        return this.id;
    }
    
    public void setId(FcAggrMastAttrId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FC_AGGR_MAST_NBR", nullable=false, insertable=false, updatable=false)
    public FcAggrMast getFcAggrMast() {
        return this.fcAggrMast;
    }
    
    public void setFcAggrMast(FcAggrMast fcAggrMast) {
        this.fcAggrMast = fcAggrMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IC_ATTR_NBR", nullable=false, insertable=false, updatable=false)
    public IcAttr getIcAttr() {
        return this.icAttr;
    }
    
    public void setIcAttr(IcAttr icAttr) {
        this.icAttr = icAttr;
    }

    
    @Column(name="ATTR_VAL", nullable=false, length=20)
    public String getAttrVal() {
        return this.attrVal;
    }
    
    public void setAttrVal(String attrVal) {
        this.attrVal = attrVal;
    }




}


