package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FcAttrVal generated by hbm2java
 */
@Entity
@Table(name="FC_ATTR_VAL"
)
public class FcAttrVal  implements java.io.Serializable {


     private FcAttrValId id;
     private FcAttr fcAttr;
     private String attrValDescr;
     private int utUserNbr;
     private Date lastModDt;

    public FcAttrVal() {
    }

	
    public FcAttrVal(FcAttrValId id, FcAttr fcAttr, int utUserNbr, Date lastModDt) {
        this.id = id;
        this.fcAttr = fcAttr;
        this.utUserNbr = utUserNbr;
        this.lastModDt = lastModDt;
    }
    public FcAttrVal(FcAttrValId id, FcAttr fcAttr, String attrValDescr, int utUserNbr, Date lastModDt) {
       this.id = id;
       this.fcAttr = fcAttr;
       this.attrValDescr = attrValDescr;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fcAttrNbr", column=@Column(name="FC_ATTR_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="attrVal", column=@Column(name="ATTR_VAL", nullable=false, length=20) ) } )
    public FcAttrValId getId() {
        return this.id;
    }
    
    public void setId(FcAttrValId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FC_ATTR_NBR", nullable=false, insertable=false, updatable=false)
    public FcAttr getFcAttr() {
        return this.fcAttr;
    }
    
    public void setFcAttr(FcAttr fcAttr) {
        this.fcAttr = fcAttr;
    }

    
    @Column(name="ATTR_VAL_DESCR", length=60)
    public String getAttrValDescr() {
        return this.attrValDescr;
    }
    
    public void setAttrValDescr(String attrValDescr) {
        this.attrValDescr = attrValDescr;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }




}


