package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FcBuildRate generated by hbm2java
 */
@Entity
@Table(name="FC_BUILD_RATE"
)
public class FcBuildRate  implements java.io.Serializable {


     private FcBuildRateId id;
     private FcBuildRateGrp fcBuildRateGrp;
     private int buildRateUnits;

    public FcBuildRate() {
    }

    public FcBuildRate(FcBuildRateId id, FcBuildRateGrp fcBuildRateGrp, int buildRateUnits) {
       this.id = id;
       this.fcBuildRateGrp = fcBuildRateGrp;
       this.buildRateUnits = buildRateUnits;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fcBuildRateGrpCd", column=@Column(name="FC_BUILD_RATE_GRP_CD", nullable=false, length=10) ), 
        @AttributeOverride(name="buildRateEffDt", column=@Column(name="BUILD_RATE_EFF_DT", nullable=false, length=7) ) } )
    public FcBuildRateId getId() {
        return this.id;
    }
    
    public void setId(FcBuildRateId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FC_BUILD_RATE_GRP_CD", nullable=false, insertable=false, updatable=false)
    public FcBuildRateGrp getFcBuildRateGrp() {
        return this.fcBuildRateGrp;
    }
    
    public void setFcBuildRateGrp(FcBuildRateGrp fcBuildRateGrp) {
        this.fcBuildRateGrp = fcBuildRateGrp;
    }

    
    @Column(name="BUILD_RATE_UNITS", nullable=false, precision=5, scale=0)
    public int getBuildRateUnits() {
        return this.buildRateUnits;
    }
    
    public void setBuildRateUnits(int buildRateUnits) {
        this.buildRateUnits = buildRateUnits;
    }




}


