package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FcFcstMnthVw generated by hbm2java
 */
@Entity
@Table(name="FC_FCST_MNTH_VW"
)
public class FcFcstMnthVw  implements java.io.Serializable {


     private FcFcstMnthVwId id;

    public FcFcstMnthVw() {
    }

    public FcFcstMnthVw(FcFcstMnthVwId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fcItemMastNbr", column=@Column(name="FC_ITEM_MAST_NBR") ), 
        @AttributeOverride(name="m1Raw", column=@Column(name="M1_RAW") ), 
        @AttributeOverride(name="m1Adj", column=@Column(name="M1_ADJ") ), 
        @AttributeOverride(name="m1v", column=@Column(name="M1V") ), 
        @AttributeOverride(name="m2Raw", column=@Column(name="M2_RAW") ), 
        @AttributeOverride(name="m2Adj", column=@Column(name="M2_ADJ") ), 
        @AttributeOverride(name="m2v", column=@Column(name="M2V") ), 
        @AttributeOverride(name="m3Raw", column=@Column(name="M3_RAW") ), 
        @AttributeOverride(name="m3Adj", column=@Column(name="M3_ADJ") ), 
        @AttributeOverride(name="m3v", column=@Column(name="M3V") ), 
        @AttributeOverride(name="m4Raw", column=@Column(name="M4_RAW") ), 
        @AttributeOverride(name="m4Adj", column=@Column(name="M4_ADJ") ), 
        @AttributeOverride(name="m4v", column=@Column(name="M4V") ), 
        @AttributeOverride(name="m5Raw", column=@Column(name="M5_RAW") ), 
        @AttributeOverride(name="m5Adj", column=@Column(name="M5_ADJ") ), 
        @AttributeOverride(name="m5v", column=@Column(name="M5V") ), 
        @AttributeOverride(name="m6Raw", column=@Column(name="M6_RAW") ), 
        @AttributeOverride(name="m6Adj", column=@Column(name="M6_ADJ") ), 
        @AttributeOverride(name="m6v", column=@Column(name="M6V") ), 
        @AttributeOverride(name="m7Raw", column=@Column(name="M7_RAW") ), 
        @AttributeOverride(name="m7Adj", column=@Column(name="M7_ADJ") ), 
        @AttributeOverride(name="m7v", column=@Column(name="M7V") ), 
        @AttributeOverride(name="m8Raw", column=@Column(name="M8_RAW") ), 
        @AttributeOverride(name="m8Adj", column=@Column(name="M8_ADJ") ), 
        @AttributeOverride(name="m8v", column=@Column(name="M8V") ), 
        @AttributeOverride(name="m9Raw", column=@Column(name="M9_RAW") ), 
        @AttributeOverride(name="m9Adj", column=@Column(name="M9_ADJ") ), 
        @AttributeOverride(name="m9v", column=@Column(name="M9V") ), 
        @AttributeOverride(name="m10Raw", column=@Column(name="M10_RAW") ), 
        @AttributeOverride(name="m10Adj", column=@Column(name="M10_ADJ") ), 
        @AttributeOverride(name="m10v", column=@Column(name="M10V") ), 
        @AttributeOverride(name="m11Raw", column=@Column(name="M11_RAW") ), 
        @AttributeOverride(name="m11Adj", column=@Column(name="M11_ADJ") ), 
        @AttributeOverride(name="m11v", column=@Column(name="M11V") ), 
        @AttributeOverride(name="m12Raw", column=@Column(name="M12_RAW") ), 
        @AttributeOverride(name="m12Adj", column=@Column(name="M12_ADJ") ), 
        @AttributeOverride(name="m12v", column=@Column(name="M12V") ) } )
    public FcFcstMnthVwId getId() {
        return this.id;
    }
    
    public void setId(FcFcstMnthVwId id) {
        this.id = id;
    }




}


