package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FcFcstPrd generated by hbm2java
 */
@Entity
@Table(name="FC_FCST_PRD"
)
public class FcFcstPrd  implements java.io.Serializable {


     private FcFcstPrdId id;
     private BigDecimal rawFcst;
     private BigDecimal adjFcst;
     private BigDecimal fcstAllocQty;

    public FcFcstPrd() {
    }

	
    public FcFcstPrd(FcFcstPrdId id) {
        this.id = id;
    }
    public FcFcstPrd(FcFcstPrdId id, BigDecimal rawFcst, BigDecimal adjFcst, BigDecimal fcstAllocQty) {
       this.id = id;
       this.rawFcst = rawFcst;
       this.adjFcst = adjFcst;
       this.fcstAllocQty = fcstAllocQty;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fcItemMastNbr", column=@Column(name="FC_ITEM_MAST_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="fcFcstDt", column=@Column(name="FC_FCST_DT", nullable=false, length=7) ) } )
    public FcFcstPrdId getId() {
        return this.id;
    }
    
    public void setId(FcFcstPrdId id) {
        this.id = id;
    }

    
    @Column(name="RAW_FCST", precision=17, scale=5)
    public BigDecimal getRawFcst() {
        return this.rawFcst;
    }
    
    public void setRawFcst(BigDecimal rawFcst) {
        this.rawFcst = rawFcst;
    }

    
    @Column(name="ADJ_FCST", precision=17, scale=5)
    public BigDecimal getAdjFcst() {
        return this.adjFcst;
    }
    
    public void setAdjFcst(BigDecimal adjFcst) {
        this.adjFcst = adjFcst;
    }

    
    @Column(name="FCST_ALLOC_QTY", precision=17, scale=5)
    public BigDecimal getFcstAllocQty() {
        return this.fcstAllocQty;
    }
    
    public void setFcstAllocQty(BigDecimal fcstAllocQty) {
        this.fcstAllocQty = fcstAllocQty;
    }




}


