package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FcFcstAggrId generated by hbm2java
 */
@Embeddable
public class FcFcstAggrId  implements java.io.Serializable {


     private int fcAggrMastNbr;
     private Date fcFcstDt;

    public FcFcstAggrId() {
    }

    public FcFcstAggrId(int fcAggrMastNbr, Date fcFcstDt) {
       this.fcAggrMastNbr = fcAggrMastNbr;
       this.fcFcstDt = fcFcstDt;
    }
   


    @Column(name="FC_AGGR_MAST_NBR", nullable=false, precision=9, scale=0)
    public int getFcAggrMastNbr() {
        return this.fcAggrMastNbr;
    }
    
    public void setFcAggrMastNbr(int fcAggrMastNbr) {
        this.fcAggrMastNbr = fcAggrMastNbr;
    }


    @Column(name="FC_FCST_DT", nullable=false, length=7)
    public Date getFcFcstDt() {
        return this.fcFcstDt;
    }
    
    public void setFcFcstDt(Date fcFcstDt) {
        this.fcFcstDt = fcFcstDt;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FcFcstAggrId) ) return false;
		 FcFcstAggrId castOther = ( FcFcstAggrId ) other; 
         
		 return (this.getFcAggrMastNbr()==castOther.getFcAggrMastNbr())
 && ( (this.getFcFcstDt()==castOther.getFcFcstDt()) || ( this.getFcFcstDt()!=null && castOther.getFcFcstDt()!=null && this.getFcFcstDt().equals(castOther.getFcFcstDt()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFcAggrMastNbr();
         result = 37 * result + ( getFcFcstDt() == null ? 0 : this.getFcFcstDt().hashCode() );
         return result;
   }   


}


