package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FcFcstAggrCycleVw generated by hbm2java
 */
@Entity
@Table(name="FC_FCST_AGGR_CYCLE_VW"
)
public class FcFcstAggrCycleVw  implements java.io.Serializable {


     private FcFcstAggrCycleVwId id;

    public FcFcstAggrCycleVw() {
    }

    public FcFcstAggrCycleVw(FcFcstAggrCycleVwId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fcAggrMastNbr", column=@Column(name="FC_AGGR_MAST_NBR") ), 
        @AttributeOverride(name="fcstGrp", column=@Column(name="FCST_GRP") ), 
        @AttributeOverride(name="fcstTypeId", column=@Column(name="FCST_TYPE_ID") ), 
        @AttributeOverride(name="fcstAggrTypeId", column=@Column(name="FCST_AGGR_TYPE_ID") ), 
        @AttributeOverride(name="cycle", column=@Column(name="CYCLE") ), 
        @AttributeOverride(name="rawFcstJan", column=@Column(name="RAW_FCST_JAN") ), 
        @AttributeOverride(name="rawFcstFeb", column=@Column(name="RAW_FCST_FEB") ), 
        @AttributeOverride(name="rawFcstMar", column=@Column(name="RAW_FCST_MAR") ), 
        @AttributeOverride(name="rawFcstApr", column=@Column(name="RAW_FCST_APR") ), 
        @AttributeOverride(name="rawFcstMay", column=@Column(name="RAW_FCST_MAY") ), 
        @AttributeOverride(name="rawFcstJun", column=@Column(name="RAW_FCST_JUN") ), 
        @AttributeOverride(name="rawFcstJul", column=@Column(name="RAW_FCST_JUL") ), 
        @AttributeOverride(name="rawFcstAug", column=@Column(name="RAW_FCST_AUG") ), 
        @AttributeOverride(name="rawFcstSep", column=@Column(name="RAW_FCST_SEP") ), 
        @AttributeOverride(name="rawFcstOct", column=@Column(name="RAW_FCST_OCT") ), 
        @AttributeOverride(name="rawFcstNov", column=@Column(name="RAW_FCST_NOV") ), 
        @AttributeOverride(name="rawFcstDec", column=@Column(name="RAW_FCST_DEC") ), 
        @AttributeOverride(name="rawFcstTot", column=@Column(name="RAW_FCST_TOT") ), 
        @AttributeOverride(name="adjFcstJan", column=@Column(name="ADJ_FCST_JAN") ), 
        @AttributeOverride(name="adjFcstFeb", column=@Column(name="ADJ_FCST_FEB") ), 
        @AttributeOverride(name="adjFcstMar", column=@Column(name="ADJ_FCST_MAR") ), 
        @AttributeOverride(name="adjFcstApr", column=@Column(name="ADJ_FCST_APR") ), 
        @AttributeOverride(name="adjFcstMay", column=@Column(name="ADJ_FCST_MAY") ), 
        @AttributeOverride(name="adjFcstJun", column=@Column(name="ADJ_FCST_JUN") ), 
        @AttributeOverride(name="adjFcstJul", column=@Column(name="ADJ_FCST_JUL") ), 
        @AttributeOverride(name="adjFcstAug", column=@Column(name="ADJ_FCST_AUG") ), 
        @AttributeOverride(name="adjFcstSep", column=@Column(name="ADJ_FCST_SEP") ), 
        @AttributeOverride(name="adjFcstOct", column=@Column(name="ADJ_FCST_OCT") ), 
        @AttributeOverride(name="adjFcstNov", column=@Column(name="ADJ_FCST_NOV") ), 
        @AttributeOverride(name="adjFcstDec", column=@Column(name="ADJ_FCST_DEC") ), 
        @AttributeOverride(name="adjFcstTot", column=@Column(name="ADJ_FCST_TOT") ) } )
    public FcFcstAggrCycleVwId getId() {
        return this.id;
    }
    
    public void setId(FcFcstAggrCycleVwId id) {
        this.id = id;
    }




}


