package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FcFcstBucket generated by hbm2java
 */
@Entity
@Table(name="FC_FCST_BUCKET"
)
public class FcFcstBucket  implements java.io.Serializable {


     private FcFcstBucketId id;

    public FcFcstBucket() {
    }

    public FcFcstBucket(FcFcstBucketId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fcItemMastNbr", column=@Column(name="FC_ITEM_MAST_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="prdStartDt", column=@Column(name="PRD_START_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="intvl", column=@Column(name="INTVL", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="intvlStartDt", column=@Column(name="INTVL_START_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="fcFcstDt", column=@Column(name="FC_FCST_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="fracPrdDmdRaw", column=@Column(name="FRAC_PRD_DMD_RAW", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="wholePrdDmdRaw", column=@Column(name="WHOLE_PRD_DMD_RAW", precision=22, scale=0) ), 
        @AttributeOverride(name="wholePrdAdjRaw", column=@Column(name="WHOLE_PRD_ADJ_RAW", precision=22, scale=0) ), 
        @AttributeOverride(name="fracPrdDmdAdj", column=@Column(name="FRAC_PRD_DMD_ADJ", precision=22, scale=0) ), 
        @AttributeOverride(name="wholePrdDmdAdj", column=@Column(name="WHOLE_PRD_DMD_ADJ", precision=22, scale=0) ), 
        @AttributeOverride(name="wholePrdAdjAdj", column=@Column(name="WHOLE_PRD_ADJ_ADJ", precision=22, scale=0) ) } )
    public FcFcstBucketId getId() {
        return this.id;
    }
    
    public void setId(FcFcstBucketId id) {
        this.id = id;
    }




}


