package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FcFcstMdlGrp generated by hbm2java
 */
@Entity
@Table(name="FC_FCST_MDL_GRP"
)
public class FcFcstMdlGrp  implements java.io.Serializable {


     private FcFcstMdlGrpId id;

    public FcFcstMdlGrp() {
    }

    public FcFcstMdlGrp(FcFcstMdlGrpId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fcstMdlGrp", column=@Column(name="FCST_MDL_GRP", nullable=false, length=16) ), 
        @AttributeOverride(name="fcstMdlNbr", column=@Column(name="FCST_MDL_NBR", nullable=false, precision=3, scale=0) ) } )
    public FcFcstMdlGrpId getId() {
        return this.id;
    }
    
    public void setId(FcFcstMdlGrpId id) {
        this.id = id;
    }




}


