package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FcFcstBucketId generated by hbm2java
 */
@Embeddable
public class FcFcstBucketId  implements java.io.Serializable {


     private int fcItemMastNbr;
     private Date prdStartDt;
     private byte intvl;
     private Date intvlStartDt;
     private Date fcFcstDt;
     private BigDecimal fracPrdDmdRaw;
     private BigDecimal wholePrdDmdRaw;
     private BigDecimal wholePrdAdjRaw;
     private BigDecimal fracPrdDmdAdj;
     private BigDecimal wholePrdDmdAdj;
     private BigDecimal wholePrdAdjAdj;

    public FcFcstBucketId() {
    }

	
    public FcFcstBucketId(int fcItemMastNbr, Date prdStartDt, byte intvl, Date intvlStartDt, Date fcFcstDt, BigDecimal fracPrdDmdRaw) {
        this.fcItemMastNbr = fcItemMastNbr;
        this.prdStartDt = prdStartDt;
        this.intvl = intvl;
        this.intvlStartDt = intvlStartDt;
        this.fcFcstDt = fcFcstDt;
        this.fracPrdDmdRaw = fracPrdDmdRaw;
    }
    public FcFcstBucketId(int fcItemMastNbr, Date prdStartDt, byte intvl, Date intvlStartDt, Date fcFcstDt, BigDecimal fracPrdDmdRaw, BigDecimal wholePrdDmdRaw, BigDecimal wholePrdAdjRaw, BigDecimal fracPrdDmdAdj, BigDecimal wholePrdDmdAdj, BigDecimal wholePrdAdjAdj) {
       this.fcItemMastNbr = fcItemMastNbr;
       this.prdStartDt = prdStartDt;
       this.intvl = intvl;
       this.intvlStartDt = intvlStartDt;
       this.fcFcstDt = fcFcstDt;
       this.fracPrdDmdRaw = fracPrdDmdRaw;
       this.wholePrdDmdRaw = wholePrdDmdRaw;
       this.wholePrdAdjRaw = wholePrdAdjRaw;
       this.fracPrdDmdAdj = fracPrdDmdAdj;
       this.wholePrdDmdAdj = wholePrdDmdAdj;
       this.wholePrdAdjAdj = wholePrdAdjAdj;
    }
   


    @Column(name="FC_ITEM_MAST_NBR", nullable=false, precision=9, scale=0)
    public int getFcItemMastNbr() {
        return this.fcItemMastNbr;
    }
    
    public void setFcItemMastNbr(int fcItemMastNbr) {
        this.fcItemMastNbr = fcItemMastNbr;
    }


    @Column(name="PRD_START_DT", nullable=false, length=7)
    public Date getPrdStartDt() {
        return this.prdStartDt;
    }
    
    public void setPrdStartDt(Date prdStartDt) {
        this.prdStartDt = prdStartDt;
    }


    @Column(name="INTVL", nullable=false, precision=2, scale=0)
    public byte getIntvl() {
        return this.intvl;
    }
    
    public void setIntvl(byte intvl) {
        this.intvl = intvl;
    }


    @Column(name="INTVL_START_DT", nullable=false, length=7)
    public Date getIntvlStartDt() {
        return this.intvlStartDt;
    }
    
    public void setIntvlStartDt(Date intvlStartDt) {
        this.intvlStartDt = intvlStartDt;
    }


    @Column(name="FC_FCST_DT", nullable=false, length=7)
    public Date getFcFcstDt() {
        return this.fcFcstDt;
    }
    
    public void setFcFcstDt(Date fcFcstDt) {
        this.fcFcstDt = fcFcstDt;
    }


    @Column(name="FRAC_PRD_DMD_RAW", nullable=false, precision=22, scale=0)
    public BigDecimal getFracPrdDmdRaw() {
        return this.fracPrdDmdRaw;
    }
    
    public void setFracPrdDmdRaw(BigDecimal fracPrdDmdRaw) {
        this.fracPrdDmdRaw = fracPrdDmdRaw;
    }


    @Column(name="WHOLE_PRD_DMD_RAW", precision=22, scale=0)
    public BigDecimal getWholePrdDmdRaw() {
        return this.wholePrdDmdRaw;
    }
    
    public void setWholePrdDmdRaw(BigDecimal wholePrdDmdRaw) {
        this.wholePrdDmdRaw = wholePrdDmdRaw;
    }


    @Column(name="WHOLE_PRD_ADJ_RAW", precision=22, scale=0)
    public BigDecimal getWholePrdAdjRaw() {
        return this.wholePrdAdjRaw;
    }
    
    public void setWholePrdAdjRaw(BigDecimal wholePrdAdjRaw) {
        this.wholePrdAdjRaw = wholePrdAdjRaw;
    }


    @Column(name="FRAC_PRD_DMD_ADJ", precision=22, scale=0)
    public BigDecimal getFracPrdDmdAdj() {
        return this.fracPrdDmdAdj;
    }
    
    public void setFracPrdDmdAdj(BigDecimal fracPrdDmdAdj) {
        this.fracPrdDmdAdj = fracPrdDmdAdj;
    }


    @Column(name="WHOLE_PRD_DMD_ADJ", precision=22, scale=0)
    public BigDecimal getWholePrdDmdAdj() {
        return this.wholePrdDmdAdj;
    }
    
    public void setWholePrdDmdAdj(BigDecimal wholePrdDmdAdj) {
        this.wholePrdDmdAdj = wholePrdDmdAdj;
    }


    @Column(name="WHOLE_PRD_ADJ_ADJ", precision=22, scale=0)
    public BigDecimal getWholePrdAdjAdj() {
        return this.wholePrdAdjAdj;
    }
    
    public void setWholePrdAdjAdj(BigDecimal wholePrdAdjAdj) {
        this.wholePrdAdjAdj = wholePrdAdjAdj;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FcFcstBucketId) ) return false;
		 FcFcstBucketId castOther = ( FcFcstBucketId ) other; 
         
		 return (this.getFcItemMastNbr()==castOther.getFcItemMastNbr())
 && ( (this.getPrdStartDt()==castOther.getPrdStartDt()) || ( this.getPrdStartDt()!=null && castOther.getPrdStartDt()!=null && this.getPrdStartDt().equals(castOther.getPrdStartDt()) ) )
 && (this.getIntvl()==castOther.getIntvl())
 && ( (this.getIntvlStartDt()==castOther.getIntvlStartDt()) || ( this.getIntvlStartDt()!=null && castOther.getIntvlStartDt()!=null && this.getIntvlStartDt().equals(castOther.getIntvlStartDt()) ) )
 && ( (this.getFcFcstDt()==castOther.getFcFcstDt()) || ( this.getFcFcstDt()!=null && castOther.getFcFcstDt()!=null && this.getFcFcstDt().equals(castOther.getFcFcstDt()) ) )
 && ( (this.getFracPrdDmdRaw()==castOther.getFracPrdDmdRaw()) || ( this.getFracPrdDmdRaw()!=null && castOther.getFracPrdDmdRaw()!=null && this.getFracPrdDmdRaw().equals(castOther.getFracPrdDmdRaw()) ) )
 && ( (this.getWholePrdDmdRaw()==castOther.getWholePrdDmdRaw()) || ( this.getWholePrdDmdRaw()!=null && castOther.getWholePrdDmdRaw()!=null && this.getWholePrdDmdRaw().equals(castOther.getWholePrdDmdRaw()) ) )
 && ( (this.getWholePrdAdjRaw()==castOther.getWholePrdAdjRaw()) || ( this.getWholePrdAdjRaw()!=null && castOther.getWholePrdAdjRaw()!=null && this.getWholePrdAdjRaw().equals(castOther.getWholePrdAdjRaw()) ) )
 && ( (this.getFracPrdDmdAdj()==castOther.getFracPrdDmdAdj()) || ( this.getFracPrdDmdAdj()!=null && castOther.getFracPrdDmdAdj()!=null && this.getFracPrdDmdAdj().equals(castOther.getFracPrdDmdAdj()) ) )
 && ( (this.getWholePrdDmdAdj()==castOther.getWholePrdDmdAdj()) || ( this.getWholePrdDmdAdj()!=null && castOther.getWholePrdDmdAdj()!=null && this.getWholePrdDmdAdj().equals(castOther.getWholePrdDmdAdj()) ) )
 && ( (this.getWholePrdAdjAdj()==castOther.getWholePrdAdjAdj()) || ( this.getWholePrdAdjAdj()!=null && castOther.getWholePrdAdjAdj()!=null && this.getWholePrdAdjAdj().equals(castOther.getWholePrdAdjAdj()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFcItemMastNbr();
         result = 37 * result + ( getPrdStartDt() == null ? 0 : this.getPrdStartDt().hashCode() );
         result = 37 * result + this.getIntvl();
         result = 37 * result + ( getIntvlStartDt() == null ? 0 : this.getIntvlStartDt().hashCode() );
         result = 37 * result + ( getFcFcstDt() == null ? 0 : this.getFcFcstDt().hashCode() );
         result = 37 * result + ( getFracPrdDmdRaw() == null ? 0 : this.getFracPrdDmdRaw().hashCode() );
         result = 37 * result + ( getWholePrdDmdRaw() == null ? 0 : this.getWholePrdDmdRaw().hashCode() );
         result = 37 * result + ( getWholePrdAdjRaw() == null ? 0 : this.getWholePrdAdjRaw().hashCode() );
         result = 37 * result + ( getFracPrdDmdAdj() == null ? 0 : this.getFracPrdDmdAdj().hashCode() );
         result = 37 * result + ( getWholePrdDmdAdj() == null ? 0 : this.getWholePrdDmdAdj().hashCode() );
         result = 37 * result + ( getWholePrdAdjAdj() == null ? 0 : this.getWholePrdAdjAdj().hashCode() );
         return result;
   }   


}


