package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FcHdrTmpId generated by hbm2java
 */
@Embeddable
public class FcHdrTmpId  implements java.io.Serializable {


     private String userFld1;
     private String userFld2;

    public FcHdrTmpId() {
    }

    public FcHdrTmpId(String userFld1, String userFld2) {
       this.userFld1 = userFld1;
       this.userFld2 = userFld2;
    }
   


    @Column(name="USER_FLD_1", nullable=false, length=20)
    public String getUserFld1() {
        return this.userFld1;
    }
    
    public void setUserFld1(String userFld1) {
        this.userFld1 = userFld1;
    }


    @Column(name="USER_FLD_2", nullable=false, length=20)
    public String getUserFld2() {
        return this.userFld2;
    }
    
    public void setUserFld2(String userFld2) {
        this.userFld2 = userFld2;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FcHdrTmpId) ) return false;
		 FcHdrTmpId castOther = ( FcHdrTmpId ) other; 
         
		 return ( (this.getUserFld1()==castOther.getUserFld1()) || ( this.getUserFld1()!=null && castOther.getUserFld1()!=null && this.getUserFld1().equals(castOther.getUserFld1()) ) )
 && ( (this.getUserFld2()==castOther.getUserFld2()) || ( this.getUserFld2()!=null && castOther.getUserFld2()!=null && this.getUserFld2().equals(castOther.getUserFld2()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserFld1() == null ? 0 : this.getUserFld1().hashCode() );
         result = 37 * result + ( getUserFld2() == null ? 0 : this.getUserFld2().hashCode() );
         return result;
   }   


}


