package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FcHist generated by hbm2java
 */
@Entity
@Table(name="FC_HIST"
)
public class FcHist  implements java.io.Serializable {


     private int fcHistNbr;
     private FcItemMast fcItemMast;
     private Short cycle;
     private Short intvl;
     private BigDecimal dmdAct;
     private BigDecimal dmdAdj;

    public FcHist() {
    }

	
    public FcHist(int fcHistNbr) {
        this.fcHistNbr = fcHistNbr;
    }
    public FcHist(int fcHistNbr, FcItemMast fcItemMast, Short cycle, Short intvl, BigDecimal dmdAct, BigDecimal dmdAdj) {
       this.fcHistNbr = fcHistNbr;
       this.fcItemMast = fcItemMast;
       this.cycle = cycle;
       this.intvl = intvl;
       this.dmdAct = dmdAct;
       this.dmdAdj = dmdAdj;
    }
   
     @Id 

    
    @Column(name="FC_HIST_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getFcHistNbr() {
        return this.fcHistNbr;
    }
    
    public void setFcHistNbr(int fcHistNbr) {
        this.fcHistNbr = fcHistNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FC_ITEM_MAST_NBR")
    public FcItemMast getFcItemMast() {
        return this.fcItemMast;
    }
    
    public void setFcItemMast(FcItemMast fcItemMast) {
        this.fcItemMast = fcItemMast;
    }

    
    @Column(name="CYCLE", precision=4, scale=0)
    public Short getCycle() {
        return this.cycle;
    }
    
    public void setCycle(Short cycle) {
        this.cycle = cycle;
    }

    
    @Column(name="INTVL", precision=4, scale=0)
    public Short getIntvl() {
        return this.intvl;
    }
    
    public void setIntvl(Short intvl) {
        this.intvl = intvl;
    }

    
    @Column(name="DMD_ACT", precision=9)
    public BigDecimal getDmdAct() {
        return this.dmdAct;
    }
    
    public void setDmdAct(BigDecimal dmdAct) {
        this.dmdAct = dmdAct;
    }

    
    @Column(name="DMD_ADJ", precision=9)
    public BigDecimal getDmdAdj() {
        return this.dmdAdj;
    }
    
    public void setDmdAdj(BigDecimal dmdAdj) {
        this.dmdAdj = dmdAdj;
    }




}


