package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FcstReportDtl generated by hbm2java
 */
@Entity
@Table(name="FCST_REPORT_DTL"
)
public class FcstReportDtl  implements java.io.Serializable {


     private FcstReportDtlId id;

    public FcstReportDtl() {
    }

    public FcstReportDtl(FcstReportDtlId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="sessionId", column=@Column(name="SESSION_ID", nullable=false, length=100) ), 
        @AttributeOverride(name="groupingString", column=@Column(name="GROUPING_STRING", nullable=false, length=100) ), 
        @AttributeOverride(name="sortSeq", column=@Column(name="SORT_SEQ", precision=3, scale=0) ), 
        @AttributeOverride(name="dmdType", column=@Column(name="DMD_TYPE", nullable=false, length=40) ), 
        @AttributeOverride(name="qtyMnth1", column=@Column(name="QTY_MNTH_1", precision=22, scale=0) ), 
        @AttributeOverride(name="qtyMnth2", column=@Column(name="QTY_MNTH_2", precision=22, scale=0) ), 
        @AttributeOverride(name="qtyMnth3", column=@Column(name="QTY_MNTH_3", precision=22, scale=0) ), 
        @AttributeOverride(name="qtyMnth4", column=@Column(name="QTY_MNTH_4", precision=22, scale=0) ), 
        @AttributeOverride(name="qtyMnth5", column=@Column(name="QTY_MNTH_5", precision=22, scale=0) ), 
        @AttributeOverride(name="qtyMnth6", column=@Column(name="QTY_MNTH_6", precision=22, scale=0) ), 
        @AttributeOverride(name="qtyMnth7", column=@Column(name="QTY_MNTH_7", precision=22, scale=0) ), 
        @AttributeOverride(name="qtyMnth8", column=@Column(name="QTY_MNTH_8", precision=22, scale=0) ), 
        @AttributeOverride(name="qtyMnth9", column=@Column(name="QTY_MNTH_9", precision=22, scale=0) ), 
        @AttributeOverride(name="qtyMnth10", column=@Column(name="QTY_MNTH_10", precision=22, scale=0) ), 
        @AttributeOverride(name="qtyMnth11", column=@Column(name="QTY_MNTH_11", precision=22, scale=0) ), 
        @AttributeOverride(name="qtyMnth12", column=@Column(name="QTY_MNTH_12", precision=22, scale=0) ) } )
    public FcstReportDtlId getId() {
        return this.id;
    }
    
    public void setId(FcstReportDtlId id) {
        this.id = id;
    }




}


