package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FcstGrp generated by hbm2java
 */
@Entity
@Table(name="FCST_GRP"
)
public class FcstGrp  implements java.io.Serializable {


     private String fcstGrp;
     private String fcstGrpDescr;
     private int utUserNbr;
     private Date lastModDt;
     private byte ooPrty;
     private byte woPrty;
     private byte ssPrty;
     private byte fcPrty;
     private Set<OeCustContract> oeCustContracts = new HashSet<OeCustContract>(0);
     private Set<OeCustMast> oeCustMasts = new HashSet<OeCustMast>(0);
     private Set<FcItemMast> fcItemMasts = new HashSet<FcItemMast>(0);
     private Set<FcAggrMast> fcAggrMasts = new HashSet<FcAggrMast>(0);

    public FcstGrp() {
    }

	
    public FcstGrp(String fcstGrp, String fcstGrpDescr, int utUserNbr, Date lastModDt, byte ooPrty, byte woPrty, byte ssPrty, byte fcPrty) {
        this.fcstGrp = fcstGrp;
        this.fcstGrpDescr = fcstGrpDescr;
        this.utUserNbr = utUserNbr;
        this.lastModDt = lastModDt;
        this.ooPrty = ooPrty;
        this.woPrty = woPrty;
        this.ssPrty = ssPrty;
        this.fcPrty = fcPrty;
    }
    public FcstGrp(String fcstGrp, String fcstGrpDescr, int utUserNbr, Date lastModDt, byte ooPrty, byte woPrty, byte ssPrty, byte fcPrty, Set<OeCustContract> oeCustContracts, Set<OeCustMast> oeCustMasts, Set<FcItemMast> fcItemMasts, Set<FcAggrMast> fcAggrMasts) {
       this.fcstGrp = fcstGrp;
       this.fcstGrpDescr = fcstGrpDescr;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
       this.ooPrty = ooPrty;
       this.woPrty = woPrty;
       this.ssPrty = ssPrty;
       this.fcPrty = fcPrty;
       this.oeCustContracts = oeCustContracts;
       this.oeCustMasts = oeCustMasts;
       this.fcItemMasts = fcItemMasts;
       this.fcAggrMasts = fcAggrMasts;
    }
   
     @Id 

    
    @Column(name="FCST_GRP", unique=true, nullable=false, length=8)
    public String getFcstGrp() {
        return this.fcstGrp;
    }
    
    public void setFcstGrp(String fcstGrp) {
        this.fcstGrp = fcstGrp;
    }

    
    @Column(name="FCST_GRP_DESCR", nullable=false, length=60)
    public String getFcstGrpDescr() {
        return this.fcstGrpDescr;
    }
    
    public void setFcstGrpDescr(String fcstGrpDescr) {
        this.fcstGrpDescr = fcstGrpDescr;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }

    
    @Column(name="OO_PRTY", nullable=false, precision=2, scale=0)
    public byte getOoPrty() {
        return this.ooPrty;
    }
    
    public void setOoPrty(byte ooPrty) {
        this.ooPrty = ooPrty;
    }

    
    @Column(name="WO_PRTY", nullable=false, precision=2, scale=0)
    public byte getWoPrty() {
        return this.woPrty;
    }
    
    public void setWoPrty(byte woPrty) {
        this.woPrty = woPrty;
    }

    
    @Column(name="SS_PRTY", nullable=false, precision=2, scale=0)
    public byte getSsPrty() {
        return this.ssPrty;
    }
    
    public void setSsPrty(byte ssPrty) {
        this.ssPrty = ssPrty;
    }

    
    @Column(name="FC_PRTY", nullable=false, precision=2, scale=0)
    public byte getFcPrty() {
        return this.fcPrty;
    }
    
    public void setFcPrty(byte fcPrty) {
        this.fcPrty = fcPrty;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fcstGrp")
    public Set<OeCustContract> getOeCustContracts() {
        return this.oeCustContracts;
    }
    
    public void setOeCustContracts(Set<OeCustContract> oeCustContracts) {
        this.oeCustContracts = oeCustContracts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fcstGrp")
    public Set<OeCustMast> getOeCustMasts() {
        return this.oeCustMasts;
    }
    
    public void setOeCustMasts(Set<OeCustMast> oeCustMasts) {
        this.oeCustMasts = oeCustMasts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fcstGrp")
    public Set<FcItemMast> getFcItemMasts() {
        return this.fcItemMasts;
    }
    
    public void setFcItemMasts(Set<FcItemMast> fcItemMasts) {
        this.fcItemMasts = fcItemMasts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fcstGrp")
    public Set<FcAggrMast> getFcAggrMasts() {
        return this.fcAggrMasts;
    }
    
    public void setFcAggrMasts(Set<FcAggrMast> fcAggrMasts) {
        this.fcAggrMasts = fcAggrMasts;
    }




}


