package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FimAttrId generated by hbm2java
 */
@Embeddable
public class FimAttrId  implements java.io.Serializable {


     private int fcItemMastNbr;
     private Integer itemNbr;
     private BigDecimal svcLvl;
     private short totLeadTime;
     private BigDecimal safetyStkMinPrd;
     private BigDecimal safetyStkMaxPrd;
     private BigDecimal safetyStkMinUnit;
     private BigDecimal safetyStkMaxUnit;
     private Integer replenQtyMinUnit;
     private Integer replenQtyMaxUnit;
     private BigDecimal replenQtyMinPrd;
     private BigDecimal replenQtyMaxPrd;
     private String storeAltFcstFlg;
     private String archAltFcstFlg;
     private String calendar;
     private String fcstMdlGrp;
     private String statId;
     private Integer apsSrcRuleSetNbr;
     private Integer safetyStkAdj;
     private String fcstTypeId;
     private Integer orgNbrCust;
     private String revLvl;
     private Integer orgNbrMfrRqst;
     private String fcstGrp;
     private String fcItemMastStatId;
     private String fcItemMastDescr;
     private Integer safetyStkAllocQty;
     private Date fcstEndDt;
     private BigDecimal unitCostStkUm;
     private BigDecimal safetyStkCalc;
     private BigDecimal safetyStkConstrain;
     private String custRefCd;
     private String safetyStkAvailToSell;
     private String hardAllocFcWithinLeadTm;
     private String fcBuildRateGrpCd;
     private String descr;
     private String prodLine;
     private String style;
     private String color;
     private String prodSize;
     private String custGrp;

    public FimAttrId() {
    }

	
    public FimAttrId(int fcItemMastNbr, short totLeadTime, String fcstTypeId, String fcItemMastStatId, String safetyStkAvailToSell, String hardAllocFcWithinLeadTm, String prodLine, String style, String color, String prodSize, String custGrp) {
        this.fcItemMastNbr = fcItemMastNbr;
        this.totLeadTime = totLeadTime;
        this.fcstTypeId = fcstTypeId;
        this.fcItemMastStatId = fcItemMastStatId;
        this.safetyStkAvailToSell = safetyStkAvailToSell;
        this.hardAllocFcWithinLeadTm = hardAllocFcWithinLeadTm;
        this.prodLine = prodLine;
        this.style = style;
        this.color = color;
        this.prodSize = prodSize;
        this.custGrp = custGrp;
    }
    public FimAttrId(int fcItemMastNbr, Integer itemNbr, BigDecimal svcLvl, short totLeadTime, BigDecimal safetyStkMinPrd, BigDecimal safetyStkMaxPrd, BigDecimal safetyStkMinUnit, BigDecimal safetyStkMaxUnit, Integer replenQtyMinUnit, Integer replenQtyMaxUnit, BigDecimal replenQtyMinPrd, BigDecimal replenQtyMaxPrd, String storeAltFcstFlg, String archAltFcstFlg, String calendar, String fcstMdlGrp, String statId, Integer apsSrcRuleSetNbr, Integer safetyStkAdj, String fcstTypeId, Integer orgNbrCust, String revLvl, Integer orgNbrMfrRqst, String fcstGrp, String fcItemMastStatId, String fcItemMastDescr, Integer safetyStkAllocQty, Date fcstEndDt, BigDecimal unitCostStkUm, BigDecimal safetyStkCalc, BigDecimal safetyStkConstrain, String custRefCd, String safetyStkAvailToSell, String hardAllocFcWithinLeadTm, String fcBuildRateGrpCd, String descr, String prodLine, String style, String color, String prodSize, String custGrp) {
       this.fcItemMastNbr = fcItemMastNbr;
       this.itemNbr = itemNbr;
       this.svcLvl = svcLvl;
       this.totLeadTime = totLeadTime;
       this.safetyStkMinPrd = safetyStkMinPrd;
       this.safetyStkMaxPrd = safetyStkMaxPrd;
       this.safetyStkMinUnit = safetyStkMinUnit;
       this.safetyStkMaxUnit = safetyStkMaxUnit;
       this.replenQtyMinUnit = replenQtyMinUnit;
       this.replenQtyMaxUnit = replenQtyMaxUnit;
       this.replenQtyMinPrd = replenQtyMinPrd;
       this.replenQtyMaxPrd = replenQtyMaxPrd;
       this.storeAltFcstFlg = storeAltFcstFlg;
       this.archAltFcstFlg = archAltFcstFlg;
       this.calendar = calendar;
       this.fcstMdlGrp = fcstMdlGrp;
       this.statId = statId;
       this.apsSrcRuleSetNbr = apsSrcRuleSetNbr;
       this.safetyStkAdj = safetyStkAdj;
       this.fcstTypeId = fcstTypeId;
       this.orgNbrCust = orgNbrCust;
       this.revLvl = revLvl;
       this.orgNbrMfrRqst = orgNbrMfrRqst;
       this.fcstGrp = fcstGrp;
       this.fcItemMastStatId = fcItemMastStatId;
       this.fcItemMastDescr = fcItemMastDescr;
       this.safetyStkAllocQty = safetyStkAllocQty;
       this.fcstEndDt = fcstEndDt;
       this.unitCostStkUm = unitCostStkUm;
       this.safetyStkCalc = safetyStkCalc;
       this.safetyStkConstrain = safetyStkConstrain;
       this.custRefCd = custRefCd;
       this.safetyStkAvailToSell = safetyStkAvailToSell;
       this.hardAllocFcWithinLeadTm = hardAllocFcWithinLeadTm;
       this.fcBuildRateGrpCd = fcBuildRateGrpCd;
       this.descr = descr;
       this.prodLine = prodLine;
       this.style = style;
       this.color = color;
       this.prodSize = prodSize;
       this.custGrp = custGrp;
    }
   


    @Column(name="FC_ITEM_MAST_NBR", nullable=false, precision=9, scale=0)
    public int getFcItemMastNbr() {
        return this.fcItemMastNbr;
    }
    
    public void setFcItemMastNbr(int fcItemMastNbr) {
        this.fcItemMastNbr = fcItemMastNbr;
    }


    @Column(name="ITEM_NBR", precision=9, scale=0)
    public Integer getItemNbr() {
        return this.itemNbr;
    }
    
    public void setItemNbr(Integer itemNbr) {
        this.itemNbr = itemNbr;
    }


    @Column(name="SVC_LVL", precision=5)
    public BigDecimal getSvcLvl() {
        return this.svcLvl;
    }
    
    public void setSvcLvl(BigDecimal svcLvl) {
        this.svcLvl = svcLvl;
    }


    @Column(name="TOT_LEAD_TIME", nullable=false, precision=4, scale=0)
    public short getTotLeadTime() {
        return this.totLeadTime;
    }
    
    public void setTotLeadTime(short totLeadTime) {
        this.totLeadTime = totLeadTime;
    }


    @Column(name="SAFETY_STK_MIN_PRD", precision=3, scale=1)
    public BigDecimal getSafetyStkMinPrd() {
        return this.safetyStkMinPrd;
    }
    
    public void setSafetyStkMinPrd(BigDecimal safetyStkMinPrd) {
        this.safetyStkMinPrd = safetyStkMinPrd;
    }


    @Column(name="SAFETY_STK_MAX_PRD", precision=3, scale=1)
    public BigDecimal getSafetyStkMaxPrd() {
        return this.safetyStkMaxPrd;
    }
    
    public void setSafetyStkMaxPrd(BigDecimal safetyStkMaxPrd) {
        this.safetyStkMaxPrd = safetyStkMaxPrd;
    }


    @Column(name="SAFETY_STK_MIN_UNIT", precision=11, scale=3)
    public BigDecimal getSafetyStkMinUnit() {
        return this.safetyStkMinUnit;
    }
    
    public void setSafetyStkMinUnit(BigDecimal safetyStkMinUnit) {
        this.safetyStkMinUnit = safetyStkMinUnit;
    }


    @Column(name="SAFETY_STK_MAX_UNIT", precision=11, scale=3)
    public BigDecimal getSafetyStkMaxUnit() {
        return this.safetyStkMaxUnit;
    }
    
    public void setSafetyStkMaxUnit(BigDecimal safetyStkMaxUnit) {
        this.safetyStkMaxUnit = safetyStkMaxUnit;
    }


    @Column(name="REPLEN_QTY_MIN_UNIT", precision=8, scale=0)
    public Integer getReplenQtyMinUnit() {
        return this.replenQtyMinUnit;
    }
    
    public void setReplenQtyMinUnit(Integer replenQtyMinUnit) {
        this.replenQtyMinUnit = replenQtyMinUnit;
    }


    @Column(name="REPLEN_QTY_MAX_UNIT", precision=8, scale=0)
    public Integer getReplenQtyMaxUnit() {
        return this.replenQtyMaxUnit;
    }
    
    public void setReplenQtyMaxUnit(Integer replenQtyMaxUnit) {
        this.replenQtyMaxUnit = replenQtyMaxUnit;
    }


    @Column(name="REPLEN_QTY_MIN_PRD", precision=4, scale=1)
    public BigDecimal getReplenQtyMinPrd() {
        return this.replenQtyMinPrd;
    }
    
    public void setReplenQtyMinPrd(BigDecimal replenQtyMinPrd) {
        this.replenQtyMinPrd = replenQtyMinPrd;
    }


    @Column(name="REPLEN_QTY_MAX_PRD", precision=4, scale=1)
    public BigDecimal getReplenQtyMaxPrd() {
        return this.replenQtyMaxPrd;
    }
    
    public void setReplenQtyMaxPrd(BigDecimal replenQtyMaxPrd) {
        this.replenQtyMaxPrd = replenQtyMaxPrd;
    }


    @Column(name="STORE_ALT_FCST_FLG", length=1)
    public String getStoreAltFcstFlg() {
        return this.storeAltFcstFlg;
    }
    
    public void setStoreAltFcstFlg(String storeAltFcstFlg) {
        this.storeAltFcstFlg = storeAltFcstFlg;
    }


    @Column(name="ARCH_ALT_FCST_FLG", length=1)
    public String getArchAltFcstFlg() {
        return this.archAltFcstFlg;
    }
    
    public void setArchAltFcstFlg(String archAltFcstFlg) {
        this.archAltFcstFlg = archAltFcstFlg;
    }


    @Column(name="CALENDAR", length=6)
    public String getCalendar() {
        return this.calendar;
    }
    
    public void setCalendar(String calendar) {
        this.calendar = calendar;
    }


    @Column(name="FCST_MDL_GRP", length=8)
    public String getFcstMdlGrp() {
        return this.fcstMdlGrp;
    }
    
    public void setFcstMdlGrp(String fcstMdlGrp) {
        this.fcstMdlGrp = fcstMdlGrp;
    }


    @Column(name="STAT_ID", length=1)
    public String getStatId() {
        return this.statId;
    }
    
    public void setStatId(String statId) {
        this.statId = statId;
    }


    @Column(name="APS_SRC_RULE_SET_NBR", precision=9, scale=0)
    public Integer getApsSrcRuleSetNbr() {
        return this.apsSrcRuleSetNbr;
    }
    
    public void setApsSrcRuleSetNbr(Integer apsSrcRuleSetNbr) {
        this.apsSrcRuleSetNbr = apsSrcRuleSetNbr;
    }


    @Column(name="SAFETY_STK_ADJ", precision=8, scale=0)
    public Integer getSafetyStkAdj() {
        return this.safetyStkAdj;
    }
    
    public void setSafetyStkAdj(Integer safetyStkAdj) {
        this.safetyStkAdj = safetyStkAdj;
    }


    @Column(name="FCST_TYPE_ID", nullable=false, length=1)
    public String getFcstTypeId() {
        return this.fcstTypeId;
    }
    
    public void setFcstTypeId(String fcstTypeId) {
        this.fcstTypeId = fcstTypeId;
    }


    @Column(name="ORG_NBR_CUST", precision=9, scale=0)
    public Integer getOrgNbrCust() {
        return this.orgNbrCust;
    }
    
    public void setOrgNbrCust(Integer orgNbrCust) {
        this.orgNbrCust = orgNbrCust;
    }


    @Column(name="REV_LVL", length=5)
    public String getRevLvl() {
        return this.revLvl;
    }
    
    public void setRevLvl(String revLvl) {
        this.revLvl = revLvl;
    }


    @Column(name="ORG_NBR_MFR_RQST", precision=9, scale=0)
    public Integer getOrgNbrMfrRqst() {
        return this.orgNbrMfrRqst;
    }
    
    public void setOrgNbrMfrRqst(Integer orgNbrMfrRqst) {
        this.orgNbrMfrRqst = orgNbrMfrRqst;
    }


    @Column(name="FCST_GRP", length=8)
    public String getFcstGrp() {
        return this.fcstGrp;
    }
    
    public void setFcstGrp(String fcstGrp) {
        this.fcstGrp = fcstGrp;
    }


    @Column(name="FC_ITEM_MAST_STAT_ID", nullable=false, length=1)
    public String getFcItemMastStatId() {
        return this.fcItemMastStatId;
    }
    
    public void setFcItemMastStatId(String fcItemMastStatId) {
        this.fcItemMastStatId = fcItemMastStatId;
    }


    @Column(name="FC_ITEM_MAST_DESCR", length=30)
    public String getFcItemMastDescr() {
        return this.fcItemMastDescr;
    }
    
    public void setFcItemMastDescr(String fcItemMastDescr) {
        this.fcItemMastDescr = fcItemMastDescr;
    }


    @Column(name="SAFETY_STK_ALLOC_QTY", precision=8, scale=0)
    public Integer getSafetyStkAllocQty() {
        return this.safetyStkAllocQty;
    }
    
    public void setSafetyStkAllocQty(Integer safetyStkAllocQty) {
        this.safetyStkAllocQty = safetyStkAllocQty;
    }


    @Column(name="FCST_END_DT", length=7)
    public Date getFcstEndDt() {
        return this.fcstEndDt;
    }
    
    public void setFcstEndDt(Date fcstEndDt) {
        this.fcstEndDt = fcstEndDt;
    }


    @Column(name="UNIT_COST_STK_UM", precision=17, scale=5)
    public BigDecimal getUnitCostStkUm() {
        return this.unitCostStkUm;
    }
    
    public void setUnitCostStkUm(BigDecimal unitCostStkUm) {
        this.unitCostStkUm = unitCostStkUm;
    }


    @Column(name="SAFETY_STK_CALC", precision=10)
    public BigDecimal getSafetyStkCalc() {
        return this.safetyStkCalc;
    }
    
    public void setSafetyStkCalc(BigDecimal safetyStkCalc) {
        this.safetyStkCalc = safetyStkCalc;
    }


    @Column(name="SAFETY_STK_CONSTRAIN", precision=10)
    public BigDecimal getSafetyStkConstrain() {
        return this.safetyStkConstrain;
    }
    
    public void setSafetyStkConstrain(BigDecimal safetyStkConstrain) {
        this.safetyStkConstrain = safetyStkConstrain;
    }


    @Column(name="CUST_REF_CD", length=40)
    public String getCustRefCd() {
        return this.custRefCd;
    }
    
    public void setCustRefCd(String custRefCd) {
        this.custRefCd = custRefCd;
    }


    @Column(name="SAFETY_STK_AVAIL_TO_SELL", nullable=false, length=1)
    public String getSafetyStkAvailToSell() {
        return this.safetyStkAvailToSell;
    }
    
    public void setSafetyStkAvailToSell(String safetyStkAvailToSell) {
        this.safetyStkAvailToSell = safetyStkAvailToSell;
    }


    @Column(name="HARD_ALLOC_FC_WITHIN_LEAD_TM", nullable=false, length=1)
    public String getHardAllocFcWithinLeadTm() {
        return this.hardAllocFcWithinLeadTm;
    }
    
    public void setHardAllocFcWithinLeadTm(String hardAllocFcWithinLeadTm) {
        this.hardAllocFcWithinLeadTm = hardAllocFcWithinLeadTm;
    }


    @Column(name="FC_BUILD_RATE_GRP_CD", length=10)
    public String getFcBuildRateGrpCd() {
        return this.fcBuildRateGrpCd;
    }
    
    public void setFcBuildRateGrpCd(String fcBuildRateGrpCd) {
        this.fcBuildRateGrpCd = fcBuildRateGrpCd;
    }


    @Column(name="DESCR", length=50)
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }


    @Column(name="PROD_LINE", nullable=false, length=20)
    public String getProdLine() {
        return this.prodLine;
    }
    
    public void setProdLine(String prodLine) {
        this.prodLine = prodLine;
    }


    @Column(name="STYLE", nullable=false, length=20)
    public String getStyle() {
        return this.style;
    }
    
    public void setStyle(String style) {
        this.style = style;
    }


    @Column(name="COLOR", nullable=false, length=20)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }


    @Column(name="PROD_SIZE", nullable=false, length=20)
    public String getProdSize() {
        return this.prodSize;
    }
    
    public void setProdSize(String prodSize) {
        this.prodSize = prodSize;
    }


    @Column(name="CUST_GRP", nullable=false, length=20)
    public String getCustGrp() {
        return this.custGrp;
    }
    
    public void setCustGrp(String custGrp) {
        this.custGrp = custGrp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FimAttrId) ) return false;
		 FimAttrId castOther = ( FimAttrId ) other; 
         
		 return (this.getFcItemMastNbr()==castOther.getFcItemMastNbr())
 && ( (this.getItemNbr()==castOther.getItemNbr()) || ( this.getItemNbr()!=null && castOther.getItemNbr()!=null && this.getItemNbr().equals(castOther.getItemNbr()) ) )
 && ( (this.getSvcLvl()==castOther.getSvcLvl()) || ( this.getSvcLvl()!=null && castOther.getSvcLvl()!=null && this.getSvcLvl().equals(castOther.getSvcLvl()) ) )
 && (this.getTotLeadTime()==castOther.getTotLeadTime())
 && ( (this.getSafetyStkMinPrd()==castOther.getSafetyStkMinPrd()) || ( this.getSafetyStkMinPrd()!=null && castOther.getSafetyStkMinPrd()!=null && this.getSafetyStkMinPrd().equals(castOther.getSafetyStkMinPrd()) ) )
 && ( (this.getSafetyStkMaxPrd()==castOther.getSafetyStkMaxPrd()) || ( this.getSafetyStkMaxPrd()!=null && castOther.getSafetyStkMaxPrd()!=null && this.getSafetyStkMaxPrd().equals(castOther.getSafetyStkMaxPrd()) ) )
 && ( (this.getSafetyStkMinUnit()==castOther.getSafetyStkMinUnit()) || ( this.getSafetyStkMinUnit()!=null && castOther.getSafetyStkMinUnit()!=null && this.getSafetyStkMinUnit().equals(castOther.getSafetyStkMinUnit()) ) )
 && ( (this.getSafetyStkMaxUnit()==castOther.getSafetyStkMaxUnit()) || ( this.getSafetyStkMaxUnit()!=null && castOther.getSafetyStkMaxUnit()!=null && this.getSafetyStkMaxUnit().equals(castOther.getSafetyStkMaxUnit()) ) )
 && ( (this.getReplenQtyMinUnit()==castOther.getReplenQtyMinUnit()) || ( this.getReplenQtyMinUnit()!=null && castOther.getReplenQtyMinUnit()!=null && this.getReplenQtyMinUnit().equals(castOther.getReplenQtyMinUnit()) ) )
 && ( (this.getReplenQtyMaxUnit()==castOther.getReplenQtyMaxUnit()) || ( this.getReplenQtyMaxUnit()!=null && castOther.getReplenQtyMaxUnit()!=null && this.getReplenQtyMaxUnit().equals(castOther.getReplenQtyMaxUnit()) ) )
 && ( (this.getReplenQtyMinPrd()==castOther.getReplenQtyMinPrd()) || ( this.getReplenQtyMinPrd()!=null && castOther.getReplenQtyMinPrd()!=null && this.getReplenQtyMinPrd().equals(castOther.getReplenQtyMinPrd()) ) )
 && ( (this.getReplenQtyMaxPrd()==castOther.getReplenQtyMaxPrd()) || ( this.getReplenQtyMaxPrd()!=null && castOther.getReplenQtyMaxPrd()!=null && this.getReplenQtyMaxPrd().equals(castOther.getReplenQtyMaxPrd()) ) )
 && ( (this.getStoreAltFcstFlg()==castOther.getStoreAltFcstFlg()) || ( this.getStoreAltFcstFlg()!=null && castOther.getStoreAltFcstFlg()!=null && this.getStoreAltFcstFlg().equals(castOther.getStoreAltFcstFlg()) ) )
 && ( (this.getArchAltFcstFlg()==castOther.getArchAltFcstFlg()) || ( this.getArchAltFcstFlg()!=null && castOther.getArchAltFcstFlg()!=null && this.getArchAltFcstFlg().equals(castOther.getArchAltFcstFlg()) ) )
 && ( (this.getCalendar()==castOther.getCalendar()) || ( this.getCalendar()!=null && castOther.getCalendar()!=null && this.getCalendar().equals(castOther.getCalendar()) ) )
 && ( (this.getFcstMdlGrp()==castOther.getFcstMdlGrp()) || ( this.getFcstMdlGrp()!=null && castOther.getFcstMdlGrp()!=null && this.getFcstMdlGrp().equals(castOther.getFcstMdlGrp()) ) )
 && ( (this.getStatId()==castOther.getStatId()) || ( this.getStatId()!=null && castOther.getStatId()!=null && this.getStatId().equals(castOther.getStatId()) ) )
 && ( (this.getApsSrcRuleSetNbr()==castOther.getApsSrcRuleSetNbr()) || ( this.getApsSrcRuleSetNbr()!=null && castOther.getApsSrcRuleSetNbr()!=null && this.getApsSrcRuleSetNbr().equals(castOther.getApsSrcRuleSetNbr()) ) )
 && ( (this.getSafetyStkAdj()==castOther.getSafetyStkAdj()) || ( this.getSafetyStkAdj()!=null && castOther.getSafetyStkAdj()!=null && this.getSafetyStkAdj().equals(castOther.getSafetyStkAdj()) ) )
 && ( (this.getFcstTypeId()==castOther.getFcstTypeId()) || ( this.getFcstTypeId()!=null && castOther.getFcstTypeId()!=null && this.getFcstTypeId().equals(castOther.getFcstTypeId()) ) )
 && ( (this.getOrgNbrCust()==castOther.getOrgNbrCust()) || ( this.getOrgNbrCust()!=null && castOther.getOrgNbrCust()!=null && this.getOrgNbrCust().equals(castOther.getOrgNbrCust()) ) )
 && ( (this.getRevLvl()==castOther.getRevLvl()) || ( this.getRevLvl()!=null && castOther.getRevLvl()!=null && this.getRevLvl().equals(castOther.getRevLvl()) ) )
 && ( (this.getOrgNbrMfrRqst()==castOther.getOrgNbrMfrRqst()) || ( this.getOrgNbrMfrRqst()!=null && castOther.getOrgNbrMfrRqst()!=null && this.getOrgNbrMfrRqst().equals(castOther.getOrgNbrMfrRqst()) ) )
 && ( (this.getFcstGrp()==castOther.getFcstGrp()) || ( this.getFcstGrp()!=null && castOther.getFcstGrp()!=null && this.getFcstGrp().equals(castOther.getFcstGrp()) ) )
 && ( (this.getFcItemMastStatId()==castOther.getFcItemMastStatId()) || ( this.getFcItemMastStatId()!=null && castOther.getFcItemMastStatId()!=null && this.getFcItemMastStatId().equals(castOther.getFcItemMastStatId()) ) )
 && ( (this.getFcItemMastDescr()==castOther.getFcItemMastDescr()) || ( this.getFcItemMastDescr()!=null && castOther.getFcItemMastDescr()!=null && this.getFcItemMastDescr().equals(castOther.getFcItemMastDescr()) ) )
 && ( (this.getSafetyStkAllocQty()==castOther.getSafetyStkAllocQty()) || ( this.getSafetyStkAllocQty()!=null && castOther.getSafetyStkAllocQty()!=null && this.getSafetyStkAllocQty().equals(castOther.getSafetyStkAllocQty()) ) )
 && ( (this.getFcstEndDt()==castOther.getFcstEndDt()) || ( this.getFcstEndDt()!=null && castOther.getFcstEndDt()!=null && this.getFcstEndDt().equals(castOther.getFcstEndDt()) ) )
 && ( (this.getUnitCostStkUm()==castOther.getUnitCostStkUm()) || ( this.getUnitCostStkUm()!=null && castOther.getUnitCostStkUm()!=null && this.getUnitCostStkUm().equals(castOther.getUnitCostStkUm()) ) )
 && ( (this.getSafetyStkCalc()==castOther.getSafetyStkCalc()) || ( this.getSafetyStkCalc()!=null && castOther.getSafetyStkCalc()!=null && this.getSafetyStkCalc().equals(castOther.getSafetyStkCalc()) ) )
 && ( (this.getSafetyStkConstrain()==castOther.getSafetyStkConstrain()) || ( this.getSafetyStkConstrain()!=null && castOther.getSafetyStkConstrain()!=null && this.getSafetyStkConstrain().equals(castOther.getSafetyStkConstrain()) ) )
 && ( (this.getCustRefCd()==castOther.getCustRefCd()) || ( this.getCustRefCd()!=null && castOther.getCustRefCd()!=null && this.getCustRefCd().equals(castOther.getCustRefCd()) ) )
 && ( (this.getSafetyStkAvailToSell()==castOther.getSafetyStkAvailToSell()) || ( this.getSafetyStkAvailToSell()!=null && castOther.getSafetyStkAvailToSell()!=null && this.getSafetyStkAvailToSell().equals(castOther.getSafetyStkAvailToSell()) ) )
 && ( (this.getHardAllocFcWithinLeadTm()==castOther.getHardAllocFcWithinLeadTm()) || ( this.getHardAllocFcWithinLeadTm()!=null && castOther.getHardAllocFcWithinLeadTm()!=null && this.getHardAllocFcWithinLeadTm().equals(castOther.getHardAllocFcWithinLeadTm()) ) )
 && ( (this.getFcBuildRateGrpCd()==castOther.getFcBuildRateGrpCd()) || ( this.getFcBuildRateGrpCd()!=null && castOther.getFcBuildRateGrpCd()!=null && this.getFcBuildRateGrpCd().equals(castOther.getFcBuildRateGrpCd()) ) )
 && ( (this.getDescr()==castOther.getDescr()) || ( this.getDescr()!=null && castOther.getDescr()!=null && this.getDescr().equals(castOther.getDescr()) ) )
 && ( (this.getProdLine()==castOther.getProdLine()) || ( this.getProdLine()!=null && castOther.getProdLine()!=null && this.getProdLine().equals(castOther.getProdLine()) ) )
 && ( (this.getStyle()==castOther.getStyle()) || ( this.getStyle()!=null && castOther.getStyle()!=null && this.getStyle().equals(castOther.getStyle()) ) )
 && ( (this.getColor()==castOther.getColor()) || ( this.getColor()!=null && castOther.getColor()!=null && this.getColor().equals(castOther.getColor()) ) )
 && ( (this.getProdSize()==castOther.getProdSize()) || ( this.getProdSize()!=null && castOther.getProdSize()!=null && this.getProdSize().equals(castOther.getProdSize()) ) )
 && ( (this.getCustGrp()==castOther.getCustGrp()) || ( this.getCustGrp()!=null && castOther.getCustGrp()!=null && this.getCustGrp().equals(castOther.getCustGrp()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFcItemMastNbr();
         result = 37 * result + ( getItemNbr() == null ? 0 : this.getItemNbr().hashCode() );
         result = 37 * result + ( getSvcLvl() == null ? 0 : this.getSvcLvl().hashCode() );
         result = 37 * result + this.getTotLeadTime();
         result = 37 * result + ( getSafetyStkMinPrd() == null ? 0 : this.getSafetyStkMinPrd().hashCode() );
         result = 37 * result + ( getSafetyStkMaxPrd() == null ? 0 : this.getSafetyStkMaxPrd().hashCode() );
         result = 37 * result + ( getSafetyStkMinUnit() == null ? 0 : this.getSafetyStkMinUnit().hashCode() );
         result = 37 * result + ( getSafetyStkMaxUnit() == null ? 0 : this.getSafetyStkMaxUnit().hashCode() );
         result = 37 * result + ( getReplenQtyMinUnit() == null ? 0 : this.getReplenQtyMinUnit().hashCode() );
         result = 37 * result + ( getReplenQtyMaxUnit() == null ? 0 : this.getReplenQtyMaxUnit().hashCode() );
         result = 37 * result + ( getReplenQtyMinPrd() == null ? 0 : this.getReplenQtyMinPrd().hashCode() );
         result = 37 * result + ( getReplenQtyMaxPrd() == null ? 0 : this.getReplenQtyMaxPrd().hashCode() );
         result = 37 * result + ( getStoreAltFcstFlg() == null ? 0 : this.getStoreAltFcstFlg().hashCode() );
         result = 37 * result + ( getArchAltFcstFlg() == null ? 0 : this.getArchAltFcstFlg().hashCode() );
         result = 37 * result + ( getCalendar() == null ? 0 : this.getCalendar().hashCode() );
         result = 37 * result + ( getFcstMdlGrp() == null ? 0 : this.getFcstMdlGrp().hashCode() );
         result = 37 * result + ( getStatId() == null ? 0 : this.getStatId().hashCode() );
         result = 37 * result + ( getApsSrcRuleSetNbr() == null ? 0 : this.getApsSrcRuleSetNbr().hashCode() );
         result = 37 * result + ( getSafetyStkAdj() == null ? 0 : this.getSafetyStkAdj().hashCode() );
         result = 37 * result + ( getFcstTypeId() == null ? 0 : this.getFcstTypeId().hashCode() );
         result = 37 * result + ( getOrgNbrCust() == null ? 0 : this.getOrgNbrCust().hashCode() );
         result = 37 * result + ( getRevLvl() == null ? 0 : this.getRevLvl().hashCode() );
         result = 37 * result + ( getOrgNbrMfrRqst() == null ? 0 : this.getOrgNbrMfrRqst().hashCode() );
         result = 37 * result + ( getFcstGrp() == null ? 0 : this.getFcstGrp().hashCode() );
         result = 37 * result + ( getFcItemMastStatId() == null ? 0 : this.getFcItemMastStatId().hashCode() );
         result = 37 * result + ( getFcItemMastDescr() == null ? 0 : this.getFcItemMastDescr().hashCode() );
         result = 37 * result + ( getSafetyStkAllocQty() == null ? 0 : this.getSafetyStkAllocQty().hashCode() );
         result = 37 * result + ( getFcstEndDt() == null ? 0 : this.getFcstEndDt().hashCode() );
         result = 37 * result + ( getUnitCostStkUm() == null ? 0 : this.getUnitCostStkUm().hashCode() );
         result = 37 * result + ( getSafetyStkCalc() == null ? 0 : this.getSafetyStkCalc().hashCode() );
         result = 37 * result + ( getSafetyStkConstrain() == null ? 0 : this.getSafetyStkConstrain().hashCode() );
         result = 37 * result + ( getCustRefCd() == null ? 0 : this.getCustRefCd().hashCode() );
         result = 37 * result + ( getSafetyStkAvailToSell() == null ? 0 : this.getSafetyStkAvailToSell().hashCode() );
         result = 37 * result + ( getHardAllocFcWithinLeadTm() == null ? 0 : this.getHardAllocFcWithinLeadTm().hashCode() );
         result = 37 * result + ( getFcBuildRateGrpCd() == null ? 0 : this.getFcBuildRateGrpCd().hashCode() );
         result = 37 * result + ( getDescr() == null ? 0 : this.getDescr().hashCode() );
         result = 37 * result + ( getProdLine() == null ? 0 : this.getProdLine().hashCode() );
         result = 37 * result + ( getStyle() == null ? 0 : this.getStyle().hashCode() );
         result = 37 * result + ( getColor() == null ? 0 : this.getColor().hashCode() );
         result = 37 * result + ( getProdSize() == null ? 0 : this.getProdSize().hashCode() );
         result = 37 * result + ( getCustGrp() == null ? 0 : this.getCustGrp().hashCode() );
         return result;
   }   


}


