package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FimAttrVw generated by hbm2java
 */
@Entity
@Table(name="FIM_ATTR_VW"
)
public class FimAttrVw  implements java.io.Serializable {


     private FimAttrVwId id;

    public FimAttrVw() {
    }

    public FimAttrVw(FimAttrVwId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fcItemMastNbr", column=@Column(name="FC_ITEM_MAST_NBR") ), 
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR") ), 
        @AttributeOverride(name="svcLvl", column=@Column(name="SVC_LVL") ), 
        @AttributeOverride(name="totLeadTime", column=@Column(name="TOT_LEAD_TIME") ), 
        @AttributeOverride(name="safetyStkMinPrd", column=@Column(name="SAFETY_STK_MIN_PRD") ), 
        @AttributeOverride(name="safetyStkMaxPrd", column=@Column(name="SAFETY_STK_MAX_PRD") ), 
        @AttributeOverride(name="safetyStkMinUnit", column=@Column(name="SAFETY_STK_MIN_UNIT") ), 
        @AttributeOverride(name="safetyStkMaxUnit", column=@Column(name="SAFETY_STK_MAX_UNIT") ), 
        @AttributeOverride(name="replenQtyMinUnit", column=@Column(name="REPLEN_QTY_MIN_UNIT") ), 
        @AttributeOverride(name="replenQtyMaxUnit", column=@Column(name="REPLEN_QTY_MAX_UNIT") ), 
        @AttributeOverride(name="replenQtyMinPrd", column=@Column(name="REPLEN_QTY_MIN_PRD") ), 
        @AttributeOverride(name="replenQtyMaxPrd", column=@Column(name="REPLEN_QTY_MAX_PRD") ), 
        @AttributeOverride(name="storeAltFcstFlg", column=@Column(name="STORE_ALT_FCST_FLG") ), 
        @AttributeOverride(name="archAltFcstFlg", column=@Column(name="ARCH_ALT_FCST_FLG") ), 
        @AttributeOverride(name="calendar", column=@Column(name="CALENDAR") ), 
        @AttributeOverride(name="fcstMdlGrp", column=@Column(name="FCST_MDL_GRP") ), 
        @AttributeOverride(name="statId", column=@Column(name="STAT_ID") ), 
        @AttributeOverride(name="apsSrcRuleSetNbr", column=@Column(name="APS_SRC_RULE_SET_NBR") ), 
        @AttributeOverride(name="safetyStkAdj", column=@Column(name="SAFETY_STK_ADJ") ), 
        @AttributeOverride(name="fcstTypeId", column=@Column(name="FCST_TYPE_ID") ), 
        @AttributeOverride(name="orgNbrCust", column=@Column(name="ORG_NBR_CUST") ), 
        @AttributeOverride(name="revLvl", column=@Column(name="REV_LVL") ), 
        @AttributeOverride(name="orgNbrMfrRqst", column=@Column(name="ORG_NBR_MFR_RQST") ), 
        @AttributeOverride(name="fcstGrp", column=@Column(name="FCST_GRP") ), 
        @AttributeOverride(name="fcItemMastStatId", column=@Column(name="FC_ITEM_MAST_STAT_ID") ), 
        @AttributeOverride(name="fcItemMastDescr", column=@Column(name="FC_ITEM_MAST_DESCR") ), 
        @AttributeOverride(name="safetyStkAllocQty", column=@Column(name="SAFETY_STK_ALLOC_QTY") ), 
        @AttributeOverride(name="fcstEndDt", column=@Column(name="FCST_END_DT") ), 
        @AttributeOverride(name="unitCostStkUm", column=@Column(name="UNIT_COST_STK_UM") ), 
        @AttributeOverride(name="safetyStkCalc", column=@Column(name="SAFETY_STK_CALC") ), 
        @AttributeOverride(name="safetyStkConstrain", column=@Column(name="SAFETY_STK_CONSTRAIN") ), 
        @AttributeOverride(name="custRefCd", column=@Column(name="CUST_REF_CD") ), 
        @AttributeOverride(name="safetyStkAvailToSell", column=@Column(name="SAFETY_STK_AVAIL_TO_SELL") ), 
        @AttributeOverride(name="hardAllocFcWithinLeadTm", column=@Column(name="HARD_ALLOC_FC_WITHIN_LEAD_TM") ), 
        @AttributeOverride(name="fcBuildRateGrpCd", column=@Column(name="FC_BUILD_RATE_GRP_CD") ), 
        @AttributeOverride(name="descr", column=@Column(name="DESCR") ), 
        @AttributeOverride(name="prodLine", column=@Column(name="PROD_LINE") ), 
        @AttributeOverride(name="style", column=@Column(name="STYLE") ), 
        @AttributeOverride(name="color", column=@Column(name="COLOR") ), 
        @AttributeOverride(name="prodSize", column=@Column(name="PROD_SIZE") ), 
        @AttributeOverride(name="custGrp", column=@Column(name="CUST_GRP") ) } )
    public FimAttrVwId getId() {
        return this.id;
    }
    
    public void setId(FimAttrVwId id) {
        this.id = id;
    }




}


