package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FimMsg generated by hbm2java
 */
@Entity
@Table(name="FIM_MSG"
)
public class FimMsg  implements java.io.Serializable {


     private BigDecimal fimMsgNbr;
     private Integer fcItemMastNbr;
     private String msgCd;
     private String msg;
     private Date msgTime;

    public FimMsg() {
    }

	
    public FimMsg(BigDecimal fimMsgNbr) {
        this.fimMsgNbr = fimMsgNbr;
    }
    public FimMsg(BigDecimal fimMsgNbr, Integer fcItemMastNbr, String msgCd, String msg, Date msgTime) {
       this.fimMsgNbr = fimMsgNbr;
       this.fcItemMastNbr = fcItemMastNbr;
       this.msgCd = msgCd;
       this.msg = msg;
       this.msgTime = msgTime;
    }
   
     @Id 

    
    @Column(name="FIM_MSG_NBR", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getFimMsgNbr() {
        return this.fimMsgNbr;
    }
    
    public void setFimMsgNbr(BigDecimal fimMsgNbr) {
        this.fimMsgNbr = fimMsgNbr;
    }

    
    @Column(name="FC_ITEM_MAST_NBR", precision=9, scale=0)
    public Integer getFcItemMastNbr() {
        return this.fcItemMastNbr;
    }
    
    public void setFcItemMastNbr(Integer fcItemMastNbr) {
        this.fcItemMastNbr = fcItemMastNbr;
    }

    
    @Column(name="MSG_CD", length=20)
    public String getMsgCd() {
        return this.msgCd;
    }
    
    public void setMsgCd(String msgCd) {
        this.msgCd = msgCd;
    }

    
    @Column(name="MSG", length=2000)
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MSG_TIME", length=11)
    public Date getMsgTime() {
        return this.msgTime;
    }
    
    public void setMsgTime(Date msgTime) {
        this.msgTime = msgTime;
    }




}


