package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IcBom generated by hbm2java
 */
@Entity
@Table(name="IC_BOM"
)
public class IcBom  implements java.io.Serializable {


     private IcBomId id;
     private PoMfrMast poMfrMast;
     private IcItemMast icItemMastByItemNbrParent;
     private IcItemMast icItemMastByItemNbr;

    public IcBom() {
    }

	
    public IcBom(IcBomId id, IcItemMast icItemMastByItemNbr) {
        this.id = id;
        this.icItemMastByItemNbr = icItemMastByItemNbr;
    }
    public IcBom(IcBomId id, PoMfrMast poMfrMast, IcItemMast icItemMastByItemNbrParent, IcItemMast icItemMastByItemNbr) {
       this.id = id;
       this.poMfrMast = poMfrMast;
       this.icItemMastByItemNbrParent = icItemMastByItemNbrParent;
       this.icItemMastByItemNbr = icItemMastByItemNbr;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="itemNbrParent", column=@Column(name="ITEM_NBR_PARENT", precision=9, scale=0) ), 
        @AttributeOverride(name="childQty", column=@Column(name="CHILD_QTY", nullable=false, precision=13, scale=6) ), 
        @AttributeOverride(name="childUm", column=@Column(name="CHILD_UM", nullable=false, length=3) ), 
        @AttributeOverride(name="utUserNbr", column=@Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="lastModDt", column=@Column(name="LAST_MOD_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="mixMfrLotFlg", column=@Column(name="MIX_MFR_LOT_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="printBagLblFlg", column=@Column(name="PRINT_BAG_LBL_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="revLvl", column=@Column(name="REV_LVL", length=5) ), 
        @AttributeOverride(name="orgNbrMfrRqst", column=@Column(name="ORG_NBR_MFR_RQST", precision=9, scale=0) ), 
        @AttributeOverride(name="mandatoryItemFlg", column=@Column(name="MANDATORY_ITEM_FLG", nullable=false, length=1) ) } )
    public IcBomId getId() {
        return this.id;
    }
    
    public void setId(IcBomId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORG_NBR_MFR_RQST", insertable=false, updatable=false)
    public PoMfrMast getPoMfrMast() {
        return this.poMfrMast;
    }
    
    public void setPoMfrMast(PoMfrMast poMfrMast) {
        this.poMfrMast = poMfrMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR_PARENT", insertable=false, updatable=false)
    public IcItemMast getIcItemMastByItemNbrParent() {
        return this.icItemMastByItemNbrParent;
    }
    
    public void setIcItemMastByItemNbrParent(IcItemMast icItemMastByItemNbrParent) {
        this.icItemMastByItemNbrParent = icItemMastByItemNbrParent;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR", nullable=false, insertable=false, updatable=false)
    public IcItemMast getIcItemMastByItemNbr() {
        return this.icItemMastByItemNbr;
    }
    
    public void setIcItemMastByItemNbr(IcItemMast icItemMastByItemNbr) {
        this.icItemMastByItemNbr = icItemMastByItemNbr;
    }




}


