package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IcBomCert generated by hbm2java
 */
@Entity
@Table(name="IC_BOM_CERT"
)
public class IcBomCert  implements java.io.Serializable {


     private IcBomCertId id;
     private IcCertCd icCertCd;
     private IcItemMast icItemMastByItemNbrParent;
     private IcItemMast icItemMastByItemNbr;
     private int utUserNbr;
     private Date lastModDt;

    public IcBomCert() {
    }

   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="itemNbrParent", column=@Column(name="ITEM_NBR_PARENT", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="certCd", column=@Column(name="CERT_CD", nullable=false, length=8) ) } )
    public IcBomCertId getId() {
        return this.id;
    }
    
    public void setId(IcBomCertId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CERT_CD", nullable=false, insertable=false, updatable=false)
    public IcCertCd getIcCertCd() {
        return this.icCertCd;
    }
    
    public void setIcCertCd(IcCertCd icCertCd) {
        this.icCertCd = icCertCd;
    }

//@ManyToOne(fetch=FetchType.LAZY)
//    @JoinColumn(name="ITEM_NBR_PARENT", nullable=false, insertable=false, updatable=false)
//    public IcItemMast getIcItemMastByItemNbrParent() {
//        return this.icItemMastByItemNbrParent;
//    }
//    
//    public void setIcItemMastByItemNbrParent(IcItemMast icItemMastByItemNbrParent) {
//        this.icItemMastByItemNbrParent = icItemMastByItemNbrParent;
//    }
//
//@ManyToOne(fetch=FetchType.LAZY)
//    @JoinColumn(name="ITEM_NBR", nullable=false, insertable=false, updatable=false)
//    public IcItemMast getIcItemMastByItemNbr() {
//        return this.icItemMastByItemNbr;
//    }
//    
//    public void setIcItemMastByItemNbr(IcItemMast icItemMastByItemNbr) {
//        this.icItemMastByItemNbr = icItemMastByItemNbr;
//    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }




}


