package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IcItemCost generated by hbm2java
 */
@Entity
@Table(name="IC_ITEM_COST"
)
public class IcItemCost  implements java.io.Serializable {


     private IcItemCostId id;
     private IcItemMast icItemMast;
     private BigDecimal unitCost;
     private Date costCalcDt;
     private int utUserNbr;
     private Date lastModDt;

    public IcItemCost() {
    }

	
    public IcItemCost(IcItemCostId id, IcItemMast icItemMast, BigDecimal unitCost, int utUserNbr, Date lastModDt) {
        this.id = id;
        this.icItemMast = icItemMast;
        this.unitCost = unitCost;
        this.utUserNbr = utUserNbr;
        this.lastModDt = lastModDt;
    }
    public IcItemCost(IcItemCostId id, IcItemMast icItemMast, BigDecimal unitCost, Date costCalcDt, int utUserNbr, Date lastModDt) {
       this.id = id;
       this.icItemMast = icItemMast;
       this.unitCost = unitCost;
       this.costCalcDt = costCalcDt;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="costTypeCd", column=@Column(name="COST_TYPE_CD", nullable=false, length=16) ) } )
    public IcItemCostId getId() {
        return this.id;
    }
    
    public void setId(IcItemCostId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR", nullable=false, insertable=false, updatable=false)
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }

    
    @Column(name="UNIT_COST", nullable=false, precision=17, scale=6)
    public BigDecimal getUnitCost() {
        return this.unitCost;
    }
    
    public void setUnitCost(BigDecimal unitCost) {
        this.unitCost = unitCost;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="COST_CALC_DT", length=7)
    public Date getCostCalcDt() {
        return this.costCalcDt;
    }
    
    public void setCostCalcDt(Date costCalcDt) {
        this.costCalcDt = costCalcDt;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }




}


