package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IcItemLocBox generated by hbm2java
 */
@Entity
@Table(name="IC_ITEM_LOC_BOX"
)
public class IcItemLocBox  implements java.io.Serializable {


     private String boxCd;
     private IcItemLoc icItemLoc;
     private BigDecimal boxQty;
     private String boxStatId;
     private String mfrSerialCd;
     private String serialCd;
     private Date locConfirmRqstDt;
     private Date locConfirmActDt;
     private Integer utUserNbrLocConfirm;
     private Date qtyConfirmRqstDt;
     private Date qtyConfirmActDt;
     private Integer utUserNbrQtyConfirm;
     private Boolean qtyConfirmRqstPrty;
     private Set<WhPickDtlWoRqst> whPickDtlWoRqsts = new HashSet<WhPickDtlWoRqst>(0);
     private Set<WhPickDtlCopRqst> whPickDtlCopRqsts = new HashSet<WhPickDtlCopRqst>(0);
     private Set<WhPickDtlTransRqst> whPickDtlTransRqsts = new HashSet<WhPickDtlTransRqst>(0);
     private Set<WhFacilityTransOnhand> whFacilityTransOnhands = new HashSet<WhFacilityTransOnhand>(0);

    public IcItemLocBox() {
    }

	
    public IcItemLocBox(String boxCd, IcItemLoc icItemLoc, String boxStatId) {
        this.boxCd = boxCd;
        this.icItemLoc = icItemLoc;
        this.boxStatId = boxStatId;
    }
    public IcItemLocBox(String boxCd, IcItemLoc icItemLoc, BigDecimal boxQty, String boxStatId, String mfrSerialCd, String serialCd, Date locConfirmRqstDt, Date locConfirmActDt, Integer utUserNbrLocConfirm, Date qtyConfirmRqstDt, Date qtyConfirmActDt, Integer utUserNbrQtyConfirm, Boolean qtyConfirmRqstPrty, Set<WhPickDtlWoRqst> whPickDtlWoRqsts, Set<WhPickDtlCopRqst> whPickDtlCopRqsts, Set<WhPickDtlTransRqst> whPickDtlTransRqsts, Set<WhFacilityTransOnhand> whFacilityTransOnhands) {
       this.boxCd = boxCd;
       this.icItemLoc = icItemLoc;
       this.boxQty = boxQty;
       this.boxStatId = boxStatId;
       this.mfrSerialCd = mfrSerialCd;
       this.serialCd = serialCd;
       this.locConfirmRqstDt = locConfirmRqstDt;
       this.locConfirmActDt = locConfirmActDt;
       this.utUserNbrLocConfirm = utUserNbrLocConfirm;
       this.qtyConfirmRqstDt = qtyConfirmRqstDt;
       this.qtyConfirmActDt = qtyConfirmActDt;
       this.utUserNbrQtyConfirm = utUserNbrQtyConfirm;
       this.qtyConfirmRqstPrty = qtyConfirmRqstPrty;
       this.whPickDtlWoRqsts = whPickDtlWoRqsts;
       this.whPickDtlCopRqsts = whPickDtlCopRqsts;
       this.whPickDtlTransRqsts = whPickDtlTransRqsts;
       this.whFacilityTransOnhands = whFacilityTransOnhands;
    }
   
     @Id 

    
    @Column(name="BOX_CD", unique=true, nullable=false, length=20)
    public String getBoxCd() {
        return this.boxCd;
    }
    
    public void setBoxCd(String boxCd) {
        this.boxCd = boxCd;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IC_ITEM_LOC_NBR", nullable=false)
    public IcItemLoc getIcItemLoc() {
        return this.icItemLoc;
    }
    
    public void setIcItemLoc(IcItemLoc icItemLoc) {
        this.icItemLoc = icItemLoc;
    }

    
    @Column(name="BOX_QTY", precision=12, scale=5)
    public BigDecimal getBoxQty() {
        return this.boxQty;
    }
    
    public void setBoxQty(BigDecimal boxQty) {
        this.boxQty = boxQty;
    }

    
    @Column(name="BOX_STAT_ID", nullable=false, length=3)
    public String getBoxStatId() {
        return this.boxStatId;
    }
    
    public void setBoxStatId(String boxStatId) {
        this.boxStatId = boxStatId;
    }

    
    @Column(name="MFR_SERIAL_CD", length=20)
    public String getMfrSerialCd() {
        return this.mfrSerialCd;
    }
    
    public void setMfrSerialCd(String mfrSerialCd) {
        this.mfrSerialCd = mfrSerialCd;
    }

    
    @Column(name="SERIAL_CD", length=20)
    public String getSerialCd() {
        return this.serialCd;
    }
    
    public void setSerialCd(String serialCd) {
        this.serialCd = serialCd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LOC_CONFIRM_RQST_DT", length=7)
    public Date getLocConfirmRqstDt() {
        return this.locConfirmRqstDt;
    }
    
    public void setLocConfirmRqstDt(Date locConfirmRqstDt) {
        this.locConfirmRqstDt = locConfirmRqstDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LOC_CONFIRM_ACT_DT", length=7)
    public Date getLocConfirmActDt() {
        return this.locConfirmActDt;
    }
    
    public void setLocConfirmActDt(Date locConfirmActDt) {
        this.locConfirmActDt = locConfirmActDt;
    }

    
    @Column(name="UT_USER_NBR_LOC_CONFIRM", precision=9, scale=0)
    public Integer getUtUserNbrLocConfirm() {
        return this.utUserNbrLocConfirm;
    }
    
    public void setUtUserNbrLocConfirm(Integer utUserNbrLocConfirm) {
        this.utUserNbrLocConfirm = utUserNbrLocConfirm;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="QTY_CONFIRM_RQST_DT", length=7)
    public Date getQtyConfirmRqstDt() {
        return this.qtyConfirmRqstDt;
    }
    
    public void setQtyConfirmRqstDt(Date qtyConfirmRqstDt) {
        this.qtyConfirmRqstDt = qtyConfirmRqstDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="QTY_CONFIRM_ACT_DT", length=7)
    public Date getQtyConfirmActDt() {
        return this.qtyConfirmActDt;
    }
    
    public void setQtyConfirmActDt(Date qtyConfirmActDt) {
        this.qtyConfirmActDt = qtyConfirmActDt;
    }

    
    @Column(name="UT_USER_NBR_QTY_CONFIRM", precision=9, scale=0)
    public Integer getUtUserNbrQtyConfirm() {
        return this.utUserNbrQtyConfirm;
    }
    
    public void setUtUserNbrQtyConfirm(Integer utUserNbrQtyConfirm) {
        this.utUserNbrQtyConfirm = utUserNbrQtyConfirm;
    }

    
    @Column(name="QTY_CONFIRM_RQST_PRTY", precision=1, scale=0)
    public Boolean getQtyConfirmRqstPrty() {
        return this.qtyConfirmRqstPrty;
    }
    
    public void setQtyConfirmRqstPrty(Boolean qtyConfirmRqstPrty) {
        this.qtyConfirmRqstPrty = qtyConfirmRqstPrty;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemLocBox")
    public Set<WhPickDtlWoRqst> getWhPickDtlWoRqsts() {
        return this.whPickDtlWoRqsts;
    }
    
    public void setWhPickDtlWoRqsts(Set<WhPickDtlWoRqst> whPickDtlWoRqsts) {
        this.whPickDtlWoRqsts = whPickDtlWoRqsts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemLocBox")
    public Set<WhPickDtlCopRqst> getWhPickDtlCopRqsts() {
        return this.whPickDtlCopRqsts;
    }
    
    public void setWhPickDtlCopRqsts(Set<WhPickDtlCopRqst> whPickDtlCopRqsts) {
        this.whPickDtlCopRqsts = whPickDtlCopRqsts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemLocBox")
    public Set<WhPickDtlTransRqst> getWhPickDtlTransRqsts() {
        return this.whPickDtlTransRqsts;
    }
    
    public void setWhPickDtlTransRqsts(Set<WhPickDtlTransRqst> whPickDtlTransRqsts) {
        this.whPickDtlTransRqsts = whPickDtlTransRqsts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemLocBox")
    public Set<WhFacilityTransOnhand> getWhFacilityTransOnhands() {
        return this.whFacilityTransOnhands;
    }
    
    public void setWhFacilityTransOnhands(Set<WhFacilityTransOnhand> whFacilityTransOnhands) {
        this.whFacilityTransOnhands = whFacilityTransOnhands;
    }




}


