package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IcItemLoc generated by hbm2java
 */
@Entity
@Table(name="IC_ITEM_LOC"
)
public class IcItemLoc  implements java.io.Serializable {


     private int icItemLocNbr;
     private ApsSplySubPool apsSplySubPool;
     private IcLotMast icLotMast;
     private IcBin icBin;
     private Date availDt;
     private int utUserNbr;
     private Date lastModDt;
     private String boxFixFlg;
     private Set<IcItemLocBox> icItemLocBoxes = new HashSet<IcItemLocBox>(0);
     private Set<WhPickDtlCopRqst> whPickDtlCopRqsts = new HashSet<WhPickDtlCopRqst>(0);
     private Set<WhPickDtlWoRqst> whPickDtlWoRqsts = new HashSet<WhPickDtlWoRqst>(0);
     private Set<WhPickDtlTransRqst> whPickDtlTransRqsts = new HashSet<WhPickDtlTransRqst>(0);

    public IcItemLoc() {
    }

	
    public IcItemLoc(int icItemLocNbr, ApsSplySubPool apsSplySubPool, IcLotMast icLotMast, IcBin icBin, int utUserNbr, Date lastModDt, String boxFixFlg) {
        this.icItemLocNbr = icItemLocNbr;
        this.apsSplySubPool = apsSplySubPool;
        this.icLotMast = icLotMast;
        this.icBin = icBin;
        this.utUserNbr = utUserNbr;
        this.lastModDt = lastModDt;
        this.boxFixFlg = boxFixFlg;
    }
    public IcItemLoc(int icItemLocNbr, ApsSplySubPool apsSplySubPool, IcLotMast icLotMast, IcBin icBin, Date availDt, int utUserNbr, Date lastModDt, String boxFixFlg, Set<IcItemLocBox> icItemLocBoxes, Set<WhPickDtlCopRqst> whPickDtlCopRqsts, Set<WhPickDtlWoRqst> whPickDtlWoRqsts, Set<WhPickDtlTransRqst> whPickDtlTransRqsts) {
       this.icItemLocNbr = icItemLocNbr;
       this.apsSplySubPool = apsSplySubPool;
       this.icLotMast = icLotMast;
       this.icBin = icBin;
       this.availDt = availDt;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
       this.boxFixFlg = boxFixFlg;
       this.icItemLocBoxes = icItemLocBoxes;
       this.whPickDtlCopRqsts = whPickDtlCopRqsts;
       this.whPickDtlWoRqsts = whPickDtlWoRqsts;
       this.whPickDtlTransRqsts = whPickDtlTransRqsts;
    }
   
     @Id 

    
    @Column(name="IC_ITEM_LOC_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getIcItemLocNbr() {
        return this.icItemLocNbr;
    }
    
    public void setIcItemLocNbr(int icItemLocNbr) {
        this.icItemLocNbr = icItemLocNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APS_SPLY_SUB_POOL_NBR", nullable=false)
    public ApsSplySubPool getApsSplySubPool() {
        return this.apsSplySubPool;
    }
    
    public void setApsSplySubPool(ApsSplySubPool apsSplySubPool) {
        this.apsSplySubPool = apsSplySubPool;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LOT_NBR", nullable=false)
    public IcLotMast getIcLotMast() {
        return this.icLotMast;
    }
    
    public void setIcLotMast(IcLotMast icLotMast) {
        this.icLotMast = icLotMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIN_NBR", nullable=false)
    public IcBin getIcBin() {
        return this.icBin;
    }
    
    public void setIcBin(IcBin icBin) {
        this.icBin = icBin;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="AVAIL_DT", length=7)
    public Date getAvailDt() {
        return this.availDt;
    }
    
    public void setAvailDt(Date availDt) {
        this.availDt = availDt;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }

    
    @Column(name="BOX_FIX_FLG", nullable=false, length=1)
    public String getBoxFixFlg() {
        return this.boxFixFlg;
    }
    
    public void setBoxFixFlg(String boxFixFlg) {
        this.boxFixFlg = boxFixFlg;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemLoc")
    public Set<IcItemLocBox> getIcItemLocBoxes() {
        return this.icItemLocBoxes;
    }
    
    public void setIcItemLocBoxes(Set<IcItemLocBox> icItemLocBoxes) {
        this.icItemLocBoxes = icItemLocBoxes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemLoc")
    public Set<WhPickDtlCopRqst> getWhPickDtlCopRqsts() {
        return this.whPickDtlCopRqsts;
    }
    
    public void setWhPickDtlCopRqsts(Set<WhPickDtlCopRqst> whPickDtlCopRqsts) {
        this.whPickDtlCopRqsts = whPickDtlCopRqsts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemLoc")
    public Set<WhPickDtlWoRqst> getWhPickDtlWoRqsts() {
        return this.whPickDtlWoRqsts;
    }
    
    public void setWhPickDtlWoRqsts(Set<WhPickDtlWoRqst> whPickDtlWoRqsts) {
        this.whPickDtlWoRqsts = whPickDtlWoRqsts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemLoc")
    public Set<WhPickDtlTransRqst> getWhPickDtlTransRqsts() {
        return this.whPickDtlTransRqsts;
    }
    
    public void setWhPickDtlTransRqsts(Set<WhPickDtlTransRqst> whPickDtlTransRqsts) {
        this.whPickDtlTransRqsts = whPickDtlTransRqsts;
    }




}


