package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IcItemCustSubst generated by hbm2java
 */
@Entity
@Table(name="IC_ITEM_CUST_SUBST"
)
public class IcItemCustSubst  implements java.io.Serializable {


     private IcItemCustSubstId id;
     private OeCustMast oeCustMast;
     private int utUserNbr;
     private Date lastModDt;

    public IcItemCustSubst() {
    }

     @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="orgNbrCust", column=@Column(name="ORG_NBR_CUST", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="itemNbrSubst", column=@Column(name="ITEM_NBR_SUBST", nullable=false, precision=9, scale=0) ) } )
    public IcItemCustSubstId getId() {
        return this.id;
    }
    
    public void setId(IcItemCustSubstId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORG_NBR_CUST", nullable=false, insertable=false, updatable=false)
    public OeCustMast getOeCustMast() {
        return this.oeCustMast;
    }
    
    public void setOeCustMast(OeCustMast oeCustMast) {
        this.oeCustMast = oeCustMast;
    }

//@ManyToOne(fetch=FetchType.LAZY)
//    @JoinColumn(name="ITEM_NBR_SUBST", nullable=false, insertable=false, updatable=false)
//    public IcItemMast getIcItemMastByItemNbrSubst() {
//        return this.icItemMastByItemNbrSubst;
//    }
//    
//    public void setIcItemMastByItemNbrSubst(IcItemMast icItemMastByItemNbrSubst) {
//        this.icItemMastByItemNbrSubst = icItemMastByItemNbrSubst;
//    }
//
//@ManyToOne(fetch=FetchType.LAZY)
//    @JoinColumn(name="ITEM_NBR", nullable=false, insertable=false, updatable=false)
//    public IcItemMast getIcItemMastByItemNbr() {
//        return this.icItemMastByItemNbr;
//    }
//    
//    public void setIcItemMastByItemNbr(IcItemMast icItemMastByItemNbr) {
//        this.icItemMastByItemNbr = icItemMastByItemNbr;
//    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }




}


