package com.pacificdataservices.diamond.models;
// Generated Mar 21, 2019 5:50:00 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IcItemMast generated by hbm2java
 */
@Entity
@Table(name="IC_ITEM_MAST"
)
public class IcItemMast  implements java.io.Serializable {


     private int itemNbr;
     private IcItemMast icItemMast;
     private String itemCd;
     private String itemDescr;
     private String stkUm;
     private String sellUm;
     private BigDecimal stdCost;
     private BigDecimal listPrice;
     private String upcCd;
     private String ean;
     private Integer qtyPerBox;
     private Integer boxPerCtn;
     private Integer slsQtyMin;
     private Integer slsQtyIncr;
     private Integer replenQtyMin;
     private Integer replenQtyIncr;
     private int icCategoryNbr;
     private String nonStkFlg;
     private String serNbrReqrFlg;
     private String mfrSerNbrReqrFlg;
     private String inspectReqrFlg;
     private String mfrLotCtrlFlg;
     private String kitFlg;
     private String priceChgFlg;
     private int utUserNbr;
     private Date lastModDt;
     private String sellFlg;
     private String harmonizedCd;
     private Short planBucketSz;
     private String currCd;
     private String reqrMfrFlg;
     private Integer shelfLifeDy;
     private Integer leadTmDy;
     private Integer indivNbrBuyer;
     private String statId;
     private String pickScanId;
     private Date introDt;
     private String splitAtBinFlg;
     private String labelNmBox;
     private String icRecvRuleCd;
     private String cycleCntRuleCd;
     private String fifoDtId;
     private String replenTypeId;
     private Integer itemNbrSupersede;
     private Integer schedQtyOptimal;
     private Integer imgImageSetHdrNbr;
     private BigDecimal itemWght;
     private BigDecimal ctnVolume;
     private Set<WoDtl> woDtls = new HashSet<WoDtl>(0);
     private Set<IcUmCnvtItem> icUmCnvtItems = new HashSet<IcUmCnvtItem>(0);
//     private IcKitMast icKitMast;
     private Set<OeOrdDtl> oeOrdDtlsForItemNbrRqst = new HashSet<OeOrdDtl>(0);
     private Set<ArRmaRcpt> arRmaRcpts = new HashSet<ArRmaRcpt>(0);
     private Set<IcItemPriceMatrix> icItemPriceMatrixes = new HashSet<IcItemPriceMatrix>(0);
     private Set<IcItemRevLvl> icItemRevLvls = new HashSet<IcItemRevLvl>(0);
     private Set<IcLotMast> icLotMasts = new HashSet<IcLotMast>(0);
     private Set<IcItemMast> icItemMasts = new HashSet<IcItemMast>(0);
     private Set<IcItemVndCostMatrix> icItemVndCostMatrixes = new HashSet<IcItemVndCostMatrix>(0);
     private Set<OeOrdDtl> oeOrdDtlsForItemNbrOrd = new HashSet<OeOrdDtl>(0);
     private Set<PoLineMultipleCert> poLineMultipleCerts = new HashSet<PoLineMultipleCert>(0);
     private Set<IcItemMastNomen> icItemMastNomens = new HashSet<IcItemMastNomen>(0);
     //private IcItemNarr icItemNarr;
     private Set<OeContractItem> oeContractItemsForItemNbr = new HashSet<OeContractItem>(0);
     //private IcItemMastUpdQueue icItemMastUpdQueue;
     private Set<OeCustMfr> oeCustMfrs = new HashSet<OeCustMfr>(0);
//     private IcItemMfgPath icItemMfgPath;
     private Set<IcItemOperationYield> icItemOperationYields = new HashSet<IcItemOperationYield>(0);
     private Set<WoHdr> woHdrs = new HashSet<WoHdr>(0);
     private Set<IcItemMastCert> icItemMastCerts = new HashSet<IcItemMastCert>(0);
     private Set<IcMultipleCert> icMultipleCerts = new HashSet<IcMultipleCert>(0);
     private Set<QaMfrApprv> qaMfrApprvs = new HashSet<QaMfrApprv>(0);
     private Set<IcItemMastRel> icItemMastRelsForItemNbr = new HashSet<IcItemMastRel>(0);
     private Set<PoUnplannedRcpt> poUnplannedRcpts = new HashSet<PoUnplannedRcpt>(0);
     private Set<VqQteDtl> vqQteDtls = new HashSet<VqQteDtl>(0);
     private Set<SqQteDtl> sqQteDtls = new HashSet<SqQteDtl>(0);
    // private Set<IcVndOnhand> icVndOnhands = new HashSet<IcVndOnhand>(0);
    // private Set<IcItemCustSubst> icItemCustSubsts = new HashSet<IcItemCustSubst>(0);
     private Set<IcItemRestrictCust> icItemRestrictCusts = new HashSet<IcItemRestrictCust>(0);
     private Set<OeContractItem> oeContractItemsForItemNbrSupersede = new HashSet<OeContractItem>(0);
     private Set<PoLineHdr> poLineHdrs = new HashSet<PoLineHdr>(0);
     private Set<PosDtl> posDtls = new HashSet<PosDtl>(0);
     private Set<IcItemMastRel> icItemMastRelsForItemNbrRel = new HashSet<IcItemMastRel>(0);
     private Set<ArRmaDtl> arRmaDtls = new HashSet<ArRmaDtl>(0);
     //private Set<FcItemMast> fcItemMasts = new HashSet<FcItemMast>(0);
     private Set<IcItemAttr> icItemAttrs = new HashSet<IcItemAttr>(0);
     private Set<VqQteMultipleCert> vqQteMultipleCerts = new HashSet<VqQteMultipleCert>(0);
     private Set<ArInvDtl> arInvDtls = new HashSet<ArInvDtl>(0);
  //   private Set<IcBomCert> icBomCerts = new HashSet<IcBomCert>(0);
     private Set<IcItemCost> icItemCosts = new HashSet<IcItemCost>(0);

    public IcItemMast() {
    }
    
    
    
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ic_item_mast_generator")
    @SequenceGenerator(name="ic_item_mast_generator", sequenceName = "item_nbr_seq", allocationSize=50)
    @Column(name="ITEM_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getItemNbr() {
        return this.itemNbr;
    }
    
    public void setItemNbr(int itemNbr) {
        this.itemNbr = itemNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR_PRIMARY")
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }

    
    @Column(name="ITEM_CD", unique=true, nullable=false, length=50)
    public String getItemCd() {
        return this.itemCd;
    }
    
    public void setItemCd(String itemCd) {
        this.itemCd = itemCd;
    }

    
    @Column(name="ITEM_DESCR", nullable=false, length=50)
    public String getItemDescr() {
        return this.itemDescr;
    }
    
    public void setItemDescr(String itemDescr) {
        this.itemDescr = itemDescr;
    }

    
    @Column(name="STK_UM", nullable=false, length=3)
    public String getStkUm() {
        return this.stkUm;
    }
    
    public void setStkUm(String stkUm) {
        this.stkUm = stkUm;
    }

    
    @Column(name="SELL_UM", length=3)
    public String getSellUm() {
        return this.sellUm;
    }
    
    public void setSellUm(String sellUm) {
        this.sellUm = sellUm;
    }

    
    @Column(name="STD_COST", precision=17, scale=6)
    public BigDecimal getStdCost() {
        return this.stdCost;
    }
    
    public void setStdCost(BigDecimal stdCost) {
        this.stdCost = stdCost;
    }

    
    @Column(name="LIST_PRICE", precision=17, scale=6)
    public BigDecimal getListPrice() {
        return this.listPrice;
    }
    
    public void setListPrice(BigDecimal listPrice) {
        this.listPrice = listPrice;
    }

    
    @Column(name="UPC_CD", length=20)
    public String getUpcCd() {
        return this.upcCd;
    }
    
    public void setUpcCd(String upcCd) {
        this.upcCd = upcCd;
    }

    
    @Column(name="EAN", length=50)
    public String getEan() {
        return this.ean;
    }
    
    public void setEan(String ean) {
        this.ean = ean;
    }

    
    @Column(name="QTY_PER_BOX", precision=7, scale=0)
    public Integer getQtyPerBox() {
        return this.qtyPerBox;
    }
    
    public void setQtyPerBox(Integer qtyPerBox) {
        this.qtyPerBox = qtyPerBox;
    }

    
    @Column(name="BOX_PER_CTN", precision=7, scale=0)
    public Integer getBoxPerCtn() {
        return this.boxPerCtn;
    }
    
    public void setBoxPerCtn(Integer boxPerCtn) {
        this.boxPerCtn = boxPerCtn;
    }

    
    @Column(name="SLS_QTY_MIN", precision=7, scale=0)
    public Integer getSlsQtyMin() {
        return this.slsQtyMin;
    }
    
    public void setSlsQtyMin(Integer slsQtyMin) {
        this.slsQtyMin = slsQtyMin;
    }

    
    @Column(name="SLS_QTY_INCR", precision=7, scale=0)
    public Integer getSlsQtyIncr() {
        return this.slsQtyIncr;
    }
    
    public void setSlsQtyIncr(Integer slsQtyIncr) {
        this.slsQtyIncr = slsQtyIncr;
    }

    
    @Column(name="REPLEN_QTY_MIN", precision=7, scale=0)
    public Integer getReplenQtyMin() {
        return this.replenQtyMin;
    }
    
    public void setReplenQtyMin(Integer replenQtyMin) {
        this.replenQtyMin = replenQtyMin;
    }

    
    @Column(name="REPLEN_QTY_INCR", precision=7, scale=0)
    public Integer getReplenQtyIncr() {
        return this.replenQtyIncr;
    }
    
    public void setReplenQtyIncr(Integer replenQtyIncr) {
        this.replenQtyIncr = replenQtyIncr;
    }

    
    @Column(name="IC_CATEGORY_NBR", nullable=false, precision=9, scale=0)
    public int getIcCategoryNbr() {
        return this.icCategoryNbr;
    }
    
    public void setIcCategoryNbr(int icCategoryNbr) {
        this.icCategoryNbr = icCategoryNbr;
    }

    
    @Column(name="NON_STK_FLG", nullable=false, length=1)
    public String getNonStkFlg() {
        return this.nonStkFlg;
    }
    
    public void setNonStkFlg(String nonStkFlg) {
        this.nonStkFlg = nonStkFlg;
    }

    
    @Column(name="SER_NBR_REQR_FLG", nullable=false, length=1)
    public String getSerNbrReqrFlg() {
        return this.serNbrReqrFlg;
    }
    
    public void setSerNbrReqrFlg(String serNbrReqrFlg) {
        this.serNbrReqrFlg = serNbrReqrFlg;
    }

    
    @Column(name="MFR_SER_NBR_REQR_FLG", nullable=false, length=1)
    public String getMfrSerNbrReqrFlg() {
        return this.mfrSerNbrReqrFlg;
    }
    
    public void setMfrSerNbrReqrFlg(String mfrSerNbrReqrFlg) {
        this.mfrSerNbrReqrFlg = mfrSerNbrReqrFlg;
    }

    
    @Column(name="INSPECT_REQR_FLG", nullable=false, length=1)
    public String getInspectReqrFlg() {
        return this.inspectReqrFlg;
    }
    
    public void setInspectReqrFlg(String inspectReqrFlg) {
        this.inspectReqrFlg = inspectReqrFlg;
    }

    
    @Column(name="MFR_LOT_CTRL_FLG", nullable=false, length=1)
    public String getMfrLotCtrlFlg() {
        return this.mfrLotCtrlFlg;
    }
    
    public void setMfrLotCtrlFlg(String mfrLotCtrlFlg) {
        this.mfrLotCtrlFlg = mfrLotCtrlFlg;
    }

    
    @Column(name="KIT_FLG", nullable=false, length=1)
    public String getKitFlg() {
        return this.kitFlg;
    }
    
    public void setKitFlg(String kitFlg) {
        this.kitFlg = kitFlg;
    }

    
    @Column(name="PRICE_CHG_FLG", nullable=false, length=1)
    public String getPriceChgFlg() {
        return this.priceChgFlg;
    }
    
    public void setPriceChgFlg(String priceChgFlg) {
        this.priceChgFlg = priceChgFlg;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }

    
    @Column(name="SELL_FLG", length=1)
    public String getSellFlg() {
        return this.sellFlg;
    }
    
    public void setSellFlg(String sellFlg) {
        this.sellFlg = sellFlg;
    }

    
    @Column(name="HARMONIZED_CD", length=15)
    public String getHarmonizedCd() {
        return this.harmonizedCd;
    }
    
    public void setHarmonizedCd(String harmonizedCd) {
        this.harmonizedCd = harmonizedCd;
    }

    
    @Column(name="PLAN_BUCKET_SZ", precision=3, scale=0)
    public Short getPlanBucketSz() {
        return this.planBucketSz;
    }
    
    public void setPlanBucketSz(Short planBucketSz) {
        this.planBucketSz = planBucketSz;
    }

    
    @Column(name="CURR_CD", length=3)
    public String getCurrCd() {
        return this.currCd;
    }
    
    public void setCurrCd(String currCd) {
        this.currCd = currCd;
    }

    
    @Column(name="REQR_MFR_FLG", nullable=false, length=1)
    public String getReqrMfrFlg() {
        return this.reqrMfrFlg;
    }
    
    public void setReqrMfrFlg(String reqrMfrFlg) {
        this.reqrMfrFlg = reqrMfrFlg;
    }

    
    @Column(name="SHELF_LIFE_DY", precision=5, scale=0)
    public Integer getShelfLifeDy() {
        return this.shelfLifeDy;
    }
    
    public void setShelfLifeDy(Integer shelfLifeDy) {
        this.shelfLifeDy = shelfLifeDy;
    }

    
    @Column(name="LEAD_TM_DY", precision=5, scale=0)
    public Integer getLeadTmDy() {
        return this.leadTmDy;
    }
    
    public void setLeadTmDy(Integer leadTmDy) {
        this.leadTmDy = leadTmDy;
    }

    
    @Column(name="INDIV_NBR_BUYER", precision=9, scale=0)
    public Integer getIndivNbrBuyer() {
        return this.indivNbrBuyer;
    }
    
    public void setIndivNbrBuyer(Integer indivNbrBuyer) {
        this.indivNbrBuyer = indivNbrBuyer;
    }

    
    @Column(name="STAT_ID", nullable=false, length=1)
    public String getStatId() {
        return this.statId;
    }
    
    public void setStatId(String statId) {
        this.statId = statId;
    }

    
    @Column(name="PICK_SCAN_ID", nullable=false, length=1)
    public String getPickScanId() {
        return this.pickScanId;
    }
    
    public void setPickScanId(String pickScanId) {
        this.pickScanId = pickScanId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="INTRO_DT", nullable=false, length=7)
    public Date getIntroDt() {
        return this.introDt;
    }
    
    public void setIntroDt(Date introDt) {
        this.introDt = introDt;
    }

    
    @Column(name="SPLIT_AT_BIN_FLG", nullable=false, length=1)
    public String getSplitAtBinFlg() {
        return this.splitAtBinFlg;
    }
    
    public void setSplitAtBinFlg(String splitAtBinFlg) {
        this.splitAtBinFlg = splitAtBinFlg;
    }

    
    @Column(name="LABEL_NM_BOX", length=20)
    public String getLabelNmBox() {
        return this.labelNmBox;
    }
    
    public void setLabelNmBox(String labelNmBox) {
        this.labelNmBox = labelNmBox;
    }

    
    @Column(name="IC_RECV_RULE_CD", length=16)
    public String getIcRecvRuleCd() {
        return this.icRecvRuleCd;
    }
    
    public void setIcRecvRuleCd(String icRecvRuleCd) {
        this.icRecvRuleCd = icRecvRuleCd;
    }

    
    @Column(name="CYCLE_CNT_RULE_CD", length=16)
    public String getCycleCntRuleCd() {
        return this.cycleCntRuleCd;
    }
    
    public void setCycleCntRuleCd(String cycleCntRuleCd) {
        this.cycleCntRuleCd = cycleCntRuleCd;
    }

    
    @Column(name="FIFO_DT_ID", nullable=false, length=1)
    public String getFifoDtId() {
        return this.fifoDtId;
    }
    
    public void setFifoDtId(String fifoDtId) {
        this.fifoDtId = fifoDtId;
    }

    
    @Column(name="REPLEN_TYPE_ID", nullable=false, length=1)
    public String getReplenTypeId() {
        return this.replenTypeId;
    }
    
    public void setReplenTypeId(String replenTypeId) {
        this.replenTypeId = replenTypeId;
    }

    
    @Column(name="ITEM_NBR_SUPERSEDE", precision=9, scale=0)
    public Integer getItemNbrSupersede() {
        return this.itemNbrSupersede;
    }
    
    public void setItemNbrSupersede(Integer itemNbrSupersede) {
        this.itemNbrSupersede = itemNbrSupersede;
    }

    
    @Column(name="SCHED_QTY_OPTIMAL", precision=7, scale=0)
    public Integer getSchedQtyOptimal() {
        return this.schedQtyOptimal;
    }
    
    public void setSchedQtyOptimal(Integer schedQtyOptimal) {
        this.schedQtyOptimal = schedQtyOptimal;
    }

    
    @Column(name="IMG_IMAGE_SET_HDR_NBR", precision=9, scale=0)
    public Integer getImgImageSetHdrNbr() {
        return this.imgImageSetHdrNbr;
    }
    
    public void setImgImageSetHdrNbr(Integer imgImageSetHdrNbr) {
        this.imgImageSetHdrNbr = imgImageSetHdrNbr;
    }

    
    @Column(name="ITEM_WGHT", precision=12, scale=5)
    public BigDecimal getItemWght() {
        return this.itemWght;
    }
    
    public void setItemWght(BigDecimal itemWght) {
        this.itemWght = itemWght;
    }

    
    @Column(name="CTN_VOLUME", precision=10)
    public BigDecimal getCtnVolume() {
        return this.ctnVolume;
    }
    
    public void setCtnVolume(BigDecimal ctnVolume) {
        this.ctnVolume = ctnVolume;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<WoDtl> getWoDtls() {
        return this.woDtls;
    }
    
    public void setWoDtls(Set<WoDtl> woDtls) {
        this.woDtls = woDtls;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<IcUmCnvtItem> getIcUmCnvtItems() {
        return this.icUmCnvtItems;
    }
    
    public void setIcUmCnvtItems(Set<IcUmCnvtItem> icUmCnvtItems) {
        this.icUmCnvtItems = icUmCnvtItems;
    }

//@OneToOne(fetch=FetchType.LAZY, mappedBy="icItemMast")
//    public IcKitMast getIcKitMast() {
//        return this.icKitMast;
//    }
//    
//    public void setIcKitMast(IcKitMast icKitMast) {
//        this.icKitMast = icKitMast;
//    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMastByItemNbrRqst")
    public Set<OeOrdDtl> getOeOrdDtlsForItemNbrRqst() {
        return this.oeOrdDtlsForItemNbrRqst;
    }
    
    public void setOeOrdDtlsForItemNbrRqst(Set<OeOrdDtl> oeOrdDtlsForItemNbrRqst) {
        this.oeOrdDtlsForItemNbrRqst = oeOrdDtlsForItemNbrRqst;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<ArRmaRcpt> getArRmaRcpts() {
        return this.arRmaRcpts;
    }
    
    public void setArRmaRcpts(Set<ArRmaRcpt> arRmaRcpts) {
        this.arRmaRcpts = arRmaRcpts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<IcItemPriceMatrix> getIcItemPriceMatrixes() {
        return this.icItemPriceMatrixes;
    }
    
    public void setIcItemPriceMatrixes(Set<IcItemPriceMatrix> icItemPriceMatrixes) {
        this.icItemPriceMatrixes = icItemPriceMatrixes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<IcItemRevLvl> getIcItemRevLvls() {
        return this.icItemRevLvls;
    }
    
    public void setIcItemRevLvls(Set<IcItemRevLvl> icItemRevLvls) {
        this.icItemRevLvls = icItemRevLvls;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<IcLotMast> getIcLotMasts() {
        return this.icLotMasts;
    }
    
    public void setIcLotMasts(Set<IcLotMast> icLotMasts) {
        this.icLotMasts = icLotMasts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<IcItemMast> getIcItemMasts() {
        return this.icItemMasts;
    }
    
    public void setIcItemMasts(Set<IcItemMast> icItemMasts) {
        this.icItemMasts = icItemMasts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<IcItemVndCostMatrix> getIcItemVndCostMatrixes() {
        return this.icItemVndCostMatrixes;
    }
    
    public void setIcItemVndCostMatrixes(Set<IcItemVndCostMatrix> icItemVndCostMatrixes) {
        this.icItemVndCostMatrixes = icItemVndCostMatrixes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMastByItemNbrOrd")
    public Set<OeOrdDtl> getOeOrdDtlsForItemNbrOrd() {
        return this.oeOrdDtlsForItemNbrOrd;
    }
    
    public void setOeOrdDtlsForItemNbrOrd(Set<OeOrdDtl> oeOrdDtlsForItemNbrOrd) {
        this.oeOrdDtlsForItemNbrOrd = oeOrdDtlsForItemNbrOrd;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<PoLineMultipleCert> getPoLineMultipleCerts() {
        return this.poLineMultipleCerts;
    }
    
    public void setPoLineMultipleCerts(Set<PoLineMultipleCert> poLineMultipleCerts) {
        this.poLineMultipleCerts = poLineMultipleCerts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<IcItemMastNomen> getIcItemMastNomens() {
        return this.icItemMastNomens;
    }
    
    public void setIcItemMastNomens(Set<IcItemMastNomen> icItemMastNomens) {
        this.icItemMastNomens = icItemMastNomens;
    }

////@OneToOne(fetch=FetchType.LAZY, mappedBy="icItemMast")
//    public IcItemNarr getIcItemNarr() {
//        return this.icItemNarr;
//    }
//    
//    public void setIcItemNarr(IcItemNarr icItemNarr) {
//        this.icItemNarr = icItemNarr;
//    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMastByItemNbr")
    public Set<OeContractItem> getOeContractItemsForItemNbr() {
        return this.oeContractItemsForItemNbr;
    }
    
    public void setOeContractItemsForItemNbr(Set<OeContractItem> oeContractItemsForItemNbr) {
        this.oeContractItemsForItemNbr = oeContractItemsForItemNbr;
    }

////@OneToOne(fetch=FetchType.LAZY, mappedBy="icItemMast")
//    public IcItemMastUpdQueue getIcItemMastUpdQueue() {
//        return this.icItemMastUpdQueue;
//    }
//    
//    public void setIcItemMastUpdQueue(IcItemMastUpdQueue icItemMastUpdQueue) {
//        this.icItemMastUpdQueue = icItemMastUpdQueue;
//    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<OeCustMfr> getOeCustMfrs() {
        return this.oeCustMfrs;
    }
    
    public void setOeCustMfrs(Set<OeCustMfr> oeCustMfrs) {
        this.oeCustMfrs = oeCustMfrs;
    }

////@OneToOne(fetch=FetchType.LAZY, mappedBy="icItemMast")
//    public IcItemMfgPath getIcItemMfgPath() {
//        return this.icItemMfgPath;
//    }
//    
//    public void setIcItemMfgPath(IcItemMfgPath icItemMfgPath) {
//        this.icItemMfgPath = icItemMfgPath;
//    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<IcItemOperationYield> getIcItemOperationYields() {
        return this.icItemOperationYields;
    }
    
    public void setIcItemOperationYields(Set<IcItemOperationYield> icItemOperationYields) {
        this.icItemOperationYields = icItemOperationYields;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<WoHdr> getWoHdrs() {
        return this.woHdrs;
    }
    
    public void setWoHdrs(Set<WoHdr> woHdrs) {
        this.woHdrs = woHdrs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<IcItemMastCert> getIcItemMastCerts() {
        return this.icItemMastCerts;
    }
    
    public void setIcItemMastCerts(Set<IcItemMastCert> icItemMastCerts) {
        this.icItemMastCerts = icItemMastCerts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<IcMultipleCert> getIcMultipleCerts() {
        return this.icMultipleCerts;
    }
    
    public void setIcMultipleCerts(Set<IcMultipleCert> icMultipleCerts) {
        this.icMultipleCerts = icMultipleCerts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<QaMfrApprv> getQaMfrApprvs() {
        return this.qaMfrApprvs;
    }
    
    public void setQaMfrApprvs(Set<QaMfrApprv> qaMfrApprvs) {
        this.qaMfrApprvs = qaMfrApprvs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMastByItemNbr")
    public Set<IcItemMastRel> getIcItemMastRelsForItemNbr() {
        return this.icItemMastRelsForItemNbr;
    }
    
    public void setIcItemMastRelsForItemNbr(Set<IcItemMastRel> icItemMastRelsForItemNbr) {
        this.icItemMastRelsForItemNbr = icItemMastRelsForItemNbr;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<PoUnplannedRcpt> getPoUnplannedRcpts() {
        return this.poUnplannedRcpts;
    }
    
    public void setPoUnplannedRcpts(Set<PoUnplannedRcpt> poUnplannedRcpts) {
        this.poUnplannedRcpts = poUnplannedRcpts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<VqQteDtl> getVqQteDtls() {
        return this.vqQteDtls;
    }
    
    public void setVqQteDtls(Set<VqQteDtl> vqQteDtls) {
        this.vqQteDtls = vqQteDtls;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<SqQteDtl> getSqQteDtls() {
        return this.sqQteDtls;
    }
    
    public void setSqQteDtls(Set<SqQteDtl> sqQteDtls) {
        this.sqQteDtls = sqQteDtls;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
//    public Set<IcVndOnhand> getIcVndOnhands() {
//        return this.icVndOnhands;
//    }
//    
//    public void setIcVndOnhands(Set<IcVndOnhand> icVndOnhands) {
//        this.icVndOnhands = icVndOnhands;
//    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
//    public Set<IcItemCustSubst> getIcItemCustSubsts() {
//        return this.icItemCustSubsts;
//    }
//    
//    public void setIcItemCustSubsts(Set<IcItemCustSubst> icItemCustSubsts) {
//        this.icItemCustSubsts = icItemCustSubsts;
//    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
//    public Set<IcItemRestrictCust> getIcItemRestrictCusts() {
//        return this.icItemRestrictCusts;
//    }
//    
//    public void setIcItemRestrictCusts(Set<IcItemRestrictCust> icItemRestrictCusts) {
//        this.icItemRestrictCusts = icItemRestrictCusts;
//    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMastByItemNbrSupersede")
    public Set<OeContractItem> getOeContractItemsForItemNbrSupersede() {
        return this.oeContractItemsForItemNbrSupersede;
    }
    
    public void setOeContractItemsForItemNbrSupersede(Set<OeContractItem> oeContractItemsForItemNbrSupersede) {
        this.oeContractItemsForItemNbrSupersede = oeContractItemsForItemNbrSupersede;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<PoLineHdr> getPoLineHdrs() {
        return this.poLineHdrs;
    }
    
    public void setPoLineHdrs(Set<PoLineHdr> poLineHdrs) {
        this.poLineHdrs = poLineHdrs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<PosDtl> getPosDtls() {
        return this.posDtls;
    }
    
    public void setPosDtls(Set<PosDtl> posDtls) {
        this.posDtls = posDtls;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMastByItemNbrRel")
    public Set<IcItemMastRel> getIcItemMastRelsForItemNbrRel() {
        return this.icItemMastRelsForItemNbrRel;
    }
    
    public void setIcItemMastRelsForItemNbrRel(Set<IcItemMastRel> icItemMastRelsForItemNbrRel) {
        this.icItemMastRelsForItemNbrRel = icItemMastRelsForItemNbrRel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<ArRmaDtl> getArRmaDtls() {
        return this.arRmaDtls;
    }
    
    public void setArRmaDtls(Set<ArRmaDtl> arRmaDtls) {
        this.arRmaDtls = arRmaDtls;
    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
//    public Set<FcItemMast> getFcItemMasts() {
//        return this.fcItemMasts;
//    }
//    
//    public void setFcItemMasts(Set<FcItemMast> fcItemMasts) {
//        this.fcItemMasts = fcItemMasts;
//    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<IcItemAttr> getIcItemAttrs() {
        return this.icItemAttrs;
    }
    
    public void setIcItemAttrs(Set<IcItemAttr> icItemAttrs) {
        this.icItemAttrs = icItemAttrs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<VqQteMultipleCert> getVqQteMultipleCerts() {
        return this.vqQteMultipleCerts;
    }
    
    public void setVqQteMultipleCerts(Set<VqQteMultipleCert> vqQteMultipleCerts) {
        this.vqQteMultipleCerts = vqQteMultipleCerts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<ArInvDtl> getArInvDtls() {
        return this.arInvDtls;
    }
    
    public void setArInvDtls(Set<ArInvDtl> arInvDtls) {
        this.arInvDtls = arInvDtls;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
//    public Set<IcBomCert> getIcBomCerts() {
//        return this.icBomCerts;
//    }
//    
//    public void setIcBomCerts(Set<IcBomCert> icBomCerts) {
//        this.icBomCerts = icBomCerts;
//    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icItemMast")
    public Set<IcItemCost> getIcItemCosts() {
        return this.icItemCosts;
    }
    
    public void setIcItemCosts(Set<IcItemCost> icItemCosts) {
        this.icItemCosts = icItemCosts;
    }



	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("IcItemMast [itemNbr=");
		builder.append(itemNbr);
		builder.append(", icItemMast=");
		builder.append(icItemMast);
		builder.append(", itemCd=");
		builder.append(itemCd);
		builder.append(", itemDescr=");
		builder.append(itemDescr);
		builder.append(", stkUm=");
		builder.append(stkUm);
		builder.append(", sellUm=");
		builder.append(sellUm);
		builder.append(", stdCost=");
		builder.append(stdCost);
		builder.append(", listPrice=");
		builder.append(listPrice);
		builder.append(", upcCd=");
		builder.append(upcCd);
		builder.append(", ean=");
		builder.append(ean);
		builder.append(", qtyPerBox=");
		builder.append(qtyPerBox);
		builder.append(", boxPerCtn=");
		builder.append(boxPerCtn);
		builder.append(", slsQtyMin=");
		builder.append(slsQtyMin);
		builder.append(", slsQtyIncr=");
		builder.append(slsQtyIncr);
		builder.append(", replenQtyMin=");
		builder.append(replenQtyMin);
		builder.append(", replenQtyIncr=");
		builder.append(replenQtyIncr);
		builder.append(", icCategoryNbr=");
		builder.append(icCategoryNbr);
		builder.append(", nonStkFlg=");
		builder.append(nonStkFlg);
		builder.append(", serNbrReqrFlg=");
		builder.append(serNbrReqrFlg);
		builder.append(", mfrSerNbrReqrFlg=");
		builder.append(mfrSerNbrReqrFlg);
		builder.append(", inspectReqrFlg=");
		builder.append(inspectReqrFlg);
		builder.append(", mfrLotCtrlFlg=");
		builder.append(mfrLotCtrlFlg);
		builder.append(", kitFlg=");
		builder.append(kitFlg);
		builder.append(", priceChgFlg=");
		builder.append(priceChgFlg);
		builder.append(", utUserNbr=");
		builder.append(utUserNbr);
		builder.append(", lastModDt=");
		builder.append(lastModDt);
		builder.append(", sellFlg=");
		builder.append(sellFlg);
		builder.append(", harmonizedCd=");
		builder.append(harmonizedCd);
		builder.append(", planBucketSz=");
		builder.append(planBucketSz);
		builder.append(", currCd=");
		builder.append(currCd);
		builder.append(", reqrMfrFlg=");
		builder.append(reqrMfrFlg);
		builder.append(", shelfLifeDy=");
		builder.append(shelfLifeDy);
		builder.append(", leadTmDy=");
		builder.append(leadTmDy);
		builder.append(", indivNbrBuyer=");
		builder.append(indivNbrBuyer);
		builder.append(", statId=");
		builder.append(statId);
		builder.append(", pickScanId=");
		builder.append(pickScanId);
		builder.append(", introDt=");
		builder.append(introDt);
		builder.append(", splitAtBinFlg=");
		builder.append(splitAtBinFlg);
		builder.append(", labelNmBox=");
		builder.append(labelNmBox);
		builder.append(", icRecvRuleCd=");
		builder.append(icRecvRuleCd);
		builder.append(", cycleCntRuleCd=");
		builder.append(cycleCntRuleCd);
		builder.append(", fifoDtId=");
		builder.append(fifoDtId);
		builder.append(", replenTypeId=");
		builder.append(replenTypeId);
		builder.append(", itemNbrSupersede=");
		builder.append(itemNbrSupersede);
		builder.append(", schedQtyOptimal=");
		builder.append(schedQtyOptimal);
		builder.append(", imgImageSetHdrNbr=");
		builder.append(imgImageSetHdrNbr);
		builder.append(", itemWght=");
		builder.append(itemWght);
		builder.append(", ctnVolume=");
		builder.append(ctnVolume);
		builder.append("]");
		return builder.toString();
	}



//	/* (non-Javadoc)
//	 * @see java.lang.Object#toString()
//	 */
//	@Override
//	public String toString() {
//		return String.format(
//				"IcItemMast [itemNbr=%s, icItemMast=%s, itemCd=%s, itemDescr=%s, stkUm=%s, sellUm=%s, stdCost=%s, listPrice=%s, upcCd=%s, ean=%s, qtyPerBox=%s, boxPerCtn=%s, slsQtyMin=%s, slsQtyIncr=%s, replenQtyMin=%s, replenQtyIncr=%s, icCategoryNbr=%s, nonStkFlg=%s, serNbrReqrFlg=%s, mfrSerNbrReqrFlg=%s, inspectReqrFlg=%s, mfrLotCtrlFlg=%s, kitFlg=%s, priceChgFlg=%s, utUserNbr=%s, lastModDt=%s, sellFlg=%s, harmonizedCd=%s, planBucketSz=%s, currCd=%s, reqrMfrFlg=%s, shelfLifeDy=%s, leadTmDy=%s, indivNbrBuyer=%s, statId=%s, pickScanId=%s, introDt=%s, splitAtBinFlg=%s, labelNmBox=%s, icRecvRuleCd=%s, cycleCntRuleCd=%s, fifoDtId=%s, replenTypeId=%s, itemNbrSupersede=%s, schedQtyOptimal=%s, imgImageSetHdrNbr=%s, itemWght=%s, ctnVolume=%s, woDtls=%s, icUmCnvtItems=%s, oeOrdDtlsForItemNbrRqst=%s, arRmaRcpts=%s, icItemPriceMatrixes=%s, icItemRevLvls=%s, icLotMasts=%s, icItemMasts=%s, icItemVndCostMatrixes=%s, oeOrdDtlsForItemNbrOrd=%s, poLineMultipleCerts=%s, icItemMastNomens=%s, oeContractItemsForItemNbr=%s, oeCustMfrs=%s, icItemOperationYields=%s, woHdrs=%s, icItemMastCerts=%s, icMultipleCerts=%s, qaMfrApprvs=%s, icItemMastRelsForItemNbr=%s, poUnplannedRcpts=%s, vqQteDtls=%s, sqQteDtls=%s, icItemRestrictCusts=%s, oeContractItemsForItemNbrSupersede=%s, poLineHdrs=%s, posDtls=%s, icItemMastRelsForItemNbrRel=%s, arRmaDtls=%s, icItemAttrs=%s, vqQteMultipleCerts=%s, arInvDtls=%s, icItemCosts=%s]",
//				itemNbr, icItemMast, itemCd, itemDescr, stkUm, sellUm, stdCost, listPrice, upcCd, ean, qtyPerBox,
//				boxPerCtn, slsQtyMin, slsQtyIncr, replenQtyMin, replenQtyIncr, icCategoryNbr, nonStkFlg, serNbrReqrFlg,
//				mfrSerNbrReqrFlg, inspectReqrFlg, mfrLotCtrlFlg, kitFlg, priceChgFlg, utUserNbr, lastModDt, sellFlg,
//				harmonizedCd, planBucketSz, currCd, reqrMfrFlg, shelfLifeDy, leadTmDy, indivNbrBuyer, statId,
//				pickScanId, introDt, splitAtBinFlg, labelNmBox, icRecvRuleCd, cycleCntRuleCd, fifoDtId, replenTypeId,
//				itemNbrSupersede, schedQtyOptimal, imgImageSetHdrNbr, itemWght, ctnVolume, woDtls, icUmCnvtItems,
//				oeOrdDtlsForItemNbrRqst, arRmaRcpts, icItemPriceMatrixes, icItemRevLvls, icLotMasts, icItemMasts,
//				icItemVndCostMatrixes, oeOrdDtlsForItemNbrOrd, poLineMultipleCerts, icItemMastNomens,
//				oeContractItemsForItemNbr, oeCustMfrs, icItemOperationYields, woHdrs, icItemMastCerts, icMultipleCerts,
//				qaMfrApprvs, icItemMastRelsForItemNbr, poUnplannedRcpts, vqQteDtls, sqQteDtls, icItemRestrictCusts,
//				oeContractItemsForItemNbrSupersede, poLineHdrs, posDtls, icItemMastRelsForItemNbrRel, arRmaDtls,
//				icItemAttrs, vqQteMultipleCerts, arInvDtls, icItemCosts);
//	}




}


