package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IcItemLocBoxVw generated by hbm2java
 */
@Entity
@Table(name="IC_ITEM_LOC_BOX_VW"
)
public class IcItemLocBoxVw  implements java.io.Serializable {


     private IcItemLocBoxVwId id;

    public IcItemLocBoxVw() {
    }

    public IcItemLocBoxVw(IcItemLocBoxVwId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="icItemLocNbr", column=@Column(name="IC_ITEM_LOC_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="lotNbr", column=@Column(name="LOT_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="itemCd", column=@Column(name="ITEM_CD", nullable=false, length=50) ), 
        @AttributeOverride(name="itemDescr", column=@Column(name="ITEM_DESCR", nullable=false, length=50) ), 
        @AttributeOverride(name="statId", column=@Column(name="STAT_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="stkUm", column=@Column(name="STK_UM", nullable=false, length=3) ), 
        @AttributeOverride(name="sellUm", column=@Column(name="SELL_UM", length=3) ), 
        @AttributeOverride(name="stdCost", column=@Column(name="STD_COST", precision=17, scale=6) ), 
        @AttributeOverride(name="listPrice", column=@Column(name="LIST_PRICE", precision=17, scale=6) ), 
        @AttributeOverride(name="upcCd", column=@Column(name="UPC_CD", length=20) ), 
        @AttributeOverride(name="ean", column=@Column(name="EAN", length=50) ), 
        @AttributeOverride(name="qtyPerBox", column=@Column(name="QTY_PER_BOX", precision=7, scale=0) ), 
        @AttributeOverride(name="boxPerCtn", column=@Column(name="BOX_PER_CTN", precision=7, scale=0) ), 
        @AttributeOverride(name="slsQtyMin", column=@Column(name="SLS_QTY_MIN", precision=7, scale=0) ), 
        @AttributeOverride(name="slsQtyIncr", column=@Column(name="SLS_QTY_INCR", precision=7, scale=0) ), 
        @AttributeOverride(name="replenQtyMin", column=@Column(name="REPLEN_QTY_MIN", precision=7, scale=0) ), 
        @AttributeOverride(name="replenQtyIncr", column=@Column(name="REPLEN_QTY_INCR", precision=7, scale=0) ), 
        @AttributeOverride(name="icCategoryNbr", column=@Column(name="IC_CATEGORY_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="icCategoryNm", column=@Column(name="IC_CATEGORY_NM", nullable=false, length=16) ), 
        @AttributeOverride(name="icCategoryDescr", column=@Column(name="IC_CATEGORY_DESCR", length=30) ), 
        @AttributeOverride(name="icCategoryNbrParent", column=@Column(name="IC_CATEGORY_NBR_PARENT", precision=9, scale=0) ), 
        @AttributeOverride(name="poVndSetHdrNbr", column=@Column(name="PO_VND_SET_HDR_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="nonStkFlg", column=@Column(name="NON_STK_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="serNbrReqrFlg", column=@Column(name="SER_NBR_REQR_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="mfrSerNbrReqrFlg", column=@Column(name="MFR_SER_NBR_REQR_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="inspectReqrFlg", column=@Column(name="INSPECT_REQR_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="mfrLotCtrlFlg", column=@Column(name="MFR_LOT_CTRL_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="kitFlg", column=@Column(name="KIT_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="priceChgFlg", column=@Column(name="PRICE_CHG_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="sellFlg", column=@Column(name="SELL_FLG", length=1) ), 
        @AttributeOverride(name="harmonizedCd", column=@Column(name="HARMONIZED_CD", length=15) ), 
        @AttributeOverride(name="planBucketSz", column=@Column(name="PLAN_BUCKET_SZ", precision=3, scale=0) ), 
        @AttributeOverride(name="currCd", column=@Column(name="CURR_CD", length=3) ), 
        @AttributeOverride(name="reqrMfrFlg", column=@Column(name="REQR_MFR_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="shelfLifeDy", column=@Column(name="SHELF_LIFE_DY", precision=5, scale=0) ), 
        @AttributeOverride(name="leadTmDy", column=@Column(name="LEAD_TM_DY", precision=5, scale=0) ), 
        @AttributeOverride(name="indivNbrBuyer", column=@Column(name="INDIV_NBR_BUYER", precision=9, scale=0) ), 
        @AttributeOverride(name="pickScanId", column=@Column(name="PICK_SCAN_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="introDt", column=@Column(name="INTRO_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="replenTypeId", column=@Column(name="REPLEN_TYPE_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="cycleCntRuleCd", column=@Column(name="CYCLE_CNT_RULE_CD", length=16) ), 
        @AttributeOverride(name="labelNmBox", column=@Column(name="LABEL_NM_BOX", length=20) ), 
        @AttributeOverride(name="icRecvRuleCd", column=@Column(name="IC_RECV_RULE_CD", length=16) ), 
        @AttributeOverride(name="splitAtBinFlg", column=@Column(name="SPLIT_AT_BIN_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="fifoDtId", column=@Column(name="FIFO_DT_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="binNbr", column=@Column(name="BIN_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="binCd", column=@Column(name="BIN_CD", nullable=false, length=16) ), 
        @AttributeOverride(name="facility", column=@Column(name="FACILITY", nullable=false, length=16) ), 
        @AttributeOverride(name="pickFlg", column=@Column(name="PICK_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="packStationFlg", column=@Column(name="PACK_STATION_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="inspectFlg", column=@Column(name="INSPECT_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="putAwayFlg", column=@Column(name="PUT_AWAY_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="binStatCd", column=@Column(name="BIN_STAT_CD", length=1) ), 
        @AttributeOverride(name="whWhseZoneNbr", column=@Column(name="WH_WHSE_ZONE_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="walkSeq", column=@Column(name="WALK_SEQ", precision=5, scale=0) ), 
        @AttributeOverride(name="pickEase", column=@Column(name="PICK_EASE", precision=1, scale=0) ), 
        @AttributeOverride(name="deleteWhenEmptyFlg", column=@Column(name="DELETE_WHEN_EMPTY_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="mrbFlg", column=@Column(name="MRB_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="binConsumeSeq", column=@Column(name="BIN_CONSUME_SEQ", precision=5, scale=0) ), 
        @AttributeOverride(name="transitBinFlg", column=@Column(name="TRANSIT_BIN_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="apsSplySubPoolNbr", column=@Column(name="APS_SPLY_SUB_POOL_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="apsSplyPoolCd", column=@Column(name="APS_SPLY_POOL_CD", nullable=false, length=20) ), 
        @AttributeOverride(name="apsSplySubPoolCd", column=@Column(name="APS_SPLY_SUB_POOL_CD", nullable=false, length=20) ), 
        @AttributeOverride(name="apsSplySubPoolDescr", column=@Column(name="APS_SPLY_SUB_POOL_DESCR", length=60) ), 
        @AttributeOverride(name="splyPoolTypeId", column=@Column(name="SPLY_POOL_TYPE_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="orgNbrVndSplyPool", column=@Column(name="ORG_NBR_VND_SPLY_POOL", precision=9, scale=0) ), 
        @AttributeOverride(name="availDt", column=@Column(name="AVAIL_DT", length=7) ), 
        @AttributeOverride(name="boxCd", column=@Column(name="BOX_CD", nullable=false, length=20) ), 
        @AttributeOverride(name="boxQty", column=@Column(name="BOX_QTY", precision=12, scale=5) ), 
        @AttributeOverride(name="boxStatId", column=@Column(name="BOX_STAT_ID", nullable=false, length=3) ), 
        @AttributeOverride(name="serialCd", column=@Column(name="SERIAL_CD", length=20) ), 
        @AttributeOverride(name="mfrSerialCd", column=@Column(name="MFR_SERIAL_CD", length=20) ), 
        @AttributeOverride(name="revLvl", column=@Column(name="REV_LVL", length=5) ), 
        @AttributeOverride(name="mfrLotCd", column=@Column(name="MFR_LOT_CD", length=20) ), 
        @AttributeOverride(name="poOrdHdrNbr", column=@Column(name="PO_ORD_HDR_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="poLineHdrNbr", column=@Column(name="PO_LINE_HDR_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="orgNbrVnd", column=@Column(name="ORG_NBR_VND", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="orgNbrMfr", column=@Column(name="ORG_NBR_MFR", precision=9, scale=0) ), 
        @AttributeOverride(name="rcptDt", column=@Column(name="RCPT_DT", length=7) ), 
        @AttributeOverride(name="lotCostUm", column=@Column(name="LOT_COST_UM", nullable=false, length=3) ), 
        @AttributeOverride(name="lotCost", column=@Column(name="LOT_COST", nullable=false, precision=13, scale=6) ), 
        @AttributeOverride(name="lotCostCurrCd", column=@Column(name="LOT_COST_CURR_CD", length=3) ), 
        @AttributeOverride(name="lotCostDenom", column=@Column(name="LOT_COST_DENOM", precision=13, scale=6) ), 
        @AttributeOverride(name="lotCostCurrCdDenom", column=@Column(name="LOT_COST_CURR_CD_DENOM", length=3) ), 
        @AttributeOverride(name="lotCostLandedOrig", column=@Column(name="LOT_COST_LANDED_ORIG", precision=17, scale=6) ), 
        @AttributeOverride(name="lotCostLandedDenomOrig", column=@Column(name="LOT_COST_LANDED_DENOM_ORIG", precision=17, scale=6) ), 
        @AttributeOverride(name="lotCostLandedCurr", column=@Column(name="LOT_COST_LANDED_CURR", precision=17, scale=6) ), 
        @AttributeOverride(name="lotStatId", column=@Column(name="LOT_STAT_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="mfrDate", column=@Column(name="MFR_DATE", length=7) ), 
        @AttributeOverride(name="lotCreComm", column=@Column(name="LOT_CRE_COMM", length=200) ), 
        @AttributeOverride(name="recvQty", column=@Column(name="RECV_QTY", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="inspectQty", column=@Column(name="INSPECT_QTY", precision=10) ), 
        @AttributeOverride(name="utUserNbrInspect", column=@Column(name="UT_USER_NBR_INSPECT", precision=9, scale=0) ), 
        @AttributeOverride(name="acceptQty", column=@Column(name="ACCEPT_QTY", precision=22, scale=0) ), 
        @AttributeOverride(name="inspectDt", column=@Column(name="INSPECT_DT", length=7) ), 
        @AttributeOverride(name="rejQty", column=@Column(name="REJ_QTY", precision=10) ), 
        @AttributeOverride(name="trdFlg", column=@Column(name="TRD_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="itemCdVnd", column=@Column(name="ITEM_CD_VND", length=50) ), 
        @AttributeOverride(name="cntryCdOrigin", column=@Column(name="CNTRY_CD_ORIGIN", length=3) ), 
        @AttributeOverride(name="lotNbrOrig", column=@Column(name="LOT_NBR_ORIG", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="expireDt", column=@Column(name="EXPIRE_DT", length=7) ), 
        @AttributeOverride(name="orgCdVnd", column=@Column(name="ORG_CD_VND", nullable=false, length=15) ), 
        @AttributeOverride(name="orgNmVnd", column=@Column(name="ORG_NM_VND", nullable=false, length=60) ), 
        @AttributeOverride(name="orgCdMfr", column=@Column(name="ORG_CD_MFR", length=15) ), 
        @AttributeOverride(name="orgNmMfr", column=@Column(name="ORG_NM_MFR", length=60) ), 
        @AttributeOverride(name="mfrCageCd", column=@Column(name="MFR_CAGE_CD", length=10) ), 
        @AttributeOverride(name="poCd", column=@Column(name="PO_CD", length=20) ), 
        @AttributeOverride(name="poDt", column=@Column(name="PO_DT", length=7) ), 
        @AttributeOverride(name="poTypeId", column=@Column(name="PO_TYPE_ID", length=1) ), 
        @AttributeOverride(name="locConfirmRqstDt", column=@Column(name="LOC_CONFIRM_RQST_DT", length=7) ), 
        @AttributeOverride(name="locConfirmActDt", column=@Column(name="LOC_CONFIRM_ACT_DT", length=7) ), 
        @AttributeOverride(name="utUserNbrLocConfirm", column=@Column(name="UT_USER_NBR_LOC_CONFIRM", precision=9, scale=0) ), 
        @AttributeOverride(name="qtyConfirmRqstDt", column=@Column(name="QTY_CONFIRM_RQST_DT", length=7) ), 
        @AttributeOverride(name="qtyConfirmActDt", column=@Column(name="QTY_CONFIRM_ACT_DT", length=7) ), 
        @AttributeOverride(name="utUserNbrQtyConfirm", column=@Column(name="UT_USER_NBR_QTY_CONFIRM", precision=9, scale=0) ), 
        @AttributeOverride(name="boxQtyLost", column=@Column(name="BOX_QTY_LOST", precision=22, scale=0) ), 
        @AttributeOverride(name="boxQtyInPick", column=@Column(name="BOX_QTY_IN_PICK", precision=22, scale=0) ), 
        @AttributeOverride(name="lotQtyPerBox", column=@Column(name="LOT_QTY_PER_BOX", precision=22, scale=0) ), 
        @AttributeOverride(name="splySubPoolAvailFlg", column=@Column(name="SPLY_SUB_POOL_AVAIL_FLG", nullable=false, length=1) ) } )
    public IcItemLocBoxVwId getId() {
        return this.id;
    }
    
    public void setId(IcItemLocBoxVwId id) {
        this.id = id;
    }




}


