package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IcLotMastVw generated by hbm2java
 */
@Entity
@Table(name="IC_LOT_MAST_VW"
)
public class IcLotMastVw  implements java.io.Serializable {


     private IcLotMastVwId id;

    public IcLotMastVw() {
    }

    public IcLotMastVw(IcLotMastVwId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="itemCd", column=@Column(name="ITEM_CD", nullable=false, length=50) ), 
        @AttributeOverride(name="lotNbr", column=@Column(name="LOT_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="revLvl", column=@Column(name="REV_LVL", length=5) ), 
        @AttributeOverride(name="mfrLotCd", column=@Column(name="MFR_LOT_CD", length=20) ), 
        @AttributeOverride(name="poOrdHdrNbr", column=@Column(name="PO_ORD_HDR_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="poLineHdrNbr", column=@Column(name="PO_LINE_HDR_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="orgNbrVnd", column=@Column(name="ORG_NBR_VND", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="orgCdVnd", column=@Column(name="ORG_CD_VND", length=15) ), 
        @AttributeOverride(name="orgNmVnd", column=@Column(name="ORG_NM_VND", length=60) ), 
        @AttributeOverride(name="orgNbrMfr", column=@Column(name="ORG_NBR_MFR", precision=9, scale=0) ), 
        @AttributeOverride(name="orgCdMfr", column=@Column(name="ORG_CD_MFR", length=15) ), 
        @AttributeOverride(name="orgNmMfr", column=@Column(name="ORG_NM_MFR", length=60) ), 
        @AttributeOverride(name="rcptDt", column=@Column(name="RCPT_DT", length=7) ), 
        @AttributeOverride(name="lotCostUm", column=@Column(name="LOT_COST_UM", nullable=false, length=3) ), 
        @AttributeOverride(name="lotCost", column=@Column(name="LOT_COST", nullable=false, precision=13, scale=6) ), 
        @AttributeOverride(name="lotCostCurrCd", column=@Column(name="LOT_COST_CURR_CD", length=3) ), 
        @AttributeOverride(name="lotCostDenom", column=@Column(name="LOT_COST_DENOM", precision=13, scale=6) ), 
        @AttributeOverride(name="lotCostCurrCdDenom", column=@Column(name="LOT_COST_CURR_CD_DENOM", length=3) ), 
        @AttributeOverride(name="lotCostLandedOrig", column=@Column(name="LOT_COST_LANDED_ORIG", precision=17, scale=6) ), 
        @AttributeOverride(name="lotCostLandedDenomOrig", column=@Column(name="LOT_COST_LANDED_DENOM_ORIG", precision=17, scale=6) ), 
        @AttributeOverride(name="lotCostLandedCurr", column=@Column(name="LOT_COST_LANDED_CURR", precision=17, scale=6) ), 
        @AttributeOverride(name="lotCostLandedDenomCurr", column=@Column(name="LOT_COST_LANDED_DENOM_CURR", precision=17, scale=6) ), 
        @AttributeOverride(name="lotStatId", column=@Column(name="LOT_STAT_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="mfrDate", column=@Column(name="MFR_DATE", length=7) ), 
        @AttributeOverride(name="lotCreComm", column=@Column(name="LOT_CRE_COMM", length=200) ), 
        @AttributeOverride(name="recvQty", column=@Column(name="RECV_QTY", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="inspectQty", column=@Column(name="INSPECT_QTY", precision=10) ), 
        @AttributeOverride(name="utUserNbrInspect", column=@Column(name="UT_USER_NBR_INSPECT", precision=9, scale=0) ), 
        @AttributeOverride(name="acceptQty", column=@Column(name="ACCEPT_QTY", precision=22, scale=0) ), 
        @AttributeOverride(name="inspectDt", column=@Column(name="INSPECT_DT", length=7) ), 
        @AttributeOverride(name="rejQty", column=@Column(name="REJ_QTY", precision=10) ), 
        @AttributeOverride(name="trdFlg", column=@Column(name="TRD_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="lotMastModUser", column=@Column(name="LOT_MAST_MOD_USER", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="lotMastModDt", column=@Column(name="LOT_MAST_MOD_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="itemCdVnd", column=@Column(name="ITEM_CD_VND", length=50) ), 
        @AttributeOverride(name="cntryCdOrigin", column=@Column(name="CNTRY_CD_ORIGIN", length=3) ), 
        @AttributeOverride(name="itemDescr", column=@Column(name="ITEM_DESCR", nullable=false, length=50) ), 
        @AttributeOverride(name="statId", column=@Column(name="STAT_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="stkUm", column=@Column(name="STK_UM", nullable=false, length=3) ), 
        @AttributeOverride(name="sellUm", column=@Column(name="SELL_UM", length=3) ), 
        @AttributeOverride(name="stdCost", column=@Column(name="STD_COST", precision=17, scale=6) ), 
        @AttributeOverride(name="listPrice", column=@Column(name="LIST_PRICE", precision=17, scale=6) ), 
        @AttributeOverride(name="upcCd", column=@Column(name="UPC_CD", length=20) ), 
        @AttributeOverride(name="ean", column=@Column(name="EAN", length=50) ), 
        @AttributeOverride(name="qtyPerBox", column=@Column(name="QTY_PER_BOX", precision=7, scale=0) ), 
        @AttributeOverride(name="boxPerCtn", column=@Column(name="BOX_PER_CTN", precision=7, scale=0) ), 
        @AttributeOverride(name="slsQtyMin", column=@Column(name="SLS_QTY_MIN", precision=7, scale=0) ), 
        @AttributeOverride(name="slsQtyIncr", column=@Column(name="SLS_QTY_INCR", precision=7, scale=0) ), 
        @AttributeOverride(name="replenQtyMin", column=@Column(name="REPLEN_QTY_MIN", precision=7, scale=0) ), 
        @AttributeOverride(name="replenQtyIncr", column=@Column(name="REPLEN_QTY_INCR", precision=7, scale=0) ), 
        @AttributeOverride(name="icCategoryNbr", column=@Column(name="IC_CATEGORY_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="nonStkFlg", column=@Column(name="NON_STK_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="serNbrReqrFlg", column=@Column(name="SER_NBR_REQR_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="mfrSerNbrReqrFlg", column=@Column(name="MFR_SER_NBR_REQR_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="inspectReqrFlg", column=@Column(name="INSPECT_REQR_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="mfrLotCtrlFlg", column=@Column(name="MFR_LOT_CTRL_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="kitFlg", column=@Column(name="KIT_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="priceChgFlg", column=@Column(name="PRICE_CHG_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="sellFlg", column=@Column(name="SELL_FLG", length=1) ), 
        @AttributeOverride(name="harmonizedCd", column=@Column(name="HARMONIZED_CD", length=15) ), 
        @AttributeOverride(name="processedForApFlg", column=@Column(name="PROCESSED_FOR_AP_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="expireDt", column=@Column(name="EXPIRE_DT", length=7) ), 
        @AttributeOverride(name="qtyOnHandFlg", column=@Column(name="QTY_ON_HAND_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="lotQtyPerBox", column=@Column(name="LOT_QTY_PER_BOX", precision=7, scale=0) ), 
        @AttributeOverride(name="poCd", column=@Column(name="PO_CD", length=20) ), 
        @AttributeOverride(name="woHdrNbr", column=@Column(name="WO_HDR_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="woReleaseNbr", column=@Column(name="WO_RELEASE_NBR", precision=9, scale=0) ) } )
    public IcLotMastVwId getId() {
        return this.id;
    }
    
    public void setId(IcLotMastVwId id) {
        this.id = id;
    }




}


