package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IcMultipleCert generated by hbm2java
 */
@Entity
@Table(name="IC_MULTIPLE_CERT"
)
public class IcMultipleCert  implements java.io.Serializable {


     private IcMultipleCertId id;
     private IcLotMast icLotMast;
     private IcItemMast icItemMast;
     private String revLvl;
     private String inspectedFlg;
     private int utUserNbr;
     private Date lastModDt;

    public IcMultipleCert() {
    }

	
    public IcMultipleCert(IcMultipleCertId id, IcLotMast icLotMast, IcItemMast icItemMast, String inspectedFlg, int utUserNbr, Date lastModDt) {
        this.id = id;
        this.icLotMast = icLotMast;
        this.icItemMast = icItemMast;
        this.inspectedFlg = inspectedFlg;
        this.utUserNbr = utUserNbr;
        this.lastModDt = lastModDt;
    }
    public IcMultipleCert(IcMultipleCertId id, IcLotMast icLotMast, IcItemMast icItemMast, String revLvl, String inspectedFlg, int utUserNbr, Date lastModDt) {
       this.id = id;
       this.icLotMast = icLotMast;
       this.icItemMast = icItemMast;
       this.revLvl = revLvl;
       this.inspectedFlg = inspectedFlg;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="lotNbr", column=@Column(name="LOT_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", nullable=false, precision=9, scale=0) ) } )
    public IcMultipleCertId getId() {
        return this.id;
    }
    
    public void setId(IcMultipleCertId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LOT_NBR", nullable=false, insertable=false, updatable=false)
    public IcLotMast getIcLotMast() {
        return this.icLotMast;
    }
    
    public void setIcLotMast(IcLotMast icLotMast) {
        this.icLotMast = icLotMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR", nullable=false, insertable=false, updatable=false)
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }

    
    @Column(name="REV_LVL", length=5)
    public String getRevLvl() {
        return this.revLvl;
    }
    
    public void setRevLvl(String revLvl) {
        this.revLvl = revLvl;
    }

    
    @Column(name="INSPECTED_FLG", nullable=false, length=1)
    public String getInspectedFlg() {
        return this.inspectedFlg;
    }
    
    public void setInspectedFlg(String inspectedFlg) {
        this.inspectedFlg = inspectedFlg;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }




}


