package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IcUmCnvtItem generated by hbm2java
 */
@Entity
@Table(name="IC_UM_CNVT_ITEM"
)
public class IcUmCnvtItem  implements java.io.Serializable {


     private IcUmCnvtItemId id;
     private IcUm icUmByUmIdTo;
     private IcUm icUmByUmIdFrom;
     private IcItemMast icItemMast;
     private BigDecimal umCnvtFactItem;
     private int utUserNbr;
     private Date lastModDt;

    public IcUmCnvtItem() {
    }

    public IcUmCnvtItem(IcUmCnvtItemId id, IcUm icUmByUmIdTo, IcUm icUmByUmIdFrom, IcItemMast icItemMast, BigDecimal umCnvtFactItem, int utUserNbr, Date lastModDt) {
       this.id = id;
       this.icUmByUmIdTo = icUmByUmIdTo;
       this.icUmByUmIdFrom = icUmByUmIdFrom;
       this.icItemMast = icItemMast;
       this.umCnvtFactItem = umCnvtFactItem;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="umIdFrom", column=@Column(name="UM_ID_FROM", nullable=false, length=3) ), 
        @AttributeOverride(name="umIdTo", column=@Column(name="UM_ID_TO", nullable=false, length=3) ) } )
    public IcUmCnvtItemId getId() {
        return this.id;
    }
    
    public void setId(IcUmCnvtItemId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UM_ID_TO", nullable=false, insertable=false, updatable=false)
    public IcUm getIcUmByUmIdTo() {
        return this.icUmByUmIdTo;
    }
    
    public void setIcUmByUmIdTo(IcUm icUmByUmIdTo) {
        this.icUmByUmIdTo = icUmByUmIdTo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UM_ID_FROM", nullable=false, insertable=false, updatable=false)
    public IcUm getIcUmByUmIdFrom() {
        return this.icUmByUmIdFrom;
    }
    
    public void setIcUmByUmIdFrom(IcUm icUmByUmIdFrom) {
        this.icUmByUmIdFrom = icUmByUmIdFrom;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR", nullable=false, insertable=false, updatable=false)
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }

    
    @Column(name="UM_CNVT_FACT_ITEM", nullable=false, precision=13, scale=5)
    public BigDecimal getUmCnvtFactItem() {
        return this.umCnvtFactItem;
    }
    
    public void setUmCnvtFactItem(BigDecimal umCnvtFactItem) {
        this.umCnvtFactItem = umCnvtFactItem;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }




}


