package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IdlFcFcst generated by hbm2java
 */
@Entity
@Table(name="IDL_FC_FCST"
)
public class IdlFcFcst  implements java.io.Serializable {


     private int idlFcFcstNbr;
     private FcItemMast fcItemMast;
     private Date fcFcstDt;
     private BigDecimal adjFcst;

    public IdlFcFcst() {
    }

    public IdlFcFcst(int idlFcFcstNbr, FcItemMast fcItemMast, Date fcFcstDt, BigDecimal adjFcst) {
       this.idlFcFcstNbr = idlFcFcstNbr;
       this.fcItemMast = fcItemMast;
       this.fcFcstDt = fcFcstDt;
       this.adjFcst = adjFcst;
    }
   
     @Id 

    
    @Column(name="IDL_FC_FCST_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getIdlFcFcstNbr() {
        return this.idlFcFcstNbr;
    }
    
    public void setIdlFcFcstNbr(int idlFcFcstNbr) {
        this.idlFcFcstNbr = idlFcFcstNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FC_ITEM_MAST_NBR", nullable=false)
    public FcItemMast getFcItemMast() {
        return this.fcItemMast;
    }
    
    public void setFcItemMast(FcItemMast fcItemMast) {
        this.fcItemMast = fcItemMast;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FC_FCST_DT", nullable=false, length=7)
    public Date getFcFcstDt() {
        return this.fcFcstDt;
    }
    
    public void setFcFcstDt(Date fcFcstDt) {
        this.fcFcstDt = fcFcstDt;
    }

    
    @Column(name="ADJ_FCST", nullable=false, precision=22, scale=0)
    public BigDecimal getAdjFcst() {
        return this.adjFcst;
    }
    
    public void setAdjFcst(BigDecimal adjFcst) {
        this.adjFcst = adjFcst;
    }




}


