package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IdlFcAdj generated by hbm2java
 */
@Entity
@Table(name="IDL_FC_ADJ"
)
public class IdlFcAdj  implements java.io.Serializable {


     private IdlFcAdjId id;

    public IdlFcAdj() {
    }

    public IdlFcAdj(IdlFcAdjId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fcItemMastNbr", column=@Column(name="FC_ITEM_MAST_NBR", unique=true, precision=9, scale=0) ), 
        @AttributeOverride(name="itemCd", column=@Column(name="ITEM_CD", nullable=false, length=50) ), 
        @AttributeOverride(name="fcstGrp", column=@Column(name="FCST_GRP", nullable=false, length=8) ), 
        @AttributeOverride(name="mnth1Adj", column=@Column(name="MNTH_1_ADJ", precision=22, scale=0) ), 
        @AttributeOverride(name="mnth2Adj", column=@Column(name="MNTH_2_ADJ", precision=22, scale=0) ), 
        @AttributeOverride(name="mnth3Adj", column=@Column(name="MNTH_3_ADJ", precision=22, scale=0) ), 
        @AttributeOverride(name="mnth4Adj", column=@Column(name="MNTH_4_ADJ", precision=22, scale=0) ), 
        @AttributeOverride(name="mnth5Adj", column=@Column(name="MNTH_5_ADJ", precision=22, scale=0) ), 
        @AttributeOverride(name="mnth6Adj", column=@Column(name="MNTH_6_ADJ", precision=22, scale=0) ), 
        @AttributeOverride(name="mnth7Adj", column=@Column(name="MNTH_7_ADJ", precision=22, scale=0) ), 
        @AttributeOverride(name="mnth8Adj", column=@Column(name="MNTH_8_ADJ", precision=22, scale=0) ), 
        @AttributeOverride(name="mnth9Adj", column=@Column(name="MNTH_9_ADJ", precision=22, scale=0) ), 
        @AttributeOverride(name="mnth10Adj", column=@Column(name="MNTH_10_ADJ", precision=22, scale=0) ), 
        @AttributeOverride(name="mnth11Adj", column=@Column(name="MNTH_11_ADJ", precision=22, scale=0) ), 
        @AttributeOverride(name="mnth12Adj", column=@Column(name="MNTH_12_ADJ", precision=22, scale=0) ), 
        @AttributeOverride(name="prodLine", column=@Column(name="PROD_LINE", length=20) ), 
        @AttributeOverride(name="style", column=@Column(name="STYLE", length=20) ), 
        @AttributeOverride(name="color", column=@Column(name="COLOR", length=20) ), 
        @AttributeOverride(name="sz", column=@Column(name="SZ", length=20) ), 
        @AttributeOverride(name="statusId", column=@Column(name="STATUS_ID", length=10) ) } )
    public IdlFcAdjId getId() {
        return this.id;
    }
    
    public void setId(IdlFcAdjId id) {
        this.id = id;
    }




}


