package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IdlIcItemLoc generated by hbm2java
 */
@Entity
@Table(name="IDL_IC_ITEM_LOC"
)
public class IdlIcItemLoc  implements java.io.Serializable {


     private int idlIcItemLocNbr;
     private String itemCd;
     private String itemDescr;
     private String stkUm;
     private BigDecimal qtyOnHand;
     private String facility;
     private String splyPoolCd;
     private String binCd;
     private Date rcptDt;
     private String orgCdVnd;
     private String orgCdMfr;
     private String rcptDtTxt;

    public IdlIcItemLoc() {
    }

	
    public IdlIcItemLoc(int idlIcItemLocNbr, String itemCd, BigDecimal qtyOnHand) {
        this.idlIcItemLocNbr = idlIcItemLocNbr;
        this.itemCd = itemCd;
        this.qtyOnHand = qtyOnHand;
    }
    public IdlIcItemLoc(int idlIcItemLocNbr, String itemCd, String itemDescr, String stkUm, BigDecimal qtyOnHand, String facility, String splyPoolCd, String binCd, Date rcptDt, String orgCdVnd, String orgCdMfr, String rcptDtTxt) {
       this.idlIcItemLocNbr = idlIcItemLocNbr;
       this.itemCd = itemCd;
       this.itemDescr = itemDescr;
       this.stkUm = stkUm;
       this.qtyOnHand = qtyOnHand;
       this.facility = facility;
       this.splyPoolCd = splyPoolCd;
       this.binCd = binCd;
       this.rcptDt = rcptDt;
       this.orgCdVnd = orgCdVnd;
       this.orgCdMfr = orgCdMfr;
       this.rcptDtTxt = rcptDtTxt;
    }
   
     @Id 

    
    @Column(name="IDL_IC_ITEM_LOC_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getIdlIcItemLocNbr() {
        return this.idlIcItemLocNbr;
    }
    
    public void setIdlIcItemLocNbr(int idlIcItemLocNbr) {
        this.idlIcItemLocNbr = idlIcItemLocNbr;
    }

    
    @Column(name="ITEM_CD", nullable=false, length=50)
    public String getItemCd() {
        return this.itemCd;
    }
    
    public void setItemCd(String itemCd) {
        this.itemCd = itemCd;
    }

    
    @Column(name="ITEM_DESCR", length=50)
    public String getItemDescr() {
        return this.itemDescr;
    }
    
    public void setItemDescr(String itemDescr) {
        this.itemDescr = itemDescr;
    }

    
    @Column(name="STK_UM", length=3)
    public String getStkUm() {
        return this.stkUm;
    }
    
    public void setStkUm(String stkUm) {
        this.stkUm = stkUm;
    }

    
    @Column(name="QTY_ON_HAND", nullable=false, precision=22, scale=0)
    public BigDecimal getQtyOnHand() {
        return this.qtyOnHand;
    }
    
    public void setQtyOnHand(BigDecimal qtyOnHand) {
        this.qtyOnHand = qtyOnHand;
    }

    
    @Column(name="FACILITY", length=16)
    public String getFacility() {
        return this.facility;
    }
    
    public void setFacility(String facility) {
        this.facility = facility;
    }

    
    @Column(name="SPLY_POOL_CD", length=20)
    public String getSplyPoolCd() {
        return this.splyPoolCd;
    }
    
    public void setSplyPoolCd(String splyPoolCd) {
        this.splyPoolCd = splyPoolCd;
    }

    
    @Column(name="BIN_CD", length=16)
    public String getBinCd() {
        return this.binCd;
    }
    
    public void setBinCd(String binCd) {
        this.binCd = binCd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RCPT_DT", length=7)
    public Date getRcptDt() {
        return this.rcptDt;
    }
    
    public void setRcptDt(Date rcptDt) {
        this.rcptDt = rcptDt;
    }

    
    @Column(name="ORG_CD_VND", length=16)
    public String getOrgCdVnd() {
        return this.orgCdVnd;
    }
    
    public void setOrgCdVnd(String orgCdVnd) {
        this.orgCdVnd = orgCdVnd;
    }

    
    @Column(name="ORG_CD_MFR", length=16)
    public String getOrgCdMfr() {
        return this.orgCdMfr;
    }
    
    public void setOrgCdMfr(String orgCdMfr) {
        this.orgCdMfr = orgCdMfr;
    }

    
    @Column(name="RCPT_DT_TXT", length=16)
    public String getRcptDtTxt() {
        return this.rcptDtTxt;
    }
    
    public void setRcptDtTxt(String rcptDtTxt) {
        this.rcptDtTxt = rcptDtTxt;
    }




}


