package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IdlPoOrdDtl generated by hbm2java
 */
@Entity
@Table(name="IDL_PO_ORD_DTL"
)
public class IdlPoOrdDtl  implements java.io.Serializable {


     private int idlPoOrdDtlNbr;
     private String poCd;
     private String currCd;
     private Date poDt;
     private String orgCdVnd;
     private String poLineNbr;
     private String itemCd;
     private String replenUm;
     private BigDecimal unitCost;
     private BigDecimal replenQty;
     private Date replenCurrEstDt;
     private String deliveryFacility;
     private String deliverySplyPoolCd;
     private BigDecimal recvQty;
     private BigDecimal openQty;
     private String replenCurrEstDtTxt;
     private String poDtTxt;

    public IdlPoOrdDtl() {
    }

	
    public IdlPoOrdDtl(int idlPoOrdDtlNbr, String poCd, String orgCdVnd, String itemCd) {
        this.idlPoOrdDtlNbr = idlPoOrdDtlNbr;
        this.poCd = poCd;
        this.orgCdVnd = orgCdVnd;
        this.itemCd = itemCd;
    }
    public IdlPoOrdDtl(int idlPoOrdDtlNbr, String poCd, String currCd, Date poDt, String orgCdVnd, String poLineNbr, String itemCd, String replenUm, BigDecimal unitCost, BigDecimal replenQty, Date replenCurrEstDt, String deliveryFacility, String deliverySplyPoolCd, BigDecimal recvQty, BigDecimal openQty, String replenCurrEstDtTxt, String poDtTxt) {
       this.idlPoOrdDtlNbr = idlPoOrdDtlNbr;
       this.poCd = poCd;
       this.currCd = currCd;
       this.poDt = poDt;
       this.orgCdVnd = orgCdVnd;
       this.poLineNbr = poLineNbr;
       this.itemCd = itemCd;
       this.replenUm = replenUm;
       this.unitCost = unitCost;
       this.replenQty = replenQty;
       this.replenCurrEstDt = replenCurrEstDt;
       this.deliveryFacility = deliveryFacility;
       this.deliverySplyPoolCd = deliverySplyPoolCd;
       this.recvQty = recvQty;
       this.openQty = openQty;
       this.replenCurrEstDtTxt = replenCurrEstDtTxt;
       this.poDtTxt = poDtTxt;
    }
   
     @Id 

    
    @Column(name="IDL_PO_ORD_DTL_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getIdlPoOrdDtlNbr() {
        return this.idlPoOrdDtlNbr;
    }
    
    public void setIdlPoOrdDtlNbr(int idlPoOrdDtlNbr) {
        this.idlPoOrdDtlNbr = idlPoOrdDtlNbr;
    }

    
    @Column(name="PO_CD", nullable=false, length=20)
    public String getPoCd() {
        return this.poCd;
    }
    
    public void setPoCd(String poCd) {
        this.poCd = poCd;
    }

    
    @Column(name="CURR_CD", length=3)
    public String getCurrCd() {
        return this.currCd;
    }
    
    public void setCurrCd(String currCd) {
        this.currCd = currCd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PO_DT", length=7)
    public Date getPoDt() {
        return this.poDt;
    }
    
    public void setPoDt(Date poDt) {
        this.poDt = poDt;
    }

    
    @Column(name="ORG_CD_VND", nullable=false, length=16)
    public String getOrgCdVnd() {
        return this.orgCdVnd;
    }
    
    public void setOrgCdVnd(String orgCdVnd) {
        this.orgCdVnd = orgCdVnd;
    }

    
    @Column(name="PO_LINE_NBR", length=5)
    public String getPoLineNbr() {
        return this.poLineNbr;
    }
    
    public void setPoLineNbr(String poLineNbr) {
        this.poLineNbr = poLineNbr;
    }

    
    @Column(name="ITEM_CD", nullable=false, length=50)
    public String getItemCd() {
        return this.itemCd;
    }
    
    public void setItemCd(String itemCd) {
        this.itemCd = itemCd;
    }

    
    @Column(name="REPLEN_UM", length=3)
    public String getReplenUm() {
        return this.replenUm;
    }
    
    public void setReplenUm(String replenUm) {
        this.replenUm = replenUm;
    }

    
    @Column(name="UNIT_COST", precision=22, scale=0)
    public BigDecimal getUnitCost() {
        return this.unitCost;
    }
    
    public void setUnitCost(BigDecimal unitCost) {
        this.unitCost = unitCost;
    }

    
    @Column(name="REPLEN_QTY", precision=22, scale=0)
    public BigDecimal getReplenQty() {
        return this.replenQty;
    }
    
    public void setReplenQty(BigDecimal replenQty) {
        this.replenQty = replenQty;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="REPLEN_CURR_EST_DT", length=7)
    public Date getReplenCurrEstDt() {
        return this.replenCurrEstDt;
    }
    
    public void setReplenCurrEstDt(Date replenCurrEstDt) {
        this.replenCurrEstDt = replenCurrEstDt;
    }

    
    @Column(name="DELIVERY_FACILITY", length=16)
    public String getDeliveryFacility() {
        return this.deliveryFacility;
    }
    
    public void setDeliveryFacility(String deliveryFacility) {
        this.deliveryFacility = deliveryFacility;
    }

    
    @Column(name="DELIVERY_SPLY_POOL_CD", length=20)
    public String getDeliverySplyPoolCd() {
        return this.deliverySplyPoolCd;
    }
    
    public void setDeliverySplyPoolCd(String deliverySplyPoolCd) {
        this.deliverySplyPoolCd = deliverySplyPoolCd;
    }

    
    @Column(name="RECV_QTY", precision=22, scale=0)
    public BigDecimal getRecvQty() {
        return this.recvQty;
    }
    
    public void setRecvQty(BigDecimal recvQty) {
        this.recvQty = recvQty;
    }

    
    @Column(name="OPEN_QTY", precision=22, scale=0)
    public BigDecimal getOpenQty() {
        return this.openQty;
    }
    
    public void setOpenQty(BigDecimal openQty) {
        this.openQty = openQty;
    }

    
    @Column(name="REPLEN_CURR_EST_DT_TXT", length=16)
    public String getReplenCurrEstDtTxt() {
        return this.replenCurrEstDtTxt;
    }
    
    public void setReplenCurrEstDtTxt(String replenCurrEstDtTxt) {
        this.replenCurrEstDtTxt = replenCurrEstDtTxt;
    }

    
    @Column(name="PO_DT_TXT", length=16)
    public String getPoDtTxt() {
        return this.poDtTxt;
    }
    
    public void setPoDtTxt(String poDtTxt) {
        this.poDtTxt = poDtTxt;
    }




}


