package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IdlSoHistDtlId generated by hbm2java
 */
@Embeddable
public class IdlSoHistDtlId  implements java.io.Serializable {


     private String salesOrderNumber;
     private String customerNumber;
     private String salespersonCode;
     private String itemCd;
     private BigDecimal qtyOrdered;
     private BigDecimal unitPrice;
     private BigDecimal avgCost;
     private String prodLine;
     private String style;
     private String color;
     private String sz;
     private Date orderDt;
     private Date startShipDt;

    public IdlSoHistDtlId() {
    }

    public IdlSoHistDtlId(String salesOrderNumber, String customerNumber, String salespersonCode, String itemCd, BigDecimal qtyOrdered, BigDecimal unitPrice, BigDecimal avgCost, String prodLine, String style, String color, String sz, Date orderDt, Date startShipDt) {
       this.salesOrderNumber = salesOrderNumber;
       this.customerNumber = customerNumber;
       this.salespersonCode = salespersonCode;
       this.itemCd = itemCd;
       this.qtyOrdered = qtyOrdered;
       this.unitPrice = unitPrice;
       this.avgCost = avgCost;
       this.prodLine = prodLine;
       this.style = style;
       this.color = color;
       this.sz = sz;
       this.orderDt = orderDt;
       this.startShipDt = startShipDt;
    }
   


    @Column(name="SALES_ORDER_NUMBER", length=16)
    public String getSalesOrderNumber() {
        return this.salesOrderNumber;
    }
    
    public void setSalesOrderNumber(String salesOrderNumber) {
        this.salesOrderNumber = salesOrderNumber;
    }


    @Column(name="CUSTOMER_NUMBER", length=16)
    public String getCustomerNumber() {
        return this.customerNumber;
    }
    
    public void setCustomerNumber(String customerNumber) {
        this.customerNumber = customerNumber;
    }


    @Column(name="SALESPERSON_CODE", length=16)
    public String getSalespersonCode() {
        return this.salespersonCode;
    }
    
    public void setSalespersonCode(String salespersonCode) {
        this.salespersonCode = salespersonCode;
    }


    @Column(name="ITEM_CD", length=50)
    public String getItemCd() {
        return this.itemCd;
    }
    
    public void setItemCd(String itemCd) {
        this.itemCd = itemCd;
    }


    @Column(name="QTY_ORDERED", precision=22, scale=0)
    public BigDecimal getQtyOrdered() {
        return this.qtyOrdered;
    }
    
    public void setQtyOrdered(BigDecimal qtyOrdered) {
        this.qtyOrdered = qtyOrdered;
    }


    @Column(name="UNIT_PRICE", precision=22, scale=0)
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }


    @Column(name="AVG_COST", precision=22, scale=0)
    public BigDecimal getAvgCost() {
        return this.avgCost;
    }
    
    public void setAvgCost(BigDecimal avgCost) {
        this.avgCost = avgCost;
    }


    @Column(name="PROD_LINE", length=5)
    public String getProdLine() {
        return this.prodLine;
    }
    
    public void setProdLine(String prodLine) {
        this.prodLine = prodLine;
    }


    @Column(name="STYLE", length=20)
    public String getStyle() {
        return this.style;
    }
    
    public void setStyle(String style) {
        this.style = style;
    }


    @Column(name="COLOR", length=10)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }


    @Column(name="SZ", length=10)
    public String getSz() {
        return this.sz;
    }
    
    public void setSz(String sz) {
        this.sz = sz;
    }


    @Column(name="ORDER_DT", length=7)
    public Date getOrderDt() {
        return this.orderDt;
    }
    
    public void setOrderDt(Date orderDt) {
        this.orderDt = orderDt;
    }


    @Column(name="START_SHIP_DT", length=7)
    public Date getStartShipDt() {
        return this.startShipDt;
    }
    
    public void setStartShipDt(Date startShipDt) {
        this.startShipDt = startShipDt;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IdlSoHistDtlId) ) return false;
		 IdlSoHistDtlId castOther = ( IdlSoHistDtlId ) other; 
         
		 return ( (this.getSalesOrderNumber()==castOther.getSalesOrderNumber()) || ( this.getSalesOrderNumber()!=null && castOther.getSalesOrderNumber()!=null && this.getSalesOrderNumber().equals(castOther.getSalesOrderNumber()) ) )
 && ( (this.getCustomerNumber()==castOther.getCustomerNumber()) || ( this.getCustomerNumber()!=null && castOther.getCustomerNumber()!=null && this.getCustomerNumber().equals(castOther.getCustomerNumber()) ) )
 && ( (this.getSalespersonCode()==castOther.getSalespersonCode()) || ( this.getSalespersonCode()!=null && castOther.getSalespersonCode()!=null && this.getSalespersonCode().equals(castOther.getSalespersonCode()) ) )
 && ( (this.getItemCd()==castOther.getItemCd()) || ( this.getItemCd()!=null && castOther.getItemCd()!=null && this.getItemCd().equals(castOther.getItemCd()) ) )
 && ( (this.getQtyOrdered()==castOther.getQtyOrdered()) || ( this.getQtyOrdered()!=null && castOther.getQtyOrdered()!=null && this.getQtyOrdered().equals(castOther.getQtyOrdered()) ) )
 && ( (this.getUnitPrice()==castOther.getUnitPrice()) || ( this.getUnitPrice()!=null && castOther.getUnitPrice()!=null && this.getUnitPrice().equals(castOther.getUnitPrice()) ) )
 && ( (this.getAvgCost()==castOther.getAvgCost()) || ( this.getAvgCost()!=null && castOther.getAvgCost()!=null && this.getAvgCost().equals(castOther.getAvgCost()) ) )
 && ( (this.getProdLine()==castOther.getProdLine()) || ( this.getProdLine()!=null && castOther.getProdLine()!=null && this.getProdLine().equals(castOther.getProdLine()) ) )
 && ( (this.getStyle()==castOther.getStyle()) || ( this.getStyle()!=null && castOther.getStyle()!=null && this.getStyle().equals(castOther.getStyle()) ) )
 && ( (this.getColor()==castOther.getColor()) || ( this.getColor()!=null && castOther.getColor()!=null && this.getColor().equals(castOther.getColor()) ) )
 && ( (this.getSz()==castOther.getSz()) || ( this.getSz()!=null && castOther.getSz()!=null && this.getSz().equals(castOther.getSz()) ) )
 && ( (this.getOrderDt()==castOther.getOrderDt()) || ( this.getOrderDt()!=null && castOther.getOrderDt()!=null && this.getOrderDt().equals(castOther.getOrderDt()) ) )
 && ( (this.getStartShipDt()==castOther.getStartShipDt()) || ( this.getStartShipDt()!=null && castOther.getStartShipDt()!=null && this.getStartShipDt().equals(castOther.getStartShipDt()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSalesOrderNumber() == null ? 0 : this.getSalesOrderNumber().hashCode() );
         result = 37 * result + ( getCustomerNumber() == null ? 0 : this.getCustomerNumber().hashCode() );
         result = 37 * result + ( getSalespersonCode() == null ? 0 : this.getSalespersonCode().hashCode() );
         result = 37 * result + ( getItemCd() == null ? 0 : this.getItemCd().hashCode() );
         result = 37 * result + ( getQtyOrdered() == null ? 0 : this.getQtyOrdered().hashCode() );
         result = 37 * result + ( getUnitPrice() == null ? 0 : this.getUnitPrice().hashCode() );
         result = 37 * result + ( getAvgCost() == null ? 0 : this.getAvgCost().hashCode() );
         result = 37 * result + ( getProdLine() == null ? 0 : this.getProdLine().hashCode() );
         result = 37 * result + ( getStyle() == null ? 0 : this.getStyle().hashCode() );
         result = 37 * result + ( getColor() == null ? 0 : this.getColor().hashCode() );
         result = 37 * result + ( getSz() == null ? 0 : this.getSz().hashCode() );
         result = 37 * result + ( getOrderDt() == null ? 0 : this.getOrderDt().hashCode() );
         result = 37 * result + ( getStartShipDt() == null ? 0 : this.getStartShipDt().hashCode() );
         return result;
   }   


}


