package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IdlSoHistDtl generated by hbm2java
 */
@Entity
@Table(name="IDL_SO_HIST_DTL"
)
public class IdlSoHistDtl  implements java.io.Serializable {


     private IdlSoHistDtlId id;

    public IdlSoHistDtl() {
    }

    public IdlSoHistDtl(IdlSoHistDtlId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="salesOrderNumber", column=@Column(name="SALES_ORDER_NUMBER", length=16) ), 
        @AttributeOverride(name="customerNumber", column=@Column(name="CUSTOMER_NUMBER", length=16) ), 
        @AttributeOverride(name="salespersonCode", column=@Column(name="SALESPERSON_CODE", length=16) ), 
        @AttributeOverride(name="itemCd", column=@Column(name="ITEM_CD", length=50) ), 
        @AttributeOverride(name="qtyOrdered", column=@Column(name="QTY_ORDERED", precision=22, scale=0) ), 
        @AttributeOverride(name="unitPrice", column=@Column(name="UNIT_PRICE", precision=22, scale=0) ), 
        @AttributeOverride(name="avgCost", column=@Column(name="AVG_COST", precision=22, scale=0) ), 
        @AttributeOverride(name="prodLine", column=@Column(name="PROD_LINE", length=5) ), 
        @AttributeOverride(name="style", column=@Column(name="STYLE", length=20) ), 
        @AttributeOverride(name="color", column=@Column(name="COLOR", length=10) ), 
        @AttributeOverride(name="sz", column=@Column(name="SZ", length=10) ), 
        @AttributeOverride(name="orderDt", column=@Column(name="ORDER_DT", length=7) ), 
        @AttributeOverride(name="startShipDt", column=@Column(name="START_SHIP_DT", length=7) ) } )
    public IdlSoHistDtlId getId() {
        return this.id;
    }
    
    public void setId(IdlSoHistDtlId id) {
        this.id = id;
    }




}


