package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ItemTmp3 generated by hbm2java
 */
@Entity
@Table(name="ITEM_TMP3"
)
public class ItemTmp3  implements java.io.Serializable {


     private ItemTmp3Id id;

    public ItemTmp3() {
    }

    public ItemTmp3(ItemTmp3Id id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="itemCd", column=@Column(name="ITEM_CD", length=50) ), 
        @AttributeOverride(name="style", column=@Column(name="STYLE", length=20) ), 
        @AttributeOverride(name="color", column=@Column(name="COLOR", length=20) ), 
        @AttributeOverride(name="sz", column=@Column(name="SZ", length=20) ), 
        @AttributeOverride(name="prodLine", column=@Column(name="PROD_LINE", length=20) ), 
        @AttributeOverride(name="status", column=@Column(name="STATUS", length=10) ), 
        @AttributeOverride(name="season", column=@Column(name="SEASON", length=20) ), 
        @AttributeOverride(name="neverOut", column=@Column(name="NEVER_OUT", length=10) ) } )
    public ItemTmp3Id getId() {
        return this.id;
    }
    
    public void setId(ItemTmp3Id id) {
        this.id = id;
    }




}


