package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MissingItems generated by hbm2java
 */
@Entity
@Table(name="MISSING_ITEMS"
)
public class MissingItems  implements java.io.Serializable {


     private MissingItemsId id;

    public MissingItems() {
    }

    public MissingItems(MissingItemsId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="itemCd", column=@Column(name="ITEM_CD", nullable=false, length=50) ) } )
    public MissingItemsId getId() {
        return this.id;
    }
    
    public void setId(MissingItemsId id) {
        this.id = id;
    }




}


