package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaIndiv generated by hbm2java
 */
@Entity
@Table(name="NA_INDIV"
)
public class NaIndiv  implements java.io.Serializable {


     private int indivNbr;
     private String sortNm;
     private String firstNm;
     private String middleInit;
     private String lastNm;
     private String salutationCd;
     private int utUserNbr;
     private Date lastModDt;
     private String indivDescr;
     private String phnNbrDflt;
     private String faxNbrDflt;
     private String emailAddrDflt;
//     private Set<PoVndMast> poVndMastsForBuyIndivNbr = new HashSet<PoVndMast>(0);
//     private Set<PoOrdHdr> poOrdHdrs = new HashSet<PoOrdHdr>(0);
//     private Set<IcItemMast> icItemMasts = new HashSet<IcItemMast>(0);
//     private Set<NaOrgIndiv> naOrgIndivs = new HashSet<NaOrgIndiv>(0);
//     private Set<OeCustMast> oeCustMastsForSellIndivNbr = new HashSet<OeCustMast>(0);
//     private Set<PoVndMast> poVndMastsForIndivNbrVndContact = new HashSet<PoVndMast>(0);
     private Set<UtUser> utUsers = new HashSet<UtUser>(0);
//     private Set<OeCustMast> oeCustMastsForIndivNbrCustContact = new HashSet<OeCustMast>(0);
//     private Set<OeOrdHdr> oeOrdHdrs = new HashSet<OeOrdHdr>(0);
//     private Set<ArInvHdr> arInvHdrs = new HashSet<ArInvHdr>(0);

    public NaIndiv() {
    }

	
  
     @Id 

    
    @Column(name="INDIV_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getIndivNbr() {
        return this.indivNbr;
    }
    
    public void setIndivNbr(int indivNbr) {
        this.indivNbr = indivNbr;
    }

    
    @Column(name="SORT_NM", nullable=false, length=41)
    public String getSortNm() {
        return this.sortNm;
    }
    
    public void setSortNm(String sortNm) {
        this.sortNm = sortNm;
    }

    
    @Column(name="FIRST_NM", nullable=false, length=20)
    public String getFirstNm() {
        return this.firstNm;
    }
    
    public void setFirstNm(String firstNm) {
        this.firstNm = firstNm;
    }

    
    @Column(name="MIDDLE_INIT", length=1)
    public String getMiddleInit() {
        return this.middleInit;
    }
    
    public void setMiddleInit(String middleInit) {
        this.middleInit = middleInit;
    }

    
    @Column(name="LAST_NM", nullable=false, length=20)
    public String getLastNm() {
        return this.lastNm;
    }
    
    public void setLastNm(String lastNm) {
        this.lastNm = lastNm;
    }

    
    @Column(name="SALUTATION_CD", length=4)
    public String getSalutationCd() {
        return this.salutationCd;
    }
    
    public void setSalutationCd(String salutationCd) {
        this.salutationCd = salutationCd;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }

    
    @Column(name="INDIV_DESCR", length=40)
    public String getIndivDescr() {
        return this.indivDescr;
    }
    
    public void setIndivDescr(String indivDescr) {
        this.indivDescr = indivDescr;
    }

    
    @Column(name="PHN_NBR_DFLT", length=20)
    public String getPhnNbrDflt() {
        return this.phnNbrDflt;
    }
    
    public void setPhnNbrDflt(String phnNbrDflt) {
        this.phnNbrDflt = phnNbrDflt;
    }

    
    @Column(name="FAX_NBR_DFLT", length=20)
    public String getFaxNbrDflt() {
        return this.faxNbrDflt;
    }
    
    public void setFaxNbrDflt(String faxNbrDflt) {
        this.faxNbrDflt = faxNbrDflt;
    }

    
    @Column(name="EMAIL_ADDR_DFLT", length=200)
    public String getEmailAddrDflt() {
        return this.emailAddrDflt;
    }
    
    public void setEmailAddrDflt(String emailAddrDflt) {
        this.emailAddrDflt = emailAddrDflt;
    }



}


