package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NaIndivNmCompressedVwId generated by hbm2java
 */
@Embeddable
public class NaIndivNmCompressedVwId  implements java.io.Serializable {


     private String indivNm;
     private String indivDescr;
     private int indivNbr;
     private String phnNbrDflt;
     private String faxNbrDflt;
     private String emailAddrDflt;

    public NaIndivNmCompressedVwId() {
    }

	
    public NaIndivNmCompressedVwId(int indivNbr) {
        this.indivNbr = indivNbr;
    }
    public NaIndivNmCompressedVwId(String indivNm, String indivDescr, int indivNbr, String phnNbrDflt, String faxNbrDflt, String emailAddrDflt) {
       this.indivNm = indivNm;
       this.indivDescr = indivDescr;
       this.indivNbr = indivNbr;
       this.phnNbrDflt = phnNbrDflt;
       this.faxNbrDflt = faxNbrDflt;
       this.emailAddrDflt = emailAddrDflt;
    }
   


    @Column(name="INDIV_NM", length=44)
    public String getIndivNm() {
        return this.indivNm;
    }
    
    public void setIndivNm(String indivNm) {
        this.indivNm = indivNm;
    }


    @Column(name="INDIV_DESCR", length=40)
    public String getIndivDescr() {
        return this.indivDescr;
    }
    
    public void setIndivDescr(String indivDescr) {
        this.indivDescr = indivDescr;
    }


    @Column(name="INDIV_NBR", nullable=false, precision=9, scale=0)
    public int getIndivNbr() {
        return this.indivNbr;
    }
    
    public void setIndivNbr(int indivNbr) {
        this.indivNbr = indivNbr;
    }


    @Column(name="PHN_NBR_DFLT", length=20)
    public String getPhnNbrDflt() {
        return this.phnNbrDflt;
    }
    
    public void setPhnNbrDflt(String phnNbrDflt) {
        this.phnNbrDflt = phnNbrDflt;
    }


    @Column(name="FAX_NBR_DFLT", length=20)
    public String getFaxNbrDflt() {
        return this.faxNbrDflt;
    }
    
    public void setFaxNbrDflt(String faxNbrDflt) {
        this.faxNbrDflt = faxNbrDflt;
    }


    @Column(name="EMAIL_ADDR_DFLT", length=200)
    public String getEmailAddrDflt() {
        return this.emailAddrDflt;
    }
    
    public void setEmailAddrDflt(String emailAddrDflt) {
        this.emailAddrDflt = emailAddrDflt;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NaIndivNmCompressedVwId) ) return false;
		 NaIndivNmCompressedVwId castOther = ( NaIndivNmCompressedVwId ) other; 
         
		 return ( (this.getIndivNm()==castOther.getIndivNm()) || ( this.getIndivNm()!=null && castOther.getIndivNm()!=null && this.getIndivNm().equals(castOther.getIndivNm()) ) )
 && ( (this.getIndivDescr()==castOther.getIndivDescr()) || ( this.getIndivDescr()!=null && castOther.getIndivDescr()!=null && this.getIndivDescr().equals(castOther.getIndivDescr()) ) )
 && (this.getIndivNbr()==castOther.getIndivNbr())
 && ( (this.getPhnNbrDflt()==castOther.getPhnNbrDflt()) || ( this.getPhnNbrDflt()!=null && castOther.getPhnNbrDflt()!=null && this.getPhnNbrDflt().equals(castOther.getPhnNbrDflt()) ) )
 && ( (this.getFaxNbrDflt()==castOther.getFaxNbrDflt()) || ( this.getFaxNbrDflt()!=null && castOther.getFaxNbrDflt()!=null && this.getFaxNbrDflt().equals(castOther.getFaxNbrDflt()) ) )
 && ( (this.getEmailAddrDflt()==castOther.getEmailAddrDflt()) || ( this.getEmailAddrDflt()!=null && castOther.getEmailAddrDflt()!=null && this.getEmailAddrDflt().equals(castOther.getEmailAddrDflt()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIndivNm() == null ? 0 : this.getIndivNm().hashCode() );
         result = 37 * result + ( getIndivDescr() == null ? 0 : this.getIndivDescr().hashCode() );
         result = 37 * result + this.getIndivNbr();
         result = 37 * result + ( getPhnNbrDflt() == null ? 0 : this.getPhnNbrDflt().hashCode() );
         result = 37 * result + ( getFaxNbrDflt() == null ? 0 : this.getFaxNbrDflt().hashCode() );
         result = 37 * result + ( getEmailAddrDflt() == null ? 0 : this.getEmailAddrDflt().hashCode() );
         return result;
   }   


}


