package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaOrg generated by hbm2java
 */
@Entity
@Table(name="NA_ORG"
)
public class NaOrg  implements java.io.Serializable {


     private int orgNbr;
     private CalCalendar calCalendar;
     private Currency currency;
     private String orgNm;
     private int utUserNbr;
     private Date lastModDt;
     private String orgWebSite;
     private String orgCd;
     private String phnNbrDflt;
     private String faxNbrDflt;
     private Integer utLocaleNbr;
  //   private PoMfrMast poMfrMast;
//     private Set<NaOrgIndiv> naOrgIndivs = new HashSet<NaOrgIndiv>(0);
//     private Set<UtUser> utUsers = new HashSet<UtUser>(0);
//     private Set<IcItemMastNomen> icItemMastNomens = new HashSet<IcItemMastNomen>(0);
//     private Set<OeOrdDtl> oeOrdDtls = new HashSet<OeOrdDtl>(0);
// //    private PoVndMast poVndMast;
     //private OeCustMast oeCustMast;
//     private Set<NaOrgAddr> naOrgAddrs = new HashSet<NaOrgAddr>(0);

    public NaOrg() {
    }

	
     @Id 

    
    @Column(name="ORG_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getOrgNbr() {
        return this.orgNbr;
    }
    
    public void setOrgNbr(int orgNbr) {
        this.orgNbr = orgNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CALENDAR", nullable=false)
    public CalCalendar getCalCalendar() {
        return this.calCalendar;
    }
    
    public void setCalCalendar(CalCalendar calCalendar) {
        this.calCalendar = calCalendar;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CURR_CD_DFLT")
    public Currency getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(Currency currency) {
        this.currency = currency;
    }

    
    @Column(name="ORG_NM", nullable=false, length=60)
    public String getOrgNm() {
        return this.orgNm;
    }
    
    public void setOrgNm(String orgNm) {
        this.orgNm = orgNm;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }

    
    @Column(name="ORG_WEB_SITE")
    public String getOrgWebSite() {
        return this.orgWebSite;
    }
    
    public void setOrgWebSite(String orgWebSite) {
        this.orgWebSite = orgWebSite;
    }

    
    @Column(name="ORG_CD", unique=true, nullable=false, length=15)
    public String getOrgCd() {
        return this.orgCd;
    }
    
    public void setOrgCd(String orgCd) {
        this.orgCd = orgCd;
    }

    
    @Column(name="PHN_NBR_DFLT", length=20)
    public String getPhnNbrDflt() {
        return this.phnNbrDflt;
    }
    
    public void setPhnNbrDflt(String phnNbrDflt) {
        this.phnNbrDflt = phnNbrDflt;
    }

    
    @Column(name="FAX_NBR_DFLT", length=20)
    public String getFaxNbrDflt() {
        return this.faxNbrDflt;
    }
    
    public void setFaxNbrDflt(String faxNbrDflt) {
        this.faxNbrDflt = faxNbrDflt;
    }

    
    @Column(name="UT_LOCALE_NBR", precision=9, scale=0)
    public Integer getUtLocaleNbr() {
        return this.utLocaleNbr;
    }
    
    public void setUtLocaleNbr(Integer utLocaleNbr) {
        this.utLocaleNbr = utLocaleNbr;
    }

//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrg")
//    public Set<NaOrgIndiv> getNaOrgIndivs() {
//        return this.naOrgIndivs;
//    }
//    
//    public void setNaOrgIndivs(Set<NaOrgIndiv> naOrgIndivs) {
//        this.naOrgIndivs = naOrgIndivs;
//    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrg")
//    public Set<UtUser> getUtUsers() {
//        return this.utUsers;
//    }
//    
//    public void setUtUsers(Set<UtUser> utUsers) {
//        this.utUsers = utUsers;
//    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrg")
//    public Set<IcItemMastNomen> getIcItemMastNomens() {
//        return this.icItemMastNomens;
//    }
//    
//    public void setIcItemMastNomens(Set<IcItemMastNomen> icItemMastNomens) {
//        this.icItemMastNomens = icItemMastNomens;
//    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrg")
//    public Set<OeOrdDtl> getOeOrdDtls() {
//        return this.oeOrdDtls;
//    }
//    
//    public void setOeOrdDtls(Set<OeOrdDtl> oeOrdDtls) {
//        this.oeOrdDtls = oeOrdDtls;
//    }

////@OneToOne(fetch=FetchType.LAZY, mappedBy="naOrg")
//    public PoVndMast getPoVndMast() {
//        return this.poVndMast;
//    }
//    
//    public void setPoVndMast(PoVndMast poVndMast) {
//        this.poVndMast = poVndMast;
//    }
//
////@OneToOne(fetch=FetchType.LAZY, mappedBy="naOrg")
//    public OeCustMast getOeCustMast() {
//        return this.oeCustMast;
//    }
//    
//    public void setOeCustMast(OeCustMast oeCustMast) {
//        this.oeCustMast = oeCustMast;
//    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrg")
//    public Set<NaOrgAddr> getNaOrgAddrs() {
//        return this.naOrgAddrs;
//    }
//    
//    public void setNaOrgAddrs(Set<NaOrgAddr> naOrgAddrs) {
//        this.naOrgAddrs = naOrgAddrs;
//    }
//



}


