package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaOrgAddr generated by hbm2java
 */
@Entity
@Table(name="NA_ORG_ADDR"
)
public class NaOrgAddr  implements java.io.Serializable {


     private int addrNbr;
     private CalCalendar calCalendar;
     private NaOrg naOrg;
     private String addrTypeId;
     private String addr1;
     private String addr2;
     private String addr3;
     private String city;
     private String stateCd;
     private String cntryCd;
     private String addrCd;
     private String addrDescr;
     private String roleNm;
     private Short pickPrty;
     private Byte pickPrtyPastDueMult;
     private Integer glTaxGrpNbr;
     private int utUserNbr;
     private Date lastModDt;
     private String postalCd;
     private String addrActiveId;
     private Integer apsSrcRuleSetNbr;
     private String phnNbrDflt;
     private String faxNbrDflt;
     private Integer indivNbrContactDflt;
     private String shipViaCdDflt;
     private Integer whShipPrtyNbrDflt;
     private String paymentMethodCdDflt;
     private Set<OeCustMast> oeCustMastsForBillToAddrNbrDflt = new HashSet<OeCustMast>(0);
     private Set<ArInvDtl> arInvDtls = new HashSet<ArInvDtl>(0);
     private Set<OeCustMast> oeCustMastsForShipToAddrNbrDflt = new HashSet<OeCustMast>(0);
     private Set<PoMfrMast> poMfrMastsForMailToAddrNbrDflt = new HashSet<PoMfrMast>(0);
     private Set<PoMfrMast> poMfrMastsForBillToAddrNbrDflt = new HashSet<PoMfrMast>(0);
     private Set<OeOrdHdr> oeOrdHdrsForBillToAddrNbr = new HashSet<OeOrdHdr>(0);
     private Set<PoLineDtl> poLineDtls = new HashSet<PoLineDtl>(0);
     private Set<PoOrdHdr> poOrdHdrsForShipToAddrNbrDflt = new HashSet<PoOrdHdr>(0);
     private Set<ArInvHdr> arInvHdrsForShipToAddrNbr = new HashSet<ArInvHdr>(0);
     private Set<ArInvHdr> arInvHdrsForBillToAddrNbr = new HashSet<ArInvHdr>(0);
     private Set<OeOrdHdr> oeOrdHdrsForShipToAddrNbrDflt = new HashSet<OeOrdHdr>(0);
     private Set<PoVndMast> poVndMastsForMailToAddrNbrDflt = new HashSet<PoVndMast>(0);
     private Set<PoVndMast> poVndMastsForBillToAddrNbrDflt = new HashSet<PoVndMast>(0);
     private Set<PoOrdHdr> poOrdHdrsForAddrNbrVnd = new HashSet<PoOrdHdr>(0);
     private Set<UtFacility> utFacilities = new HashSet<UtFacility>(0);
     private Set<OeOrdDtl> oeOrdDtls = new HashSet<OeOrdDtl>(0);

    public NaOrgAddr() {
    }

	
    public NaOrgAddr(int addrNbr, CalCalendar calCalendar, NaOrg naOrg, String addrTypeId, String addr1, String addrCd, int utUserNbr, Date lastModDt, String addrActiveId) {
        this.addrNbr = addrNbr;
        this.calCalendar = calCalendar;
        this.naOrg = naOrg;
        this.addrTypeId = addrTypeId;
        this.addr1 = addr1;
        this.addrCd = addrCd;
        this.utUserNbr = utUserNbr;
        this.lastModDt = lastModDt;
        this.addrActiveId = addrActiveId;
    }
    public NaOrgAddr(int addrNbr, CalCalendar calCalendar, NaOrg naOrg, String addrTypeId, String addr1, String addr2, String addr3, String city, String stateCd, String cntryCd, String addrCd, String addrDescr, String roleNm, Short pickPrty, Byte pickPrtyPastDueMult, Integer glTaxGrpNbr, int utUserNbr, Date lastModDt, String postalCd, String addrActiveId, Integer apsSrcRuleSetNbr, String phnNbrDflt, String faxNbrDflt, Integer indivNbrContactDflt, String shipViaCdDflt, Integer whShipPrtyNbrDflt, String paymentMethodCdDflt, Set<OeCustMast> oeCustMastsForBillToAddrNbrDflt, Set<ArInvDtl> arInvDtls, Set<OeCustMast> oeCustMastsForShipToAddrNbrDflt, Set<PoMfrMast> poMfrMastsForMailToAddrNbrDflt, Set<PoMfrMast> poMfrMastsForBillToAddrNbrDflt, Set<OeOrdHdr> oeOrdHdrsForBillToAddrNbr, Set<PoLineDtl> poLineDtls, Set<PoOrdHdr> poOrdHdrsForShipToAddrNbrDflt, Set<ArInvHdr> arInvHdrsForShipToAddrNbr, Set<ArInvHdr> arInvHdrsForBillToAddrNbr, Set<OeOrdHdr> oeOrdHdrsForShipToAddrNbrDflt, Set<PoVndMast> poVndMastsForMailToAddrNbrDflt, Set<PoVndMast> poVndMastsForBillToAddrNbrDflt, Set<PoOrdHdr> poOrdHdrsForAddrNbrVnd, Set<UtFacility> utFacilities, Set<OeOrdDtl> oeOrdDtls) {
       this.addrNbr = addrNbr;
       this.calCalendar = calCalendar;
       this.naOrg = naOrg;
       this.addrTypeId = addrTypeId;
       this.addr1 = addr1;
       this.addr2 = addr2;
       this.addr3 = addr3;
       this.city = city;
       this.stateCd = stateCd;
       this.cntryCd = cntryCd;
       this.addrCd = addrCd;
       this.addrDescr = addrDescr;
       this.roleNm = roleNm;
       this.pickPrty = pickPrty;
       this.pickPrtyPastDueMult = pickPrtyPastDueMult;
       this.glTaxGrpNbr = glTaxGrpNbr;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
       this.postalCd = postalCd;
       this.addrActiveId = addrActiveId;
       this.apsSrcRuleSetNbr = apsSrcRuleSetNbr;
       this.phnNbrDflt = phnNbrDflt;
       this.faxNbrDflt = faxNbrDflt;
       this.indivNbrContactDflt = indivNbrContactDflt;
       this.shipViaCdDflt = shipViaCdDflt;
       this.whShipPrtyNbrDflt = whShipPrtyNbrDflt;
       this.paymentMethodCdDflt = paymentMethodCdDflt;
       this.oeCustMastsForBillToAddrNbrDflt = oeCustMastsForBillToAddrNbrDflt;
       this.arInvDtls = arInvDtls;
       this.oeCustMastsForShipToAddrNbrDflt = oeCustMastsForShipToAddrNbrDflt;
       this.poMfrMastsForMailToAddrNbrDflt = poMfrMastsForMailToAddrNbrDflt;
       this.poMfrMastsForBillToAddrNbrDflt = poMfrMastsForBillToAddrNbrDflt;
       this.oeOrdHdrsForBillToAddrNbr = oeOrdHdrsForBillToAddrNbr;
       this.poLineDtls = poLineDtls;
       this.poOrdHdrsForShipToAddrNbrDflt = poOrdHdrsForShipToAddrNbrDflt;
       this.arInvHdrsForShipToAddrNbr = arInvHdrsForShipToAddrNbr;
       this.arInvHdrsForBillToAddrNbr = arInvHdrsForBillToAddrNbr;
       this.oeOrdHdrsForShipToAddrNbrDflt = oeOrdHdrsForShipToAddrNbrDflt;
       this.poVndMastsForMailToAddrNbrDflt = poVndMastsForMailToAddrNbrDflt;
       this.poVndMastsForBillToAddrNbrDflt = poVndMastsForBillToAddrNbrDflt;
       this.poOrdHdrsForAddrNbrVnd = poOrdHdrsForAddrNbrVnd;
       this.utFacilities = utFacilities;
       this.oeOrdDtls = oeOrdDtls;
    }
   
     @Id 

    
    @Column(name="ADDR_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getAddrNbr() {
        return this.addrNbr;
    }
    
    public void setAddrNbr(int addrNbr) {
        this.addrNbr = addrNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CALENDAR", nullable=false)
    public CalCalendar getCalCalendar() {
        return this.calCalendar;
    }
    
    public void setCalCalendar(CalCalendar calCalendar) {
        this.calCalendar = calCalendar;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORG_NBR", nullable=false)
    public NaOrg getNaOrg() {
        return this.naOrg;
    }
    
    public void setNaOrg(NaOrg naOrg) {
        this.naOrg = naOrg;
    }

    
    @Column(name="ADDR_TYPE_ID", nullable=false, length=4)
    public String getAddrTypeId() {
        return this.addrTypeId;
    }
    
    public void setAddrTypeId(String addrTypeId) {
        this.addrTypeId = addrTypeId;
    }

    
    @Column(name="ADDR_1", nullable=false, length=30)
    public String getAddr1() {
        return this.addr1;
    }
    
    public void setAddr1(String addr1) {
        this.addr1 = addr1;
    }

    
    @Column(name="ADDR_2", length=30)
    public String getAddr2() {
        return this.addr2;
    }
    
    public void setAddr2(String addr2) {
        this.addr2 = addr2;
    }

    
    @Column(name="ADDR_3", length=30)
    public String getAddr3() {
        return this.addr3;
    }
    
    public void setAddr3(String addr3) {
        this.addr3 = addr3;
    }

    
    @Column(name="CITY", length=25)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="STATE_CD", length=5)
    public String getStateCd() {
        return this.stateCd;
    }
    
    public void setStateCd(String stateCd) {
        this.stateCd = stateCd;
    }

    
    @Column(name="CNTRY_CD", length=3)
    public String getCntryCd() {
        return this.cntryCd;
    }
    
    public void setCntryCd(String cntryCd) {
        this.cntryCd = cntryCd;
    }

    
    @Column(name="ADDR_CD", nullable=false, length=8)
    public String getAddrCd() {
        return this.addrCd;
    }
    
    public void setAddrCd(String addrCd) {
        this.addrCd = addrCd;
    }

    
    @Column(name="ADDR_DESCR", length=60)
    public String getAddrDescr() {
        return this.addrDescr;
    }
    
    public void setAddrDescr(String addrDescr) {
        this.addrDescr = addrDescr;
    }

    
    @Column(name="ROLE_NM", length=30)
    public String getRoleNm() {
        return this.roleNm;
    }
    
    public void setRoleNm(String roleNm) {
        this.roleNm = roleNm;
    }

    
    @Column(name="PICK_PRTY", precision=3, scale=0)
    public Short getPickPrty() {
        return this.pickPrty;
    }
    
    public void setPickPrty(Short pickPrty) {
        this.pickPrty = pickPrty;
    }

    
    @Column(name="PICK_PRTY_PAST_DUE_MULT", precision=2, scale=0)
    public Byte getPickPrtyPastDueMult() {
        return this.pickPrtyPastDueMult;
    }
    
    public void setPickPrtyPastDueMult(Byte pickPrtyPastDueMult) {
        this.pickPrtyPastDueMult = pickPrtyPastDueMult;
    }

    
    @Column(name="GL_TAX_GRP_NBR", precision=9, scale=0)
    public Integer getGlTaxGrpNbr() {
        return this.glTaxGrpNbr;
    }
    
    public void setGlTaxGrpNbr(Integer glTaxGrpNbr) {
        this.glTaxGrpNbr = glTaxGrpNbr;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }

    
    @Column(name="POSTAL_CD", length=10)
    public String getPostalCd() {
        return this.postalCd;
    }
    
    public void setPostalCd(String postalCd) {
        this.postalCd = postalCd;
    }

    
    @Column(name="ADDR_ACTIVE_ID", nullable=false, length=1)
    public String getAddrActiveId() {
        return this.addrActiveId;
    }
    
    public void setAddrActiveId(String addrActiveId) {
        this.addrActiveId = addrActiveId;
    }

    
    @Column(name="APS_SRC_RULE_SET_NBR", precision=9, scale=0)
    public Integer getApsSrcRuleSetNbr() {
        return this.apsSrcRuleSetNbr;
    }
    
    public void setApsSrcRuleSetNbr(Integer apsSrcRuleSetNbr) {
        this.apsSrcRuleSetNbr = apsSrcRuleSetNbr;
    }

    
    @Column(name="PHN_NBR_DFLT", length=20)
    public String getPhnNbrDflt() {
        return this.phnNbrDflt;
    }
    
    public void setPhnNbrDflt(String phnNbrDflt) {
        this.phnNbrDflt = phnNbrDflt;
    }

    
    @Column(name="FAX_NBR_DFLT", length=20)
    public String getFaxNbrDflt() {
        return this.faxNbrDflt;
    }
    
    public void setFaxNbrDflt(String faxNbrDflt) {
        this.faxNbrDflt = faxNbrDflt;
    }

    
    @Column(name="INDIV_NBR_CONTACT_DFLT", precision=9, scale=0)
    public Integer getIndivNbrContactDflt() {
        return this.indivNbrContactDflt;
    }
    
    public void setIndivNbrContactDflt(Integer indivNbrContactDflt) {
        this.indivNbrContactDflt = indivNbrContactDflt;
    }

    
    @Column(name="SHIP_VIA_CD_DFLT", length=8)
    public String getShipViaCdDflt() {
        return this.shipViaCdDflt;
    }
    
    public void setShipViaCdDflt(String shipViaCdDflt) {
        this.shipViaCdDflt = shipViaCdDflt;
    }

    
    @Column(name="WH_SHIP_PRTY_NBR_DFLT", precision=5, scale=0)
    public Integer getWhShipPrtyNbrDflt() {
        return this.whShipPrtyNbrDflt;
    }
    
    public void setWhShipPrtyNbrDflt(Integer whShipPrtyNbrDflt) {
        this.whShipPrtyNbrDflt = whShipPrtyNbrDflt;
    }

    
    @Column(name="PAYMENT_METHOD_CD_DFLT", length=3)
    public String getPaymentMethodCdDflt() {
        return this.paymentMethodCdDflt;
    }
    
    public void setPaymentMethodCdDflt(String paymentMethodCdDflt) {
        this.paymentMethodCdDflt = paymentMethodCdDflt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrgAddrByBillToAddrNbrDflt")
    public Set<OeCustMast> getOeCustMastsForBillToAddrNbrDflt() {
        return this.oeCustMastsForBillToAddrNbrDflt;
    }
    
    public void setOeCustMastsForBillToAddrNbrDflt(Set<OeCustMast> oeCustMastsForBillToAddrNbrDflt) {
        this.oeCustMastsForBillToAddrNbrDflt = oeCustMastsForBillToAddrNbrDflt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrgAddr")
    public Set<ArInvDtl> getArInvDtls() {
        return this.arInvDtls;
    }
    
    public void setArInvDtls(Set<ArInvDtl> arInvDtls) {
        this.arInvDtls = arInvDtls;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrgAddrByShipToAddrNbrDflt")
    public Set<OeCustMast> getOeCustMastsForShipToAddrNbrDflt() {
        return this.oeCustMastsForShipToAddrNbrDflt;
    }
    
    public void setOeCustMastsForShipToAddrNbrDflt(Set<OeCustMast> oeCustMastsForShipToAddrNbrDflt) {
        this.oeCustMastsForShipToAddrNbrDflt = oeCustMastsForShipToAddrNbrDflt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrgAddrByMailToAddrNbrDflt")
    public Set<PoMfrMast> getPoMfrMastsForMailToAddrNbrDflt() {
        return this.poMfrMastsForMailToAddrNbrDflt;
    }
    
    public void setPoMfrMastsForMailToAddrNbrDflt(Set<PoMfrMast> poMfrMastsForMailToAddrNbrDflt) {
        this.poMfrMastsForMailToAddrNbrDflt = poMfrMastsForMailToAddrNbrDflt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrgAddrByBillToAddrNbrDflt")
    public Set<PoMfrMast> getPoMfrMastsForBillToAddrNbrDflt() {
        return this.poMfrMastsForBillToAddrNbrDflt;
    }
    
    public void setPoMfrMastsForBillToAddrNbrDflt(Set<PoMfrMast> poMfrMastsForBillToAddrNbrDflt) {
        this.poMfrMastsForBillToAddrNbrDflt = poMfrMastsForBillToAddrNbrDflt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrgAddrByBillToAddrNbr")
    public Set<OeOrdHdr> getOeOrdHdrsForBillToAddrNbr() {
        return this.oeOrdHdrsForBillToAddrNbr;
    }
    
    public void setOeOrdHdrsForBillToAddrNbr(Set<OeOrdHdr> oeOrdHdrsForBillToAddrNbr) {
        this.oeOrdHdrsForBillToAddrNbr = oeOrdHdrsForBillToAddrNbr;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrgAddr")
    public Set<PoLineDtl> getPoLineDtls() {
        return this.poLineDtls;
    }
    
    public void setPoLineDtls(Set<PoLineDtl> poLineDtls) {
        this.poLineDtls = poLineDtls;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrgAddrByShipToAddrNbrDflt")
    public Set<PoOrdHdr> getPoOrdHdrsForShipToAddrNbrDflt() {
        return this.poOrdHdrsForShipToAddrNbrDflt;
    }
    
    public void setPoOrdHdrsForShipToAddrNbrDflt(Set<PoOrdHdr> poOrdHdrsForShipToAddrNbrDflt) {
        this.poOrdHdrsForShipToAddrNbrDflt = poOrdHdrsForShipToAddrNbrDflt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrgAddrByShipToAddrNbr")
    public Set<ArInvHdr> getArInvHdrsForShipToAddrNbr() {
        return this.arInvHdrsForShipToAddrNbr;
    }
    
    public void setArInvHdrsForShipToAddrNbr(Set<ArInvHdr> arInvHdrsForShipToAddrNbr) {
        this.arInvHdrsForShipToAddrNbr = arInvHdrsForShipToAddrNbr;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrgAddrByBillToAddrNbr")
    public Set<ArInvHdr> getArInvHdrsForBillToAddrNbr() {
        return this.arInvHdrsForBillToAddrNbr;
    }
    
    public void setArInvHdrsForBillToAddrNbr(Set<ArInvHdr> arInvHdrsForBillToAddrNbr) {
        this.arInvHdrsForBillToAddrNbr = arInvHdrsForBillToAddrNbr;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrgAddrByShipToAddrNbrDflt")
    public Set<OeOrdHdr> getOeOrdHdrsForShipToAddrNbrDflt() {
        return this.oeOrdHdrsForShipToAddrNbrDflt;
    }
    
    public void setOeOrdHdrsForShipToAddrNbrDflt(Set<OeOrdHdr> oeOrdHdrsForShipToAddrNbrDflt) {
        this.oeOrdHdrsForShipToAddrNbrDflt = oeOrdHdrsForShipToAddrNbrDflt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrgAddrByMailToAddrNbrDflt")
    public Set<PoVndMast> getPoVndMastsForMailToAddrNbrDflt() {
        return this.poVndMastsForMailToAddrNbrDflt;
    }
    
    public void setPoVndMastsForMailToAddrNbrDflt(Set<PoVndMast> poVndMastsForMailToAddrNbrDflt) {
        this.poVndMastsForMailToAddrNbrDflt = poVndMastsForMailToAddrNbrDflt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrgAddrByBillToAddrNbrDflt")
    public Set<PoVndMast> getPoVndMastsForBillToAddrNbrDflt() {
        return this.poVndMastsForBillToAddrNbrDflt;
    }
    
    public void setPoVndMastsForBillToAddrNbrDflt(Set<PoVndMast> poVndMastsForBillToAddrNbrDflt) {
        this.poVndMastsForBillToAddrNbrDflt = poVndMastsForBillToAddrNbrDflt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrgAddrByAddrNbrVnd")
    public Set<PoOrdHdr> getPoOrdHdrsForAddrNbrVnd() {
        return this.poOrdHdrsForAddrNbrVnd;
    }
    
    public void setPoOrdHdrsForAddrNbrVnd(Set<PoOrdHdr> poOrdHdrsForAddrNbrVnd) {
        this.poOrdHdrsForAddrNbrVnd = poOrdHdrsForAddrNbrVnd;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrgAddr")
    public Set<UtFacility> getUtFacilities() {
        return this.utFacilities;
    }
    
    public void setUtFacilities(Set<UtFacility> utFacilities) {
        this.utFacilities = utFacilities;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naOrgAddr")
    public Set<OeOrdDtl> getOeOrdDtls() {
        return this.oeOrdDtls;
    }
    
    public void setOeOrdDtls(Set<OeOrdDtl> oeOrdDtls) {
        this.oeOrdDtls = oeOrdDtls;
    }




}


