package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OeContractItemLog generated by hbm2java
 */
@Entity
@Table(name="OE_CONTRACT_ITEM_LOG"
)
public class OeContractItemLog  implements java.io.Serializable {


     private OeContractItemLogId id;

    public OeContractItemLog() {
    }

    public OeContractItemLog(OeContractItemLogId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orgNbrCust", column=@Column(name="ORG_NBR_CUST", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="contractCd", column=@Column(name="CONTRACT_CD", nullable=false, length=8) ), 
        @AttributeOverride(name="itemCdCust", column=@Column(name="ITEM_CD_CUST", nullable=false, length=50) ), 
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="itemNbrSupersede", column=@Column(name="ITEM_NBR_SUPERSEDE", precision=9, scale=0) ), 
        @AttributeOverride(name="effDtBeg", column=@Column(name="EFF_DT_BEG", length=7) ), 
        @AttributeOverride(name="effDtEnd", column=@Column(name="EFF_DT_END", length=7) ), 
        @AttributeOverride(name="totContractQty", column=@Column(name="TOT_CONTRACT_QTY", precision=9, scale=0) ), 
        @AttributeOverride(name="utUserNbrMod", column=@Column(name="UT_USER_NBR_MOD", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="modDt", column=@Column(name="MOD_DT", nullable=false, length=7) ) } )
    public OeContractItemLogId getId() {
        return this.id;
    }
    
    public void setId(OeContractItemLogId id) {
        this.id = id;
    }




}


