package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OeCustMastVw generated by hbm2java
 */
@Entity
@Table(name="OE_CUST_MAST_VW"
)
public class OeCustMastVw  implements java.io.Serializable {


     private OeCustMastVwId id;

    public OeCustMastVw() {
    }

    public OeCustMastVw(OeCustMastVwId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orgNbrCust", column=@Column(name="ORG_NBR_CUST", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="statId", column=@Column(name="STAT_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="sellIndivNbr", column=@Column(name="SELL_INDIV_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="shipToAddrNbrDflt", column=@Column(name="SHIP_TO_ADDR_NBR_DFLT", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="shipToAddrCdDflt", column=@Column(name="SHIP_TO_ADDR_CD_DFLT", nullable=false, length=8) ), 
        @AttributeOverride(name="billToAddrNbrDflt", column=@Column(name="BILL_TO_ADDR_NBR_DFLT", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="billToAddrCdDflt", column=@Column(name="BILL_TO_ADDR_CD_DFLT", nullable=false, length=8) ), 
        @AttributeOverride(name="termCdDflt", column=@Column(name="TERM_CD_DFLT", nullable=false, length=10) ), 
        @AttributeOverride(name="fobCdDflt", column=@Column(name="FOB_CD_DFLT", nullable=false, length=8) ), 
        @AttributeOverride(name="currCdDflt", column=@Column(name="CURR_CD_DFLT", nullable=false, length=3) ), 
        @AttributeOverride(name="shipViaCdDflt", column=@Column(name="SHIP_VIA_CD_DFLT", nullable=false, length=8) ), 
        @AttributeOverride(name="ordTypeCdDflt", column=@Column(name="ORD_TYPE_CD_DFLT", nullable=false, length=8) ), 
        @AttributeOverride(name="sicCd", column=@Column(name="SIC_CD", length=8) ), 
        @AttributeOverride(name="custGrp", column=@Column(name="CUST_GRP", length=8) ), 
        @AttributeOverride(name="custPriceGrp", column=@Column(name="CUST_PRICE_GRP", length=10) ), 
        @AttributeOverride(name="salesTerrCdDflt", column=@Column(name="SALES_TERR_CD_DFLT", nullable=false, length=8) ), 
        @AttributeOverride(name="salesRegionCdDflt", column=@Column(name="SALES_REGION_CD_DFLT", length=8) ), 
        @AttributeOverride(name="contractCustFlg", column=@Column(name="CONTRACT_CUST_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="reqrPoFlg", column=@Column(name="REQR_PO_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="dupPoAllowFlg", column=@Column(name="DUP_PO_ALLOW_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="priceChgFlg", column=@Column(name="PRICE_CHG_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="virtualCustFlg", column=@Column(name="VIRTUAL_CUST_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="addAddrFlg", column=@Column(name="ADD_ADDR_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="custAllocPrty", column=@Column(name="CUST_ALLOC_PRTY", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="shipPctLineDflt", column=@Column(name="SHIP_PCT_LINE_DFLT", precision=5) ), 
        @AttributeOverride(name="shipPctDollarDflt", column=@Column(name="SHIP_PCT_DOLLAR_DFLT", precision=5) ), 
        @AttributeOverride(name="shipLinePctDflt", column=@Column(name="SHIP_LINE_PCT_DFLT", precision=3, scale=0) ), 
        @AttributeOverride(name="autoCloseLinePctDflt", column=@Column(name="AUTO_CLOSE_LINE_PCT_DFLT", precision=3, scale=0) ), 
        @AttributeOverride(name="maxShipmentsPerLineDflt", column=@Column(name="MAX_SHIPMENTS_PER_LINE_DFLT", precision=2, scale=0) ), 
        @AttributeOverride(name="orgCdCust", column=@Column(name="ORG_CD_CUST", nullable=false, length=15) ), 
        @AttributeOverride(name="orgNmCust", column=@Column(name="ORG_NM_CUST", nullable=false, length=60) ), 
        @AttributeOverride(name="introDt", column=@Column(name="INTRO_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="trdFlg", column=@Column(name="TRD_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="trdGlAcct", column=@Column(name="TRD_GL_ACCT", length=20) ), 
        @AttributeOverride(name="creditLimit", column=@Column(name="CREDIT_LIMIT", precision=12) ), 
        @AttributeOverride(name="currArBal", column=@Column(name="CURR_AR_BAL", precision=10) ), 
        @AttributeOverride(name="labelNmBag", column=@Column(name="LABEL_NM_BAG", length=4000) ), 
        @AttributeOverride(name="labelNmPackBox", column=@Column(name="LABEL_NM_PACK_BOX", length=4000) ), 
        @AttributeOverride(name="labelNmPackBoxPlain", column=@Column(name="LABEL_NM_PACK_BOX_PLAIN", length=4000) ), 
        @AttributeOverride(name="packBoxContentsRptNm", column=@Column(name="PACK_BOX_CONTENTS_RPT_NM", length=4000) ), 
        @AttributeOverride(name="packSlipRptNm", column=@Column(name="PACK_SLIP_RPT_NM", length=4000) ), 
        @AttributeOverride(name="summaryInvRptNm", column=@Column(name="SUMMARY_INV_RPT_NM") ), 
        @AttributeOverride(name="showPriceOnPackSlipFlg", column=@Column(name="SHOW_PRICE_ON_PACK_SLIP_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="nbrPackSlipCopies", column=@Column(name="NBR_PACK_SLIP_COPIES", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="nbrInvoiceCopies", column=@Column(name="NBR_INVOICE_COPIES", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="phnNbrDflt", column=@Column(name="PHN_NBR_DFLT", length=20) ), 
        @AttributeOverride(name="faxNbrDflt", column=@Column(name="FAX_NBR_DFLT", length=20) ), 
        @AttributeOverride(name="avgDaysToPay", column=@Column(name="AVG_DAYS_TO_PAY", precision=3, scale=0) ), 
        @AttributeOverride(name="indivNbrCustContact", column=@Column(name="INDIV_NBR_CUST_CONTACT", precision=9, scale=0) ), 
        @AttributeOverride(name="custUpdDt", column=@Column(name="CUST_UPD_DT", length=7) ), 
        @AttributeOverride(name="fcstGrp", column=@Column(name="FCST_GRP", nullable=false, length=8) ), 
        @AttributeOverride(name="arIntegrationTm", column=@Column(name="AR_INTEGRATION_TM", length=7) ), 
        @AttributeOverride(name="orgNbrCustParent", column=@Column(name="ORG_NBR_CUST_PARENT", precision=9, scale=0) ) } )
    public OeCustMastVwId getId() {
        return this.id;
    }
    
    public void setId(OeCustMastVwId id) {
        this.id = id;
    }




}


