package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OeOrdDtlLog generated by hbm2java
 */
@Entity
@Table(name="OE_ORD_DTL_LOG"
)
public class OeOrdDtlLog  implements java.io.Serializable {


     private OeOrdDtlLogId id;

    public OeOrdDtlLog() {
    }

    public OeOrdDtlLog(OeOrdDtlLogId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="oeOrdDtlNbr", column=@Column(name="OE_ORD_DTL_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="oeOrdHdrNbr", column=@Column(name="OE_ORD_HDR_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="orgNbrCust", column=@Column(name="ORG_NBR_CUST", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="lineNbr", column=@Column(name="LINE_NBR", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="custLineCd", column=@Column(name="CUST_LINE_CD", length=5) ), 
        @AttributeOverride(name="itemNbrRqst", column=@Column(name="ITEM_NBR_RQST", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="itemNbrOrd", column=@Column(name="ITEM_NBR_ORD", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="qtyOrd", column=@Column(name="QTY_ORD", nullable=false, precision=12, scale=5) ), 
        @AttributeOverride(name="qtyOrdStkUm", column=@Column(name="QTY_ORD_STK_UM", nullable=false, precision=12, scale=5) ), 
        @AttributeOverride(name="sellUm", column=@Column(name="SELL_UM", nullable=false, length=3) ), 
        @AttributeOverride(name="rqstDt", column=@Column(name="RQST_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="shipToAddrNbr", column=@Column(name="SHIP_TO_ADDR_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="promDtOrig", column=@Column(name="PROM_DT_ORIG", length=7) ), 
        @AttributeOverride(name="promDtCurr", column=@Column(name="PROM_DT_CURR", nullable=false, length=7) ), 
        @AttributeOverride(name="unitPriceSellUm", column=@Column(name="UNIT_PRICE_SELL_UM", precision=17, scale=6) ), 
        @AttributeOverride(name="unitPriceDenomSellUm", column=@Column(name="UNIT_PRICE_DENOM_SELL_UM", precision=17, scale=6) ), 
        @AttributeOverride(name="unitPriceStkUm", column=@Column(name="UNIT_PRICE_STK_UM", precision=17, scale=6) ), 
        @AttributeOverride(name="unitPriceDenomStkUm", column=@Column(name="UNIT_PRICE_DENOM_STK_UM", precision=17, scale=6) ), 
        @AttributeOverride(name="tieCd", column=@Column(name="TIE_CD", length=1) ), 
        @AttributeOverride(name="lineStatId", column=@Column(name="LINE_STAT_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="itemCdCust", column=@Column(name="ITEM_CD_CUST", length=50) ), 
        @AttributeOverride(name="apsSrcRuleSetNbr", column=@Column(name="APS_SRC_RULE_SET_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="orgNbrMfrRqst", column=@Column(name="ORG_NBR_MFR_RQST", precision=9, scale=0) ), 
        @AttributeOverride(name="lotNotExpireBeforeDt", column=@Column(name="LOT_NOT_EXPIRE_BEFORE_DT", length=7) ), 
        @AttributeOverride(name="lotManufactureAfterDt", column=@Column(name="LOT_MANUFACTURE_AFTER_DT", length=7) ), 
        @AttributeOverride(name="cntryCdOrigin", column=@Column(name="CNTRY_CD_ORIGIN", length=3) ), 
        @AttributeOverride(name="revLvl", column=@Column(name="REV_LVL", length=5) ), 
        @AttributeOverride(name="shipViaCd", column=@Column(name="SHIP_VIA_CD", nullable=false, length=8) ), 
        @AttributeOverride(name="contractCd", column=@Column(name="CONTRACT_CD", length=8) ), 
        @AttributeOverride(name="custBinCd", column=@Column(name="CUST_BIN_CD", length=40) ), 
        @AttributeOverride(name="pkgQty", column=@Column(name="PKG_QTY", precision=7, scale=0) ), 
        @AttributeOverride(name="pickPrtyCust", column=@Column(name="PICK_PRTY_CUST", precision=3, scale=0) ), 
        @AttributeOverride(name="pickPrtyRqst", column=@Column(name="PICK_PRTY_RQST", precision=2, scale=0) ), 
        @AttributeOverride(name="pickPrtyPastDueMult", column=@Column(name="PICK_PRTY_PAST_DUE_MULT", precision=2, scale=0) ), 
        @AttributeOverride(name="qtyShip", column=@Column(name="QTY_SHIP", precision=12, scale=5) ), 
        @AttributeOverride(name="qtyShipStkUm", column=@Column(name="QTY_SHIP_STK_UM", precision=13, scale=5) ), 
        @AttributeOverride(name="qtyAlloc", column=@Column(name="QTY_ALLOC", precision=13, scale=5) ), 
        @AttributeOverride(name="qtyAllocStkUm", column=@Column(name="QTY_ALLOC_STK_UM", precision=13, scale=5) ), 
        @AttributeOverride(name="partMismatchReasonCd", column=@Column(name="PART_MISMATCH_REASON_CD", length=8) ), 
        @AttributeOverride(name="custRef", column=@Column(name="CUST_REF", length=20) ), 
        @AttributeOverride(name="shipFromFacility", column=@Column(name="SHIP_FROM_FACILITY", nullable=false, length=16) ), 
        @AttributeOverride(name="shipCmpltFlg", column=@Column(name="SHIP_CMPLT_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="hotFlg", column=@Column(name="HOT_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="shipLinePct", column=@Column(name="SHIP_LINE_PCT", precision=3, scale=0) ), 
        @AttributeOverride(name="cancelCd", column=@Column(name="CANCEL_CD", length=8) ), 
        @AttributeOverride(name="cancelDt", column=@Column(name="CANCEL_DT", length=7) ), 
        @AttributeOverride(name="utUserNbrCancel", column=@Column(name="UT_USER_NBR_CANCEL", precision=9, scale=0) ), 
        @AttributeOverride(name="closeReasonCd", column=@Column(name="CLOSE_REASON_CD", length=8) ), 
        @AttributeOverride(name="closeDt", column=@Column(name="CLOSE_DT", length=7) ), 
        @AttributeOverride(name="utUserNbrClose", column=@Column(name="UT_USER_NBR_CLOSE", precision=9, scale=0) ), 
        @AttributeOverride(name="utUserNbr", column=@Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="lastModDt", column=@Column(name="LAST_MOD_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="action", column=@Column(name="ACTION", nullable=false, length=6) ), 
        @AttributeOverride(name="utUserNbrAction", column=@Column(name="UT_USER_NBR_ACTION", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="actionTm", column=@Column(name="ACTION_TM", nullable=false, length=7) ) } )
    public OeOrdDtlLogId getId() {
        return this.id;
    }
    
    public void setId(OeOrdDtlLogId id) {
        this.id = id;
    }




}


