package com.pacificdataservices.diamond.models;
// Generated Apr 25, 2019 6:28:42 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OeOrdDtlHist generated by hbm2java
 */
@Entity
@Table(name="OE_ORD_DTL_HIST"
)
public class OeOrdDtlHist  implements java.io.Serializable {


     private int oeOrdDtlNbr;
     private int oeOrdHdrNbr;
     private Date ordDt;
     private String ordStatId;
     private int orgNbrCust;
     private String orgCdCust;
     private String custPoCd;
     private Date custPoDt;
     private String fobCd;
     private String currCd;
     private String trdFlg;
     private String ordTypeCd;
     private String ordCd;
     private String salesTerrCd;
     private String transmitFlg;
     private short lineNbr;
     private String custLineCd;
     private int itemNbrRqst;
     private int itemNbrOrd;
     private BigDecimal qtyOrd;
     private BigDecimal qtyOrdStkUm;
     private String sellUm;
     private Date rqstDt;
     private int shipToAddrNbr;
     private Date promDtOrig;
     private Date promDtCurr;
     private BigDecimal unitPriceSellUm;
     private BigDecimal unitPriceDenomSellUm;
     private BigDecimal unitPriceStkUm;
     private BigDecimal unitPriceDenomStkUm;
     private String itemCdCust;
     private int apsSrcRuleSetNbr;
     private Integer orgNbrMfrRqst;
     private Date lotNotExpireBeforeDt;
     private Date lotManufactureAfterDt;
     private String cntryCdOrigin;
     private String revLvl;
     private String shipViaCd;
     private String contractCd;
     private String custBinCd;
     private BigDecimal qtyShip;
     private BigDecimal qtyShipStkUm;
     private BigDecimal qtyAlloc;
     private BigDecimal qtyAllocStkUm;
     private String partMismatchReasonCd;
     private String custRef;
     private String shipFromFacility;
     private String shipCmpltFlg;
     private String hotFlg;
     private Short shipLinePct;
     private String cancelCd;
     private Date cancelDt;

    public OeOrdDtlHist() {
    }

	
   
    @Id 
    @Column(name="OE_ORD_DTL_NBR", nullable=false, precision=9, scale=0)
    public int getOeOrdDtlNbr() {
        return this.oeOrdDtlNbr;
    }
    
    public void setOeOrdDtlNbr(int oeOrdDtlNbr) {
        this.oeOrdDtlNbr = oeOrdDtlNbr;
    }

    
    @Column(name="OE_ORD_HDR_NBR", nullable=false, precision=9, scale=0)
    public int getOeOrdHdrNbr() {
        return this.oeOrdHdrNbr;
    }
    
    public void setOeOrdHdrNbr(int oeOrdHdrNbr) {
        this.oeOrdHdrNbr = oeOrdHdrNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ORD_DT", nullable=false, length=7)
    public Date getOrdDt() {
        return this.ordDt;
    }
    
    public void setOrdDt(Date ordDt) {
        this.ordDt = ordDt;
    }

    
    @Column(name="ORD_STAT_ID", nullable=false, length=1)
    public String getOrdStatId() {
        return this.ordStatId;
    }
    
    public void setOrdStatId(String ordStatId) {
        this.ordStatId = ordStatId;
    }

    
    @Column(name="ORG_NBR_CUST", nullable=false, precision=9, scale=0)
    public int getOrgNbrCust() {
        return this.orgNbrCust;
    }
    
    public void setOrgNbrCust(int orgNbrCust) {
        this.orgNbrCust = orgNbrCust;
    }

    
    @Column(name="ORG_CD_CUST", nullable=false, length=15)
    public String getOrgCdCust() {
        return this.orgCdCust;
    }
    
    public void setOrgCdCust(String orgCdCust) {
        this.orgCdCust = orgCdCust;
    }

    
    @Column(name="CUST_PO_CD", length=30)
    public String getCustPoCd() {
        return this.custPoCd;
    }
    
    public void setCustPoCd(String custPoCd) {
        this.custPoCd = custPoCd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CUST_PO_DT", length=7)
    public Date getCustPoDt() {
        return this.custPoDt;
    }
    
    public void setCustPoDt(Date custPoDt) {
        this.custPoDt = custPoDt;
    }

    
    @Column(name="FOB_CD", length=8)
    public String getFobCd() {
        return this.fobCd;
    }
    
    public void setFobCd(String fobCd) {
        this.fobCd = fobCd;
    }

    
    @Column(name="CURR_CD", nullable=false, length=3)
    public String getCurrCd() {
        return this.currCd;
    }
    
    public void setCurrCd(String currCd) {
        this.currCd = currCd;
    }

    
    @Column(name="TRD_FLG", nullable=false, length=1)
    public String getTrdFlg() {
        return this.trdFlg;
    }
    
    public void setTrdFlg(String trdFlg) {
        this.trdFlg = trdFlg;
    }

    
    @Column(name="ORD_TYPE_CD", nullable=false, length=8)
    public String getOrdTypeCd() {
        return this.ordTypeCd;
    }
    
    public void setOrdTypeCd(String ordTypeCd) {
        this.ordTypeCd = ordTypeCd;
    }

    
    @Column(name="ORD_CD", nullable=false, length=20)
    public String getOrdCd() {
        return this.ordCd;
    }
    
    public void setOrdCd(String ordCd) {
        this.ordCd = ordCd;
    }

    
    @Column(name="SALES_TERR_CD", nullable=false, length=8)
    public String getSalesTerrCd() {
        return this.salesTerrCd;
    }
    
    public void setSalesTerrCd(String salesTerrCd) {
        this.salesTerrCd = salesTerrCd;
    }

    
    @Column(name="TRANSMIT_FLG", nullable=false, length=1)
    public String getTransmitFlg() {
        return this.transmitFlg;
    }
    
    public void setTransmitFlg(String transmitFlg) {
        this.transmitFlg = transmitFlg;
    }

    
    @Column(name="LINE_NBR", nullable=false, precision=4, scale=0)
    public short getLineNbr() {
        return this.lineNbr;
    }
    
    public void setLineNbr(short lineNbr) {
        this.lineNbr = lineNbr;
    }

    
    @Column(name="CUST_LINE_CD", length=5)
    public String getCustLineCd() {
        return this.custLineCd;
    }
    
    public void setCustLineCd(String custLineCd) {
        this.custLineCd = custLineCd;
    }

    
    @Column(name="ITEM_NBR_RQST", nullable=false, precision=9, scale=0)
    public int getItemNbrRqst() {
        return this.itemNbrRqst;
    }
    
    public void setItemNbrRqst(int itemNbrRqst) {
        this.itemNbrRqst = itemNbrRqst;
    }

    
    @Column(name="ITEM_NBR_ORD", nullable=false, precision=9, scale=0)
    public int getItemNbrOrd() {
        return this.itemNbrOrd;
    }
    
    public void setItemNbrOrd(int itemNbrOrd) {
        this.itemNbrOrd = itemNbrOrd;
    }

    
    @Column(name="QTY_ORD", nullable=false, precision=15, scale=5)
    public BigDecimal getQtyOrd() {
        return this.qtyOrd;
    }
    
    public void setQtyOrd(BigDecimal qtyOrd) {
        this.qtyOrd = qtyOrd;
    }

    
    @Column(name="QTY_ORD_STK_UM", nullable=false, precision=15, scale=5)
    public BigDecimal getQtyOrdStkUm() {
        return this.qtyOrdStkUm;
    }
    
    public void setQtyOrdStkUm(BigDecimal qtyOrdStkUm) {
        this.qtyOrdStkUm = qtyOrdStkUm;
    }

    
    @Column(name="SELL_UM", nullable=false, length=3)
    public String getSellUm() {
        return this.sellUm;
    }
    
    public void setSellUm(String sellUm) {
        this.sellUm = sellUm;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RQST_DT", nullable=false, length=7)
    public Date getRqstDt() {
        return this.rqstDt;
    }
    
    public void setRqstDt(Date rqstDt) {
        this.rqstDt = rqstDt;
    }

    
    @Column(name="SHIP_TO_ADDR_NBR", nullable=false, precision=9, scale=0)
    public int getShipToAddrNbr() {
        return this.shipToAddrNbr;
    }
    
    public void setShipToAddrNbr(int shipToAddrNbr) {
        this.shipToAddrNbr = shipToAddrNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PROM_DT_ORIG", nullable=false, length=7)
    public Date getPromDtOrig() {
        return this.promDtOrig;
    }
    
    public void setPromDtOrig(Date promDtOrig) {
        this.promDtOrig = promDtOrig;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PROM_DT_CURR", nullable=false, length=7)
    public Date getPromDtCurr() {
        return this.promDtCurr;
    }
    
    public void setPromDtCurr(Date promDtCurr) {
        this.promDtCurr = promDtCurr;
    }

    
    @Column(name="UNIT_PRICE_SELL_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceSellUm() {
        return this.unitPriceSellUm;
    }
    
    public void setUnitPriceSellUm(BigDecimal unitPriceSellUm) {
        this.unitPriceSellUm = unitPriceSellUm;
    }

    
    @Column(name="UNIT_PRICE_DENOM_SELL_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceDenomSellUm() {
        return this.unitPriceDenomSellUm;
    }
    
    public void setUnitPriceDenomSellUm(BigDecimal unitPriceDenomSellUm) {
        this.unitPriceDenomSellUm = unitPriceDenomSellUm;
    }

    
    @Column(name="UNIT_PRICE_STK_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceStkUm() {
        return this.unitPriceStkUm;
    }
    
    public void setUnitPriceStkUm(BigDecimal unitPriceStkUm) {
        this.unitPriceStkUm = unitPriceStkUm;
    }

    
    @Column(name="UNIT_PRICE_DENOM_STK_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceDenomStkUm() {
        return this.unitPriceDenomStkUm;
    }
    
    public void setUnitPriceDenomStkUm(BigDecimal unitPriceDenomStkUm) {
        this.unitPriceDenomStkUm = unitPriceDenomStkUm;
    }

    
    @Column(name="ITEM_CD_CUST", length=50)
    public String getItemCdCust() {
        return this.itemCdCust;
    }
    
    public void setItemCdCust(String itemCdCust) {
        this.itemCdCust = itemCdCust;
    }

    
    @Column(name="APS_SRC_RULE_SET_NBR", nullable=false, precision=9, scale=0)
    public int getApsSrcRuleSetNbr() {
        return this.apsSrcRuleSetNbr;
    }
    
    public void setApsSrcRuleSetNbr(int apsSrcRuleSetNbr) {
        this.apsSrcRuleSetNbr = apsSrcRuleSetNbr;
    }

    
    @Column(name="ORG_NBR_MFR_RQST", precision=9, scale=0)
    public Integer getOrgNbrMfrRqst() {
        return this.orgNbrMfrRqst;
    }
    
    public void setOrgNbrMfrRqst(Integer orgNbrMfrRqst) {
        this.orgNbrMfrRqst = orgNbrMfrRqst;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LOT_NOT_EXPIRE_BEFORE_DT", length=7)
    public Date getLotNotExpireBeforeDt() {
        return this.lotNotExpireBeforeDt;
    }
    
    public void setLotNotExpireBeforeDt(Date lotNotExpireBeforeDt) {
        this.lotNotExpireBeforeDt = lotNotExpireBeforeDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LOT_MANUFACTURE_AFTER_DT", length=7)
    public Date getLotManufactureAfterDt() {
        return this.lotManufactureAfterDt;
    }
    
    public void setLotManufactureAfterDt(Date lotManufactureAfterDt) {
        this.lotManufactureAfterDt = lotManufactureAfterDt;
    }

    
    @Column(name="CNTRY_CD_ORIGIN", length=3)
    public String getCntryCdOrigin() {
        return this.cntryCdOrigin;
    }
    
    public void setCntryCdOrigin(String cntryCdOrigin) {
        this.cntryCdOrigin = cntryCdOrigin;
    }

    
    @Column(name="REV_LVL", length=5)
    public String getRevLvl() {
        return this.revLvl;
    }
    
    public void setRevLvl(String revLvl) {
        this.revLvl = revLvl;
    }

    
    @Column(name="SHIP_VIA_CD", nullable=false, length=8)
    public String getShipViaCd() {
        return this.shipViaCd;
    }
    
    public void setShipViaCd(String shipViaCd) {
        this.shipViaCd = shipViaCd;
    }

    
    @Column(name="CONTRACT_CD", length=8)
    public String getContractCd() {
        return this.contractCd;
    }
    
    public void setContractCd(String contractCd) {
        this.contractCd = contractCd;
    }

    
    @Column(name="CUST_BIN_CD", length=40)
    public String getCustBinCd() {
        return this.custBinCd;
    }
    
    public void setCustBinCd(String custBinCd) {
        this.custBinCd = custBinCd;
    }

    
    @Column(name="QTY_SHIP", precision=15, scale=5)
    public BigDecimal getQtyShip() {
        return this.qtyShip;
    }
    
    public void setQtyShip(BigDecimal qtyShip) {
        this.qtyShip = qtyShip;
    }

    
    @Column(name="QTY_SHIP_STK_UM", precision=15, scale=5)
    public BigDecimal getQtyShipStkUm() {
        return this.qtyShipStkUm;
    }
    
    public void setQtyShipStkUm(BigDecimal qtyShipStkUm) {
        this.qtyShipStkUm = qtyShipStkUm;
    }

    
    @Column(name="QTY_ALLOC", precision=13, scale=5)
    public BigDecimal getQtyAlloc() {
        return this.qtyAlloc;
    }
    
    public void setQtyAlloc(BigDecimal qtyAlloc) {
        this.qtyAlloc = qtyAlloc;
    }

    
    @Column(name="QTY_ALLOC_STK_UM", precision=13, scale=5)
    public BigDecimal getQtyAllocStkUm() {
        return this.qtyAllocStkUm;
    }
    
    public void setQtyAllocStkUm(BigDecimal qtyAllocStkUm) {
        this.qtyAllocStkUm = qtyAllocStkUm;
    }

    
    @Column(name="PART_MISMATCH_REASON_CD", length=8)
    public String getPartMismatchReasonCd() {
        return this.partMismatchReasonCd;
    }
    
    public void setPartMismatchReasonCd(String partMismatchReasonCd) {
        this.partMismatchReasonCd = partMismatchReasonCd;
    }

    
    @Column(name="CUST_REF", length=40)
    public String getCustRef() {
        return this.custRef;
    }
    
    public void setCustRef(String custRef) {
        this.custRef = custRef;
    }

    
    @Column(name="SHIP_FROM_FACILITY", nullable=false, length=16)
    public String getShipFromFacility() {
        return this.shipFromFacility;
    }
    
    public void setShipFromFacility(String shipFromFacility) {
        this.shipFromFacility = shipFromFacility;
    }

    
    @Column(name="SHIP_CMPLT_FLG", nullable=false, length=1)
    public String getShipCmpltFlg() {
        return this.shipCmpltFlg;
    }
    
    public void setShipCmpltFlg(String shipCmpltFlg) {
        this.shipCmpltFlg = shipCmpltFlg;
    }

    
    @Column(name="HOT_FLG", nullable=false, length=1)
    public String getHotFlg() {
        return this.hotFlg;
    }
    
    public void setHotFlg(String hotFlg) {
        this.hotFlg = hotFlg;
    }

    
    @Column(name="SHIP_LINE_PCT", precision=3, scale=0)
    public Short getShipLinePct() {
        return this.shipLinePct;
    }
    
    public void setShipLinePct(Short shipLinePct) {
        this.shipLinePct = shipLinePct;
    }

    
    @Column(name="CANCEL_CD", length=8)
    public String getCancelCd() {
        return this.cancelCd;
    }
    
    public void setCancelCd(String cancelCd) {
        this.cancelCd = cancelCd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CANCEL_DT", length=7)
    public Date getCancelDt() {
        return this.cancelDt;
    }
    
    public void setCancelDt(Date cancelDt) {
        this.cancelDt = cancelDt;
    }




}


