package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OeOrdDtlLogId generated by hbm2java
 */
@Embeddable
public class OeOrdDtlLogId  implements java.io.Serializable {


     private int oeOrdDtlNbr;
     private int oeOrdHdrNbr;
     private int orgNbrCust;
     private short lineNbr;
     private String custLineCd;
     private int itemNbrRqst;
     private int itemNbrOrd;
     private BigDecimal qtyOrd;
     private BigDecimal qtyOrdStkUm;
     private String sellUm;
     private Date rqstDt;
     private int shipToAddrNbr;
     private Date promDtOrig;
     private Date promDtCurr;
     private BigDecimal unitPriceSellUm;
     private BigDecimal unitPriceDenomSellUm;
     private BigDecimal unitPriceStkUm;
     private BigDecimal unitPriceDenomStkUm;
     private String tieCd;
     private String lineStatId;
     private String itemCdCust;
     private int apsSrcRuleSetNbr;
     private Integer orgNbrMfrRqst;
     private Date lotNotExpireBeforeDt;
     private Date lotManufactureAfterDt;
     private String cntryCdOrigin;
     private String revLvl;
     private String shipViaCd;
     private String contractCd;
     private String custBinCd;
     private Integer pkgQty;
     private Short pickPrtyCust;
     private Byte pickPrtyRqst;
     private Byte pickPrtyPastDueMult;
     private BigDecimal qtyShip;
     private BigDecimal qtyShipStkUm;
     private BigDecimal qtyAlloc;
     private BigDecimal qtyAllocStkUm;
     private String partMismatchReasonCd;
     private String custRef;
     private String shipFromFacility;
     private String shipCmpltFlg;
     private String hotFlg;
     private Short shipLinePct;
     private String cancelCd;
     private Date cancelDt;
     private Integer utUserNbrCancel;
     private String closeReasonCd;
     private Date closeDt;
     private Integer utUserNbrClose;
     private int utUserNbr;
     private Date lastModDt;
     private String action;
     private int utUserNbrAction;
     private Date actionTm;

    public OeOrdDtlLogId() {
    }

	
    public OeOrdDtlLogId(int oeOrdDtlNbr, int oeOrdHdrNbr, int orgNbrCust, short lineNbr, int itemNbrRqst, int itemNbrOrd, BigDecimal qtyOrd, BigDecimal qtyOrdStkUm, String sellUm, Date rqstDt, int shipToAddrNbr, Date promDtCurr, String lineStatId, int apsSrcRuleSetNbr, String shipViaCd, String shipFromFacility, String shipCmpltFlg, String hotFlg, int utUserNbr, Date lastModDt, String action, int utUserNbrAction, Date actionTm) {
        this.oeOrdDtlNbr = oeOrdDtlNbr;
        this.oeOrdHdrNbr = oeOrdHdrNbr;
        this.orgNbrCust = orgNbrCust;
        this.lineNbr = lineNbr;
        this.itemNbrRqst = itemNbrRqst;
        this.itemNbrOrd = itemNbrOrd;
        this.qtyOrd = qtyOrd;
        this.qtyOrdStkUm = qtyOrdStkUm;
        this.sellUm = sellUm;
        this.rqstDt = rqstDt;
        this.shipToAddrNbr = shipToAddrNbr;
        this.promDtCurr = promDtCurr;
        this.lineStatId = lineStatId;
        this.apsSrcRuleSetNbr = apsSrcRuleSetNbr;
        this.shipViaCd = shipViaCd;
        this.shipFromFacility = shipFromFacility;
        this.shipCmpltFlg = shipCmpltFlg;
        this.hotFlg = hotFlg;
        this.utUserNbr = utUserNbr;
        this.lastModDt = lastModDt;
        this.action = action;
        this.utUserNbrAction = utUserNbrAction;
        this.actionTm = actionTm;
    }
    public OeOrdDtlLogId(int oeOrdDtlNbr, int oeOrdHdrNbr, int orgNbrCust, short lineNbr, String custLineCd, int itemNbrRqst, int itemNbrOrd, BigDecimal qtyOrd, BigDecimal qtyOrdStkUm, String sellUm, Date rqstDt, int shipToAddrNbr, Date promDtOrig, Date promDtCurr, BigDecimal unitPriceSellUm, BigDecimal unitPriceDenomSellUm, BigDecimal unitPriceStkUm, BigDecimal unitPriceDenomStkUm, String tieCd, String lineStatId, String itemCdCust, int apsSrcRuleSetNbr, Integer orgNbrMfrRqst, Date lotNotExpireBeforeDt, Date lotManufactureAfterDt, String cntryCdOrigin, String revLvl, String shipViaCd, String contractCd, String custBinCd, Integer pkgQty, Short pickPrtyCust, Byte pickPrtyRqst, Byte pickPrtyPastDueMult, BigDecimal qtyShip, BigDecimal qtyShipStkUm, BigDecimal qtyAlloc, BigDecimal qtyAllocStkUm, String partMismatchReasonCd, String custRef, String shipFromFacility, String shipCmpltFlg, String hotFlg, Short shipLinePct, String cancelCd, Date cancelDt, Integer utUserNbrCancel, String closeReasonCd, Date closeDt, Integer utUserNbrClose, int utUserNbr, Date lastModDt, String action, int utUserNbrAction, Date actionTm) {
       this.oeOrdDtlNbr = oeOrdDtlNbr;
       this.oeOrdHdrNbr = oeOrdHdrNbr;
       this.orgNbrCust = orgNbrCust;
       this.lineNbr = lineNbr;
       this.custLineCd = custLineCd;
       this.itemNbrRqst = itemNbrRqst;
       this.itemNbrOrd = itemNbrOrd;
       this.qtyOrd = qtyOrd;
       this.qtyOrdStkUm = qtyOrdStkUm;
       this.sellUm = sellUm;
       this.rqstDt = rqstDt;
       this.shipToAddrNbr = shipToAddrNbr;
       this.promDtOrig = promDtOrig;
       this.promDtCurr = promDtCurr;
       this.unitPriceSellUm = unitPriceSellUm;
       this.unitPriceDenomSellUm = unitPriceDenomSellUm;
       this.unitPriceStkUm = unitPriceStkUm;
       this.unitPriceDenomStkUm = unitPriceDenomStkUm;
       this.tieCd = tieCd;
       this.lineStatId = lineStatId;
       this.itemCdCust = itemCdCust;
       this.apsSrcRuleSetNbr = apsSrcRuleSetNbr;
       this.orgNbrMfrRqst = orgNbrMfrRqst;
       this.lotNotExpireBeforeDt = lotNotExpireBeforeDt;
       this.lotManufactureAfterDt = lotManufactureAfterDt;
       this.cntryCdOrigin = cntryCdOrigin;
       this.revLvl = revLvl;
       this.shipViaCd = shipViaCd;
       this.contractCd = contractCd;
       this.custBinCd = custBinCd;
       this.pkgQty = pkgQty;
       this.pickPrtyCust = pickPrtyCust;
       this.pickPrtyRqst = pickPrtyRqst;
       this.pickPrtyPastDueMult = pickPrtyPastDueMult;
       this.qtyShip = qtyShip;
       this.qtyShipStkUm = qtyShipStkUm;
       this.qtyAlloc = qtyAlloc;
       this.qtyAllocStkUm = qtyAllocStkUm;
       this.partMismatchReasonCd = partMismatchReasonCd;
       this.custRef = custRef;
       this.shipFromFacility = shipFromFacility;
       this.shipCmpltFlg = shipCmpltFlg;
       this.hotFlg = hotFlg;
       this.shipLinePct = shipLinePct;
       this.cancelCd = cancelCd;
       this.cancelDt = cancelDt;
       this.utUserNbrCancel = utUserNbrCancel;
       this.closeReasonCd = closeReasonCd;
       this.closeDt = closeDt;
       this.utUserNbrClose = utUserNbrClose;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
       this.action = action;
       this.utUserNbrAction = utUserNbrAction;
       this.actionTm = actionTm;
    }
   


    @Column(name="OE_ORD_DTL_NBR", nullable=false, precision=9, scale=0)
    public int getOeOrdDtlNbr() {
        return this.oeOrdDtlNbr;
    }
    
    public void setOeOrdDtlNbr(int oeOrdDtlNbr) {
        this.oeOrdDtlNbr = oeOrdDtlNbr;
    }


    @Column(name="OE_ORD_HDR_NBR", nullable=false, precision=9, scale=0)
    public int getOeOrdHdrNbr() {
        return this.oeOrdHdrNbr;
    }
    
    public void setOeOrdHdrNbr(int oeOrdHdrNbr) {
        this.oeOrdHdrNbr = oeOrdHdrNbr;
    }


    @Column(name="ORG_NBR_CUST", nullable=false, precision=9, scale=0)
    public int getOrgNbrCust() {
        return this.orgNbrCust;
    }
    
    public void setOrgNbrCust(int orgNbrCust) {
        this.orgNbrCust = orgNbrCust;
    }


    @Column(name="LINE_NBR", nullable=false, precision=3, scale=0)
    public short getLineNbr() {
        return this.lineNbr;
    }
    
    public void setLineNbr(short lineNbr) {
        this.lineNbr = lineNbr;
    }


    @Column(name="CUST_LINE_CD", length=5)
    public String getCustLineCd() {
        return this.custLineCd;
    }
    
    public void setCustLineCd(String custLineCd) {
        this.custLineCd = custLineCd;
    }


    @Column(name="ITEM_NBR_RQST", nullable=false, precision=9, scale=0)
    public int getItemNbrRqst() {
        return this.itemNbrRqst;
    }
    
    public void setItemNbrRqst(int itemNbrRqst) {
        this.itemNbrRqst = itemNbrRqst;
    }


    @Column(name="ITEM_NBR_ORD", nullable=false, precision=9, scale=0)
    public int getItemNbrOrd() {
        return this.itemNbrOrd;
    }
    
    public void setItemNbrOrd(int itemNbrOrd) {
        this.itemNbrOrd = itemNbrOrd;
    }


    @Column(name="QTY_ORD", nullable=false, precision=12, scale=5)
    public BigDecimal getQtyOrd() {
        return this.qtyOrd;
    }
    
    public void setQtyOrd(BigDecimal qtyOrd) {
        this.qtyOrd = qtyOrd;
    }


    @Column(name="QTY_ORD_STK_UM", nullable=false, precision=12, scale=5)
    public BigDecimal getQtyOrdStkUm() {
        return this.qtyOrdStkUm;
    }
    
    public void setQtyOrdStkUm(BigDecimal qtyOrdStkUm) {
        this.qtyOrdStkUm = qtyOrdStkUm;
    }


    @Column(name="SELL_UM", nullable=false, length=3)
    public String getSellUm() {
        return this.sellUm;
    }
    
    public void setSellUm(String sellUm) {
        this.sellUm = sellUm;
    }


    @Column(name="RQST_DT", nullable=false, length=7)
    public Date getRqstDt() {
        return this.rqstDt;
    }
    
    public void setRqstDt(Date rqstDt) {
        this.rqstDt = rqstDt;
    }


    @Column(name="SHIP_TO_ADDR_NBR", nullable=false, precision=9, scale=0)
    public int getShipToAddrNbr() {
        return this.shipToAddrNbr;
    }
    
    public void setShipToAddrNbr(int shipToAddrNbr) {
        this.shipToAddrNbr = shipToAddrNbr;
    }


    @Column(name="PROM_DT_ORIG", length=7)
    public Date getPromDtOrig() {
        return this.promDtOrig;
    }
    
    public void setPromDtOrig(Date promDtOrig) {
        this.promDtOrig = promDtOrig;
    }


    @Column(name="PROM_DT_CURR", nullable=false, length=7)
    public Date getPromDtCurr() {
        return this.promDtCurr;
    }
    
    public void setPromDtCurr(Date promDtCurr) {
        this.promDtCurr = promDtCurr;
    }


    @Column(name="UNIT_PRICE_SELL_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceSellUm() {
        return this.unitPriceSellUm;
    }
    
    public void setUnitPriceSellUm(BigDecimal unitPriceSellUm) {
        this.unitPriceSellUm = unitPriceSellUm;
    }


    @Column(name="UNIT_PRICE_DENOM_SELL_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceDenomSellUm() {
        return this.unitPriceDenomSellUm;
    }
    
    public void setUnitPriceDenomSellUm(BigDecimal unitPriceDenomSellUm) {
        this.unitPriceDenomSellUm = unitPriceDenomSellUm;
    }


    @Column(name="UNIT_PRICE_STK_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceStkUm() {
        return this.unitPriceStkUm;
    }
    
    public void setUnitPriceStkUm(BigDecimal unitPriceStkUm) {
        this.unitPriceStkUm = unitPriceStkUm;
    }


    @Column(name="UNIT_PRICE_DENOM_STK_UM", precision=17, scale=6)
    public BigDecimal getUnitPriceDenomStkUm() {
        return this.unitPriceDenomStkUm;
    }
    
    public void setUnitPriceDenomStkUm(BigDecimal unitPriceDenomStkUm) {
        this.unitPriceDenomStkUm = unitPriceDenomStkUm;
    }


    @Column(name="TIE_CD", length=1)
    public String getTieCd() {
        return this.tieCd;
    }
    
    public void setTieCd(String tieCd) {
        this.tieCd = tieCd;
    }


    @Column(name="LINE_STAT_ID", nullable=false, length=1)
    public String getLineStatId() {
        return this.lineStatId;
    }
    
    public void setLineStatId(String lineStatId) {
        this.lineStatId = lineStatId;
    }


    @Column(name="ITEM_CD_CUST", length=50)
    public String getItemCdCust() {
        return this.itemCdCust;
    }
    
    public void setItemCdCust(String itemCdCust) {
        this.itemCdCust = itemCdCust;
    }


    @Column(name="APS_SRC_RULE_SET_NBR", nullable=false, precision=9, scale=0)
    public int getApsSrcRuleSetNbr() {
        return this.apsSrcRuleSetNbr;
    }
    
    public void setApsSrcRuleSetNbr(int apsSrcRuleSetNbr) {
        this.apsSrcRuleSetNbr = apsSrcRuleSetNbr;
    }


    @Column(name="ORG_NBR_MFR_RQST", precision=9, scale=0)
    public Integer getOrgNbrMfrRqst() {
        return this.orgNbrMfrRqst;
    }
    
    public void setOrgNbrMfrRqst(Integer orgNbrMfrRqst) {
        this.orgNbrMfrRqst = orgNbrMfrRqst;
    }


    @Column(name="LOT_NOT_EXPIRE_BEFORE_DT", length=7)
    public Date getLotNotExpireBeforeDt() {
        return this.lotNotExpireBeforeDt;
    }
    
    public void setLotNotExpireBeforeDt(Date lotNotExpireBeforeDt) {
        this.lotNotExpireBeforeDt = lotNotExpireBeforeDt;
    }


    @Column(name="LOT_MANUFACTURE_AFTER_DT", length=7)
    public Date getLotManufactureAfterDt() {
        return this.lotManufactureAfterDt;
    }
    
    public void setLotManufactureAfterDt(Date lotManufactureAfterDt) {
        this.lotManufactureAfterDt = lotManufactureAfterDt;
    }


    @Column(name="CNTRY_CD_ORIGIN", length=3)
    public String getCntryCdOrigin() {
        return this.cntryCdOrigin;
    }
    
    public void setCntryCdOrigin(String cntryCdOrigin) {
        this.cntryCdOrigin = cntryCdOrigin;
    }


    @Column(name="REV_LVL", length=5)
    public String getRevLvl() {
        return this.revLvl;
    }
    
    public void setRevLvl(String revLvl) {
        this.revLvl = revLvl;
    }


    @Column(name="SHIP_VIA_CD", nullable=false, length=8)
    public String getShipViaCd() {
        return this.shipViaCd;
    }
    
    public void setShipViaCd(String shipViaCd) {
        this.shipViaCd = shipViaCd;
    }


    @Column(name="CONTRACT_CD", length=8)
    public String getContractCd() {
        return this.contractCd;
    }
    
    public void setContractCd(String contractCd) {
        this.contractCd = contractCd;
    }


    @Column(name="CUST_BIN_CD", length=40)
    public String getCustBinCd() {
        return this.custBinCd;
    }
    
    public void setCustBinCd(String custBinCd) {
        this.custBinCd = custBinCd;
    }


    @Column(name="PKG_QTY", precision=7, scale=0)
    public Integer getPkgQty() {
        return this.pkgQty;
    }
    
    public void setPkgQty(Integer pkgQty) {
        this.pkgQty = pkgQty;
    }


    @Column(name="PICK_PRTY_CUST", precision=3, scale=0)
    public Short getPickPrtyCust() {
        return this.pickPrtyCust;
    }
    
    public void setPickPrtyCust(Short pickPrtyCust) {
        this.pickPrtyCust = pickPrtyCust;
    }


    @Column(name="PICK_PRTY_RQST", precision=2, scale=0)
    public Byte getPickPrtyRqst() {
        return this.pickPrtyRqst;
    }
    
    public void setPickPrtyRqst(Byte pickPrtyRqst) {
        this.pickPrtyRqst = pickPrtyRqst;
    }


    @Column(name="PICK_PRTY_PAST_DUE_MULT", precision=2, scale=0)
    public Byte getPickPrtyPastDueMult() {
        return this.pickPrtyPastDueMult;
    }
    
    public void setPickPrtyPastDueMult(Byte pickPrtyPastDueMult) {
        this.pickPrtyPastDueMult = pickPrtyPastDueMult;
    }


    @Column(name="QTY_SHIP", precision=12, scale=5)
    public BigDecimal getQtyShip() {
        return this.qtyShip;
    }
    
    public void setQtyShip(BigDecimal qtyShip) {
        this.qtyShip = qtyShip;
    }


    @Column(name="QTY_SHIP_STK_UM", precision=13, scale=5)
    public BigDecimal getQtyShipStkUm() {
        return this.qtyShipStkUm;
    }
    
    public void setQtyShipStkUm(BigDecimal qtyShipStkUm) {
        this.qtyShipStkUm = qtyShipStkUm;
    }


    @Column(name="QTY_ALLOC", precision=13, scale=5)
    public BigDecimal getQtyAlloc() {
        return this.qtyAlloc;
    }
    
    public void setQtyAlloc(BigDecimal qtyAlloc) {
        this.qtyAlloc = qtyAlloc;
    }


    @Column(name="QTY_ALLOC_STK_UM", precision=13, scale=5)
    public BigDecimal getQtyAllocStkUm() {
        return this.qtyAllocStkUm;
    }
    
    public void setQtyAllocStkUm(BigDecimal qtyAllocStkUm) {
        this.qtyAllocStkUm = qtyAllocStkUm;
    }


    @Column(name="PART_MISMATCH_REASON_CD", length=8)
    public String getPartMismatchReasonCd() {
        return this.partMismatchReasonCd;
    }
    
    public void setPartMismatchReasonCd(String partMismatchReasonCd) {
        this.partMismatchReasonCd = partMismatchReasonCd;
    }


    @Column(name="CUST_REF", length=20)
    public String getCustRef() {
        return this.custRef;
    }
    
    public void setCustRef(String custRef) {
        this.custRef = custRef;
    }


    @Column(name="SHIP_FROM_FACILITY", nullable=false, length=16)
    public String getShipFromFacility() {
        return this.shipFromFacility;
    }
    
    public void setShipFromFacility(String shipFromFacility) {
        this.shipFromFacility = shipFromFacility;
    }


    @Column(name="SHIP_CMPLT_FLG", nullable=false, length=1)
    public String getShipCmpltFlg() {
        return this.shipCmpltFlg;
    }
    
    public void setShipCmpltFlg(String shipCmpltFlg) {
        this.shipCmpltFlg = shipCmpltFlg;
    }


    @Column(name="HOT_FLG", nullable=false, length=1)
    public String getHotFlg() {
        return this.hotFlg;
    }
    
    public void setHotFlg(String hotFlg) {
        this.hotFlg = hotFlg;
    }


    @Column(name="SHIP_LINE_PCT", precision=3, scale=0)
    public Short getShipLinePct() {
        return this.shipLinePct;
    }
    
    public void setShipLinePct(Short shipLinePct) {
        this.shipLinePct = shipLinePct;
    }


    @Column(name="CANCEL_CD", length=8)
    public String getCancelCd() {
        return this.cancelCd;
    }
    
    public void setCancelCd(String cancelCd) {
        this.cancelCd = cancelCd;
    }


    @Column(name="CANCEL_DT", length=7)
    public Date getCancelDt() {
        return this.cancelDt;
    }
    
    public void setCancelDt(Date cancelDt) {
        this.cancelDt = cancelDt;
    }


    @Column(name="UT_USER_NBR_CANCEL", precision=9, scale=0)
    public Integer getUtUserNbrCancel() {
        return this.utUserNbrCancel;
    }
    
    public void setUtUserNbrCancel(Integer utUserNbrCancel) {
        this.utUserNbrCancel = utUserNbrCancel;
    }


    @Column(name="CLOSE_REASON_CD", length=8)
    public String getCloseReasonCd() {
        return this.closeReasonCd;
    }
    
    public void setCloseReasonCd(String closeReasonCd) {
        this.closeReasonCd = closeReasonCd;
    }


    @Column(name="CLOSE_DT", length=7)
    public Date getCloseDt() {
        return this.closeDt;
    }
    
    public void setCloseDt(Date closeDt) {
        this.closeDt = closeDt;
    }


    @Column(name="UT_USER_NBR_CLOSE", precision=9, scale=0)
    public Integer getUtUserNbrClose() {
        return this.utUserNbrClose;
    }
    
    public void setUtUserNbrClose(Integer utUserNbrClose) {
        this.utUserNbrClose = utUserNbrClose;
    }


    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }


    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }


    @Column(name="ACTION", nullable=false, length=6)
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }


    @Column(name="UT_USER_NBR_ACTION", nullable=false, precision=9, scale=0)
    public int getUtUserNbrAction() {
        return this.utUserNbrAction;
    }
    
    public void setUtUserNbrAction(int utUserNbrAction) {
        this.utUserNbrAction = utUserNbrAction;
    }


    @Column(name="ACTION_TM", nullable=false, length=7)
    public Date getActionTm() {
        return this.actionTm;
    }
    
    public void setActionTm(Date actionTm) {
        this.actionTm = actionTm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OeOrdDtlLogId) ) return false;
		 OeOrdDtlLogId castOther = ( OeOrdDtlLogId ) other; 
         
		 return (this.getOeOrdDtlNbr()==castOther.getOeOrdDtlNbr())
 && (this.getOeOrdHdrNbr()==castOther.getOeOrdHdrNbr())
 && (this.getOrgNbrCust()==castOther.getOrgNbrCust())
 && (this.getLineNbr()==castOther.getLineNbr())
 && ( (this.getCustLineCd()==castOther.getCustLineCd()) || ( this.getCustLineCd()!=null && castOther.getCustLineCd()!=null && this.getCustLineCd().equals(castOther.getCustLineCd()) ) )
 && (this.getItemNbrRqst()==castOther.getItemNbrRqst())
 && (this.getItemNbrOrd()==castOther.getItemNbrOrd())
 && ( (this.getQtyOrd()==castOther.getQtyOrd()) || ( this.getQtyOrd()!=null && castOther.getQtyOrd()!=null && this.getQtyOrd().equals(castOther.getQtyOrd()) ) )
 && ( (this.getQtyOrdStkUm()==castOther.getQtyOrdStkUm()) || ( this.getQtyOrdStkUm()!=null && castOther.getQtyOrdStkUm()!=null && this.getQtyOrdStkUm().equals(castOther.getQtyOrdStkUm()) ) )
 && ( (this.getSellUm()==castOther.getSellUm()) || ( this.getSellUm()!=null && castOther.getSellUm()!=null && this.getSellUm().equals(castOther.getSellUm()) ) )
 && ( (this.getRqstDt()==castOther.getRqstDt()) || ( this.getRqstDt()!=null && castOther.getRqstDt()!=null && this.getRqstDt().equals(castOther.getRqstDt()) ) )
 && (this.getShipToAddrNbr()==castOther.getShipToAddrNbr())
 && ( (this.getPromDtOrig()==castOther.getPromDtOrig()) || ( this.getPromDtOrig()!=null && castOther.getPromDtOrig()!=null && this.getPromDtOrig().equals(castOther.getPromDtOrig()) ) )
 && ( (this.getPromDtCurr()==castOther.getPromDtCurr()) || ( this.getPromDtCurr()!=null && castOther.getPromDtCurr()!=null && this.getPromDtCurr().equals(castOther.getPromDtCurr()) ) )
 && ( (this.getUnitPriceSellUm()==castOther.getUnitPriceSellUm()) || ( this.getUnitPriceSellUm()!=null && castOther.getUnitPriceSellUm()!=null && this.getUnitPriceSellUm().equals(castOther.getUnitPriceSellUm()) ) )
 && ( (this.getUnitPriceDenomSellUm()==castOther.getUnitPriceDenomSellUm()) || ( this.getUnitPriceDenomSellUm()!=null && castOther.getUnitPriceDenomSellUm()!=null && this.getUnitPriceDenomSellUm().equals(castOther.getUnitPriceDenomSellUm()) ) )
 && ( (this.getUnitPriceStkUm()==castOther.getUnitPriceStkUm()) || ( this.getUnitPriceStkUm()!=null && castOther.getUnitPriceStkUm()!=null && this.getUnitPriceStkUm().equals(castOther.getUnitPriceStkUm()) ) )
 && ( (this.getUnitPriceDenomStkUm()==castOther.getUnitPriceDenomStkUm()) || ( this.getUnitPriceDenomStkUm()!=null && castOther.getUnitPriceDenomStkUm()!=null && this.getUnitPriceDenomStkUm().equals(castOther.getUnitPriceDenomStkUm()) ) )
 && ( (this.getTieCd()==castOther.getTieCd()) || ( this.getTieCd()!=null && castOther.getTieCd()!=null && this.getTieCd().equals(castOther.getTieCd()) ) )
 && ( (this.getLineStatId()==castOther.getLineStatId()) || ( this.getLineStatId()!=null && castOther.getLineStatId()!=null && this.getLineStatId().equals(castOther.getLineStatId()) ) )
 && ( (this.getItemCdCust()==castOther.getItemCdCust()) || ( this.getItemCdCust()!=null && castOther.getItemCdCust()!=null && this.getItemCdCust().equals(castOther.getItemCdCust()) ) )
 && (this.getApsSrcRuleSetNbr()==castOther.getApsSrcRuleSetNbr())
 && ( (this.getOrgNbrMfrRqst()==castOther.getOrgNbrMfrRqst()) || ( this.getOrgNbrMfrRqst()!=null && castOther.getOrgNbrMfrRqst()!=null && this.getOrgNbrMfrRqst().equals(castOther.getOrgNbrMfrRqst()) ) )
 && ( (this.getLotNotExpireBeforeDt()==castOther.getLotNotExpireBeforeDt()) || ( this.getLotNotExpireBeforeDt()!=null && castOther.getLotNotExpireBeforeDt()!=null && this.getLotNotExpireBeforeDt().equals(castOther.getLotNotExpireBeforeDt()) ) )
 && ( (this.getLotManufactureAfterDt()==castOther.getLotManufactureAfterDt()) || ( this.getLotManufactureAfterDt()!=null && castOther.getLotManufactureAfterDt()!=null && this.getLotManufactureAfterDt().equals(castOther.getLotManufactureAfterDt()) ) )
 && ( (this.getCntryCdOrigin()==castOther.getCntryCdOrigin()) || ( this.getCntryCdOrigin()!=null && castOther.getCntryCdOrigin()!=null && this.getCntryCdOrigin().equals(castOther.getCntryCdOrigin()) ) )
 && ( (this.getRevLvl()==castOther.getRevLvl()) || ( this.getRevLvl()!=null && castOther.getRevLvl()!=null && this.getRevLvl().equals(castOther.getRevLvl()) ) )
 && ( (this.getShipViaCd()==castOther.getShipViaCd()) || ( this.getShipViaCd()!=null && castOther.getShipViaCd()!=null && this.getShipViaCd().equals(castOther.getShipViaCd()) ) )
 && ( (this.getContractCd()==castOther.getContractCd()) || ( this.getContractCd()!=null && castOther.getContractCd()!=null && this.getContractCd().equals(castOther.getContractCd()) ) )
 && ( (this.getCustBinCd()==castOther.getCustBinCd()) || ( this.getCustBinCd()!=null && castOther.getCustBinCd()!=null && this.getCustBinCd().equals(castOther.getCustBinCd()) ) )
 && ( (this.getPkgQty()==castOther.getPkgQty()) || ( this.getPkgQty()!=null && castOther.getPkgQty()!=null && this.getPkgQty().equals(castOther.getPkgQty()) ) )
 && ( (this.getPickPrtyCust()==castOther.getPickPrtyCust()) || ( this.getPickPrtyCust()!=null && castOther.getPickPrtyCust()!=null && this.getPickPrtyCust().equals(castOther.getPickPrtyCust()) ) )
 && ( (this.getPickPrtyRqst()==castOther.getPickPrtyRqst()) || ( this.getPickPrtyRqst()!=null && castOther.getPickPrtyRqst()!=null && this.getPickPrtyRqst().equals(castOther.getPickPrtyRqst()) ) )
 && ( (this.getPickPrtyPastDueMult()==castOther.getPickPrtyPastDueMult()) || ( this.getPickPrtyPastDueMult()!=null && castOther.getPickPrtyPastDueMult()!=null && this.getPickPrtyPastDueMult().equals(castOther.getPickPrtyPastDueMult()) ) )
 && ( (this.getQtyShip()==castOther.getQtyShip()) || ( this.getQtyShip()!=null && castOther.getQtyShip()!=null && this.getQtyShip().equals(castOther.getQtyShip()) ) )
 && ( (this.getQtyShipStkUm()==castOther.getQtyShipStkUm()) || ( this.getQtyShipStkUm()!=null && castOther.getQtyShipStkUm()!=null && this.getQtyShipStkUm().equals(castOther.getQtyShipStkUm()) ) )
 && ( (this.getQtyAlloc()==castOther.getQtyAlloc()) || ( this.getQtyAlloc()!=null && castOther.getQtyAlloc()!=null && this.getQtyAlloc().equals(castOther.getQtyAlloc()) ) )
 && ( (this.getQtyAllocStkUm()==castOther.getQtyAllocStkUm()) || ( this.getQtyAllocStkUm()!=null && castOther.getQtyAllocStkUm()!=null && this.getQtyAllocStkUm().equals(castOther.getQtyAllocStkUm()) ) )
 && ( (this.getPartMismatchReasonCd()==castOther.getPartMismatchReasonCd()) || ( this.getPartMismatchReasonCd()!=null && castOther.getPartMismatchReasonCd()!=null && this.getPartMismatchReasonCd().equals(castOther.getPartMismatchReasonCd()) ) )
 && ( (this.getCustRef()==castOther.getCustRef()) || ( this.getCustRef()!=null && castOther.getCustRef()!=null && this.getCustRef().equals(castOther.getCustRef()) ) )
 && ( (this.getShipFromFacility()==castOther.getShipFromFacility()) || ( this.getShipFromFacility()!=null && castOther.getShipFromFacility()!=null && this.getShipFromFacility().equals(castOther.getShipFromFacility()) ) )
 && ( (this.getShipCmpltFlg()==castOther.getShipCmpltFlg()) || ( this.getShipCmpltFlg()!=null && castOther.getShipCmpltFlg()!=null && this.getShipCmpltFlg().equals(castOther.getShipCmpltFlg()) ) )
 && ( (this.getHotFlg()==castOther.getHotFlg()) || ( this.getHotFlg()!=null && castOther.getHotFlg()!=null && this.getHotFlg().equals(castOther.getHotFlg()) ) )
 && ( (this.getShipLinePct()==castOther.getShipLinePct()) || ( this.getShipLinePct()!=null && castOther.getShipLinePct()!=null && this.getShipLinePct().equals(castOther.getShipLinePct()) ) )
 && ( (this.getCancelCd()==castOther.getCancelCd()) || ( this.getCancelCd()!=null && castOther.getCancelCd()!=null && this.getCancelCd().equals(castOther.getCancelCd()) ) )
 && ( (this.getCancelDt()==castOther.getCancelDt()) || ( this.getCancelDt()!=null && castOther.getCancelDt()!=null && this.getCancelDt().equals(castOther.getCancelDt()) ) )
 && ( (this.getUtUserNbrCancel()==castOther.getUtUserNbrCancel()) || ( this.getUtUserNbrCancel()!=null && castOther.getUtUserNbrCancel()!=null && this.getUtUserNbrCancel().equals(castOther.getUtUserNbrCancel()) ) )
 && ( (this.getCloseReasonCd()==castOther.getCloseReasonCd()) || ( this.getCloseReasonCd()!=null && castOther.getCloseReasonCd()!=null && this.getCloseReasonCd().equals(castOther.getCloseReasonCd()) ) )
 && ( (this.getCloseDt()==castOther.getCloseDt()) || ( this.getCloseDt()!=null && castOther.getCloseDt()!=null && this.getCloseDt().equals(castOther.getCloseDt()) ) )
 && ( (this.getUtUserNbrClose()==castOther.getUtUserNbrClose()) || ( this.getUtUserNbrClose()!=null && castOther.getUtUserNbrClose()!=null && this.getUtUserNbrClose().equals(castOther.getUtUserNbrClose()) ) )
 && (this.getUtUserNbr()==castOther.getUtUserNbr())
 && ( (this.getLastModDt()==castOther.getLastModDt()) || ( this.getLastModDt()!=null && castOther.getLastModDt()!=null && this.getLastModDt().equals(castOther.getLastModDt()) ) )
 && ( (this.getAction()==castOther.getAction()) || ( this.getAction()!=null && castOther.getAction()!=null && this.getAction().equals(castOther.getAction()) ) )
 && (this.getUtUserNbrAction()==castOther.getUtUserNbrAction())
 && ( (this.getActionTm()==castOther.getActionTm()) || ( this.getActionTm()!=null && castOther.getActionTm()!=null && this.getActionTm().equals(castOther.getActionTm()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOeOrdDtlNbr();
         result = 37 * result + this.getOeOrdHdrNbr();
         result = 37 * result + this.getOrgNbrCust();
         result = 37 * result + this.getLineNbr();
         result = 37 * result + ( getCustLineCd() == null ? 0 : this.getCustLineCd().hashCode() );
         result = 37 * result + this.getItemNbrRqst();
         result = 37 * result + this.getItemNbrOrd();
         result = 37 * result + ( getQtyOrd() == null ? 0 : this.getQtyOrd().hashCode() );
         result = 37 * result + ( getQtyOrdStkUm() == null ? 0 : this.getQtyOrdStkUm().hashCode() );
         result = 37 * result + ( getSellUm() == null ? 0 : this.getSellUm().hashCode() );
         result = 37 * result + ( getRqstDt() == null ? 0 : this.getRqstDt().hashCode() );
         result = 37 * result + this.getShipToAddrNbr();
         result = 37 * result + ( getPromDtOrig() == null ? 0 : this.getPromDtOrig().hashCode() );
         result = 37 * result + ( getPromDtCurr() == null ? 0 : this.getPromDtCurr().hashCode() );
         result = 37 * result + ( getUnitPriceSellUm() == null ? 0 : this.getUnitPriceSellUm().hashCode() );
         result = 37 * result + ( getUnitPriceDenomSellUm() == null ? 0 : this.getUnitPriceDenomSellUm().hashCode() );
         result = 37 * result + ( getUnitPriceStkUm() == null ? 0 : this.getUnitPriceStkUm().hashCode() );
         result = 37 * result + ( getUnitPriceDenomStkUm() == null ? 0 : this.getUnitPriceDenomStkUm().hashCode() );
         result = 37 * result + ( getTieCd() == null ? 0 : this.getTieCd().hashCode() );
         result = 37 * result + ( getLineStatId() == null ? 0 : this.getLineStatId().hashCode() );
         result = 37 * result + ( getItemCdCust() == null ? 0 : this.getItemCdCust().hashCode() );
         result = 37 * result + this.getApsSrcRuleSetNbr();
         result = 37 * result + ( getOrgNbrMfrRqst() == null ? 0 : this.getOrgNbrMfrRqst().hashCode() );
         result = 37 * result + ( getLotNotExpireBeforeDt() == null ? 0 : this.getLotNotExpireBeforeDt().hashCode() );
         result = 37 * result + ( getLotManufactureAfterDt() == null ? 0 : this.getLotManufactureAfterDt().hashCode() );
         result = 37 * result + ( getCntryCdOrigin() == null ? 0 : this.getCntryCdOrigin().hashCode() );
         result = 37 * result + ( getRevLvl() == null ? 0 : this.getRevLvl().hashCode() );
         result = 37 * result + ( getShipViaCd() == null ? 0 : this.getShipViaCd().hashCode() );
         result = 37 * result + ( getContractCd() == null ? 0 : this.getContractCd().hashCode() );
         result = 37 * result + ( getCustBinCd() == null ? 0 : this.getCustBinCd().hashCode() );
         result = 37 * result + ( getPkgQty() == null ? 0 : this.getPkgQty().hashCode() );
         result = 37 * result + ( getPickPrtyCust() == null ? 0 : this.getPickPrtyCust().hashCode() );
         result = 37 * result + ( getPickPrtyRqst() == null ? 0 : this.getPickPrtyRqst().hashCode() );
         result = 37 * result + ( getPickPrtyPastDueMult() == null ? 0 : this.getPickPrtyPastDueMult().hashCode() );
         result = 37 * result + ( getQtyShip() == null ? 0 : this.getQtyShip().hashCode() );
         result = 37 * result + ( getQtyShipStkUm() == null ? 0 : this.getQtyShipStkUm().hashCode() );
         result = 37 * result + ( getQtyAlloc() == null ? 0 : this.getQtyAlloc().hashCode() );
         result = 37 * result + ( getQtyAllocStkUm() == null ? 0 : this.getQtyAllocStkUm().hashCode() );
         result = 37 * result + ( getPartMismatchReasonCd() == null ? 0 : this.getPartMismatchReasonCd().hashCode() );
         result = 37 * result + ( getCustRef() == null ? 0 : this.getCustRef().hashCode() );
         result = 37 * result + ( getShipFromFacility() == null ? 0 : this.getShipFromFacility().hashCode() );
         result = 37 * result + ( getShipCmpltFlg() == null ? 0 : this.getShipCmpltFlg().hashCode() );
         result = 37 * result + ( getHotFlg() == null ? 0 : this.getHotFlg().hashCode() );
         result = 37 * result + ( getShipLinePct() == null ? 0 : this.getShipLinePct().hashCode() );
         result = 37 * result + ( getCancelCd() == null ? 0 : this.getCancelCd().hashCode() );
         result = 37 * result + ( getCancelDt() == null ? 0 : this.getCancelDt().hashCode() );
         result = 37 * result + ( getUtUserNbrCancel() == null ? 0 : this.getUtUserNbrCancel().hashCode() );
         result = 37 * result + ( getCloseReasonCd() == null ? 0 : this.getCloseReasonCd().hashCode() );
         result = 37 * result + ( getCloseDt() == null ? 0 : this.getCloseDt().hashCode() );
         result = 37 * result + ( getUtUserNbrClose() == null ? 0 : this.getUtUserNbrClose().hashCode() );
         result = 37 * result + this.getUtUserNbr();
         result = 37 * result + ( getLastModDt() == null ? 0 : this.getLastModDt().hashCode() );
         result = 37 * result + ( getAction() == null ? 0 : this.getAction().hashCode() );
         result = 37 * result + this.getUtUserNbrAction();
         result = 37 * result + ( getActionTm() == null ? 0 : this.getActionTm().hashCode() );
         return result;
   }   


}


