package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PlanGrp1 generated by hbm2java
 */
@Entity
@Table(name="PLAN_GRP_1"
)
public class PlanGrp1  implements java.io.Serializable {


     private PlanGrp1Id id;

    public PlanGrp1() {
    }

    public PlanGrp1(PlanGrp1Id id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="itemNbrOther", column=@Column(name="ITEM_NBR_OTHER", precision=9, scale=0) ) } )
    public PlanGrp1Id getId() {
        return this.id;
    }
    
    public void setId(PlanGrp1Id id) {
        this.id = id;
    }




}


