package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PoLineHdrCertId generated by hbm2java
 */
@Embeddable
public class PoLineHdrCertId  implements java.io.Serializable {


     private int poLineHdrNbr;
     private String certCd;

    public PoLineHdrCertId() {
    }

    public PoLineHdrCertId(int poLineHdrNbr, String certCd) {
       this.poLineHdrNbr = poLineHdrNbr;
       this.certCd = certCd;
    }
   


    @Column(name="PO_LINE_HDR_NBR", nullable=false, precision=9, scale=0)
    public int getPoLineHdrNbr() {
        return this.poLineHdrNbr;
    }
    
    public void setPoLineHdrNbr(int poLineHdrNbr) {
        this.poLineHdrNbr = poLineHdrNbr;
    }


    @Column(name="CERT_CD", nullable=false, length=8)
    public String getCertCd() {
        return this.certCd;
    }
    
    public void setCertCd(String certCd) {
        this.certCd = certCd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PoLineHdrCertId) ) return false;
		 PoLineHdrCertId castOther = ( PoLineHdrCertId ) other; 
         
		 return (this.getPoLineHdrNbr()==castOther.getPoLineHdrNbr())
 && ( (this.getCertCd()==castOther.getCertCd()) || ( this.getCertCd()!=null && castOther.getCertCd()!=null && this.getCertCd().equals(castOther.getCertCd()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPoLineHdrNbr();
         result = 37 * result + ( getCertCd() == null ? 0 : this.getCertCd().hashCode() );
         return result;
   }   


}


