package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PoLineCert generated by hbm2java
 */
@Entity
@Table(name="PO_LINE_CERT"
)
public class PoLineCert  implements java.io.Serializable {


     private PoLineCertId id;

    public PoLineCert() {
    }

    public PoLineCert(PoLineCertId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="poLineHdrNbr", column=@Column(name="PO_LINE_HDR_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", nullable=false, precision=9, scale=0) ) } )
    public PoLineCertId getId() {
        return this.id;
    }
    
    public void setId(PoLineCertId id) {
        this.id = id;
    }




}


