package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PoLineCertId generated by hbm2java
 */
@Embeddable
public class PoLineCertId  implements java.io.Serializable {


     private int poLineHdrNbr;
     private int itemNbr;

    public PoLineCertId() {
    }

    public PoLineCertId(int poLineHdrNbr, int itemNbr) {
       this.poLineHdrNbr = poLineHdrNbr;
       this.itemNbr = itemNbr;
    }
   


    @Column(name="PO_LINE_HDR_NBR", nullable=false, precision=9, scale=0)
    public int getPoLineHdrNbr() {
        return this.poLineHdrNbr;
    }
    
    public void setPoLineHdrNbr(int poLineHdrNbr) {
        this.poLineHdrNbr = poLineHdrNbr;
    }


    @Column(name="ITEM_NBR", nullable=false, precision=9, scale=0)
    public int getItemNbr() {
        return this.itemNbr;
    }
    
    public void setItemNbr(int itemNbr) {
        this.itemNbr = itemNbr;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PoLineCertId) ) return false;
		 PoLineCertId castOther = ( PoLineCertId ) other; 
         
		 return (this.getPoLineHdrNbr()==castOther.getPoLineHdrNbr())
 && (this.getItemNbr()==castOther.getItemNbr());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPoLineHdrNbr();
         result = 37 * result + this.getItemNbr();
         return result;
   }   


}


