package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PoMfrMastVw generated by hbm2java
 */
@Entity
@Table(name="PO_MFR_MAST_VW"
)
public class PoMfrMastVw  implements java.io.Serializable {


     private PoMfrMastVwId id;

    public PoMfrMastVw() {
    }

    public PoMfrMastVw(PoMfrMastVwId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orgNbrMfr", column=@Column(name="ORG_NBR_MFR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="statId", column=@Column(name="STAT_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="mailToAddrNbrDflt", column=@Column(name="MAIL_TO_ADDR_NBR_DFLT", precision=9, scale=0) ), 
        @AttributeOverride(name="billToAddrNbrDflt", column=@Column(name="BILL_TO_ADDR_NBR_DFLT", precision=9, scale=0) ), 
        @AttributeOverride(name="orgCdMfr", column=@Column(name="ORG_CD_MFR", nullable=false, length=15) ), 
        @AttributeOverride(name="orgNmMfr", column=@Column(name="ORG_NM_MFR", nullable=false, length=60) ), 
        @AttributeOverride(name="introDt", column=@Column(name="INTRO_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="phnNbrDflt", column=@Column(name="PHN_NBR_DFLT", length=20) ), 
        @AttributeOverride(name="faxNbrDflt", column=@Column(name="FAX_NBR_DFLT", length=20) ), 
        @AttributeOverride(name="mfrCageCd", column=@Column(name="MFR_CAGE_CD", length=10) ) } )
    public PoMfrMastVwId getId() {
        return this.id;
    }
    
    public void setId(PoMfrMastVwId id) {
        this.id = id;
    }




}


