package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PoMfrMastVwId generated by hbm2java
 */
@Embeddable
public class PoMfrMastVwId  implements java.io.Serializable {


     private int orgNbrMfr;
     private String statId;
     private Integer mailToAddrNbrDflt;
     private Integer billToAddrNbrDflt;
     private String orgCdMfr;
     private String orgNmMfr;
     private Date introDt;
     private String phnNbrDflt;
     private String faxNbrDflt;
     private String mfrCageCd;

    public PoMfrMastVwId() {
    }

	
    public PoMfrMastVwId(int orgNbrMfr, String statId, String orgCdMfr, String orgNmMfr, Date introDt) {
        this.orgNbrMfr = orgNbrMfr;
        this.statId = statId;
        this.orgCdMfr = orgCdMfr;
        this.orgNmMfr = orgNmMfr;
        this.introDt = introDt;
    }
    public PoMfrMastVwId(int orgNbrMfr, String statId, Integer mailToAddrNbrDflt, Integer billToAddrNbrDflt, String orgCdMfr, String orgNmMfr, Date introDt, String phnNbrDflt, String faxNbrDflt, String mfrCageCd) {
       this.orgNbrMfr = orgNbrMfr;
       this.statId = statId;
       this.mailToAddrNbrDflt = mailToAddrNbrDflt;
       this.billToAddrNbrDflt = billToAddrNbrDflt;
       this.orgCdMfr = orgCdMfr;
       this.orgNmMfr = orgNmMfr;
       this.introDt = introDt;
       this.phnNbrDflt = phnNbrDflt;
       this.faxNbrDflt = faxNbrDflt;
       this.mfrCageCd = mfrCageCd;
    }
   


    @Column(name="ORG_NBR_MFR", nullable=false, precision=9, scale=0)
    public int getOrgNbrMfr() {
        return this.orgNbrMfr;
    }
    
    public void setOrgNbrMfr(int orgNbrMfr) {
        this.orgNbrMfr = orgNbrMfr;
    }


    @Column(name="STAT_ID", nullable=false, length=1)
    public String getStatId() {
        return this.statId;
    }
    
    public void setStatId(String statId) {
        this.statId = statId;
    }


    @Column(name="MAIL_TO_ADDR_NBR_DFLT", precision=9, scale=0)
    public Integer getMailToAddrNbrDflt() {
        return this.mailToAddrNbrDflt;
    }
    
    public void setMailToAddrNbrDflt(Integer mailToAddrNbrDflt) {
        this.mailToAddrNbrDflt = mailToAddrNbrDflt;
    }


    @Column(name="BILL_TO_ADDR_NBR_DFLT", precision=9, scale=0)
    public Integer getBillToAddrNbrDflt() {
        return this.billToAddrNbrDflt;
    }
    
    public void setBillToAddrNbrDflt(Integer billToAddrNbrDflt) {
        this.billToAddrNbrDflt = billToAddrNbrDflt;
    }


    @Column(name="ORG_CD_MFR", nullable=false, length=15)
    public String getOrgCdMfr() {
        return this.orgCdMfr;
    }
    
    public void setOrgCdMfr(String orgCdMfr) {
        this.orgCdMfr = orgCdMfr;
    }


    @Column(name="ORG_NM_MFR", nullable=false, length=60)
    public String getOrgNmMfr() {
        return this.orgNmMfr;
    }
    
    public void setOrgNmMfr(String orgNmMfr) {
        this.orgNmMfr = orgNmMfr;
    }


    @Column(name="INTRO_DT", nullable=false, length=7)
    public Date getIntroDt() {
        return this.introDt;
    }
    
    public void setIntroDt(Date introDt) {
        this.introDt = introDt;
    }


    @Column(name="PHN_NBR_DFLT", length=20)
    public String getPhnNbrDflt() {
        return this.phnNbrDflt;
    }
    
    public void setPhnNbrDflt(String phnNbrDflt) {
        this.phnNbrDflt = phnNbrDflt;
    }


    @Column(name="FAX_NBR_DFLT", length=20)
    public String getFaxNbrDflt() {
        return this.faxNbrDflt;
    }
    
    public void setFaxNbrDflt(String faxNbrDflt) {
        this.faxNbrDflt = faxNbrDflt;
    }


    @Column(name="MFR_CAGE_CD", length=10)
    public String getMfrCageCd() {
        return this.mfrCageCd;
    }
    
    public void setMfrCageCd(String mfrCageCd) {
        this.mfrCageCd = mfrCageCd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PoMfrMastVwId) ) return false;
		 PoMfrMastVwId castOther = ( PoMfrMastVwId ) other; 
         
		 return (this.getOrgNbrMfr()==castOther.getOrgNbrMfr())
 && ( (this.getStatId()==castOther.getStatId()) || ( this.getStatId()!=null && castOther.getStatId()!=null && this.getStatId().equals(castOther.getStatId()) ) )
 && ( (this.getMailToAddrNbrDflt()==castOther.getMailToAddrNbrDflt()) || ( this.getMailToAddrNbrDflt()!=null && castOther.getMailToAddrNbrDflt()!=null && this.getMailToAddrNbrDflt().equals(castOther.getMailToAddrNbrDflt()) ) )
 && ( (this.getBillToAddrNbrDflt()==castOther.getBillToAddrNbrDflt()) || ( this.getBillToAddrNbrDflt()!=null && castOther.getBillToAddrNbrDflt()!=null && this.getBillToAddrNbrDflt().equals(castOther.getBillToAddrNbrDflt()) ) )
 && ( (this.getOrgCdMfr()==castOther.getOrgCdMfr()) || ( this.getOrgCdMfr()!=null && castOther.getOrgCdMfr()!=null && this.getOrgCdMfr().equals(castOther.getOrgCdMfr()) ) )
 && ( (this.getOrgNmMfr()==castOther.getOrgNmMfr()) || ( this.getOrgNmMfr()!=null && castOther.getOrgNmMfr()!=null && this.getOrgNmMfr().equals(castOther.getOrgNmMfr()) ) )
 && ( (this.getIntroDt()==castOther.getIntroDt()) || ( this.getIntroDt()!=null && castOther.getIntroDt()!=null && this.getIntroDt().equals(castOther.getIntroDt()) ) )
 && ( (this.getPhnNbrDflt()==castOther.getPhnNbrDflt()) || ( this.getPhnNbrDflt()!=null && castOther.getPhnNbrDflt()!=null && this.getPhnNbrDflt().equals(castOther.getPhnNbrDflt()) ) )
 && ( (this.getFaxNbrDflt()==castOther.getFaxNbrDflt()) || ( this.getFaxNbrDflt()!=null && castOther.getFaxNbrDflt()!=null && this.getFaxNbrDflt().equals(castOther.getFaxNbrDflt()) ) )
 && ( (this.getMfrCageCd()==castOther.getMfrCageCd()) || ( this.getMfrCageCd()!=null && castOther.getMfrCageCd()!=null && this.getMfrCageCd().equals(castOther.getMfrCageCd()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrgNbrMfr();
         result = 37 * result + ( getStatId() == null ? 0 : this.getStatId().hashCode() );
         result = 37 * result + ( getMailToAddrNbrDflt() == null ? 0 : this.getMailToAddrNbrDflt().hashCode() );
         result = 37 * result + ( getBillToAddrNbrDflt() == null ? 0 : this.getBillToAddrNbrDflt().hashCode() );
         result = 37 * result + ( getOrgCdMfr() == null ? 0 : this.getOrgCdMfr().hashCode() );
         result = 37 * result + ( getOrgNmMfr() == null ? 0 : this.getOrgNmMfr().hashCode() );
         result = 37 * result + ( getIntroDt() == null ? 0 : this.getIntroDt().hashCode() );
         result = 37 * result + ( getPhnNbrDflt() == null ? 0 : this.getPhnNbrDflt().hashCode() );
         result = 37 * result + ( getFaxNbrDflt() == null ? 0 : this.getFaxNbrDflt().hashCode() );
         result = 37 * result + ( getMfrCageCd() == null ? 0 : this.getMfrCageCd().hashCode() );
         return result;
   }   


}


