package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PoOrdHdr generated by hbm2java
 */
@Entity
@Table(name="PO_ORD_HDR"
)
public class PoOrdHdr  implements java.io.Serializable {


     private int poOrdHdrNbr;
     private PoVndMast poVndMast;
     private NaIndiv naIndiv;
     private NaOrgAddr naOrgAddrByShipToAddrNbrDflt;
     private NaOrgAddr naOrgAddrByAddrNbrVnd;
     private String poCd;
     private Date poDt;
     private String currCd;
     private int billToAddrNbr;
     private short nextPoLineNbr;
     private String ordStatId;
     private String vndrOrdCd;
     private String termCd;
     private String fobCd;
     private String trdFlg;
     private int utUserNbr;
     private Date lastModDt;
     private String shipViaCdDflt;
     private String cancelCd;
     private Date cancelDt;
     private Integer utUserNbrCancel;
     private String indivNmSeller;
     private String sellerPhnNbr;
     private String sellerEmailAddr;
     private String ackFlg;
     private String sellerFaxNbr;
     private String transmitFlg;
     private String poTypeId;
     private Set<PoLineHdr> poLineHdrs = new HashSet<PoLineHdr>(0);
     private Set<PoUnplannedRcpt> poUnplannedRcpts = new HashSet<PoUnplannedRcpt>(0);
     private Set<IcLotMast> icLotMasts = new HashSet<IcLotMast>(0);

    public PoOrdHdr() {
    }

	
    public PoOrdHdr(int poOrdHdrNbr, PoVndMast poVndMast, NaIndiv naIndiv, NaOrgAddr naOrgAddrByShipToAddrNbrDflt, NaOrgAddr naOrgAddrByAddrNbrVnd, String poCd, Date poDt, String currCd, int billToAddrNbr, short nextPoLineNbr, String ordStatId, String trdFlg, int utUserNbr, Date lastModDt, String shipViaCdDflt, String ackFlg, String transmitFlg, String poTypeId) {
        this.poOrdHdrNbr = poOrdHdrNbr;
        this.poVndMast = poVndMast;
        this.naIndiv = naIndiv;
        this.naOrgAddrByShipToAddrNbrDflt = naOrgAddrByShipToAddrNbrDflt;
        this.naOrgAddrByAddrNbrVnd = naOrgAddrByAddrNbrVnd;
        this.poCd = poCd;
        this.poDt = poDt;
        this.currCd = currCd;
        this.billToAddrNbr = billToAddrNbr;
        this.nextPoLineNbr = nextPoLineNbr;
        this.ordStatId = ordStatId;
        this.trdFlg = trdFlg;
        this.utUserNbr = utUserNbr;
        this.lastModDt = lastModDt;
        this.shipViaCdDflt = shipViaCdDflt;
        this.ackFlg = ackFlg;
        this.transmitFlg = transmitFlg;
        this.poTypeId = poTypeId;
    }
    public PoOrdHdr(int poOrdHdrNbr, PoVndMast poVndMast, NaIndiv naIndiv, NaOrgAddr naOrgAddrByShipToAddrNbrDflt, NaOrgAddr naOrgAddrByAddrNbrVnd, String poCd, Date poDt, String currCd, int billToAddrNbr, short nextPoLineNbr, String ordStatId, String vndrOrdCd, String termCd, String fobCd, String trdFlg, int utUserNbr, Date lastModDt, String shipViaCdDflt, String cancelCd, Date cancelDt, Integer utUserNbrCancel, String indivNmSeller, String sellerPhnNbr, String sellerEmailAddr, String ackFlg, String sellerFaxNbr, String transmitFlg, String poTypeId, Set<PoLineHdr> poLineHdrs, Set<PoUnplannedRcpt> poUnplannedRcpts, Set<IcLotMast> icLotMasts) {
       this.poOrdHdrNbr = poOrdHdrNbr;
       this.poVndMast = poVndMast;
       this.naIndiv = naIndiv;
       this.naOrgAddrByShipToAddrNbrDflt = naOrgAddrByShipToAddrNbrDflt;
       this.naOrgAddrByAddrNbrVnd = naOrgAddrByAddrNbrVnd;
       this.poCd = poCd;
       this.poDt = poDt;
       this.currCd = currCd;
       this.billToAddrNbr = billToAddrNbr;
       this.nextPoLineNbr = nextPoLineNbr;
       this.ordStatId = ordStatId;
       this.vndrOrdCd = vndrOrdCd;
       this.termCd = termCd;
       this.fobCd = fobCd;
       this.trdFlg = trdFlg;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
       this.shipViaCdDflt = shipViaCdDflt;
       this.cancelCd = cancelCd;
       this.cancelDt = cancelDt;
       this.utUserNbrCancel = utUserNbrCancel;
       this.indivNmSeller = indivNmSeller;
       this.sellerPhnNbr = sellerPhnNbr;
       this.sellerEmailAddr = sellerEmailAddr;
       this.ackFlg = ackFlg;
       this.sellerFaxNbr = sellerFaxNbr;
       this.transmitFlg = transmitFlg;
       this.poTypeId = poTypeId;
       this.poLineHdrs = poLineHdrs;
       this.poUnplannedRcpts = poUnplannedRcpts;
       this.icLotMasts = icLotMasts;
    }
   
     @Id 

    
    @Column(name="PO_ORD_HDR_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getPoOrdHdrNbr() {
        return this.poOrdHdrNbr;
    }
    
    public void setPoOrdHdrNbr(int poOrdHdrNbr) {
        this.poOrdHdrNbr = poOrdHdrNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORG_NBR_VND", nullable=false)
    public PoVndMast getPoVndMast() {
        return this.poVndMast;
    }
    
    public void setPoVndMast(PoVndMast poVndMast) {
        this.poVndMast = poVndMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="INDIV_NBR_BUY", nullable=false)
    public NaIndiv getNaIndiv() {
        return this.naIndiv;
    }
    
    public void setNaIndiv(NaIndiv naIndiv) {
        this.naIndiv = naIndiv;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SHIP_TO_ADDR_NBR_DFLT", nullable=false)
    public NaOrgAddr getNaOrgAddrByShipToAddrNbrDflt() {
        return this.naOrgAddrByShipToAddrNbrDflt;
    }
    
    public void setNaOrgAddrByShipToAddrNbrDflt(NaOrgAddr naOrgAddrByShipToAddrNbrDflt) {
        this.naOrgAddrByShipToAddrNbrDflt = naOrgAddrByShipToAddrNbrDflt;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ADDR_NBR_VND", nullable=false)
    public NaOrgAddr getNaOrgAddrByAddrNbrVnd() {
        return this.naOrgAddrByAddrNbrVnd;
    }
    
    public void setNaOrgAddrByAddrNbrVnd(NaOrgAddr naOrgAddrByAddrNbrVnd) {
        this.naOrgAddrByAddrNbrVnd = naOrgAddrByAddrNbrVnd;
    }

    
    @Column(name="PO_CD", unique=true, nullable=false, length=20)
    public String getPoCd() {
        return this.poCd;
    }
    
    public void setPoCd(String poCd) {
        this.poCd = poCd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PO_DT", nullable=false, length=7)
    public Date getPoDt() {
        return this.poDt;
    }
    
    public void setPoDt(Date poDt) {
        this.poDt = poDt;
    }

    
    @Column(name="CURR_CD", nullable=false, length=3)
    public String getCurrCd() {
        return this.currCd;
    }
    
    public void setCurrCd(String currCd) {
        this.currCd = currCd;
    }

    
    @Column(name="BILL_TO_ADDR_NBR", nullable=false, precision=9, scale=0)
    public int getBillToAddrNbr() {
        return this.billToAddrNbr;
    }
    
    public void setBillToAddrNbr(int billToAddrNbr) {
        this.billToAddrNbr = billToAddrNbr;
    }

    
    @Column(name="NEXT_PO_LINE_NBR", nullable=false, precision=3, scale=0)
    public short getNextPoLineNbr() {
        return this.nextPoLineNbr;
    }
    
    public void setNextPoLineNbr(short nextPoLineNbr) {
        this.nextPoLineNbr = nextPoLineNbr;
    }

    
    @Column(name="ORD_STAT_ID", nullable=false, length=1)
    public String getOrdStatId() {
        return this.ordStatId;
    }
    
    public void setOrdStatId(String ordStatId) {
        this.ordStatId = ordStatId;
    }

    
    @Column(name="VNDR_ORD_CD", length=20)
    public String getVndrOrdCd() {
        return this.vndrOrdCd;
    }
    
    public void setVndrOrdCd(String vndrOrdCd) {
        this.vndrOrdCd = vndrOrdCd;
    }

    
    @Column(name="TERM_CD", length=10)
    public String getTermCd() {
        return this.termCd;
    }
    
    public void setTermCd(String termCd) {
        this.termCd = termCd;
    }

    
    @Column(name="FOB_CD", length=8)
    public String getFobCd() {
        return this.fobCd;
    }
    
    public void setFobCd(String fobCd) {
        this.fobCd = fobCd;
    }

    
    @Column(name="TRD_FLG", nullable=false, length=1)
    public String getTrdFlg() {
        return this.trdFlg;
    }
    
    public void setTrdFlg(String trdFlg) {
        this.trdFlg = trdFlg;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }

    
    @Column(name="SHIP_VIA_CD_DFLT", nullable=false, length=8)
    public String getShipViaCdDflt() {
        return this.shipViaCdDflt;
    }
    
    public void setShipViaCdDflt(String shipViaCdDflt) {
        this.shipViaCdDflt = shipViaCdDflt;
    }

    
    @Column(name="CANCEL_CD", length=8)
    public String getCancelCd() {
        return this.cancelCd;
    }
    
    public void setCancelCd(String cancelCd) {
        this.cancelCd = cancelCd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CANCEL_DT", length=7)
    public Date getCancelDt() {
        return this.cancelDt;
    }
    
    public void setCancelDt(Date cancelDt) {
        this.cancelDt = cancelDt;
    }

    
    @Column(name="UT_USER_NBR_CANCEL", precision=9, scale=0)
    public Integer getUtUserNbrCancel() {
        return this.utUserNbrCancel;
    }
    
    public void setUtUserNbrCancel(Integer utUserNbrCancel) {
        this.utUserNbrCancel = utUserNbrCancel;
    }

    
    @Column(name="INDIV_NM_SELLER", length=45)
    public String getIndivNmSeller() {
        return this.indivNmSeller;
    }
    
    public void setIndivNmSeller(String indivNmSeller) {
        this.indivNmSeller = indivNmSeller;
    }

    
    @Column(name="SELLER_PHN_NBR", length=20)
    public String getSellerPhnNbr() {
        return this.sellerPhnNbr;
    }
    
    public void setSellerPhnNbr(String sellerPhnNbr) {
        this.sellerPhnNbr = sellerPhnNbr;
    }

    
    @Column(name="SELLER_EMAIL_ADDR", length=40)
    public String getSellerEmailAddr() {
        return this.sellerEmailAddr;
    }
    
    public void setSellerEmailAddr(String sellerEmailAddr) {
        this.sellerEmailAddr = sellerEmailAddr;
    }

    
    @Column(name="ACK_FLG", nullable=false, length=1)
    public String getAckFlg() {
        return this.ackFlg;
    }
    
    public void setAckFlg(String ackFlg) {
        this.ackFlg = ackFlg;
    }

    
    @Column(name="SELLER_FAX_NBR", length=20)
    public String getSellerFaxNbr() {
        return this.sellerFaxNbr;
    }
    
    public void setSellerFaxNbr(String sellerFaxNbr) {
        this.sellerFaxNbr = sellerFaxNbr;
    }

    
    @Column(name="TRANSMIT_FLG", nullable=false, length=1)
    public String getTransmitFlg() {
        return this.transmitFlg;
    }
    
    public void setTransmitFlg(String transmitFlg) {
        this.transmitFlg = transmitFlg;
    }

    
    @Column(name="PO_TYPE_ID", nullable=false, length=1)
    public String getPoTypeId() {
        return this.poTypeId;
    }
    
    public void setPoTypeId(String poTypeId) {
        this.poTypeId = poTypeId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="poOrdHdr")
    public Set<PoLineHdr> getPoLineHdrs() {
        return this.poLineHdrs;
    }
    
    public void setPoLineHdrs(Set<PoLineHdr> poLineHdrs) {
        this.poLineHdrs = poLineHdrs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="poOrdHdr")
    public Set<PoUnplannedRcpt> getPoUnplannedRcpts() {
        return this.poUnplannedRcpts;
    }
    
    public void setPoUnplannedRcpts(Set<PoUnplannedRcpt> poUnplannedRcpts) {
        this.poUnplannedRcpts = poUnplannedRcpts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="poOrdHdr")
    public Set<IcLotMast> getIcLotMasts() {
        return this.icLotMasts;
    }
    
    public void setIcLotMasts(Set<IcLotMast> icLotMasts) {
        this.icLotMasts = icLotMasts;
    }




}


