package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PoOrdDtl generated by hbm2java
 */
@Entity
@Table(name="PO_ORD_DTL"
)
public class PoOrdDtl  implements java.io.Serializable {


     private PoOrdDtlId id;

    public PoOrdDtl() {
    }

    public PoOrdDtl(PoOrdDtlId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="poLineDtlNbr", column=@Column(name="PO_LINE_DTL_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="poOrdHdrNbr", column=@Column(name="PO_ORD_HDR_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="poLineHdrNbr", column=@Column(name="PO_LINE_HDR_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="poLineNbr", column=@Column(name="PO_LINE_NBR", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="poCd", column=@Column(name="PO_CD", nullable=false, length=20) ), 
        @AttributeOverride(name="poDt", column=@Column(name="PO_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="vndrOrdCd", column=@Column(name="VNDR_ORD_CD", length=20) ), 
        @AttributeOverride(name="currCd", column=@Column(name="CURR_CD", nullable=false, length=3) ), 
        @AttributeOverride(name="trdFlg", column=@Column(name="TRD_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="orgNbrVnd", column=@Column(name="ORG_NBR_VND", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="orgCdVnd", column=@Column(name="ORG_CD_VND", nullable=false, length=15) ), 
        @AttributeOverride(name="orgNmVnd", column=@Column(name="ORG_NM_VND", nullable=false, length=60) ), 
        @AttributeOverride(name="vndrOrdLineCd", column=@Column(name="VNDR_ORD_LINE_CD", length=3) ), 
        @AttributeOverride(name="replenQty", column=@Column(name="REPLEN_QTY", nullable=false, precision=13, scale=5) ), 
        @AttributeOverride(name="unitCost", column=@Column(name="UNIT_COST", nullable=false, precision=13, scale=5) ), 
        @AttributeOverride(name="unitCostDenom", column=@Column(name="UNIT_COST_DENOM", nullable=false, precision=13, scale=5) ), 
        @AttributeOverride(name="schedQty", column=@Column(name="SCHED_QTY", nullable=false, precision=13, scale=5) ), 
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="itemCd", column=@Column(name="ITEM_CD", nullable=false, length=50) ), 
        @AttributeOverride(name="itemDescr", column=@Column(name="ITEM_DESCR", nullable=false, length=50) ), 
        @AttributeOverride(name="stkUm", column=@Column(name="STK_UM", nullable=false, length=3) ), 
        @AttributeOverride(name="itemCdVnd", column=@Column(name="ITEM_CD_VND", length=50) ), 
        @AttributeOverride(name="replenUm", column=@Column(name="REPLEN_UM", nullable=false, length=3) ), 
        @AttributeOverride(name="recvQty", column=@Column(name="RECV_QTY", precision=13, scale=5) ), 
        @AttributeOverride(name="replenEstShipDt", column=@Column(name="REPLEN_EST_SHIP_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="replenRqstShipDt", column=@Column(name="REPLEN_RQST_SHIP_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="replenCurrEstDt", column=@Column(name="REPLEN_CURR_EST_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="revLvl", column=@Column(name="REV_LVL", length=5) ), 
        @AttributeOverride(name="orgNbrMfr", column=@Column(name="ORG_NBR_MFR", precision=9, scale=0) ), 
        @AttributeOverride(name="orgCdMfr", column=@Column(name="ORG_CD_MFR", length=15) ), 
        @AttributeOverride(name="orgNmMfr", column=@Column(name="ORG_NM_MFR", length=60) ), 
        @AttributeOverride(name="lineStatId", column=@Column(name="LINE_STAT_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="cntryCdOrigin", column=@Column(name="CNTRY_CD_ORIGIN", length=3) ), 
        @AttributeOverride(name="facility", column=@Column(name="FACILITY", nullable=false, length=16) ), 
        @AttributeOverride(name="apsSplySubPoolNbr", column=@Column(name="APS_SPLY_SUB_POOL_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="shipViaCd", column=@Column(name="SHIP_VIA_CD", nullable=false, length=8) ), 
        @AttributeOverride(name="shipToAddrNbr", column=@Column(name="SHIP_TO_ADDR_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="apsSplyPoolCd", column=@Column(name="APS_SPLY_POOL_CD", nullable=false, length=20) ), 
        @AttributeOverride(name="apsSplySubPoolCd", column=@Column(name="APS_SPLY_SUB_POOL_CD", nullable=false, length=20) ), 
        @AttributeOverride(name="icCategoryNbr", column=@Column(name="IC_CATEGORY_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="poCancelCd", column=@Column(name="PO_CANCEL_CD", length=8) ), 
        @AttributeOverride(name="lineCancelCd", column=@Column(name="LINE_CANCEL_CD", length=8) ), 
        @AttributeOverride(name="schedCancelCd", column=@Column(name="SCHED_CANCEL_CD", length=8) ), 
        @AttributeOverride(name="reqrMfrFlg", column=@Column(name="REQR_MFR_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="stdCost", column=@Column(name="STD_COST", precision=17, scale=6) ), 
        @AttributeOverride(name="listPrice", column=@Column(name="LIST_PRICE", precision=17, scale=6) ), 
        @AttributeOverride(name="indivNbrBuy", column=@Column(name="INDIV_NBR_BUY", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="indivNmSeller", column=@Column(name="INDIV_NM_SELLER", length=45) ), 
        @AttributeOverride(name="sellerPhnNbr", column=@Column(name="SELLER_PHN_NBR", length=20) ), 
        @AttributeOverride(name="sellerEmailAddr", column=@Column(name="SELLER_EMAIL_ADDR", length=40) ), 
        @AttributeOverride(name="schedQtyStkUm", column=@Column(name="SCHED_QTY_STK_UM", nullable=false, precision=13, scale=5) ), 
        @AttributeOverride(name="recvQtyStkUm", column=@Column(name="RECV_QTY_STK_UM", precision=13, scale=5) ), 
        @AttributeOverride(name="unitCostStkUm", column=@Column(name="UNIT_COST_STK_UM", nullable=false, precision=17, scale=6) ), 
        @AttributeOverride(name="unitCostDenomStkUm", column=@Column(name="UNIT_COST_DENOM_STK_UM", precision=17, scale=6) ), 
        @AttributeOverride(name="ordStatId", column=@Column(name="ORD_STAT_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="lotManufactureAfterDt", column=@Column(name="LOT_MANUFACTURE_AFTER_DT", length=7) ), 
        @AttributeOverride(name="lotNotExpireBeforeDt", column=@Column(name="LOT_NOT_EXPIRE_BEFORE_DT", length=7) ), 
        @AttributeOverride(name="apsAvailDt", column=@Column(name="APS_AVAIL_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="buyReasonCd", column=@Column(name="BUY_REASON_CD", length=8) ) } )
    public PoOrdDtlId getId() {
        return this.id;
    }
    
    public void setId(PoOrdDtlId id) {
        this.id = id;
    }




}


