package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PoResched generated by hbm2java
 */
@Entity
@Table(name="PO_RESCHED"
)
public class PoResched  implements java.io.Serializable {


     private PoReschedId id;
     private PoLineDtl poLineDtl;
     private PoVndMast poVndMast;

    public PoResched() {
    }

	
    public PoResched(PoReschedId id) {
        this.id = id;
    }
    public PoResched(PoReschedId id, PoLineDtl poLineDtl, PoVndMast poVndMast) {
       this.id = id;
       this.poLineDtl = poLineDtl;
       this.poVndMast = poVndMast;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="poLineDtlNbr", column=@Column(name="PO_LINE_DTL_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="reschedDt", column=@Column(name="RESCHED_DT", length=7) ), 
        @AttributeOverride(name="reschedQty", column=@Column(name="RESCHED_QTY", precision=13, scale=5) ), 
        @AttributeOverride(name="orgNbrVnd", column=@Column(name="ORG_NBR_VND", precision=9, scale=0) ) } )
    public PoReschedId getId() {
        return this.id;
    }
    
    public void setId(PoReschedId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PO_LINE_DTL_NBR", insertable=false, updatable=false)
    public PoLineDtl getPoLineDtl() {
        return this.poLineDtl;
    }
    
    public void setPoLineDtl(PoLineDtl poLineDtl) {
        this.poLineDtl = poLineDtl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORG_NBR_VND", insertable=false, updatable=false)
    public PoVndMast getPoVndMast() {
        return this.poVndMast;
    }
    
    public void setPoVndMast(PoVndMast poVndMast) {
        this.poVndMast = poVndMast;
    }




}


