package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PoRequisitionId generated by hbm2java
 */
@Embeddable
public class PoRequisitionId  implements java.io.Serializable {


     private int itemNbr;
     private String facility;
     private Date needByDt;

    public PoRequisitionId() {
    }

    public PoRequisitionId(int itemNbr, String facility, Date needByDt) {
       this.itemNbr = itemNbr;
       this.facility = facility;
       this.needByDt = needByDt;
    }
   


    @Column(name="ITEM_NBR", nullable=false, precision=9, scale=0)
    public int getItemNbr() {
        return this.itemNbr;
    }
    
    public void setItemNbr(int itemNbr) {
        this.itemNbr = itemNbr;
    }


    @Column(name="FACILITY", nullable=false, length=16)
    public String getFacility() {
        return this.facility;
    }
    
    public void setFacility(String facility) {
        this.facility = facility;
    }


    @Column(name="NEED_BY_DT", nullable=false, length=7)
    public Date getNeedByDt() {
        return this.needByDt;
    }
    
    public void setNeedByDt(Date needByDt) {
        this.needByDt = needByDt;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PoRequisitionId) ) return false;
		 PoRequisitionId castOther = ( PoRequisitionId ) other; 
         
		 return (this.getItemNbr()==castOther.getItemNbr())
 && ( (this.getFacility()==castOther.getFacility()) || ( this.getFacility()!=null && castOther.getFacility()!=null && this.getFacility().equals(castOther.getFacility()) ) )
 && ( (this.getNeedByDt()==castOther.getNeedByDt()) || ( this.getNeedByDt()!=null && castOther.getNeedByDt()!=null && this.getNeedByDt().equals(castOther.getNeedByDt()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getItemNbr();
         result = 37 * result + ( getFacility() == null ? 0 : this.getFacility().hashCode() );
         result = 37 * result + ( getNeedByDt() == null ? 0 : this.getNeedByDt().hashCode() );
         return result;
   }   


}


