package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PoReschedId generated by hbm2java
 */
@Embeddable
public class PoReschedId  implements java.io.Serializable {


     private Integer poLineDtlNbr;
     private Date reschedDt;
     private BigDecimal reschedQty;
     private Integer orgNbrVnd;

    public PoReschedId() {
    }

    public PoReschedId(Integer poLineDtlNbr, Date reschedDt, BigDecimal reschedQty, Integer orgNbrVnd) {
       this.poLineDtlNbr = poLineDtlNbr;
       this.reschedDt = reschedDt;
       this.reschedQty = reschedQty;
       this.orgNbrVnd = orgNbrVnd;
    }
   


    @Column(name="PO_LINE_DTL_NBR", precision=9, scale=0)
    public Integer getPoLineDtlNbr() {
        return this.poLineDtlNbr;
    }
    
    public void setPoLineDtlNbr(Integer poLineDtlNbr) {
        this.poLineDtlNbr = poLineDtlNbr;
    }


    @Column(name="RESCHED_DT", length=7)
    public Date getReschedDt() {
        return this.reschedDt;
    }
    
    public void setReschedDt(Date reschedDt) {
        this.reschedDt = reschedDt;
    }


    @Column(name="RESCHED_QTY", precision=13, scale=5)
    public BigDecimal getReschedQty() {
        return this.reschedQty;
    }
    
    public void setReschedQty(BigDecimal reschedQty) {
        this.reschedQty = reschedQty;
    }


    @Column(name="ORG_NBR_VND", precision=9, scale=0)
    public Integer getOrgNbrVnd() {
        return this.orgNbrVnd;
    }
    
    public void setOrgNbrVnd(Integer orgNbrVnd) {
        this.orgNbrVnd = orgNbrVnd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PoReschedId) ) return false;
		 PoReschedId castOther = ( PoReschedId ) other; 
         
		 return ( (this.getPoLineDtlNbr()==castOther.getPoLineDtlNbr()) || ( this.getPoLineDtlNbr()!=null && castOther.getPoLineDtlNbr()!=null && this.getPoLineDtlNbr().equals(castOther.getPoLineDtlNbr()) ) )
 && ( (this.getReschedDt()==castOther.getReschedDt()) || ( this.getReschedDt()!=null && castOther.getReschedDt()!=null && this.getReschedDt().equals(castOther.getReschedDt()) ) )
 && ( (this.getReschedQty()==castOther.getReschedQty()) || ( this.getReschedQty()!=null && castOther.getReschedQty()!=null && this.getReschedQty().equals(castOther.getReschedQty()) ) )
 && ( (this.getOrgNbrVnd()==castOther.getOrgNbrVnd()) || ( this.getOrgNbrVnd()!=null && castOther.getOrgNbrVnd()!=null && this.getOrgNbrVnd().equals(castOther.getOrgNbrVnd()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPoLineDtlNbr() == null ? 0 : this.getPoLineDtlNbr().hashCode() );
         result = 37 * result + ( getReschedDt() == null ? 0 : this.getReschedDt().hashCode() );
         result = 37 * result + ( getReschedQty() == null ? 0 : this.getReschedQty().hashCode() );
         result = 37 * result + ( getOrgNbrVnd() == null ? 0 : this.getOrgNbrVnd().hashCode() );
         return result;
   }   


}


