package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PoUnplannedRcpt generated by hbm2java
 */
@Entity
@Table(name="PO_UNPLANNED_RCPT"
)
public class PoUnplannedRcpt  implements java.io.Serializable {


     private int poUnplannedRcptNbr;
     private ApsSplySubPool apsSplySubPool;
     private PoLineHdr poLineHdr;
     private PoMfrMast poMfrMast;
     private PoOrdHdr poOrdHdr;
     private PoVndMast poVndMast;
     private UtFacility utFacility;
     private IcLotMast icLotMast;
     private IcBin icBin;
     private IcItemMast icItemMast;
     private Date rcptDt;
     private BigDecimal qtyRecv;
     private String lotUm;
     private String mfrLotCd;
     private Date mfrDt;
     private String revLvl;
     private int utUserNbr;
     private Date lastModDt;
     private String rcptStatId;
     private Date processedDt;
     private BigDecimal qtyRecvStkUm;
     private Date expireDt;
     private String cntryCdOrigin;
     private String itemCdVnd;
     private BigDecimal unitCostDenomReplenUm;
     private BigDecimal unitCostReplenUm;
     private BigDecimal unitCostStkUm;
     private BigDecimal unitCostDenomStkUm;
     private String rcptComm;

    public PoUnplannedRcpt() {
    }

	
    public PoUnplannedRcpt(int poUnplannedRcptNbr, ApsSplySubPool apsSplySubPool, UtFacility utFacility, IcItemMast icItemMast, Date rcptDt, BigDecimal qtyRecv, int utUserNbr, Date lastModDt, String rcptStatId, BigDecimal qtyRecvStkUm) {
        this.poUnplannedRcptNbr = poUnplannedRcptNbr;
        this.apsSplySubPool = apsSplySubPool;
        this.utFacility = utFacility;
        this.icItemMast = icItemMast;
        this.rcptDt = rcptDt;
        this.qtyRecv = qtyRecv;
        this.utUserNbr = utUserNbr;
        this.lastModDt = lastModDt;
        this.rcptStatId = rcptStatId;
        this.qtyRecvStkUm = qtyRecvStkUm;
    }
    public PoUnplannedRcpt(int poUnplannedRcptNbr, ApsSplySubPool apsSplySubPool, PoLineHdr poLineHdr, PoMfrMast poMfrMast, PoOrdHdr poOrdHdr, PoVndMast poVndMast, UtFacility utFacility, IcLotMast icLotMast, IcBin icBin, IcItemMast icItemMast, Date rcptDt, BigDecimal qtyRecv, String lotUm, String mfrLotCd, Date mfrDt, String revLvl, int utUserNbr, Date lastModDt, String rcptStatId, Date processedDt, BigDecimal qtyRecvStkUm, Date expireDt, String cntryCdOrigin, String itemCdVnd, BigDecimal unitCostDenomReplenUm, BigDecimal unitCostReplenUm, BigDecimal unitCostStkUm, BigDecimal unitCostDenomStkUm, String rcptComm) {
       this.poUnplannedRcptNbr = poUnplannedRcptNbr;
       this.apsSplySubPool = apsSplySubPool;
       this.poLineHdr = poLineHdr;
       this.poMfrMast = poMfrMast;
       this.poOrdHdr = poOrdHdr;
       this.poVndMast = poVndMast;
       this.utFacility = utFacility;
       this.icLotMast = icLotMast;
       this.icBin = icBin;
       this.icItemMast = icItemMast;
       this.rcptDt = rcptDt;
       this.qtyRecv = qtyRecv;
       this.lotUm = lotUm;
       this.mfrLotCd = mfrLotCd;
       this.mfrDt = mfrDt;
       this.revLvl = revLvl;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
       this.rcptStatId = rcptStatId;
       this.processedDt = processedDt;
       this.qtyRecvStkUm = qtyRecvStkUm;
       this.expireDt = expireDt;
       this.cntryCdOrigin = cntryCdOrigin;
       this.itemCdVnd = itemCdVnd;
       this.unitCostDenomReplenUm = unitCostDenomReplenUm;
       this.unitCostReplenUm = unitCostReplenUm;
       this.unitCostStkUm = unitCostStkUm;
       this.unitCostDenomStkUm = unitCostDenomStkUm;
       this.rcptComm = rcptComm;
    }
   
     @Id 

    
    @Column(name="PO_UNPLANNED_RCPT_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getPoUnplannedRcptNbr() {
        return this.poUnplannedRcptNbr;
    }
    
    public void setPoUnplannedRcptNbr(int poUnplannedRcptNbr) {
        this.poUnplannedRcptNbr = poUnplannedRcptNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APS_SPLY_SUB_POOL_NBR", nullable=false)
    public ApsSplySubPool getApsSplySubPool() {
        return this.apsSplySubPool;
    }
    
    public void setApsSplySubPool(ApsSplySubPool apsSplySubPool) {
        this.apsSplySubPool = apsSplySubPool;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PO_LINE_HDR_NBR")
    public PoLineHdr getPoLineHdr() {
        return this.poLineHdr;
    }
    
    public void setPoLineHdr(PoLineHdr poLineHdr) {
        this.poLineHdr = poLineHdr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORG_NBR_MFR")
    public PoMfrMast getPoMfrMast() {
        return this.poMfrMast;
    }
    
    public void setPoMfrMast(PoMfrMast poMfrMast) {
        this.poMfrMast = poMfrMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PO_ORD_HDR_NBR")
    public PoOrdHdr getPoOrdHdr() {
        return this.poOrdHdr;
    }
    
    public void setPoOrdHdr(PoOrdHdr poOrdHdr) {
        this.poOrdHdr = poOrdHdr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORG_NBR_VND")
    public PoVndMast getPoVndMast() {
        return this.poVndMast;
    }
    
    public void setPoVndMast(PoVndMast poVndMast) {
        this.poVndMast = poVndMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FACILITY", nullable=false)
    public UtFacility getUtFacility() {
        return this.utFacility;
    }
    
    public void setUtFacility(UtFacility utFacility) {
        this.utFacility = utFacility;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LOT_NBR")
    public IcLotMast getIcLotMast() {
        return this.icLotMast;
    }
    
    public void setIcLotMast(IcLotMast icLotMast) {
        this.icLotMast = icLotMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIN_NBR")
    public IcBin getIcBin() {
        return this.icBin;
    }
    
    public void setIcBin(IcBin icBin) {
        this.icBin = icBin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR", nullable=false)
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RCPT_DT", nullable=false, length=7)
    public Date getRcptDt() {
        return this.rcptDt;
    }
    
    public void setRcptDt(Date rcptDt) {
        this.rcptDt = rcptDt;
    }

    
    @Column(name="QTY_RECV", nullable=false, precision=15, scale=5)
    public BigDecimal getQtyRecv() {
        return this.qtyRecv;
    }
    
    public void setQtyRecv(BigDecimal qtyRecv) {
        this.qtyRecv = qtyRecv;
    }

    
    @Column(name="LOT_UM", length=3)
    public String getLotUm() {
        return this.lotUm;
    }
    
    public void setLotUm(String lotUm) {
        this.lotUm = lotUm;
    }

    
    @Column(name="MFR_LOT_CD", length=20)
    public String getMfrLotCd() {
        return this.mfrLotCd;
    }
    
    public void setMfrLotCd(String mfrLotCd) {
        this.mfrLotCd = mfrLotCd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MFR_DT", length=7)
    public Date getMfrDt() {
        return this.mfrDt;
    }
    
    public void setMfrDt(Date mfrDt) {
        this.mfrDt = mfrDt;
    }

    
    @Column(name="REV_LVL", length=5)
    public String getRevLvl() {
        return this.revLvl;
    }
    
    public void setRevLvl(String revLvl) {
        this.revLvl = revLvl;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }

    
    @Column(name="RCPT_STAT_ID", nullable=false, length=1)
    public String getRcptStatId() {
        return this.rcptStatId;
    }
    
    public void setRcptStatId(String rcptStatId) {
        this.rcptStatId = rcptStatId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PROCESSED_DT", length=7)
    public Date getProcessedDt() {
        return this.processedDt;
    }
    
    public void setProcessedDt(Date processedDt) {
        this.processedDt = processedDt;
    }

    
    @Column(name="QTY_RECV_STK_UM", nullable=false, precision=13, scale=5)
    public BigDecimal getQtyRecvStkUm() {
        return this.qtyRecvStkUm;
    }
    
    public void setQtyRecvStkUm(BigDecimal qtyRecvStkUm) {
        this.qtyRecvStkUm = qtyRecvStkUm;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXPIRE_DT", length=7)
    public Date getExpireDt() {
        return this.expireDt;
    }
    
    public void setExpireDt(Date expireDt) {
        this.expireDt = expireDt;
    }

    
    @Column(name="CNTRY_CD_ORIGIN", length=3)
    public String getCntryCdOrigin() {
        return this.cntryCdOrigin;
    }
    
    public void setCntryCdOrigin(String cntryCdOrigin) {
        this.cntryCdOrigin = cntryCdOrigin;
    }

    
    @Column(name="ITEM_CD_VND", length=50)
    public String getItemCdVnd() {
        return this.itemCdVnd;
    }
    
    public void setItemCdVnd(String itemCdVnd) {
        this.itemCdVnd = itemCdVnd;
    }

    
    @Column(name="UNIT_COST_DENOM_REPLEN_UM", precision=17, scale=6)
    public BigDecimal getUnitCostDenomReplenUm() {
        return this.unitCostDenomReplenUm;
    }
    
    public void setUnitCostDenomReplenUm(BigDecimal unitCostDenomReplenUm) {
        this.unitCostDenomReplenUm = unitCostDenomReplenUm;
    }

    
    @Column(name="UNIT_COST_REPLEN_UM", precision=17, scale=6)
    public BigDecimal getUnitCostReplenUm() {
        return this.unitCostReplenUm;
    }
    
    public void setUnitCostReplenUm(BigDecimal unitCostReplenUm) {
        this.unitCostReplenUm = unitCostReplenUm;
    }

    
    @Column(name="UNIT_COST_STK_UM", precision=17, scale=6)
    public BigDecimal getUnitCostStkUm() {
        return this.unitCostStkUm;
    }
    
    public void setUnitCostStkUm(BigDecimal unitCostStkUm) {
        this.unitCostStkUm = unitCostStkUm;
    }

    
    @Column(name="UNIT_COST_DENOM_STK_UM", precision=17, scale=6)
    public BigDecimal getUnitCostDenomStkUm() {
        return this.unitCostDenomStkUm;
    }
    
    public void setUnitCostDenomStkUm(BigDecimal unitCostDenomStkUm) {
        this.unitCostDenomStkUm = unitCostDenomStkUm;
    }

    
    @Column(name="RCPT_COMM", length=200)
    public String getRcptComm() {
        return this.rcptComm;
    }
    
    public void setRcptComm(String rcptComm) {
        this.rcptComm = rcptComm;
    }




}


