package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PoVndSetDtl generated by hbm2java
 */
@Entity
@Table(name="PO_VND_SET_DTL"
)
public class PoVndSetDtl  implements java.io.Serializable {


     private PoVndSetDtlId id;
     private PoVndMast poVndMast;
     private PoVndSetHdr poVndSetHdr;
     private int utUserNbr;
     private Date lastModDt;

    public PoVndSetDtl() {
    }

    public PoVndSetDtl(PoVndSetDtlId id, PoVndMast poVndMast, PoVndSetHdr poVndSetHdr, int utUserNbr, Date lastModDt) {
       this.id = id;
       this.poVndMast = poVndMast;
       this.poVndSetHdr = poVndSetHdr;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="poVndSetHdrNbr", column=@Column(name="PO_VND_SET_HDR_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="orgNbrVnd", column=@Column(name="ORG_NBR_VND", nullable=false, precision=9, scale=0) ) } )
    public PoVndSetDtlId getId() {
        return this.id;
    }
    
    public void setId(PoVndSetDtlId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORG_NBR_VND", nullable=false, insertable=false, updatable=false)
    public PoVndMast getPoVndMast() {
        return this.poVndMast;
    }
    
    public void setPoVndMast(PoVndMast poVndMast) {
        this.poVndMast = poVndMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PO_VND_SET_HDR_NBR", nullable=false, insertable=false, updatable=false)
    public PoVndSetHdr getPoVndSetHdr() {
        return this.poVndSetHdr;
    }
    
    public void setPoVndSetHdr(PoVndSetHdr poVndSetHdr) {
        this.poVndSetHdr = poVndSetHdr;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }




}


