package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PoVndSetDtlId generated by hbm2java
 */
@Embeddable
public class PoVndSetDtlId  implements java.io.Serializable {


     private int poVndSetHdrNbr;
     private int orgNbrVnd;

    public PoVndSetDtlId() {
    }

    public PoVndSetDtlId(int poVndSetHdrNbr, int orgNbrVnd) {
       this.poVndSetHdrNbr = poVndSetHdrNbr;
       this.orgNbrVnd = orgNbrVnd;
    }
   


    @Column(name="PO_VND_SET_HDR_NBR", nullable=false, precision=9, scale=0)
    public int getPoVndSetHdrNbr() {
        return this.poVndSetHdrNbr;
    }
    
    public void setPoVndSetHdrNbr(int poVndSetHdrNbr) {
        this.poVndSetHdrNbr = poVndSetHdrNbr;
    }


    @Column(name="ORG_NBR_VND", nullable=false, precision=9, scale=0)
    public int getOrgNbrVnd() {
        return this.orgNbrVnd;
    }
    
    public void setOrgNbrVnd(int orgNbrVnd) {
        this.orgNbrVnd = orgNbrVnd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PoVndSetDtlId) ) return false;
		 PoVndSetDtlId castOther = ( PoVndSetDtlId ) other; 
         
		 return (this.getPoVndSetHdrNbr()==castOther.getPoVndSetHdrNbr())
 && (this.getOrgNbrVnd()==castOther.getOrgNbrVnd());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPoVndSetHdrNbr();
         result = 37 * result + this.getOrgNbrVnd();
         return result;
   }   


}


