package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PoVndMastVw generated by hbm2java
 */
@Entity
@Table(name="PO_VND_MAST_VW"
)
public class PoVndMastVw  implements java.io.Serializable {


     private PoVndMastVwId id;

    public PoVndMastVw() {
    }

    public PoVndMastVw(PoVndMastVwId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orgNbrVnd", column=@Column(name="ORG_NBR_VND", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="statId", column=@Column(name="STAT_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="buyIndivNbr", column=@Column(name="BUY_INDIV_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="mailToAddrNbrDflt", column=@Column(name="MAIL_TO_ADDR_NBR_DFLT", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="mailToAddrCdDflt", column=@Column(name="MAIL_TO_ADDR_CD_DFLT", nullable=false, length=8) ), 
        @AttributeOverride(name="billToAddrNbrDflt", column=@Column(name="BILL_TO_ADDR_NBR_DFLT", precision=9, scale=0) ), 
        @AttributeOverride(name="billToAddrCdDflt", column=@Column(name="BILL_TO_ADDR_CD_DFLT", length=8) ), 
        @AttributeOverride(name="currCdDflt", column=@Column(name="CURR_CD_DFLT", nullable=false, length=3) ), 
        @AttributeOverride(name="termCdDflt", column=@Column(name="TERM_CD_DFLT", nullable=false, length=10) ), 
        @AttributeOverride(name="shipViaCdDflt", column=@Column(name="SHIP_VIA_CD_DFLT", nullable=false, length=8) ), 
        @AttributeOverride(name="fobCdDflt", column=@Column(name="FOB_CD_DFLT", nullable=false, length=8) ), 
        @AttributeOverride(name="trdFlg", column=@Column(name="TRD_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="trdGlAcct", column=@Column(name="TRD_GL_ACCT", length=20) ), 
        @AttributeOverride(name="orgCdVnd", column=@Column(name="ORG_CD_VND", nullable=false, length=15) ), 
        @AttributeOverride(name="orgNmVnd", column=@Column(name="ORG_NM_VND", nullable=false, length=60) ), 
        @AttributeOverride(name="introDt", column=@Column(name="INTRO_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="replenAllowFlg", column=@Column(name="REPLEN_ALLOW_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="receiveAllowFlg", column=@Column(name="RECEIVE_ALLOW_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="allocSlipDy", column=@Column(name="ALLOC_SLIP_DY", precision=5, scale=0) ), 
        @AttributeOverride(name="phnNbrDflt", column=@Column(name="PHN_NBR_DFLT", length=20) ), 
        @AttributeOverride(name="faxNbrDflt", column=@Column(name="FAX_NBR_DFLT", length=20) ), 
        @AttributeOverride(name="indivNbrVndContact", column=@Column(name="INDIV_NBR_VND_CONTACT", precision=9, scale=0) ), 
        @AttributeOverride(name="workOrderRptNm", column=@Column(name="WORK_ORDER_RPT_NM") ), 
        @AttributeOverride(name="vndUpdDt", column=@Column(name="VND_UPD_DT", length=7) ) } )
    public PoVndMastVwId getId() {
        return this.id;
    }
    
    public void setId(PoVndMastVwId id) {
        this.id = id;
    }




}


