package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PoVndSetHdr generated by hbm2java
 */
@Entity
@Table(name="PO_VND_SET_HDR"
)
public class PoVndSetHdr  implements java.io.Serializable {


     private int poVndSetHdrNbr;
     private String poVndSetHdrCd;
     private String poVndSetHdrDescr;
     private int utUserNbr;
     private Date lastModDt;
     private Set<IcCategory> icCategories = new HashSet<IcCategory>(0);
     private Set<PoVndSetDtl> poVndSetDtls = new HashSet<PoVndSetDtl>(0);

    public PoVndSetHdr() {
    }

	
    public PoVndSetHdr(int poVndSetHdrNbr, String poVndSetHdrCd, int utUserNbr, Date lastModDt) {
        this.poVndSetHdrNbr = poVndSetHdrNbr;
        this.poVndSetHdrCd = poVndSetHdrCd;
        this.utUserNbr = utUserNbr;
        this.lastModDt = lastModDt;
    }
    public PoVndSetHdr(int poVndSetHdrNbr, String poVndSetHdrCd, String poVndSetHdrDescr, int utUserNbr, Date lastModDt, Set<IcCategory> icCategories, Set<PoVndSetDtl> poVndSetDtls) {
       this.poVndSetHdrNbr = poVndSetHdrNbr;
       this.poVndSetHdrCd = poVndSetHdrCd;
       this.poVndSetHdrDescr = poVndSetHdrDescr;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
       this.icCategories = icCategories;
       this.poVndSetDtls = poVndSetDtls;
    }
   
     @Id 

    
    @Column(name="PO_VND_SET_HDR_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getPoVndSetHdrNbr() {
        return this.poVndSetHdrNbr;
    }
    
    public void setPoVndSetHdrNbr(int poVndSetHdrNbr) {
        this.poVndSetHdrNbr = poVndSetHdrNbr;
    }

    
    @Column(name="PO_VND_SET_HDR_CD", unique=true, nullable=false, length=20)
    public String getPoVndSetHdrCd() {
        return this.poVndSetHdrCd;
    }
    
    public void setPoVndSetHdrCd(String poVndSetHdrCd) {
        this.poVndSetHdrCd = poVndSetHdrCd;
    }

    
    @Column(name="PO_VND_SET_HDR_DESCR", length=60)
    public String getPoVndSetHdrDescr() {
        return this.poVndSetHdrDescr;
    }
    
    public void setPoVndSetHdrDescr(String poVndSetHdrDescr) {
        this.poVndSetHdrDescr = poVndSetHdrDescr;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="poVndSetHdr")
    public Set<IcCategory> getIcCategories() {
        return this.icCategories;
    }
    
    public void setIcCategories(Set<IcCategory> icCategories) {
        this.icCategories = icCategories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="poVndSetHdr")
    public Set<PoVndSetDtl> getPoVndSetDtls() {
        return this.poVndSetDtls;
    }
    
    public void setPoVndSetDtls(Set<PoVndSetDtl> poVndSetDtls) {
        this.poVndSetDtls = poVndSetDtls;
    }




}


