package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QaMfrApprv generated by hbm2java
 */
@Entity
@Table(name="QA_MFR_APPRV"
)
public class QaMfrApprv  implements java.io.Serializable {


     private QaMfrApprvId id;
     private PoMfrMast poMfrMast;
     private IcItemMast icItemMast;

    public QaMfrApprv() {
    }

    public QaMfrApprv(QaMfrApprvId id, PoMfrMast poMfrMast, IcItemMast icItemMast) {
       this.id = id;
       this.poMfrMast = poMfrMast;
       this.icItemMast = icItemMast;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="qaProjCd", column=@Column(name="QA_PROJ_CD", nullable=false, length=16) ), 
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="orgNbrMfr", column=@Column(name="ORG_NBR_MFR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="mfrRestrictId", column=@Column(name="MFR_RESTRICT_ID", nullable=false, length=1) ) } )
    public QaMfrApprvId getId() {
        return this.id;
    }
    
    public void setId(QaMfrApprvId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORG_NBR_MFR", nullable=false, insertable=false, updatable=false)
    public PoMfrMast getPoMfrMast() {
        return this.poMfrMast;
    }
    
    public void setPoMfrMast(PoMfrMast poMfrMast) {
        this.poMfrMast = poMfrMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR", nullable=false, insertable=false, updatable=false)
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }




}


