package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SeasonStartDates generated by hbm2java
 */
@Entity
@Table(name="SEASON_START_DATES"
)
public class SeasonStartDates  implements java.io.Serializable {


     private String season;
     private Date startDt;

    public SeasonStartDates() {
    }

	
    public SeasonStartDates(String season) {
        this.season = season;
    }
    public SeasonStartDates(String season, Date startDt) {
       this.season = season;
       this.startDt = startDt;
    }
   
     @Id 

    
    @Column(name="SEASON", unique=true, nullable=false, length=10)
    public String getSeason() {
        return this.season;
    }
    
    public void setSeason(String season) {
        this.season = season;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="START_DT", length=7)
    public Date getStartDt() {
        return this.startDt;
    }
    
    public void setStartDt(Date startDt) {
        this.startDt = startDt;
    }




}


