package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SqQteDtl generated by hbm2java
 */
@Entity
@Table(name="SQ_QTE_DTL"
)
public class SqQteDtl  implements java.io.Serializable {


     private int sqQteDtlNbr;
     private PoMfrMast poMfrMast;
     private SqQteHdr sqQteHdr;
     private OeOrdDtl oeOrdDtl;
     private IcItemMast icItemMast;
     private String itemCdQte;
     private String itemCdCust;
     private String qteUm;
     private BigDecimal qteQty;
     private BigDecimal qteQtyStkUm;
     private BigDecimal qtePrice;
     private BigDecimal qtePriceDenom;
     private BigDecimal qtePriceStkUm;
     private BigDecimal qtePriceDenomStkUm;
     private Date rqstDt;
     private Short leadTmWkProm;
     private Date promDt;
     private String sqLostCd;
     private String revLvl;
     private String qtePriceBasisId;
     private String qtePriceBasisKey;
     private BigDecimal qtePriceBasisCost;
     private int utUserNbr;
     private Date lastModDt;

    public SqQteDtl() {
    }

	
    public SqQteDtl(int sqQteDtlNbr, SqQteHdr sqQteHdr, String itemCdQte, String itemCdCust, String qteUm, BigDecimal qteQty, BigDecimal qteQtyStkUm, int utUserNbr, Date lastModDt) {
        this.sqQteDtlNbr = sqQteDtlNbr;
        this.sqQteHdr = sqQteHdr;
        this.itemCdQte = itemCdQte;
        this.itemCdCust = itemCdCust;
        this.qteUm = qteUm;
        this.qteQty = qteQty;
        this.qteQtyStkUm = qteQtyStkUm;
        this.utUserNbr = utUserNbr;
        this.lastModDt = lastModDt;
    }
    public SqQteDtl(int sqQteDtlNbr, PoMfrMast poMfrMast, SqQteHdr sqQteHdr, OeOrdDtl oeOrdDtl, IcItemMast icItemMast, String itemCdQte, String itemCdCust, String qteUm, BigDecimal qteQty, BigDecimal qteQtyStkUm, BigDecimal qtePrice, BigDecimal qtePriceDenom, BigDecimal qtePriceStkUm, BigDecimal qtePriceDenomStkUm, Date rqstDt, Short leadTmWkProm, Date promDt, String sqLostCd, String revLvl, String qtePriceBasisId, String qtePriceBasisKey, BigDecimal qtePriceBasisCost, int utUserNbr, Date lastModDt) {
       this.sqQteDtlNbr = sqQteDtlNbr;
       this.poMfrMast = poMfrMast;
       this.sqQteHdr = sqQteHdr;
       this.oeOrdDtl = oeOrdDtl;
       this.icItemMast = icItemMast;
       this.itemCdQte = itemCdQte;
       this.itemCdCust = itemCdCust;
       this.qteUm = qteUm;
       this.qteQty = qteQty;
       this.qteQtyStkUm = qteQtyStkUm;
       this.qtePrice = qtePrice;
       this.qtePriceDenom = qtePriceDenom;
       this.qtePriceStkUm = qtePriceStkUm;
       this.qtePriceDenomStkUm = qtePriceDenomStkUm;
       this.rqstDt = rqstDt;
       this.leadTmWkProm = leadTmWkProm;
       this.promDt = promDt;
       this.sqLostCd = sqLostCd;
       this.revLvl = revLvl;
       this.qtePriceBasisId = qtePriceBasisId;
       this.qtePriceBasisKey = qtePriceBasisKey;
       this.qtePriceBasisCost = qtePriceBasisCost;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
    }
   
     @Id 

    
    @Column(name="SQ_QTE_DTL_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getSqQteDtlNbr() {
        return this.sqQteDtlNbr;
    }
    
    public void setSqQteDtlNbr(int sqQteDtlNbr) {
        this.sqQteDtlNbr = sqQteDtlNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORG_NBR_MFR_RQST")
    public PoMfrMast getPoMfrMast() {
        return this.poMfrMast;
    }
    
    public void setPoMfrMast(PoMfrMast poMfrMast) {
        this.poMfrMast = poMfrMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SQ_QTE_HDR_NBR", nullable=false)
    public SqQteHdr getSqQteHdr() {
        return this.sqQteHdr;
    }
    
    public void setSqQteHdr(SqQteHdr sqQteHdr) {
        this.sqQteHdr = sqQteHdr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OE_ORD_DTL_NBR")
    public OeOrdDtl getOeOrdDtl() {
        return this.oeOrdDtl;
    }
    
    public void setOeOrdDtl(OeOrdDtl oeOrdDtl) {
        this.oeOrdDtl = oeOrdDtl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR_QTE")
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }

    
    @Column(name="ITEM_CD_QTE", nullable=false, length=50)
    public String getItemCdQte() {
        return this.itemCdQte;
    }
    
    public void setItemCdQte(String itemCdQte) {
        this.itemCdQte = itemCdQte;
    }

    
    @Column(name="ITEM_CD_CUST", nullable=false, length=50)
    public String getItemCdCust() {
        return this.itemCdCust;
    }
    
    public void setItemCdCust(String itemCdCust) {
        this.itemCdCust = itemCdCust;
    }

    
    @Column(name="QTE_UM", nullable=false, length=3)
    public String getQteUm() {
        return this.qteUm;
    }
    
    public void setQteUm(String qteUm) {
        this.qteUm = qteUm;
    }

    
    @Column(name="QTE_QTY", nullable=false, precision=13, scale=5)
    public BigDecimal getQteQty() {
        return this.qteQty;
    }
    
    public void setQteQty(BigDecimal qteQty) {
        this.qteQty = qteQty;
    }

    
    @Column(name="QTE_QTY_STK_UM", nullable=false, precision=13, scale=5)
    public BigDecimal getQteQtyStkUm() {
        return this.qteQtyStkUm;
    }
    
    public void setQteQtyStkUm(BigDecimal qteQtyStkUm) {
        this.qteQtyStkUm = qteQtyStkUm;
    }

    
    @Column(name="QTE_PRICE", precision=17, scale=6)
    public BigDecimal getQtePrice() {
        return this.qtePrice;
    }
    
    public void setQtePrice(BigDecimal qtePrice) {
        this.qtePrice = qtePrice;
    }

    
    @Column(name="QTE_PRICE_DENOM", precision=17, scale=6)
    public BigDecimal getQtePriceDenom() {
        return this.qtePriceDenom;
    }
    
    public void setQtePriceDenom(BigDecimal qtePriceDenom) {
        this.qtePriceDenom = qtePriceDenom;
    }

    
    @Column(name="QTE_PRICE_STK_UM", precision=17, scale=6)
    public BigDecimal getQtePriceStkUm() {
        return this.qtePriceStkUm;
    }
    
    public void setQtePriceStkUm(BigDecimal qtePriceStkUm) {
        this.qtePriceStkUm = qtePriceStkUm;
    }

    
    @Column(name="QTE_PRICE_DENOM_STK_UM", precision=17, scale=6)
    public BigDecimal getQtePriceDenomStkUm() {
        return this.qtePriceDenomStkUm;
    }
    
    public void setQtePriceDenomStkUm(BigDecimal qtePriceDenomStkUm) {
        this.qtePriceDenomStkUm = qtePriceDenomStkUm;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RQST_DT", length=7)
    public Date getRqstDt() {
        return this.rqstDt;
    }
    
    public void setRqstDt(Date rqstDt) {
        this.rqstDt = rqstDt;
    }

    
    @Column(name="LEAD_TM_WK_PROM", precision=3, scale=0)
    public Short getLeadTmWkProm() {
        return this.leadTmWkProm;
    }
    
    public void setLeadTmWkProm(Short leadTmWkProm) {
        this.leadTmWkProm = leadTmWkProm;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PROM_DT", length=7)
    public Date getPromDt() {
        return this.promDt;
    }
    
    public void setPromDt(Date promDt) {
        this.promDt = promDt;
    }

    
    @Column(name="SQ_LOST_CD", length=8)
    public String getSqLostCd() {
        return this.sqLostCd;
    }
    
    public void setSqLostCd(String sqLostCd) {
        this.sqLostCd = sqLostCd;
    }

    
    @Column(name="REV_LVL", length=5)
    public String getRevLvl() {
        return this.revLvl;
    }
    
    public void setRevLvl(String revLvl) {
        this.revLvl = revLvl;
    }

    
    @Column(name="QTE_PRICE_BASIS_ID", length=1)
    public String getQtePriceBasisId() {
        return this.qtePriceBasisId;
    }
    
    public void setQtePriceBasisId(String qtePriceBasisId) {
        this.qtePriceBasisId = qtePriceBasisId;
    }

    
    @Column(name="QTE_PRICE_BASIS_KEY", length=20)
    public String getQtePriceBasisKey() {
        return this.qtePriceBasisKey;
    }
    
    public void setQtePriceBasisKey(String qtePriceBasisKey) {
        this.qtePriceBasisKey = qtePriceBasisKey;
    }

    
    @Column(name="QTE_PRICE_BASIS_COST", precision=17, scale=6)
    public BigDecimal getQtePriceBasisCost() {
        return this.qtePriceBasisCost;
    }
    
    public void setQtePriceBasisCost(BigDecimal qtePriceBasisCost) {
        this.qtePriceBasisCost = qtePriceBasisCost;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }




}


