package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SqQteHdr generated by hbm2java
 */
@Entity
@Table(name="SQ_QTE_HDR"
)
public class SqQteHdr  implements java.io.Serializable {


     private int sqQteHdrNbr;
     private OeCustMast oeCustMast;
     private String sqQteCd;
     private Date sqQteDt;
     private String currCdQte;
     private String indivNmSpokenTo;
     private String indivPhnNbr;
     private String indivFaxNbr;
     private String indivEmailAddr;
     private Date sqQteEffDt;
     private Date sqQteExpDt;
     private String custQteRefCd;
     private int sqQteIndivNbr;
     private int utUserNbr;
     private Date lastModDt;
     private String transmitFlg;
     private String orgNmCust;
     private Set<SqQteDtl> sqQteDtls = new HashSet<SqQteDtl>(0);

    public SqQteHdr() {
    }

	
    public SqQteHdr(int sqQteHdrNbr, OeCustMast oeCustMast, String sqQteCd, Date sqQteDt, String currCdQte, Date sqQteEffDt, Date sqQteExpDt, int sqQteIndivNbr, int utUserNbr, Date lastModDt, String transmitFlg, String orgNmCust) {
        this.sqQteHdrNbr = sqQteHdrNbr;
        this.oeCustMast = oeCustMast;
        this.sqQteCd = sqQteCd;
        this.sqQteDt = sqQteDt;
        this.currCdQte = currCdQte;
        this.sqQteEffDt = sqQteEffDt;
        this.sqQteExpDt = sqQteExpDt;
        this.sqQteIndivNbr = sqQteIndivNbr;
        this.utUserNbr = utUserNbr;
        this.lastModDt = lastModDt;
        this.transmitFlg = transmitFlg;
        this.orgNmCust = orgNmCust;
    }
    public SqQteHdr(int sqQteHdrNbr, OeCustMast oeCustMast, String sqQteCd, Date sqQteDt, String currCdQte, String indivNmSpokenTo, String indivPhnNbr, String indivFaxNbr, String indivEmailAddr, Date sqQteEffDt, Date sqQteExpDt, String custQteRefCd, int sqQteIndivNbr, int utUserNbr, Date lastModDt, String transmitFlg, String orgNmCust, Set<SqQteDtl> sqQteDtls) {
       this.sqQteHdrNbr = sqQteHdrNbr;
       this.oeCustMast = oeCustMast;
       this.sqQteCd = sqQteCd;
       this.sqQteDt = sqQteDt;
       this.currCdQte = currCdQte;
       this.indivNmSpokenTo = indivNmSpokenTo;
       this.indivPhnNbr = indivPhnNbr;
       this.indivFaxNbr = indivFaxNbr;
       this.indivEmailAddr = indivEmailAddr;
       this.sqQteEffDt = sqQteEffDt;
       this.sqQteExpDt = sqQteExpDt;
       this.custQteRefCd = custQteRefCd;
       this.sqQteIndivNbr = sqQteIndivNbr;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
       this.transmitFlg = transmitFlg;
       this.orgNmCust = orgNmCust;
       this.sqQteDtls = sqQteDtls;
    }
   
     @Id 

    
    @Column(name="SQ_QTE_HDR_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getSqQteHdrNbr() {
        return this.sqQteHdrNbr;
    }
    
    public void setSqQteHdrNbr(int sqQteHdrNbr) {
        this.sqQteHdrNbr = sqQteHdrNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORG_NBR_CUST", nullable=false)
    public OeCustMast getOeCustMast() {
        return this.oeCustMast;
    }
    
    public void setOeCustMast(OeCustMast oeCustMast) {
        this.oeCustMast = oeCustMast;
    }

    
    @Column(name="SQ_QTE_CD", unique=true, nullable=false, length=20)
    public String getSqQteCd() {
        return this.sqQteCd;
    }
    
    public void setSqQteCd(String sqQteCd) {
        this.sqQteCd = sqQteCd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SQ_QTE_DT", nullable=false, length=7)
    public Date getSqQteDt() {
        return this.sqQteDt;
    }
    
    public void setSqQteDt(Date sqQteDt) {
        this.sqQteDt = sqQteDt;
    }

    
    @Column(name="CURR_CD_QTE", nullable=false, length=9)
    public String getCurrCdQte() {
        return this.currCdQte;
    }
    
    public void setCurrCdQte(String currCdQte) {
        this.currCdQte = currCdQte;
    }

    
    @Column(name="INDIV_NM_SPOKEN_TO", length=40)
    public String getIndivNmSpokenTo() {
        return this.indivNmSpokenTo;
    }
    
    public void setIndivNmSpokenTo(String indivNmSpokenTo) {
        this.indivNmSpokenTo = indivNmSpokenTo;
    }

    
    @Column(name="INDIV_PHN_NBR", length=20)
    public String getIndivPhnNbr() {
        return this.indivPhnNbr;
    }
    
    public void setIndivPhnNbr(String indivPhnNbr) {
        this.indivPhnNbr = indivPhnNbr;
    }

    
    @Column(name="INDIV_FAX_NBR", length=20)
    public String getIndivFaxNbr() {
        return this.indivFaxNbr;
    }
    
    public void setIndivFaxNbr(String indivFaxNbr) {
        this.indivFaxNbr = indivFaxNbr;
    }

    
    @Column(name="INDIV_EMAIL_ADDR", length=40)
    public String getIndivEmailAddr() {
        return this.indivEmailAddr;
    }
    
    public void setIndivEmailAddr(String indivEmailAddr) {
        this.indivEmailAddr = indivEmailAddr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SQ_QTE_EFF_DT", nullable=false, length=7)
    public Date getSqQteEffDt() {
        return this.sqQteEffDt;
    }
    
    public void setSqQteEffDt(Date sqQteEffDt) {
        this.sqQteEffDt = sqQteEffDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SQ_QTE_EXP_DT", nullable=false, length=7)
    public Date getSqQteExpDt() {
        return this.sqQteExpDt;
    }
    
    public void setSqQteExpDt(Date sqQteExpDt) {
        this.sqQteExpDt = sqQteExpDt;
    }

    
    @Column(name="CUST_QTE_REF_CD", length=20)
    public String getCustQteRefCd() {
        return this.custQteRefCd;
    }
    
    public void setCustQteRefCd(String custQteRefCd) {
        this.custQteRefCd = custQteRefCd;
    }

    
    @Column(name="SQ_QTE_INDIV_NBR", nullable=false, precision=9, scale=0)
    public int getSqQteIndivNbr() {
        return this.sqQteIndivNbr;
    }
    
    public void setSqQteIndivNbr(int sqQteIndivNbr) {
        this.sqQteIndivNbr = sqQteIndivNbr;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }

    
    @Column(name="TRANSMIT_FLG", nullable=false, length=1)
    public String getTransmitFlg() {
        return this.transmitFlg;
    }
    
    public void setTransmitFlg(String transmitFlg) {
        this.transmitFlg = transmitFlg;
    }

    
    @Column(name="ORG_NM_CUST", nullable=false, length=60)
    public String getOrgNmCust() {
        return this.orgNmCust;
    }
    
    public void setOrgNmCust(String orgNmCust) {
        this.orgNmCust = orgNmCust;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sqQteHdr")
    public Set<SqQteDtl> getSqQteDtls() {
        return this.sqQteDtls;
    }
    
    public void setSqQteDtls(Set<SqQteDtl> sqQteDtls) {
        this.sqQteDtls = sqQteDtls;
    }




}


