package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TmpFcFcst generated by hbm2java
 */
@Entity
@Table(name="TMP_FC_FCST"
)
public class TmpFcFcst  implements java.io.Serializable {


     private TmpFcFcstId id;

    public TmpFcFcst() {
    }

    public TmpFcFcst(TmpFcFcstId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fcItemMastNbr", column=@Column(name="FC_ITEM_MAST_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="fcFcstDt", column=@Column(name="FC_FCST_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="adjFcst", column=@Column(name="ADJ_FCST", precision=22, scale=0) ) } )
    public TmpFcFcstId getId() {
        return this.id;
    }
    
    public void setId(TmpFcFcstId id) {
        this.id = id;
    }




}


