package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TmpFcHist generated by hbm2java
 */
@Entity
@Table(name="TMP_FC_HIST"
)
public class TmpFcHist  implements java.io.Serializable {


     private TmpFcHistId id;

    public TmpFcHist() {
    }

    public TmpFcHist(TmpFcHistId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fcItemMastNbr", column=@Column(name="FC_ITEM_MAST_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="dmdDt", column=@Column(name="DMD_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="dmdAdj", column=@Column(name="DMD_ADJ", precision=22, scale=0) ) } )
    public TmpFcHistId getId() {
        return this.id;
    }
    
    public void setId(TmpFcHistId id) {
        this.id = id;
    }




}


