package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TmpFcHistId generated by hbm2java
 */
@Embeddable
public class TmpFcHistId  implements java.io.Serializable {


     private int fcItemMastNbr;
     private Date dmdDt;
     private BigDecimal dmdAdj;

    public TmpFcHistId() {
    }

	
    public TmpFcHistId(int fcItemMastNbr, Date dmdDt) {
        this.fcItemMastNbr = fcItemMastNbr;
        this.dmdDt = dmdDt;
    }
    public TmpFcHistId(int fcItemMastNbr, Date dmdDt, BigDecimal dmdAdj) {
       this.fcItemMastNbr = fcItemMastNbr;
       this.dmdDt = dmdDt;
       this.dmdAdj = dmdAdj;
    }
   


    @Column(name="FC_ITEM_MAST_NBR", nullable=false, precision=9, scale=0)
    public int getFcItemMastNbr() {
        return this.fcItemMastNbr;
    }
    
    public void setFcItemMastNbr(int fcItemMastNbr) {
        this.fcItemMastNbr = fcItemMastNbr;
    }


    @Column(name="DMD_DT", nullable=false, length=7)
    public Date getDmdDt() {
        return this.dmdDt;
    }
    
    public void setDmdDt(Date dmdDt) {
        this.dmdDt = dmdDt;
    }


    @Column(name="DMD_ADJ", precision=22, scale=0)
    public BigDecimal getDmdAdj() {
        return this.dmdAdj;
    }
    
    public void setDmdAdj(BigDecimal dmdAdj) {
        this.dmdAdj = dmdAdj;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TmpFcHistId) ) return false;
		 TmpFcHistId castOther = ( TmpFcHistId ) other; 
         
		 return (this.getFcItemMastNbr()==castOther.getFcItemMastNbr())
 && ( (this.getDmdDt()==castOther.getDmdDt()) || ( this.getDmdDt()!=null && castOther.getDmdDt()!=null && this.getDmdDt().equals(castOther.getDmdDt()) ) )
 && ( (this.getDmdAdj()==castOther.getDmdAdj()) || ( this.getDmdAdj()!=null && castOther.getDmdAdj()!=null && this.getDmdAdj().equals(castOther.getDmdAdj()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFcItemMastNbr();
         result = 37 * result + ( getDmdDt() == null ? 0 : this.getDmdDt().hashCode() );
         result = 37 * result + ( getDmdAdj() == null ? 0 : this.getDmdAdj().hashCode() );
         return result;
   }   


}


