package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TmpLotRevLvlVw generated by hbm2java
 */
@Entity
@Table(name="TMP_LOT_REV_LVL_VW"
)
public class TmpLotRevLvlVw  implements java.io.Serializable {


     private TmpLotRevLvlVwId id;

    public TmpLotRevLvlVw() {
    }

    public TmpLotRevLvlVw(TmpLotRevLvlVwId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="lotNbr", column=@Column(name="LOT_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="revLvl", column=@Column(name="REV_LVL", length=5) ) } )
    public TmpLotRevLvlVwId getId() {
        return this.id;
    }
    
    public void setId(TmpLotRevLvlVwId id) {
        this.id = id;
    }




}


