package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TmpSafetyStkAdj generated by hbm2java
 */
@Entity
@Table(name="TMP_SAFETY_STK_ADJ"
)
public class TmpSafetyStkAdj  implements java.io.Serializable {


     private TmpSafetyStkAdjId id;

    public TmpSafetyStkAdj() {
    }

    public TmpSafetyStkAdj(TmpSafetyStkAdjId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fcItemMastNbr", column=@Column(name="FC_ITEM_MAST_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="safetyStkAdj", column=@Column(name="SAFETY_STK_ADJ", precision=9, scale=0) ) } )
    public TmpSafetyStkAdjId getId() {
        return this.id;
    }
    
    public void setId(TmpSafetyStkAdjId id) {
        this.id = id;
    }




}


