package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TmpSafetyStkAdjId generated by hbm2java
 */
@Embeddable
public class TmpSafetyStkAdjId  implements java.io.Serializable {


     private Integer fcItemMastNbr;
     private Integer safetyStkAdj;

    public TmpSafetyStkAdjId() {
    }

    public TmpSafetyStkAdjId(Integer fcItemMastNbr, Integer safetyStkAdj) {
       this.fcItemMastNbr = fcItemMastNbr;
       this.safetyStkAdj = safetyStkAdj;
    }
   


    @Column(name="FC_ITEM_MAST_NBR", precision=9, scale=0)
    public Integer getFcItemMastNbr() {
        return this.fcItemMastNbr;
    }
    
    public void setFcItemMastNbr(Integer fcItemMastNbr) {
        this.fcItemMastNbr = fcItemMastNbr;
    }


    @Column(name="SAFETY_STK_ADJ", precision=9, scale=0)
    public Integer getSafetyStkAdj() {
        return this.safetyStkAdj;
    }
    
    public void setSafetyStkAdj(Integer safetyStkAdj) {
        this.safetyStkAdj = safetyStkAdj;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TmpSafetyStkAdjId) ) return false;
		 TmpSafetyStkAdjId castOther = ( TmpSafetyStkAdjId ) other; 
         
		 return ( (this.getFcItemMastNbr()==castOther.getFcItemMastNbr()) || ( this.getFcItemMastNbr()!=null && castOther.getFcItemMastNbr()!=null && this.getFcItemMastNbr().equals(castOther.getFcItemMastNbr()) ) )
 && ( (this.getSafetyStkAdj()==castOther.getSafetyStkAdj()) || ( this.getSafetyStkAdj()!=null && castOther.getSafetyStkAdj()!=null && this.getSafetyStkAdj().equals(castOther.getSafetyStkAdj()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFcItemMastNbr() == null ? 0 : this.getFcItemMastNbr().hashCode() );
         result = 37 * result + ( getSafetyStkAdj() == null ? 0 : this.getSafetyStkAdj().hashCode() );
         return result;
   }   


}


