package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UnallocatedDmdByWeekVw generated by hbm2java
 */
@Entity
@Table(name="UNALLOCATED_DMD_BY_WEEK_VW"
)
public class UnallocatedDmdByWeekVw  implements java.io.Serializable {


     private UnallocatedDmdByWeekVwId id;

    public UnallocatedDmdByWeekVw() {
    }

    public UnallocatedDmdByWeekVw(UnallocatedDmdByWeekVwId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="itemCd", column=@Column(name="ITEM_CD") ), 
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR") ), 
        @AttributeOverride(name="prdStartDt", column=@Column(name="PRD_START_DT") ), 
        @AttributeOverride(name="facility", column=@Column(name="FACILITY") ), 
        @AttributeOverride(name="unallocatedQty", column=@Column(name="UNALLOCATED_QTY") ) } )
    public UnallocatedDmdByWeekVwId getId() {
        return this.id;
    }
    
    public void setId(UnallocatedDmdByWeekVwId id) {
        this.id = id;
    }




}


