package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UtCache generated by hbm2java
 */
@Entity
@Table(name="UT_CACHE"
)
public class UtCache  implements java.io.Serializable {


     private String objectName;
     private Date changeTime;
     private int cacheChangeNbr;
     private String className;

    public UtCache() {
    }

	
    public UtCache(String objectName, int cacheChangeNbr) {
        this.objectName = objectName;
        this.cacheChangeNbr = cacheChangeNbr;
    }
    public UtCache(String objectName, Date changeTime, int cacheChangeNbr, String className) {
       this.objectName = objectName;
       this.changeTime = changeTime;
       this.cacheChangeNbr = cacheChangeNbr;
       this.className = className;
    }
   
     @Id 

    
    @Column(name="OBJECT_NAME", unique=true, nullable=false, length=32)
    public String getObjectName() {
        return this.objectName;
    }
    
    public void setObjectName(String objectName) {
        this.objectName = objectName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CHANGE_TIME", length=7)
    public Date getChangeTime() {
        return this.changeTime;
    }
    
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    
    @Column(name="CACHE_CHANGE_NBR", nullable=false, precision=9, scale=0)
    public int getCacheChangeNbr() {
        return this.cacheChangeNbr;
    }
    
    public void setCacheChangeNbr(int cacheChangeNbr) {
        this.cacheChangeNbr = cacheChangeNbr;
    }

    
    @Column(name="CLASS_NAME", length=32)
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }




}


