package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UtDataSrc generated by hbm2java
 */
@Entity
@Table(name="UT_DATA_SRC"
)
public class UtDataSrc  implements java.io.Serializable {


     private String dataSrcNm;
     private String dataSrcUrl;
     private String dataSrcDriverNm;
     private String dataSrcUsername;
     private String dataSrcPassword;
     private Set<UtEtl> utEtlsForDataSrcNmSrc = new HashSet<UtEtl>(0);
     private Set<UtEtl> utEtlsForDataSrcNmDest = new HashSet<UtEtl>(0);

    public UtDataSrc() {
    }

	
    public UtDataSrc(String dataSrcNm, String dataSrcDriverNm, String dataSrcUsername, String dataSrcPassword) {
        this.dataSrcNm = dataSrcNm;
        this.dataSrcDriverNm = dataSrcDriverNm;
        this.dataSrcUsername = dataSrcUsername;
        this.dataSrcPassword = dataSrcPassword;
    }
    public UtDataSrc(String dataSrcNm, String dataSrcUrl, String dataSrcDriverNm, String dataSrcUsername, String dataSrcPassword, Set<UtEtl> utEtlsForDataSrcNmSrc, Set<UtEtl> utEtlsForDataSrcNmDest) {
       this.dataSrcNm = dataSrcNm;
       this.dataSrcUrl = dataSrcUrl;
       this.dataSrcDriverNm = dataSrcDriverNm;
       this.dataSrcUsername = dataSrcUsername;
       this.dataSrcPassword = dataSrcPassword;
       this.utEtlsForDataSrcNmSrc = utEtlsForDataSrcNmSrc;
       this.utEtlsForDataSrcNmDest = utEtlsForDataSrcNmDest;
    }
   
     @Id 

    
    @Column(name="DATA_SRC_NM", unique=true, nullable=false, length=20)
    public String getDataSrcNm() {
        return this.dataSrcNm;
    }
    
    public void setDataSrcNm(String dataSrcNm) {
        this.dataSrcNm = dataSrcNm;
    }

    
    @Column(name="DATA_SRC_URL", length=512)
    public String getDataSrcUrl() {
        return this.dataSrcUrl;
    }
    
    public void setDataSrcUrl(String dataSrcUrl) {
        this.dataSrcUrl = dataSrcUrl;
    }

    
    @Column(name="DATA_SRC_DRIVER_NM", nullable=false, length=128)
    public String getDataSrcDriverNm() {
        return this.dataSrcDriverNm;
    }
    
    public void setDataSrcDriverNm(String dataSrcDriverNm) {
        this.dataSrcDriverNm = dataSrcDriverNm;
    }

    
    @Column(name="DATA_SRC_USERNAME", nullable=false, length=20)
    public String getDataSrcUsername() {
        return this.dataSrcUsername;
    }
    
    public void setDataSrcUsername(String dataSrcUsername) {
        this.dataSrcUsername = dataSrcUsername;
    }

    
    @Column(name="DATA_SRC_PASSWORD", nullable=false, length=20)
    public String getDataSrcPassword() {
        return this.dataSrcPassword;
    }
    
    public void setDataSrcPassword(String dataSrcPassword) {
        this.dataSrcPassword = dataSrcPassword;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="utDataSrcByDataSrcNmSrc")
    public Set<UtEtl> getUtEtlsForDataSrcNmSrc() {
        return this.utEtlsForDataSrcNmSrc;
    }
    
    public void setUtEtlsForDataSrcNmSrc(Set<UtEtl> utEtlsForDataSrcNmSrc) {
        this.utEtlsForDataSrcNmSrc = utEtlsForDataSrcNmSrc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="utDataSrcByDataSrcNmDest")
    public Set<UtEtl> getUtEtlsForDataSrcNmDest() {
        return this.utEtlsForDataSrcNmDest;
    }
    
    public void setUtEtlsForDataSrcNmDest(Set<UtEtl> utEtlsForDataSrcNmDest) {
        this.utEtlsForDataSrcNmDest = utEtlsForDataSrcNmDest;
    }




}


