package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UtEtl generated by hbm2java
 */
@Entity
@Table(name="UT_ETL"
)
public class UtEtl  implements java.io.Serializable {


     private int utEtlNbr;
     private UtDataSrc utDataSrcByDataSrcNmSrc;
     private UtDataSrc utDataSrcByDataSrcNmDest;
     private String utEtlDescr;
     private String truncFlg;
     private String tableId;
     private String dataSelectStmt;
     private String dataInsertStmt;
     private Set<UtEtlGrp> utEtlGrps = new HashSet<UtEtlGrp>(0);

    public UtEtl() {
    }

	
    public UtEtl(int utEtlNbr, UtDataSrc utDataSrcByDataSrcNmSrc, UtDataSrc utDataSrcByDataSrcNmDest, String utEtlDescr, String truncFlg, String tableId, String dataSelectStmt, String dataInsertStmt) {
        this.utEtlNbr = utEtlNbr;
        this.utDataSrcByDataSrcNmSrc = utDataSrcByDataSrcNmSrc;
        this.utDataSrcByDataSrcNmDest = utDataSrcByDataSrcNmDest;
        this.utEtlDescr = utEtlDescr;
        this.truncFlg = truncFlg;
        this.tableId = tableId;
        this.dataSelectStmt = dataSelectStmt;
        this.dataInsertStmt = dataInsertStmt;
    }
    public UtEtl(int utEtlNbr, UtDataSrc utDataSrcByDataSrcNmSrc, UtDataSrc utDataSrcByDataSrcNmDest, String utEtlDescr, String truncFlg, String tableId, String dataSelectStmt, String dataInsertStmt, Set<UtEtlGrp> utEtlGrps) {
       this.utEtlNbr = utEtlNbr;
       this.utDataSrcByDataSrcNmSrc = utDataSrcByDataSrcNmSrc;
       this.utDataSrcByDataSrcNmDest = utDataSrcByDataSrcNmDest;
       this.utEtlDescr = utEtlDescr;
       this.truncFlg = truncFlg;
       this.tableId = tableId;
       this.dataSelectStmt = dataSelectStmt;
       this.dataInsertStmt = dataInsertStmt;
       this.utEtlGrps = utEtlGrps;
    }
   
     @Id 

    
    @Column(name="UT_ETL_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getUtEtlNbr() {
        return this.utEtlNbr;
    }
    
    public void setUtEtlNbr(int utEtlNbr) {
        this.utEtlNbr = utEtlNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DATA_SRC_NM_SRC", nullable=false)
    public UtDataSrc getUtDataSrcByDataSrcNmSrc() {
        return this.utDataSrcByDataSrcNmSrc;
    }
    
    public void setUtDataSrcByDataSrcNmSrc(UtDataSrc utDataSrcByDataSrcNmSrc) {
        this.utDataSrcByDataSrcNmSrc = utDataSrcByDataSrcNmSrc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DATA_SRC_NM_DEST", nullable=false)
    public UtDataSrc getUtDataSrcByDataSrcNmDest() {
        return this.utDataSrcByDataSrcNmDest;
    }
    
    public void setUtDataSrcByDataSrcNmDest(UtDataSrc utDataSrcByDataSrcNmDest) {
        this.utDataSrcByDataSrcNmDest = utDataSrcByDataSrcNmDest;
    }

    
    @Column(name="UT_ETL_DESCR", nullable=false, length=80)
    public String getUtEtlDescr() {
        return this.utEtlDescr;
    }
    
    public void setUtEtlDescr(String utEtlDescr) {
        this.utEtlDescr = utEtlDescr;
    }

    
    @Column(name="TRUNC_FLG", nullable=false, length=1)
    public String getTruncFlg() {
        return this.truncFlg;
    }
    
    public void setTruncFlg(String truncFlg) {
        this.truncFlg = truncFlg;
    }

    
    @Column(name="TABLE_ID", nullable=false, length=8)
    public String getTableId() {
        return this.tableId;
    }
    
    public void setTableId(String tableId) {
        this.tableId = tableId;
    }

    
    @Column(name="DATA_SELECT_STMT", nullable=false, length=4000)
    public String getDataSelectStmt() {
        return this.dataSelectStmt;
    }
    
    public void setDataSelectStmt(String dataSelectStmt) {
        this.dataSelectStmt = dataSelectStmt;
    }

    
    @Column(name="DATA_INSERT_STMT", nullable=false, length=4000)
    public String getDataInsertStmt() {
        return this.dataInsertStmt;
    }
    
    public void setDataInsertStmt(String dataInsertStmt) {
        this.dataInsertStmt = dataInsertStmt;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="utEtls")
    public Set<UtEtlGrp> getUtEtlGrps() {
        return this.utEtlGrps;
    }
    
    public void setUtEtlGrps(Set<UtEtlGrp> utEtlGrps) {
        this.utEtlGrps = utEtlGrps;
    }




}


