package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.sql.Clob;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UtProcessLog generated by hbm2java
 */
@Entity
@Table(name="UT_PROCESS_LOG"
)
public class UtProcessLog  implements java.io.Serializable {


     private int utProcessLogNbr;
     private int utProcessStatusNbr;
     private String logMsgId;
     private String logMsg;
     private Clob logMsgClob;
     private Date logMsgTs;

    public UtProcessLog() {
    }

    public UtProcessLog(int utProcessLogNbr, int utProcessStatusNbr, String logMsgId, String logMsg, Clob logMsgClob, Date logMsgTs) {
       this.utProcessLogNbr = utProcessLogNbr;
       this.utProcessStatusNbr = utProcessStatusNbr;
       this.logMsgId = logMsgId;
       this.logMsg = logMsg;
       this.logMsgClob = logMsgClob;
       this.logMsgTs = logMsgTs;
    }
   
     @Id 

    
    @Column(name="UT_PROCESS_LOG_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getUtProcessLogNbr() {
        return this.utProcessLogNbr;
    }
    
    public void setUtProcessLogNbr(int utProcessLogNbr) {
        this.utProcessLogNbr = utProcessLogNbr;
    }

    
    @Column(name="UT_PROCESS_STATUS_NBR", nullable=false, precision=9, scale=0)
    public int getUtProcessStatusNbr() {
        return this.utProcessStatusNbr;
    }
    
    public void setUtProcessStatusNbr(int utProcessStatusNbr) {
        this.utProcessStatusNbr = utProcessStatusNbr;
    }

    
    @Column(name="LOG_MSG_ID", nullable=false, length=8)
    public String getLogMsgId() {
        return this.logMsgId;
    }
    
    public void setLogMsgId(String logMsgId) {
        this.logMsgId = logMsgId;
    }

    
    @Column(name="LOG_MSG", nullable=false, length=256)
    public String getLogMsg() {
        return this.logMsg;
    }
    
    public void setLogMsg(String logMsg) {
        this.logMsg = logMsg;
    }

    
    @Column(name="LOG_MSG_CLOB", nullable=false)
    public Clob getLogMsgClob() {
        return this.logMsgClob;
    }
    
    public void setLogMsgClob(Clob logMsgClob) {
        this.logMsgClob = logMsgClob;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LOG_MSG_TS", nullable=false, length=11)
    public Date getLogMsgTs() {
        return this.logMsgTs;
    }
    
    public void setLogMsgTs(Date logMsgTs) {
        this.logMsgTs = logMsgTs;
    }




}


