package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UtTableRowMsgId generated by hbm2java
 */
@Embeddable
public class UtTableRowMsgId  implements java.io.Serializable {


     private String tableId;
     private Long primaryKey;
     private String msgId;
     private String msg;

    public UtTableRowMsgId() {
    }

    public UtTableRowMsgId(String tableId, Long primaryKey, String msgId, String msg) {
       this.tableId = tableId;
       this.primaryKey = primaryKey;
       this.msgId = msgId;
       this.msg = msg;
    }
   


    @Column(name="TABLE_ID", length=32)
    public String getTableId() {
        return this.tableId;
    }
    
    public void setTableId(String tableId) {
        this.tableId = tableId;
    }


    @Column(name="PRIMARY_KEY", precision=18, scale=0)
    public Long getPrimaryKey() {
        return this.primaryKey;
    }
    
    public void setPrimaryKey(Long primaryKey) {
        this.primaryKey = primaryKey;
    }


    @Column(name="MSG_ID", length=16)
    public String getMsgId() {
        return this.msgId;
    }
    
    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }


    @Column(name="MSG", length=64)
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UtTableRowMsgId) ) return false;
		 UtTableRowMsgId castOther = ( UtTableRowMsgId ) other; 
         
		 return ( (this.getTableId()==castOther.getTableId()) || ( this.getTableId()!=null && castOther.getTableId()!=null && this.getTableId().equals(castOther.getTableId()) ) )
 && ( (this.getPrimaryKey()==castOther.getPrimaryKey()) || ( this.getPrimaryKey()!=null && castOther.getPrimaryKey()!=null && this.getPrimaryKey().equals(castOther.getPrimaryKey()) ) )
 && ( (this.getMsgId()==castOther.getMsgId()) || ( this.getMsgId()!=null && castOther.getMsgId()!=null && this.getMsgId().equals(castOther.getMsgId()) ) )
 && ( (this.getMsg()==castOther.getMsg()) || ( this.getMsg()!=null && castOther.getMsg()!=null && this.getMsg().equals(castOther.getMsg()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTableId() == null ? 0 : this.getTableId().hashCode() );
         result = 37 * result + ( getPrimaryKey() == null ? 0 : this.getPrimaryKey().hashCode() );
         result = 37 * result + ( getMsgId() == null ? 0 : this.getMsgId().hashCode() );
         result = 37 * result + ( getMsg() == null ? 0 : this.getMsg().hashCode() );
         return result;
   }   


}


