package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UtUserRole generated by hbm2java
 */
@Entity
@Table(name="UT_USER_ROLE"
)
public class UtUserRole  implements java.io.Serializable {


     private UtUserRoleId id;

    public UtUserRole() {
    }

    public UtUserRole(UtUserRoleId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="utUserNbr", column=@Column(name="UT_USER_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="roleNm", column=@Column(name="ROLE_NM", length=8) ) } )
    public UtUserRoleId getId() {
        return this.id;
    }
    
    public void setId(UtUserRoleId id) {
        this.id = id;
    }




}


