package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VqHdrDtlVw generated by hbm2java
 */
@Entity
@Table(name="VQ_HDR_DTL_VW"
)
public class VqHdrDtlVw  implements java.io.Serializable {


     private VqHdrDtlVwId id;

    public VqHdrDtlVw() {
    }

    public VqHdrDtlVw(VqHdrDtlVwId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vqQteHdrNbr", column=@Column(name="VQ_QTE_HDR_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="vqQteCd", column=@Column(name="VQ_QTE_CD", nullable=false, length=20) ), 
        @AttributeOverride(name="orgNbrVnd", column=@Column(name="ORG_NBR_VND", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="orgCdVnd", column=@Column(name="ORG_CD_VND", nullable=false, length=15) ), 
        @AttributeOverride(name="orgNmVnd", column=@Column(name="ORG_NM_VND", nullable=false, length=60) ), 
        @AttributeOverride(name="vqQteDt", column=@Column(name="VQ_QTE_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="indivNmSpokenTo", column=@Column(name="INDIV_NM_SPOKEN_TO", length=40) ), 
        @AttributeOverride(name="indivPhnNbr", column=@Column(name="INDIV_PHN_NBR", length=20) ), 
        @AttributeOverride(name="indivFaxNbr", column=@Column(name="INDIV_FAX_NBR", length=20) ), 
        @AttributeOverride(name="indivEmailAddr", column=@Column(name="INDIV_EMAIL_ADDR", length=40) ), 
        @AttributeOverride(name="currCdQte", column=@Column(name="CURR_CD_QTE", nullable=false, length=9) ), 
        @AttributeOverride(name="vqQteEffDt", column=@Column(name="VQ_QTE_EFF_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="vqQteExpDt", column=@Column(name="VQ_QTE_EXP_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="vndQteRefCd", column=@Column(name="VND_QTE_REF_CD", length=20) ), 
        @AttributeOverride(name="transmitFlg", column=@Column(name="TRANSMIT_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="vqQteIndivNbr", column=@Column(name="VQ_QTE_INDIV_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="vqQteDtlNbr", column=@Column(name="VQ_QTE_DTL_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="itemNbrQte", column=@Column(name="ITEM_NBR_QTE", precision=9, scale=0) ), 
        @AttributeOverride(name="itemCdQte", column=@Column(name="ITEM_CD_QTE", nullable=false, length=50) ), 
        @AttributeOverride(name="itemCdVnd", column=@Column(name="ITEM_CD_VND", nullable=false, length=50) ), 
        @AttributeOverride(name="qteUm", column=@Column(name="QTE_UM", nullable=false, length=3) ), 
        @AttributeOverride(name="qteQty", column=@Column(name="QTE_QTY", nullable=false, precision=13, scale=5) ), 
        @AttributeOverride(name="qteCost", column=@Column(name="QTE_COST", precision=17, scale=6) ), 
        @AttributeOverride(name="qteCostDenom", column=@Column(name="QTE_COST_DENOM", precision=17, scale=6) ), 
        @AttributeOverride(name="qteCostStkUm", column=@Column(name="QTE_COST_STK_UM", precision=17, scale=6) ), 
        @AttributeOverride(name="qteCostDenomStkUm", column=@Column(name="QTE_COST_DENOM_STK_UM", precision=17, scale=6) ), 
        @AttributeOverride(name="orgNbrMfrRqst", column=@Column(name="ORG_NBR_MFR_RQST", precision=9, scale=0) ), 
        @AttributeOverride(name="orgCdMfr", column=@Column(name="ORG_CD_MFR", length=15) ), 
        @AttributeOverride(name="orgNmMfr", column=@Column(name="ORG_NM_MFR", length=60) ), 
        @AttributeOverride(name="revLvl", column=@Column(name="REV_LVL", length=5) ), 
        @AttributeOverride(name="rqstDt", column=@Column(name="RQST_DT", nullable=false, length=7) ), 
        @AttributeOverride(name="promDt", column=@Column(name="PROM_DT", length=7) ), 
        @AttributeOverride(name="leadTmWkProm", column=@Column(name="LEAD_TM_WK_PROM", precision=3, scale=0) ), 
        @AttributeOverride(name="vqLostCd", column=@Column(name="VQ_LOST_CD", length=8) ) } )
    public VqHdrDtlVwId getId() {
        return this.id;
    }
    
    public void setId(VqHdrDtlVwId id) {
        this.id = id;
    }




}


