package com.pacificdataservices.diamond.models;
// Generated Apr 25, 2019 6:28:42 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * VqQteVw generated by hbm2java
 */
@Entity
@Table(name="VQ_QTE_VW"
)
@XmlRootElement
public class VqQteVw  implements java.io.Serializable {


     private int vqQteDtlNbr;
     private int vqQteHdrNbr;
     private String vqQteCd;
     private int orgNbrVnd;
     private Date vqQteDt;
     private String orgCd;
     private String orgNm;
     private String currCdQte;
     private String indivNmSpokenTo;
     private String indivPhnNbr;
     private String indivFaxNbr;
     private String indivEmailAddr;
     private Date vqQteEffDt;
     private Date vqQteExpDt;
     private String vndQteRefCd;
     private int vqQteIndivNbr;
     private String transmitFlg;
     private Integer itemNbrQte;
     private String itemCdQte;
     private String itemCdVnd;
     private String qteUm;
     private BigDecimal qteQty;
     private BigDecimal qteQtyStkUm;
     private BigDecimal qteCost;
     private BigDecimal qteCostDenom;
     private BigDecimal qteCostStkUm;
     private BigDecimal qteCostDenomStkUm;
     private Integer orgNbrMfrRqst;
     private String revLvl;
     private Date rqstDt;
     private Short leadTmWkProm;
     private Date promDt;
     private String vqLostCd;

    public VqQteVw() {
    }

	
    public VqQteVw(int vqQteDtlNbr, int vqQteHdrNbr, String vqQteCd, int orgNbrVnd, Date vqQteDt, String orgCd, String orgNm, String currCdQte, Date vqQteEffDt, Date vqQteExpDt, int vqQteIndivNbr, String transmitFlg, String itemCdQte, String itemCdVnd, String qteUm, BigDecimal qteQty, BigDecimal qteQtyStkUm, Date rqstDt) {
        this.vqQteDtlNbr = vqQteDtlNbr;
        this.vqQteHdrNbr = vqQteHdrNbr;
        this.vqQteCd = vqQteCd;
        this.orgNbrVnd = orgNbrVnd;
        this.vqQteDt = vqQteDt;
        this.orgCd = orgCd;
        this.orgNm = orgNm;
        this.currCdQte = currCdQte;
        this.vqQteEffDt = vqQteEffDt;
        this.vqQteExpDt = vqQteExpDt;
        this.vqQteIndivNbr = vqQteIndivNbr;
        this.transmitFlg = transmitFlg;
        this.itemCdQte = itemCdQte;
        this.itemCdVnd = itemCdVnd;
        this.qteUm = qteUm;
        this.qteQty = qteQty;
        this.qteQtyStkUm = qteQtyStkUm;
        this.rqstDt = rqstDt;
    }
    public VqQteVw(int vqQteDtlNbr, int vqQteHdrNbr, String vqQteCd, int orgNbrVnd, Date vqQteDt, String orgCd, String orgNm, String currCdQte, String indivNmSpokenTo, String indivPhnNbr, String indivFaxNbr, String indivEmailAddr, Date vqQteEffDt, Date vqQteExpDt, String vndQteRefCd, int vqQteIndivNbr, String transmitFlg, Integer itemNbrQte, String itemCdQte, String itemCdVnd, String qteUm, BigDecimal qteQty, BigDecimal qteQtyStkUm, BigDecimal qteCost, BigDecimal qteCostDenom, BigDecimal qteCostStkUm, BigDecimal qteCostDenomStkUm, Integer orgNbrMfrRqst, String revLvl, Date rqstDt, Short leadTmWkProm, Date promDt, String vqLostCd) {
       this.vqQteDtlNbr = vqQteDtlNbr;
       this.vqQteHdrNbr = vqQteHdrNbr;
       this.vqQteCd = vqQteCd;
       this.orgNbrVnd = orgNbrVnd;
       this.vqQteDt = vqQteDt;
       this.orgCd = orgCd;
       this.orgNm = orgNm;
       this.currCdQte = currCdQte;
       this.indivNmSpokenTo = indivNmSpokenTo;
       this.indivPhnNbr = indivPhnNbr;
       this.indivFaxNbr = indivFaxNbr;
       this.indivEmailAddr = indivEmailAddr;
       this.vqQteEffDt = vqQteEffDt;
       this.vqQteExpDt = vqQteExpDt;
       this.vndQteRefCd = vndQteRefCd;
       this.vqQteIndivNbr = vqQteIndivNbr;
       this.transmitFlg = transmitFlg;
       this.itemNbrQte = itemNbrQte;
       this.itemCdQte = itemCdQte;
       this.itemCdVnd = itemCdVnd;
       this.qteUm = qteUm;
       this.qteQty = qteQty;
       this.qteQtyStkUm = qteQtyStkUm;
       this.qteCost = qteCost;
       this.qteCostDenom = qteCostDenom;
       this.qteCostStkUm = qteCostStkUm;
       this.qteCostDenomStkUm = qteCostDenomStkUm;
       this.orgNbrMfrRqst = orgNbrMfrRqst;
       this.revLvl = revLvl;
       this.rqstDt = rqstDt;
       this.leadTmWkProm = leadTmWkProm;
       this.promDt = promDt;
       this.vqLostCd = vqLostCd;
    }
   
     @Id 

    
    @Column(name="VQ_QTE_DTL_NBR", nullable=false, precision=9, scale=0)
    public int getVqQteDtlNbr() {
        return this.vqQteDtlNbr;
    }
    
    public void setVqQteDtlNbr(int vqQteDtlNbr) {
        this.vqQteDtlNbr = vqQteDtlNbr;
    }

    
    @Column(name="VQ_QTE_HDR_NBR", nullable=false, precision=9, scale=0)
    public int getVqQteHdrNbr() {
        return this.vqQteHdrNbr;
    }
    
    public void setVqQteHdrNbr(int vqQteHdrNbr) {
        this.vqQteHdrNbr = vqQteHdrNbr;
    }

    
    @Column(name="VQ_QTE_CD", nullable=false, length=20)
    public String getVqQteCd() {
        return this.vqQteCd;
    }
    
    public void setVqQteCd(String vqQteCd) {
        this.vqQteCd = vqQteCd;
    }

    
    @Column(name="ORG_NBR_VND", nullable=false, precision=9, scale=0)
    public int getOrgNbrVnd() {
        return this.orgNbrVnd;
    }
    
    public void setOrgNbrVnd(int orgNbrVnd) {
        this.orgNbrVnd = orgNbrVnd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VQ_QTE_DT", nullable=false, length=7)
    public Date getVqQteDt() {
        return this.vqQteDt;
    }
    
    public void setVqQteDt(Date vqQteDt) {
        this.vqQteDt = vqQteDt;
    }

    
    @Column(name="ORG_CD", nullable=false, length=15)
    public String getOrgCd() {
        return this.orgCd;
    }
    
    public void setOrgCd(String orgCd) {
        this.orgCd = orgCd;
    }

    
    @Column(name="ORG_NM", nullable=false, length=60)
    public String getOrgNm() {
        return this.orgNm;
    }
    
    public void setOrgNm(String orgNm) {
        this.orgNm = orgNm;
    }

    
    @Column(name="CURR_CD_QTE", nullable=false, length=9)
    public String getCurrCdQte() {
        return this.currCdQte;
    }
    
    public void setCurrCdQte(String currCdQte) {
        this.currCdQte = currCdQte;
    }

    
    @Column(name="INDIV_NM_SPOKEN_TO", length=40)
    public String getIndivNmSpokenTo() {
        return this.indivNmSpokenTo;
    }
    
    public void setIndivNmSpokenTo(String indivNmSpokenTo) {
        this.indivNmSpokenTo = indivNmSpokenTo;
    }

    
    @Column(name="INDIV_PHN_NBR", length=20)
    public String getIndivPhnNbr() {
        return this.indivPhnNbr;
    }
    
    public void setIndivPhnNbr(String indivPhnNbr) {
        this.indivPhnNbr = indivPhnNbr;
    }

    
    @Column(name="INDIV_FAX_NBR", length=20)
    public String getIndivFaxNbr() {
        return this.indivFaxNbr;
    }
    
    public void setIndivFaxNbr(String indivFaxNbr) {
        this.indivFaxNbr = indivFaxNbr;
    }

    
    @Column(name="INDIV_EMAIL_ADDR", length=40)
    public String getIndivEmailAddr() {
        return this.indivEmailAddr;
    }
    
    public void setIndivEmailAddr(String indivEmailAddr) {
        this.indivEmailAddr = indivEmailAddr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VQ_QTE_EFF_DT", nullable=false, length=7)
    public Date getVqQteEffDt() {
        return this.vqQteEffDt;
    }
    
    public void setVqQteEffDt(Date vqQteEffDt) {
        this.vqQteEffDt = vqQteEffDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VQ_QTE_EXP_DT", nullable=false, length=7)
    public Date getVqQteExpDt() {
        return this.vqQteExpDt;
    }
    
    public void setVqQteExpDt(Date vqQteExpDt) {
        this.vqQteExpDt = vqQteExpDt;
    }

    
    @Column(name="VND_QTE_REF_CD", length=20)
    public String getVndQteRefCd() {
        return this.vndQteRefCd;
    }
    
    public void setVndQteRefCd(String vndQteRefCd) {
        this.vndQteRefCd = vndQteRefCd;
    }

    
    @Column(name="VQ_QTE_INDIV_NBR", nullable=false, precision=9, scale=0)
    public int getVqQteIndivNbr() {
        return this.vqQteIndivNbr;
    }
    
    public void setVqQteIndivNbr(int vqQteIndivNbr) {
        this.vqQteIndivNbr = vqQteIndivNbr;
    }

    
    @Column(name="TRANSMIT_FLG", nullable=false, length=1)
    public String getTransmitFlg() {
        return this.transmitFlg;
    }
    
    public void setTransmitFlg(String transmitFlg) {
        this.transmitFlg = transmitFlg;
    }

    
    @Column(name="ITEM_NBR_QTE", precision=9, scale=0)
    public Integer getItemNbrQte() {
        return this.itemNbrQte;
    }
    
    public void setItemNbrQte(Integer itemNbrQte) {
        this.itemNbrQte = itemNbrQte;
    }

    
    @Column(name="ITEM_CD_QTE", nullable=false, length=50)
    public String getItemCdQte() {
        return this.itemCdQte;
    }
    
    public void setItemCdQte(String itemCdQte) {
        this.itemCdQte = itemCdQte;
    }

    
    @Column(name="ITEM_CD_VND", nullable=false, length=50)
    public String getItemCdVnd() {
        return this.itemCdVnd;
    }
    
    public void setItemCdVnd(String itemCdVnd) {
        this.itemCdVnd = itemCdVnd;
    }

    
    @Column(name="QTE_UM", nullable=false, length=3)
    public String getQteUm() {
        return this.qteUm;
    }
    
    public void setQteUm(String qteUm) {
        this.qteUm = qteUm;
    }

    
    @Column(name="QTE_QTY", nullable=false, precision=13, scale=5)
    public BigDecimal getQteQty() {
        return this.qteQty;
    }
    
    public void setQteQty(BigDecimal qteQty) {
        this.qteQty = qteQty;
    }

    
    @Column(name="QTE_QTY_STK_UM", nullable=false, precision=13, scale=5)
    public BigDecimal getQteQtyStkUm() {
        return this.qteQtyStkUm;
    }
    
    public void setQteQtyStkUm(BigDecimal qteQtyStkUm) {
        this.qteQtyStkUm = qteQtyStkUm;
    }

    
    @Column(name="QTE_COST", precision=17, scale=6)
    public BigDecimal getQteCost() {
        return this.qteCost;
    }
    
    public void setQteCost(BigDecimal qteCost) {
        this.qteCost = qteCost;
    }

    
    @Column(name="QTE_COST_DENOM", precision=17, scale=6)
    public BigDecimal getQteCostDenom() {
        return this.qteCostDenom;
    }
    
    public void setQteCostDenom(BigDecimal qteCostDenom) {
        this.qteCostDenom = qteCostDenom;
    }

    
    @Column(name="QTE_COST_STK_UM", precision=17, scale=6)
    public BigDecimal getQteCostStkUm() {
        return this.qteCostStkUm;
    }
    
    public void setQteCostStkUm(BigDecimal qteCostStkUm) {
        this.qteCostStkUm = qteCostStkUm;
    }

    
    @Column(name="QTE_COST_DENOM_STK_UM", precision=17, scale=6)
    public BigDecimal getQteCostDenomStkUm() {
        return this.qteCostDenomStkUm;
    }
    
    public void setQteCostDenomStkUm(BigDecimal qteCostDenomStkUm) {
        this.qteCostDenomStkUm = qteCostDenomStkUm;
    }

    
    @Column(name="ORG_NBR_MFR_RQST", precision=9, scale=0)
    public Integer getOrgNbrMfrRqst() {
        return this.orgNbrMfrRqst;
    }
    
    public void setOrgNbrMfrRqst(Integer orgNbrMfrRqst) {
        this.orgNbrMfrRqst = orgNbrMfrRqst;
    }

    
    @Column(name="REV_LVL", length=5)
    public String getRevLvl() {
        return this.revLvl;
    }
    
    public void setRevLvl(String revLvl) {
        this.revLvl = revLvl;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RQST_DT", nullable=false, length=7)
    public Date getRqstDt() {
        return this.rqstDt;
    }
    
    public void setRqstDt(Date rqstDt) {
        this.rqstDt = rqstDt;
    }

    
    @Column(name="LEAD_TM_WK_PROM", precision=3, scale=0)
    public Short getLeadTmWkProm() {
        return this.leadTmWkProm;
    }
    
    public void setLeadTmWkProm(Short leadTmWkProm) {
        this.leadTmWkProm = leadTmWkProm;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PROM_DT", length=7)
    public Date getPromDt() {
        return this.promDt;
    }
    
    public void setPromDt(Date promDt) {
        this.promDt = promDt;
    }

    
    @Column(name="VQ_LOST_CD", length=8)
    public String getVqLostCd() {
        return this.vqLostCd;
    }
    
    public void setVqLostCd(String vqLostCd) {
        this.vqLostCd = vqLostCd;
    }




}


