package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VqQteMultipleCert generated by hbm2java
 */
@Entity
@Table(name="VQ_QTE_MULTIPLE_CERT"
)
public class VqQteMultipleCert  implements java.io.Serializable {


     private VqQteMultipleCertId id;
     private VqQteDtl vqQteDtl;
     private IcItemMast icItemMast;
     private int utUserNbr;
     private Date lastModDt;

    public VqQteMultipleCert() {
    }

    public VqQteMultipleCert(VqQteMultipleCertId id, VqQteDtl vqQteDtl, IcItemMast icItemMast, int utUserNbr, Date lastModDt) {
       this.id = id;
       this.vqQteDtl = vqQteDtl;
       this.icItemMast = icItemMast;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vqQteDtlNbr", column=@Column(name="VQ_QTE_DTL_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", nullable=false, precision=9, scale=0) ) } )
    public VqQteMultipleCertId getId() {
        return this.id;
    }
    
    public void setId(VqQteMultipleCertId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VQ_QTE_DTL_NBR", nullable=false, insertable=false, updatable=false)
    public VqQteDtl getVqQteDtl() {
        return this.vqQteDtl;
    }
    
    public void setVqQteDtl(VqQteDtl vqQteDtl) {
        this.vqQteDtl = vqQteDtl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR", nullable=false, insertable=false, updatable=false)
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }




}


