package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VqQteDtl generated by hbm2java
 */
@Entity
@Table(name="VQ_QTE_DTL"
)
public class VqQteDtl  implements java.io.Serializable {


     private int vqQteDtlNbr;
     private PoMfrMast poMfrMast;
     private VqQteHdr vqQteHdr;
     private IcItemMast icItemMast;
     private String itemCdQte;
     private String itemCdVnd;
     private String qteUm;
     private BigDecimal qteQty;
     private BigDecimal qteQtyStkUm;
     private BigDecimal qteCost;
     private BigDecimal qteCostDenom;
     private BigDecimal qteCostStkUm;
     private BigDecimal qteCostDenomStkUm;
     private String revLvl;
     private Date rqstDt;
     private Short leadTmWkProm;
     private Date promDt;
     private String vqLostCd;
     private int utUserNbr;
     private Date lastModDt;
     private Set<VqQteMultipleCert> vqQteMultipleCerts = new HashSet<VqQteMultipleCert>(0);

    public VqQteDtl() {
    }

	
    public VqQteDtl(int vqQteDtlNbr, VqQteHdr vqQteHdr, String itemCdQte, String itemCdVnd, String qteUm, BigDecimal qteQty, BigDecimal qteQtyStkUm, Date rqstDt, int utUserNbr, Date lastModDt) {
        this.vqQteDtlNbr = vqQteDtlNbr;
        this.vqQteHdr = vqQteHdr;
        this.itemCdQte = itemCdQte;
        this.itemCdVnd = itemCdVnd;
        this.qteUm = qteUm;
        this.qteQty = qteQty;
        this.qteQtyStkUm = qteQtyStkUm;
        this.rqstDt = rqstDt;
        this.utUserNbr = utUserNbr;
        this.lastModDt = lastModDt;
    }
    public VqQteDtl(int vqQteDtlNbr, PoMfrMast poMfrMast, VqQteHdr vqQteHdr, IcItemMast icItemMast, String itemCdQte, String itemCdVnd, String qteUm, BigDecimal qteQty, BigDecimal qteQtyStkUm, BigDecimal qteCost, BigDecimal qteCostDenom, BigDecimal qteCostStkUm, BigDecimal qteCostDenomStkUm, String revLvl, Date rqstDt, Short leadTmWkProm, Date promDt, String vqLostCd, int utUserNbr, Date lastModDt, Set<VqQteMultipleCert> vqQteMultipleCerts) {
       this.vqQteDtlNbr = vqQteDtlNbr;
       this.poMfrMast = poMfrMast;
       this.vqQteHdr = vqQteHdr;
       this.icItemMast = icItemMast;
       this.itemCdQte = itemCdQte;
       this.itemCdVnd = itemCdVnd;
       this.qteUm = qteUm;
       this.qteQty = qteQty;
       this.qteQtyStkUm = qteQtyStkUm;
       this.qteCost = qteCost;
       this.qteCostDenom = qteCostDenom;
       this.qteCostStkUm = qteCostStkUm;
       this.qteCostDenomStkUm = qteCostDenomStkUm;
       this.revLvl = revLvl;
       this.rqstDt = rqstDt;
       this.leadTmWkProm = leadTmWkProm;
       this.promDt = promDt;
       this.vqLostCd = vqLostCd;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
       this.vqQteMultipleCerts = vqQteMultipleCerts;
    }
   
     @Id 

    
    @Column(name="VQ_QTE_DTL_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getVqQteDtlNbr() {
        return this.vqQteDtlNbr;
    }
    
    public void setVqQteDtlNbr(int vqQteDtlNbr) {
        this.vqQteDtlNbr = vqQteDtlNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORG_NBR_MFR_RQST")
    public PoMfrMast getPoMfrMast() {
        return this.poMfrMast;
    }
    
    public void setPoMfrMast(PoMfrMast poMfrMast) {
        this.poMfrMast = poMfrMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VQ_QTE_HDR_NBR", nullable=false)
    public VqQteHdr getVqQteHdr() {
        return this.vqQteHdr;
    }
    
    public void setVqQteHdr(VqQteHdr vqQteHdr) {
        this.vqQteHdr = vqQteHdr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR_QTE")
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }

    
    @Column(name="ITEM_CD_QTE", nullable=false, length=50)
    public String getItemCdQte() {
        return this.itemCdQte;
    }
    
    public void setItemCdQte(String itemCdQte) {
        this.itemCdQte = itemCdQte;
    }

    
    @Column(name="ITEM_CD_VND", nullable=false, length=50)
    public String getItemCdVnd() {
        return this.itemCdVnd;
    }
    
    public void setItemCdVnd(String itemCdVnd) {
        this.itemCdVnd = itemCdVnd;
    }

    
    @Column(name="QTE_UM", nullable=false, length=3)
    public String getQteUm() {
        return this.qteUm;
    }
    
    public void setQteUm(String qteUm) {
        this.qteUm = qteUm;
    }

    
    @Column(name="QTE_QTY", nullable=false, precision=13, scale=5)
    public BigDecimal getQteQty() {
        return this.qteQty;
    }
    
    public void setQteQty(BigDecimal qteQty) {
        this.qteQty = qteQty;
    }

    
    @Column(name="QTE_QTY_STK_UM", nullable=false, precision=13, scale=5)
    public BigDecimal getQteQtyStkUm() {
        return this.qteQtyStkUm;
    }
    
    public void setQteQtyStkUm(BigDecimal qteQtyStkUm) {
        this.qteQtyStkUm = qteQtyStkUm;
    }

    
    @Column(name="QTE_COST", precision=17, scale=6)
    public BigDecimal getQteCost() {
        return this.qteCost;
    }
    
    public void setQteCost(BigDecimal qteCost) {
        this.qteCost = qteCost;
    }

    
    @Column(name="QTE_COST_DENOM", precision=17, scale=6)
    public BigDecimal getQteCostDenom() {
        return this.qteCostDenom;
    }
    
    public void setQteCostDenom(BigDecimal qteCostDenom) {
        this.qteCostDenom = qteCostDenom;
    }

    
    @Column(name="QTE_COST_STK_UM", precision=17, scale=6)
    public BigDecimal getQteCostStkUm() {
        return this.qteCostStkUm;
    }
    
    public void setQteCostStkUm(BigDecimal qteCostStkUm) {
        this.qteCostStkUm = qteCostStkUm;
    }

    
    @Column(name="QTE_COST_DENOM_STK_UM", precision=17, scale=6)
    public BigDecimal getQteCostDenomStkUm() {
        return this.qteCostDenomStkUm;
    }
    
    public void setQteCostDenomStkUm(BigDecimal qteCostDenomStkUm) {
        this.qteCostDenomStkUm = qteCostDenomStkUm;
    }

    
    @Column(name="REV_LVL", length=5)
    public String getRevLvl() {
        return this.revLvl;
    }
    
    public void setRevLvl(String revLvl) {
        this.revLvl = revLvl;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RQST_DT", nullable=false, length=7)
    public Date getRqstDt() {
        return this.rqstDt;
    }
    
    public void setRqstDt(Date rqstDt) {
        this.rqstDt = rqstDt;
    }

    
    @Column(name="LEAD_TM_WK_PROM", precision=3, scale=0)
    public Short getLeadTmWkProm() {
        return this.leadTmWkProm;
    }
    
    public void setLeadTmWkProm(Short leadTmWkProm) {
        this.leadTmWkProm = leadTmWkProm;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PROM_DT", length=7)
    public Date getPromDt() {
        return this.promDt;
    }
    
    public void setPromDt(Date promDt) {
        this.promDt = promDt;
    }

    
    @Column(name="VQ_LOST_CD", length=8)
    public String getVqLostCd() {
        return this.vqLostCd;
    }
    
    public void setVqLostCd(String vqLostCd) {
        this.vqLostCd = vqLostCd;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vqQteDtl")
    public Set<VqQteMultipleCert> getVqQteMultipleCerts() {
        return this.vqQteMultipleCerts;
    }
    
    public void setVqQteMultipleCerts(Set<VqQteMultipleCert> vqQteMultipleCerts) {
        this.vqQteMultipleCerts = vqQteMultipleCerts;
    }




}


