package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WhFacilityTransOnhand generated by hbm2java
 */
@Entity
@Table(name="WH_FACILITY_TRANS_ONHAND"
)
public class WhFacilityTransOnhand  implements java.io.Serializable {


     private int whFacilityTransOnhandNbr;
     private ApsSplySubPool apsSplySubPoolByApsSplySubPoolNbrDest;
     private ApsSplySubPool apsSplySubPoolByApsSplySubPoolNbrSrc;
     private UtFacility utFacility;
     private IcLotMast icLotMast;
     private IcItemLocBox icItemLocBox;
     private String rqstStatId;
     private String facilitySrc;
     private BigDecimal qtyRqst;
     private Date rqstDt;
     private int utUserNbrRqst;
     private Integer utUserNbrConfirm;
     private int utUserNbr;
     private Date lastModDt;
     private Date availDt;
     private Set<ApsAllocOnhandFc> apsAllocOnhandFcs = new HashSet<ApsAllocOnhandFc>(0);
     private Set<ApsAllocOnhandOo> apsAllocOnhandOos = new HashSet<ApsAllocOnhandOo>(0);
     private Set<WhPickDtlTransRqst> whPickDtlTransRqsts = new HashSet<WhPickDtlTransRqst>(0);
     private Set<ApsAllocOnhandSs> apsAllocOnhandSses = new HashSet<ApsAllocOnhandSs>(0);
     private Set<ApsAllocOnhandWo> apsAllocOnhandWos = new HashSet<ApsAllocOnhandWo>(0);

    public WhFacilityTransOnhand() {
    }

	
    public WhFacilityTransOnhand(int whFacilityTransOnhandNbr, ApsSplySubPool apsSplySubPoolByApsSplySubPoolNbrDest, ApsSplySubPool apsSplySubPoolByApsSplySubPoolNbrSrc, UtFacility utFacility, IcLotMast icLotMast, String rqstStatId, String facilitySrc, BigDecimal qtyRqst, Date rqstDt, int utUserNbrRqst, int utUserNbr, Date lastModDt) {
        this.whFacilityTransOnhandNbr = whFacilityTransOnhandNbr;
        this.apsSplySubPoolByApsSplySubPoolNbrDest = apsSplySubPoolByApsSplySubPoolNbrDest;
        this.apsSplySubPoolByApsSplySubPoolNbrSrc = apsSplySubPoolByApsSplySubPoolNbrSrc;
        this.utFacility = utFacility;
        this.icLotMast = icLotMast;
        this.rqstStatId = rqstStatId;
        this.facilitySrc = facilitySrc;
        this.qtyRqst = qtyRqst;
        this.rqstDt = rqstDt;
        this.utUserNbrRqst = utUserNbrRqst;
        this.utUserNbr = utUserNbr;
        this.lastModDt = lastModDt;
    }
    public WhFacilityTransOnhand(int whFacilityTransOnhandNbr, ApsSplySubPool apsSplySubPoolByApsSplySubPoolNbrDest, ApsSplySubPool apsSplySubPoolByApsSplySubPoolNbrSrc, UtFacility utFacility, IcLotMast icLotMast, IcItemLocBox icItemLocBox, String rqstStatId, String facilitySrc, BigDecimal qtyRqst, Date rqstDt, int utUserNbrRqst, Integer utUserNbrConfirm, int utUserNbr, Date lastModDt, Date availDt, Set<ApsAllocOnhandFc> apsAllocOnhandFcs, Set<ApsAllocOnhandOo> apsAllocOnhandOos, Set<WhPickDtlTransRqst> whPickDtlTransRqsts, Set<ApsAllocOnhandSs> apsAllocOnhandSses, Set<ApsAllocOnhandWo> apsAllocOnhandWos) {
       this.whFacilityTransOnhandNbr = whFacilityTransOnhandNbr;
       this.apsSplySubPoolByApsSplySubPoolNbrDest = apsSplySubPoolByApsSplySubPoolNbrDest;
       this.apsSplySubPoolByApsSplySubPoolNbrSrc = apsSplySubPoolByApsSplySubPoolNbrSrc;
       this.utFacility = utFacility;
       this.icLotMast = icLotMast;
       this.icItemLocBox = icItemLocBox;
       this.rqstStatId = rqstStatId;
       this.facilitySrc = facilitySrc;
       this.qtyRqst = qtyRqst;
       this.rqstDt = rqstDt;
       this.utUserNbrRqst = utUserNbrRqst;
       this.utUserNbrConfirm = utUserNbrConfirm;
       this.utUserNbr = utUserNbr;
       this.lastModDt = lastModDt;
       this.availDt = availDt;
       this.apsAllocOnhandFcs = apsAllocOnhandFcs;
       this.apsAllocOnhandOos = apsAllocOnhandOos;
       this.whPickDtlTransRqsts = whPickDtlTransRqsts;
       this.apsAllocOnhandSses = apsAllocOnhandSses;
       this.apsAllocOnhandWos = apsAllocOnhandWos;
    }
   
     @Id 

    
    @Column(name="WH_FACILITY_TRANS_ONHAND_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getWhFacilityTransOnhandNbr() {
        return this.whFacilityTransOnhandNbr;
    }
    
    public void setWhFacilityTransOnhandNbr(int whFacilityTransOnhandNbr) {
        this.whFacilityTransOnhandNbr = whFacilityTransOnhandNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APS_SPLY_SUB_POOL_NBR_DEST", nullable=false)
    public ApsSplySubPool getApsSplySubPoolByApsSplySubPoolNbrDest() {
        return this.apsSplySubPoolByApsSplySubPoolNbrDest;
    }
    
    public void setApsSplySubPoolByApsSplySubPoolNbrDest(ApsSplySubPool apsSplySubPoolByApsSplySubPoolNbrDest) {
        this.apsSplySubPoolByApsSplySubPoolNbrDest = apsSplySubPoolByApsSplySubPoolNbrDest;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APS_SPLY_SUB_POOL_NBR_SRC", nullable=false)
    public ApsSplySubPool getApsSplySubPoolByApsSplySubPoolNbrSrc() {
        return this.apsSplySubPoolByApsSplySubPoolNbrSrc;
    }
    
    public void setApsSplySubPoolByApsSplySubPoolNbrSrc(ApsSplySubPool apsSplySubPoolByApsSplySubPoolNbrSrc) {
        this.apsSplySubPoolByApsSplySubPoolNbrSrc = apsSplySubPoolByApsSplySubPoolNbrSrc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FACILITY_DEST", nullable=false)
    public UtFacility getUtFacility() {
        return this.utFacility;
    }
    
    public void setUtFacility(UtFacility utFacility) {
        this.utFacility = utFacility;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LOT_NBR", nullable=false)
    public IcLotMast getIcLotMast() {
        return this.icLotMast;
    }
    
    public void setIcLotMast(IcLotMast icLotMast) {
        this.icLotMast = icLotMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BOX_CD")
    public IcItemLocBox getIcItemLocBox() {
        return this.icItemLocBox;
    }
    
    public void setIcItemLocBox(IcItemLocBox icItemLocBox) {
        this.icItemLocBox = icItemLocBox;
    }

    
    @Column(name="RQST_STAT_ID", nullable=false, length=1)
    public String getRqstStatId() {
        return this.rqstStatId;
    }
    
    public void setRqstStatId(String rqstStatId) {
        this.rqstStatId = rqstStatId;
    }

    
    @Column(name="FACILITY_SRC", nullable=false, length=16)
    public String getFacilitySrc() {
        return this.facilitySrc;
    }
    
    public void setFacilitySrc(String facilitySrc) {
        this.facilitySrc = facilitySrc;
    }

    
    @Column(name="QTY_RQST", nullable=false, precision=13, scale=5)
    public BigDecimal getQtyRqst() {
        return this.qtyRqst;
    }
    
    public void setQtyRqst(BigDecimal qtyRqst) {
        this.qtyRqst = qtyRqst;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RQST_DT", nullable=false, length=7)
    public Date getRqstDt() {
        return this.rqstDt;
    }
    
    public void setRqstDt(Date rqstDt) {
        this.rqstDt = rqstDt;
    }

    
    @Column(name="UT_USER_NBR_RQST", nullable=false, precision=9, scale=0)
    public int getUtUserNbrRqst() {
        return this.utUserNbrRqst;
    }
    
    public void setUtUserNbrRqst(int utUserNbrRqst) {
        this.utUserNbrRqst = utUserNbrRqst;
    }

    
    @Column(name="UT_USER_NBR_CONFIRM", precision=9, scale=0)
    public Integer getUtUserNbrConfirm() {
        return this.utUserNbrConfirm;
    }
    
    public void setUtUserNbrConfirm(Integer utUserNbrConfirm) {
        this.utUserNbrConfirm = utUserNbrConfirm;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="AVAIL_DT", length=7)
    public Date getAvailDt() {
        return this.availDt;
    }
    
    public void setAvailDt(Date availDt) {
        this.availDt = availDt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="whFacilityTransOnhand")
    public Set<ApsAllocOnhandFc> getApsAllocOnhandFcs() {
        return this.apsAllocOnhandFcs;
    }
    
    public void setApsAllocOnhandFcs(Set<ApsAllocOnhandFc> apsAllocOnhandFcs) {
        this.apsAllocOnhandFcs = apsAllocOnhandFcs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="whFacilityTransOnhand")
    public Set<ApsAllocOnhandOo> getApsAllocOnhandOos() {
        return this.apsAllocOnhandOos;
    }
    
    public void setApsAllocOnhandOos(Set<ApsAllocOnhandOo> apsAllocOnhandOos) {
        this.apsAllocOnhandOos = apsAllocOnhandOos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="whFacilityTransOnhand")
    public Set<WhPickDtlTransRqst> getWhPickDtlTransRqsts() {
        return this.whPickDtlTransRqsts;
    }
    
    public void setWhPickDtlTransRqsts(Set<WhPickDtlTransRqst> whPickDtlTransRqsts) {
        this.whPickDtlTransRqsts = whPickDtlTransRqsts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="whFacilityTransOnhand")
    public Set<ApsAllocOnhandSs> getApsAllocOnhandSses() {
        return this.apsAllocOnhandSses;
    }
    
    public void setApsAllocOnhandSses(Set<ApsAllocOnhandSs> apsAllocOnhandSses) {
        this.apsAllocOnhandSses = apsAllocOnhandSses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="whFacilityTransOnhand")
    public Set<ApsAllocOnhandWo> getApsAllocOnhandWos() {
        return this.apsAllocOnhandWos;
    }
    
    public void setApsAllocOnhandWos(Set<ApsAllocOnhandWo> apsAllocOnhandWos) {
        this.apsAllocOnhandWos = apsAllocOnhandWos;
    }




}


