package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WhPickDtlCopRqstExtVw generated by hbm2java
 */
@Entity
@Table(name="WH_PICK_DTL_COP_RQST_EXT_VW"
)
public class WhPickDtlCopRqstExtVw  implements java.io.Serializable {


     private WhPickDtlCopRqstExtVwId id;

    public WhPickDtlCopRqstExtVw() {
    }

    public WhPickDtlCopRqstExtVw(WhPickDtlCopRqstExtVwId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="whPickDtlCopRqstNbr", column=@Column(name="WH_PICK_DTL_COP_RQST_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="whPickBatchCopNbr", column=@Column(name="WH_PICK_BATCH_COP_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="icItemLocNbr", column=@Column(name="IC_ITEM_LOC_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="boxCd", column=@Column(name="BOX_CD", nullable=false, length=20) ), 
        @AttributeOverride(name="copPickQtyRqst", column=@Column(name="COP_PICK_QTY_RQST", nullable=false, precision=13, scale=5) ), 
        @AttributeOverride(name="copPickQtyAct", column=@Column(name="COP_PICK_QTY_ACT", precision=13, scale=5) ), 
        @AttributeOverride(name="oeOrdDtlNbr", column=@Column(name="OE_ORD_DTL_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="apsAllocOnhandOoNbr", column=@Column(name="APS_ALLOC_ONHAND_OO_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="boxCdDest", column=@Column(name="BOX_CD_DEST", length=20) ), 
        @AttributeOverride(name="boxCnt", column=@Column(name="BOX_CNT", precision=5, scale=0) ), 
        @AttributeOverride(name="pickScanCd", column=@Column(name="PICK_SCAN_CD", length=20) ), 
        @AttributeOverride(name="whPickDtlCopRqstNbrSrc", column=@Column(name="WH_PICK_DTL_COP_RQST_NBR_SRC", precision=9, scale=0) ), 
        @AttributeOverride(name="itemCd", column=@Column(name="ITEM_CD", nullable=false, length=50) ), 
        @AttributeOverride(name="itemDescr", column=@Column(name="ITEM_DESCR", nullable=false, length=50) ), 
        @AttributeOverride(name="stkUm", column=@Column(name="STK_UM", nullable=false, length=3) ), 
        @AttributeOverride(name="binCd", column=@Column(name="BIN_CD", nullable=false, length=16) ), 
        @AttributeOverride(name="binNbr", column=@Column(name="BIN_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="facility", column=@Column(name="FACILITY", nullable=false, length=16) ), 
        @AttributeOverride(name="whWhseZoneNbr", column=@Column(name="WH_WHSE_ZONE_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="orgNbrMfr", column=@Column(name="ORG_NBR_MFR", precision=9, scale=0) ), 
        @AttributeOverride(name="mfrLotCd", column=@Column(name="MFR_LOT_CD", length=20) ), 
        @AttributeOverride(name="apsSplySubPoolNbr", column=@Column(name="APS_SPLY_SUB_POOL_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="boxStatId", column=@Column(name="BOX_STAT_ID", nullable=false, length=3) ), 
        @AttributeOverride(name="ordCd", column=@Column(name="ORD_CD", nullable=false, length=20) ), 
        @AttributeOverride(name="lineNbr", column=@Column(name="LINE_NBR", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="orgNbrCust", column=@Column(name="ORG_NBR_CUST", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="orgCdCust", column=@Column(name="ORG_CD_CUST", nullable=false, length=15) ), 
        @AttributeOverride(name="orgNmCust", column=@Column(name="ORG_NM_CUST", nullable=false, length=60) ), 
        @AttributeOverride(name="lotNbr", column=@Column(name="LOT_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="itemCdCust", column=@Column(name="ITEM_CD_CUST", length=50) ), 
        @AttributeOverride(name="itemNbrOrd", column=@Column(name="ITEM_NBR_ORD", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="itemCdOrd", column=@Column(name="ITEM_CD_ORD", nullable=false, length=50) ), 
        @AttributeOverride(name="itemDescrOrd", column=@Column(name="ITEM_DESCR_ORD", nullable=false, length=50) ), 
        @AttributeOverride(name="custPoCd", column=@Column(name="CUST_PO_CD", length=30) ), 
        @AttributeOverride(name="orgCdMfr", column=@Column(name="ORG_CD_MFR", length=15) ), 
        @AttributeOverride(name="orgNmMfr", column=@Column(name="ORG_NM_MFR", length=60) ), 
        @AttributeOverride(name="revLvl", column=@Column(name="REV_LVL", length=5) ), 
        @AttributeOverride(name="lotCostUm", column=@Column(name="LOT_COST_UM", nullable=false, length=3) ), 
        @AttributeOverride(name="mfrSerialCd", column=@Column(name="MFR_SERIAL_CD", length=20) ), 
        @AttributeOverride(name="serialCd", column=@Column(name="SERIAL_CD", length=20) ), 
        @AttributeOverride(name="custLineCd", column=@Column(name="CUST_LINE_CD", length=5) ), 
        @AttributeOverride(name="labelNmBag", column=@Column(name="LABEL_NM_BAG", length=4000) ), 
        @AttributeOverride(name="labelNmPackBox", column=@Column(name="LABEL_NM_PACK_BOX", length=4000) ), 
        @AttributeOverride(name="packBoxContentsRptNm", column=@Column(name="PACK_BOX_CONTENTS_RPT_NM", length=4000) ), 
        @AttributeOverride(name="packSlipRptNm", column=@Column(name="PACK_SLIP_RPT_NM", length=4000) ), 
        @AttributeOverride(name="showPriceOnPackSlipFlg", column=@Column(name="SHOW_PRICE_ON_PACK_SLIP_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="nbrPackSlipCopies", column=@Column(name="NBR_PACK_SLIP_COPIES", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="walkSeq", column=@Column(name="WALK_SEQ", precision=5, scale=0) ), 
        @AttributeOverride(name="custRef", column=@Column(name="CUST_REF", length=40) ), 
        @AttributeOverride(name="pickScanId", column=@Column(name="PICK_SCAN_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="splitAtBinFlg", column=@Column(name="SPLIT_AT_BIN_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="upcCd", column=@Column(name="UPC_CD", length=20) ), 
        @AttributeOverride(name="ean", column=@Column(name="EAN", length=50) ), 
        @AttributeOverride(name="qtyPerBox", column=@Column(name="QTY_PER_BOX", precision=22, scale=0) ), 
        @AttributeOverride(name="shipCmpltFlg", column=@Column(name="SHIP_CMPLT_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="hotFlg", column=@Column(name="HOT_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="qtyOrd", column=@Column(name="QTY_ORD", nullable=false, precision=15, scale=5) ), 
        @AttributeOverride(name="qtyShip", column=@Column(name="QTY_SHIP", precision=15, scale=5) ), 
        @AttributeOverride(name="custBinCd", column=@Column(name="CUST_BIN_CD", length=40) ), 
        @AttributeOverride(name="mfrCageCd", column=@Column(name="MFR_CAGE_CD", length=10) ), 
        @AttributeOverride(name="oeOrdHdrNbr", column=@Column(name="OE_ORD_HDR_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="shipToAddrNbr", column=@Column(name="SHIP_TO_ADDR_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="shipLinePct", column=@Column(name="SHIP_LINE_PCT", precision=3, scale=0) ), 
        @AttributeOverride(name="autoCloseLinePct", column=@Column(name="AUTO_CLOSE_LINE_PCT", precision=3, scale=0) ), 
        @AttributeOverride(name="maxShipmentsPerLine", column=@Column(name="MAX_SHIPMENTS_PER_LINE", precision=2, scale=0) ), 
        @AttributeOverride(name="shipViaCd", column=@Column(name="SHIP_VIA_CD", nullable=false, length=8) ), 
        @AttributeOverride(name="pkgQty", column=@Column(name="PKG_QTY", precision=7, scale=0) ) } )
    public WhPickDtlCopRqstExtVwId getId() {
        return this.id;
    }
    
    public void setId(WhPickDtlCopRqstExtVwId id) {
        this.id = id;
    }




}


