package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WhPickDtlWoRqstExtVw generated by hbm2java
 */
@Entity
@Table(name="WH_PICK_DTL_WO_RQST_EXT_VW"
)
public class WhPickDtlWoRqstExtVw  implements java.io.Serializable {


     private WhPickDtlWoRqstExtVwId id;

    public WhPickDtlWoRqstExtVw() {
    }

    public WhPickDtlWoRqstExtVw(WhPickDtlWoRqstExtVwId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="whPickDtlWoRqstNbr", column=@Column(name="WH_PICK_DTL_WO_RQST_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="whPickBatchWoNbr", column=@Column(name="WH_PICK_BATCH_WO_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="icItemLocNbr", column=@Column(name="IC_ITEM_LOC_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="boxCd", column=@Column(name="BOX_CD", length=20) ), 
        @AttributeOverride(name="woPickQtyRqst", column=@Column(name="WO_PICK_QTY_RQST", nullable=false, precision=13, scale=5) ), 
        @AttributeOverride(name="woPickQtyAct", column=@Column(name="WO_PICK_QTY_ACT", precision=13, scale=5) ), 
        @AttributeOverride(name="woDtlNbr", column=@Column(name="WO_DTL_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="woReleaseNbr", column=@Column(name="WO_RELEASE_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="apsAllocOnhandWoNbr", column=@Column(name="APS_ALLOC_ONHAND_WO_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="pickScanCd", column=@Column(name="PICK_SCAN_CD", length=20) ), 
        @AttributeOverride(name="boxCdDest", column=@Column(name="BOX_CD_DEST", length=20) ), 
        @AttributeOverride(name="boxCnt", column=@Column(name="BOX_CNT", precision=5, scale=0) ), 
        @AttributeOverride(name="itemCd", column=@Column(name="ITEM_CD", nullable=false, length=50) ), 
        @AttributeOverride(name="itemDescr", column=@Column(name="ITEM_DESCR", nullable=false, length=50) ), 
        @AttributeOverride(name="binNbr", column=@Column(name="BIN_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="binCd", column=@Column(name="BIN_CD", nullable=false, length=16) ), 
        @AttributeOverride(name="facility", column=@Column(name="FACILITY", nullable=false, length=16) ), 
        @AttributeOverride(name="whWhseZoneNbr", column=@Column(name="WH_WHSE_ZONE_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="itemNbr", column=@Column(name="ITEM_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="orgNbrMfr", column=@Column(name="ORG_NBR_MFR", precision=9, scale=0) ), 
        @AttributeOverride(name="mfrLotCd", column=@Column(name="MFR_LOT_CD", length=20) ), 
        @AttributeOverride(name="apsSplySubPoolNbr", column=@Column(name="APS_SPLY_SUB_POOL_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="lotNbr", column=@Column(name="LOT_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="boxStatId", column=@Column(name="BOX_STAT_ID", nullable=false, length=3) ), 
        @AttributeOverride(name="lotCostUm", column=@Column(name="LOT_COST_UM", nullable=false, length=3) ), 
        @AttributeOverride(name="revLvl", column=@Column(name="REV_LVL", length=5) ), 
        @AttributeOverride(name="mfrSerialCd", column=@Column(name="MFR_SERIAL_CD", length=20) ), 
        @AttributeOverride(name="serialCd", column=@Column(name="SERIAL_CD", length=20) ), 
        @AttributeOverride(name="orgCdMfr", column=@Column(name="ORG_CD_MFR", length=15) ), 
        @AttributeOverride(name="orgNmMfr", column=@Column(name="ORG_NM_MFR", length=60) ), 
        @AttributeOverride(name="woHdrNbr", column=@Column(name="WO_HDR_NBR", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="walkSeq", column=@Column(name="WALK_SEQ", precision=5, scale=0) ), 
        @AttributeOverride(name="pickScanId", column=@Column(name="PICK_SCAN_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="splitAtBinFlg", column=@Column(name="SPLIT_AT_BIN_FLG", nullable=false, length=1) ), 
        @AttributeOverride(name="upcCd", column=@Column(name="UPC_CD", length=20) ), 
        @AttributeOverride(name="ean", column=@Column(name="EAN", length=50) ), 
        @AttributeOverride(name="replenTypeId", column=@Column(name="REPLEN_TYPE_ID", nullable=false, length=1) ), 
        @AttributeOverride(name="itemCdComponent", column=@Column(name="ITEM_CD_COMPONENT", nullable=false, length=50) ), 
        @AttributeOverride(name="itemDescrComponent", column=@Column(name="ITEM_DESCR_COMPONENT", nullable=false, length=50) ) } )
    public WhPickDtlWoRqstExtVwId getId() {
        return this.id;
    }
    
    public void setId(WhPickDtlWoRqstExtVwId id) {
        this.id = id;
    }




}


