package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WhPickDtlCopRqst generated by hbm2java
 */
@Entity
@Table(name="WH_PICK_DTL_COP_RQST"
)
public class WhPickDtlCopRqst  implements java.io.Serializable {


     private int whPickDtlCopRqstNbr;
     private ApsAllocOnhandOo apsAllocOnhandOo;
     private OeOrdDtl oeOrdDtl;
     private IcItemLoc icItemLoc;
     private IcItemLocBox icItemLocBox;
     private int whPickBatchCopNbr;
     private BigDecimal copPickQtyRqst;
     private BigDecimal copPickQtyAct;
     private Integer whPickDtlCopRqstNbrSrc;
     private Integer boxCnt;
     private String boxCdDest;
     private String pickScanCd;

    public WhPickDtlCopRqst() {
    }

	
    public WhPickDtlCopRqst(int whPickDtlCopRqstNbr, ApsAllocOnhandOo apsAllocOnhandOo, OeOrdDtl oeOrdDtl, IcItemLocBox icItemLocBox, int whPickBatchCopNbr, BigDecimal copPickQtyRqst) {
        this.whPickDtlCopRqstNbr = whPickDtlCopRqstNbr;
        this.apsAllocOnhandOo = apsAllocOnhandOo;
        this.oeOrdDtl = oeOrdDtl;
        this.icItemLocBox = icItemLocBox;
        this.whPickBatchCopNbr = whPickBatchCopNbr;
        this.copPickQtyRqst = copPickQtyRqst;
    }
    public WhPickDtlCopRqst(int whPickDtlCopRqstNbr, ApsAllocOnhandOo apsAllocOnhandOo, OeOrdDtl oeOrdDtl, IcItemLoc icItemLoc, IcItemLocBox icItemLocBox, int whPickBatchCopNbr, BigDecimal copPickQtyRqst, BigDecimal copPickQtyAct, Integer whPickDtlCopRqstNbrSrc, Integer boxCnt, String boxCdDest, String pickScanCd) {
       this.whPickDtlCopRqstNbr = whPickDtlCopRqstNbr;
       this.apsAllocOnhandOo = apsAllocOnhandOo;
       this.oeOrdDtl = oeOrdDtl;
       this.icItemLoc = icItemLoc;
       this.icItemLocBox = icItemLocBox;
       this.whPickBatchCopNbr = whPickBatchCopNbr;
       this.copPickQtyRqst = copPickQtyRqst;
       this.copPickQtyAct = copPickQtyAct;
       this.whPickDtlCopRqstNbrSrc = whPickDtlCopRqstNbrSrc;
       this.boxCnt = boxCnt;
       this.boxCdDest = boxCdDest;
       this.pickScanCd = pickScanCd;
    }
   
     @Id 

    
    @Column(name="WH_PICK_DTL_COP_RQST_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getWhPickDtlCopRqstNbr() {
        return this.whPickDtlCopRqstNbr;
    }
    
    public void setWhPickDtlCopRqstNbr(int whPickDtlCopRqstNbr) {
        this.whPickDtlCopRqstNbr = whPickDtlCopRqstNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APS_ALLOC_ONHAND_OO_NBR", nullable=false)
    public ApsAllocOnhandOo getApsAllocOnhandOo() {
        return this.apsAllocOnhandOo;
    }
    
    public void setApsAllocOnhandOo(ApsAllocOnhandOo apsAllocOnhandOo) {
        this.apsAllocOnhandOo = apsAllocOnhandOo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OE_ORD_DTL_NBR", nullable=false)
    public OeOrdDtl getOeOrdDtl() {
        return this.oeOrdDtl;
    }
    
    public void setOeOrdDtl(OeOrdDtl oeOrdDtl) {
        this.oeOrdDtl = oeOrdDtl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IC_ITEM_LOC_NBR")
    public IcItemLoc getIcItemLoc() {
        return this.icItemLoc;
    }
    
    public void setIcItemLoc(IcItemLoc icItemLoc) {
        this.icItemLoc = icItemLoc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BOX_CD", nullable=false)
    public IcItemLocBox getIcItemLocBox() {
        return this.icItemLocBox;
    }
    
    public void setIcItemLocBox(IcItemLocBox icItemLocBox) {
        this.icItemLocBox = icItemLocBox;
    }

    
    @Column(name="WH_PICK_BATCH_COP_NBR", nullable=false, precision=9, scale=0)
    public int getWhPickBatchCopNbr() {
        return this.whPickBatchCopNbr;
    }
    
    public void setWhPickBatchCopNbr(int whPickBatchCopNbr) {
        this.whPickBatchCopNbr = whPickBatchCopNbr;
    }

    
    @Column(name="COP_PICK_QTY_RQST", nullable=false, precision=13, scale=5)
    public BigDecimal getCopPickQtyRqst() {
        return this.copPickQtyRqst;
    }
    
    public void setCopPickQtyRqst(BigDecimal copPickQtyRqst) {
        this.copPickQtyRqst = copPickQtyRqst;
    }

    
    @Column(name="COP_PICK_QTY_ACT", precision=13, scale=5)
    public BigDecimal getCopPickQtyAct() {
        return this.copPickQtyAct;
    }
    
    public void setCopPickQtyAct(BigDecimal copPickQtyAct) {
        this.copPickQtyAct = copPickQtyAct;
    }

    
    @Column(name="WH_PICK_DTL_COP_RQST_NBR_SRC", precision=9, scale=0)
    public Integer getWhPickDtlCopRqstNbrSrc() {
        return this.whPickDtlCopRqstNbrSrc;
    }
    
    public void setWhPickDtlCopRqstNbrSrc(Integer whPickDtlCopRqstNbrSrc) {
        this.whPickDtlCopRqstNbrSrc = whPickDtlCopRqstNbrSrc;
    }

    
    @Column(name="BOX_CNT", precision=5, scale=0)
    public Integer getBoxCnt() {
        return this.boxCnt;
    }
    
    public void setBoxCnt(Integer boxCnt) {
        this.boxCnt = boxCnt;
    }

    
    @Column(name="BOX_CD_DEST", length=20)
    public String getBoxCdDest() {
        return this.boxCdDest;
    }
    
    public void setBoxCdDest(String boxCdDest) {
        this.boxCdDest = boxCdDest;
    }

    
    @Column(name="PICK_SCAN_CD", length=20)
    public String getPickScanCd() {
        return this.pickScanCd;
    }
    
    public void setPickScanCd(String pickScanCd) {
        this.pickScanCd = pickScanCd;
    }




}


