package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WhPickDtlWoRqst generated by hbm2java
 */
@Entity
@Table(name="WH_PICK_DTL_WO_RQST"
)
public class WhPickDtlWoRqst  implements java.io.Serializable {


     private int whPickDtlWoRqstNbr;
     private ApsAllocOnhandWo apsAllocOnhandWo;
     private WoDtl woDtl;
     private WoRelease woRelease;
     private IcItemLoc icItemLoc;
     private IcItemLocBox icItemLocBox;
     private int whPickBatchWoNbr;
     private BigDecimal woPickQtyRqst;
     private BigDecimal woPickQtyAct;
     private Integer whPickDtlWoRqstNbrSrc;
     private String pickScanCd;
     private Integer boxCnt;
     private String boxCdDest;

    public WhPickDtlWoRqst() {
    }

	
    public WhPickDtlWoRqst(int whPickDtlWoRqstNbr, WoDtl woDtl, WoRelease woRelease, int whPickBatchWoNbr, BigDecimal woPickQtyRqst) {
        this.whPickDtlWoRqstNbr = whPickDtlWoRqstNbr;
        this.woDtl = woDtl;
        this.woRelease = woRelease;
        this.whPickBatchWoNbr = whPickBatchWoNbr;
        this.woPickQtyRqst = woPickQtyRqst;
    }
    public WhPickDtlWoRqst(int whPickDtlWoRqstNbr, ApsAllocOnhandWo apsAllocOnhandWo, WoDtl woDtl, WoRelease woRelease, IcItemLoc icItemLoc, IcItemLocBox icItemLocBox, int whPickBatchWoNbr, BigDecimal woPickQtyRqst, BigDecimal woPickQtyAct, Integer whPickDtlWoRqstNbrSrc, String pickScanCd, Integer boxCnt, String boxCdDest) {
       this.whPickDtlWoRqstNbr = whPickDtlWoRqstNbr;
       this.apsAllocOnhandWo = apsAllocOnhandWo;
       this.woDtl = woDtl;
       this.woRelease = woRelease;
       this.icItemLoc = icItemLoc;
       this.icItemLocBox = icItemLocBox;
       this.whPickBatchWoNbr = whPickBatchWoNbr;
       this.woPickQtyRqst = woPickQtyRqst;
       this.woPickQtyAct = woPickQtyAct;
       this.whPickDtlWoRqstNbrSrc = whPickDtlWoRqstNbrSrc;
       this.pickScanCd = pickScanCd;
       this.boxCnt = boxCnt;
       this.boxCdDest = boxCdDest;
    }
   
     @Id 

    
    @Column(name="WH_PICK_DTL_WO_RQST_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getWhPickDtlWoRqstNbr() {
        return this.whPickDtlWoRqstNbr;
    }
    
    public void setWhPickDtlWoRqstNbr(int whPickDtlWoRqstNbr) {
        this.whPickDtlWoRqstNbr = whPickDtlWoRqstNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APS_ALLOC_ONHAND_WO_NBR")
    public ApsAllocOnhandWo getApsAllocOnhandWo() {
        return this.apsAllocOnhandWo;
    }
    
    public void setApsAllocOnhandWo(ApsAllocOnhandWo apsAllocOnhandWo) {
        this.apsAllocOnhandWo = apsAllocOnhandWo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WO_DTL_NBR", nullable=false)
    public WoDtl getWoDtl() {
        return this.woDtl;
    }
    
    public void setWoDtl(WoDtl woDtl) {
        this.woDtl = woDtl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WO_RELEASE_NBR", nullable=false)
    public WoRelease getWoRelease() {
        return this.woRelease;
    }
    
    public void setWoRelease(WoRelease woRelease) {
        this.woRelease = woRelease;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IC_ITEM_LOC_NBR")
    public IcItemLoc getIcItemLoc() {
        return this.icItemLoc;
    }
    
    public void setIcItemLoc(IcItemLoc icItemLoc) {
        this.icItemLoc = icItemLoc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BOX_CD")
    public IcItemLocBox getIcItemLocBox() {
        return this.icItemLocBox;
    }
    
    public void setIcItemLocBox(IcItemLocBox icItemLocBox) {
        this.icItemLocBox = icItemLocBox;
    }

    
    @Column(name="WH_PICK_BATCH_WO_NBR", nullable=false, precision=9, scale=0)
    public int getWhPickBatchWoNbr() {
        return this.whPickBatchWoNbr;
    }
    
    public void setWhPickBatchWoNbr(int whPickBatchWoNbr) {
        this.whPickBatchWoNbr = whPickBatchWoNbr;
    }

    
    @Column(name="WO_PICK_QTY_RQST", nullable=false, precision=13, scale=5)
    public BigDecimal getWoPickQtyRqst() {
        return this.woPickQtyRqst;
    }
    
    public void setWoPickQtyRqst(BigDecimal woPickQtyRqst) {
        this.woPickQtyRqst = woPickQtyRqst;
    }

    
    @Column(name="WO_PICK_QTY_ACT", precision=13, scale=5)
    public BigDecimal getWoPickQtyAct() {
        return this.woPickQtyAct;
    }
    
    public void setWoPickQtyAct(BigDecimal woPickQtyAct) {
        this.woPickQtyAct = woPickQtyAct;
    }

    
    @Column(name="WH_PICK_DTL_WO_RQST_NBR_SRC", precision=9, scale=0)
    public Integer getWhPickDtlWoRqstNbrSrc() {
        return this.whPickDtlWoRqstNbrSrc;
    }
    
    public void setWhPickDtlWoRqstNbrSrc(Integer whPickDtlWoRqstNbrSrc) {
        this.whPickDtlWoRqstNbrSrc = whPickDtlWoRqstNbrSrc;
    }

    
    @Column(name="PICK_SCAN_CD", length=20)
    public String getPickScanCd() {
        return this.pickScanCd;
    }
    
    public void setPickScanCd(String pickScanCd) {
        this.pickScanCd = pickScanCd;
    }

    
    @Column(name="BOX_CNT", precision=5, scale=0)
    public Integer getBoxCnt() {
        return this.boxCnt;
    }
    
    public void setBoxCnt(Integer boxCnt) {
        this.boxCnt = boxCnt;
    }

    
    @Column(name="BOX_CD_DEST", length=20)
    public String getBoxCdDest() {
        return this.boxCdDest;
    }
    
    public void setBoxCdDest(String boxCdDest) {
        this.boxCdDest = boxCdDest;
    }




}


