package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WhPickDtlRqstVw generated by hbm2java
 */
@Entity
@Table(name="WH_PICK_DTL_RQST_VW"
)
public class WhPickDtlRqstVw  implements java.io.Serializable {


     private WhPickDtlRqstVwId id;

    public WhPickDtlRqstVw() {
    }

    public WhPickDtlRqstVw(WhPickDtlRqstVwId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="rqstTypeId", column=@Column(name="RQST_TYPE_ID", length=3) ), 
        @AttributeOverride(name="whPickDtlRqstNbr", column=@Column(name="WH_PICK_DTL_RQST_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="boxCd", column=@Column(name="BOX_CD", length=20) ), 
        @AttributeOverride(name="woReleaseNbr", column=@Column(name="WO_RELEASE_NBR", precision=22, scale=0) ), 
        @AttributeOverride(name="woDtlNbr", column=@Column(name="WO_DTL_NBR", precision=22, scale=0) ), 
        @AttributeOverride(name="oeOrdDtlNbr", column=@Column(name="OE_ORD_DTL_NBR", precision=22, scale=0) ), 
        @AttributeOverride(name="whFacilityTransOnhandNbr", column=@Column(name="WH_FACILITY_TRANS_ONHAND_NBR", precision=22, scale=0) ), 
        @AttributeOverride(name="pickQtyRqst", column=@Column(name="PICK_QTY_RQST", precision=13, scale=5) ), 
        @AttributeOverride(name="pickQtyAct", column=@Column(name="PICK_QTY_ACT", precision=13, scale=5) ), 
        @AttributeOverride(name="apsAllocOnhandNbr", column=@Column(name="APS_ALLOC_ONHAND_NBR", precision=22, scale=0) ), 
        @AttributeOverride(name="icItemLocNbr", column=@Column(name="IC_ITEM_LOC_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="woHdrNbr", column=@Column(name="WO_HDR_NBR", precision=22, scale=0) ), 
        @AttributeOverride(name="ordCd", column=@Column(name="ORD_CD", length=20) ), 
        @AttributeOverride(name="lineNbr", column=@Column(name="LINE_NBR", precision=22, scale=0) ), 
        @AttributeOverride(name="orgNmCust", column=@Column(name="ORG_NM_CUST", length=60) ), 
        @AttributeOverride(name="itemNbrRqst", column=@Column(name="ITEM_NBR_RQST", precision=9, scale=0) ), 
        @AttributeOverride(name="itemCd", column=@Column(name="ITEM_CD", length=50) ), 
        @AttributeOverride(name="lotNbr", column=@Column(name="LOT_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="apsSplySubPoolNbr", column=@Column(name="APS_SPLY_SUB_POOL_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="binNbr", column=@Column(name="BIN_NBR", precision=9, scale=0) ), 
        @AttributeOverride(name="binCd", column=@Column(name="BIN_CD", length=16) ), 
        @AttributeOverride(name="facility", column=@Column(name="FACILITY", length=16) ), 
        @AttributeOverride(name="facilitySrc", column=@Column(name="FACILITY_SRC", length=16) ), 
        @AttributeOverride(name="facilityDest", column=@Column(name="FACILITY_DEST", length=16) ), 
        @AttributeOverride(name="pickScanCd", column=@Column(name="PICK_SCAN_CD", length=20) ), 
        @AttributeOverride(name="boxCnt", column=@Column(name="BOX_CNT", precision=5, scale=0) ), 
        @AttributeOverride(name="whPickDtlRqstNbrSrc", column=@Column(name="WH_PICK_DTL_RQST_NBR_SRC", precision=9, scale=0) ), 
        @AttributeOverride(name="boxStatId", column=@Column(name="BOX_STAT_ID", length=3) ), 
        @AttributeOverride(name="boxQty", column=@Column(name="BOX_QTY", precision=12, scale=5) ), 
        @AttributeOverride(name="hotFlg", column=@Column(name="HOT_FLG", length=1) ), 
        @AttributeOverride(name="componentQtyPerUnit", column=@Column(name="COMPONENT_QTY_PER_UNIT", precision=22, scale=0) ), 
        @AttributeOverride(name="upcCd", column=@Column(name="UPC_CD", length=20) ), 
        @AttributeOverride(name="ean", column=@Column(name="EAN", length=50) ), 
        @AttributeOverride(name="splitAtBinFlg", column=@Column(name="SPLIT_AT_BIN_FLG", length=1) ), 
        @AttributeOverride(name="mfrLotCd", column=@Column(name="MFR_LOT_CD", length=20) ), 
        @AttributeOverride(name="itemDescr", column=@Column(name="ITEM_DESCR", length=50) ), 
        @AttributeOverride(name="whPickBatchNbr", column=@Column(name="WH_PICK_BATCH_NBR", precision=9, scale=0) ) } )
    public WhPickDtlRqstVwId getId() {
        return this.id;
    }
    
    public void setId(WhPickDtlRqstVwId id) {
        this.id = id;
    }




}


