package com.pacificdataservices.diamond.models;
// Generated Feb 10, 2019 3:34:51 PM by Hibernate Tools 5.4.1.Final


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WoDtl generated by hbm2java
 */
@Entity
@Table(name="WO_DTL"
)
public class WoDtl  implements java.io.Serializable {


     private int woDtlNbr;
     private WoHdr woHdr;
     private PoMfrMast poMfrMast;
     private IcUm icUm;
     private IcItemMast icItemMast;
     private int utUserNbr;
     private Date lastModDt;
     private BigDecimal componentQtyPerUnit;
     private String revLvl;
     private BigDecimal qtyAlloc;
     private BigDecimal qtyAllocStkUm;
     private String mixMfrLotFlg;
     private String mandatoryItemFlg;
     private String printBagLblFlg;
  //   private Set<ApsAllocWoWo> apsAllocWoWos = new HashSet<ApsAllocWoWo>(0);
     private Set<WhPickDtlWoRqst> whPickDtlWoRqsts = new HashSet<WhPickDtlWoRqst>(0);
     private Set<IcCertCd> icCertCds = new HashSet<IcCertCd>(0);

    public WoDtl() {
    }

	
    
     @Id 

    
    @Column(name="WO_DTL_NBR", unique=true, nullable=false, precision=9, scale=0)
    public int getWoDtlNbr() {
        return this.woDtlNbr;
    }
    
    public void setWoDtlNbr(int woDtlNbr) {
        this.woDtlNbr = woDtlNbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WO_HDR_NBR", nullable=false)
    public WoHdr getWoHdr() {
        return this.woHdr;
    }
    
    public void setWoHdr(WoHdr woHdr) {
        this.woHdr = woHdr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORG_NBR_MFR_RQST")
    public PoMfrMast getPoMfrMast() {
        return this.poMfrMast;
    }
    
    public void setPoMfrMast(PoMfrMast poMfrMast) {
        this.poMfrMast = poMfrMast;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COMPONENT_UM", nullable=false)
    public IcUm getIcUm() {
        return this.icUm;
    }
    
    public void setIcUm(IcUm icUm) {
        this.icUm = icUm;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_NBR_COMPONENT", nullable=false)
    public IcItemMast getIcItemMast() {
        return this.icItemMast;
    }
    
    public void setIcItemMast(IcItemMast icItemMast) {
        this.icItemMast = icItemMast;
    }

    
    @Column(name="UT_USER_NBR", nullable=false, precision=9, scale=0)
    public int getUtUserNbr() {
        return this.utUserNbr;
    }
    
    public void setUtUserNbr(int utUserNbr) {
        this.utUserNbr = utUserNbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DT", nullable=false, length=7)
    public Date getLastModDt() {
        return this.lastModDt;
    }
    
    public void setLastModDt(Date lastModDt) {
        this.lastModDt = lastModDt;
    }

    
    @Column(name="COMPONENT_QTY_PER_UNIT", nullable=false, precision=13, scale=5)
    public BigDecimal getComponentQtyPerUnit() {
        return this.componentQtyPerUnit;
    }
    
    public void setComponentQtyPerUnit(BigDecimal componentQtyPerUnit) {
        this.componentQtyPerUnit = componentQtyPerUnit;
    }

    
    @Column(name="REV_LVL", length=5)
    public String getRevLvl() {
        return this.revLvl;
    }
    
    public void setRevLvl(String revLvl) {
        this.revLvl = revLvl;
    }

    
    @Column(name="QTY_ALLOC", precision=13, scale=5)
    public BigDecimal getQtyAlloc() {
        return this.qtyAlloc;
    }
    
    public void setQtyAlloc(BigDecimal qtyAlloc) {
        this.qtyAlloc = qtyAlloc;
    }

    
    @Column(name="QTY_ALLOC_STK_UM", precision=13, scale=5)
    public BigDecimal getQtyAllocStkUm() {
        return this.qtyAllocStkUm;
    }
    
    public void setQtyAllocStkUm(BigDecimal qtyAllocStkUm) {
        this.qtyAllocStkUm = qtyAllocStkUm;
    }

    
    @Column(name="MIX_MFR_LOT_FLG", nullable=false, length=1)
    public String getMixMfrLotFlg() {
        return this.mixMfrLotFlg;
    }
    
    public void setMixMfrLotFlg(String mixMfrLotFlg) {
        this.mixMfrLotFlg = mixMfrLotFlg;
    }

    
    @Column(name="MANDATORY_ITEM_FLG", nullable=false, length=1)
    public String getMandatoryItemFlg() {
        return this.mandatoryItemFlg;
    }
    
    public void setMandatoryItemFlg(String mandatoryItemFlg) {
        this.mandatoryItemFlg = mandatoryItemFlg;
    }

    
    @Column(name="PRINT_BAG_LBL_FLG", nullable=false, length=1)
    public String getPrintBagLblFlg() {
        return this.printBagLblFlg;
    }
    
    public void setPrintBagLblFlg(String printBagLblFlg) {
        this.printBagLblFlg = printBagLblFlg;
    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="woDtl")
//    public Set<ApsAllocWoWo> getApsAllocWoWos() {
//        return this.apsAllocWoWos;
//    }
//    
//    public void setApsAllocWoWos(Set<ApsAllocWoWo> apsAllocWoWos) {
//        this.apsAllocWoWos = apsAllocWoWos;
//    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="woDtl")
    public Set<WhPickDtlWoRqst> getWhPickDtlWoRqsts() {
        return this.whPickDtlWoRqsts;
    }
    
    public void setWhPickDtlWoRqsts(Set<WhPickDtlWoRqst> whPickDtlWoRqsts) {
        this.whPickDtlWoRqsts = whPickDtlWoRqsts;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="WO_DTL_CERT",  joinColumns = { 
        @JoinColumn(name="WO_DTL_NBR", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="CERT_CD", nullable=false, updatable=false) })
    public Set<IcCertCd> getIcCertCds() {
        return this.icCertCds;
    }
    
    public void setIcCertCds(Set<IcCertCd> icCertCds) {
        this.icCertCds = icCertCds;
    }




}


