package com.dbexperts.oracle.dto;



/**
 * Contains a temporal representation of the data persisted in a tuple of
 * v$session Persistence management is supported in class OracleSessionBase.
 * This code was generated by com.javautil.JavaGen on Sat Jul 12 21:20:46 CDT
 * 2003
 */
public class OracleSessionBase {

	// class attributes
	/** the container for the data persisted in SADDR */
	private byte[]				saddr	= null;

	/** the container for the data persisted in SID */
	private int					sid;

	/** the container for the data persisted in SERIAL# */
	private int					serialNbr;

	/** the container for the data persisted in AUDSID */
	private int				audsid;

	/** the container for the data persisted in PADDR */
	private byte[]				paddr;

	/** the container for the data persisted in USER# */
	private int				userNbr;

	/** the container for the data persisted in USERNAME */
	private String				username;

	/** the container for the data persisted in COMMAND */
	private int				command;

	/** the container for the data persisted in OWNERID */
	private int				ownerid;

	/** the container for the data persisted in TADDR */
	private String				taddr;

	/** the container for the data persisted in LOCKWAIT */
	private String				lockwait;

	/** the container for the data persisted in STATUS */
	private String				status;

	/** the container for the data persisted in SERVER */
	private String				server;

	/** the container for the data persisted in SCHEMA# */
	private int				schemaNbr;

	/** the container for the data persisted in SCHEMANAME */
	private String				schemaname;

	/** the container for the data persisted in OSUSER */
	private String				osuser;

	/** the container for the data persisted in PROCESS */
	private String				process;

	/** the container for the data persisted in MACHINE */
	private String				machine;

	/** the container for the data persisted in TERMINAL */
	private String				terminal;

	/** the container for the data persisted in PROGRAM */
	private String				program;

	/** the container for the data persisted in TYPE */
	private String				type;

	/** the container for the data persisted in SQL_ADDRESS */
	private byte[]				sqlAddress;

	/** the container for the data persisted in SQL_HASH_VALUE */
	private int				sqlHashValue;

	/** the container for the data persisted in PREV_SQL_ADDR */
	private byte[]				prevSqlAddr;

	/** the container for the data persisted in PREV_HASH_VALUE */
	private int				prevHashValue;

	/** the container for the data persisted in MODULE */
	private String				module;

	/** the container for the data persisted in MODULE_HASH */
	private int				moduleHash;

	/** the container for the data persisted in ACTION */
	private String				action;

	/** the container for the data persisted in ACTION_HASH */
	private int				actionHash;

	/** the container for the data persisted in CLIENT_INFO */
	private String				clientInfo;

	/** the container for the data persisted in FIXED_TABLE_SEQUENCE */
	private int				fixedTableSequence;

	/** the container for the data persisted in ROW_WAIT_OBJ# */
	private int				rowWaitObjNbr;

	/** the container for the data persisted in ROW_WAIT_FILE# */
	private int				rowWaitFileNbr;

	/** the container for the data persisted in ROW_WAIT_BLOCK# */
	private int				rowWaitBlockNbr;

	/** the container for the data persisted in ROW_WAIT_ROW# */
	private int				rowWaitRowNbr;

	/** the container for the data persisted in LOGON_TIME */
	private java.sql.Timestamp	logonTime;

	/** the container for the data persisted in LAST_CALL_ET */
	private int				lastCallEt;

	/** the container for the data persisted in PDML_ENABLED */
	private String				pdmlEnabled;

	/** the container for the data persisted in FAILOVER_TYPE */
	private String				failoverType;

	/** the container for the data persisted in FAILOVER_METHOD */
	private String				failoverMethod;

	/** the container for the data persisted in FAILED_OVER */
	private String				failedOver;

	/** the container for the data persisted in RESOURCE_CONSUMER_GROUP */
	private String				resourceConsumerGroup;

	/** the container for the data persisted in PDML_STATUS */
	private String				pdmlStatus;

	/** the container for the data persisted in PDDL_STATUS */
	private String				pddlStatus;

	/** the container for the data persisted in PQ_STATUS */
	private String				pqStatus;

	/** the container for the data persisted in CURRENT_QUEUE_DURATION */
	private int				currentQueueDuration;

	/** the container for the data persisted in CLIENT_IDENTIFIER */
	private String				clientIdentifier;

	public String getAction() {
		return action;
	}

	public int getActionHash() {
		return actionHash;
	}

	public int getAudsid() {
		return audsid;
	}

	public String getClientIdentifier() {
		return clientIdentifier;
	}

	public String getClientInfo() {
		return clientInfo;
	}

	public int getCommand() {
		return command;
	}

	public int getCurrentQueueDuration() {
		return currentQueueDuration;
	}

	public String getFailedOver() {
		return failedOver;
	}

	public String getFailoverMethod() {
		return failoverMethod;
	}

	public String getFailoverType() {
		return failoverType;
	}

	public int getFixedTableSequence() {
		return fixedTableSequence;
	}

	public int getLastCallEt() {
		return lastCallEt;
	}

	public String getLockwait() {
		return lockwait;
	}

	public java.sql.Timestamp getLogonTime() {
		return logonTime;
	}

	public String getMachine() {
		return machine;
	}

	public String getModule() {
		return module;
	}

	public int getModuleHash() {
		return moduleHash;
	}

	public String getOsuser() {
		return osuser;
	}

	public int getOwnerid() {
		return ownerid;
	}

	public byte[] getPaddr() {
		return paddr;
	}

	public String getPddlStatus() {
		return pddlStatus;
	}

	public String getPdmlEnabled() {
		return pdmlEnabled;
	}

	public String getPdmlStatus() {
		return pdmlStatus;
	}

	public String getPqStatus() {
		return pqStatus;
	}

	public int getPrevHashValue() {
		return prevHashValue;
	}

	public byte[] getPrevSqlAddr() {
		return prevSqlAddr;
	}

	public String getProcess() {
		return process;
	}

	public String getProgram() {
		return program;
	}

	public String getResourceConsumerGroup() {
		return resourceConsumerGroup;
	}

	public int getRowWaitBlockNbr() {
		return rowWaitBlockNbr;
	}

	public int getRowWaitFileNbr() {
		return rowWaitFileNbr;
	}

	public int getRowWaitObjNbr() {
		return rowWaitObjNbr;
	}

	public int getRowWaitRowNbr() {
		return rowWaitRowNbr;
	}

	public byte[] getSaddr() {
		return saddr;
	}

	public String getSchemaname() {
		return schemaname;
	}

	public int getSchemaNbr() {
		return schemaNbr;
	}

	public int getSerialNbr() {
		return serialNbr;
	}

	public String getServer() {
		return server;
	}

	public int getSid() {
		return sid;
	}

	public byte[] getSqlAddress() {
		return sqlAddress;
	}

	public int getSqlHashValue() {
		return sqlHashValue;
	}

	public String getStatus() {
		return status;
	}

	public String getTaddr() {
		return taddr;
	}

	public String getTerminal() {
		return terminal;
	}

	public String getType() {
		return type;
	}

	public String getUsername() {
		return username;
	}

	public int getUserNbr() {
		return userNbr;
	}

    public void setAction(final String val) {
        action=val;
    }

    public void setActionHash(final int val) {
        actionHash=val;
    }

    public void setAudsid(final int val) {
        audsid=val;
    }

    public void setClientIdentifier(final String val) {
        clientIdentifier=val;
    }

    public void setClientInfo(final String val) {
        clientInfo=val;
    }

    public void setCommand(final int val) {
        command=val;
    }

    public void setCurrentQueueDuration(final int val) {
        currentQueueDuration=val;
    }

    public void setFailedOver(final String val) {
        failedOver=val;
    }

    public void setFailoverMethod(final String val) {
        failoverMethod=val;
    }

    public void setFailoverType(final String val) {
        failoverType=val;
    }

    public void setFixedTableSequence(final int val) {
        fixedTableSequence=val;
    }

    public void setLastCallEt(final int val) {
        lastCallEt=val;
    }

    public void setLockwait(final String val) {
        lockwait=val;
    }

    public void setLogonTime(final java.sql.Timestamp val) {
        logonTime=val;
    }

    public void setMachine(final String val) {
        machine=val;
    }

    public void setModule(final String val) {
        module=val;
    }

    public void setModuleHash(final int val) {
        moduleHash=val;
    }



    public void setOsuser(final String val) {
        osuser=val;
    }

    public void setOwnerid(final int val) {
        ownerid=val;
    }

    public void setPaddr(final byte [] val) {
        paddr=val;
    }

    public void setPddlStatus(final String val) {
        pddlStatus=val;
    }

    public void setPdmlEnabled(final String val) {
        pdmlEnabled=val;
    }

    public void setPdmlStatus(final String val) {
        pdmlStatus=val;
    }

    public void setPqStatus(final String val) {
        pqStatus=val;
    }

    public void setPrevHashValue(final int val) {
        prevHashValue=val;
    }

    public void setPrevSqlAddr(final byte [] val) {
        prevSqlAddr=val;
    }

    public void setProcess(final String val) {
        process=val;
    }

    public void setProgram(final String val) {
        program=val;
    }

    public void setResourceConsumerGroup(final String val) {
        resourceConsumerGroup=val;
    }

    public void setRowWaitBlockNbr(final int val) {
        rowWaitBlockNbr=val;
    }

    public void setRowWaitFileNbr(final int val) {
        rowWaitFileNbr=val;
    }

    public void setRowWaitObjNbr(final int val) {
        rowWaitObjNbr=val;
    }

    public void setRowWaitRowNbr(final int val) {
        rowWaitRowNbr=val;
    }

    public void setSaddr(final byte [] val) {
        saddr=val;
    }

    public void setSchemaname(final String val) {
        schemaname=val;
    }

    public void setSchemaNbr(final int val) {
        schemaNbr=val;
    }

    public void setSerialNbr(final int val) {
        serialNbr=val;
    }

    public void setServer(final String val) {
        server=val;
    }

    public void setSid(final int val) {
        sid=val;
    }

    public void setSqlAddress(final byte [] val) {
        sqlAddress=val;
    }

    public void setSqlHashValue(final int val) {
        sqlHashValue=val;
    }

    public void setStatus(final String val) {
        status=val;
    }

    public void setTaddr(final String val) {
        taddr=val;
    }

    public void setTerminal(final String val) {
        terminal=val;
    }

    public void setType(final String val) {
        type=val;
    }

      public void setUsername(final String val) {
        username=val;
    }

      public void setUserNbr(final int val) {
        userNbr=val;
    }
}
