--------------------------------------------------------
--  DDL for Table AIL_BACK
--------------------------------------------------------

  CREATE TABLE "AIL_BACK" 
   (	"ITEM_NBR" NUMBER(9,0), 
	"APS_LOG_FILE_NAME" VARCHAR2(255), 
	"LAST_PLAN_DT" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 655360 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
