--------------------------------------------------------
--  DDL for Table APS_ITEM_LOG
--------------------------------------------------------

  CREATE TABLE "APS_ITEM_LOG" 
   (	"ITEM_NBR" NUMBER(9,0), 
	"APS_LOG_FILE_NAME" VARCHAR2(255), 
	"LAST_PLAN_DT" TIMESTAMP (6), 
	 CONSTRAINT "APS_ITEM_LOG_PK" PRIMARY KEY ("ITEM_NBR") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" 
 PCTTHRESHOLD 50;
