--------------------------------------------------------
--  DDL for Table APS_SRC_RULE
--------------------------------------------------------

  CREATE TABLE "APS_SRC_RULE" 
   (	"APS_SRC_RULE_NBR" NUMBER(9,0), 
	"APS_SRC_RULE_SET_NBR" NUMBER(9,0), 
	"APS_SPLY_SUB_POOL_NBR" NUMBER(9,0), 
	"FACILITY" VARCHAR2(16), 
	"SPLY_TYPE_ID" VARCHAR2(1), 
	"SRC_PRTY" NUMBER(3,0), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
