--------------------------------------------------------
--  DDL for Table APS_ITEM_REPLEN_POLICY
--------------------------------------------------------

  CREATE TABLE "APS_ITEM_REPLEN_POLICY" 
   (	"ITEM_NBR" NUMBER(9,0), 
	"FACILITY" VARCHAR2(16), 
	"REPLEN_QTY_MIN_UNIT" NUMBER(8,0), 
	"REPLEN_QTY_MAX_UNIT" NUMBER(8,0), 
	"REPLEN_QTY_MIN_PRD" NUMBER(4,1), 
	"REPLEN_QTY_MAX_PRD" NUMBER(4,1), 
	"REPLEN_QTY_INCR_UNIT" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 720896 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
