--------------------------------------------------------
--  DDL for Table AR_INV_HDR
--------------------------------------------------------

  CREATE TABLE "AR_INV_HDR" 
   (	"INV_CD" VARCHAR2(20), 
	"INV_DT" DATE, 
	"INV_STAT_ID" VARCHAR2(1), 
	"ORG_NBR_CUST" NUMBER(9,0), 
	"ORG_NM_CUST" VARCHAR2(60), 
	"OE_ORD_HDR_NBR" NUMBER(9,0), 
	"ORD_CD" VARCHAR2(20), 
	"CUST_PO_CD" VARCHAR2(30), 
	"CURR_CD" VARCHAR2(3), 
	"SHIP_DT" DATE, 
	"BILL_TO_ADDR_NBR" NUMBER(9,0), 
	"BILL_TO_ADDR_CD" VARCHAR2(8), 
	"BILL_TO_ADDR_DESCR" VARCHAR2(60), 
	"BILL_TO_ADDR_1" VARCHAR2(30), 
	"BILL_TO_ADDR_2" VARCHAR2(30), 
	"BILL_TO_ADDR_3" VARCHAR2(30), 
	"BILL_TO_CITY" VARCHAR2(25), 
	"BILL_TO_STATE_CD" VARCHAR2(5), 
	"BILL_TO_POSTAL_CD" VARCHAR2(10), 
	"BILL_TO_CNTRY_CD" VARCHAR2(3), 
	"SHIP_TO_ADDR_NBR" NUMBER(9,0), 
	"SHIP_TO_ADDR_CD" VARCHAR2(8), 
	"SHIP_TO_ADDR_DESCR" VARCHAR2(60), 
	"SHIP_TO_ADDR_1" VARCHAR2(30), 
	"SHIP_TO_ADDR_2" VARCHAR2(30), 
	"SHIP_TO_ADDR_3" VARCHAR2(30), 
	"SHIP_TO_CITY" VARCHAR2(25), 
	"SHIP_TO_STATE_CD" VARCHAR2(5), 
	"SHIP_TO_POSTAL_CD" VARCHAR2(10), 
	"SHIP_TO_CNTRY_CD" VARCHAR2(3), 
	"SHIP_VIA_CD" VARCHAR2(8), 
	"TERM_CD" VARCHAR2(10), 
	"GROSS_INV_VALUE" NUMBER(17,5), 
	"WGHT" NUMBER(10,3), 
	"CTN_CNT" NUMBER(7,0), 
	"FRGT_CHARGE" NUMBER(11,2), 
	"NET_INV_VALUE" NUMBER(17,5), 
	"WAYBILL_CD" VARCHAR2(20), 
	"TRD_FLG" VARCHAR2(1), 
	"AR_INV_BATCH_NBR" NUMBER(9,0), 
	"FOB_CD" VARCHAR2(8), 
	"ORG_CD_CUST" VARCHAR2(15), 
	"SALES_TERR_CD" VARCHAR2(8), 
	"SELL_INDIV_NBR" NUMBER(9,0), 
	"AR_SUMMARY_INV_NBR" NUMBER(9,0), 
	"GL_TAX_GRP_NBR" NUMBER(9,0), 
	"PRINT_FLG" VARCHAR2(1) DEFAULT 'N', 
	"INV_PRINT_DT_ORIG" DATE, 
	"INV_PRINT_DT_LAST" DATE, 
	"UT_USER_NBR_PRINT" NUMBER(9,0), 
	"ORD_TYPE_CD" VARCHAR2(8), 
	"SUMMARY_INV_REF" VARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;

   COMMENT ON COLUMN "AR_INV_HDR"."INV_CD" IS 'This is the Unique Invoice Number assigned to each Invoice. System Generated using a Function GET_INV_CD.
Specifics of the format of he';
   COMMENT ON COLUMN "AR_INV_HDR"."INV_DT" IS 'The Date the Invoice was created.
This is not the date the inventory was shipped.
If the inventory is shipped on the last day of the month and invoice posting doesn''t occur until the following month, then the revenue
is not recognized.';
   COMMENT ON COLUMN "AR_INV_HDR"."INV_STAT_ID" IS 'The Status of the Invoice. This can be one of N-New,';
   COMMENT ON COLUMN "AR_INV_HDR"."ORG_NBR_CUST" IS 'The foreign key to the customer organization master surrogate primary key.';
   COMMENT ON COLUMN "AR_INV_HDR"."ORG_NM_CUST" IS 'The name of the organization from the order header.
In order entry this defaults to the name of the organization from the org master';
   COMMENT ON COLUMN "AR_INV_HDR"."OE_ORD_HDR_NBR" IS 'A foreign key to the surrogate primary key of the customer order header.';
   COMMENT ON COLUMN "AR_INV_HDR"."ORD_CD" IS 'The order code generated by order entry for the order.';
   COMMENT ON COLUMN "AR_INV_HDR"."CUST_PO_CD" IS 'The purchase order number assigned by the customer.
This purchase order number may appear on multiple customer orders.';
   COMMENT ON COLUMN "AR_INV_HDR"."CURR_CD" IS 'The currency code in which the order was placed.
Tony wants to restrict each customer to only one currency code.';
   COMMENT ON COLUMN "AR_INV_HDR"."SHIP_DT" IS 'The date the inventory was shipped.';
   COMMENT ON COLUMN "AR_INV_HDR"."BILL_TO_ADDR_NBR" IS 'A foreign key to the surrogate primary key for the address for the customer.';
   COMMENT ON COLUMN "AR_INV_HDR"."BILL_TO_ADDR_CD" IS 'The code assigned to the billing address at the time the invoice was created.
Will not reflect changes made to the address code after invoice creation.';
   COMMENT ON COLUMN "AR_INV_HDR"."BILL_TO_ADDR_DESCR" IS 'The description of the bill to address copied from the address of record for the order.';
   COMMENT ON COLUMN "AR_INV_HDR"."SHIP_VIA_CD" IS 'The ship via code used at the time the shipment was made.';
   COMMENT ON COLUMN "AR_INV_HDR"."TERM_CD" IS 'The payment terms, copied from the order at the time the invoice was created.
May be changed in invoice review prior to posting.';
   COMMENT ON COLUMN "AR_INV_HDR"."WAYBILL_CD" IS 'The waybill code assigned by the carrier at the time the invoice was created.';
   COMMENT ON COLUMN "AR_INV_HDR"."TRD_FLG" IS '''Y'' this is a trade.
This may only be made ''Y'' if the customer is a trading partner.May be changed during "invoice review"';
   COMMENT ON TABLE "AR_INV_HDR"  IS 'In invoice review the bill to address, ship to address, terms code and trading flag may be changed on the invoice header.
The following G/L transactions should be effected.Credit Receiving Expense';
