--------------------------------------------------------
--  DDL for Table CAL_HOLIDAY
--------------------------------------------------------

  CREATE TABLE "CAL_HOLIDAY" 
   (	"CAL_HOLIDAY_NBR" NUMBER(9,0), 
	"CALENDAR" VARCHAR2(6), 
	"MONTH" NUMBER(2,0), 
	"DAY_OF_MONTH" NUMBER(2,0), 
	"RECURS" VARCHAR2(2), 
	"ALIGN" VARCHAR2(8), 
	"START_DT" DATE, 
	"END_DT" DATE, 
	"OCCURENCE" VARCHAR2(8), 
	"DAY_OF_WEEK" VARCHAR2(3)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;

   COMMENT ON COLUMN "CAL_HOLIDAY"."ALIGN" IS '''PREVWK'' - Previous Work Day 
''NEXTWK'' - Next Work Day 
''IFWK''        - If a work day 
''CLOSEST'' - Closest work day';
   COMMENT ON COLUMN "CAL_HOLIDAY"."OCCURENCE" IS '''1ST'',''2ND'',''3RD'',''4TH'',''5TH'',''LAST''';
