--------------------------------------------------------
--  DDL for Table FC_ADJ
--------------------------------------------------------

  CREATE TABLE "FC_ADJ" 
   (	"FC_ADJ_NBR" NUMBER(9,0), 
	"FC_ITEM_MAST_NBR" NUMBER(9,0), 
	"ADJ_ID" VARCHAR2(2), 
	"ADJ_AMT" NUMBER(10,2), 
	"ADJ_COMM" VARCHAR2(80), 
	"INDIV_NBR_ADJ" NUMBER(9,0), 
	"ADJ_TM" DATE, 
	"EFFECTIVE_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 7340032 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
