--------------------------------------------------------
--  DDL for Table FC_AGGR_MAST
--------------------------------------------------------

  CREATE TABLE "FC_AGGR_MAST" 
   (	"FC_AGGR_MAST_NBR" NUMBER(9,0), 
	"FC_AGGR_MAST_DESCR" VARCHAR2(30), 
	"FCST_GRP" VARCHAR2(8), 
	"FCST_TYPE_ID" VARCHAR2(1), 
	"FCST_AGGR_TYPE_ID" VARCHAR2(1), 
	"CALENDAR" VARCHAR2(6), 
	"TOT_LEAD_TIME" NUMBER(4,0), 
	"STORE_ALT_FCST_FLG" VARCHAR2(1), 
	"FC_AGGR_MAST_STAT_ID" VARCHAR2(1), 
	"TRC_FILE_NM_ABSOLUTE" VARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 458752 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;

   COMMENT ON COLUMN "FC_AGGR_MAST"."FCST_TYPE_ID" IS 'H - History Aggregated Forecast,
F - Forecast Aggregated Forecast';
   COMMENT ON COLUMN "FC_AGGR_MAST"."FCST_AGGR_TYPE_ID" IS 'Q - Quantity Aggregation,
C - Cost Aggregation, P - Price Aggregation';
