--------------------------------------------------------
--  DDL for Table FC_AGGR_MAST_ATTR
--------------------------------------------------------

  CREATE TABLE "FC_AGGR_MAST_ATTR" 
   (	"FC_AGGR_MAST_NBR" NUMBER(9,0), 
	"IC_ATTR_NBR" NUMBER(9,0), 
	"ATTR_VAL" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
