--------------------------------------------------------
--  DDL for Table FC_FCST_PRD
--------------------------------------------------------

  CREATE TABLE "FC_FCST_PRD" 
   (	"FC_ITEM_MAST_NBR" NUMBER(9,0), 
	"FC_FCST_DT" DATE, 
	"RAW_FCST" NUMBER(17,5), 
	"ADJ_FCST" NUMBER(17,5), 
	"FCST_ALLOC_QTY" NUMBER(17,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 15728640 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
