--------------------------------------------------------
--  DDL for Table FC_FCST_PRD_OLD
--------------------------------------------------------

  CREATE TABLE "FC_FCST_PRD_OLD" 
   (	"FC_ITEM_MAST_NBR" NUMBER(9,0), 
	"PRD_START_DT" DATE, 
	"FRAC_PRD_DMD" NUMBER, 
	"FC_FCST_PRD_NBR" NUMBER(9,0), 
	"WHOLE_PRD_DMD" NUMBER, 
	"WHOLE_PRD_ADJ" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40894464 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
