--------------------------------------------------------
--  DDL for Table FC_FCST_BUCKET
--------------------------------------------------------

  CREATE TABLE "FC_FCST_BUCKET" 
   (	"FC_ITEM_MAST_NBR" NUMBER(9,0), 
	"PRD_START_DT" DATE, 
	"INTVL" NUMBER(2,0), 
	"INTVL_START_DT" DATE, 
	"FC_FCST_DT" DATE, 
	"FRAC_PRD_DMD_RAW" NUMBER, 
	"WHOLE_PRD_DMD_RAW" NUMBER, 
	"WHOLE_PRD_ADJ_RAW" NUMBER, 
	"FRAC_PRD_DMD_ADJ" NUMBER, 
	"WHOLE_PRD_DMD_ADJ" NUMBER, 
	"WHOLE_PRD_ADJ_ADJ" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 10485760 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
