--------------------------------------------------------
--  DDL for Table FC_HIST
--------------------------------------------------------

  CREATE TABLE "FC_HIST" 
   (	"FC_HIST_NBR" NUMBER(9,0), 
	"FC_ITEM_MAST_NBR" NUMBER(9,0), 
	"DMD_ACT" NUMBER(13,2), 
	"DMD_ADJ" NUMBER(13,2), 
	"DMD_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 14680064 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;

   COMMENT ON COLUMN "FC_HIST"."FC_HIST_NBR" IS 'Surrogate primary key for';
   COMMENT ON COLUMN "FC_HIST"."FC_ITEM_MAST_NBR" IS 'Surrogate primary key for FC_ITEM_MAST.';
