--------------------------------------------------------
--  DDL for Table FCST_REPORT_DTL
--------------------------------------------------------

  CREATE TABLE "FCST_REPORT_DTL" 
   (	"SESSION_ID" VARCHAR2(100), 
	"GROUPING_STRING" VARCHAR2(100), 
	"SORT_SEQ" NUMBER(3,0), 
	"DMD_TYPE" VARCHAR2(40), 
	"QTY_MNTH_1" NUMBER, 
	"QTY_MNTH_2" NUMBER, 
	"QTY_MNTH_3" NUMBER, 
	"QTY_MNTH_4" NUMBER, 
	"QTY_MNTH_5" NUMBER, 
	"QTY_MNTH_6" NUMBER, 
	"QTY_MNTH_7" NUMBER, 
	"QTY_MNTH_8" NUMBER, 
	"QTY_MNTH_9" NUMBER, 
	"QTY_MNTH_10" NUMBER, 
	"QTY_MNTH_11" NUMBER, 
	"QTY_MNTH_12" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 17825792 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
