--------------------------------------------------------
--  DDL for Table FIM_ATTR
--------------------------------------------------------

  CREATE TABLE "FIM_ATTR" 
   (	"FC_ITEM_MAST_NBR" NUMBER(9,0), 
	"ITEM_NBR" NUMBER(9,0), 
	"SVC_LVL" NUMBER(5,2), 
	"TOT_LEAD_TIME" NUMBER(4,0), 
	"SAFETY_STK_MIN_PRD" NUMBER(3,1), 
	"SAFETY_STK_MAX_PRD" NUMBER(3,1), 
	"SAFETY_STK_MIN_UNIT" NUMBER(11,3), 
	"SAFETY_STK_MAX_UNIT" NUMBER(11,3), 
	"REPLEN_QTY_MIN_UNIT" NUMBER(8,0), 
	"REPLEN_QTY_MAX_UNIT" NUMBER(8,0), 
	"REPLEN_QTY_MIN_PRD" NUMBER(4,1), 
	"REPLEN_QTY_MAX_PRD" NUMBER(4,1), 
	"STORE_ALT_FCST_FLG" VARCHAR2(1), 
	"ARCH_ALT_FCST_FLG" VARCHAR2(1), 
	"CALENDAR" VARCHAR2(6), 
	"FCST_MDL_GRP" VARCHAR2(8), 
	"STAT_ID" VARCHAR2(1), 
	"APS_SRC_RULE_SET_NBR" NUMBER(9,0), 
	"SAFETY_STK_ADJ" NUMBER(8,0), 
	"FCST_TYPE_ID" VARCHAR2(1), 
	"ORG_NBR_CUST" NUMBER(9,0), 
	"REV_LVL" VARCHAR2(5), 
	"ORG_NBR_MFR_RQST" NUMBER(9,0), 
	"FCST_GRP" VARCHAR2(8), 
	"FC_ITEM_MAST_STAT_ID" VARCHAR2(1), 
	"FC_ITEM_MAST_DESCR" VARCHAR2(30), 
	"SAFETY_STK_ALLOC_QTY" NUMBER(8,0), 
	"FCST_END_DT" DATE, 
	"UNIT_COST_STK_UM" NUMBER(17,5), 
	"SAFETY_STK_CALC" NUMBER(10,2), 
	"SAFETY_STK_CONSTRAIN" NUMBER(10,2), 
	"CUST_REF_CD" VARCHAR2(40), 
	"SAFETY_STK_AVAIL_TO_SELL" VARCHAR2(1), 
	"HARD_ALLOC_FC_WITHIN_LEAD_TM" VARCHAR2(1), 
	"FC_BUILD_RATE_GRP_CD" VARCHAR2(10), 
	"DESCR" VARCHAR2(50), 
	"PROD_LINE" VARCHAR2(20), 
	"STYLE" VARCHAR2(20), 
	"COLOR" VARCHAR2(20), 
	"PROD_SIZE" VARCHAR2(20), 
	"CUST_GRP" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
