--------------------------------------------------------
--  DDL for Table FIM_MSG
--------------------------------------------------------

  CREATE TABLE "FIM_MSG" 
   (	"FIM_MSG_NBR" NUMBER, 
	"FC_ITEM_MAST_NBR" NUMBER(9,0), 
	"MSG_CD" VARCHAR2(20), 
	"MSG" VARCHAR2(2000), 
	"MSG_TIME" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 7340032 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
