--------------------------------------------------------
--  File created - Saturday-January-25-2020   
--------------------------------------------------------
@/common/home/jjs/java-projects/aerodemo/dickies/AIL_BACK_2.sql
@/common/home/jjs/java-projects/aerodemo/dickies/ALLOC_STATS_2.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APP_CTL_2.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APP_CTL2_2.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_NBR_2.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_ONHAND_FC_2.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_ONHAND_OO_2.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_ONHAND_SS_2.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_ONHAND_WO_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_REPLEN_FC_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_REPLEN_OO_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_REPLEN_SS_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_REPLEN_WO_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_WO_FC_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_WO_OO_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_WO_SS_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_WO_WO_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_CTL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_DISPATCH_QUEUE_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_IDEAL_GLOBAL_REPLEN_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ITEM_GLOBAL_SUBST_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ITEM_LOG_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ITEM_REPLEN_POLICY_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_PLAN_GRP_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_RESULT_DTL_DMD_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_RESULT_DTL_SPLY_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_RQST_QUEUE_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_SPLY_POOL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_SPLY_SUB_POOL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_SRC_RULE_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_SRC_RULE_SET_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/AR_INV_DTL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/AR_INV_HDR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/CAL_CALENDAR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/CAL_DT_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/CAL_HOLIDAY_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/CURRENCY_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/DEBUG_TABLE_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FCST_GRP_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FCST_REPORT_DTL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_ADJ_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_AGGR_MAST_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_AGGR_MAST_ATTR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_AGGR_MAST_DTL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_ATTR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_ATTR_VAL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_BUILD_RATE_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_BUILD_RATE_GRP_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_CTL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_DTL_TMP_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_AGGR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_BAK_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_BUCKET_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_MDL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_MDL_GRP_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_MDL_GRP_HDR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_MDL_OLD_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_PRD_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_PRD_OLD_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_XX_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_HDR_TMP_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_HIST_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_HIST_DIST_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_ITEM_ATTR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_ITEM_FCST_MDL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_ITEM_MAST_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_ITEM_MAST_DTL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_ITEM_UNFORECASTABLE_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_QUEUE_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FIM_ATTR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FIM_ATTRS_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FIM_MSG_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ATTR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ATTR_VAL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ATTR_VAL_BAK_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_BIN_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_CATEGORY_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_CERT_CD_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ITEM_ATTR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ITEM_ATTR_BAK_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ITEM_CUST_SUBST_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ITEM_LOC_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ITEM_LOC_BOX_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ITEM_MAST_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ITEM_MAST_CERT_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ITEM_MAST_EQUIV_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ITEM_MAST_EQUIV_REF_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_LOT_MAST_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_LOT_MAST_CERT_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_MULTIPLE_CERT_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_AR_INV_DTL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_CUST_MAST_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_FC_ADJ_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_FC_FCST_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_IC_ITEM_ATTR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_IC_ITEM_LOC_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_IC_ITEM_MAST_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_MFR_MFG_CAP_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_OE_ORD_DTL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_PO_ORD_DTL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_SO_HIST_DTL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/ITEM_TMP2_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/ITEM_TMP3_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/MISSING_ITEMS_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/NA_INDIV_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/NA_ORG_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/NA_ORG_ADDR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/NA_ORG_INDIV_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/OE_CUST_CONTRACT_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/OE_CUST_MAST_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/OE_CUST_MAST_CERT_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/OE_CUST_MFR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/OE_ORD_DTL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/OE_ORD_DTL_CERT_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/OE_ORD_HDR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_LINE_DTL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_LINE_HDR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_LINE_HDR_CERT_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_LINE_MULTIPLE_CERT_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_MFR_MAST_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_ORD_HDR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_REQUISITION_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_REQUISITION_BAK_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_REQUISITION_BAK2_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_RESCHED_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_RESCHED_BAK_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_VND_MAST_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_VND_SET_DTL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_VND_SET_HDR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PROF_PLAN_TABLE_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/SEASON_START_DATES_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/SERVICE_RQST_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/SERVICE_RQST_PARMS_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/SQ_QTE_DTL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/SQ_QTE_HDR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/SS_ADJ_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/SS_TMP_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/TD_TASK_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/TMP_FCST_DTL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/TMP_FC_FCST_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/TMP_FC_FCST_BUCKET_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/TMP_FC_HIST_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/TMP_FIM_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/TMP_IC_ITEM_MAST_ATTR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/TMP_INVENTORY_PIPELINE.sql
@/common/home/jjs/java-projects/aerodemo/dickies/TMP_ITEM.sql
@/common/home/jjs/java-projects/aerodemo/dickies/TMP_SAFETY_STK_ADJ.sql
@/common/home/jjs/java-projects/aerodemo/dickies/TOAD_LICK.sql
@/common/home/jjs/java-projects/aerodemo/dickies/USER_FIELD_CTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/UT_CACHE.sql
@/common/home/jjs/java-projects/aerodemo/dickies/UT_DATA_SRC.sql
@/common/home/jjs/java-projects/aerodemo/dickies/UT_ETL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/UT_ETL_GRP.sql
@/common/home/jjs/java-projects/aerodemo/dickies/UT_ETL_GRP_DTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/UT_FACILITY.sql
@/common/home/jjs/java-projects/aerodemo/dickies/UT_NOTE.sql
@/common/home/jjs/java-projects/aerodemo/dickies/UT_PROCESS_STATUS.sql
@/common/home/jjs/java-projects/aerodemo/dickies/UT_QUERY.sql
@/common/home/jjs/java-projects/aerodemo/dickies/UT_TABLE.sql
@/common/home/jjs/java-projects/aerodemo/dickies/UT_TABLE_ROW_MSG.sql
@/common/home/jjs/java-projects/aerodemo/dickies/UT_TABLE_RULE.sql
@/common/home/jjs/java-projects/aerodemo/dickies/UT_USER.sql
@/common/home/jjs/java-projects/aerodemo/dickies/UT_USER_ROLE.sql
@/common/home/jjs/java-projects/aerodemo/dickies/UT_WEB_SESSION.sql
@/common/home/jjs/java-projects/aerodemo/dickies/VQ_QTE_DTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/VQ_QTE_HDR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/VQ_QTE_MULTIPLE_CERT.sql
@/common/home/jjs/java-projects/aerodemo/dickies/WEB_REPORT.sql
@/common/home/jjs/java-projects/aerodemo/dickies/WH_FACILITY_TRANS_ONHAND.sql
@/common/home/jjs/java-projects/aerodemo/dickies/WH_FACILITY_TRANS_REPLEN.sql
@/common/home/jjs/java-projects/aerodemo/dickies/WH_PICK_DTL_COP_RQST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/WH_PICK_DTL_TRANS_RQST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/WH_PICK_DTL_WO_RQST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/WO_DTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/WO_DTL_CERT.sql
@/common/home/jjs/java-projects/aerodemo/dickies/WO_HDR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/WO_HDR_CERT.sql
@/common/home/jjs/java-projects/aerodemo/dickies/WO_RELEASE.sql
@/common/home/jjs/java-projects/aerodemo/dickies/Y.sql
@/common/home/jjs/java-projects/aerodemo/dickies/Z.sql
