--------------------------------------------------------
--  File created - Saturday-January-25-2020   
--------------------------------------------------------
@/common/home/jjs/java-projects/aerodemo/dickies/AIL_BACK_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/ALLOC_STATS_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APP_CTL_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APP_CTL2_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_NBR_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_ONHAND_FC_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_ONHAND_OO_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_ONHAND_SS_1.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_ONHAND_WO.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_REPLEN_FC.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_REPLEN_OO.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_REPLEN_SS.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_REPLEN_WO.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_WO_FC.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_WO_OO.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_WO_SS.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ALLOC_WO_WO.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_CTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_DISPATCH_QUEUE.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_IDEAL_GLOBAL_REPLEN.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ITEM_GLOBAL_SUBST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ITEM_LOG.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_ITEM_REPLEN_POLICY.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_PLAN_GRP.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_RESULT_DTL_DMD.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_RESULT_DTL_SPLY.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_RQST_QUEUE.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_SPLY_POOL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_SPLY_SUB_POOL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_SRC_RULE.sql
@/common/home/jjs/java-projects/aerodemo/dickies/APS_SRC_RULE_SET.sql
@/common/home/jjs/java-projects/aerodemo/dickies/AR_INV_DTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/AR_INV_HDR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/CAL_CALENDAR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/CAL_DT.sql
@/common/home/jjs/java-projects/aerodemo/dickies/CAL_HOLIDAY.sql
@/common/home/jjs/java-projects/aerodemo/dickies/CURRENCY.sql
@/common/home/jjs/java-projects/aerodemo/dickies/DEBUG_TABLE.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FCST_GRP.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FCST_REPORT_DTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_ADJ.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_AGGR_MAST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_AGGR_MAST_ATTR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_AGGR_MAST_DTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_ATTR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_ATTR_VAL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_BUILD_RATE.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_BUILD_RATE_GRP.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_CTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_DTL_TMP.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_AGGR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_BAK.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_BUCKET.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_MDL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_MDL_GRP.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_MDL_GRP_HDR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_MDL_OLD.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_PRD.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_PRD_OLD.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_FCST_XX.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_HDR_TMP.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_HIST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_HIST_DIST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_ITEM_ATTR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_ITEM_FCST_MDL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_ITEM_MAST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_ITEM_MAST_DTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_ITEM_UNFORECASTABLE.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FC_QUEUE.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FIM_ATTR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FIM_ATTRS.sql
@/common/home/jjs/java-projects/aerodemo/dickies/FIM_MSG.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ATTR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ATTR_VAL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ATTR_VAL_BAK.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_BIN.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_CATEGORY.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_CERT_CD.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ITEM_ATTR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ITEM_ATTR_BAK.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ITEM_CUST_SUBST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ITEM_LOC.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ITEM_LOC_BOX.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ITEM_MAST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ITEM_MAST_CERT.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ITEM_MAST_EQUIV.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_ITEM_MAST_EQUIV_REF.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_LOT_MAST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_LOT_MAST_CERT.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IC_MULTIPLE_CERT.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_AR_INV_DTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_CUST_MAST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_FC_ADJ.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_FC_FCST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_IC_ITEM_ATTR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_IC_ITEM_LOC.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_IC_ITEM_MAST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_MFR_MFG_CAP.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_OE_ORD_DTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_PO_ORD_DTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/IDL_SO_HIST_DTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/ITEM_TMP2.sql
@/common/home/jjs/java-projects/aerodemo/dickies/ITEM_TMP3.sql
@/common/home/jjs/java-projects/aerodemo/dickies/MISSING_ITEMS.sql
@/common/home/jjs/java-projects/aerodemo/dickies/NA_INDIV.sql
@/common/home/jjs/java-projects/aerodemo/dickies/NA_ORG.sql
@/common/home/jjs/java-projects/aerodemo/dickies/NA_ORG_ADDR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/NA_ORG_INDIV.sql
@/common/home/jjs/java-projects/aerodemo/dickies/OE_CUST_CONTRACT.sql
@/common/home/jjs/java-projects/aerodemo/dickies/OE_CUST_MAST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/OE_CUST_MAST_CERT.sql
@/common/home/jjs/java-projects/aerodemo/dickies/OE_CUST_MFR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/OE_ORD_DTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/OE_ORD_DTL_CERT.sql
@/common/home/jjs/java-projects/aerodemo/dickies/OE_ORD_HDR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_LINE_DTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_LINE_HDR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_LINE_HDR_CERT.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_LINE_MULTIPLE_CERT.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_MFR_MAST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_ORD_HDR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_REQUISITION.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_REQUISITION_BAK.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_REQUISITION_BAK2.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_RESCHED.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_RESCHED_BAK.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_VND_MAST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_VND_SET_DTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PO_VND_SET_HDR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/PROF_PLAN_TABLE.sql
@/common/home/jjs/java-projects/aerodemo/dickies/SEASON_START_DATES.sql
@/common/home/jjs/java-projects/aerodemo/dickies/SERVICE_RQST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/SERVICE_RQST_PARMS.sql
@/common/home/jjs/java-projects/aerodemo/dickies/SQ_QTE_DTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/SQ_QTE_HDR.sql
@/common/home/jjs/java-projects/aerodemo/dickies/SS_ADJ.sql
@/common/home/jjs/java-projects/aerodemo/dickies/SS_TMP.sql
@/common/home/jjs/java-projects/aerodemo/dickies/TD_TASK.sql
@/common/home/jjs/java-projects/aerodemo/dickies/TMP_FCST_DTL.sql
@/common/home/jjs/java-projects/aerodemo/dickies/TMP_FC_FCST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/TMP_FC_FCST_BUCKET.sql
@/common/home/jjs/java-projects/aerodemo/dickies/TMP_FC_HIST.sql
@/common/home/jjs/java-projects/aerodemo/dickies/TMP_FIM.sql
@/common/home/jjs/java-projects/aerodemo/dickies/TMP_IC_ITEM_MAST_ATTR.sql
