--------------------------------------------------------
--  DDL for Table IC_CERT_CD
--------------------------------------------------------

  CREATE TABLE "IC_CERT_CD" 
   (	"CERT_CD" VARCHAR2(8), 
	"CERT_CD_DESCR" VARCHAR2(60), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"DOC_FLG" VARCHAR2(1), 
	"CERT_VALUE" NUMBER(3,0), 
	"WEB_FLG" VARCHAR2(1) DEFAULT 'N', 
	"CERT_SRC_ID" VARCHAR2(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
