--------------------------------------------------------
--  DDL for Table IC_ITEM_MAST_EQUIV
--------------------------------------------------------

  CREATE TABLE "IC_ITEM_MAST_EQUIV" 
   (	"ITEM_NBR" NUMBER(9,0), 
	"ITEM_NBR_EQUIV" NUMBER(9,0), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	 CONSTRAINT "SYS_IOT_TOP_54474" PRIMARY KEY ("ITEM_NBR", "ITEM_NBR_EQUIV") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" 
 PCTTHRESHOLD 50;
