--------------------------------------------------------
--  DDL for Table IC_ITEM_MAST
--------------------------------------------------------

  CREATE TABLE "IC_ITEM_MAST" 
   (	"ITEM_CD" VARCHAR2(50), 
	"ITEM_NBR" NUMBER(9,0), 
	"ITEM_DESCR" VARCHAR2(50), 
	"STK_UM" VARCHAR2(3), 
	"SELL_UM" VARCHAR2(3), 
	"STD_COST" NUMBER(17,6), 
	"LIST_PRICE" NUMBER(17,6), 
	"UPC_CD" VARCHAR2(20), 
	"EAN" VARCHAR2(50), 
	"QTY_PER_BOX" NUMBER(7,0), 
	"BOX_PER_CTN" NUMBER(7,0), 
	"SLS_QTY_MIN" NUMBER(7,0), 
	"SLS_QTY_INCR" NUMBER(7,0), 
	"REPLEN_QTY_MIN" NUMBER(7,0), 
	"REPLEN_QTY_INCR" NUMBER(7,0), 
	"IC_CATEGORY_NBR" NUMBER(9,0), 
	"NON_STK_FLG" VARCHAR2(1) DEFAULT 'N', 
	"SER_NBR_REQR_FLG" VARCHAR2(1) DEFAULT 'N', 
	"MFR_SER_NBR_REQR_FLG" VARCHAR2(1) DEFAULT 'N', 
	"INSPECT_REQR_FLG" VARCHAR2(1) DEFAULT 'N', 
	"MFR_LOT_CTRL_FLG" VARCHAR2(1), 
	"KIT_FLG" VARCHAR2(1), 
	"PRICE_CHG_FLG" VARCHAR2(1), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"SELL_FLG" VARCHAR2(1), 
	"HARMONIZED_CD" VARCHAR2(15), 
	"PLAN_BUCKET_SZ" NUMBER(3,0), 
	"CURR_CD" VARCHAR2(3), 
	"REQR_MFR_FLG" VARCHAR2(1) DEFAULT 'N', 
	"SHELF_LIFE_DY" NUMBER(5,0), 
	"LEAD_TM_DY" NUMBER(5,0), 
	"INDIV_NBR_BUYER" NUMBER(9,0), 
	"STAT_ID" VARCHAR2(1) DEFAULT 'A', 
	"PICK_SCAN_ID" VARCHAR2(1), 
	"INTRO_DT" DATE, 
	"SPLIT_AT_BIN_FLG" VARCHAR2(1), 
	"LABEL_NM_BOX" VARCHAR2(20), 
	"IC_RECV_RULE_CD" VARCHAR2(16), 
	"CYCLE_CNT_RULE_CD" VARCHAR2(16), 
	"FIFO_DT_ID" VARCHAR2(1), 
	"REPLEN_TYPE_ID" VARCHAR2(1) DEFAULT 'B', 
	"ITEM_NBR_PRIMARY" NUMBER(9,0), 
	"ITEM_NBR_SUPERSEDE" NUMBER(9,0), 
	"SCHED_QTY_OPTIMAL" NUMBER(7,0), 
	"IMG_IMAGE_SET_HDR_NBR" NUMBER(9,0), 
	"ITEM_WGHT" NUMBER(12,5), 
	"CTN_VOLUME" NUMBER(10,2), 
	"USER_FLD_1" VARCHAR2(20), 
	"USER_FLD_2" VARCHAR2(20), 
	"USER_FLD_3" VARCHAR2(20), 
	"USER_FLD_4" VARCHAR2(20), 
	"USER_FLD_5" VARCHAR2(20), 
	"USER_FLD_6" VARCHAR2(20), 
	"USER_FLD_7" VARCHAR2(20), 
	"USER_FLD_8" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;

   COMMENT ON COLUMN "IC_ITEM_MAST"."FIFO_DT_ID" IS 'R-Receipt Date, M-Manufacture Date, E-Expiration Date';
   COMMENT ON COLUMN "IC_ITEM_MAST"."REPLEN_TYPE_ID" IS 'B-Buy, M-Manufacture,
	A-Assemble, K-Kit, D-Do not Buy';
