--------------------------------------------------------
--  DDL for Table IDL_SO_HIST_DTL
--------------------------------------------------------

  CREATE TABLE "IDL_SO_HIST_DTL" 
   (	"SALES_ORDER_NUMBER" VARCHAR2(16), 
	"CUSTOMER_NUMBER" VARCHAR2(16), 
	"SALESPERSON_CODE" VARCHAR2(16), 
	"ITEM_CD" VARCHAR2(50), 
	"QTY_ORDERED" NUMBER, 
	"UNIT_PRICE" NUMBER, 
	"AVG_COST" NUMBER, 
	"PROD_LINE" VARCHAR2(5), 
	"STYLE" VARCHAR2(20), 
	"COLOR" VARCHAR2(10), 
	"SZ" VARCHAR2(10), 
	"ORDER_DT" DATE, 
	"START_SHIP_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 671088640 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
