--------------------------------------------------------
--  DDL for Table IDL_CUST_MAST
--------------------------------------------------------

  CREATE TABLE "IDL_CUST_MAST" 
   (	"IDL_CUST_MAST_NBR" VARCHAR2(9), 
	"ORG_CD_CUST" VARCHAR2(16), 
	"FCST_GRP" VARCHAR2(8), 
	"SLS_TERR_CD" VARCHAR2(8), 
	"SLS_GRP" VARCHAR2(8), 
	"SALESMAN_CD" VARCHAR2(8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;

   COMMENT ON COLUMN "IDL_CUST_MAST"."ORG_CD_CUST" IS 'Unique Code Identifying a Customer';
   COMMENT ON COLUMN "IDL_CUST_MAST"."FCST_GRP" IS 'The Group assigned to the Customer for Forecasting purposes';
   COMMENT ON TABLE "IDL_CUST_MAST"  IS 'System interface table for loading customer information.';
