--------------------------------------------------------
--  DDL for Table ITEM_TMP3
--------------------------------------------------------

  CREATE TABLE "ITEM_TMP3" 
   (	"ITEM_CD" VARCHAR2(50), 
	"STYLE" VARCHAR2(20), 
	"COLOR" VARCHAR2(20), 
	"SZ" VARCHAR2(20), 
	"PROD_LINE" VARCHAR2(20), 
	"STATUS" VARCHAR2(10), 
	"SEASON" VARCHAR2(20), 
	"NEVER_OUT" VARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 655360 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
