--------------------------------------------------------
--  DDL for Table NA_INDIV
--------------------------------------------------------

  CREATE TABLE "NA_INDIV" 
   (	"INDIV_NBR" NUMBER(9,0), 
	"SORT_NM" VARCHAR2(41), 
	"FIRST_NM" VARCHAR2(20), 
	"MIDDLE_INIT" VARCHAR2(1), 
	"LAST_NM" VARCHAR2(20), 
	"SALUTATION_CD" VARCHAR2(4), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"INDIV_DESCR" VARCHAR2(40), 
	"PHN_NBR_DFLT" VARCHAR2(20), 
	"FAX_NBR_DFLT" VARCHAR2(20), 
	"EMAIL_ADDR_DFLT" VARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;

   COMMENT ON COLUMN "NA_INDIV"."INDIV_NBR" IS 'Surrogate primary key for INDIV_NBR';
   COMMENT ON COLUMN "NA_INDIV"."MIDDLE_INIT" IS 'The first letter of an individual''s middle name, not the surname or given name.';
   COMMENT ON COLUMN "NA_INDIV"."UT_USER_NBR" IS 'Surrogate primary key for UT_USER';
   COMMENT ON COLUMN "NA_INDIV"."PHN_NBR_DFLT" IS 'Default telephone number for this entity.';
