--------------------------------------------------------
--  DDL for Table NA_ORG
--------------------------------------------------------

  CREATE TABLE "NA_ORG" 
   (	"ORG_NBR" NUMBER(9,0), 
	"ORG_NM" VARCHAR2(60), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"ORG_WEB_SITE" VARCHAR2(255), 
	"CURR_CD_DFLT" VARCHAR2(3), 
	"ORG_CD" VARCHAR2(15), 
	"PHN_NBR_DFLT" VARCHAR2(20), 
	"FAX_NBR_DFLT" VARCHAR2(20), 
	"CALENDAR" VARCHAR2(8), 
	"UT_LOCALE_NBR" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
