--------------------------------------------------------
--  DDL for Table OE_CUST_MFR
--------------------------------------------------------

  CREATE TABLE "OE_CUST_MFR" 
   (	"ITEM_NBR" NUMBER(9,0), 
	"ORG_NBR_CUST" NUMBER(9,0), 
	"ORG_NBR_MFR" NUMBER(9,0), 
	"EFF_DT_BEG" DATE, 
	"EFF_DT_END" DATE, 
	"MFR_RESTRICT_ID" VARCHAR2(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
