--------------------------------------------------------
--  DDL for Table PO_LINE_HDR
--------------------------------------------------------

  CREATE TABLE "PO_LINE_HDR" 
   (	"PO_LINE_HDR_NBR" NUMBER(9,0), 
	"PO_ORD_HDR_NBR" NUMBER(9,0), 
	"PO_LINE_NBR" NUMBER(3,0), 
	"ITEM_NBR" NUMBER(9,0), 
	"REPLEN_UM" VARCHAR2(3), 
	"UNIT_COST" NUMBER(13,5), 
	"UNIT_COST_DENOM" NUMBER(13,5), 
	"REV_LVL" VARCHAR2(5), 
	"ORG_NBR_MFR" NUMBER(9,0), 
	"LINE_STAT_ID" VARCHAR2(1), 
	"VNDR_ORD_LINE_CD" VARCHAR2(3), 
	"CNTRY_CD_ORIGIN" VARCHAR2(3), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"ENTER_DT" DATE, 
	"ITEM_CD_VND" VARCHAR2(50), 
	"CANCEL_CD" VARCHAR2(8), 
	"CANCEL_DT" DATE, 
	"UT_USER_NBR_CANCEL" NUMBER(9,0), 
	"LOT_NOT_EXPIRE_BEFORE_DT" DATE, 
	"LOT_MANUFACTURE_AFTER_DT" DATE, 
	"REPLEN_QTY" NUMBER(13,5), 
	"REPLEN_QTY_STK_UM" NUMBER(13,5), 
	"UNIT_COST_STK_UM" NUMBER(17,6), 
	"UNIT_COST_DENOM_STK_UM" NUMBER(17,6), 
	"PO_CLOSE_REASON_CD" VARCHAR2(8), 
	"CLOSE_TM" DATE, 
	"UT_USER_NBR_CLOSE" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;

   COMMENT ON COLUMN "PO_LINE_HDR"."LINE_STAT_ID" IS 'O-Open, C-Closed, X-Cancelled';
