--------------------------------------------------------
--  DDL for Table PO_MFR_MAST
--------------------------------------------------------

  CREATE TABLE "PO_MFR_MAST" 
   (	"ORG_NBR_MFR" NUMBER(9,0), 
	"STAT_ID" VARCHAR2(1), 
	"INTRO_DT" DATE, 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"MAIL_TO_ADDR_NBR_DFLT" NUMBER(9,0), 
	"BILL_TO_ADDR_NBR_DFLT" NUMBER(9,0), 
	"MFR_CAGE_CD" VARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
