--------------------------------------------------------
--  DDL for Table SERVICE_RQST
--------------------------------------------------------

  CREATE TABLE "SERVICE_RQST" 
   (	"SERVICE_RQST_CD" VARCHAR2(20), 
	"SERVICE_RQST_DESCR" VARCHAR2(60), 
	"CLASSNAME" VARCHAR2(255), 
	"PIPE_NM" VARCHAR2(255), 
	"VALIDATE_FLG" VARCHAR2(1) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
