--------------------------------------------------------
--  DDL for Table TMP_INVENTORY_PIPELINE
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "TMP_INVENTORY_PIPELINE" 
   (	"PIPELINE_DT" DATE, 
	"QTY_ON_HAND" NUMBER, 
	"OPEN_PO_QTY" NUMBER, 
	"OPEN_SO_QTY" NUMBER, 
	"SAFETY_STK_QTY" NUMBER, 
	"FCST_QTY" NUMBER, 
	"QTY_ON_HAND_REMAIN" NUMBER, 
	"ARO_QTY" NUMBER, 
	"ONHAND_VALUE" NUMBER, 
	"OPEN_PO_VALUE" NUMBER, 
	"OPEN_SO_VALUE" NUMBER, 
	"SAFETY_STK_VALUE" NUMBER, 
	"FCST_VALUE" NUMBER, 
	"REMAIN_VALUE" NUMBER, 
	"ARO_VALUE" NUMBER
   ) ON COMMIT PRESERVE ROWS ;
