--------------------------------------------------------
--  DDL for Table USER_FIELD_CTL
--------------------------------------------------------

  CREATE TABLE "USER_FIELD_CTL" 
   (	"TABLE_NAME" VARCHAR2(32), 
	"COLUMN_NAME" VARCHAR2(32), 
	"HEADER" VARCHAR2(16), 
	"LABEL" VARCHAR2(32), 
	"COLUMN_VALUES_QUERY" VARCHAR2(2048), 
	"REF_TABLE_NAME" VARCHAR2(32), 
	"REF_TABLE_COLUMN" VARCHAR2(32), 
	"REF_TABLE_COLUMN_VAL" VARCHAR2(16), 
	"REF_TABLE_USER_VAL" VARCHAR2(16)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
