--------------------------------------------------------
--  DDL for Table UT_DATA_SRC
--------------------------------------------------------

  CREATE TABLE "UT_DATA_SRC" 
   (	"DATA_SRC_NM" VARCHAR2(20), 
	"DATA_SRC_URL" VARCHAR2(512), 
	"DATA_SRC_DRIVER_NM" VARCHAR2(128), 
	"DATA_SRC_USERNAME" VARCHAR2(20), 
	"DATA_SRC_PASSWORD" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
