--------------------------------------------------------
--  DDL for Table UT_ETL
--------------------------------------------------------

  CREATE TABLE "UT_ETL" 
   (	"UT_ETL_NBR" NUMBER(9,0), 
	"UT_ETL_DESCR" VARCHAR2(80), 
	"TRUNC_FLG" VARCHAR2(1), 
	"TABLE_ID" VARCHAR2(8), 
	"DATA_SELECT_STMT" VARCHAR2(4000), 
	"DATA_INSERT_STMT" VARCHAR2(4000), 
	"DATA_SRC_NM_SRC" VARCHAR2(20), 
	"DATA_SRC_NM_DEST" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
