--------------------------------------------------------
--  DDL for Table UT_PROCESS_STATUS
--------------------------------------------------------

  CREATE TABLE "UT_PROCESS_STATUS" 
   (	"UT_PROCESS_STATUS_NBR" NUMBER(9,0), 
	"PROCESS_NM" VARCHAR2(128), 
	"THREAD_NM" VARCHAR2(128), 
	"PROCESS_RUN_NBR" NUMBER(9,0), 
	"STATUS_MSG" VARCHAR2(2000), 
	"STATUS_ID" VARCHAR2(1), 
	"STATUS_TS" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
