--------------------------------------------------------
--  DDL for Table UT_TABLE_RULE
--------------------------------------------------------

  CREATE TABLE "UT_TABLE_RULE" 
   (	"TABLE_ID" VARCHAR2(8), 
	"MSG_ID" VARCHAR2(16), 
	"SQL_TEXT" VARCHAR2(4000), 
	"MSG_DESCR" VARCHAR2(4000), 
	"QUERY_NM" VARCHAR2(32), 
	"RULE_TYPE" VARCHAR2(8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
