--------------------------------------------------------
--  DDL for Table UT_TABLE_ROW_MSG
--------------------------------------------------------

  CREATE TABLE "UT_TABLE_ROW_MSG" 
   (	"TABLE_ID" VARCHAR2(32), 
	"PRIMARY_KEY" NUMBER(18,0), 
	"MSG_ID" VARCHAR2(16), 
	"MSG" VARCHAR2(64)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
