--------------------------------------------------------
--  DDL for Table UT_USER
--------------------------------------------------------

  CREATE TABLE "UT_USER" 
   (	"ORG_NBR" NUMBER(9,0), 
	"UT_USER_NBR" NUMBER(9,0), 
	"USER_NAME" VARCHAR2(15), 
	"PASSWD" VARCHAR2(10), 
	"CALENDAR" VARCHAR2(6), 
	"FACILITY" VARCHAR2(16), 
	"PRINTER" VARCHAR2(50), 
	"PRINTER_LABEL" VARCHAR2(50), 
	"PICK_RULE_CD" VARCHAR2(8), 
	"PACK_STATION" VARCHAR2(16), 
	"RF_PASSWD" VARCHAR2(20), 
	"INDIV_NBR" NUMBER(9,0), 
	"LAST_LOGIN_TM" DATE, 
	"SHOW_TOOLTIP_FLG" VARCHAR2(1) DEFAULT 'Y', 
	"USER_STAT_ID" VARCHAR2(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;

   COMMENT ON COLUMN "UT_USER"."ORG_NBR" IS 'Surrogate primary key for ORG_NBR';
   COMMENT ON COLUMN "UT_USER"."UT_USER_NBR" IS 'Surrogate primary key for UT_USER';
   COMMENT ON COLUMN "UT_USER"."PASSWD" IS 'A password, may be encrypted or obfuscated.  Depending on options may be reversible.';
   COMMENT ON COLUMN "UT_USER"."FACILITY" IS 'The facility associated with this record.  ';
   COMMENT ON COLUMN "UT_USER"."INDIV_NBR" IS 'Surrogate primary key for INDIV_NBR';
