--------------------------------------------------------
--  DDL for Table WEB_REPORT
--------------------------------------------------------

  CREATE TABLE "WEB_REPORT" 
   (	"WEB_REPORT_NBR" NUMBER(9,0), 
	"REPORT_CD" VARCHAR2(16), 
	"REPORT_DESCR" VARCHAR2(60), 
	"XSQL_FILE_NM" VARCHAR2(255), 
	"XSL_FILE_NM" VARCHAR2(255), 
	"APEX_APP_NBR_SRC" NUMBER(9,0), 
	"APEX_APP_NBR_DEST" NUMBER(9,0), 
	"APEX_PAGE_NBR" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
