--------------------------------------------------------
--  DDL for Table Y
--------------------------------------------------------

  CREATE TABLE "Y" 
   (	"ITEM_NBR" NUMBER(9,0), 
	"NEED_BY_DT" DATE, 
	"FACILITY" VARCHAR2(16), 
	"NEED_QTY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
