import { ListOfValue  } from '../dto/ListOfValue';

export const IC_CATEGORIES: ListOfValue[] = [
    { code: '000', description: 'Unknown' },
    { code: '001', description: 'Miscellaneous Charges' },
    { code: '002', description: 'Aerospace Demo Products' },
    { code: '003', description: 'BRAD' },
    { code: '010', description: 'Zephyr' },
    { code: '015', description: 'Clamps and Brackets' },
    { code: '016', description: 'Fittings' },
    { code: '017', description: 'Collars' },
    { code: '020', description: 'Jumpers and Terminals' },
    { code: '021', description: 'Fillers,Shims,Decals,Markers' },
    { code: '022', description: 'O-Rings,Packings,Retainers' },
    { code: '023', description: 'Pins, Miscellaneous' },
    { code: '024', description: 'Washers' },
    { code: '025', description: 'Bolts' },
    { code: '026', description: 'Screws' },
    { code: '028', description: 'Canada Air Tooling(Use 098)' },
    { code: '029', description: 'Grommets' },
    { code: '030', description: 'Hinges' },
    { code: '032', description: 'Gang Channels' },
    { code: '033', description: 'Studs' },
    { code: '034', description: 'Inserts' },
    { code: '035', description: 'Nuts, Miscellaneous' },
    { code: '038', description: 'Douglas Tooling(Use 098)' },
    { code: '043', description: 'Delron Products' },
    { code: '046', description: 'Huck Captive Screws & Nuts' },
    { code: '048', description: 'Monogram Wedgelock' },
    { code: '055', description: 'Flexloc Self Locking Nuts' },
    { code: '056', description: 'Huck Products' },
    { code: '058', description: 'Deutsch Fittings' },
    { code: '059', description: 'Deutsch Tooling' },
    { code: '060', description: 'BRUCE LIGHTING' },
    { code: '061', description: 'Aircraft Bearings & Bushings' },
    { code: '063', description: 'Calfax Products' },
    { code: '066', description: 'Visuloks' },
    { code: '068', description: 'Taperlok Cutters' },
    { code: '071', description: 'Taperloks - Regular' },
    { code: '072', description: 'Oversize Taperloks' },
    { code: '075', description: 'Rivets, Solid' },
    { code: '076', description: 'Blind Rivets' },
    { code: '078', description: 'California Aircraft Tools' },
    { code: '081', description: 'Pins' },
    { code: '083', description: 'SHURLOK' },
    { code: '085', description: 'Precision Springs' },
    { code: '088', description: 'Wire' },
    { code: '091', description: 'Aerospace' },
    { code: '095', description: 'Self-Locking' },
    { code: '096', description: 'Miscellaneous Aerospace Prod' },
    { code: '098', description: 'Aerospace Tooling' },
    { code: '099', description: 'Kits' },
    { code: '102', description: 'Industrial Demo Products' },
    { code: '103', description: 'EIDOS' },
    { code: '105', description: 'APM HEXSEAL' },
    { code: '107', description: 'Hex Hd Cap Screw Imperial' },
    { code: '108', description: 'Hex Hd Cap Screw Metric' },
    { code: '109', description: 'Nuts Imperial' },
    { code: '110', description: 'Nuts Metric' },
    { code: '111', description: 'Screws Imperial' },
    { code: '112', description: 'Screws Metric' },
    { code: '113', description: 'Washers Imperial' },
    { code: '114', description: 'Washers Metric' },
    { code: '115', description: 'Machined Parts' },
    { code: '116', description: 'Socket Hd Cap Screws Imperial' },
    { code: '117', description: 'Socket Hd Cap Screws Metric' },
    { code: '118', description: 'Socket Set Screws Imperial' },
    { code: '119', description: 'Socket Set Screws Metric' },
    { code: '120', description: 'Allen Hand Tools' },
    { code: '121', description: 'Flexloc Self Locking Nuts' },
    { code: '122', description: 'Pemserter Presses & Tooling' },
    { code: '134', description: 'Jonathan/COMPX' },
    { code: '135', description: 'Aztec Engineering' },
    { code: '136', description: 'Miscelleanous Industrial' },
    { code: '140', description: 'Holokrome Metrics' },
    { code: '141', description: 'UNBRAKO METRICS' },
    { code: '142', description: 'UNBRAKO(Metric, Semi-Standard)' },
    { code: '143', description: 'Unbrako Shoulder Bolts-Inch' },
    { code: '144', description: 'UNBRAKO Shoulder Bolts-Metric' },
    { code: '150', description: 'Unbrako Non Stock Items' },
    { code: '151', description: 'UNBRAKO SPECIALS' },
    { code: '152', description: 'Atlas Inserts / Tooling' },
    { code: '153', description: 'Speedserts' },
    { code: '154', description: 'Hemco Guages' },
    { code: '155', description: 'Nylon Collar Lock Nuts' },
    { code: '15P', description: 'Atlas Engineering Tool Parts' },
    { code: '160', description: 'Stafford Collars & Couplings' },
    { code: '162', description: 'Stickscrew Screws PEM' },
    { code: '165', description: 'Monadnock' },
    { code: '16P', description: 'Stickscrew Tool Parts' },
    { code: '16T', description: 'Stickscrew Tools' },
    { code: '170', description: 'Eaton Yale' },
    { code: '173', description: 'Southco' },
    { code: '180', description: 'Holokrome Keys' },
    { code: '181', description: 'UNBRAKO KEYS' },
    { code: '182', description: 'Pemserter / Tooling' },
    { code: '183', description: 'Coilthread Inserts (Kato)' },
    { code: '185', description: 'PEM Specials' },
    { code: '186', description: 'Camloc Products' },
    { code: '188', description: 'UNBRAKO(Semi-Standard)' },
    { code: '189', description: 'Amtak Tacks, Pins' },
    { code: '18P', description: 'Amtak Tool Parts' },
    { code: '18T', description: 'Amtak Tools' },
    { code: '190', description: 'Holokrome Imperial Screws' },
    { code: '191', description: 'UNBRAKO(Standard)' },
    { code: '192', description: 'PEM' },
    { code: '193', description: 'Keenserts' },
    { code: '194', description: 'DZUS' },
    { code: '195', description: 'Keysert' },
    { code: '196', description: 'Recoil' },
    { code: '197', description: 'Carbon Steel Inserts' },
    { code: '198', description: 'Tool Repair  Rental  Service' },
    { code: '199', description: 'ND / Nylok' },
    { code: 'Aerospace', description: 'Aerospace' },
    { code: 'Altas Division', description: 'Altas Division' },
    { code: 'Amtak Line', description: 'Amtak Line' },
    { code: 'Coilthread', description: 'Coilthread Products' },
    { code: 'Commercial Items', description: 'Commercial Products' },
    { code: 'Danaher Products', description: 'Danaher Products' },
    { code: 'FinWasher', description: 'Finishing Washer' },
    { code: 'FinWasherImp', description: 'Finishing Washer Imperial' },
    { code: 'FinWasherMet', description: 'Finishing Washer Metric' },
    { code: 'Flat Washer Met', description: 'Flat Washers Metric' },
    { code: 'FlatWasherImp', description: 'Imperial Flat Wahers' },
    { code: 'FlatWashers', description: 'Flat Washers' },
    { code: 'Hex Hd Cap Screw', description: 'Hex head Cap Screw' },
    { code: 'Huck Products', description: 'Huck Products' },
    { code: 'Industrial', description: 'Industrial Parts' },
    { code: 'Inserts', description: 'All Inserts and Insert Tooling' },
    { code: 'Interfast', description: 'All parts' },
    { code: 'LockWasher', description: 'Locking Wahsers' },
    { code: 'LockWasherImp', description: 'Lock Washer Imperial' },
    { code: 'LockWasherMet', description: 'Lock Washers Metric' },
    { code: 'Miscellaneous', description: 'Interfast' },
    { code: 'Nuts', description: 'Nuts' },
    { code: 'PEM Corporation', description: 'PEM Corporation' },
    { code: 'PEM Division', description: 'PEM Division' },
    { code: 'Pemserter Line', description: 'Pemserter Line' },
    { code: 'Rivets', description: 'Rivets' },
    { code: 'Screws', description: 'Screws' },
    { code: 'Sock Hd Cap Scre', description: 'Socket Headed Cap Screws' },
    { code: 'Sock Set Screws', description: 'Socket Set Screws' },
    { code: 'Stickscrew Line', description: 'Stickscrew Products' },
    { code: 'Taperloks', description: 'Tapeloks' },
    { code: 'Tooling Aero', description: 'Aerospace Tooling' },
    { code: 'Washers', description: 'Washers' },
];
