import { IcItemMast } from '../dto/icItemMast';

export const ICITEMMASTS: IcItemMast[] = [
    {
      itemNbr: 33791,
      itemCd: 'BACB30VT6K3',
      itemDescr: 'PIN',
      stkUm: 'EA',
      sellUm: 'EA',
      stdCost: 1.163108,
      icCategoryNbr: 250,
      nonStkFlg: 'N',
      serNbrReqrFlg: 'N',
      mfrSerNbrReqrFlg: 'N',
      inspectReqrFlg: 'Y',
      mfrLotCtrlFlg: 'Y',
      kitFlg: 'N',
      priceChgFlg: 'Y',
      utUserNbr: 81,
      lastModDt: '2019-01-27T04:33:59+07',
      sellFlg: 'Y',
      harmonizedCd: '73182990009967',
      currCd: 'CAD',
      reqrMfrFlg: 'Y',
      leadTmDy: 630,
      statId: 'A',
      pickScanId: 'L',
      introDt: '2012-09-15T04:33:59+07',
      splitAtBinFlg: 'N',
      fifoDtId: 'R',
      replenTypeId: 'B',
    },
    {
      itemNbr: 53515,
      itemCd: 'HST10AG6-3',
      itemDescr: 'PIN',
      stkUm: 'EA',
      sellUm: 'EA',
      stdCost: 0.524488,
      icCategoryNbr: 250,
      nonStkFlg: 'N',
      serNbrReqrFlg: 'N',
      mfrSerNbrReqrFlg: 'N',
      inspectReqrFlg: 'Y',
      mfrLotCtrlFlg: 'Y',
      kitFlg: 'N',
      priceChgFlg: 'Y',
      utUserNbr: 81,
      lastModDt: '2018-08-31T04:33:59+07',
      sellFlg: 'Y',
      harmonizedCd: '73182990009967',
      currCd: 'CAD',
      reqrMfrFlg: 'Y',
      leadTmDy: 700,
      statId: 'A',
      pickScanId: 'L',
      introDt: '2006-10-10T04:33:59+07',
      splitAtBinFlg: 'N',
      fifoDtId: 'R',
      replenTypeId: 'B',
    },
    {
      itemNbr: 127544,
      itemCd: 'B0206001AG6-3',
      itemDescr: 'HI LITE',
      stkUm: 'EA',
      sellUm: 'EA',
      icCategoryNbr: 254,
      nonStkFlg: 'N',
      serNbrReqrFlg: 'N',
      mfrSerNbrReqrFlg: 'N',
      inspectReqrFlg: 'Y',
      mfrLotCtrlFlg: 'Y',
      kitFlg: 'N',
      priceChgFlg: 'Y',
      utUserNbr: 1,
      lastModDt: '2011-12-19T04:33:59+07',
      sellFlg: 'Y',
      harmonizedCd: '88033000009967',
      currCd: 'CAD',
      reqrMfrFlg: 'Y',
      leadTmDy: 142,
      statId: 'A',
      pickScanId: 'L',
      introDt: '2011-12-19T04:33:59+07',
      splitAtBinFlg: 'N',
      fifoDtId: 'R',
      replenTypeId: 'B',
      stdCost: null,
    },
    {
      itemNbr: 346096,
      itemCd: 'HST10AG-6-3',
      itemDescr: 'Use HST10AG6-3',
      stkUm: 'EA',
      sellUm: 'EA',
      icCategoryNbr: 636,
      nonStkFlg: 'N',
      serNbrReqrFlg: 'N',
      mfrSerNbrReqrFlg: 'N',
      inspectReqrFlg: 'Y',
      mfrLotCtrlFlg: 'Y',
      kitFlg: 'N',
      priceChgFlg: 'Y',
      utUserNbr: 81,
      lastModDt: '2018-08-31T04:33:59+07',
      harmonizedCd: '73181590459967',
      reqrMfrFlg: 'Y',
      leadTmDy: 700,
      statId: 'A',
      pickScanId: 'L',
      introDt: '2015-11-01T13:37:38+07',
      splitAtBinFlg: 'N',
      fifoDtId: 'R',
      replenTypeId: 'D',
      stdCost: null,
      sellFlg: 'Y',
      currCd: 'CAD'
    },
    {
      itemNbr: 1304665,
      itemCd: '100-159-6-3',
      itemDescr: 'PIN',
      stkUm: 'EA',
      sellUm: 'EA',
      icCategoryNbr: 250,
      nonStkFlg: 'Y',
      serNbrReqrFlg: 'N',
      mfrSerNbrReqrFlg: 'N',
      inspectReqrFlg: 'Y',
      mfrLotCtrlFlg: 'Y',
      kitFlg: 'N',
      priceChgFlg: 'Y',
      utUserNbr: 66,
      lastModDt: '2018-12-15T04:33:59+07',
      sellFlg: 'Y',
      harmonizedCd: '8803300000',
      reqrMfrFlg: 'Y',
      leadTmDy: 114,
      statId: 'A',
      pickScanId: 'L',
      introDt: '2018-12-15T04:33:59+07',
      splitAtBinFlg: 'N',
      fifoDtId: 'R',
      replenTypeId: 'B',
      stdCost: null,
      currCd: null
    }
];
