import { PipelineLine } from '../dto/pipelineLine';

export const PIPELINE_LINE: PipelineLine = {
      identifiers: [
        'LACORE',
        'Adjusted'
      ],
      values: [
        null,
        25.0,
        25.0,
        25.0,
        25.0,
        25.0,
        25.0,
        25.0,
        25.0,
        25.0,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
};
