changequote(`{{', `}}')
include({{ProjectDescription.rst}})
include({{Features.rst}})
include({{Benefits.rst}})
include({{Analyze.rst}})
include({{Answers.rst}})
include({{Audit.rst}})
include({{processing.rst}})
include({{ProductOffering.rst}})
include({{Technologies.rst}})
include({{vending-sales-reporting.rst}})
include({{cds_record_layout.rst}})
include({{Contributions.rst}})
)
