export class IcItemMast {
  itemNbr: number;
  itemCd: string;
  itemDescr: string;
  stkUm: string;
  sellUm: string;
  stdCost: number;
  leadTmDy: number;
  serNbrReqrFlg: string;
  mfrSerNbrReqrFlg: string;
  inspectReqrFlg: string;
  mfrLotCtrlFlg: string;
  kitFlg: string;
  priceChgFlg: string;
  utUserNbr: number;
  lastModDt: string;
  sellFlg: string;
  harmonizedCd: string;
  currCd: string;
  reqrMfrFlg: string;
  statId: string;
  pickScanId: string;
  introDt: string;
  splitAtBinFlg: string;
  fifoDtId: string;
  replenTypeId: string;
  icCategoryNbr: number;
  nonStkFlg: string;
}
