--------------------------------------------------------
--  File created - Tuesday-May-12-2020   
--------------------------------------------------------
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_INFO_ID_SEQ.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_INFO_RUN_ID_SEQ.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/JOB_LOG_ID_SEQ.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/JOB_MSG_ID_SEQ.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/JOB_STEP_ID_SEQ.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/LOGGER_DTL_ID_SEQ.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/LOGGER_DTL_SEQ.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/LOGGER_HDR_ID_SEQ.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/UT_CONDITION_ID_SEQ.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/UT_CONDITION_RUN_ID_SEQ.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/UT_CONDITION_RUN_STEP_ID_SEQ.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_EXPLAIN_PLAN.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_INFO.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_INFO_RUN.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_SQL_TEXT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_STAT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/JOB_LOG.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/JOB_MSG.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/JOB_STEP.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/LOGGER_DTL.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/LOGGER_HDR.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/UT_CONDITION.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/UT_CONDITION_ROW_MSG.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/UT_CONDITION_RUN.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/UT_CONDITION_RUN_PARM.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/UT_CONDITION_RUN_STEP.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_INFO_VW.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/JOB_LOG_VW.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/JOB_STEP_VW.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/LOGGER_HDR_DTL.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/JOB_LOG_PK.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/JOB_LOG_TOKEN_UQ.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/JOB_MSG_PK.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/JOB_STEP_PK.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/LOGGER_DTL_UNIQ.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_EXPLAIN_PLAN_PK.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_INFO_PK.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_INFO_RUN_ID.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_STAT_PK.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_TEXT_PK.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/PLLOGGER_TEST_1.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/PLLOGGER_TEST_2.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/PREPARE_CONNECTION.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/LOGGER.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/PLLOGGER.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/LOGGER_1.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/PLLOGGER_1.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/LOGGER_MESSAGE_FORMATTER.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/READ_FILE.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/JOB_STEP_CONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/UT_CONDITION_RUN_CONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/LOGGER_HDR_CONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/LOGGER_DTL_CONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/UT_CONDITION_RUN_STEP_CONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_INFO_RUN_CONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_SQL_TEXT_CONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/UT_CONDITION_ROW_MSG_CONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/UT_CONDITION_RUN_PARM_CONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_STAT_CONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/JOB_MSG_CONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/JOB_LOG_CONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_INFO_CONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/UT_CONDITION_CONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_EXPLAIN_PLAN_CONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_INFO_REFCONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/CURSOR_STAT_REFCONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/JOB_MSG_REFCONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/JOB_STEP_REFCONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/UT_CONDITION_ROW_MSG_REFCONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/UT_CONDITION_RUN_PARM_REFCONSTRAINT.sql
@/common/home/jjs/java-projects/diamond-javautil-2020/javautil-7/javautil-dblogging/exports/UT_CONDITION_RUN_STEP_REFCONSTRAINT.sql
