--------------------------------------------------------
--  DDL for Table JOB_LOG
--------------------------------------------------------

  CREATE TABLE "JOB_LOG" 
   (	"JOB_LOG_ID" NUMBER(9,0), 
	"SCHEMA_NAME" VARCHAR2(30), 
	"PROCESS_NAME" VARCHAR2(128), 
	"THREAD_NAME" VARCHAR2(128), 
	"STATUS_MSG" VARCHAR2(256), 
	"STATUS_TS" TIMESTAMP (9), 
	"END_TS" TIMESTAMP (9), 
	"ELAPSED_MILLIS" NUMBER(9,0), 
	"SID" NUMBER, 
	"SERIAL_NBR" NUMBER, 
	"IGNORE_FLG" VARCHAR2(1) DEFAULT 'N', 
	"MODULE_NAME" VARCHAR2(64), 
	"CLASSNAME" VARCHAR2(255), 
	"TRACEFILE_NAME" VARCHAR2(4000), 
	"TRACEFILE_DATA" CLOB, 
	"TRACEFILE_JSON" CLOB, 
	"ABORT_STACKTRACE" CLOB, 
	"JOB_TOKEN" VARCHAR2(64), 
	"LOGFILE_NAME" VARCHAR2(255)
   ) ;
