--------------------------------------------------------
--  Constraints for Table UT_CONDITION
--------------------------------------------------------

  ALTER TABLE "UT_CONDITION" MODIFY ("UT_CONDITION_ID" NOT NULL ENABLE);
  ALTER TABLE "UT_CONDITION" MODIFY ("CONDITION_NAME" NOT NULL ENABLE);
  ALTER TABLE "UT_CONDITION" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "UT_CONDITION" MODIFY ("SQL_TEXT" NOT NULL ENABLE);
  ALTER TABLE "UT_CONDITION" ADD PRIMARY KEY ("UT_CONDITION_ID")
  USING INDEX  ENABLE;
