--------------------------------------------------------
--  Constraints for Table UT_CONDITION_RUN_STEP
--------------------------------------------------------

  ALTER TABLE "UT_CONDITION_RUN_STEP" MODIFY ("UT_CONDITION_RUN_STEP_ID" NOT NULL ENABLE);
  ALTER TABLE "UT_CONDITION_RUN_STEP" MODIFY ("UT_CONDITION_ID" NOT NULL ENABLE);
  ALTER TABLE "UT_CONDITION_RUN_STEP" MODIFY ("UT_CONDITION_RUN_ID" NOT NULL ENABLE);
  ALTER TABLE "UT_CONDITION_RUN_STEP" MODIFY ("START_TS" NOT NULL ENABLE);
  ALTER TABLE "UT_CONDITION_RUN_STEP" ADD PRIMARY KEY ("UT_CONDITION_RUN_STEP_ID")
  USING INDEX  ENABLE;
