--------------------------------------------------------
--  Constraints for Table UT_CONDITION_RUN_PARM
--------------------------------------------------------

  ALTER TABLE "UT_CONDITION_RUN_PARM" MODIFY ("UT_CONDITION_RUN_ID" NOT NULL ENABLE);
  ALTER TABLE "UT_CONDITION_RUN_PARM" MODIFY ("PARM_NM" NOT NULL ENABLE);
  ALTER TABLE "UT_CONDITION_RUN_PARM" MODIFY ("PARM_TYPE" NOT NULL ENABLE);
  ALTER TABLE "UT_CONDITION_RUN_PARM" ADD PRIMARY KEY ("UT_CONDITION_RUN_ID", "PARM_NM")
  USING INDEX  ENABLE;
