ELECT vqh.vq_qte_hdr_nbr,
    vqh.vq_qte_cd,
    vqh.org_nbr_vnd,
    vqh.vq_qte_dt,
    nov.org_cd,
    nov.org_nm,
    vqh.curr_cd_qte,
    vqh.indiv_nm_spoken_to,
    vqh.indiv_phn_nbr,
    vqh.indiv_fax_nbr,
    vqh.indiv_email_addr,
    vqh.vq_qte_eff_dt,
    vqh.vq_qte_exp_dt,
    vqh.vnd_qte_ref_cd,
    vqh.vq_qte_indiv_nbr,
    vqh.transmit_flg,
    vqd.vq_qte_dtl_nbr,
    vqd.item_nbr_qte,
    vqd.item_cd_qte,
    vqd.item_cd_vnd,
    vqd.qte_um,
    vqd.qte_qty,
    vqd.qte_qty_stk_um,
    vqd.qte_cost,
    vqd.qte_cost_denom,
    vqd.qte_cost_stk_um,
    vqd.qte_cost_denom_stk_um,
    vqd.org_nbr_mfr_rqst,
    vqd.rev_lvl,
    vqd.rqst_dt,
    vqd.lead_tm_wk_prom,
    vqd.prom_dt,
    vqd.vq_lost_cd
   FROM vq_qte_hdr vqh,
    vq_qte_dtl vqd,
    na_org nov
  WHERE vqh.vq_qte_hdr_nbr = vqd.vq_qte_hdr_nbr 
	AND vqh.org_nbr_vnd = no.org_nbr;


