--#<
set echo on
--#>
create  or replace view oe_ord_hdr_dtl_vw as
select      
        ooh.oe_ord_hdr_nbr,
        ooh.ord_dt,
        ooh.ord_stat_id,
        ooh.org_nbr_cust,
        ooh.bill_to_addr_nbr,
        ooh.ship_to_addr_nbr_dflt,
        ooh.cust_po_cd,
        ooh.cust_po_dt,
        ooh.rqst_dt_dflt,
        ooh.cancel_dt cancel_dt_hdr,
        ooh.term_cd,
        ooh.ship_via_cd_dflt,
        ooh.fob_cd,
        ooh.curr_cd,
        ooh.ut_user_nbr_cancel,
        ooh.cancel_cd,
        ooh.ord_prty,
        ooh.sell_indiv_nbr,
        ooh.trd_flg,
        ooh.ut_user_nbr ut_user_nbr_hdr,
        ooh.last_mod_dt last_mod_dt_hdr,
        ooh.ship_pct_line,
        ooh.ship_pct_dollar,
        ooh.next_line_nbr,
        ooh.org_nm_cust,
        ooh.ord_type_cd,
        ooh.ord_cd,
        ooh.buyer_email_addr,
        ooh.indiv_nm_buyer,
        ooh.buyer_phn_nbr,
        ooh.sales_terr_cd,
        ooh.buyer_fax_nbr,
        ooh.transmit_flg,
        -- ooh.wh_ship_prty_nbr_dflt,
        -- ooh.payment_method_cd_dflt,
       ood.line_nbr,
       ood.item_nbr_rqst,
       ood.qty_ord,
       ood.sell_um,
       ood.rqst_dt,
       ood.ship_to_addr_nbr,
       ood.prom_dt_orig,
       ood.tie_cd,
       ood.line_stat_id,
       ood.item_cd_cust,
       ood.pkg_qty,
       ood.pick_prty_cust,
       ood.pick_prty_rqst,
       ood.pick_prty_past_due_mult,
       ood.ut_user_nbr ut_user_nbr_dtl,
       ood.last_mod_dt last_mod_dt_dtl,
       ood.ship_via_cd,
       ood.cust_bin_cd,
       ood.cust_line_cd,
       ood.org_nbr_mfr_rqst,
       ood.contract_cd,
       ood.qty_ship,
       ood.item_nbr_ord,
       ood.aps_src_rule_set_nbr,
       ood.cancel_cd cancel_cd_dtl,
       ood.cancel_dt line_cancel_dt,
       ood.ut_user_nbr_cancel ut_user_cancel_dtl,
       ood.lot_not_expire_before_dt,
       ood.lot_manufacture_after_dt,
       ood.cntry_cd_origin,
       ood.qty_ord_stk_um,
       ood.rev_lvl,
       ood.unit_price_stk_um,
       ood.unit_price_denom_stk_um,
       ood.qty_ship_stk_um,
       ood.part_mismatch_reason_cd,
       ood.unit_price_sell_um,
       ood.unit_price_denom_sell_um,
       ood.cust_ref,
       ood.qty_alloc,
       ood.qty_alloc_stk_um,
       ood.prom_dt_curr,
       ood.ship_from_facility,
       ood.ship_cmplt_flg,
       ood.hot_flg,
       ood.ship_line_pct,
       ood.oe_close_reason_cd,
       ood.close_tm,
       ood.ut_user_nbr_close,
       ood.auto_close_line_pct,
       ood.max_shipments_per_line
       -- ood.wh_ship_prty_nbr
from oe_ord_hdr ooh,
     oe_ord_dtl ood
where ooh.oe_ord_hdr_nbr = ood.oe_ord_hdr_nbr;
