package org.javautil.exceptionprocessing.dto;

// Generated Jun 7, 2009 8:20:16 PM by Hibernate Tools 3.2.2.GA

/**
 * UtProcessStatId generated by hbm2java
 */
public class UtProcessStatId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int utProcessStatusNbr;
	private int logSeqNbr;
	private Integer statistic;

	public UtProcessStatId() {
	}

	public UtProcessStatId(final int utProcessStatusNbr, final int logSeqNbr,
			final Integer statistic) {
		this.utProcessStatusNbr = utProcessStatusNbr;
		this.logSeqNbr = logSeqNbr;
		this.statistic = statistic;
	}

	public int getUtProcessStatusNbr() {
		return this.utProcessStatusNbr;
	}

	public void setUtProcessStatusNbr(final int utProcessStatusNbr) {
		this.utProcessStatusNbr = utProcessStatusNbr;
	}

	public int getLogSeqNbr() {
		return this.logSeqNbr;
	}

	public void setLogSeqNbr(final int logSeqNbr) {
		this.logSeqNbr = logSeqNbr;
	}

	public Integer getStatistic() {
		return this.statistic;
	}

	public void setStatistic(final Integer statistic) {
		this.statistic = statistic;
	}

}
