package org.javautil.exceptionprocessing.dto;

// Generated Jun 7, 2009 8:20:16 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * UtQuery generated by hbm2java
 */
public class UtQuery implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer utQueryNbr;
	private UtDataLocation utDataLocation;
	private String queryNm;
	private String queryDescr;
	private String queryText;
	private String apexRptHeading;
	private String tableId;
	private Set<UtTableRule> utTableRules = new HashSet<UtTableRule>(0);
	private Set<UtTableRuleHist> utTableRuleHists = new HashSet<UtTableRuleHist>(
			0);

	public UtQuery() {
	}

	public UtQuery(final UtDataLocation utDataLocation, final String queryNm) {
		this.utDataLocation = utDataLocation;
		this.queryNm = queryNm;
	}

	public UtQuery(final UtDataLocation utDataLocation, final String queryNm,
			final String queryDescr, final String queryText,
			final String apexRptHeading, final String tableId,
			final Set<UtTableRule> utTableRules,
			final Set<UtTableRuleHist> utTableRuleHists) {
		this.utDataLocation = utDataLocation;
		this.queryNm = queryNm;
		this.queryDescr = queryDescr;
		this.queryText = queryText;
		this.apexRptHeading = apexRptHeading;
		this.tableId = tableId;
		this.utTableRules = utTableRules;
		this.utTableRuleHists = utTableRuleHists;
	}

	public Integer getUtQueryNbr() {
		return this.utQueryNbr;
	}

	public void setUtQueryNbr(final Integer utQueryNbr) {
		this.utQueryNbr = utQueryNbr;
	}

	public UtDataLocation getUtDataLocation() {
		return this.utDataLocation;
	}

	public void setUtDataLocation(final UtDataLocation utDataLocation) {
		this.utDataLocation = utDataLocation;
	}

	public String getQueryNm() {
		return this.queryNm;
	}

	public void setQueryNm(final String queryNm) {
		this.queryNm = queryNm;
	}

	public String getQueryDescr() {
		return this.queryDescr;
	}

	public void setQueryDescr(final String queryDescr) {
		this.queryDescr = queryDescr;
	}

	public String getQueryText() {
		return this.queryText;
	}

	public void setQueryText(final String queryText) {
		this.queryText = queryText;
	}

	public String getApexRptHeading() {
		return this.apexRptHeading;
	}

	public void setApexRptHeading(final String apexRptHeading) {
		this.apexRptHeading = apexRptHeading;
	}

	public String getTableId() {
		return this.tableId;
	}

	public void setTableId(final String tableId) {
		this.tableId = tableId;
	}

	public Set<UtTableRule> getUtTableRules() {
		return this.utTableRules;
	}

	public void setUtTableRules(final Set<UtTableRule> utTableRules) {
		this.utTableRules = utTableRules;
	}

	public Set<UtTableRuleHist> getUtTableRuleHists() {
		return this.utTableRuleHists;
	}

	public void setUtTableRuleHists(final Set<UtTableRuleHist> utTableRuleHists) {
		this.utTableRuleHists = utTableRuleHists;
	}

}
