package org.javautil.exceptionprocessing.dto;

// Generated Jun 7, 2009 8:20:16 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * UtTableRule generated by hbm2java
 */
public class UtTableRule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer utTableRuleNbr;
	private UtAreaResp utAreaResp;
	private UtDataLocation utDataLocation;
	private UtTableRule utTableRule;
	private UtQuery utQuery;
	private String msgId;
	private String sqlText;
	private String msgDescr;
	private String ruleType;
	private String dataSrcNmSrc;
	private String dataSrcNmDest;
	private Integer maxQuerySec;
	private String severeRuleFlg;
	private String shortDescr;
	private String exceptionTypeCd;
	private String dispCdEnum;
	private Integer logLvl;
	private Set<UtTableRuleParm> utTableRuleParms = new HashSet<UtTableRuleParm>(
			0);
	private Set<UtTableRuleHist> utTableRuleHistsForUtTableRuleNbr = new HashSet<UtTableRuleHist>(
			0);
	private Set<UtTableRuleHist> utTableRuleHistsForUtTableRuleNbrExclude = new HashSet<UtTableRuleHist>(
			0);
	private Set<UtTableRuleRptSum> utTableRuleRptSums = new HashSet<UtTableRuleRptSum>(
			0);
	private Set<UtTableRowMsg> utTableRowMsgs = new HashSet<UtTableRowMsg>(0);
	private Set<UtTableRule> utTableRules = new HashSet<UtTableRule>(0);
	private Set<UtRuleGrpDtl> utRuleGrpDtls = new HashSet<UtRuleGrpDtl>(0);

	public UtTableRule() {
	}

	public UtTableRule(final UtDataLocation utDataLocation,
			final String severeRuleFlg, final String exceptionTypeCd) {
		this.utDataLocation = utDataLocation;
		this.severeRuleFlg = severeRuleFlg;
		this.exceptionTypeCd = exceptionTypeCd;
	}

	public UtTableRule(
			final UtAreaResp utAreaResp,
			final UtDataLocation utDataLocation,
			final UtTableRule utTableRule,
			final UtQuery utQuery,
			final String msgId,
			final String sqlText,
			final String msgDescr,
			final String ruleType,
			final String dataSrcNmSrc,
			final String dataSrcNmDest,
			final Integer maxQuerySec,
			final String severeRuleFlg,
			final String shortDescr,
			final String exceptionTypeCd,
			final String dispCdEnum,
			final Integer logLvl,
			final Set<UtTableRuleParm> utTableRuleParms,
			final Set<UtTableRuleHist> utTableRuleHistsForUtTableRuleNbr,
			final Set<UtTableRuleHist> utTableRuleHistsForUtTableRuleNbrExclude,
			final Set<UtTableRuleRptSum> utTableRuleRptSums,
			final Set<UtTableRowMsg> utTableRowMsgs,
			final Set<UtTableRule> utTableRules,
			final Set<UtRuleGrpDtl> utRuleGrpDtls) {
		this.utAreaResp = utAreaResp;
		this.utDataLocation = utDataLocation;
		this.utTableRule = utTableRule;
		this.utQuery = utQuery;
		this.msgId = msgId;
		this.sqlText = sqlText;
		this.msgDescr = msgDescr;
		this.ruleType = ruleType;
		this.dataSrcNmSrc = dataSrcNmSrc;
		this.dataSrcNmDest = dataSrcNmDest;
		this.maxQuerySec = maxQuerySec;
		this.severeRuleFlg = severeRuleFlg;
		this.shortDescr = shortDescr;
		this.exceptionTypeCd = exceptionTypeCd;
		this.dispCdEnum = dispCdEnum;
		this.logLvl = logLvl;
		this.utTableRuleParms = utTableRuleParms;
		this.utTableRuleHistsForUtTableRuleNbr = utTableRuleHistsForUtTableRuleNbr;
		this.utTableRuleHistsForUtTableRuleNbrExclude = utTableRuleHistsForUtTableRuleNbrExclude;
		this.utTableRuleRptSums = utTableRuleRptSums;
		this.utTableRowMsgs = utTableRowMsgs;
		this.utTableRules = utTableRules;
		this.utRuleGrpDtls = utRuleGrpDtls;
	}

	public Integer getUtTableRuleNbr() {
		return this.utTableRuleNbr;
	}

	public void setUtTableRuleNbr(final Integer utTableRuleNbr) {
		this.utTableRuleNbr = utTableRuleNbr;
	}

	public UtAreaResp getUtAreaResp() {
		return this.utAreaResp;
	}

	public void setUtAreaResp(final UtAreaResp utAreaResp) {
		this.utAreaResp = utAreaResp;
	}

	public UtDataLocation getUtDataLocation() {
		return this.utDataLocation;
	}

	public void setUtDataLocation(final UtDataLocation utDataLocation) {
		this.utDataLocation = utDataLocation;
	}

	public UtTableRule getUtTableRule() {
		return this.utTableRule;
	}

	public void setUtTableRule(final UtTableRule utTableRule) {
		this.utTableRule = utTableRule;
	}

	public UtQuery getUtQuery() {
		return this.utQuery;
	}

	public void setUtQuery(final UtQuery utQuery) {
		this.utQuery = utQuery;
	}

	public String getMsgId() {
		return this.msgId;
	}

	public void setMsgId(final String msgId) {
		this.msgId = msgId;
	}

	public String getSqlText() {
		return this.sqlText;
	}

	public void setSqlText(final String sqlText) {
		this.sqlText = sqlText;
	}

	public String getMsgDescr() {
		return this.msgDescr;
	}

	public void setMsgDescr(final String msgDescr) {
		this.msgDescr = msgDescr;
	}

	public String getRuleType() {
		return this.ruleType;
	}

	public void setRuleType(final String ruleType) {
		this.ruleType = ruleType;
	}

	public String getDataSrcNmSrc() {
		return this.dataSrcNmSrc;
	}

	public void setDataSrcNmSrc(final String dataSrcNmSrc) {
		this.dataSrcNmSrc = dataSrcNmSrc;
	}

	public String getDataSrcNmDest() {
		return this.dataSrcNmDest;
	}

	public void setDataSrcNmDest(final String dataSrcNmDest) {
		this.dataSrcNmDest = dataSrcNmDest;
	}

	public Integer getMaxQuerySec() {
		return this.maxQuerySec;
	}

	public void setMaxQuerySec(final Integer maxQuerySec) {
		this.maxQuerySec = maxQuerySec;
	}

	public String getSevereRuleFlg() {
		return this.severeRuleFlg;
	}

	public void setSevereRuleFlg(final String severeRuleFlg) {
		this.severeRuleFlg = severeRuleFlg;
	}

	public String getShortDescr() {
		return this.shortDescr;
	}

	public void setShortDescr(final String shortDescr) {
		this.shortDescr = shortDescr;
	}

	public String getExceptionTypeCd() {
		return this.exceptionTypeCd;
	}

	public void setExceptionTypeCd(final String exceptionTypeCd) {
		this.exceptionTypeCd = exceptionTypeCd;
	}

	public String getDispCdEnum() {
		return this.dispCdEnum;
	}

	public void setDispCdEnum(final String dispCdEnum) {
		this.dispCdEnum = dispCdEnum;
	}

	public Integer getLogLvl() {
		return this.logLvl;
	}

	public void setLogLvl(final Integer logLvl) {
		this.logLvl = logLvl;
	}

	public Set<UtTableRuleParm> getUtTableRuleParms() {
		return this.utTableRuleParms;
	}

	public void setUtTableRuleParms(final Set<UtTableRuleParm> utTableRuleParms) {
		this.utTableRuleParms = utTableRuleParms;
	}

	public Set<UtTableRuleHist> getUtTableRuleHistsForUtTableRuleNbr() {
		return this.utTableRuleHistsForUtTableRuleNbr;
	}

	public void setUtTableRuleHistsForUtTableRuleNbr(
			final Set<UtTableRuleHist> utTableRuleHistsForUtTableRuleNbr) {
		this.utTableRuleHistsForUtTableRuleNbr = utTableRuleHistsForUtTableRuleNbr;
	}

	public Set<UtTableRuleHist> getUtTableRuleHistsForUtTableRuleNbrExclude() {
		return this.utTableRuleHistsForUtTableRuleNbrExclude;
	}

	public void setUtTableRuleHistsForUtTableRuleNbrExclude(
			final Set<UtTableRuleHist> utTableRuleHistsForUtTableRuleNbrExclude) {
		this.utTableRuleHistsForUtTableRuleNbrExclude = utTableRuleHistsForUtTableRuleNbrExclude;
	}

	public Set<UtTableRuleRptSum> getUtTableRuleRptSums() {
		return this.utTableRuleRptSums;
	}

	public void setUtTableRuleRptSums(
			final Set<UtTableRuleRptSum> utTableRuleRptSums) {
		this.utTableRuleRptSums = utTableRuleRptSums;
	}

	public Set<UtTableRowMsg> getUtTableRowMsgs() {
		return this.utTableRowMsgs;
	}

	public void setUtTableRowMsgs(final Set<UtTableRowMsg> utTableRowMsgs) {
		this.utTableRowMsgs = utTableRowMsgs;
	}

	public Set<UtTableRule> getUtTableRules() {
		return this.utTableRules;
	}

	public void setUtTableRules(final Set<UtTableRule> utTableRules) {
		this.utTableRules = utTableRules;
	}

	public Set<UtRuleGrpDtl> getUtRuleGrpDtls() {
		return this.utRuleGrpDtls;
	}

	public void setUtRuleGrpDtls(final Set<UtRuleGrpDtl> utRuleGrpDtls) {
		this.utRuleGrpDtls = utRuleGrpDtls;
	}

}
