//package org.javautil.core;
//import org.javautil.collections.ArrayComparatorTest;
//import org.javautil.collections.TupleTest;
//import org.javautil.conditionidentification.ConditionIdentificationTest;
//import org.javautil.core.csv.CSVWriterTest;
//import org.javautil.core.sql.DatasourceFactoryH2Test;
//import org.javautil.core.sql.DatasourceFactoryTest;
//import org.javautil.core.sql.DialectTest;
//import org.javautil.core.sql.H2FileDatabaseTest;
//import org.javautil.core.sql.H2MemoryDatabaseExample;
//import org.javautil.core.sql.NamedSqlStatementTest;
//import org.javautil.core.sql.SqlRunnerTest;
//import org.javautil.core.sql.SqlStatementTest;
//import org.javautil.core.text.AsStringTest;
//import org.javautil.core.text.CSVReaderTest;
//import org.javautil.core.text.CSVTokenizerTest;
//import org.javautil.core.text.CommandLineTokenizerTest;
//import org.javautil.core.text.FormatTest;
//import org.javautil.core.text.MultlineStringBuilderTest;
//import org.javautil.core.text.SimpleDateFormatterTest;
//import org.javautil.core.text.StringHelperTest;
//import org.javautil.core.text.TabExpanderTest;
//import org.javautil.core.text.WordFrequencyTest;
//import org.javautil.core.tree.ForestBuilderTest;
//import org.javautil.core.tree.TreeBuilderTest;
//import org.javautil.core.tree.TreeHelperTest;
//import org.javautil.csv.TabTokenizerTest;
//import org.javautil.dataset.ColumnMetaMapTest;
//import org.javautil.dataset.ColumnMetadataCsvMarshallerTest;
//import org.javautil.dataset.ColumnMetadataGrouperTest;
//import org.javautil.dataset.ColumnMetadataTest;
//import org.javautil.dataset.DataSet2Test;
//import org.javautil.dataset.DistinctTest;
//import org.javautil.dataset.GroupByTest;
//import org.javautil.dataset.MappedDatasetRowTest;
//import org.javautil.dataset.MatrixDatasetTest;
//import org.javautil.dataset.MatrixModificationNoSortTest;
//import org.javautil.dataset.MatrixModificationSortTest;
//import org.javautil.dataset.csv.DatasetCsvMetadataMarshallerTest;
//import org.javautil.dataset.csv.DatasetCsvUnmarshallerTest;
//import org.javautil.dataset.csv.DatasetMarshallerWithMetadataTest;
//import org.javautil.dataset.csv.DatasetMetadataCsvUnmarshallerTest;
//import org.javautil.dataset.render.HtmlTableDatasetRendererTest;
//import org.javautil.document.BreakHelperTest;
//import org.javautil.document.layout.IncrementalDocumentRendererTest;
//import org.javautil.document.style.ColorUtilTest;
//import org.javautil.document.style.HorizontalAlignmentTest;
//import org.javautil.document.style.SimpleBorderTest;
//import org.javautil.document.style.StyleImplTest;
//import org.javautil.field.object.DateObjectDefinitionTest;
//import org.javautil.file.InputStreamComparatorTest;
//import org.javautil.h2.H2DropAllObjectsTest;
//import org.javautil.io.ArchiveFileUtilsTest;
//import org.javautil.io.FileUtilTest;
//import org.javautil.io.FiltePathHelperTest;
//import org.javautil.io.ResourceHelperTest;
//import org.javautil.io.StringFileWriterTest;
//import org.javautil.lang.ArrayHelperTest;
//import org.javautil.lang.BigDecimalCoercerTest;
//import org.javautil.lang.ExceptionListExceptionTest;
//import org.javautil.lang.ThreadHelperTest;
//import org.javautil.lang.reflect.ClassCacheEntryTest;
//import org.javautil.mp3.WordExtractorImplTest;
//import org.javautil.properties.BooleanPropertyHelperTest;
//import org.javautil.properties.IntegerPropertyHelperTest;
//import org.javautil.recordvalidation.FieldTypeTest;
//import org.javautil.recordvalidation.UnformattedSignedIntegerFieldTypeTest;
//import org.javautil.recordvalidation.fieldtype.DateFieldTypeTest;
//import org.javautil.security.CryptoTest;
//import org.javautil.security.PasswordHasherTest;
//import org.javautil.test.StackTraceUtilsTest;
//import org.javautil.util.ConfigurableToStringTest;
//import org.javautil.util.DateFactoryTest;
//import org.javautil.util.DateFormatTest;
//import org.javautil.util.DateHelperTest;
//import org.javautil.util.DayTest;
//import org.javautil.util.MapSetTest;
//import org.javautil.util.MathUtilTest;
//import org.javautil.util.NullCompareTest;
//import org.javautil.util.ReflectUtilTest;
//import org.javautil.util.ShaHasherTest;
//import org.javautil.util.TestBase64Coder;
//import org.javautil.xml.XmlRendererTest;
//import org.junit.runner.RunWith;
//import org.junit.runners.Suite;
//
//@RunWith(Suite.class)
//
//@Suite.SuiteClasses({
////	AbstractTableRendererTest.class,
////	ApplicationPropertiesDataSourceTest.class,
//	AppTest.class,
//	ArchiveFileUtilsTest.class,
////	ArchiveTest.class,
//	ArrayComparatorTest.class,
//	ArrayHelperTest.class,
//	AsStringTest.class,
////	BaseTest.class,
//	BigDecimalCoercerTest.class,
//	BooleanPropertyHelperTest.class,
//	BreakHelperTest.class,
////	Class1.class,
//	ClassCacheEntryTest.class,
//
//	ColorUtilTest.class,
//	ColumnMetadataCsvMarshallerTest.class,
//	ColumnMetadataGrouperTest.class,
//	ColumnMetadataTest.class,
//	ColumnMetaMapTest.class,
//	CommandLineTokenizerTest.class,
//	ConditionIdentificationTest.class,
//	ConfigurableToStringTest.class,
////	ConfigurableToStringTestData.class,
////	ConvictionsDataset.class,
////	CrosstabDatasetTest.class,
//	CryptoTest.class,
//	CSVReaderTest.class,
////	CsvResourceReaderTest.class,
//	CSVTokenizerTest.class,
//	CSVTokenizerTest.class,
//	CsvWriterTest.class,
//	DataSet2Test.class,
//	DatasetCsvMetadataMarshallerTest.class,
//	DatasetCsvUnmarshallerTest.class,
//	//DatasetMarshallerTest.class,
//	DatasetMarshallerWithMetadataTest.class,
//	DatasetMetadataCsvUnmarshallerTest.class,
////	DatasetSource.class,
//	DatasourceFactoryTest.class,
//	DatasourceFactoryH2Test.class,
//	DateFactoryTest.class,
//	DateFieldTypeTest.class,
//	DateFormatTest.class,
//	DateHelperTest.class,
//	DateObjectDefinitionTest.class,
//	DayTest.class,
//	DialectTest.class,
//	DistinctTest.class,
//	ExceptionListExceptionTest.class,
////	ExtendedSalesDataset.class,
////	FeesDataset.class,
//	//FieldHelperTest.class,
//	FieldTypeTest.class,
//
//	FileUtilTest.class,
//	FiltePathHelperTest.class,
//	ForestBuilderTest.class,
//	FormatTest.class,
//	//GenerateRevengTest.class,  // TODO requires oracle running
//	GroupByTest.class,
//	H2DropAllObjectsTest.class,
//	H2FileDatabaseTest.class,
//	H2MemoryDatabaseExample.class,
//	HorizontalAlignmentTest.class,
//	HtmlTableDatasetRendererTest.class,
//	//IncomparableTrailingNullsDataset.class,
//	IncrementalDocumentRendererTest.class,
//	InputStreamComparatorTest.class,
//	IntegerPropertyHelperTest.class,
////	IOUtilsTest.class,
//	//ListOfMapsDatasetTest.class,
//	MappedDatasetRowTest.class,
//	//MappedResultSetIteratorTest.class,
//	MapSetTest.class,
//	MathUtilTest.class,
//	MatrixDatasetTest.class,
//	MatrixModificationNoSortTest.class,
//	MatrixModificationSortTest.class,
//	MultlineStringBuilderTest.class,
//	NamedSqlStatementTest.class,
//	NullCompareTest.class,
//	PasswordHasherTest.class,
//	ReflectUtilTest.class,
//	ResourceHelperTest.class,
//	//ResultValidator.class,
//	//SeedSalesReportingDatabase.class,
//	ShaHasherTest.class,
//	SimpleBorderTest.class,
//	SimpleDateFormatterTest.class,
//	//SimpleTreeNode.class,
//	//SimpleTreeNodeList.class,
//	//SqlCsvExporterCLITest.class,  // TODO requires oracle running
//	SqlRunnerTest.class,
////	SqlSplitterTest2.class,
////	SqlSplitterTest.class,
//	SqlStatementTest.class,
//	StackTraceUtilsTest.class,
////	StaticData.class,
//	StringFileWriterTest.class,
//	StringHelperTest.class,
//
//	StyleImplTest.class,
//
//	TabExpanderTest.class,
//	TabTokenizerTest.class,
//	TestBase64Coder.class,
//	//TestBean.class,
//	//TestData.class,
//	ThreadHelperTest.class,
//	//TicketsDataset.class,
//	//TrailingNullsDataset.class,
//	TreeBuilderTest.class,
//	TreeHelperTest.class,
//	TupleTest.class,
//	UnformattedSignedIntegerFieldTypeTest.class,
//	WordExtractorImplTest.class,
//	WordFrequencyTest.class,
//	XmlRendererTest.class,
//
//})
//
//public class TestSuite {   
//}  	