--------------------------------------------------------
--  DDL for Table AP_INV_DTL
--------------------------------------------------------

  CREATE TABLE "AP_INV_DTL" 
   (	"AP_INV_DTL_NBR" NUMBER(9,0), 
	"AP_INV_HDR_NBR" NUMBER(9,0), 
	"LINE_NBR" NUMBER(3,0), 
	"PO_CD" VARCHAR2(20), 
	"PO_LINE_HDR_NBR" NUMBER(9,0), 
	"LINE_NBR_PO" NUMBER(3,0), 
	"VNDR_ORD_CD" VARCHAR2(30), 
	"VNDR_ORD_LINE_CD" VARCHAR2(5), 
	"ITEM_NBR" NUMBER(9,0), 
	"ITEM_CD" VARCHAR2(50), 
	"ITEM_DESCR" VARCHAR2(50), 
	"REPLEN_UM" VARCHAR2(3), 
	"QTY_RECV" NUMBER(13,5), 
	"QTY_RECV_STK_UM" NUMBER(13,5), 
	"RCPT_DT" DATE, 
	"SHIP_VIA_CD" VARCHAR2(8), 
	"ORG_NBR_MFR" NUMBER(9,0), 
	"ORG_CD_MFR" VARCHAR2(15), 
	"ORG_NM_MFR" VARCHAR2(60), 
	"UNIT_COST_STK_UM" NUMBER(17,6), 
	"UNIT_COST_DENOM_STK_UM" NUMBER(17,6), 
	"UNIT_COST_REPLEN_UM" NUMBER(17,6), 
	"UNIT_COST_DENOM_REPLEN_UM" NUMBER(17,6), 
	"LOT_NBR" NUMBER(9,0), 
	"APS_SPLY_SUB_POOL_NBR" NUMBER(9,0), 
	"FACILITY" VARCHAR2(16)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 23068672 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
