--------------------------------------------------------
--  DDL for Table AP_INV_HDR_CHARGE
--------------------------------------------------------

  CREATE TABLE "AP_INV_HDR_CHARGE" 
   (	"AP_INV_HDR_CHARGE_NBR" NUMBER(9,0), 
	"AP_INV_HDR_NBR" NUMBER(9,0), 
	"CHARGE_CD" VARCHAR2(10), 
	"CHARGE_AMT" NUMBER(9,2), 
	"CHARGE_AMT_DENOM" NUMBER(9,2), 
	"TAXABLE_FLG" VARCHAR2(1) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
