--------------------------------------------------------
--  DDL for Table AR_INV_DTL_SERIAL
--------------------------------------------------------

  CREATE TABLE "AR_INV_DTL_SERIAL" 
   (	"AR_INV_DTL_NBR" NUMBER(9,0), 
	"SERIAL_CD" VARCHAR2(20), 
	"MFR_SERIAL_CD" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16777216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
