--------------------------------------------------------
--  DDL for Table AR_INV_DTL_06212003
--------------------------------------------------------

  CREATE TABLE "AR_INV_DTL_06212003" 
   (	"AR_INV_DTL_NBR" NUMBER(9,0), 
	"INV_CD" VARCHAR2(20), 
	"LINE_NBR" NUMBER(3,0), 
	"ORD_CD" VARCHAR2(20), 
	"OE_ORD_DTL_NBR" NUMBER(9,0), 
	"LINE_NBR_ORD" NUMBER(3,0), 
	"CUST_PO_CD" VARCHAR2(30), 
	"CUST_LINE_CD" VARCHAR2(5), 
	"ITEM_NBR" NUMBER(9,0), 
	"ITEM_CD" VARCHAR2(50), 
	"ITEM_DESCR" VARCHAR2(50), 
	"SHIP_TO_ADDR_NBR" NUMBER(9,0), 
	"SHIP_TO_ADDR_CD" VARCHAR2(16), 
	"SELL_UM" VARCHAR2(3), 
	"QTY_OPEN" NUMBER(13,5), 
	"QTY_SHIP" NUMBER(13,5), 
	"LOT_NBR" NUMBER(9,0), 
	"ORG_NBR_VND" NUMBER(9,0), 
	"ORG_NM_VND" VARCHAR2(60), 
	"ORG_NBR_MFR" NUMBER(9,0), 
	"ORG_NM_MFR" VARCHAR2(60), 
	"MFR_LOT_CD" VARCHAR2(20), 
	"REV_LVL" VARCHAR2(5), 
	"UNIT_COST_STK_UM" NUMBER(17,6), 
	"UNIT_COST_DENOM_STK_UM" NUMBER(17,6), 
	"UNIT_COST_SELL_UM" NUMBER(17,6), 
	"UNIT_COST_DENOM_SELL_UM" NUMBER(17,6), 
	"UNIT_PRICE_STK_UM" NUMBER(17,6), 
	"UNIT_PRICE_DENOM_STK_UM" NUMBER(17,6), 
	"UNIT_PRICE_SELL_UM" NUMBER(17,6), 
	"UNIT_PRICE_DENOM_SELL_UM" NUMBER(17,6), 
	"TIE_CD" VARCHAR2(1), 
	"CONTRACT_CD" VARCHAR2(8), 
	"CUST_BIN_CD" VARCHAR2(40), 
	"APS_SPLY_SUB_POOL_NBR" NUMBER(9,0), 
	"FACILITY" VARCHAR2(16), 
	"ORG_CD_MFR" VARCHAR2(15), 
	"ORG_CD_VND" VARCHAR2(15), 
	"QTY_OPEN_STK_UM" NUMBER(13,5), 
	"QTY_SHIP_STK_UM" NUMBER(13,5), 
	"BIN_CD" VARCHAR2(16), 
	"IC_CATEGORY_NBR" NUMBER(9,0), 
	"IC_CATEGORY_NM" VARCHAR2(16), 
	"IC_CATEGORY_DESCR" VARCHAR2(60)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
