--------------------------------------------------------
--  DDL for Table AR_INV_DTL_BOX
--------------------------------------------------------

  CREATE TABLE "AR_INV_DTL_BOX" 
   (	"AR_INV_DTL_NBR" NUMBER(9,0), 
	"BOX_CD" VARCHAR2(20), 
	"WH_PICK_DTL_COP_RQST_NBR" NUMBER(9,0), 
	"APS_ALLOC_ONHAND_OO_NBR" NUMBER(9,0), 
	"BOX_QTY" NUMBER(13,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 67108864 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
