--------------------------------------------------------
--  DDL for Table AR_INV_DTL_GL
--------------------------------------------------------

  CREATE TABLE "AR_INV_DTL_GL" 
   (	"AR_INV_DTL_NBR" NUMBER(9,0), 
	"GL_ACCT_CD" VARCHAR2(100), 
	"GL_TRANS_AMT" NUMBER(17,6), 
	"GL_TRANS_DESCR" VARCHAR2(255), 
	"DISTRIB_TYPE" NUMBER(3,0), 
	"CURR_CD" VARCHAR2(3)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 260046848 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
