--------------------------------------------------------
--  DDL for Table AR_RMA_HDR_CHARGE
--------------------------------------------------------

  CREATE TABLE "AR_RMA_HDR_CHARGE" 
   (	"RMA_CD" VARCHAR2(20), 
	"CHARGE_CD" VARCHAR2(8), 
	"CHARGE_AMT" NUMBER(10,2), 
	"CHARGE_AMT_DENOM" NUMBER(10,2), 
	"TAXABLE_FLG" VARCHAR2(1), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
