--------------------------------------------------------
--  DDL for Table AR_SHIP_PAYMENT_METHOD
--------------------------------------------------------

  CREATE TABLE "AR_SHIP_PAYMENT_METHOD" 
   (	"PAYMENT_METHOD_CD" VARCHAR2(3), 
	"PAYMENT_METHOD_DESCR" VARCHAR2(30), 
	"CUST_RESP_FLG" VARCHAR2(1), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_TM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
