--------------------------------------------------------
--  DDL for Table BILL_OF_LADING_HDR
--------------------------------------------------------

  CREATE TABLE "BILL_OF_LADING_HDR" 
   (	"BILL_OF_LADING_NBR" NUMBER(9,0), 
	"ORG_NBR_CUST" NUMBER(9,0), 
	"ORG_CD_CUST" VARCHAR2(16), 
	"ORG_NM_CUST" VARCHAR2(60), 
	"SHIP_TO_ADDR_NBR" NUMBER(9,0), 
	"SHIP_TO_ADDR_CD" VARCHAR2(8), 
	"SHIP_TO_ADDR_DESCR" VARCHAR2(60), 
	"SHIP_TO_ADDR_1" VARCHAR2(30), 
	"SHIP_TO_ADDR_2" VARCHAR2(30), 
	"SHIP_TO_ADDR_3" VARCHAR2(30), 
	"SHIP_TO_CITY" VARCHAR2(25), 
	"SHIP_TO_STATE_CD" VARCHAR2(5), 
	"SHIP_TO_POSTAL_CD" VARCHAR2(10), 
	"SHIP_TO_CNTRY_CD" VARCHAR2(3), 
	"SHIP_VIA_ACCT_CD" VARCHAR2(20), 
	"SHIP_TM" DATE, 
	"SHIP_VIA_CD" VARCHAR2(8), 
	"FOB_CD" VARCHAR2(8), 
	"FRGHT_TERM_CD" VARCHAR2(8), 
	"COD_PAYEE_ID" VARCHAR2(1), 
	"COD_AMT" NUMBER(10,2), 
	"COLLECT_CHG" NUMBER(10,2), 
	"INDIV_NBR_SHIP" NUMBER(9,0), 
	"PICK_UP_INDIV_NM" VARCHAR2(20), 
	"WAYBILL_CD" VARCHAR2(20), 
	"SHIP_MSG" VARCHAR2(80)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;

   COMMENT ON COLUMN "BILL_OF_LADING_HDR"."COD_PAYEE_ID" IS 'C-Consignee, S-Shipper, N-Not Applicable';
