--------------------------------------------------------
--  DDL for Table BWJIT_BIN_SCAN_ERROR_LOCAL
--------------------------------------------------------

  CREATE TABLE "BWJIT_BIN_SCAN_ERROR_LOCAL" 
   (	"BATCH_NO" NUMBER, 
	"ERR_MSG" VARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
