--------------------------------------------------------
--  DDL for Table CAL_DT
--------------------------------------------------------

  CREATE TABLE "CAL_DT" 
   (	"CAL_DT" DATE, 
	"CALENDAR" VARCHAR2(6), 
	"CYCLE" NUMBER(4,0), 
	"INTVL" NUMBER(2,0), 
	"INTVL_PCT" NUMBER(6,3), 
	"WORK_DAY_FLG" VARCHAR2(1), 
	"PRD_START_DT" DATE, 
	"CAL_QTR" NUMBER(1,0), 
	"WORK_DAY_NBR" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
