--------------------------------------------------------
--  DDL for Table CM_AP_DTL_TAX
--------------------------------------------------------

  CREATE TABLE "CM_AP_DTL_TAX" 
   (	"CM_AP_DTL_NBR" NUMBER(9,0), 
	"TAX_CD" VARCHAR2(16), 
	"TAX_AMT" NUMBER(11,2), 
	"TAX_AMT_DENOM" NUMBER(11,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
