--------------------------------------------------------
--  DDL for Table CURRENCY_EXCHG_RATE
--------------------------------------------------------

  CREATE TABLE "CURRENCY_EXCHG_RATE" 
   (	"CURR_CD" VARCHAR2(3), 
	"EFF_DT_START" DATE, 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"EXCHG_RATE" NUMBER(20,10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
