--------------------------------------------------------
--  DDL for Table DN_AP_DTL_GL
--------------------------------------------------------

  CREATE TABLE "DN_AP_DTL_GL" 
   (	"DN_AP_DTL_NBR" NUMBER(9,0), 
	"GL_ACCT_CD" VARCHAR2(50), 
	"GL_TRANS_AMT" NUMBER(17,6), 
	"CURR_CD" VARCHAR2(3), 
	"DISTRIB_TYPE" NUMBER(3,0), 
	"GL_TRANS_DESCR" VARCHAR2(255)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
