--------------------------------------------------------
--  DDL for Table EDI_INBOUND_CTL
--------------------------------------------------------

  CREATE TABLE "EDI_INBOUND_CTL" 
   (	"EDI_SRC_CD" VARCHAR2(20), 
	"EDI_FILE_PATH" VARCHAR2(255), 
	"EDI_FILE_MASK" VARCHAR2(127), 
	"EDI_PARSER_CLASSNAME" VARCHAR2(255), 
	"EDI_LOAD_PROCEDURE_NM" VARCHAR2(61), 
	"EDI_ORG_NBR_TRADING_PARTNER" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
