--------------------------------------------------------
--  DDL for Table EDI_BIN_SCAN_BATCH
--------------------------------------------------------

  CREATE TABLE "EDI_BIN_SCAN_BATCH" 
   (	"EDI_BIN_SCAN_BATCH_NBR" NUMBER(9,0), 
	"BATCH_LOAD_DT" DATE, 
	"BATCH_STAT_ID" VARCHAR2(1), 
	"BATCH_PROCESS_DT" DATE, 
	"UT_USER_NBR_PROCESS" NUMBER(9,0), 
	"BIN_SCAN_FILE_PATH" VARCHAR2(512), 
	"BIN_SCAN_FILE_ARCHIVE_PATH" VARCHAR2(512)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;

   COMMENT ON COLUMN "EDI_BIN_SCAN_BATCH"."BATCH_STAT_ID" IS 'O-Open, C-CLosed, E-Errors';
