--------------------------------------------------------
--  DDL for Table FC_ATTR
--------------------------------------------------------

  CREATE TABLE "FC_ATTR" 
   (	"FC_ATTR_NBR" NUMBER(9,0), 
	"ATTR_NM" VARCHAR2(16), 
	"ATTR_DESCR" VARCHAR2(60), 
	"ATTR_SEQ" NUMBER(3,0), 
	"REQR_FLG" VARCHAR2(1), 
	"ATTR_CONSTR_FLG" VARCHAR2(1), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
