--------------------------------------------------------
--  DDL for Table FC_CYCLE
--------------------------------------------------------

  CREATE TABLE "FC_CYCLE" 
   (	"CALENDAR" VARCHAR2(6), 
	"CYCLE" NUMBER(4,0), 
	"BEG_DT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
