--------------------------------------------------------
--  DDL for Table FC_INTVL
--------------------------------------------------------

  CREATE TABLE "FC_INTVL" 
   (	"CALENDAR" VARCHAR2(6), 
	"CYCLE" NUMBER(4,0), 
	"INTVL" NUMBER(2,0), 
	"PRD_BEG" NUMBER(2,0), 
	"PRD_END" NUMBER(2,0), 
	"INTVL_NAME" VARCHAR2(20), 
	"INTVL_NBR" NUMBER(6,0), 
	"PRD_NBR_BEG" NUMBER(6,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
