--------------------------------------------------------
--  DDL for Table FC_PRD
--------------------------------------------------------

  CREATE TABLE "FC_PRD" 
   (	"CALENDAR" VARCHAR2(6), 
	"CYCLE" NUMBER(4,0), 
	"PRD" NUMBER(2,0), 
	"BEG_DT" DATE, 
	"INTVL_NBR" NUMBER(6,0), 
	"INTVL_NBR_1" NUMBER(8,0), 
	"INTVL_NBR_2" NUMBER(8,0), 
	"INTVL_PCT_1" NUMBER(4,1), 
	"INTVL_PCT_2" NUMBER(4,1), 
	"PRD_NBR" NUMBER(8,0), 
	"INTVL" NUMBER(2,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
