--------------------------------------------------------
--  DDL for Table FC_PRD_DT
--------------------------------------------------------

  CREATE TABLE "FC_PRD_DT" 
   (	"PRD_DT" DATE, 
	"CYCLE" NUMBER(4,0), 
	"PRD" NUMBER(2,0), 
	"INTVL_NBR" NUMBER(6,0), 
	"PRD_NBR" NUMBER(10,0), 
	"CALENDAR" VARCHAR2(6), 
	"CAPACITY" NUMBER(10,2), 
	"INTVL" NUMBER(2,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
