--------------------------------------------------------
--  DDL for Table FCST_GRP_BACKUP
--------------------------------------------------------

  CREATE TABLE "FCST_GRP_BACKUP" 
   (	"FCST_GRP" VARCHAR2(8), 
	"FCST_GRP_DESCR" VARCHAR2(60), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"OO_PRTY" NUMBER(2,0), 
	"WO_PRTY" NUMBER(2,0), 
	"SS_PRTY" NUMBER(2,0), 
	"FC_PRTY" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
