--------------------------------------------------------
--  File created - Saturday-January-25-2020   
--------------------------------------------------------
@/common/home/jjs/java-projects/aerodemo/interfast/AGING_INVT_SHIP_VAL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AGING_INVT_VAL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APP_CTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_ALLOC_DELETE_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_ALLOC_ONHAND_FC.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_ALLOC_ONHAND_OO.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_ALLOC_ONHAND_SS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_ALLOC_ONHAND_WO.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_ALLOC_REPLEN_FC.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_ALLOC_REPLEN_OO.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_ALLOC_REPLEN_SS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_ALLOC_REPLEN_WO.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_ALLOC_WO_FC.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_ALLOC_WO_OO.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_ALLOC_WO_SS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_ALLOC_WO_WO.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_CTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_DMD_RULE_SET_ITEM.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_ITEM_GLOBAL_SUBST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_ITEM_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_PLAN_GRP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_RESULT_DTL_DEL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_RESULT_DTL_DMD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_RESULT_DTL_SPLY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_RQST_QUEUE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SCENARIO.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SPLY_FACILITY_ITEM.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SPLY_POOL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SPLY_SUB_POOL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SPLY_SUB_POOL_AUTH.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SRC_RULE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SRC_RULE_BACKUP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SRC_RULE_SET.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SRC_RULE_SET_BACKUP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SRC_RULE_SET_XX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SRC_RULE_XX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SUMMARY_DAT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SUMMARY_DAT_AMT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SUMMARY_DAT_FC.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SUMMARY_DAT_OO.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SUMMARY_DAT_PO.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SUMMARY_DAT_SS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SUMMARY_DAT_WO_DMD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/APS_SUMMARY_DAT_WO_SPLY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AP_INV_BATCH.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AP_INV_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AP_INV_DTL_CHARGE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AP_INV_DTL_GL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AP_INV_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AP_INV_HDR_CHARGE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AP_INV_HDR_GL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AP_INV_HDR_INTEGRATION_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/ARDD_TMP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_FRGHT_TERM.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_BATCH.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_DTL_06212003.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_DTL_06252003_AFTER.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_DTL_06252003_BEFORE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_DTL_BOX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_DTL_CHARGE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_DTL_GL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_DTL_SERIAL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_HDR_06212003.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_HDR_06252003_AFTER.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_HDR_06252003_BEFORE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_HDR_CHARGE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_HDR_FRGHT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_HDR_GL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_HDR_INTEGRATION_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_HDR_TAX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_INV_NOTIFY_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_PAYMENT_RCPT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_PAYMENT_RCPT_APPLY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_RMA_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_RMA_DTL_CHARGE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_RMA_DTL_GL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_RMA_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_RMA_HDR_CHARGE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_RMA_HDR_GL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_RMA_HDR_INTEGRATION_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_RMA_HDR_TAX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_RMA_RCPT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_RMA_RCPT_SERIAL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_RMA_REASON.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_SHIP_PAYMENT_METHOD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/AR_UNPLANNED_RMA.sql
@/common/home/jjs/java-projects/aerodemo/interfast/BILL_OF_LADING_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/BILL_OF_LADING_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/BILL_OF_LADING_INV.sql
@/common/home/jjs/java-projects/aerodemo/interfast/BRAD_WORK_ORD_TMP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/BWJIT_BIN_SCAN_ERROR_LOCAL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/CAL_CALENDAR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/CAL_DT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/CM_AP_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/CM_AP_DTL_GL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/CM_AP_DTL_TAX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/CM_AP_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/CM_AP_HDR_INTEGRATION_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/CM_AR_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/CM_AR_DTL_GL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/CM_AR_DTL_TAX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/CM_AR_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/CM_AR_HDR_INTEGRATION_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/CM_REASON_CODES.sql
@/common/home/jjs/java-projects/aerodemo/interfast/CURRENCY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/CURRENCY_EXCHG_RATE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/CUSTOMER_PRICE_GRP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/CYCLE_CNT_RULE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/CYC_ITEM_NOT_ACTIVE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DATE_DIFF.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DEBUG_TABLE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DEMO_CUSTOMERS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DEMO_ORDERS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DEMO_ORDER_ITEMS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DEMO_PAGE_HIERARCHY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DEMO_PRODUCT_INFO.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DEMO_STATES.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DEMO_USERS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DEPT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DN_AP_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DN_AP_DTL_GL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DN_AP_DTL_TAX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DN_AP_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DN_AP_HDR_INTEGRATION_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DN_AR_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DN_AR_DTL_GL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DN_AR_DTL_TAX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DN_AR_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DN_AR_HDR_INTEGRATION_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DN_REASON_CODES.sql
@/common/home/jjs/java-projects/aerodemo/interfast/DUP_BINSCAN_NOTIFY_LOCAL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/EDI_BIN_SCAN_BATCH.sql
@/common/home/jjs/java-projects/aerodemo/interfast/EDI_BIN_SCAN_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/EDI_INBOUND_CTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/EMAIL_GROUP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/EMP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FCST_GRP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FCST_GRP_BACKUP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FCST_GRP_XX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_ADJ.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_ADJ_OLD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_ATTR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_ATTR_VAL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_BUILD_RATE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_BUILD_RATE_GRP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_CAT_ADJ.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_CTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_CYCLE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_FCST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_FCST_MDL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_FCST_MDL_GRP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_FCST_MDL_GRP_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_HIST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_INTVL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_INTVL_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_ITEM_ATTR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_ITEM_DFLT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_ITEM_FCST_MDL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_ITEM_MAST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_ITEM_MAST_XX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_PRD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_PRD_DT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FC_QUEUE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/FOB.sql
@/common/home/jjs/java-projects/aerodemo/interfast/GEO_COUNTRY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/GEO_POSTAL_CODES.sql
@/common/home/jjs/java-projects/aerodemo/interfast/GEO_STATE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/GL_TAX_GRP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/GL_TAX_GRP_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/GL_TERMS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/GL_TERMS_TXT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ADJ_CD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ATTR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ATTR_VAL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_BIN.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_BIN_BAK.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_BOM.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_BOM_CERT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_CATEGORY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_CATEGORY_ATTR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_CATEGORY_AUTH.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_CATEGORY_NARR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_CAT_DISC.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_CERT_CD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_DUTY_RATE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_HARMONIZED_CODE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_INVENTORY_SNAPSHOT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_ATTR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_BRAD_CYC.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_COST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_COST_TYPE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_CUST_SUBST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_LOC.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_LOC_BOX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_LOC_XX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_MAST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_MAST_CERT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_MAST_EQUIV.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_MAST_NOMEN.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_MAST_REL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_MAST_TMP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_MAST_UPD_QUEUE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_MFG_PATH.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_NARR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_OPERATION_YIELD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_PRICE_MATRIX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_PRICE_MATRIX_LOAD_ERR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_RESTRICT_CUST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_REV_LVL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_REV_LVL_APPLY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_SER.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_SER_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_STAT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_ITEM_VND_COST_MATRIX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_KIT_MAST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_LOT_COST_HIST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_LOT_IMAGE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_LOT_MAST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_LOT_MAST_BOUND.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_LOT_MAST_CERT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_LOT_MAST_CERT_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_LOT_MAST_COST_UPDT_XX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_LOT_MAST_PO_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_MULTIPLE_CERT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_RECV_RULE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_SUMMARY_DAT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_SUMMARY_DAT_PLAN.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_TOTE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_TRANS_GL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_TRANS_GL_20031015.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_TRANS_GL_ACCT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_TRANS_GL_ACCT_20031015.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_TRANS_GL_INTEGRATION_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_TRANS_HIST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_UM.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_UM_CNVT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_UM_CNVT_ITEM.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_UM_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_VND_ONHAND.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_WHSE_ZONE_GRP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_WHSE_ZONE_GRP_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IC_WHSE_ZONE_XX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IDENTIFIED_LOT_SCAN_TMP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/ILM_BOGUS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/ILM_BOGUS2.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IMG_IMAGE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IMG_IMAGE_SET_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IMG_IMAGE_SET_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/IMG_SCAN_BATCH.sql
@/common/home/jjs/java-projects/aerodemo/interfast/JIT_ERR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/JIT_TRANSACTIONS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/JIT_TRANS_BATCH.sql
@/common/home/jjs/java-projects/aerodemo/interfast/MFG_OPERATION.sql
@/common/home/jjs/java-projects/aerodemo/interfast/MFG_PATH.sql
@/common/home/jjs/java-projects/aerodemo/interfast/MFG_PATH_OPERATION.sql
@/common/home/jjs/java-projects/aerodemo/interfast/MFG_WORK_STATION.sql
@/common/home/jjs/java-projects/aerodemo/interfast/MFG_WORK_STATION_OPERATION.sql
@/common/home/jjs/java-projects/aerodemo/interfast/MV_BIGTAB.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ADDR_TAX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_CATEGORY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_CUST_ATTR_REQ.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_EMAIL_TYPE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_INDIV.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_INDIV_ADDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_INDIV_CATEGORY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_INDIV_EMAIL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_INDIV_PHN.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_INDIV_TYPE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ORG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ORG_ADDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ORG_ADDR_CONTACT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ORG_ADDR_RPT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ORG_ADDR_SHIP_VIA_ACCT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ORG_ADDR_TYPE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ORG_ATTR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ORG_ATTR_MAST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ORG_ATTR_VAL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ORG_CATEGORY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ORG_DEPT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ORG_DEPT_INDIV.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ORG_GRP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ORG_INDIV.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ORG_INDIV_ADDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ORG_PHN.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ORG_SHIP_NOTIFY_CUST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_ORG_TYPE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_PHN_TYPE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_SALUTATION.sql
@/common/home/jjs/java-projects/aerodemo/interfast/NA_VND_ATTR_REQ.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CANCEL_CD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CLOSE_REASON.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CONTRACT_ITEM.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CONTRACT_ITEM_CERT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CONTRACT_ITEM_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CONTRACT_PRICE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CREDIT_CARD_INFO.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CUST_BIN.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CUST_BIN_CERT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CUST_BIN_GRP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CUST_BIN_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CUST_BIN_XX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CUST_CONTRACT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CUST_GRP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CUST_MAST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CUST_MAST_CERT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CUST_MAST_SHIP_VIA_ACCT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CUST_MFR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CUST_PRICE_GRP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CUST_PRICE_GRP_CAT_DISC.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_CUST_PRICE_GRP_DISC.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_HOLD_AUTH.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_HOLD_AUTO_REL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_HOLD_CD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_HOLD_CD_AUTH.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_HOLD_CD_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_HOLD_LINE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_HOLD_ORD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_HOLD_REL_LINE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_HOLD_REL_ORD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_LIST_PRICE_OLD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_MISC_CHG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_ORD_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_ORD_DTL_CERT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_ORD_DTL_CHARGE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_ORD_DTL_DUMMY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_ORD_DTL_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_ORD_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_ORD_HDR_CHARGE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_ORD_HDR_DUMMY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_ORD_TYPE_CD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_PART_MISMATCH_REASON.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_PRICE_POLICY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_PRICE_POLICY_CURR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_SALES_REGION.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_SALES_REGION_INDIV.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_SALES_TERR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OE_SALES_TERR_INDIV.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OOD1.sql
@/common/home/jjs/java-projects/aerodemo/interfast/OOH1.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PLAN_PO.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PLUS_ITEM.sql
@/common/home/jjs/java-projects/aerodemo/interfast/POS_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/POS_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_AUTH_INDIV.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_AUTH_INDIV_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_BUY_REASON.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_CANCEL_CD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_CLOSE_REASON.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_LINE_CHARGE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_LINE_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_LINE_DTL_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_LINE_DTL_XX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_LINE_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_LINE_HDR_CERT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_LINE_MULTIPLE_CERT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_MFR_MAST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_MISC_CHG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_ORD_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_ORD_HDR_AUTH.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_ORD_HDR_CHARGE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_RESCHED.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_STD_NOTE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_UNPLANNED_RCPT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_UNPLANNED_RCPT_CERT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_UNPLANNED_RCPT_SERIAL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_VND_MAST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_VND_MAST_SHIP_VIA_ACCT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_VND_SET_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/PO_VND_SET_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_ATTR_VAL_MFR_STATE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_ATTR_VAL_STATE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_ATTR_VAL_VND_STATE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_CALIBRATE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_CALIBRATE_HIST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_CONTRACT_APPRV_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_CONTRACT_APPRV_MFR_LOT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_CONTRACT_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_CUST_RTRN.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_CUST_SPLY_SUB_POOL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_ERR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_INSPECTOR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_MFR_APPRV.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_PROJ_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_REJECT_CODES.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_RTRN_DISP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_RTRN_REASON.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_SAMPLE_RULE_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_SAMPLE_RULE_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_TST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_TST_GRP_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_TST_GRP_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_TST_RSLT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_TST_STE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_TST_STE_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_TST_STE_PLAN.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_TST_STE_PLAN_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_TST_STE_VND.sql
@/common/home/jjs/java-projects/aerodemo/interfast/QA_VND_REJECT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/SALES_CALL_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/SALES_CALL_OBSTACLES.sql
@/common/home/jjs/java-projects/aerodemo/interfast/SALES_CALL_SUMMARY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/SALES_LEAD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/SERVICE_RQST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/SERVICE_RQST_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/SERVICE_RQST_PARMS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/SHIP_NOTIFY_ERROR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/SHIP_NOTIFY_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/SHIP_VIA.sql
@/common/home/jjs/java-projects/aerodemo/interfast/SQ_LOST_CODES.sql
@/common/home/jjs/java-projects/aerodemo/interfast/SQ_LOST_CODES_TXT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/SQ_QTE_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/SQ_QTE_DTL_CERT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/SQ_QTE_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/SQ_QTE_PRICE_BASIS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/SQ_QTE_TEST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TEST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TEST_055299.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TEST_067500.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TEST_INV.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TEST_ITEM.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TEST_SHIP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TEST_SHIP_OTHER.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TMP_APS_ALLOC_ONHAND_OO.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TMP_APS_RESULT_DTL_DMD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TMP_APS_RESULT_DTL_SPLY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TMP_FACILITY_TRANS_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TMP_IC_LOT_MAST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TMP_ITEM.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TMP_LOT_MAST_OLD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TMP_OE_ORD_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TMP_OE_ORD_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TMP_OE_ORD_HDR_NBR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TMP_PO_LINE_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TMP_PO_LINE_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/TMP_WO_RELEASE_UNIT_QTY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UNBRAKO_ORD_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UNBRAKO_ORD_DTL_CERT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UNBRAKO_ORD_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UNBRAKO_ORD_HDR_CHARGE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UNBRAKO_SHIP_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UNBRAKO_TRANS_BATCH.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UNBRAKO_TRANS_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UNBRAKO_TRANS_RQST_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UNBRAKO_TRANS_RQST_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UPC_ITEMS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UPC_QTY_FIX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UPC_QTY_FIX_ITEM.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_CACHE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_COLUMN.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_ERR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_FACILITY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_FACILITY_ADDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_FACILITY_AUTH.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_FACILITY_PRINTER.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_FACILITY_PRINTER_USE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_FORM.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_FORM_FUNCTION.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_FORM_FUNCTION_LOAD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_FORM_FUNCTION_ROLE_PRIV.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_FORM_LOAD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_FORM_MENU.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_FORM_ROLE_PRIV.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_FORM_TABS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_FORM_TAB_BLOCKS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_FORM_TOOLTIP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_LABEL_CLASS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_LABEL_CLASS_ARG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_LABEL_TYPE_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_LOCALE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_NOTE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_NOTE_TABLE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_NOTE_TYPE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_PRINTER_MODEL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_PRINTER_USE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_PROCEDURE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_PROCEDURE_LOAD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_PROCEDURE_ROLE_PRIV.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_ROLE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_TABLE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_TABLE_COLUMNS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_TABLE_LOAD.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_TABLE_ROLE_PRIV.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_USER.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_USER_DOC_VIEW_LIST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_USER_FACILITY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/UT_USER_ROLE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/VND_RTRN_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/VND_RTRN_DTL_GL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/VND_RTRN_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/VND_RTRN_HDR_INTEGRATION_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/VQ_LOST_CODES.sql
@/common/home/jjs/java-projects/aerodemo/interfast/VQ_QTE_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/VQ_QTE_DTL_CERT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/VQ_QTE_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/VQ_QTE_MULTIPLE_CERT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/VQ_QTE_TEST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WATCH_FLG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WEB_CTRL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WEB_QTE_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_CONTAINER.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_CONTAINER_BOX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_CYCLE_CNT_BATCH.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_CYCLE_CNT_RQST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_FACILITY_SHIP_VIA_PICK.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_FACILITY_TRANS_LOG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_FACILITY_TRANS_ONHAND.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_FACILITY_TRANS_REPLEN.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_FACILITY_TRANS_SHIP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_FACILITY_TRANS_SHIP_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_FACILITY_TRANS_WO.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_FACILITY_XFER_LEAD_TM.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_FACILITY_XFER_POOL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_FACILITY_XFER_SHIP_DY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_PACK_BOX.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_PICK_BATCH_COP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_PICK_BATCH_TRANS.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_PICK_BATCH_WO.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_PICK_DTL_COP_RQST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_PICK_DTL_TRANS_RQST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_PICK_DTL_WO_RQST.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_PICK_RULE_COP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_PICK_RULE_USER.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_PICK_RULE_USER_COP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_PICK_RULE_WO.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_PICK_SCAN_ID.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_PICK_SIM_COP.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_SHIP_BIN.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_SHIP_PRTY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_SHIP_VIA_PRTY.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_WHSE_ZONE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WH_WHSE_ZONE_USER.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WO_DTL.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WO_DTL_CERT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WO_DTL_MFG.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WO_HDR.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WO_HDR_CERT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WO_MFG_CHARGE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WO_PICK_SIM.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WO_RELEASE.sql
@/common/home/jjs/java-projects/aerodemo/interfast/WO_UNIT.sql
@/common/home/jjs/java-projects/aerodemo/interfast/X.sql
