--------------------------------------------------------
--  DDL for Table GEO_POSTAL_CODES
--------------------------------------------------------

  CREATE TABLE "GEO_POSTAL_CODES" 
   (	"POSTAL_CD" VARCHAR2(10), 
	"CITY" VARCHAR2(30), 
	"STATE_CD" VARCHAR2(5), 
	"CNTRY_CD" VARCHAR2(3), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
