--------------------------------------------------------
--  DDL for Table GL_TAX_GRP
--------------------------------------------------------

  CREATE TABLE "GL_TAX_GRP" 
   (	"GL_TAX_GRP_NBR" NUMBER(9,0), 
	"GL_TAX_GRP_CD" VARCHAR2(16), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"GL_TAX_GRP_DESCR" VARCHAR2(60)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
