--------------------------------------------------------
--  DDL for Table IC_ADJ_CD
--------------------------------------------------------

  CREATE TABLE "IC_ADJ_CD" 
   (	"ADJ_CD" VARCHAR2(8), 
	"ADJ_CD_DESCR" VARCHAR2(60), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"INCR_DECR_ID" VARCHAR2(1), 
	"ADJ_CD_STAT_ID" VARCHAR2(1) DEFAULT 'A'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
