--------------------------------------------------------
--  DDL for Table IC_BOM
--------------------------------------------------------

  CREATE TABLE "IC_BOM" 
   (	"ITEM_NBR" NUMBER(9,0), 
	"ITEM_NBR_PARENT" NUMBER(9,0), 
	"CHILD_QTY" NUMBER(13,6), 
	"CHILD_UM" VARCHAR2(3), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"MIX_MFR_LOT_FLG" VARCHAR2(1), 
	"PRINT_BAG_LBL_FLG" VARCHAR2(1), 
	"REV_LVL" VARCHAR2(5), 
	"ORG_NBR_MFR_RQST" NUMBER(9,0), 
	"MANDATORY_ITEM_FLG" VARCHAR2(1) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
