--------------------------------------------------------
--  DDL for Table IC_CAT_DISC
--------------------------------------------------------

  CREATE TABLE "IC_CAT_DISC" 
   (	"IC_CATEGORY_NBR" NUMBER(9,0), 
	"CUST_PRICE_GRP" VARCHAR2(8), 
	"DISC_PERC" NUMBER, 
	"IC_CATEGORY" VARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
