--------------------------------------------------------
--  DDL for Table IC_DUTY_RATE
--------------------------------------------------------

  CREATE TABLE "IC_DUTY_RATE" 
   (	"HARMONIZED_CD" VARCHAR2(20), 
	"CNTRY_CD" VARCHAR2(3), 
	"DUTY_PCT" NUMBER(10,5), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
