--------------------------------------------------------
--  DDL for Table IC_ITEM_COST_TYPE
--------------------------------------------------------

  CREATE TABLE "IC_ITEM_COST_TYPE" 
   (	"COST_TYPE_CD" VARCHAR2(16), 
	"COST_TYPE_DESCR" VARCHAR2(60), 
	"COST_TYPE_PROCEDURE_NM" VARCHAR2(100), 
	"PROC_EXEC_DT" DATE, 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
