--------------------------------------------------------
--  DDL for Table IC_ITEM_SER
--------------------------------------------------------

  CREATE TABLE "IC_ITEM_SER" 
   (	"SERIAL_CD" VARCHAR2(20), 
	"LOT_NBR" NUMBER(9,0), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"WO_HDR_NBR" NUMBER(9,0), 
	"BUILD_DT" DATE, 
	"IC_TRANS_GL_NBR" NUMBER(9,0), 
	"MFR_SERIAL_CD" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16777216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
