--------------------------------------------------------
--  DDL for Table IC_ITEM_PRICE_MATRIX
--------------------------------------------------------

  CREATE TABLE "IC_ITEM_PRICE_MATRIX" 
   (	"ITEM_NBR" NUMBER(9,0), 
	"QTY_ORD" NUMBER(13,5), 
	"LIST_PRICE" NUMBER(17,6), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"CURR_CD" VARCHAR2(3)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
