--------------------------------------------------------
--  DDL for Table IC_ITEM_MAST_NOMEN
--------------------------------------------------------

  CREATE TABLE "IC_ITEM_MAST_NOMEN" 
   (	"ITEM_NBR" NUMBER(9,0), 
	"ORG_NBR_NOMEN" NUMBER(9,0), 
	"ITEM_CD_NOMEN" VARCHAR2(50), 
	"ITEM_DESCR_NOMEN" VARCHAR2(50), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"DISPLAY_FLG" VARCHAR2(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 92274688 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
