--------------------------------------------------------
--  DDL for Table IC_KIT_MAST
--------------------------------------------------------

  CREATE TABLE "IC_KIT_MAST" 
   (	"ITEM_NBR" NUMBER(9,0), 
	"ORG_NBR_CUST" NUMBER(9,0), 
	"APS_SRC_RULE_SET_NBR_DFLT" NUMBER(9,0), 
	"FACILITY_DFLT" VARCHAR2(16), 
	"APS_SPLY_SUB_POOL_NBR_DFLT" NUMBER(9,0), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
