--------------------------------------------------------
--  DDL for Table IC_LOT_MAST_CERT_LOG
--------------------------------------------------------

  CREATE TABLE "IC_LOT_MAST_CERT_LOG" 
   (	"LOT_NBR" NUMBER(9,0), 
	"CERT_CD" VARCHAR2(8), 
	"CERT_RCPT_DT" DATE, 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"MOD_ACTION" VARCHAR2(1), 
	"UT_USER_NBR_MOD" NUMBER(9,0), 
	"MOD_TM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;

   COMMENT ON COLUMN "IC_LOT_MAST_CERT_LOG"."MOD_ACTION" IS 'I - Insert, U - Update, D - Delete';
