--------------------------------------------------------
--  DDL for Table IC_LOT_MAST_PO_DTL
--------------------------------------------------------

  CREATE TABLE "IC_LOT_MAST_PO_DTL" 
   (	"LOT_NBR" NUMBER(9,0), 
	"PO_LINE_DTL_NBR" NUMBER(9,0), 
	"REPLEN_RQST_SHIP_DT" DATE, 
	"REPLEN_CURR_EST_DT" DATE, 
	"OPEN_PO_QTY" NUMBER(13,5), 
	"RECV_QTY" NUMBER(13,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16777216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
