--------------------------------------------------------
--  DDL for Table IDENTIFIED_LOT_SCAN_TMP
--------------------------------------------------------

  CREATE TABLE "IDENTIFIED_LOT_SCAN_TMP" 
   (	"LOT_NBR" NUMBER(9,0), 
	"ITEM_NBR" NUMBER(9,0), 
	"RCPT_DT" DATE, 
	"PO_CD" VARCHAR2(20), 
	"ITEM_CD" VARCHAR2(50), 
	"MFR_LOT_CD" VARCHAR2(20), 
	"MFR_CAGE_CD" VARCHAR2(10), 
	"ORG_NM_MFR" VARCHAR2(60)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
