--------------------------------------------------------
--  DDL for Table IMG_IMAGE_SET_DTL
--------------------------------------------------------

  CREATE TABLE "IMG_IMAGE_SET_DTL" 
   (	"IMG_IMAGE_SET_HDR_NBR" NUMBER(9,0), 
	"IMG_IMAGE_NBR" NUMBER(9,0), 
	"IMG_IMAGE_SET_DTL_DESCR" VARCHAR2(255)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
