--------------------------------------------------------
--  DDL for Table IMG_IMAGE_SET_HDR
--------------------------------------------------------

  CREATE TABLE "IMG_IMAGE_SET_HDR" 
   (	"IMG_IMAGE_SET_HDR_NBR" NUMBER(9,0), 
	"IMG_IMAGE_SET_DESCR" VARCHAR2(255), 
	"SCAN_SET_FLG" VARCHAR2(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
