--------------------------------------------------------
--  DDL for Table IMG_SCAN_BATCH
--------------------------------------------------------

  CREATE TABLE "IMG_SCAN_BATCH" 
   (	"IMG_SCAN_BATCH_NBR" NUMBER(9,0), 
	"SCAN_DEVICE_TYPE_ID" VARCHAR2(20), 
	"IMG_CAPTURE_TM" DATE, 
	"INDIV_NBR_CAPTURE" NUMBER(9,0), 
	"IMG_IMAGE_SET_HDR_NBR" NUMBER(9,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
