--------------------------------------------------------
--  DDL for Table JIT_ERR
--------------------------------------------------------

  CREATE TABLE "JIT_ERR" 
   (	"JIT_ERR_CD" VARCHAR2(8), 
	"JIT_ERR_MSG" VARCHAR2(255), 
	"JIT_ERR_CORRECT_MSG" VARCHAR2(255)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
