--------------------------------------------------------
--  DDL for Table NA_ADDR_TAX
--------------------------------------------------------

  CREATE TABLE "NA_ADDR_TAX" 
   (	"NA_ADDR_TAX_NBR" NUMBER(9,0), 
	"ADDR_NBR" NUMBER(9,0), 
	"TAX_CD" VARCHAR2(16), 
	"TAX_EXEMPT_CD" VARCHAR2(16), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
