--------------------------------------------------------
--  DDL for Table NA_CATEGORY
--------------------------------------------------------

  CREATE TABLE "NA_CATEGORY" 
   (	"NA_CATEGORY_NBR" NUMBER(9,0), 
	"NA_CATEGORY_CD" VARCHAR2(20), 
	"NA_CATEGORY_NBR_PARENT" NUMBER(9,0), 
	"NA_CATEGORY_DESCR" VARCHAR2(60), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"NA_CATEGORY_LVL" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
