--------------------------------------------------------
--  DDL for Table NA_INDIV_PHN
--------------------------------------------------------

  CREATE TABLE "NA_INDIV_PHN" 
   (	"NA_INDIV_PHN_NBR" NUMBER(9,0), 
	"INDIV_NBR" NUMBER(9,0), 
	"PHN_TYPE_CD" VARCHAR2(8), 
	"CNTRY_PHN_CD" NUMBER(3,0), 
	"AREA_CD" NUMBER(5,0), 
	"PHN_NBR" VARCHAR2(20), 
	"PHN_EXT" NUMBER(5,0), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"PHN_TYPE_DESCR" VARCHAR2(60)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
