--------------------------------------------------------
--  DDL for Table NA_ORG_DEPT
--------------------------------------------------------

  CREATE TABLE "NA_ORG_DEPT" 
   (	"NA_ORG_DEPT_NBR" NUMBER(9,0), 
	"ORG_NBR" NUMBER(9,0), 
	"NA_ORG_DEPT_NBR_PARENT" NUMBER(9,0), 
	"NA_ORG_DEPT_NM" VARCHAR2(20), 
	"NA_ORG_DEPT_DESCR" VARCHAR2(60), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
