--------------------------------------------------------
--  DDL for Table OE_CUST_MAST_SHIP_VIA_ACCT
--------------------------------------------------------

  CREATE TABLE "OE_CUST_MAST_SHIP_VIA_ACCT" 
   (	"ORG_NBR_CUST" NUMBER(9,0), 
	"SHIP_VIA_CD" VARCHAR2(8), 
	"SHIP_VIA_ACCT_CD" VARCHAR2(20), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_TM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
