--------------------------------------------------------
--  DDL for Table OE_CONTRACT_ITEM_LOG
--------------------------------------------------------

  CREATE TABLE "OE_CONTRACT_ITEM_LOG" 
   (	"ORG_NBR_CUST" NUMBER(9,0), 
	"CONTRACT_CD" VARCHAR2(8), 
	"ITEM_CD_CUST" VARCHAR2(50), 
	"ITEM_NBR" NUMBER(9,0), 
	"ITEM_NBR_SUPERSEDE" NUMBER(9,0), 
	"EFF_DT_BEG" DATE, 
	"EFF_DT_END" DATE, 
	"TOT_CONTRACT_QTY" NUMBER(9,0), 
	"UT_USER_NBR_MOD" NUMBER(9,0), 
	"MOD_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16777216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
