--------------------------------------------------------
--  DDL for Table OE_CUST_BIN_XX
--------------------------------------------------------

  CREATE TABLE "OE_CUST_BIN_XX" 
   (	"ORG_NBR_CUST" NUMBER(9,0), 
	"CONTRACT_CD" VARCHAR2(8), 
	"PGM_CD" VARCHAR2(8), 
	"ITEM_CD_CUST" VARCHAR2(50), 
	"CUST_BIN_CD" VARCHAR2(30), 
	"ORD_QTY_MIN" NUMBER(9,0), 
	"ORD_QTY_MAX" NUMBER(9,0), 
	"CUST_AVG_MNTH_DMD" NUMBER(10,2), 
	"PKG_QTY" NUMBER(9,0), 
	"MIN_SAFE_STK" NUMBER(9,0), 
	"BIN_CAP" NUMBER(9,0), 
	"BIN_STK_UM" VARCHAR2(3), 
	"EFF_DT_BEG" DATE, 
	"EFF_DT_END" DATE, 
	"REPLEN_QTY" NUMBER(9,0), 
	"CUST_BIN_GRP" VARCHAR2(10), 
	"CUST_BILL_INFO" VARCHAR2(20), 
	"SHIP_TO_ADDR_NBR" NUMBER(9,0), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"BIN_QTY" NUMBER(13,5), 
	"BIN_RACK" VARCHAR2(4), 
	"BIN_ROW" VARCHAR2(2), 
	"BIN_POSITION" VARCHAR2(2), 
	"BIN_QTY_MIN" NUMBER(9,0), 
	"PLAN_CUST_AVG_MNTH_DMD" NUMBER(10,2), 
	"CUST_PO_CD" VARCHAR2(30), 
	"NOTE_NBR_REF" NUMBER(9,0), 
	"UPD_PLAN_CUST_AMC_FLG" VARCHAR2(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
