--------------------------------------------------------
--  DDL for Table OE_SALES_REGION
--------------------------------------------------------

  CREATE TABLE "OE_SALES_REGION" 
   (	"SALES_REGION_CD" VARCHAR2(8), 
	"SALES_REGION_DESCR" VARCHAR2(60), 
	"SALES_REGION_CD_STAT_ID" VARCHAR2(1), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_TM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
