--------------------------------------------------------
--  DDL for Table PO_LINE_DTL_LOG
--------------------------------------------------------

  CREATE TABLE "PO_LINE_DTL_LOG" 
   (	"PO_LINE_DTL_NBR" NUMBER(9,0), 
	"SCHED_QTY" NUMBER(13,5), 
	"SCHED_QTY_STK_UM" NUMBER(13,5), 
	"RECV_QTY" NUMBER(13,5), 
	"RECV_QTY_STK_UM" NUMBER(13,5), 
	"REPLEN_RQST_SHIP_DT" DATE, 
	"REPLEN_EST_SHIP_DT" DATE, 
	"REPLEN_CURR_EST_DT" DATE, 
	"FACILITY" VARCHAR2(16), 
	"APS_SPLY_SUB_POOL_NBR" NUMBER(9,0), 
	"SHIP_TO_ADDR_NBR" NUMBER(9,0), 
	"SHIP_VIA_CD" VARCHAR2(8), 
	"APS_AVAIL_DT" DATE, 
	"CANCEL_CD" VARCHAR2(8), 
	"CANCEL_DT" DATE, 
	"UT_USER_NBR_CANCEL" NUMBER(9,0), 
	"MOD_DT" DATE, 
	"UT_USER_NBR_MOD" NUMBER(9,0), 
	"CANNOT_RESCHED_FLG" VARCHAR2(1) DEFAULT 'N', 
	"BUY_REASON_CD" VARCHAR2(8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16777216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
