--------------------------------------------------------
--  DDL for Table PO_UNPLANNED_RCPT
--------------------------------------------------------

  CREATE TABLE "PO_UNPLANNED_RCPT" 
   (	"PO_UNPLANNED_RCPT_NBR" NUMBER(9,0), 
	"ITEM_NBR" NUMBER(9,0), 
	"RCPT_DT" DATE, 
	"ORG_NBR_VND" NUMBER(9,0), 
	"QTY_RECV" NUMBER(15,5), 
	"LOT_UM" VARCHAR2(3), 
	"MFR_LOT_CD" VARCHAR2(20), 
	"MFR_DT" DATE, 
	"ORG_NBR_MFR" NUMBER(9,0), 
	"REV_LVL" VARCHAR2(5), 
	"PO_ORD_HDR_NBR" NUMBER(9,0), 
	"PO_LINE_HDR_NBR" NUMBER(9,0), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"RCPT_STAT_ID" VARCHAR2(1), 
	"PROCESSED_DT" DATE, 
	"BIN_NBR" NUMBER(9,0), 
	"APS_SPLY_SUB_POOL_NBR" NUMBER(9,0), 
	"FACILITY" VARCHAR2(16), 
	"QTY_RECV_STK_UM" NUMBER(13,5), 
	"EXPIRE_DT" DATE, 
	"LOT_NBR" NUMBER(9,0), 
	"CNTRY_CD_ORIGIN" VARCHAR2(3), 
	"ITEM_CD_VND" VARCHAR2(50), 
	"UNIT_COST_DENOM_REPLEN_UM" NUMBER(17,6), 
	"UNIT_COST_REPLEN_UM" NUMBER(17,6), 
	"UNIT_COST_STK_UM" NUMBER(17,6), 
	"UNIT_COST_DENOM_STK_UM" NUMBER(17,6), 
	"RCPT_COMM" VARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16777216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
