--------------------------------------------------------
--  DDL for Table POS_DTL
--------------------------------------------------------

  CREATE TABLE "POS_DTL" 
   (	"POS_DTL_NBR" NUMBER(9,0), 
	"POS_HDR_NBR" NUMBER(9,0), 
	"BOX_CD" VARCHAR2(20), 
	"QTY_SHIP" NUMBER(13,5), 
	"QTY_SHIP_STK_UM" NUMBER(13,5), 
	"ITEM_NBR_SHIP" NUMBER(9,0), 
	"LOT_NBR" NUMBER(9,0), 
	"FACILITY" VARCHAR2(16), 
	"APS_SPLY_SUB_POOL_NBR" NUMBER(9,0), 
	"UNIT_PRICE_DENOM_SELL_UM" NUMBER(17,6), 
	"UNIT_PRICE_SELL_UM" NUMBER(17,6), 
	"UNIT_PRICE_DENOM_STK_UM" NUMBER(17,6), 
	"UNIT_PRICE_STK_UM" NUMBER(17,6), 
	"CONTRACT_CD" VARCHAR2(8), 
	"CUST_BIN_CD" VARCHAR2(40), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"ITEM_CD_CUST" VARCHAR2(50), 
	"OE_ORD_DTL_NBR" NUMBER(9,0), 
	"OE_ORD_LINE_NBR" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16777216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
