--------------------------------------------------------
--  DDL for Table QA_CONTRACT_APPRV_HDR
--------------------------------------------------------

  CREATE TABLE "QA_CONTRACT_APPRV_HDR" 
   (	"ORG_NBR_CUST_CONTRACT" NUMBER(9,0), 
	"ORG_NBR_CUST_APPRV" NUMBER(9,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
