--------------------------------------------------------
--  DDL for Table QA_INSPECTOR
--------------------------------------------------------

  CREATE TABLE "QA_INSPECTOR" 
   (	"INSPECTOR_NBR" NUMBER(2,0), 
	"USER_NAME" VARCHAR2(30), 
	"QA_PASSWD" VARCHAR2(10), 
	"MFR_STAT_AUTH_FLG" VARCHAR2(1)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
