--------------------------------------------------------
--  DDL for Table QA_MFR_APPRV
--------------------------------------------------------

  CREATE TABLE "QA_MFR_APPRV" 
   (	"QA_PROJ_CD" VARCHAR2(16), 
	"ITEM_NBR" NUMBER(9,0), 
	"ORG_NBR_MFR" NUMBER(9,0), 
	"MFR_RESTRICT_ID" VARCHAR2(1)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
