--------------------------------------------------------
--  DDL for Table QA_TST
--------------------------------------------------------

  CREATE TABLE "QA_TST" 
   (	"QA_TST_CD" VARCHAR2(16), 
	"QA_TST_DESCR" VARCHAR2(60), 
	"DESTROY_FLG" VARCHAR2(1), 
	"TST_COST" NUMBER(6,2), 
	"TST_COST_TYPE" VARCHAR2(1), 
	"TST_TYPE" VARCHAR2(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
