--------------------------------------------------------
--  DDL for Table QA_TST_STE_PLAN
--------------------------------------------------------

  CREATE TABLE "QA_TST_STE_PLAN" 
   (	"QA_TST_STE_CD" VARCHAR2(16), 
	"PLAN_NBR" NUMBER(9,0), 
	"PLAN_NBR_NXT" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
