--------------------------------------------------------
--  DDL for Table QA_TST_STE_VND
--------------------------------------------------------

  CREATE TABLE "QA_TST_STE_VND" 
   (	"QA_TST_STE_VND_NBR" NUMBER(9,0), 
	"QA_PROJ_CD" VARCHAR2(16), 
	"IC_ATTR_NBR" NUMBER(9,0), 
	"ATTR_VAL" VARCHAR2(20), 
	"QA_TST_STE_CD" VARCHAR2(16), 
	"ORG_NBR_VND" NUMBER(9,0), 
	"PLAN_NBR" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
