--------------------------------------------------------
--  DDL for Table SALES_LEAD
--------------------------------------------------------

  CREATE TABLE "SALES_LEAD" 
   (	"SALES_LEAD_NBR" NUMBER(9,0), 
	"SALES_LEAD_REF" VARCHAR2(50), 
	"ORG_NBR_LEAD_SRC" NUMBER(9,0), 
	"LEAD_RECV_DT" DATE, 
	"INDIV_NBR_LEAD_RECV" NUMBER(9,0), 
	"INDIV_NBR_LEAD_ASSIGN" NUMBER(9,0), 
	"LEAD_ASSIGN_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
