--------------------------------------------------------
--  DDL for Table SERVICE_RQST_LOG
--------------------------------------------------------

  CREATE TABLE "SERVICE_RQST_LOG" 
   (	"SERVICE_RQST_LOG_NBR" NUMBER(9,0), 
	"SERVICE_RQST_CD" VARCHAR2(20), 
	"SERVICE_RQST_PARMS" VARCHAR2(2048), 
	"SERVICE_RQST_ISSUE_TM" DATE, 
	"SERVICE_RQST_COMPLETE_TM" DATE, 
	"SERVICE_RQST_ELAPSED_MS" NUMBER(9,0), 
	"SERVICE_RQST_TRACE" VARCHAR2(4000), 
	"SERVICE_RQST_STAT_ID" VARCHAR2(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1031798784 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
