--------------------------------------------------------
--  DDL for Table SHIP_NOTIFY_ERROR
--------------------------------------------------------

  CREATE TABLE "SHIP_NOTIFY_ERROR" 
   (	"ORG_NBR_CUST" NUMBER, 
	"NOTIFY_EMAIL_ADDR" VARCHAR2(200), 
	"SHIP_DT" DATE, 
	"ERROR_MSG" VARCHAR2(2000), 
	"ERROR_DT" DATE DEFAULT SYSDATE, 
	"UT_USER_NBR" NUMBER, 
	"COMM" VARCHAR2(1000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
