--------------------------------------------------------
--  DDL for Table TEST_INV
--------------------------------------------------------

  CREATE TABLE "TEST_INV" 
   (	"ITEM_NBR" NUMBER(9,0), 
	"RCPT_DT" DATE, 
	"LOT_NBR" NUMBER(9,0), 
	"BOX_QTY" NUMBER(12,5), 
	"LOT_COST_LANDED_CURR" NUMBER(17,6), 
	"REASON_CD" VARCHAR2(17)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
