--------------------------------------------------------
--  DDL for Table TEST_067500
--------------------------------------------------------

  CREATE TABLE "TEST_067500" 
   (	"ITEM_NBR" NUMBER(9,0), 
	"CERT_CD" VARCHAR2(8), 
	"USE_CONTRACT_ITEM_CERT" VARCHAR2(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
