--------------------------------------------------------
--  DDL for Table TEST_ITEM
--------------------------------------------------------

  CREATE TABLE "TEST_ITEM" 
   (	"ORG_NBR" NUMBER(9,0), 
	"ORG_CD" VARCHAR2(15), 
	"ITEM_NBR" NUMBER(9,0), 
	"ITEM_CD" VARCHAR2(50), 
	"EFF_DT_BEG" DATE, 
	"EFF_DT_END" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
