--------------------------------------------------------
--  DDL for Table TMP_OE_ORD_HDR
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "TMP_OE_ORD_HDR" 
   (	"OE_ORD_HDR_NBR" NUMBER(9,0), 
	"ORD_TYPE_CD" VARCHAR2(8), 
	"ORD_CD" VARCHAR2(20), 
	"ORD_DT" DATE, 
	"ORG_NBR_CUST" NUMBER(9,0), 
	"ORG_NM_CUST" VARCHAR2(60), 
	"ORD_STAT_ID" VARCHAR2(1), 
	"BILL_TO_ADDR_NBR" NUMBER(9,0), 
	"SHIP_TO_ADDR_NBR_DFLT" NUMBER(9,0), 
	"CUST_PO_CD" VARCHAR2(30), 
	"CUST_PO_DT" DATE, 
	"RQST_DT_DFLT" DATE, 
	"CANCEL_DT" DATE, 
	"TERM_CD" VARCHAR2(10), 
	"SHIP_VIA_CD_DFLT" VARCHAR2(8), 
	"FOB_CD" VARCHAR2(8), 
	"CURR_CD" VARCHAR2(3), 
	"UT_USER_NBR_CANCEL" NUMBER(9,0), 
	"CANCEL_TIME" DATE, 
	"CANCEL_CD" VARCHAR2(8), 
	"ORD_PRTY" NUMBER(3,0), 
	"SELL_INDIV_NBR" NUMBER(9,0), 
	"BUYER_EMAIL_ADDR" VARCHAR2(40), 
	"INDIV_NM_BUYER" VARCHAR2(45), 
	"BUYER_PHN_NBR" VARCHAR2(20), 
	"SALES_TERR_CD" VARCHAR2(8), 
	"BUYER_FAX_NBR" VARCHAR2(20), 
	"TRD_FLG" VARCHAR2(1), 
	"SHIP_PCT_LINE" NUMBER(3,0), 
	"SHIP_PCT_DOLLAR" NUMBER(3,0), 
	"NEXT_LINE_NBR" NUMBER(4,0), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE
   ) ON COMMIT DELETE ROWS ;
