--------------------------------------------------------
--  DDL for Table TMP_WO_RELEASE_UNIT_QTY
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "TMP_WO_RELEASE_UNIT_QTY" 
   (	"WO_HDR_NBR" NUMBER(9,0), 
	"ITEM_NBR_KIT" NUMBER(9,0), 
	"ITEM_NBR_COMPONENT" NUMBER(9,0), 
	"COMPONENT_UM" VARCHAR2(2), 
	"COMPONENT_QTY_PER_UNIT" NUMBER(13,5), 
	"MIX_MFR_LOT_FLG" VARCHAR2(1), 
	"MANDATORY_ITEM_FLG" VARCHAR2(1), 
	"PRINT_BAG_LBL_FLG" VARCHAR2(1), 
	"WO_RELEASE_NBR" NUMBER(9,0), 
	"WO_UNIT_NBR" NUMBER(9,0), 
	"BIN_NBR" NUMBER(9,0), 
	"QTY_IN_KIT_BIN" NUMBER(13,5), 
	"KIT_QTY" NUMBER(13,5)
   ) ON COMMIT DELETE ROWS ;
