--------------------------------------------------------
--  DDL for Table UNBRAKO_SHIP_DTL
--------------------------------------------------------

  CREATE TABLE "UNBRAKO_SHIP_DTL" 
   (	"POS_DTL_NBR" NUMBER, 
	"ORD_NBR" NUMBER, 
	"ITEM_CD_ORD" VARCHAR2(50), 
	"QTY_SHIP" NUMBER, 
	"UT_USER_NBR" NUMBER, 
	"LAST_MOD_DT" DATE, 
	"SHIP_STAT_ID" VARCHAR2(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
