--------------------------------------------------------
--  DDL for Table UNBRAKO_ORD_HDR_CHARGE
--------------------------------------------------------

  CREATE TABLE "UNBRAKO_ORD_HDR_CHARGE" 
   (	"ORD_CHARGE_NBR" NUMBER, 
	"ORD_NBR" NUMBER, 
	"CHARGE_CD" VARCHAR2(10), 
	"UT_USER_NBR" NUMBER, 
	"LAST_MOD_DT" DATE, 
	"RECUR_FLG" VARCHAR2(1) DEFAULT 'N', 
	"AR_INV_HDR_CHARGE_NBR" NUMBER, 
	"TAXABLE_FLG" VARCHAR2(1) DEFAULT 'N', 
	"CHARGE_AMT_DENOM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
