--------------------------------------------------------
--  DDL for Table UNBRAKO_ORD_DTL
--------------------------------------------------------

  CREATE TABLE "UNBRAKO_ORD_DTL" 
   (	"ORD_NBR" NUMBER, 
	"ORD_DTL_NBR" NUMBER, 
	"ITEM_CD_ORD" VARCHAR2(50), 
	"QTY_ORD_STK_UM" NUMBER, 
	"UNIT_PRICE_DENOM_STK_UM" NUMBER, 
	"QTY_SHIP_STK_UM" NUMBER, 
	"RQST_DT" DATE, 
	"UT_USER_NBR" NUMBER, 
	"LAST_MOD_DT" DATE, 
	"LINE_STAT_ID" VARCHAR2(1) DEFAULT 'O', 
	"ITEM_CD_CUST" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
