--------------------------------------------------------
--  DDL for Table UNBRAKO_TRANS_BATCH
--------------------------------------------------------

  CREATE TABLE "UNBRAKO_TRANS_BATCH" 
   (	"TRANS_BATCH_NBR" NUMBER, 
	"TRANS_BATCH_DT" DATE, 
	"TRANS_HDR_NBR" NUMBER, 
	"FACILITY_SRC" VARCHAR2(16), 
	"FACILITY_DEST" VARCHAR2(16), 
	"LOT_NBR" NUMBER, 
	"ITEM_CD" VARCHAR2(50), 
	"BIN_CD" VARCHAR2(16), 
	"MFR_LOT_CD" VARCHAR2(20), 
	"BOX_CD" VARCHAR2(20), 
	"PICK_QTY" NUMBER, 
	"UT_USER_NBR" NUMBER, 
	"LAST_MOD_DT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
