--------------------------------------------------------
--  DDL for Table UPC_QTY_FIX_ITEM
--------------------------------------------------------

  CREATE TABLE "UPC_QTY_FIX_ITEM" 
   (	"ITEM_NBR" NUMBER(9,0), 
	"FACILITY" VARCHAR2(16), 
	"APS_SPLY_SUB_POOL_NBR" NUMBER(9,0), 
	"QTY_START" NUMBER(13,5), 
	"QTY_RECV" NUMBER(13,5), 
	"QTY_ADJUST_IN" NUMBER(13,5), 
	"QTY_ADJUST_OUT" NUMBER(13,5), 
	"QTY_SHIP" NUMBER(13,5), 
	"QTY_FAC_TRANS_IN" NUMBER(13,5), 
	"QTY_FAC_TRANS_OUT" NUMBER(13,5), 
	"QTY_ON_HAND" NUMBER(13,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
