--------------------------------------------------------
--  DDL for Table UT_CACHE
--------------------------------------------------------

  CREATE TABLE "UT_CACHE" 
   (	"OBJECT_NAME" VARCHAR2(32), 
	"CHANGE_TIME" DATE, 
	"CACHE_CHANGE_NBR" NUMBER(9,0) DEFAULT 1, 
	"CLASS_NAME" VARCHAR2(32)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
