--------------------------------------------------------
--  DDL for Table UT_ERR
--------------------------------------------------------

  CREATE TABLE "UT_ERR" 
   (	"ERR_CD" VARCHAR2(10), 
	"ERR_MSG" VARCHAR2(1024), 
	"CAUSE_MSG" VARCHAR2(1024), 
	"CORRECT_MSG" VARCHAR2(1024)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
