--------------------------------------------------------
--  DDL for Table UT_FACILITY
--------------------------------------------------------

  CREATE TABLE "UT_FACILITY" 
   (	"FACILITY" VARCHAR2(16), 
	"PRIMARY_ADDR_NBR" NUMBER(9,0), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"CALENDAR" VARCHAR2(6), 
	"FACILITY_STAT_ID" VARCHAR2(1) DEFAULT 'A', 
	"UT_FACILITY_NBR" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
