--------------------------------------------------------
--  DDL for Table UT_FORM_TABS
--------------------------------------------------------

  CREATE TABLE "UT_FORM_TABS" 
   (	"UT_FORM_TAB_NBR" NUMBER(9,0), 
	"FORM_NM" VARCHAR2(30), 
	"TAB_CANVAS_NM" VARCHAR2(30), 
	"TAB_PAGE_NM" VARCHAR2(30), 
	"TAB_PAGE_SEQ" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
