--------------------------------------------------------
--  DDL for Table UT_FORM_TOOLTIP
--------------------------------------------------------

  CREATE TABLE "UT_FORM_TOOLTIP" 
   (	"FIELD_NM" VARCHAR2(30), 
	"FORM_NM" VARCHAR2(30), 
	"BLOCK_NM" VARCHAR2(30), 
	"TOOLTIP_TXT" VARCHAR2(1024)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
