--------------------------------------------------------
--  DDL for Table UT_FORM_LOAD
--------------------------------------------------------

  CREATE TABLE "UT_FORM_LOAD" 
   (	"FORM_NM" VARCHAR2(30), 
	"FORM_DESCR" VARCHAR2(255)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
