--------------------------------------------------------
--  DDL for Table UT_LABEL_CLASS_ARG
--------------------------------------------------------

  CREATE TABLE "UT_LABEL_CLASS_ARG" 
   (	"LABEL_NM" VARCHAR2(20), 
	"ARG_NM" VARCHAR2(20), 
	"ARG_DESC" VARCHAR2(50), 
	"ARG_TYPE" VARCHAR2(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
