--------------------------------------------------------
--  DDL for Table UT_PROCEDURE_LOAD
--------------------------------------------------------

  CREATE TABLE "UT_PROCEDURE_LOAD" 
   (	"PROCEDURE_NM" VARCHAR2(70)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
