--------------------------------------------------------
--  DDL for Table UT_TABLE_ROLE_PRIV
--------------------------------------------------------

  CREATE TABLE "UT_TABLE_ROLE_PRIV" 
   (	"TABLE_NM" VARCHAR2(30), 
	"ROLE_NM" VARCHAR2(16), 
	"SELECT_ALLOW_FLG" VARCHAR2(1), 
	"INSERT_ALLOW_FLG" VARCHAR2(1), 
	"UPDATE_ALLOW_FLG" VARCHAR2(1), 
	"DELETE_ALLOW_FLG" VARCHAR2(1), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
