--------------------------------------------------------
--  DDL for Table UT_USER
--------------------------------------------------------

  CREATE TABLE "UT_USER" 
   (	"ORG_NBR" NUMBER(9,0), 
	"UT_USER_NBR" NUMBER(9,0), 
	"USER_NAME" VARCHAR2(15), 
	"PASSWD" VARCHAR2(10), 
	"CALENDAR" VARCHAR2(6), 
	"FACILITY" VARCHAR2(16), 
	"PRINTER" VARCHAR2(50), 
	"PRINTER_LABEL" VARCHAR2(50), 
	"PICK_RULE_CD" VARCHAR2(8), 
	"PACK_STATION" VARCHAR2(16), 
	"RF_PASSWD" VARCHAR2(20), 
	"INDIV_NBR" NUMBER(9,0), 
	"LAST_LOGIN_TM" DATE, 
	"SHOW_TOOLTIP_FLG" VARCHAR2(1) DEFAULT 'Y', 
	"USER_STAT_ID" VARCHAR2(1), 
	"LDAP_ATTR_VAL" VARCHAR2(30), 
	"LDAP_USER_HASH" VARCHAR2(40), 
	"LDAP_CONN_EXPIRE_TM" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
