--------------------------------------------------------
--  DDL for Table WEB_QTE_LOG
--------------------------------------------------------

  CREATE TABLE "WEB_QTE_LOG" 
   (	"SQ_QTE_HDR_NBR" NUMBER, 
	"QTE_DT" DATE, 
	"ACTION_FLG" VARCHAR2(1) DEFAULT 'N', 
	"UT_USER_NBR" NUMBER, 
	"LAST_MOD_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
