--------------------------------------------------------
--  DDL for Table WH_CYCLE_CNT_RQST
--------------------------------------------------------

  CREATE TABLE "WH_CYCLE_CNT_RQST" 
   (	"WH_CYCLE_CNT_RQST_NBR" NUMBER(9,0), 
	"WH_CYCLE_CNT_BATCH_NBR" NUMBER(9,0), 
	"BOX_CD" VARCHAR2(20), 
	"BOX_QTY" NUMBER(13,5), 
	"BOX_QTY_ACT" NUMBER(13,5), 
	"ADJ_CD" VARCHAR2(8)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
