--------------------------------------------------------
--  DDL for Table WH_FACILITY_TRANS_LOG
--------------------------------------------------------

  CREATE TABLE "WH_FACILITY_TRANS_LOG" 
   (	"WH_FACILITY_TRANS_LOG_NBR" NUMBER(9,0), 
	"FACILITY_SRC" VARCHAR2(16), 
	"FACILITY_DEST" VARCHAR2(16), 
	"APS_SPLY_SUB_POOL_NBR_SRC" NUMBER(9,0), 
	"APS_SPLY_SUB_POOL_NBR_DEST" NUMBER(9,0), 
	"TRANSFER_DT" DATE, 
	"LOT_NBR" NUMBER(9,0), 
	"LOT_COST_LANDED_CURR" NUMBER(17,6), 
	"SHIP_VIA_CD" VARCHAR2(8), 
	"WAYBILL_CD" VARCHAR2(20), 
	"IC_TRANS_GL_NBR" NUMBER(9,0), 
	"TRANS_QTY" NUMBER(13,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16777216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
