--------------------------------------------------------
--  DDL for Table WH_FACILITY_SHIP_VIA_PICK
--------------------------------------------------------

  CREATE TABLE "WH_FACILITY_SHIP_VIA_PICK" 
   (	"FACILITY" VARCHAR2(16), 
	"SHIP_VIA_CD" VARCHAR2(8), 
	"PICK_FLG" VARCHAR2(1), 
	"PICK_LEAD_TM_DY" NUMBER(3,0), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
