--------------------------------------------------------
--  DDL for Table WH_PICK_RULE_USER_COP
--------------------------------------------------------

  CREATE TABLE "WH_PICK_RULE_USER_COP" 
   (	"WH_PICK_RULE_COP_CD" VARCHAR2(16), 
	"UT_USER_NBR_PICK" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
