--------------------------------------------------------
--  DDL for Table WO_RELEASE
--------------------------------------------------------

  CREATE TABLE "WO_RELEASE" 
   (	"WO_RELEASE_NBR" NUMBER(9,0), 
	"WO_HDR_NBR" NUMBER(9,0), 
	"QTY_RELEASE" NUMBER(7,0), 
	"RELEASE_STAT_ID" VARCHAR2(1), 
	"QTY_FILL" NUMBER(7,0), 
	"UT_USER_NBR" NUMBER(9,0), 
	"LAST_MOD_DT" DATE, 
	"RELEASE_FILL_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIAMOND" ;
