
  CREATE global temporary TABLE GTT_TABLE_ROW_MSG (	
	PRIMARY_KEY NUMBER(18,0),
	MSG VARCHAR2(64),
	UT_TABLE_RULE_NBR NUMBER(18,0) NOT NULL ENABLE,
	UT_RULE_GRP_RUN_NBR NUMBER(18,0) NOT NULL ENABLE,
	 CONSTRAINT GTT_TABLE_ROW_MSG_PK 
		PRIMARY KEY (UT_TABLE_RULE_NBR, UT_RULE_GRP_RUN_NBR, PRIMARY_KEY)
   );
