CREATE TABLE UT_DATA_LOCATION (
	SCHEMA							VARCHAR2(30)	NOT NULL,
	TABLE_NAME						VARCHAR2(30)	NOT NULL,
		CONSTRAINT UT_DATA_LOCATION_PK PRIMARY KEY (SCHEMA, TABLE_NAME) ENABLE )
ORGANIZATION INDEX ;


