  CREATE TABLE UT_MEASURE
   (	MEAS_NBR NUMBER(9,0) NOT NULL ENABLE,
	MEAS_ID VARCHAR2(20) NOT NULL ENABLE,
	SHORT_DESCR VARCHAR2(60) NOT NULL ENABLE,
	LONG_DESCR CLOB,
	ENTRY_USER NUMBER(9,0) NOT NULL ENABLE,
	ENTRY_TM TIMESTAMP (0) NOT NULL ENABLE,
	MOD_USER NUMBER(9,0),
	MOD_TM TIMESTAMP (0),
	 CONSTRAINT UT_MEAS_PK PRIMARY KEY (MEAS_NBR),
	 CONSTRAINT UT_MEAS_UK UNIQUE (MEAS_ID)
   );


