
  CREATE TABLE UT_METRIC_THRESHOLD
   (	UT_METRIC_THRESHOLD_NBR NUMBER(9,0) NOT NULL ENABLE,
	MEAS_NBR NUMBER(9,0) NOT NULL ENABLE,
	ORG_NBR_SRC NUMBER(9,0) NOT NULL ENABLE,
	FACT_TABLE_ID VARCHAR2(8) NOT NULL ENABLE,
	DIMEN_TABLE_ID VARCHAR2(8),
	DIMEN_PK NUMBER(18,0),
	THRESHOLD_VAL_LOWER_FATAL NUMBER,
	THRESHOLD_VAL_LOWER_SEVERE NUMBER,
	THRESHOLD_VAL_LOWER_WARN NUMBER,
	THRESHOLD_VAL_UPPER_WARN NUMBER,
	THRESHOLD_VAL_UPPER_SEVERE NUMBER,
	THRESHOLD_VAL_UPPER_FATAL NUMBER,
	THRESHOLD_ORDER VARCHAR2(1) NOT NULL ENABLE,
	ENTRY_USER NUMBER(9,0) NOT NULL ENABLE,
	ENTRY_TM TIMESTAMP (0) NOT NULL ENABLE,
	MOD_USER NUMBER(9,0),
	MOD_TM TIMESTAMP (0),
	 CONSTRAINT UT_METRIC_THERSHOLD_PK PRIMARY KEY (UT_METRIC_THRESHOLD_NBR),
	 CONSTRAINT UMT_CHECK_THRESHOLD_ORDER CHECK ( THRESHOLD_ORDER IN ('A', 'D')) ENABLE,
	 CONSTRAINT UMT_UM_FK FOREIGN KEY (MEAS_NBR)
	  REFERENCES UT_MEASURE (MEAS_NBR) ENABLE,
	 CONSTRAINT UMT_UT_FACT_FK FOREIGN KEY (FACT_TABLE_ID)
	  REFERENCES UT_TABLE (TABLE_ID) ENABLE,
	 CONSTRAINT UMT_UT_DIMEN_FK FOREIGN KEY (DIMEN_TABLE_ID)
	  REFERENCES UT_TABLE (TABLE_ID) ENABLE
   );


