CREATE TABLE UT_PROCESS_STATUS
(
  UT_PROCESS_STATUS_NBR  NUMBER(9),
  SCHEMA_NM              VARCHAR2(30 BYTE),
  PROCESS_NM             VARCHAR2(128 BYTE),
  THREAD_NM              VARCHAR2(128 BYTE),
  PROCESS_RUN_NBR        NUMBER(9),
  STATUS_MSG             VARCHAR2(256 BYTE),
  STATUS_ID              VARCHAR2(1 BYTE),
  STATUS_TS              TIMESTAMP(6),
  TOTAL_ELAPSED          INTERVAL DAY(2) TO SECOND(6),
  SID                    NUMBER,
  SERIAL#                NUMBER,
  IGNORE_FLG             VARCHAR2(1 BYTE)       DEFAULT 'N'
);


CREATE UNIQUE INDEX UT_PROCESS_STATUS_PK ON UT_PROCESS_STATUS
(UT_PROCESS_STATUS_NBR);


ALTER TABLE UT_PROCESS_STATUS ADD (
  CHECK ( IGNORE_FLG IN ('Y', 'N')));

ALTER TABLE UT_PROCESS_STATUS ADD (
  CONSTRAINT UT_PROCESS_STATUS_PK
 PRIMARY KEY
 (UT_PROCESS_STATUS_NBR));