
CREATE TABLE UT_PROCESS_LOG
(
  UT_PROCESS_LOG_NBR     NUMBER(9),
  UT_PROCESS_STATUS_NBR  NUMBER(9),
  LOG_MSG_ID             VARCHAR2(8 BYTE),
  LOG_MSG                VARCHAR2(256 BYTE),
  LOG_MSG_CLOB           CLOB,
  LOG_MSG_TS             TIMESTAMP(6),
  ELAPSED_TIME           INTERVAL DAY(2) TO SECOND(6),
  LOG_SEQ_NBR            NUMBER(18)             NOT NULL,
  CALLER_NAME            VARCHAR2(100 BYTE),
  LINE_NBR               NUMBER(5),
  CALL_STACK             CLOB,
  LOG_LEVEL              NUMBER(2)
);


CREATE UNIQUE INDEX UT_PROCESS_LOG_PK ON UT_PROCESS_LOG
(UT_PROCESS_STATUS_NBR, LOG_SEQ_NBR);


ALTER TABLE UT_PROCESS_LOG ADD (
  CONSTRAINT UT_PROCESS_LOG_PK
 PRIMARY KEY
 (UT_PROCESS_STATUS_NBR, LOG_SEQ_NBR));


ALTER TABLE UT_PROCESS_LOG ADD (
  CONSTRAINT UPL_UPS_FK 
 FOREIGN KEY (UT_PROCESS_STATUS_NBR) 
 REFERENCES UT_PROCESS_STATUS (UT_PROCESS_STATUS_NBR));