CREATE TABLE UT_PROCESS_STAT
(
  UT_PROCESS_STATUS_NBR  NUMBER(9)              NOT NULL,
  LOG_SEQ_NBR            NUMBER(9)              NOT NULL,
  SID                    NUMBER,
  STATISTIC#             NUMBER,
  VALUE                  NUMBER
);


CREATE UNIQUE INDEX UT_PROCESS_STAT_PK ON UT_PROCESS_STAT
(UT_PROCESS_STATUS_NBR, LOG_SEQ_NBR, STATISTIC#);


ALTER TABLE UT_PROCESS_STAT ADD (
  CONSTRAINT UT_PROCESS_STAT_PK
 PRIMARY KEY
 (UT_PROCESS_STATUS_NBR, LOG_SEQ_NBR, STATISTIC#));


ALTER TABLE UT_PROCESS_STAT ADD (
  CONSTRAINT UPSTAT_UPS_FK 
 FOREIGN KEY (UT_PROCESS_STATUS_NBR) 
 REFERENCES UT_PROCESS_STATUS (UT_PROCESS_STATUS_NBR));
