comment on column UT_PROCESS_LOG.UT_PROCESS_LOG_NBR is 'Surrogate primary key.';
comment on column UT_PROCESS_LOG.UT_PROCESS_STATUS_NBR is '  ';
comment on column UT_PROCESS_LOG.LOG_MSG_ID is 'Surrogate primary key.';
comment on column UT_PROCESS_LOG.LOG_MSG is '  ';
comment on column UT_PROCESS_LOG.LOG_MSG_CLOB is '  ';
comment on column UT_PROCESS_LOG.LOG_MSG_TS is '  ';
comment on column UT_PROCESS_LOG.ELAPSED_TIME is '  ';
comment on column UT_PROCESS_LOG.LOG_SEQ_NBR is '  ';
comment on column UT_PROCESS_LOG.CALLER_NAME is '  ';
comment on column UT_PROCESS_LOG.LINE_NBR is 'PL/SQL line number of this call  ';
comment on column UT_PROCESS_LOG.CALL_STACK is 'The PL/SQL stack  ';
comment on column UT_PROCESS_LOG.LOG_LEVEL is '  ';
comment on column UT_PROCESS_STAT.UT_PROCESS_STATUS_NBR is 'Surrogate primary key.';
comment on column UT_PROCESS_STAT.LOG_SEQ_NBR is 'Surrogate primary key.';
comment on column UT_PROCESS_STAT.SID is '  ';
comment on column UT_PROCESS_STAT.STATISTIC# is '  ';
comment on column UT_PROCESS_STAT.VALUE is '  ';
comment on column UT_PROCESS_STATUS.UT_PROCESS_STATUS_NBR is 'Surrogate primary key.';
comment on column UT_PROCESS_STATUS.SCHEMA_NM is '  ';
comment on column UT_PROCESS_STATUS.PROCESS_NM is '  ';
comment on column UT_PROCESS_STATUS.THREAD_NM is '  ';
comment on column UT_PROCESS_STATUS.PROCESS_RUN_NBR is '  ';
comment on column UT_PROCESS_STATUS.STATUS_MSG is '  ';
comment on column UT_PROCESS_STATUS.STATUS_ID is '  ';
comment on column UT_PROCESS_STATUS.STATUS_TS is '  ';
comment on column UT_PROCESS_STATUS.TOTAL_ELAPSED is '  ';
comment on column UT_PROCESS_STATUS.SID is '  ';
comment on column UT_PROCESS_STATUS.SERIAL# is '  ';
comment on column UT_PROCESS_STATUS.IGNORE_FLG is '  ';
