
  CREATE TABLE UT_QUERY
   (	UT_QUERY_NBR NUMBER(18,0) NOT NULL ENABLE,
	QUERY_NM VARCHAR2(32) NOT NULL ENABLE,
	QUERY_DESCR VARCHAR2(128),
	SCHEMA VARCHAR2(30) NOT NULL ENABLE,
	TABLE_NAME VARCHAR2(30) NOT NULL ENABLE,
	QUERY_TEXT CLOB,
	APEX_RPT_HEADING VARCHAR2(4000),
	TABLE_ID VARCHAR2(8),
	 CONSTRAINT UT_QUERY_PK PRIMARY KEY (UT_QUERY_NBR), 
	 CONSTRAINT UT_QUERY_UK UNIQUE (SCHEMA, TABLE_NAME, QUERY_NM),
	 CONSTRAINT UQ_UDL_FK FOREIGN KEY (SCHEMA, TABLE_NAME)
	  REFERENCES UT_DATA_LOCATION (SCHEMA, TABLE_NAME) ENABLE
   ); 


