
  CREATE TABLE UT_RULE_GRP_DTL
   (	UT_TABLE_RULE_NBR NUMBER(18,0),
	UT_RULE_GRP_NBR NUMBER(18,0) NOT NULL ENABLE,
	RUN_SEQ NUMBER(5,0),
	 CONSTRAINT UT_RULE_GRP_DTL_PK PRIMARY KEY (UT_RULE_GRP_NBR, UT_TABLE_RULE_NBR),
	 CONSTRAINT URGD_URG_FK FOREIGN KEY (UT_RULE_GRP_NBR)
	  REFERENCES UT_RULE_GRP (UT_RULE_GRP_NBR) ENABLE,
	 CONSTRAINT URGD_UTR_FK FOREIGN KEY (UT_TABLE_RULE_NBR)
	  REFERENCES UT_TABLE_RULE (UT_TABLE_RULE_NBR) ENABLE
   );


