
  CREATE TABLE UT_RULE_GRP
   (	UT_RULE_GRP_NM VARCHAR2(32),
	UT_RULE_GRP_DESCR VARCHAR2(60),
	UT_RULE_GRP_LONG_DESCR CLOB,
	UT_RULE_GRP_NBR NUMBER(18,0) NOT NULL ENABLE,
	THREAD_CNT NUMBER(3,0),
	MAX_QUERY_SEC_DFLT NUMBER(5,0),
	 CONSTRAINT UT_RULE_GRP_PK PRIMARY KEY (UT_RULE_GRP_NBR),
	 CONSTRAINT UT_RULE_GRP_UK UNIQUE (UT_RULE_GRP_NM)
   );


