
  CREATE TABLE UT_RULE_GRP_RUN
   (	UT_RULE_GRP_RUN_NBR NUMBER(18,0) NOT NULL ENABLE,
	UT_RULE_GRP_NBR NUMBER(18,0) NOT NULL ENABLE,
	UT_RUN_GRP_DESCR VARCHAR2(80),
	LAST_RUN_TM TIMESTAMP (6) NOT NULL ENABLE,
	CTRL_PT_NBR NUMBER(18,0) NOT NULL ENABLE,
	UT_PROCESS_STATUS_NBR NUMBER(18,0),
	 CONSTRAINT UT_RULE_GRP_RUN_PK PRIMARY KEY (UT_RULE_GRP_RUN_NBR),
	 CONSTRAINT URGN_URG_FK FOREIGN KEY (UT_RULE_GRP_NBR)
	  REFERENCES UT_RULE_GRP (UT_RULE_GRP_NBR) ENABLE,
	 CONSTRAINT URGR_UPS_FK FOREIGN KEY (UT_PROCESS_STATUS_NBR)
	  REFERENCES UT_PROCESS_STATUS (UT_PROCESS_STATUS_NBR) ENABLE
   );


