set echo on
  CREATE TABLE UT_SCHEMA_GRP_DTL
   (	
	UT_SCHEMA_GRP_NBR NUMBER(9),
	SCHEMA_NM VARCHAR2(30),
	 CONSTRAINT UT_SCHEMA_GRP_DTL_PK PRIMARY KEY (UT_SCHEMA_GRP_NBR, SCHEMA_NM),
	 CONSTRAINT USGD_US_FK FOREIGN KEY (SCHEMA_NM)
	  REFERENCES UT_SCHEMA (SCHEMA_NM) ENABLE,
	 CONSTRAINT USGD_USG_FK FOREIGN KEY (ut_schema_grp_nbr)
	  REFERENCES UT_SCHEMA_GRP (UT_SCHEMA_GRP_NBR) ENABLE
   );
