
  CREATE TABLE UT_TABLE_RULE (
	UT_TABLE_RULE_NBR NUMBER(9,0),
	MSG_ID VARCHAR2(16),
	SQL_TEXT CLOB,
	MSG_DESCR CLOB,
	RULE_TYPE VARCHAR2(8),
	DATA_SRC_NM_SRC VARCHAR2(20),
	DATA_SRC_NM_DEST VARCHAR2(20),
	UT_QUERY_NBR NUMBER(9,0),
	SCHEMA VARCHAR2(30) NOT NULL ENABLE,
	TABLE_NAME VARCHAR2(30) NOT NULL ENABLE,
	MAX_QUERY_SEC NUMBER(5,0) DEFAULT 30,
	SEVERE_RULE_FLG VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	SHORT_DESCR VARCHAR2(80),
	EXCEPTION_TYPE_CD VARCHAR2(1) NOT NULL ENABLE,
	UT_TABLE_RULE_NBR_EXCLUDE NUMBER(18,0),
	DISP_CD_ENUM VARCHAR2(1),
	LOG_LVL NUMBER(1,0),
	 CONSTRAINT UT_TABLE_RULE_PK PRIMARY KEY (UT_TABLE_RULE_NBR) ENABLE,
	 CONSTRAINT UT_TABLE_RULE_UK UNIQUE (MSG_ID) ENABLE,
	 CHECK ( severe_rule_flg in ('Y', 'N')) ENABLE,
	 CONSTRAINT CHECK_EXCEPTION_TYPE_CD CHECK (exception_type_cd IN ('I', 'E')) ENABLE,
	 CONSTRAINT UTR_CHECK_DISP_CD_ENUM CHECK ( DISP_CD_ENUM IN ('A', 'M', 'S')) ENABLE,
	 CONSTRAINT MAX_QUERY_SEC_CHK CHECK (max_query_sec > 1 and max_query_sec <= 120) ENABLE,
	 CONSTRAINT UTR_UDL_FK FOREIGN KEY (SCHEMA, TABLE_NAME)
	  REFERENCES UT_DATA_LOCATION (SCHEMA, TABLE_NAME) ENABLE,
	 CONSTRAINT UTR_UTR_FK FOREIGN KEY (UT_TABLE_RULE_NBR_EXCLUDE)
	  REFERENCES UT_TABLE_RULE (UT_TABLE_RULE_NBR) ENABLE,
	 CONSTRAINT UTR_UQ_FK FOREIGN KEY (UT_QUERY_NBR)
	  REFERENCES UT_QUERY (UT_QUERY_NBR) ENABLE
   );

alter table ut_table_rule add ut_area_resp_nbr number(9);

alter table ut_table_rule add constraint utr_uar_fk 
foreign key (ut_area_resp_nbr) references ut_area_resp(ut_area_resp_nbr);

