
  CREATE TABLE UT_TABLE_RULE_PRIV
   (	UT_TABLE_RULE_PRIV_NBR NUMBER(9,0) NOT NULL ENABLE,
	UT_TABLE_RULE_NBR NUMBER(9,0) NOT NULL ENABLE,
	ROLE_NBR NUMBER(9,0) NOT NULL ENABLE,
	RULE_ALLOW_FLG VARCHAR2(1) NOT NULL ENABLE,
	RULE_REJ_FLG VARCHAR2(1) NOT NULL ENABLE,
	ENTRY_USER NUMBER(9,0) NOT NULL ENABLE,
	ENTRY_TM TIMESTAMP (0) NOT NULL ENABLE,
	MOD_USER NUMBER(9,0),
	MOD_TM TIMESTAMP (0),
	 CHECK ( RULE_ALLOW_FLG IN ('Y', 'N')) ENABLE,
	 CHECK ( RULE_REJ_FLG IN ('Y', 'N')) ENABLE,
	 CONSTRAINT UT_TABLE_RULE_PRIV_PK PRIMARY KEY (UT_TABLE_RULE_PRIV_NBR) ENABLE,
	 CONSTRAINT UT_TABLE_RULE_PRIV_UK UNIQUE (UT_TABLE_RULE_NBR, ROLE_NBR) ENABLE,
	 CONSTRAINT UTRPRIV_UTR_FK FOREIGN KEY (UT_TABLE_RULE_NBR)
	  REFERENCES UT_TABLE_RULE (UT_TABLE_RULE_NBR) ENABLE,
	 CONSTRAINT UTRPRIV_UR_FK FOREIGN KEY (ROLE_NBR)
	  REFERENCES UT_ROLE (ROLE_NBR) ENABLE
   );


