
  CREATE TABLE UT_TABLE_RULE_PARM
   (	UT_TABLE_RULE_NBR NUMBER(18,0) NOT NULL ENABLE,
	PARM_NM VARCHAR2(30) NOT NULL ENABLE,
	PARM_DATA_TYPE VARCHAR2(10),
	 CONSTRAINT UT_TABLE_RULE_PARM_PK PRIMARY KEY (UT_TABLE_RULE_NBR, PARM_NM) ENABLE,
	 CONSTRAINT UTRP_UTR_FK FOREIGN KEY (UT_TABLE_RULE_NBR)
	  REFERENCES UT_TABLE_RULE (UT_TABLE_RULE_NBR) ENABLE
   );
