
  CREATE TABLE UT_TABLE_ROW_MEASURE
   (	FACT_TABLE_ID VARCHAR2(8) NOT NULL ENABLE,
	FACT_TABLE_PK NUMBER(18,0) NOT NULL ENABLE,
	MEAS_NBR NUMBER(9,0) NOT NULL ENABLE,
	MEAS NUMBER NOT NULL ENABLE
   )  ;


