
  CREATE TABLE UT_TABLE_RULE_RPT_SUM
   (	UT_TABLE_RULE_RPT_SUM_NBR NUMBER(18,0) NOT NULL ENABLE,
	UT_TABLE_RULE_NBR NUMBER(18,0) NOT NULL ENABLE,
	RPT_DESCR VARCHAR2(80) NOT NULL ENABLE,
	APEX_PAGE_NBR NUMBER(5,0) NOT NULL ENABLE,
	 CONSTRAINT UT_TABLE_RULE_RPT_SUM_PK PRIMARY KEY (UT_TABLE_RULE_RPT_SUM_NBR) ENABLE,
	 CONSTRAINT UTRRS_UTR_FK FOREIGN KEY (UT_TABLE_RULE_NBR)
	  REFERENCES UT_TABLE_RULE (UT_TABLE_RULE_NBR) ENABLE
   );


