
  CREATE TABLE UT_TABLE_ROW_MSG
   (	PRIMARY_KEY NUMBER(18,0),
	MSG VARCHAR2(64),
	UT_TABLE_RULE_NBR NUMBER(18,0) NOT NULL ENABLE,
	UT_RULE_GRP_RUN_NBR NUMBER(18,0) NOT NULL ENABLE,
	UT_USER_NBR_ALLOW NUMBER(9,0),
	DISP_CD_ENUM VARCHAR2(1),
	UT_USER_NBR_DISP NUMBER(9,0),
	 CONSTRAINT UT_TABLE_ROW_MSG_PK 
		PRIMARY KEY (UT_TABLE_RULE_NBR, UT_RULE_GRP_RUN_NBR, PRIMARY_KEY),
	 CONSTRAINT UTRM_CHECK_DISP_CD_ENUM CHECK ( DISP_CD_ENUM IN ('A', 'M', 'S')) ENABLE,
	 CONSTRAINT UTRM_URGR_FK FOREIGN KEY (UT_RULE_GRP_RUN_NBR)
	  REFERENCES UT_RULE_GRP_RUN (UT_RULE_GRP_RUN_NBR) ENABLE,
	 CONSTRAINT UTRM_UTR_FK FOREIGN KEY (UT_TABLE_RULE_NBR)
	  REFERENCES UT_TABLE_RULE (UT_TABLE_RULE_NBR) ENABLE
   );
